// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "nl",
        "default",
        "X staat aan. → X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → De temperatuur Y.",
    ),
    (
        "nl",
        "butler",
        "X staat aan. → Goed. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Goed. De temperatuur Y.",
    ),
    (
        "nl",
        "locker",
        "X staat aan. → Oké. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Oké. De temperatuur Y.",
    ),
    (
        "nl",
        "fuersorglich",
        "X staat aan. → Ik doe het meteen. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Ik doe het meteen. De temperatuur Y.",
    ),
    (
        "nl",
        "party",
        "X staat aan. → Lekker bezig. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Lekker bezig. De temperatuur Y.",
    ),
    (
        "nl",
        "grantig",
        "X staat aan. → Nou goed. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Nou goed. De temperatuur Y.",
    ),
    (
        "nl",
        "sarkastisch",
        "X staat aan. → Natuurlijk. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Natuurlijk. De temperatuur Y.",
    ),
    (
        "nl",
        "pirat",
        "X staat aan. → Aye. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Aye. De temperatuur Y.",
    ),
    (
        "nl",
        "hippie",
        "X staat aan. → Relax. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Relax. De temperatuur Y.",
    ),
    (
        "nl",
        "gollum",
        "X staat aan. → Ja. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Ja. De temperatuur Y.",
    ),
    (
        "nl",
        "jarvis",
        "X staat aan. → Natuurlijk. X staat aan.
X staat uit. → X staat uit.
De temperatuur Y. → Natuurlijk. De temperatuur Y.",
    ),
    (
        "da",
        "default",
        "X er taendt. → X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Temperaturen Y.",
    ),
    (
        "da",
        "butler",
        "X er taendt. → Godt. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Godt. Temperaturen Y.",
    ),
    (
        "da",
        "locker",
        "X er taendt. → Okay. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Okay. Temperaturen Y.",
    ),
    (
        "da",
        "fuersorglich",
        "X er taendt. → Det gor jeg med det samme. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Det gor jeg med det samme. Temperaturen Y.",
    ),
    (
        "da",
        "party",
        "X er taendt. → Sa korer vi. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Sa korer vi. Temperaturen Y.",
    ),
    (
        "da",
        "grantig",
        "X er taendt. → Na godt. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Na godt. Temperaturen Y.",
    ),
    (
        "da",
        "sarkastisch",
        "X er taendt. → Selvfolgelig. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Selvfolgelig. Temperaturen Y.",
    ),
    (
        "da",
        "pirat",
        "X er taendt. → Aye. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Aye. Temperaturen Y.",
    ),
    (
        "da",
        "hippie",
        "X er taendt. → Afslappet. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Afslappet. Temperaturen Y.",
    ),
    (
        "da",
        "gollum",
        "X er taendt. → Ja. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Ja. Temperaturen Y.",
    ),
    (
        "da",
        "jarvis",
        "X er taendt. → Selvfølgelig, sir. X er taendt.
X er slukket. → X er slukket.
Temperaturen Y. → Selvfølgelig, sir. Temperaturen Y.",
    ),
    (
        "en-GB",
        "default",
        "X is on. → X is on.
X is off. → X is off.
The temperature Y. → The temperature Y.",
    ),
    (
        "en-GB",
        "butler",
        "X is on. → Very well. X is on.
X is off. → X is off.
The temperature Y. → Very well. The temperature Y.",
    ),
    (
        "en-GB",
        "locker",
        "X is on. → Got it. X is on.
X is off. → X is off.
The temperature Y. → Got it. The temperature Y.",
    ),
    (
        "en-GB",
        "fuersorglich",
        "X is on. → Doing that now. X is on.
X is off. → X is off.
The temperature Y. → Doing that now. The temperature Y.",
    ),
    (
        "en-GB",
        "party",
        "X is on. → Let's go. X is on.
X is off. → X is off.
The temperature Y. → Let's go. The temperature Y.",
    ),
    (
        "en-GB",
        "grantig",
        "X is on. → Fine. X is on.
X is off. → X is off.
The temperature Y. → Fine. The temperature Y.",
    ),
    (
        "en-GB",
        "sarkastisch",
        "X is on. → Of course. X is on.
X is off. → X is off.
The temperature Y. → Of course. The temperature Y.",
    ),
    (
        "en-GB",
        "pirat",
        "X is on. → Aye. X is on.
X is off. → X is off.
The temperature Y. → Aye. The temperature Y.",
    ),
    (
        "en-GB",
        "hippie",
        "X is on. → All good. X is on.
X is off. → X is off.
The temperature Y. → All good. The temperature Y.",
    ),
    (
        "en-GB",
        "gollum",
        "X is on. → Yes. X is on.
X is off. → X is off.
The temperature Y. → Yes. The temperature Y.",
    ),
    (
        "en-GB",
        "jarvis",
        "X is on. → Certainly, sir. X is on.
X is off. → X is off.
The temperature Y. → Certainly, sir. The temperature Y.",
    ),
    (
        "hu",
        "default",
        "X be van kapcsolva. → X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → A homerseklet Y.",
    ),
    (
        "hu",
        "butler",
        "X be van kapcsolva. → Nagyon jol. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Nagyon jol. A homerseklet Y.",
    ),
    (
        "hu",
        "locker",
        "X be van kapcsolva. → Oké. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Oké. A homerseklet Y.",
    ),
    (
        "hu",
        "fuersorglich",
        "X be van kapcsolva. → Azonnal megcsinalom. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Azonnal megcsinalom. A homerseklet Y.",
    ),
    (
        "hu",
        "party",
        "X be van kapcsolva. → Gyerunk. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Gyerunk. A homerseklet Y.",
    ),
    (
        "hu",
        "grantig",
        "X be van kapcsolva. → Hát jo. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Hát jo. A homerseklet Y.",
    ),
    (
        "hu",
        "sarkastisch",
        "X be van kapcsolva. → Persze. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Persze. A homerseklet Y.",
    ),
    (
        "hu",
        "pirat",
        "X be van kapcsolva. → Aye. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Aye. A homerseklet Y.",
    ),
    (
        "hu",
        "hippie",
        "X be van kapcsolva. → Laza. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Laza. A homerseklet Y.",
    ),
    (
        "hu",
        "gollum",
        "X be van kapcsolva. → Igen. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Igen. A homerseklet Y.",
    ),
    (
        "hu",
        "jarvis",
        "X be van kapcsolva. → Persze, uram. X be van kapcsolva.
X ki van kapcsolva. → X ki van kapcsolva.
A homerseklet Y. → Persze, uram. A homerseklet Y.",
    ),
    (
        "sr-Latn",
        "default",
        "X je upaljen. → X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "sr-Latn",
        "butler",
        "X je upaljen. → Vrlo dobro. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Vrlo dobro. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "locker",
        "X je upaljen. → U redu. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → U redu. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "fuersorglich",
        "X je upaljen. → Odmah to radim. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Odmah to radim. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "party",
        "X je upaljen. → Idemo. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Idemo. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "grantig",
        "X je upaljen. → Dobro. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Dobro. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "sarkastisch",
        "X je upaljen. → Naravno. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Naravno. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "pirat",
        "X je upaljen. → Aye. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "hippie",
        "X je upaljen. → Opusteno. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Opusteno. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "gollum",
        "X je upaljen. → Da. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Da. Temperatura Y.",
    ),
    (
        "sr-Latn",
        "jarvis",
        "X je upaljen. → Naravno, gospodine. X je upaljen.
X je ugasen. → X je ugasen.
Temperatura Y. → Naravno, gospodine. Temperatura Y.",
    ),
    (
        "he",
        "default",
        "X דולק. → X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → הטמפרטורה Y.",
    ),
    (
        "he",
        "butler",
        "X דולק. → בסדר. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → בסדר. הטמפרטורה Y.",
    ),
    (
        "he",
        "locker",
        "X דולק. → הבנתי. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → הבנתי. הטמפרטורה Y.",
    ),
    (
        "he",
        "fuersorglich",
        "X דולק. → אני עושה את זה עכשיו. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → אני עושה את זה עכשיו. הטמפרטורה Y.",
    ),
    (
        "he",
        "party",
        "X דולק. → יאללה. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → יאללה. הטמפרטורה Y.",
    ),
    (
        "he",
        "grantig",
        "X דולק. → טוב. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → טוב. הטמפרטורה Y.",
    ),
    (
        "he",
        "sarkastisch",
        "X דולק. → ברור. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → ברור. הטמפרטורה Y.",
    ),
    (
        "he",
        "pirat",
        "X דולק. → Aye. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → Aye. הטמפרטורה Y.",
    ),
    (
        "he",
        "hippie",
        "X דולק. → בקלות. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → בקלות. הטמפרטורה Y.",
    ),
    (
        "he",
        "gollum",
        "X דולק. → כן. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → כן. הטמפרטורה Y.",
    ),
    (
        "he",
        "jarvis",
        "X דולק. → כמובן, אדוני. X דולק.
X כבוי. → X כבוי.
הטמפרטורה Y. → כמובן, אדוני. הטמפרטורה Y.",
    ),
    (
        "ja",
        "default",
        "Xはついています。 → Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → 温度Y。",
    ),
    (
        "ja",
        "butler",
        "Xはついています。 → わかりました。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → わかりました。 温度Y。",
    ),
    (
        "ja",
        "locker",
        "Xはついています。 → 了解。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → 了解。 温度Y。",
    ),
    (
        "ja",
        "fuersorglich",
        "Xはついています。 → 今やります。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → 今やります。 温度Y。",
    ),
    (
        "ja",
        "party",
        "Xはついています。 → いこう。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → いこう。 温度Y。",
    ),
    (
        "ja",
        "grantig",
        "Xはついています。 → わかった。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → わかった。 温度Y。",
    ),
    (
        "ja",
        "sarkastisch",
        "Xはついています。 → もちろん。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → もちろん。 温度Y。",
    ),
    (
        "ja",
        "pirat",
        "Xはついています。 → Aye. Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → Aye. 温度Y。",
    ),
    (
        "ja",
        "hippie",
        "Xはついています。 → のんびり。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → のんびり。 温度Y。",
    ),
    (
        "ja",
        "gollum",
        "Xはついています。 → はい。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → はい。 温度Y。",
    ),
    (
        "ja",
        "jarvis",
        "Xはついています。 → 承知しました。 Xはついています。
Xは消えています。 → Xは消えています。
温度Y。 → 承知しました。 温度Y。",
    ),
    (
        "is",
        "default",
        "X er kveikt. → X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Hitinn Y.",
    ),
    (
        "is",
        "butler",
        "X er kveikt. → Gott. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Gott. Hitinn Y.",
    ),
    (
        "is",
        "locker",
        "X er kveikt. → Skil. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Skil. Hitinn Y.",
    ),
    (
        "is",
        "fuersorglich",
        "X er kveikt. → Geri thad strax. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Geri thad strax. Hitinn Y.",
    ),
    (
        "is",
        "party",
        "X er kveikt. → Forum. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Forum. Hitinn Y.",
    ),
    (
        "is",
        "grantig",
        "X er kveikt. → Allt i lagi. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Allt i lagi. Hitinn Y.",
    ),
    (
        "is",
        "sarkastisch",
        "X er kveikt. → Audvitad. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Audvitad. Hitinn Y.",
    ),
    (
        "is",
        "pirat",
        "X er kveikt. → Aye. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Aye. Hitinn Y.",
    ),
    (
        "is",
        "hippie",
        "X er kveikt. → Rolegt. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Rolegt. Hitinn Y.",
    ),
    (
        "is",
        "gollum",
        "X er kveikt. → Ja. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Ja. Hitinn Y.",
    ),
    (
        "is",
        "jarvis",
        "X er kveikt. → Að sjálfsögðu, herra. X er kveikt.
X er slokkt. → X er slokkt.
Hitinn Y. → Að sjálfsögðu, herra. Hitinn Y.",
    ),
    (
        "ms",
        "default",
        "X hidup. → X hidup.
X mati. → X mati.
Suhu Y. → Suhu Y.",
    ),
    (
        "ms",
        "butler",
        "X hidup. → Baik. X hidup.
X mati. → X mati.
Suhu Y. → Baik. Suhu Y.",
    ),
    (
        "ms",
        "locker",
        "X hidup. → Faham. X hidup.
X mati. → X mati.
Suhu Y. → Faham. Suhu Y.",
    ),
    (
        "ms",
        "fuersorglich",
        "X hidup. → Saya buat sekarang. X hidup.
X mati. → X mati.
Suhu Y. → Saya buat sekarang. Suhu Y.",
    ),
    (
        "ms",
        "party",
        "X hidup. → Jom. X hidup.
X mati. → X mati.
Suhu Y. → Jom. Suhu Y.",
    ),
    (
        "ms",
        "grantig",
        "X hidup. → Baiklah. X hidup.
X mati. → X mati.
Suhu Y. → Baiklah. Suhu Y.",
    ),
    (
        "ms",
        "sarkastisch",
        "X hidup. → Sudah tentu. X hidup.
X mati. → X mati.
Suhu Y. → Sudah tentu. Suhu Y.",
    ),
    (
        "ms",
        "pirat",
        "X hidup. → Aye. X hidup.
X mati. → X mati.
Suhu Y. → Aye. Suhu Y.",
    ),
    (
        "ms",
        "hippie",
        "X hidup. → Santai. X hidup.
X mati. → X mati.
Suhu Y. → Santai. Suhu Y.",
    ),
    (
        "ms",
        "gollum",
        "X hidup. → Ya. X hidup.
X mati. → X mati.
Suhu Y. → Ya. Suhu Y.",
    ),
    (
        "ms",
        "jarvis",
        "X hidup. → Sudah tentu, tuan. X hidup.
X mati. → X mati.
Suhu Y. → Sudah tentu, tuan. Suhu Y.",
    ),
    (
        "kn",
        "default",
        "X ಹಚ್ಚಿದೆ. → X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "butler",
        "X ಹಚ್ಚಿದೆ. → ಚೆನ್ನಾಗಿದೆ. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಚೆನ್ನಾಗಿದೆ. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "locker",
        "X ಹಚ್ಚಿದೆ. → ತಿಳಿಯಿತು. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ತಿಳಿಯಿತು. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "fuersorglich",
        "X ಹಚ್ಚಿದೆ. → ಈಗ ಮಾಡುತ್ತೇನೆ. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಈಗ ಮಾಡುತ್ತೇನೆ. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "party",
        "X ಹಚ್ಚಿದೆ. → ಹೋಗೋಣ. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಹೋಗೋಣ. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "grantig",
        "X ಹಚ್ಚಿದೆ. → ಸರಿ. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಸರಿ. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "sarkastisch",
        "X ಹಚ್ಚಿದೆ. → ಖಂಡಿತ. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಖಂಡಿತ. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "pirat",
        "X ಹಚ್ಚಿದೆ. → Aye. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → Aye. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "hippie",
        "X ಹಚ್ಚಿದೆ. → ನಿಧಾನ. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ನಿಧಾನ. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "gollum",
        "X ಹಚ್ಚಿದೆ. → ಹೌದು. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಹೌದು. ಉಷ್ಣತೆ Y.",
    ),
    (
        "kn",
        "jarvis",
        "X ಹಚ್ಚಿದೆ. → ಹೌದು, ಸರ್. X ಹಚ್ಚಿದೆ.
X ಆರಿಸಿದೆ. → X ಆರಿಸಿದೆ.
ಉಷ್ಣತೆ Y. → ಹೌದು, ಸರ್. ಉಷ್ಣತೆ Y.",
    ),
    (
        "ne",
        "default",
        "X बल्यो। → X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → तापक्रम Y।",
    ),
    (
        "ne",
        "butler",
        "X बल्यो। → ठीक। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → ठीक। तापक्रम Y।",
    ),
    (
        "ne",
        "locker",
        "X बल्यो। → बुझेँ। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → बुझेँ। तापक्रम Y।",
    ),
    (
        "ne",
        "fuersorglich",
        "X बल्यो। → अहिले गर्छु। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → अहिले गर्छु। तापक्रम Y।",
    ),
    (
        "ne",
        "party",
        "X बल्यो। → चलाऔँ। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → चलाऔँ। तापक्रम Y।",
    ),
    (
        "ne",
        "grantig",
        "X बल्यो। → ठीक छ। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → ठीक छ। तापक्रम Y।",
    ),
    (
        "ne",
        "sarkastisch",
        "X बल्यो। → अवश्य। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → अवश्य। तापक्रम Y।",
    ),
    (
        "ne",
        "pirat",
        "X बल्यो। → Aye. X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → Aye. तापक्रम Y।",
    ),
    (
        "ne",
        "hippie",
        "X बल्यो। → शान्त। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → शान्त। तापक्रम Y।",
    ),
    (
        "ne",
        "gollum",
        "X बल्यो। → हो। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → हो। तापक्रम Y।",
    ),
    (
        "ne",
        "jarvis",
        "X बल्यो। → हो, सर। X बल्यो।
X निभ्यो। → X निभ्यो।
तापक्रम Y। → हो, सर। तापक्रम Y।",
    ),
];
