// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "it",
        "default",
        "X e acceso. → X e acceso.
X e spento. → X e spento.
La temperatura Y. → La temperatura Y.",
    ),
    (
        "it",
        "butler",
        "X e acceso. → Molto bene. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Molto bene. La temperatura Y.",
    ),
    (
        "it",
        "locker",
        "X e acceso. → Fatto. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Fatto. La temperatura Y.",
    ),
    (
        "it",
        "fuersorglich",
        "X e acceso. → Subito. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Subito. La temperatura Y.",
    ),
    (
        "it",
        "party",
        "X e acceso. → Andiamo. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Andiamo. La temperatura Y.",
    ),
    (
        "it",
        "grantig",
        "X e acceso. → Va be'. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Va be'. La temperatura Y.",
    ),
    (
        "it",
        "sarkastisch",
        "X e acceso. → Certo. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Certo. La temperatura Y.",
    ),
    (
        "it",
        "pirat",
        "X e acceso. → Aye. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Aye. La temperatura Y.",
    ),
    (
        "it",
        "hippie",
        "X e acceso. → Easy. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Easy. La temperatura Y.",
    ),
    (
        "it",
        "gollum",
        "X e acceso. → Si. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Si. La temperatura Y.",
    ),
    (
        "it",
        "jarvis",
        "X e acceso. → Certo, signore. X e acceso.
X e spento. → X e spento.
La temperatura Y. → Certo, signore. La temperatura Y.",
    ),
    (
        "sv",
        "default",
        "X är på. → X är på.
X är av. → X är av.
Temperaturen Y. → Temperaturen Y.",
    ),
    (
        "sv",
        "butler",
        "X är på. → Mycket väl. X är på.
X är av. → X är av.
Temperaturen Y. → Mycket väl. Temperaturen Y.",
    ),
    (
        "sv",
        "locker",
        "X är på. → Okej. X är på.
X är av. → X är av.
Temperaturen Y. → Okej. Temperaturen Y.",
    ),
    (
        "sv",
        "fuersorglich",
        "X är på. → Gör det genast. X är på.
X är av. → X är av.
Temperaturen Y. → Gör det genast. Temperaturen Y.",
    ),
    (
        "sv",
        "party",
        "X är på. → Nu kör vi. X är på.
X är av. → X är av.
Temperaturen Y. → Nu kör vi. Temperaturen Y.",
    ),
    (
        "sv",
        "grantig",
        "X är på. → Nåväl. X är på.
X är av. → X är av.
Temperaturen Y. → Nåväl. Temperaturen Y.",
    ),
    (
        "sv",
        "sarkastisch",
        "X är på. → Javisst. X är på.
X är av. → X är av.
Temperaturen Y. → Javisst. Temperaturen Y.",
    ),
    (
        "sv",
        "pirat",
        "X är på. → Aye. X är på.
X är av. → X är av.
Temperaturen Y. → Aye. Temperaturen Y.",
    ),
    (
        "sv",
        "hippie",
        "X är på. → Lugnt. X är på.
X är av. → X är av.
Temperaturen Y. → Lugnt. Temperaturen Y.",
    ),
    (
        "sv",
        "gollum",
        "X är på. → Ja. X är på.
X är av. → X är av.
Temperaturen Y. → Ja. Temperaturen Y.",
    ),
    (
        "sv",
        "jarvis",
        "X är på. → Javisst, sir. X är på.
X är av. → X är av.
Temperaturen Y. → Javisst, sir. Temperaturen Y.",
    ),
    (
        "af",
        "default",
        "X is aan. → X is aan.
X is af. → X is af.
Die temperatuur Y. → Die temperatuur Y.",
    ),
    (
        "af",
        "butler",
        "X is aan. → Baie goed. X is aan.
X is af. → X is af.
Die temperatuur Y. → Baie goed. Die temperatuur Y.",
    ),
    (
        "af",
        "locker",
        "X is aan. → Reg. X is aan.
X is af. → X is af.
Die temperatuur Y. → Reg. Die temperatuur Y.",
    ),
    (
        "af",
        "fuersorglich",
        "X is aan. → Ek doen dit nou. X is aan.
X is af. → X is af.
Die temperatuur Y. → Ek doen dit nou. Die temperatuur Y.",
    ),
    (
        "af",
        "party",
        "X is aan. → Kom ons gaan. X is aan.
X is af. → X is af.
Die temperatuur Y. → Kom ons gaan. Die temperatuur Y.",
    ),
    (
        "af",
        "grantig",
        "X is aan. → Goed. X is aan.
X is af. → X is af.
Die temperatuur Y. → Goed. Die temperatuur Y.",
    ),
    (
        "af",
        "sarkastisch",
        "X is aan. → Natuurlik. X is aan.
X is af. → X is af.
Die temperatuur Y. → Natuurlik. Die temperatuur Y.",
    ),
    (
        "af",
        "pirat",
        "X is aan. → Aye. X is aan.
X is af. → X is af.
Die temperatuur Y. → Aye. Die temperatuur Y.",
    ),
    (
        "af",
        "hippie",
        "X is aan. → Easy. X is aan.
X is af. → X is af.
Die temperatuur Y. → Easy. Die temperatuur Y.",
    ),
    (
        "af",
        "gollum",
        "X is aan. → Ja. X is aan.
X is af. → X is af.
Die temperatuur Y. → Ja. Die temperatuur Y.",
    ),
    (
        "af",
        "jarvis",
        "X is aan. → Natuurlik, meneer. X is aan.
X is af. → X is af.
Die temperatuur Y. → Natuurlik, meneer. Die temperatuur Y.",
    ),
    (
        "sl",
        "default",
        "X je prizgan. → X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "sl",
        "butler",
        "X je prizgan. → Zelo dobro. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Zelo dobro. Temperatura Y.",
    ),
    (
        "sl",
        "locker",
        "X je prizgan. → V redu. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → V redu. Temperatura Y.",
    ),
    (
        "sl",
        "fuersorglich",
        "X je prizgan. → Naredim takoj. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Naredim takoj. Temperatura Y.",
    ),
    (
        "sl",
        "party",
        "X je prizgan. → Gremo. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Gremo. Temperatura Y.",
    ),
    (
        "sl",
        "grantig",
        "X je prizgan. → No dobro. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → No dobro. Temperatura Y.",
    ),
    (
        "sl",
        "sarkastisch",
        "X je prizgan. → Seveda. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Seveda. Temperatura Y.",
    ),
    (
        "sl",
        "pirat",
        "X je prizgan. → Aye. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "sl",
        "hippie",
        "X je prizgan. → Sproščeno. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Sproščeno. Temperatura Y.",
    ),
    (
        "sl",
        "gollum",
        "X je prizgan. → Da. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Da. Temperatura Y.",
    ),
    (
        "sl",
        "jarvis",
        "X je prizgan. → Seveda, gospod. X je prizgan.
X je ugasnjen. → X je ugasnjen.
Temperatura Y. → Seveda, gospod. Temperatura Y.",
    ),
    (
        "zh-CN",
        "default",
        "X开了。 → X开了。
X关了。 → X关了。
温度Y。 → 温度Y。",
    ),
    (
        "zh-CN",
        "butler",
        "X开了。 → 好的。 X开了。
X关了。 → X关了。
温度Y。 → 好的。 温度Y。",
    ),
    (
        "zh-CN",
        "locker",
        "X开了。 → 行。 X开了。
X关了。 → X关了。
温度Y。 → 行。 温度Y。",
    ),
    (
        "zh-CN",
        "fuersorglich",
        "X开了。 → 马上就做。 X开了。
X关了。 → X关了。
温度Y。 → 马上就做。 温度Y。",
    ),
    (
        "zh-CN",
        "party",
        "X开了。 → 走起。 X开了。
X关了。 → X关了。
温度Y。 → 走起。 温度Y。",
    ),
    (
        "zh-CN",
        "grantig",
        "X开了。 → 行吧。 X开了。
X关了。 → X关了。
温度Y。 → 行吧。 温度Y。",
    ),
    (
        "zh-CN",
        "sarkastisch",
        "X开了。 → 当然。 X开了。
X关了。 → X关了。
温度Y。 → 当然。 温度Y。",
    ),
    (
        "zh-CN",
        "pirat",
        "X开了。 → Aye. X开了。
X关了。 → X关了。
温度Y。 → Aye. 温度Y。",
    ),
    (
        "zh-CN",
        "hippie",
        "X开了。 → 放松。 X开了。
X关了。 → X关了。
温度Y。 → 放松。 温度Y。",
    ),
    (
        "zh-CN",
        "gollum",
        "X开了。 → 是。 X开了。
X关了。 → X关了。
温度Y。 → 是。 温度Y。",
    ),
    (
        "zh-CN",
        "jarvis",
        "X开了。 → 当然，先生。 X开了。
X关了。 → X关了。
温度Y。 → 当然，先生。 温度Y。",
    ),
    (
        "ur",
        "default",
        "X چالو ہے۔ → X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → درجہ حرارت Y۔",
    ),
    (
        "ur",
        "butler",
        "X چالو ہے۔ → ٹھیک ہے۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ٹھیک ہے۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "locker",
        "X چالو ہے۔ → سمجھ گیا۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → سمجھ گیا۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "fuersorglich",
        "X چالو ہے۔ → ابھی کرتا ہوں۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ابھی کرتا ہوں۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "party",
        "X چالو ہے۔ → چلو۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → چلو۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "grantig",
        "X چالو ہے۔ → ہاں جی۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ہاں جی۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "sarkastisch",
        "X چالو ہے۔ → یقینا۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → یقینا۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "pirat",
        "X چالو ہے۔ → Aye. X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → Aye. درجہ حرارت Y۔",
    ),
    (
        "ur",
        "hippie",
        "X چالو ہے۔ → آرام سے۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → آرام سے۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "gollum",
        "X چالو ہے۔ → ہاں۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → ہاں۔ درجہ حرارت Y۔",
    ),
    (
        "ur",
        "jarvis",
        "X چالو ہے۔ → جی ہاں، سر۔ X چالو ہے۔
X بند ہے۔ → X بند ہے۔
درجہ حرارت Y۔ → جی ہاں، سر۔ درجہ حرارت Y۔",
    ),
    (
        "et",
        "default",
        "X on sees. → X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Temperatuur Y.",
    ),
    (
        "et",
        "butler",
        "X on sees. → Hasti. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Hasti. Temperatuur Y.",
    ),
    (
        "et",
        "locker",
        "X on sees. → Selge. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Selge. Temperatuur Y.",
    ),
    (
        "et",
        "fuersorglich",
        "X on sees. → Teen kohe. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Teen kohe. Temperatuur Y.",
    ),
    (
        "et",
        "party",
        "X on sees. → Laks. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Laks. Temperatuur Y.",
    ),
    (
        "et",
        "grantig",
        "X on sees. → Olgu. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Olgu. Temperatuur Y.",
    ),
    (
        "et",
        "sarkastisch",
        "X on sees. → Muidugi. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Muidugi. Temperatuur Y.",
    ),
    (
        "et",
        "pirat",
        "X on sees. → Aye. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Aye. Temperatuur Y.",
    ),
    (
        "et",
        "hippie",
        "X on sees. → Rahulikult. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Rahulikult. Temperatuur Y.",
    ),
    (
        "et",
        "gollum",
        "X on sees. → Jah. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Jah. Temperatuur Y.",
    ),
    (
        "et",
        "jarvis",
        "X on sees. → Muidugi, härra. X on sees.
X on valjas. → X on valjas.
Temperatuur Y. → Muidugi, härra. Temperatuur Y.",
    ),
    (
        "kw",
        "default",
        "X yw enowys. → X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → An tempredh Y.",
    ),
    (
        "kw",
        "butler",
        "X yw enowys. → Da lowr. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Da lowr. An tempredh Y.",
    ),
    (
        "kw",
        "locker",
        "X yw enowys. → Komprenys. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Komprenys. An tempredh Y.",
    ),
    (
        "kw",
        "fuersorglich",
        "X yw enowys. → Y hwrav henna lemmyn. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Y hwrav henna lemmyn. An tempredh Y.",
    ),
    (
        "kw",
        "party",
        "X yw enowys. → Deun yn-rag. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Deun yn-rag. An tempredh Y.",
    ),
    (
        "kw",
        "grantig",
        "X yw enowys. → Da. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Da. An tempredh Y.",
    ),
    (
        "kw",
        "sarkastisch",
        "X yw enowys. → Yn sur. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Yn sur. An tempredh Y.",
    ),
    (
        "kw",
        "pirat",
        "X yw enowys. → Aye. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Aye. An tempredh Y.",
    ),
    (
        "kw",
        "hippie",
        "X yw enowys. → Esbos. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Esbos. An tempredh Y.",
    ),
    (
        "kw",
        "gollum",
        "X yw enowys. → Ya. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Ya. An tempredh Y.",
    ),
    (
        "kw",
        "jarvis",
        "X yw enowys. → Yn sur, syrra. X yw enowys.
X yw difygys. → X yw difygys.
An tempredh Y. → Yn sur, syrra. An tempredh Y.",
    ),
    (
        "vi",
        "default",
        "X dang bat. → X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Nhiet do Y.",
    ),
    (
        "vi",
        "butler",
        "X dang bat. → Tot. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Tot. Nhiet do Y.",
    ),
    (
        "vi",
        "locker",
        "X dang bat. → Hieu. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Hieu. Nhiet do Y.",
    ),
    (
        "vi",
        "fuersorglich",
        "X dang bat. → Toi lam ngay. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Toi lam ngay. Nhiet do Y.",
    ),
    (
        "vi",
        "party",
        "X dang bat. → Di nao. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Di nao. Nhiet do Y.",
    ),
    (
        "vi",
        "grantig",
        "X dang bat. → Thoi duoc. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Thoi duoc. Nhiet do Y.",
    ),
    (
        "vi",
        "sarkastisch",
        "X dang bat. → Duong nhien. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Duong nhien. Nhiet do Y.",
    ),
    (
        "vi",
        "pirat",
        "X dang bat. → Aye. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Aye. Nhiet do Y.",
    ),
    (
        "vi",
        "hippie",
        "X dang bat. → De. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → De. Nhiet do Y.",
    ),
    (
        "vi",
        "gollum",
        "X dang bat. → Co. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Co. Nhiet do Y.",
    ),
    (
        "vi",
        "jarvis",
        "X dang bat. → Dạ, thưa ông. X dang bat.
X dang tat. → X dang tat.
Nhiet do Y. → Dạ, thưa ông. Nhiet do Y.",
    ),
    (
        "mr",
        "default",
        "X चालू आहे. → X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → तापमान Y.",
    ),
    (
        "mr",
        "butler",
        "X चालू आहे. → ठीक. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → ठीक. तापमान Y.",
    ),
    (
        "mr",
        "locker",
        "X चालू आहे. → कळाले. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → कळाले. तापमान Y.",
    ),
    (
        "mr",
        "fuersorglich",
        "X चालू आहे. → आता करतो. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → आता करतो. तापमान Y.",
    ),
    (
        "mr",
        "party",
        "X चालू आहे. → चला. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → चला. तापमान Y.",
    ),
    (
        "mr",
        "grantig",
        "X चालू आहे. → ठीक आहे. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → ठीक आहे. तापमान Y.",
    ),
    (
        "mr",
        "sarkastisch",
        "X चालू आहे. → नक्कीच. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → नक्कीच. तापमान Y.",
    ),
    (
        "mr",
        "pirat",
        "X चालू आहे. → Aye. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → Aye. तापमान Y.",
    ),
    (
        "mr",
        "hippie",
        "X चालू आहे. → शांत. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → शांत. तापमान Y.",
    ),
    (
        "mr",
        "gollum",
        "X चालू आहे. → हो. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → हो. तापमान Y.",
    ),
    (
        "mr",
        "jarvis",
        "X चालू आहे. → हो, सर. X चालू आहे.
X बंद आहे. → X बंद आहे.
तापमान Y. → हो, सर. तापमान Y.",
    ),
    (
        "ka",
        "default",
        "X ჩართულია. → X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → ტემპერატურა Y.",
    ),
    (
        "ka",
        "butler",
        "X ჩართულია. → კარგი. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → კარგი. ტემპერატურა Y.",
    ),
    (
        "ka",
        "locker",
        "X ჩართულია. → გავიგე. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → გავიგე. ტემპერატურა Y.",
    ),
    (
        "ka",
        "fuersorglich",
        "X ჩართულია. → ახლა გავაკეთებ. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → ახლა გავაკეთებ. ტემპერატურა Y.",
    ),
    (
        "ka",
        "party",
        "X ჩართულია. → წავიდეთ. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → წავიდეთ. ტემპერატურა Y.",
    ),
    (
        "ka",
        "grantig",
        "X ჩართულია. → კარგი. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → კარგი. ტემპერატურა Y.",
    ),
    (
        "ka",
        "sarkastisch",
        "X ჩართულია. → რა თქმა უნდა. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → რა თქმა უნდა. ტემპერატურა Y.",
    ),
    (
        "ka",
        "pirat",
        "X ჩართულია. → Aye. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → Aye. ტემპერატურა Y.",
    ),
    (
        "ka",
        "hippie",
        "X ჩართულია. → მშვიდად. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → მშვიდად. ტემპერატურა Y.",
    ),
    (
        "ka",
        "gollum",
        "X ჩართულია. → დიახ. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → დიახ. ტემპერატურა Y.",
    ),
    (
        "ka",
        "jarvis",
        "X ჩართულია. → რა თქმა უნდა, ბატონო. X ჩართულია.
X გამორთულია. → X გამორთულია.
ტემპერატურა Y. → რა თქმა უნდა, ბატონო. ტემპერატურა Y.",
    ),
];
