// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "ca",
        "default",
        "X esta encès. → X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → La temperatura Y.",
    ),
    (
        "ca",
        "butler",
        "X esta encès. → Molt be. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Molt be. La temperatura Y.",
    ),
    (
        "ca",
        "locker",
        "X esta encès. → Fet. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Fet. La temperatura Y.",
    ),
    (
        "ca",
        "fuersorglich",
        "X esta encès. → Ara mateix. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Ara mateix. La temperatura Y.",
    ),
    (
        "ca",
        "party",
        "X esta encès. → Som-hi. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Som-hi. La temperatura Y.",
    ),
    (
        "ca",
        "grantig",
        "X esta encès. → Be. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Be. La temperatura Y.",
    ),
    (
        "ca",
        "sarkastisch",
        "X esta encès. → Esclar. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Esclar. La temperatura Y.",
    ),
    (
        "ca",
        "pirat",
        "X esta encès. → Aye. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Aye. La temperatura Y.",
    ),
    (
        "ca",
        "hippie",
        "X esta encès. → Tranqui. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Tranqui. La temperatura Y.",
    ),
    (
        "ca",
        "gollum",
        "X esta encès. → Si. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → Si. La temperatura Y.",
    ),
    (
        "ca",
        "jarvis",
        "X esta encès. → És clar, senyor. X esta encès.
X esta apagat. → X esta apagat.
La temperatura Y. → És clar, senyor. La temperatura Y.",
    ),
    (
        "de-CH",
        "default",
        "X isch aa. → X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → D Temperatur Y.",
    ),
    (
        "de-CH",
        "butler",
        "X isch aa. → Guet. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Guet. D Temperatur Y.",
    ),
    (
        "de-CH",
        "locker",
        "X isch aa. → Passt. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Passt. D Temperatur Y.",
    ),
    (
        "de-CH",
        "fuersorglich",
        "X isch aa. → Mach i gli. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Mach i gli. D Temperatur Y.",
    ),
    (
        "de-CH",
        "party",
        "X isch aa. → Lauft. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Lauft. D Temperatur Y.",
    ),
    (
        "de-CH",
        "grantig",
        "X isch aa. → Scho guet. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Scho guet. D Temperatur Y.",
    ),
    (
        "de-CH",
        "sarkastisch",
        "X isch aa. → Na klar. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Na klar. D Temperatur Y.",
    ),
    (
        "de-CH",
        "pirat",
        "X isch aa. → Aye. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Aye. D Temperatur Y.",
    ),
    (
        "de-CH",
        "hippie",
        "X isch aa. → Easy. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Easy. D Temperatur Y.",
    ),
    (
        "de-CH",
        "gollum",
        "X isch aa. → Ja. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Ja. D Temperatur Y.",
    ),
    (
        "de-CH",
        "jarvis",
        "X isch aa. → Natürlich, Sir. X isch aa.
X isch uus. → X isch uus.
D Temperatur Y. → Natürlich, Sir. D Temperatur Y.",
    ),
    (
        "sk",
        "default",
        "X je zapnute. → X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Teplota Y.",
    ),
    (
        "sk",
        "butler",
        "X je zapnute. → Velmi dobre. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Velmi dobre. Teplota Y.",
    ),
    (
        "sk",
        "locker",
        "X je zapnute. → Jasne. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Jasne. Teplota Y.",
    ),
    (
        "sk",
        "fuersorglich",
        "X je zapnute. → Hned to spravim. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Hned to spravim. Teplota Y.",
    ),
    (
        "sk",
        "party",
        "X je zapnute. → Ideme. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Ideme. Teplota Y.",
    ),
    (
        "sk",
        "grantig",
        "X je zapnute. → No dobre. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → No dobre. Teplota Y.",
    ),
    (
        "sk",
        "sarkastisch",
        "X je zapnute. → Samozrejme. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Samozrejme. Teplota Y.",
    ),
    (
        "sk",
        "pirat",
        "X je zapnute. → Aye. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Aye. Teplota Y.",
    ),
    (
        "sk",
        "hippie",
        "X je zapnute. → Pohoda. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Pohoda. Teplota Y.",
    ),
    (
        "sk",
        "gollum",
        "X je zapnute. → Ano. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Ano. Teplota Y.",
    ),
    (
        "sk",
        "jarvis",
        "X je zapnute. → Samozrejme, pán. X je zapnute.
X je vypnute. → X je vypnute.
Teplota Y. → Samozrejme, pán. Teplota Y.",
    ),
    (
        "el",
        "default",
        "X ειναι ανοιχτο. → X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Η θερμοκρασια Y.",
    ),
    (
        "el",
        "butler",
        "X ειναι ανοιχτο. → Πολυ καλα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Πολυ καλα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "locker",
        "X ειναι ανοιχτο. → Ενταξει. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Ενταξει. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "fuersorglich",
        "X ειναι ανοιχτο. → Το κανω αμεσως. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Το κανω αμεσως. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "party",
        "X ειναι ανοιχτο. → Πάμε. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Πάμε. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "grantig",
        "X ειναι ανοιχτο. → Καλα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Καλα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "sarkastisch",
        "X ειναι ανοιχτο. → Φυσικα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Φυσικα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "pirat",
        "X ειναι ανοιχτο. → Aye. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Aye. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "hippie",
        "X ειναι ανοιχτο. → Χαλαρα. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Χαλαρα. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "gollum",
        "X ειναι ανοιχτο. → Ναι. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Ναι. Η θερμοκρασια Y.",
    ),
    (
        "el",
        "jarvis",
        "X ειναι ανοιχτο. → Βεβαίως, κύριε. X ειναι ανοιχτο.
X ειναι κλειστο. → X ειναι κλειστο.
Η θερμοκρασια Y. → Βεβαίως, κύριε. Η θερμοκρασια Y.",
    ),
    (
        "zh-HK",
        "default",
        "X開咗。 → X開咗。
X關咗。 → X關咗。
溫度Y。 → 溫度Y。",
    ),
    (
        "zh-HK",
        "butler",
        "X開咗。 → 好呀。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 好呀。 溫度Y。",
    ),
    (
        "zh-HK",
        "locker",
        "X開咗。 → 得。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 得。 溫度Y。",
    ),
    (
        "zh-HK",
        "fuersorglich",
        "X開咗。 → 而家就做。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 而家就做。 溫度Y。",
    ),
    (
        "zh-HK",
        "party",
        "X開咗。 → 嚟啦。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 嚟啦。 溫度Y。",
    ),
    (
        "zh-HK",
        "grantig",
        "X開咗。 → 算啦。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 算啦。 溫度Y。",
    ),
    (
        "zh-HK",
        "sarkastisch",
        "X開咗。 → 當然啦。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 當然啦。 溫度Y。",
    ),
    (
        "zh-HK",
        "pirat",
        "X開咗。 → Aye. X開咗。
X關咗。 → X關咗。
溫度Y。 → Aye. 溫度Y。",
    ),
    (
        "zh-HK",
        "hippie",
        "X開咗。 → 放鬆啲。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 放鬆啲。 溫度Y。",
    ),
    (
        "zh-HK",
        "gollum",
        "X開咗。 → 係。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 係。 溫度Y。",
    ),
    (
        "zh-HK",
        "jarvis",
        "X開咗。 → 當然，先生。 X開咗。
X關咗。 → X關咗。
溫度Y。 → 當然，先生。 溫度Y。",
    ),
    (
        "th",
        "default",
        "X เปิดแล้ว. → X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → อุณหภูมิ Y.",
    ),
    (
        "th",
        "butler",
        "X เปิดแล้ว. → ได้เลย. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ได้เลย. อุณหภูมิ Y.",
    ),
    (
        "th",
        "locker",
        "X เปิดแล้ว. → โอเค. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → โอเค. อุณหภูมิ Y.",
    ),
    (
        "th",
        "fuersorglich",
        "X เปิดแล้ว. → ทำให้เลย. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ทำให้เลย. อุณหภูมิ Y.",
    ),
    (
        "th",
        "party",
        "X เปิดแล้ว. → ไปเลย. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ไปเลย. อุณหภูมิ Y.",
    ),
    (
        "th",
        "grantig",
        "X เปิดแล้ว. → ก็ได้. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ก็ได้. อุณหภูมิ Y.",
    ),
    (
        "th",
        "sarkastisch",
        "X เปิดแล้ว. → แน่นอน. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → แน่นอน. อุณหภูมิ Y.",
    ),
    (
        "th",
        "pirat",
        "X เปิดแล้ว. → Aye. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → Aye. อุณหภูมิ Y.",
    ),
    (
        "th",
        "hippie",
        "X เปิดแล้ว. → สบายๆ. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → สบายๆ. อุณหภูมิ Y.",
    ),
    (
        "th",
        "gollum",
        "X เปิดแล้ว. → ใช่. X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ใช่. อุณหภูมิ Y.",
    ),
    (
        "th",
        "jarvis",
        "X เปิดแล้ว. → ครับท่าน X เปิดแล้ว.
X ปิดแล้ว. → X ปิดแล้ว.
อุณหภูมิ Y. → ครับท่าน อุณหภูมิ Y.",
    ),
    (
        "ga",
        "default",
        "Ta X ar siul. → Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → An teocht Y.",
    ),
    (
        "ga",
        "butler",
        "Ta X ar siul. → Go maith. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Go maith. An teocht Y.",
    ),
    (
        "ga",
        "locker",
        "Ta X ar siul. → Faighte. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Faighte. An teocht Y.",
    ),
    (
        "ga",
        "fuersorglich",
        "Ta X ar siul. → Deanaim e anois. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Deanaim e anois. An teocht Y.",
    ),
    (
        "ga",
        "party",
        "Ta X ar siul. → Ar aghaidh linn. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ar aghaidh linn. An teocht Y.",
    ),
    (
        "ga",
        "grantig",
        "Ta X ar siul. → Ceart go leor. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ceart go leor. An teocht Y.",
    ),
    (
        "ga",
        "sarkastisch",
        "Ta X ar siul. → Ar ndoigh. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ar ndoigh. An teocht Y.",
    ),
    (
        "ga",
        "pirat",
        "Ta X ar siul. → Aye. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Aye. An teocht Y.",
    ),
    (
        "ga",
        "hippie",
        "Ta X ar siul. → Easca. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Easca. An teocht Y.",
    ),
    (
        "ga",
        "gollum",
        "Ta X ar siul. → Ta. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ta. An teocht Y.",
    ),
    (
        "ga",
        "jarvis",
        "Ta X ar siul. → Ar ndóigh, a dhuine uasail. Ta X ar siul.
Ta X muchta. → Ta X muchta.
An teocht Y. → Ar ndóigh, a dhuine uasail. An teocht Y.",
    ),
    (
        "lv",
        "default",
        "X ir ieslegts. → X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "lv",
        "butler",
        "X ir ieslegts. → Labi. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Labi. Temperatura Y.",
    ),
    (
        "lv",
        "locker",
        "X ir ieslegts. → Skaidrs. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Skaidrs. Temperatura Y.",
    ),
    (
        "lv",
        "fuersorglich",
        "X ir ieslegts. → Darisu tulit. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Darisu tulit. Temperatura Y.",
    ),
    (
        "lv",
        "party",
        "X ir ieslegts. → Ejam. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Ejam. Temperatura Y.",
    ),
    (
        "lv",
        "grantig",
        "X ir ieslegts. → Labi. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Labi. Temperatura Y.",
    ),
    (
        "lv",
        "sarkastisch",
        "X ir ieslegts. → Protams. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Protams. Temperatura Y.",
    ),
    (
        "lv",
        "pirat",
        "X ir ieslegts. → Aye. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "lv",
        "hippie",
        "X ir ieslegts. → Mierigi. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Mierigi. Temperatura Y.",
    ),
    (
        "lv",
        "gollum",
        "X ir ieslegts. → Ja. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Ja. Temperatura Y.",
    ),
    (
        "lv",
        "jarvis",
        "X ir ieslegts. → Protams, kungs. X ir ieslegts.
X ir izslegts. → X ir izslegts.
Temperatura Y. → Protams, kungs. Temperatura Y.",
    ),
    (
        "bn",
        "default",
        "X জ্বলছে। → X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → তাপমাত্রা Y।",
    ),
    (
        "bn",
        "butler",
        "X জ্বলছে। → ভালো। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → ভালো। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "locker",
        "X জ্বলছে। → বুঝেছি। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → বুঝেছি। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "fuersorglich",
        "X জ্বলছে। → এখন করছি। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → এখন করছি। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "party",
        "X জ্বলছে। → চলো। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → চলো। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "grantig",
        "X জ্বলছে। → ঠিক। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → ঠিক। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "sarkastisch",
        "X জ্বলছে। → অবশ্যই। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → অবশ্যই। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "pirat",
        "X জ্বলছে। → Aye. X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → Aye. তাপমাত্রা Y।",
    ),
    (
        "bn",
        "hippie",
        "X জ্বলছে। → আরাম। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → আরাম। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "gollum",
        "X জ্বলছে। → হ্যাঁ। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → হ্যাঁ। তাপমাত্রা Y।",
    ),
    (
        "bn",
        "jarvis",
        "X জ্বলছে। → জি হ্যাঁ, স্যার। X জ্বলছে।
X নিভানো। → X নিভানো।
তাপমাত্রা Y। → জি হ্যাঁ, স্যার। তাপমাত্রা Y।",
    ),
    (
        "te",
        "default",
        "X వెలిగింది. → X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "butler",
        "X వెలిగింది. → బాగుంది. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → బాగుంది. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "locker",
        "X వెలిగింది. → అర్థమైంది. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → అర్థమైంది. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "fuersorglich",
        "X వెలిగింది. → ఇప్పుడు చేస్తున్నాను. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → ఇప్పుడు చేస్తున్నాను. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "party",
        "X వెలిగింది. → పోదాం. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → పోదాం. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "grantig",
        "X వెలిగింది. → సరే. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → సరే. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "sarkastisch",
        "X వెలిగింది. → కచ్చితం. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → కచ్చితం. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "pirat",
        "X వెలిగింది. → Aye. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → Aye. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "hippie",
        "X వెలిగింది. → ప్రశాంతం. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → ప్రశాంతం. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "gollum",
        "X వెలిగింది. → అవును. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → అవును. ఉష్ణోగ్రత Y.",
    ),
    (
        "te",
        "jarvis",
        "X వెలిగింది. → అవును, సర్. X వెలిగింది.
X ఆరిపోయింది. → X ఆరిపోయింది.
ఉష్ణోగ్రత Y. → అవును, సర్. ఉష్ణోగ్రత Y.",
    ),
];
