// @generated by scripts/lang_packs. DO NOT EDIT.
pub(super) const ROWS: &[(&str, &str, &str)] = &[
    (
        "fr",
        "default",
        "X est allume. → X est allume.
X est eteint. → X est eteint.
La temperature Y. → La temperature Y.",
    ),
    (
        "fr",
        "butler",
        "X est allume. → Tres bien. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Tres bien. La temperature Y.",
    ),
    (
        "fr",
        "locker",
        "X est allume. → C'est bon. X est allume.
X est eteint. → X est eteint.
La temperature Y. → C'est bon. La temperature Y.",
    ),
    (
        "fr",
        "fuersorglich",
        "X est allume. → Je m'en occupe. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Je m'en occupe. La temperature Y.",
    ),
    (
        "fr",
        "party",
        "X est allume. → C'est parti. X est allume.
X est eteint. → X est eteint.
La temperature Y. → C'est parti. La temperature Y.",
    ),
    (
        "fr",
        "grantig",
        "X est allume. → Bon. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Bon. La temperature Y.",
    ),
    (
        "fr",
        "sarkastisch",
        "X est allume. → Evidemment. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Evidemment. La temperature Y.",
    ),
    (
        "fr",
        "pirat",
        "X est allume. → Aye. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Aye. La temperature Y.",
    ),
    (
        "fr",
        "hippie",
        "X est allume. → Cool. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Cool. La temperature Y.",
    ),
    (
        "fr",
        "gollum",
        "X est allume. → Oui. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Oui. La temperature Y.",
    ),
    (
        "fr",
        "jarvis",
        "X est allume. → Evidemment. X est allume.
X est eteint. → X est eteint.
La temperature Y. → Evidemment. La temperature Y.",
    ),
    (
        "ro",
        "default",
        "X este aprins. → X este aprins.
X este stins. → X este stins.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "ro",
        "butler",
        "X este aprins. → Foarte bine. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Foarte bine. Temperatura Y.",
    ),
    (
        "ro",
        "locker",
        "X este aprins. → Gata. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Gata. Temperatura Y.",
    ),
    (
        "ro",
        "fuersorglich",
        "X este aprins. → Imediat. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Imediat. Temperatura Y.",
    ),
    (
        "ro",
        "party",
        "X este aprins. → Hai. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Hai. Temperatura Y.",
    ),
    (
        "ro",
        "grantig",
        "X este aprins. → Bine. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Bine. Temperatura Y.",
    ),
    (
        "ro",
        "sarkastisch",
        "X este aprins. → Sigur. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Sigur. Temperatura Y.",
    ),
    (
        "ro",
        "pirat",
        "X este aprins. → Aye. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "ro",
        "hippie",
        "X este aprins. → Relax. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Relax. Temperatura Y.",
    ),
    (
        "ro",
        "gollum",
        "X este aprins. → Da. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Da. Temperatura Y.",
    ),
    (
        "ro",
        "jarvis",
        "X este aprins. → Sigur, domnule. X este aprins.
X este stins. → X este stins.
Temperatura Y. → Sigur, domnule. Temperatura Y.",
    ),
    (
        "de-AT",
        "default",
        "X is an. → X is an.
X is aus. → X is aus.
Die Temperatur Y. → Die Temperatur Y.",
    ),
    (
        "de-AT",
        "butler",
        "X is an. → Sehr wohl. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Sehr wohl. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "locker",
        "X is an. → Passt. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Passt. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "fuersorglich",
        "X is an. → Mach i gleich. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Mach i gleich. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "party",
        "X is an. → Lauft. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Lauft. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "grantig",
        "X is an. → Schon gut. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Schon gut. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "sarkastisch",
        "X is an. → Na klar. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Na klar. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "pirat",
        "X is an. → Aye. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Aye. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "hippie",
        "X is an. → Alles easy. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Alles easy. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "gollum",
        "X is an. → Ja. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Ja. Die Temperatur Y.",
    ),
    (
        "de-AT",
        "jarvis",
        "X is an. → Natürlich, Sir. X is an.
X is aus. → X is aus.
Die Temperatur Y. → Natürlich, Sir. Die Temperatur Y.",
    ),
    (
        "pl",
        "default",
        "X jest wlaczone. → X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Temperatura Y.",
    ),
    (
        "pl",
        "butler",
        "X jest wlaczone. → Bardzo dobrze. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Bardzo dobrze. Temperatura Y.",
    ),
    (
        "pl",
        "locker",
        "X jest wlaczone. → Jasne. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Jasne. Temperatura Y.",
    ),
    (
        "pl",
        "fuersorglich",
        "X jest wlaczone. → Zrobie to od razu. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Zrobie to od razu. Temperatura Y.",
    ),
    (
        "pl",
        "party",
        "X jest wlaczone. → Jedziemy. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Jedziemy. Temperatura Y.",
    ),
    (
        "pl",
        "grantig",
        "X jest wlaczone. → No dobra. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → No dobra. Temperatura Y.",
    ),
    (
        "pl",
        "sarkastisch",
        "X jest wlaczone. → Oczywiscie. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Oczywiscie. Temperatura Y.",
    ),
    (
        "pl",
        "pirat",
        "X jest wlaczone. → Aye. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Aye. Temperatura Y.",
    ),
    (
        "pl",
        "hippie",
        "X jest wlaczone. → Spoko. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Spoko. Temperatura Y.",
    ),
    (
        "pl",
        "gollum",
        "X jest wlaczone. → Tak. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Tak. Temperatura Y.",
    ),
    (
        "pl",
        "jarvis",
        "X jest wlaczone. → Oczywiście, panie. X jest wlaczone.
X jest wylaczone. → X jest wylaczone.
Temperatura Y. → Oczywiście, panie. Temperatura Y.",
    ),
    (
        "sr",
        "default",
        "X је упаљен. → X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Температура Y.",
    ),
    (
        "sr",
        "butler",
        "X је упаљен. → Врло добро. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Врло добро. Температура Y.",
    ),
    (
        "sr",
        "locker",
        "X је упаљен. → У реду. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → У реду. Температура Y.",
    ),
    (
        "sr",
        "fuersorglich",
        "X је упаљен. → Одмах то радим. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Одмах то радим. Температура Y.",
    ),
    (
        "sr",
        "party",
        "X је упаљен. → Идемо. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Идемо. Температура Y.",
    ),
    (
        "sr",
        "grantig",
        "X је упаљен. → Добро. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Добро. Температура Y.",
    ),
    (
        "sr",
        "sarkastisch",
        "X је упаљен. → Наравно. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Наравно. Температура Y.",
    ),
    (
        "sr",
        "pirat",
        "X је упаљен. → Aye. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Aye. Температура Y.",
    ),
    (
        "sr",
        "hippie",
        "X је упаљен. → Опуштено. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Опуштено. Температура Y.",
    ),
    (
        "sr",
        "gollum",
        "X је упаљен. → Да. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Да. Температура Y.",
    ),
    (
        "sr",
        "jarvis",
        "X је упаљен. → Наравно, господине. X је упаљен.
X је угашен. → X је угашен.
Температура Y. → Наравно, господине. Температура Y.",
    ),
    (
        "ar",
        "default",
        "X يعمل. → X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → درجة الحرارة Y.",
    ),
    (
        "ar",
        "butler",
        "X يعمل. → حسنا. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → حسنا. درجة الحرارة Y.",
    ),
    (
        "ar",
        "locker",
        "X يعمل. → تمام. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → تمام. درجة الحرارة Y.",
    ),
    (
        "ar",
        "fuersorglich",
        "X يعمل. → الآن أفعل ذلك. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → الآن أفعل ذلك. درجة الحرارة Y.",
    ),
    (
        "ar",
        "party",
        "X يعمل. → يلا. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → يلا. درجة الحرارة Y.",
    ),
    (
        "ar",
        "grantig",
        "X يعمل. → طيب. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → طيب. درجة الحرارة Y.",
    ),
    (
        "ar",
        "sarkastisch",
        "X يعمل. → طبعا. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → طبعا. درجة الحرارة Y.",
    ),
    (
        "ar",
        "pirat",
        "X يعمل. → Aye. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → Aye. درجة الحرارة Y.",
    ),
    (
        "ar",
        "hippie",
        "X يعمل. → على مهلك. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → على مهلك. درجة الحرارة Y.",
    ),
    (
        "ar",
        "gollum",
        "X يعمل. → نعم. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → نعم. درجة الحرارة Y.",
    ),
    (
        "ar",
        "jarvis",
        "X يعمل. → طبعا يا سيدي. X يعمل.
X مطفأ. → X مطفأ.
درجة الحرارة Y. → طبعا يا سيدي. درجة الحرارة Y.",
    ),
    (
        "ko",
        "default",
        "X 켜졌어요. → X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 온도 Y.",
    ),
    (
        "ko",
        "butler",
        "X 켜졌어요. → 알겠습니다. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 알겠습니다. 온도 Y.",
    ),
    (
        "ko",
        "locker",
        "X 켜졌어요. → 오케이. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 오케이. 온도 Y.",
    ),
    (
        "ko",
        "fuersorglich",
        "X 켜졌어요. → 지금 할게요. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 지금 할게요. 온도 Y.",
    ),
    (
        "ko",
        "party",
        "X 켜졌어요. → 가자. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 가자. 온도 Y.",
    ),
    (
        "ko",
        "grantig",
        "X 켜졌어요. → 그래. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 그래. 온도 Y.",
    ),
    (
        "ko",
        "sarkastisch",
        "X 켜졌어요. → 당연하지. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 당연하지. 온도 Y.",
    ),
    (
        "ko",
        "pirat",
        "X 켜졌어요. → Aye. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → Aye. 온도 Y.",
    ),
    (
        "ko",
        "hippie",
        "X 켜졌어요. → 편하게. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 편하게. 온도 Y.",
    ),
    (
        "ko",
        "gollum",
        "X 켜졌어요. → 네. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 네. 온도 Y.",
    ),
    (
        "ko",
        "jarvis",
        "X 켜졌어요. → 물론이죠, 선생님. X 켜졌어요.
X 꺼졌어요. → X 꺼졌어요.
온도 Y. → 물론이죠, 선생님. 온도 Y.",
    ),
    (
        "gl",
        "default",
        "X esta aceso. → X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → A temperatura Y.",
    ),
    (
        "gl",
        "butler",
        "X esta aceso. → Moi ben. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Moi ben. A temperatura Y.",
    ),
    (
        "gl",
        "locker",
        "X esta aceso. → Feito. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Feito. A temperatura Y.",
    ),
    (
        "gl",
        "fuersorglich",
        "X esta aceso. → Agora mesmo. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Agora mesmo. A temperatura Y.",
    ),
    (
        "gl",
        "party",
        "X esta aceso. → Imos. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Imos. A temperatura Y.",
    ),
    (
        "gl",
        "grantig",
        "X esta aceso. → Bueno. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Bueno. A temperatura Y.",
    ),
    (
        "gl",
        "sarkastisch",
        "X esta aceso. → Claro. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Claro. A temperatura Y.",
    ),
    (
        "gl",
        "pirat",
        "X esta aceso. → Aye. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Aye. A temperatura Y.",
    ),
    (
        "gl",
        "hippie",
        "X esta aceso. → Tranqui. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Tranqui. A temperatura Y.",
    ),
    (
        "gl",
        "gollum",
        "X esta aceso. → Si. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Si. A temperatura Y.",
    ),
    (
        "gl",
        "jarvis",
        "X esta aceso. → Claro, señor. X esta aceso.
X esta apagado. → X esta apagado.
A temperatura Y. → Claro, señor. A temperatura Y.",
    ),
    (
        "id",
        "default",
        "X menyala. → X menyala.
X mati. → X mati.
Suhu Y. → Suhu Y.",
    ),
    (
        "id",
        "butler",
        "X menyala. → Baik. X menyala.
X mati. → X mati.
Suhu Y. → Baik. Suhu Y.",
    ),
    (
        "id",
        "locker",
        "X menyala. → Oke. X menyala.
X mati. → X mati.
Suhu Y. → Oke. Suhu Y.",
    ),
    (
        "id",
        "fuersorglich",
        "X menyala. → Saya kerjakan sekarang. X menyala.
X mati. → X mati.
Suhu Y. → Saya kerjakan sekarang. Suhu Y.",
    ),
    (
        "id",
        "party",
        "X menyala. → Ayo. X menyala.
X mati. → X mati.
Suhu Y. → Ayo. Suhu Y.",
    ),
    (
        "id",
        "grantig",
        "X menyala. → Ya sudah. X menyala.
X mati. → X mati.
Suhu Y. → Ya sudah. Suhu Y.",
    ),
    (
        "id",
        "sarkastisch",
        "X menyala. → Tentu saja. X menyala.
X mati. → X mati.
Suhu Y. → Tentu saja. Suhu Y.",
    ),
    (
        "id",
        "pirat",
        "X menyala. → Aye. X menyala.
X mati. → X mati.
Suhu Y. → Aye. Suhu Y.",
    ),
    (
        "id",
        "hippie",
        "X menyala. → Santai. X menyala.
X mati. → X mati.
Suhu Y. → Santai. Suhu Y.",
    ),
    (
        "id",
        "gollum",
        "X menyala. → Ya. X menyala.
X mati. → X mati.
Suhu Y. → Ya. Suhu Y.",
    ),
    (
        "id",
        "jarvis",
        "X menyala. → Tentu, tuan. X menyala.
X mati. → X mati.
Suhu Y. → Tentu, tuan. Suhu Y.",
    ),
    (
        "gu",
        "default",
        "X ચાલુ છે. → X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → તાપમાન Y.",
    ),
    (
        "gu",
        "butler",
        "X ચાલુ છે. → સરસ. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → સરસ. તાપમાન Y.",
    ),
    (
        "gu",
        "locker",
        "X ચાલુ છે. → સમજાયું. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → સમજાયું. તાપમાન Y.",
    ),
    (
        "gu",
        "fuersorglich",
        "X ચાલુ છે. → હવે કરું છું. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → હવે કરું છું. તાપમાન Y.",
    ),
    (
        "gu",
        "party",
        "X ચાલુ છે. → ચાલો. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → ચાલો. તાપમાન Y.",
    ),
    (
        "gu",
        "grantig",
        "X ચાલુ છે. → ઠીક. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → ઠીક. તાપમાન Y.",
    ),
    (
        "gu",
        "sarkastisch",
        "X ચાલુ છે. → ચોક્કસ. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → ચોક્કસ. તાપમાન Y.",
    ),
    (
        "gu",
        "pirat",
        "X ચાલુ છે. → Aye. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → Aye. તાપમાન Y.",
    ),
    (
        "gu",
        "hippie",
        "X ચાલુ છે. → શાંત. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → શાંત. તાપમાન Y.",
    ),
    (
        "gu",
        "gollum",
        "X ચાલુ છે. → હા. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → હા. તાપમાન Y.",
    ),
    (
        "gu",
        "jarvis",
        "X ચાલુ છે. → જી હા, સર. X ચાલુ છે.
X બંધ છે. → X બંધ છે.
તાપમાન Y. → જી હા, સર. તાપમાન Y.",
    ),
    (
        "pa",
        "default",
        "X ਚਾਲੂ ਹੈ। → X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "butler",
        "X ਚਾਲੂ ਹੈ। → ਠੀਕ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਠੀਕ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "locker",
        "X ਚਾਲੂ ਹੈ। → ਸਮਝ ਗਿਆ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਸਮਝ ਗਿਆ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "fuersorglich",
        "X ਚਾਲੂ ਹੈ। → ਹੁਣ ਕਰਦਾ ਹਾਂ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਹੁਣ ਕਰਦਾ ਹਾਂ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "party",
        "X ਚਾਲੂ ਹੈ। → ਚਲੋ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਚਲੋ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "grantig",
        "X ਚਾਲੂ ਹੈ। → ਠੀਕ ਹੈ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਠੀਕ ਹੈ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "sarkastisch",
        "X ਚਾਲੂ ਹੈ। → ਜ਼ਰੂਰ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਜ਼ਰੂਰ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "pirat",
        "X ਚਾਲੂ ਹੈ। → Aye. X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → Aye. ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "hippie",
        "X ਚਾਲੂ ਹੈ। → ਆਰਾਮ ਨਾਲ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਆਰਾਮ ਨਾਲ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "gollum",
        "X ਚਾਲੂ ਹੈ। → ਹਾਂ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਹਾਂ। ਤਾਪਮਾਨ Y।",
    ),
    (
        "pa",
        "jarvis",
        "X ਚਾਲੂ ਹੈ। → ਜੀ ਹਾਂ, ਸਰ। X ਚਾਲੂ ਹੈ।
X ਬੰਦ ਹੈ। → X ਬੰਦ ਹੈ।
ਤਾਪਮਾਨ Y। → ਜੀ ਹਾਂ, ਸਰ। ਤਾਪਮਾਨ Y।",
    ),
];
