//! Generated full-home Assist suites. Quick is local; full is opt-in.
//! @generated by scripts/full_home/generate.py. DO NOT EDIT.
mod voice_suite_support;

use klar_nlu::types::HomeGraph;
use voice_suite_support::{print_stats, run_groups_lang, suite_home};

fn run_tier(code: &str, tier: &str) -> voice_suite_support::RunStats {
    let name = format!("full_home/{code}");
    let home: HomeGraph = suite_home(&name);
    run_groups_lang(&name, &[tier], home, Some(code), None)
}

fn assert_tier(code: &str, tier: &str, min_ok: usize) {
    let stats = run_tier(code, tier);
    print_stats(&format!("Klar NLU · full-home {code} {tier}"), &stats);
    assert!(stats.ok + stats.fail >= min_ok, "{code} {tier} has no cases");
    if tier == "full" && code != "de" && code != "en" && std::env::var_os("KLAR_FULL_HOME_STRICT").is_none() {
        if stats.fail > 0 {
            println!("::warning title={code} full-home::{tier} {fail} failures", fail = stats.fail);
        }
        return;
    }
    assert_eq!(stats.fail, 0, "{code} {tier} failures:\n{}", stats.fails.join("\n"));
}

macro_rules! full_home {
    ($quick:ident, $full:ident, $code:literal) => {
        #[test]
        fn $quick() {
            assert_tier($code, "quick", 25);
        }
        #[test]
        fn $full() {
            if std::env::var_os("KLAR_FULL_HOME").is_none() {
                return;
            }
            assert_tier($code, "full", 80);
        }
    };
}

full_home!(full_home_quick_de, full_home_full_de, "de");
full_home!(full_home_quick_en, full_home_full_en, "en");
full_home!(full_home_quick_fr, full_home_full_fr, "fr");
full_home!(full_home_quick_nl, full_home_full_nl, "nl");
full_home!(full_home_quick_es, full_home_full_es, "es");
full_home!(full_home_quick_it, full_home_full_it, "it");
full_home!(full_home_quick_pt, full_home_full_pt, "pt");
full_home!(full_home_quick_ca, full_home_full_ca, "ca");
full_home!(full_home_quick_ro, full_home_full_ro, "ro");
full_home!(full_home_quick_da, full_home_full_da, "da");
full_home!(full_home_quick_nb, full_home_full_nb, "nb");
full_home!(full_home_quick_sv, full_home_full_sv, "sv");
full_home!(full_home_quick_fi, full_home_full_fi, "fi");
full_home!(full_home_quick_de_ch, full_home_full_de_ch, "de-CH");
full_home!(full_home_quick_de_at, full_home_full_de_at, "de-AT");
full_home!(full_home_quick_en_gb, full_home_full_en_gb, "en-GB");
full_home!(full_home_quick_pt_br, full_home_full_pt_br, "pt-BR");
full_home!(full_home_quick_af, full_home_full_af, "af");
full_home!(full_home_quick_cs, full_home_full_cs, "cs");
full_home!(full_home_quick_sk, full_home_full_sk, "sk");
full_home!(full_home_quick_pl, full_home_full_pl, "pl");
full_home!(full_home_quick_hu, full_home_full_hu, "hu");
full_home!(full_home_quick_hr, full_home_full_hr, "hr");
full_home!(full_home_quick_sl, full_home_full_sl, "sl");
full_home!(full_home_quick_bg, full_home_full_bg, "bg");
full_home!(full_home_quick_el, full_home_full_el, "el");
full_home!(full_home_quick_sr, full_home_full_sr, "sr");
full_home!(full_home_quick_sr_latn, full_home_full_sr_latn, "sr-Latn");
full_home!(full_home_quick_uk, full_home_full_uk, "uk");
full_home!(full_home_quick_zh_cn, full_home_full_zh_cn, "zh-CN");
full_home!(full_home_quick_zh_tw, full_home_full_zh_tw, "zh-TW");
full_home!(full_home_quick_zh_hk, full_home_full_zh_hk, "zh-HK");
full_home!(full_home_quick_ar, full_home_full_ar, "ar");
full_home!(full_home_quick_he, full_home_full_he, "he");
full_home!(full_home_quick_fa, full_home_full_fa, "fa");
full_home!(full_home_quick_ur, full_home_full_ur, "ur");
full_home!(full_home_quick_tr, full_home_full_tr, "tr");
full_home!(full_home_quick_th, full_home_full_th, "th");
full_home!(full_home_quick_ko, full_home_full_ko, "ko");
full_home!(full_home_quick_ja, full_home_full_ja, "ja");
full_home!(full_home_quick_cy, full_home_full_cy, "cy");
full_home!(full_home_quick_et, full_home_full_et, "et");
full_home!(full_home_quick_eu, full_home_full_eu, "eu");
full_home!(full_home_quick_ga, full_home_full_ga, "ga");
full_home!(full_home_quick_gl, full_home_full_gl, "gl");
full_home!(full_home_quick_is, full_home_full_is, "is");
full_home!(full_home_quick_lb, full_home_full_lb, "lb");
full_home!(full_home_quick_kw, full_home_full_kw, "kw");
full_home!(full_home_quick_lt, full_home_full_lt, "lt");
full_home!(full_home_quick_lv, full_home_full_lv, "lv");
full_home!(full_home_quick_id, full_home_full_id, "id");
full_home!(full_home_quick_ms, full_home_full_ms, "ms");
full_home!(full_home_quick_sw, full_home_full_sw, "sw");
full_home!(full_home_quick_vi, full_home_full_vi, "vi");
full_home!(full_home_quick_hi, full_home_full_hi, "hi");
full_home!(full_home_quick_bn, full_home_full_bn, "bn");
full_home!(full_home_quick_gu, full_home_full_gu, "gu");
full_home!(full_home_quick_kn, full_home_full_kn, "kn");
full_home!(full_home_quick_ml, full_home_full_ml, "ml");
full_home!(full_home_quick_mr, full_home_full_mr, "mr");
full_home!(full_home_quick_ta, full_home_full_ta, "ta");
full_home!(full_home_quick_te, full_home_full_te, "te");
full_home!(full_home_quick_pa, full_home_full_pa, "pa");
full_home!(full_home_quick_ne, full_home_full_ne, "ne");
full_home!(full_home_quick_hy, full_home_full_hy, "hy");
full_home!(full_home_quick_ka, full_home_full_ka, "ka");
full_home!(full_home_quick_mn, full_home_full_mn, "mn");
