"""German labels for the family-home suite."""

AREA = {
    "entryway": ("Eingang", "am Eingang", ["eingang", "diele"]),
    "living": ("Wohnzimmer", "im Wohnzimmer", ["wohnzimmer", "wohnraum"]),
    "dining": ("Esszimmer", "im Esszimmer", ["esszimmer"]),
    "kitchen": ("Küche", "in der Küche", ["kueche", "kuche"]),
    "family_room": ("Familienzimmer", "im Familienzimmer", ["familienzimmer"]),
    "laundry": ("Waschküche", "in der Waschküche", ["waschkueche"]),
    "powder_room": ("Gäste-WC", "im Gäste-WC", ["gaestewc", "gaeste wc"]),
    "garage": ("Garage", "in der Garage", ["garage"]),
    "master_bedroom": ("Schlafzimmer", "im Schlafzimmer", ["schlafzimmer", "elternschlafzimmer"]),
    "bedroom_2": ("Kinderzimmer 2", "in Kinderzimmer 2", ["kinderzimmer 2"]),
    "bedroom_3": ("Kinderzimmer 3", "in Kinderzimmer 3", ["kinderzimmer 3"]),
    "bedroom_4": ("Kinderzimmer 4", "in Kinderzimmer 4", ["kinderzimmer 4"]),
    "master_bath": ("Elternbad", "im Elternbad", ["elternbad"]),
    "main_bath": ("Badezimmer", "im Badezimmer", ["badezimmer", "bad"]),
    "hallway": ("Flur", "im Flur", ["flur"]),
}

NAME = {
    "Entryway Light": "Eingangslicht",
    "Front Door": "Haustür",
    "Front Door Sensor": "Türsensor",
    "Living Room Ceiling": "Wohnzimmer Decke",
    "Living Room Lamp": "Wohnzimmer Lampe",
    "Living Room TV": "Wohnzimmer Fernseher",
    "Living Room Blinds": "Wohnzimmer Rollo",
    "Dining Pendant": "Esszimmer Pendelleuchte",
    "Kitchen Ceiling": "Küche Decke",
    "Island Lights": "Insel Licht",
    "Rangehood": "Dunstabzug",
    "Dishwasher": "Spülmaschine",
    "Family Room Ceiling": "Familienzimmer Decke",
    "Family Room TV": "Familienzimmer Fernseher",
    "Family Room Fan": "Familienzimmer Lüfter",
    "Laundry Light": "Waschküche Licht",
    "Washing Machine": "Waschmaschine",
    "Dryer": "Trockner",
    "Powder Room Light": "Gäste-WC Licht",
    "Garage Light": "Garagenlicht",
    "Garage Door": "Garagentor",
    "Garage Entry Door": "Garagentür",
    "Master Ceiling": "Schlafzimmer Decke",
    "Master Ensuite Light": "Ankleide Licht",
    "Left Bedside Lamp": "Nachttisch links",
    "Right Bedside Lamp": "Nachttisch rechts",
    "Master Fan": "Schlafzimmer Lüfter",
    "Master Blinds": "Schlafzimmer Rollo",
    "Bedroom 2 Ceiling": "Kinderzimmer 2 Decke",
    "Bedroom 2 Fan": "Kinderzimmer 2 Lüfter",
    "Bedroom 2 Blinds": "Kinderzimmer 2 Rollo",
    "Bedroom 3 Ceiling": "Kinderzimmer 3 Decke",
    "Bedroom 3 Blinds": "Kinderzimmer 3 Rollo",
    "Bedroom 4 Ceiling": "Kinderzimmer 4 Decke",
    "Master Bath Light": "Elternbad Licht",
    "Master Bath Fan": "Elternbad Lüfter",
    "Main Bath Light": "Badezimmer Licht",
    "Main Bath Fan": "Badezimmer Lüfter",
    "Hallway Light": "Flur Licht",
    "Ground Floor Thermostat": "Heizung Erdgeschoss",
    "Upper Floor Thermostat": "Heizung Obergeschoss",
    "Movie Night": "Filmabend",
    "Dinner Time": "Abendessen",
    "Kids Bedtime": "Kinder ins Bett",
    "Good Morning": "Guten Morgen",
    "Good Night": "Gute Nacht",
    "Leaving Home": "Haus verlassen",
    "Oven Timer": "Ofen-Timer",
    "Laundry Timer": "Wäsche-Timer",
    "Chores": "Aufgaben",
}

COLOR = {
    "orange": "orange",
    "pink": "pink",
    "red": "rot",
    "blue": "blau",
    "green": "grün",
    "yellow": "gelb",
    "white": "weiß",
    "purple": "lila",
}

SCENE_CASES = {
    "movie_night": "scene.movie_night",
    "dinner_time": "scene.dinner_time",
    "kids_bedtime": "scene.kids_bedtime",
    "good_morning": "scene.good_morning",
}
SCRIPT_CASES = {
    "good_night": "script.good_night",
    "leaving_home": "script.leaving_home",
}
