"""Localized rare Home Assistant device states for floor/area status."""

from __future__ import annotations

_DEVICE_KEYS = ('paused', 'docked', 'cleaning', 'returning', 'playing', 'idle', 'heat', 'cool', 'auto', 'dry', 'fan_only', 'error', 'opening', 'closing')
_DEVICE: dict[str, tuple[str, ...]] = {
    "de": ("pausiert", "an der Station", "saugt", "fährt zur Station", "spielt", "bereit", "heizt", "kühlt", "automatisch", "entfeuchtet", "nur Lüfter", "Fehler", "öffnet", "schließt"),
    "en": ("paused", "docked", "cleaning", "returning", "playing", "idle", "heating", "cooling", "auto", "drying", "fan only", "error", "opening", "closing"),
    "fr": ("en pause", "à la base", "aspire", "rentre", "joue", "prêt", "chauffe", "refroidit", "auto", "déshumidifie", "ventilation", "erreur", "s'ouvre", "se ferme"),
    "nl": ("gepauzeerd", "aan het station", "zuigt", "gaat naar het station", "speelt", "wacht", "verwarmt", "koelt", "automatisch", "ontvochtigt", "alleen ventilator", "fout", "opent", "sluit"),
    "es": ("en pausa", "en la base", "aspira", "vuelve", "reproduce", "listo", "calienta", "enfría", "automático", "deshumidifica", "solo ventilador", "error", "abriendo", "cerrando"),
    "it": ("in pausa", "alla base", "aspira", "torna", "riproduce", "pronto", "riscalda", "raffredda", "automatico", "deumidifica", "solo ventola", "errore", "si apre", "si chiude"),
    "pt": ("em pausa", "na base", "aspira", "regressa", "a tocar", "pronto", "aquece", "arrefece", "automático", "desumidifica", "só ventoinha", "erro", "a abrir", "a fechar"),
    "ca": ("en pausa", "a la base", "aspira", "torna", "reprodueix", "llest", "escalfa", "refreda", "automàtic", "deshumidifica", "només ventilador", "error", "s'obre", "es tanca"),
    "ro": ("în pauză", "la bază", "aspiră", "se întoarce", "redă", "gata", "încălzește", "răcește", "automat", "dezumidifică", "doar ventilator", "eroare", "se deschide", "se închide"),
    "da": ("pauset", "ved stationen", "støvsuger", "kører hjem", "spiller", "klar", "varmer", "køler", "automatisk", "affugter", "kun blæser", "fejl", "åbner", "lukker"),
    "nb": ("pauset", "ved stasjonen", "støvsuger", "kjører hjem", "spiller", "klar", "varmer", "kjøler", "automatisk", "avfukter", "bare vifte", "feil", "åpner", "lukker"),
    "sv": ("pausad", "vid stationen", "dammsuger", "åker hem", "spelar", "redo", "värmer", "kyler", "automatiskt", "avfuktar", "bara fläkt", "fel", "öppnar", "stänger"),
    "fi": ("tauolla", "asemalla", "imuroi", "palaa", "soi", "valmis", "lämmittää", "jäähdyttää", "automaattinen", "kuivattaa", "vain tuuletin", "virhe", "avautuu", "sulkeutuu"),
    "af": ("gepouseer", "by die stasie", "stofsuig", "gaan terug", "speel", "gereed", "verhit", "verkoel", "outomaties", "ontvogtig", "net waaier", "fout", "maak oop", "maak toe"),
    "cs": ("pozastaveno", "v doku", "vysává", "vrací se", "hraje", "nečinný", "topí", "chladí", "auto", "odvlhčuje", "jen ventilátor", "chyba", "otevírá", "zavírá"),
    "sk": ("pozastavené", "v doku", "vysáva", "vracia sa", "hrá", "nečinný", "kúri", "chladí", "auto", "odvlhčuje", "len ventilátor", "chyba", "otvára", "zatvára"),
    "pl": ("wstrzymane", "w stacji", "odkurza", "wraca", "odtwarza", "gotowe", "grzeje", "chłodzi", "auto", "osusza", "tylko wentylator", "błąd", "otwiera", "zamyka"),
    "hu": ("szünetel", "az állomáson", "porszívóz", "visszatér", "játszik", "készen", "fűt", "hűt", "auto", "párátlanít", "csak ventillátor", "hiba", "nyílik", "zárul"),
    "hr": ("pauzirano", "na stanici", "usisava", "vraća se", "svira", "spreman", "grije", "hladi", "automatski", "odvlažuje", "samo ventilator", "greška", "otvara", "zatvara"),
    "sl": ("pavzirano", "na postaji", "sesa", "se vrača", "predvaja", "pripravljeno", "ogreva", "hladi", "samodejno", "razvlažuje", "samo ventilator", "napaka", "odpira", "zapira"),
    "bg": ("пауза", "на станцията", "почиства", "връща се", "свири", "готов", "топли", "охлажда", "автоматично", "изсушава", "само вентилатор", "грешка", "отваря", "затваря"),
    "el": ("σε παύση", "στη βάση", "σκουπίζει", "επιστρέφει", "παίζει", "έτοιμο", "ζεσταίνει", "ψύχει", "αυτόματο", "αφύγρανση", "μόνο ανεμιστήρας", "σφάλμα", "ανοίγει", "κλείνει"),
    "sr": ("паузирано", "на станици", "усисава", "враћа се", "свира", "спремно", "греје", "хлади", "аутоматски", "одвлажује", "само вентилатор", "грешка", "отвара", "затвара"),
    "uk": ("пауза", "на станції", "прибирає", "повертається", "грає", "готово", "гріє", "охолоджує", "авто", "осушує", "лише вентилятор", "помилка", "відчиняє", "зачиняє"),
    "zh-CN": ("已暂停", "在基站", "清扫中", "返回中", "播放中", "待机", "制热", "制冷", "自动", "除湿", "仅风扇", "故障", "打开中", "关闭中"),
    "ar": ("متوقف", "في القاعدة", "ينظف", "يعود", "يشغل", "جاهز", "تدفئة", "تبريد", "تلقائي", "تجفيف", "مروحة فقط", "خطأ", "يفتح", "يغلق"),
    "he": ("מושהה", "בתחנה", "שואב", "חוזר", "מנגן", "מוכן", "מחמם", "מקרר", "אוטומטי", "מייבש", "מאוורר בלבד", "שגיאה", "נפתח", "נסגר"),
    "fa": ("مکث", "در پایگاه", "جارو می‌کند", "برمی‌گردد", "پخش", "آماده", "گرمایش", "سرمایش", "خودکار", "خشک‌کن", "فقط فن", "خطا", "باز می‌شود", "بسته می‌شود"),
    "ur": ("توقف", "اسٹیشن پر", "صاف کر رہا ہے", "واپس آ رہا ہے", "چل رہا ہے", "تیار", "گرم", "ٹھنڈا", "خودکار", "خشک", "صرف پنکھا", "خرابی", "کھل رہا", "بند ہو رہا"),
    "tr": ("duraklatıldı", "istasyonda", "süpürüyor", "dönüyor", "çalıyor", "hazır", "ısıtıyor", "soğutuyor", "otomatik", "nem alıyor", "sadece fan", "hata", "açılıyor", "kapanıyor"),
    "th": ("หยุดชั่วคราว", "ที่ฐาน", "กำลังดูดฝุ่น", "กำลังกลับ", "กำลังเล่น", "พร้อม", "ทำความร้อน", "ทำความเย็น", "อัตโนมัติ", "ลดความชื้น", "พัดลมอย่างเดียว", "ข้อผิดพลาด", "กำลังเปิด", "กำลังปิด"),
    "ko": ("일시정지", "충전대", "청소 중", "복귀 중", "재생 중", "대기", "난방", "냉방", "자동", "제습", "송풍", "오류", "여는 중", "닫는 중"),
    "ja": ("一時停止", "ステーション", "掃除中", "帰還中", "再生中", "待機", "暖房", "冷房", "自動", "除湿", "送風", "エラー", "開いています", "閉じています"),
    "cy": ("wedi seibio", "yn y orsaf", "yn sugno", "yn dychwelyd", "yn chwarae", "barod", "yn gwresogi", "yn oeri", "awtomatig", "sychu", "ffan yn unig", "gwall", "yn agor", "yn cau"),
    "et": ("pausil", "jaamas", "imub", "naaseb", "mängib", "valmis", "köetab", "jahutab", "automaatne", "kuivatab", "ainult ventilaator", "viga", "avaneb", "sulgeb"),
    "eu": ("pausatuta", "oinarrian", "xurgatzen", "itzultzen", "jotzen", "prest", "berotzen", "hozten", "automatikoa", "lehortzen", "haizagailua soilik", "errorea", "irekitzen", "ixten"),
    "ga": ("curtha ar sos", "ag an stáisiún", "ag súchán", "ag filleadh", "ag seinm", "réidh", "ag téamh", "ag fuarú", "uathoibríoch", "triomú", "fean amháin", "earráid", "ag oscailt", "ag dúnadh"),
    "gl": ("en pausa", "na base", "aspira", "volve", "reproduce", "listo", "quece", "arrefria", "automático", "deshumidifica", "só ventoinha", "erro", "abrindo", "pechando"),
    "is": ("í hléi", "við stöðina", "ryksugar", "snýr aftur", "spilar", "tilbúið", "hitar", "kælir", "sjálfvirkt", "þurrkar", "bara viftu", "villa", "opnast", "lokast"),
    "lb": ("pauséiert", "op der Statioun", "saugt", "fiert zeréck", "spillt", "bereet", "heizt", "killt", "automatesch", "entfiicht", "nëmme Lüfter", "Feeler", "mécht op", "mécht zou"),
    "kw": ("powesys", "dhe'n orsav", "ow sugna", "ow dehweles", "ow seni", "parys", "ow tomma", "ow yeynhe", "awtomatek", "sygh", "yn unig fan", "gwall", "ow ygeri", "ow degea"),
    "lt": ("pristabdyta", "stotyje", "siurbia", "grįžta", "groja", "pasiruošęs", "šildo", "šaldo", "auto", "sausina", "tik ventiliatorius", "klaida", "atidaro", "uždaro"),
    "lv": ("pauzēts", "stacijā", "putekļsūcējs", "atgriežas", "atskaņo", "gatavs", "silda", "dzesē", "auto", "žāvē", "tikai ventilators", "kļūda", "atver", "aizver"),
    "id": ("dijeda", "di stasiun", "menyedot", "kembali", "memutar", "siap", "memanaskan", "mendinginkan", "otomatis", "mengeringkan", "hanya kipas", "error", "membuka", "menutup"),
    "ms": ("dijeda", "di stesen", "menghisap", "kembali", "bermain", "sedia", "memanaskan", "menyejukkan", "automatik", "mengeringkan", "kipas sahaja", "ralat", "membuka", "menutup"),
    "sw": ("imesimamishwa", "kwenye kituo", "inasafisha", "inarudi", "inacheza", "tayari", "inapasha", "inapoa", "otomatiki", "kukausha", "feni tu", "hitilafu", "inafungua", "inafunga"),
    "vi": ("tạm dừng", "ở đế", "đang hút", "đang về", "đang phát", "sẵn sàng", "sưởi", "làm mát", "tự động", "hút ẩm", "chỉ quạt", "lỗi", "đang mở", "đang đóng"),
    "hi": ("रुका", "स्टेशन पर", "साफ कर रहा है", "वापस आ रहा है", "चल रहा है", "तैयार", "गर्मी", "ठंडक", "स्वचालित", "सूखा", "केवल पंखा", "त्रुटि", "खुल रहा", "बंद हो रहा"),
    "bn": ("বিরতি", "স্টেশনে", "পরিষ্কার করছে", "ফিরছে", "বাজছে", "প্রস্তুত", "গরম", "ঠান্ডা", "স্বয়ংক্রিয়", "শুকনো", "শুধু পাখা", "ত্রুটি", "খুলছে", "বন্ধ হচ্ছে"),
    "gu": ("થોભાવ્યું", "સ્ટેશન પર", "સાફ કરે છે", "પાછું આવે છે", "ચાલે છે", "તૈયાર", "ગરમ", "ઠંડુ", "આપોઆપ", "સૂકવે", "માત્ર પંખો", "ભૂલ", "ખૂલે છે", "બંધ થાય છે"),
    "mr": ("थांबवले", "स्टेशनवर", "साफ करते", "परत येते", "चालू आहे", "तयार", "उष्ण", "थंड", "आपोआप", "सुकवत", "फक्त पंखा", "त्रुटी", "उघडते", "बंद होते"),
    "ta": ("இடைநிறுத்தம்", "நிலையத்தில்", "சுத்தம் செய்கிறது", "திரும்புகிறது", "இயங்குகிறது", "தயார்", "சூடு", "குளிர்", "தானியங்கி", "உலர்த்து", "விசிறி மட்டும்", "பிழை", "திறக்கிறது", "மூடுகிறது"),
    "ne": ("रोकियो", "स्टेशनमा", "सफा गर्दै", "फर्किँदै", "बज्दै", "तयार", "तातो", "चिसो", "स्वचालित", "सुकाउँदै", "पंखा मात्र", "त्रुटि", "खुल्दै", "बन्द हुँदै"),
    "hy": ("դադարեցված", "կայանում", "մաքրում է", "վերադառնում է", "նվագում է", "պատրաստ", "տաքացնում", "սառեցնում", "ավտո", "չորացնում", "միայն օդափոխիչ", "սխալ", "բացվում է", "փակվում է"),
    "mn": ("түр зогссон", "буудал дээр", "цэвэрлэж байна", "буцаж байна", "тоглож байна", "бэлэн", "халаана", "хөргөнө", "авто", "хатаана", "зөвхөн сэнс", "алдаа", "нээгдэж байна", "хаагдаж байна"),
    "kn": ("ವಿರಾಮ", "ನಿಲ್ದಾಣದಲ್ಲಿ", "ಸ್ವಚ್ಛಗೊಳಿಸುತ್ತಿದೆ", "ಹಿಂತಿರುಗುತ್ತಿದೆ", "ಪ್ಲೇ ಆಗುತ್ತಿದೆ", "ಸಿದ್ಧ", "ಬೆಚ್ಚಗೆ", "ತಂಪು", "ಸ್ವಯಂ", "ಒಣಗಿಸುತ್ತಿದೆ", "ಫ್ಯಾನ್ ಮಾತ್ರ", "ದೋಷ", "ತೆರೆಯುತ್ತಿದೆ", "ಮುಚ್ಚುತ್ತಿದೆ"),
    "ml": ("താൽക്കാലികമായി നിർത്തി", "സ്റ്റേഷനിൽ", "വൃത്തിയാക്കുന്നു", "മടങ്ങുന്നു", "പ്ലേ ചെയ്യുന്നു", "തയ്യാർ", "ചൂട്", "തണുപ്പ്", "ഓട്ടോ", "ഉണക്കുന്നു", "ഫാൻ മാത്രം", "പിശക്", "തുറക്കുന്നു", "അടയ്ക്കുന്നു"),
    "te": ("పాజ్", "స్టేషన్‌లో", "శుభ్రం చేస్తోంది", "తిరిగి వస్తోంది", "ప్లే అవుతోంది", "సిద్ధం", "వేడి", "చల్లదనం", "ఆటో", "ఎండబెడుతోంది", "ఫ్యాన్ మాత్రమే", "లోపం", "తెరుస్తోంది", "మూస్తోంది"),
    "pa": ("ਰੋਕਿਆ", "ਸਟੇਸ਼ਨ ਤੇ", "ਸਾਫ਼ ਕਰ ਰਿਹਾ", "ਵਾਪਸ ਆ ਰਿਹਾ", "ਚੱਲ ਰਿਹਾ", "ਤਿਆਰ", "ਗਰਮ", "ਠੰਢਾ", "ਆਟੋ", "ਸੁਕਾਉਂਦਾ", "ਸਿਰਫ਼ ਪੱਖਾ", "ਗਲਤੀ", "ਖੁੱਲ੍ਹ ਰਿਹਾ", "ਬੰਦ ਹੋ ਰਿਹਾ"),
    "ka": ("დაპაუზებული", "სადგურზე", "ასუფთავებს", "ბრუნდება", "უკრავს", "მზადაა", "ათბობს", "აგრილებს", "ავტო", "აშრობს", "მხოლოდ ვენტილატორი", "შეცდომა", "იღება", "იხურება"),
}

