#!/usr/bin/env python3
"""Generate quick + full Assist datasets for every compiled locale."""

from __future__ import annotations

import sys
import shutil
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / "scripts"))

from catalog import for_tier
from home import build_home
from lex import all_lexes
from realize import render

DATA = ROOT / "tests" / "datasets" / "full_home"
LIMITS = {"quick": 2, "full": 6}


def dump(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8")


def emit_cases(lex: dict, tier: str) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    code = lex["code"]
    limit = LIMITS[tier]
    if code not in {"de", "en"}:
        limit = 1 if tier == "quick" else 2
    for case in for_tier(tier):
        row = {
            "name": case["name"],
            "conditions": case["conditions"],
            "sentences": render(lex, case, limit, merge_defaults=tier == "full"),
        }
        if case.get("forbid"):
            row["forbid"] = case["forbid"]
        if case.get("nlu_expect"):
            row["nlu_expect"] = case["nlu_expect"]
        grouped[case["group"]].append(row)
    return grouped


def write_locale(lex: dict) -> tuple[int, int]:
    code = lex["code"]
    dest = DATA / code
    if dest.exists():
        shutil.rmtree(dest)
    dump(dest / "home_config.yaml", build_home(lex))
    counts = {}
    for tier in ("quick", "full"):
        grouped = emit_cases(lex, tier)
        counts[tier] = sum(len(rows) for rows in grouped.values())
        for group, rows in grouped.items():
            dump(dest / tier / f"{group}.yaml", rows)
    return counts["quick"], counts["full"]


def write_tests(codes: list[str]) -> None:
    lines = [
        "//! Generated full-home Assist suites. Quick is local; full is opt-in.",
        "//! @generated by scripts/full_home/generate.py. DO NOT EDIT.",
        "mod voice_suite_support;",
        "",
        "use klar_nlu::types::HomeGraph;",
        "use voice_suite_support::{print_stats, run_groups_lang, suite_home};",
        "",
        "fn run_tier(code: &str, tier: &str) -> voice_suite_support::RunStats {",
        "    let name = format!(\"full_home/{code}\");",
        "    let home: HomeGraph = suite_home(&name);",
        "    run_groups_lang(&name, &[tier], home, Some(code), None)",
        "}",
        "",
        "fn assert_tier(code: &str, tier: &str, min_ok: usize) {",
        "    let stats = run_tier(code, tier);",
        "    print_stats(&format!(\"Klar NLU · full-home {code} {tier}\"), &stats);",
        "    assert!(stats.ok + stats.fail >= min_ok, \"{code} {tier} has no cases\");",
        "    if tier == \"full\" && code != \"de\" && code != \"en\" && std::env::var_os(\"KLAR_FULL_HOME_STRICT\").is_none() {",
        "        if stats.fail > 0 {",
        "            println!(\"::warning title={code} full-home::{tier} {fail} failures\", fail = stats.fail);",
        "        }",
        "        return;",
        "    }",
        "    assert_eq!(stats.fail, 0, \"{code} {tier} failures:\\n{}\", stats.fails.join(\"\\n\"));",
        "}",
        "",
        "macro_rules! full_home {",
        "    ($quick:ident, $full:ident, $code:literal) => {",
        "        #[test]",
        "        fn $quick() {",
        "            assert_tier($code, \"quick\", 25);",
        "        }",
        "        #[test]",
        "        fn $full() {",
        "            if std::env::var_os(\"KLAR_FULL_HOME\").is_none() {",
        "                return;",
        "            }",
        "            assert_tier($code, \"full\", 80);",
        "        }",
        "    };",
        "}",
        "",
    ]
    for code in codes:
        ident = code.lower().replace("-", "_")
        lines.append(f'full_home!(full_home_quick_{ident}, full_home_full_{ident}, "{code}");')
    path = ROOT / "tests" / "full_home.rs"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", path.relative_to(ROOT))


def main() -> None:
    lexes = all_lexes()
    codes = []
    for lex in lexes:
        quick, full = write_locale(lex)
        codes.append(lex["code"])
        print(f"wrote {lex['code']}: quick={quick} full={full}")
    write_tests(codes)


if __name__ == "__main__":
    main()
