#!/usr/bin/env python3
"""Stdlib tests for CHANGELOG release-note extraction."""

from __future__ import annotations

import contextlib
import importlib.util
import io
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _load():
    path = ROOT / "scripts" / "release-notes.py"
    spec = importlib.util.spec_from_file_location("klar_release_notes", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


mod = _load()


class ReleaseNotesTests(unittest.TestCase):
    def test_extracts_2026_8_4(self) -> None:
        notes = mod.section((ROOT / "CHANGELOG.md").read_text(encoding="utf-8"), "2026.8.4")
        self.assertIn("### Security", notes)
        self.assertIn("SHA-256", notes)
        self.assertNotIn("## [2026.8.3]", notes)
        self.assertNotIn("## [2026.8.5]", notes)

    def test_extracts_2026_8_5(self) -> None:
        notes = mod.section((ROOT / "CHANGELOG.md").read_text(encoding="utf-8"), "2026.8.5")
        self.assertIn("### Bug Fixes", notes)
        self.assertIn("Adaptive Lighting", notes)
        self.assertNotIn("## [2026.8.4]", notes)

    def test_synthetic_range(self) -> None:
        text = (
            "# Changelog\n\n"
            "## [1.2.0](https://example.test/compare/1.1.0...1.2.0) - 2026-01-02\n\n"
            "### Features\n\n- extra lights\n\n"
            "## [1.1.0] - 2026-01-01\n\n"
            "### Bug Fixes\n\n- older\n"
        )
        notes = mod.section(text, "v1.2.0")
        self.assertIn("extra lights", notes)
        self.assertNotIn("older", notes)

    def test_missing_version(self) -> None:
        self.assertEqual(mod.section("# Changelog\n", "9.9.9"), "")
        self.assertEqual(mod.main(["release-notes.py", "9.9.9"]), 1)

    def test_calver_base_strips_rc_suffix(self) -> None:
        self.assertEqual(mod.calver_base("v2026.8.30-staging.a1b2c3d"), "2026.8.30")
        self.assertEqual(mod.calver_base("2026.8.30-rc.12"), "2026.8.30")

    def test_staging_notes_list_commits_since_main(self) -> None:
        notes = mod.commits_since(
            [
                "feat: full-home language lift",
                "Merge pull request #92 from org/branch",
                "fix: gitleaks RE2 panic",
            ],
            "main",
        )
        self.assertIn("## Changes since `main`", notes)
        self.assertIn("- feat: full-home language lift", notes)
        self.assertIn("- fix: gitleaks RE2 panic", notes)
        self.assertNotIn("Merge pull request", notes)

    def test_heading_without_groups_is_rejected(self) -> None:
        empty = "## [2026.8.4] - 2026-08-15\n\n<!-- generated by git-cliff -->\n"
        notes = mod.section(empty, "2026.8.4")
        self.assertTrue(notes)
        self.assertIsNone(re.search(r"^### ", notes, re.M))

    def test_hoist_breaking_from_mark(self) -> None:
        notes = (
            "## [1.2.0](https://example.test/compare/1.1.0...1.2.0) - 2026-01-02\n\n"
            "### Features\n\n"
            "- [**breaking**] drop /api/parse\n"
            "- extra lights\n"
        )
        out = mod.hoist_breaking(notes)
        self.assertTrue(out.startswith("## Breaking Changes"))
        self.assertLess(out.index("drop /api/parse"), out.index("### Features"))
        self.assertIn("- extra lights", out)

    def test_hoist_skips_when_none(self) -> None:
        notes = "## [1.0.0]\n\n### Bug Fixes\n\n- older\n"
        self.assertEqual(mod.hoist_breaking(notes), notes)

    def test_hoist_from_breaking_group(self) -> None:
        notes = (
            "## [1.3.0] - 2026-01-03\n\n"
            "### Breaking Changes\n\n"
            "- HTTP parse is V2 only\n\n"
            "### Features\n\n"
            "- extra lights\n"
        )
        out = mod.hoist_breaking(notes)
        lead = out.split("## [1.3.0]", 1)[0]
        self.assertIn("HTTP parse is V2 only", lead)
        self.assertNotIn("extra lights", lead)

    def test_staging_hoists_bang_commits(self) -> None:
        notes = mod.commits_since(["feat!: parse is V2 only", "fix: typo"], "main")
        out = mod.hoist_breaking(notes)
        self.assertTrue(out.startswith("## Breaking Changes"))
        self.assertIn("feat!: parse is V2 only", out.split("## Changes since", 1)[0])
        self.assertIn("- fix: typo", out)

    def test_stable_notes_hoist_v2_break(self) -> None:
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            self.assertEqual(mod.main(["release-notes.py", "2026.8.26"]), 0)
        out = buf.getvalue()
        self.assertTrue(out.startswith("## Breaking Changes"))
        self.assertIn("V2 ParseOutcome", out)
        self.assertIn("### Features", out)

    def test_addon_changelogs_match_root(self) -> None:
        root = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
        self.assertTrue(root.startswith("# Changelog"))
        for rel in ("addon/CHANGELOG.md", "addon-staging/CHANGELOG.md"):
            path = ROOT / rel
            self.assertTrue(path.is_file(), rel)
            self.assertEqual(path.read_text(encoding="utf-8"), root)

    def test_sync_addons_rewrites_copies(self) -> None:
        self.assertEqual(mod.main(["release-notes.py", "--sync-addons"]), 0)
        self.test_addon_changelogs_match_root()


if __name__ == "__main__":
    unittest.main()
