#!/usr/bin/env python3
"""CI gates for compiled Assist packs.

de/en live in src/lang/packs/{de,en}/ as hand-written reference packs.
The generator must not overwrite them. Shared LanguagePack fields belong
in those two packs, scripts/lang_packs/emit*.py, and this checklist.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKS = ROOT / "src" / "lang" / "packs"
PARSE = ROOT / "src" / "parse"
NLU = ROOT / "src" / "nlu"
DATASETS = ROOT / "tests" / "datasets" / "assist"
PARITY = ROOT / "tests" / "datasets" / "parity"
PARITY_SUITES = ("wohnung_mittel", "familienhaus_de", "m0_exact", "m2_floors")
MAX_LINES = 500
BANNED = re.compile(r"LangId::De|LangId::En")
FAKE_SUFFIX = re.compile(r"[A-Za-z]{4,}(cov|cli|fanx|opn|cls|scn|lst)\"")
BANNED_ENGINE = re.compile(r'"(bitte|leuchte|erledigt)"')
BANNER = "@generated by scripts/lang_packs. DO NOT EDIT."
DEFAULT_IDS = re.compile(r"pub const DEFAULT:\s*\[LangId;\s*(\d+)\]\s*=\s*\[([^\]]+)\]")
SIZE_ROOTS = [
    ROOT / "src" / "lang" / "catalog",
    ROOT / "src" / "parse",
    ROOT / "src" / "nlu",
    ROOT / "tests" / "voice_suite_support",
    ROOT / "scripts" / "parity",
]
FIELD_GROUPS = ("Talk", "Nouns", "Fixtures", "Cues", "Maps", "Chat", "Household", "LanguagePack")
GERMAN_SCAFFOLD = re.compile(r"aufgabenliste|klimaanlage|(?<![A-Za-z])insel(?![A-Za-z])|filmabend|verlassen")
HANDWRITTEN = {"de", "en"}
DE_SCAFFOLD_OK = HANDWRITTEN | {"de_ch", "de_at"}
MOD_TO_TAG = {
    "de_ch": "de-CH",
    "de_at": "de-AT",
    "en_gb": "en-GB",
    "pt_br": "pt-BR",
    "sr_latn": "sr-Latn",
    "zh_cn": "zh-CN",
    "zh_tw": "zh-TW",
    "zh_hk": "zh-HK",
}


def check_default_catalog() -> None:
    """No privileged de+en default. Catalog is per-request; empty means no merge."""
    lang_mod = (ROOT / "src" / "lang" / "mod.rs").read_text(encoding="utf-8")
    if DEFAULT_IDS.search(lang_mod):
        fail("LangId::DEFAULT must not exist; compiled locales are first-class")
    if "Catalog::merge(&[LangId::De.pack(), LangId::En.pack()])" in lang_mod:
        fail("default catalog must not merge only De and En")
    const_py = (ROOT / "custom_components" / "klar_nlu" / "const.py").read_text(encoding="utf-8")
    if re.search(r'^DEFAULT_LANGUAGES = \("de", "en"\)$', const_py, re.MULTILINE):
        fail("DEFAULT_LANGUAGES must not be de+en only")
    settings = (ROOT / "src" / "types" / "settings.rs").read_text(encoding="utf-8")
    if 'vec!["de".into(), "en".into()]' in settings:
        fail("Settings default_languages must not special-case de+en")


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def line_count(path: Path) -> int:
    return path.read_text(encoding="utf-8").count("\n") + 1


def check_size_gate() -> None:
    over = []
    for rust in PACKS.rglob("*.rs"):
        lines = line_count(rust)
        if lines > MAX_LINES:
            over.append(f"{rust.relative_to(ROOT)}:{lines}")
    for root in SIZE_ROOTS:
        if not root.exists():
            continue
        paths = root.rglob("*.rs") if root.suffix != ".py" and root.is_dir() else []
        if root.name in {"parity"}:
            paths = root.glob("*.py")
        for path in paths:
            if path.name.startswith("test_"):
                continue
            lines = line_count(path)
            if lines > MAX_LINES:
                over.append(f"{path.relative_to(ROOT)}:{lines}")
    if over:
        fail("files over 500 lines:\n" + "\n".join(over))


def struct_fields(source: str, name: str) -> list[str]:
    match = re.search(rf"pub struct {name} \{{(.*?)\n\}}", source, re.S)
    if not match:
        return []
    return re.findall(r"pub(?:\([^)]+\))? (\w+):", match.group(1))


def check_field_checklist() -> None:
    groups = (ROOT / "src" / "lang" / "groups.rs").read_text(encoding="utf-8")
    emit = "".join(path.read_text(encoding="utf-8") for path in sorted((ROOT / "scripts" / "lang_packs").glob("emit*.py")))
    de_pack = (PACKS / "de" / "pack.rs").read_text(encoding="utf-8")
    en_pack = (PACKS / "en" / "pack.rs").read_text(encoding="utf-8")
    missing = []
    for name in FIELD_GROUPS:
        for field in struct_fields(groups, name):
            if field == "id":
                continue
            if f"{field}:" not in emit and f"{field} =" not in emit:
                missing.append(f"emit.py missing {name}.{field}")
            if f"{field}:" not in de_pack:
                missing.append(f"packs/de/pack.rs missing {name}.{field}")
            if f"{field}:" not in en_pack:
                missing.append(f"packs/en/pack.rs missing {name}.{field}")
    if missing:
        fail("LanguagePack field checklist:\n" + "\n".join(missing))


def check_banners() -> None:
    missing = []
    for rust in PACKS.rglob("*.rs"):
        if rust.parent.name in HANDWRITTEN:
            continue
        if BANNER not in rust.read_text(encoding="utf-8"):
            missing.append(str(rust.relative_to(ROOT)))
    for path in (
        ROOT / "src" / "lang" / "registry.rs",
        ROOT / "src" / "lang" / "packs" / "mod.rs",
        ROOT / "custom_components" / "klar_nlu" / "languages.py",
        ROOT / "tests" / "assist_langs.rs",
    ):
        if path.exists() and BANNER not in path.read_text(encoding="utf-8"):
            missing.append(str(path.relative_to(ROOT)))
    if missing:
        fail("generated files missing DO NOT EDIT banner:\n" + "\n".join(missing))


def main() -> None:
    if not PACKS.is_dir():
        fail("missing src/lang/packs")
    missing_repr = []
    for pack in sorted(path for path in PACKS.iterdir() if path.is_dir()):
        mapped = MOD_TO_TAG.get(pack.name, pack.name)
        if mapped == "ru" or pack.name == "ru":
            fail("russian pack must not ship")
        handwritten = pack.name in HANDWRITTEN
        if not handwritten and not (DATASETS / mapped / "representative.yaml").is_file():
            missing_repr.append(mapped)
        if not handwritten:
            for suite in PARITY_SUITES:
                if not (PARITY / mapped / suite).is_dir():
                    fail(f"{pack.name} missing parity suite tests/datasets/parity/{mapped}/{suite}")
        verbs = (pack / "verbs.rs").read_text(encoding="utf-8")
        speech = (pack / "speech.rs").read_text(encoding="utf-8")
        body = (pack / "pack.rs").read_text(encoding="utf-8")
        if "VerbKind::On" not in verbs or "VerbKind::Off" not in verbs:
            fail(f"{pack.name} missing On/Off verbs")
        if 'unknown: ""' in speech or 'confirm: ""' in speech:
            fail(f"{pack.name} has empty speech")
        if "light_nouns: &[]" in body:
            fail(f"{pack.name} has empty light_nouns")
        for field in ("teach:", "undo:", "clock:", "weather:"):
            if f"{field} &[]" in body:
                fail(f"{pack.name} household {field} is empty")
        if not handwritten and (FAKE_SUFFIX.search(body) or FAKE_SUFFIX.search(verbs)):
            fail(f"{pack.name} has synthetic suffix tokens")
        if pack.name not in DE_SCAFFOLD_OK and GERMAN_SCAFFOLD.search(body):
            fail(f"{pack.name} has German home-graph tokens")
        num_chunk = body[body.find("numbers:") : body.find("numbers:") + 2500] if "numbers:" in body else ""
        native_nums = [word for word in re.findall(r'\("([^"]+)", \d+\)', num_chunk) if not word.isdigit()]
        if len(native_nums) < 10:
            fail(f"{pack.name} needs native number words, got {native_nums[:5]}")
    if missing_repr:
        fail("missing representative.yaml for: " + ", ".join(missing_repr))
    registry = (ROOT / "src" / "lang" / "registry.rs").read_text(encoding="utf-8")
    if re.search(r'"ru"|ru-RU', registry):
        fail("registry must not list Russian")
    for rust in list(PARSE.rglob("*.rs")) + list(NLU.rglob("*.rs")):
        text = rust.read_text(encoding="utf-8")
        if BANNED.search(text):
            fail(f"{rust.relative_to(ROOT)} matches LangId::De/En")
        if rust.name.endswith("tests.rs"):
            continue
        if BANNED_ENGINE.search(text):
            fail(f"{rust.relative_to(ROOT)} hardcodes banned de/en tokens")
    check_size_gate()
    check_field_checklist()
    check_banners()
    check_default_catalog()
    print("lang pack gates ok")


if __name__ == "__main__":
    main()
