pub(crate) mod auth;
pub(crate) mod backup;
pub mod bootstrap;
pub(crate) mod bundle;
pub(crate) mod conversations;
pub(crate) mod dashboard;
pub(crate) mod home_sync;
pub(crate) mod lang_api;
pub(crate) mod lang_explain;
pub mod limits;
pub(crate) mod llm;
pub(crate) mod llm_calls;
pub(crate) mod metrics;
pub(crate) mod policies;
pub(crate) mod privacy;
pub(crate) mod speech;
pub mod state;
pub(crate) mod trainer;
pub(crate) mod trainer_apply;
pub(crate) mod trainer_args;
pub(crate) mod trainer_chat;
pub(crate) mod trainer_consent;
pub(crate) mod trainer_entity;
pub(crate) mod trainer_house;
pub(crate) mod trainer_phrases;
pub(crate) mod trainer_reads;
pub(crate) mod trainer_settings;
pub(crate) mod trainer_turns;
pub mod web;
pub mod wyoming;

pub use bootstrap::{run, RuntimeArgs};
pub use bundle::{BundleEntry, BundleRequest, BundleResponse};
pub use privacy::{hash_conversation_id, redact_entries, replay_tokens, NameMap};
pub use state::AppState;
