// @generated by scripts/lang_packs. DO NOT EDIT.
//! Compiled language table. de/en live in packs/ like every other locale.
//! Every compiled locale is first-class. The engine never matches De|En in parse.

use super::pack::LanguagePack;
use super::{packs, LangId};
use serde::Serialize;
use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(Debug, Clone, Copy, Serialize)]
pub struct LangMeta {
    pub code: &'static str,
    pub native_name: &'static str,
    pub script: &'static str,
    pub variants: &'static [&'static str],
}

struct LangRow {
    id: LangId,
    meta: LangMeta,
    pack: &'static LanguagePack,
}

const LANGS: &[LangRow] = &[
    LangRow {
        id: LangId::new("de"),
        meta: LangMeta { code: "de", native_name: "Deutsch", script: "Latn", variants: &["de", "de-DE"] },
        pack: &packs::de::PACK,
    },
    LangRow {
        id: LangId::new("en"),
        meta: LangMeta { code: "en", native_name: "English", script: "Latn", variants: &["en", "en-US"] },
        pack: &packs::en::PACK,
    },
    LangRow {
        id: LangId::new("fr"),
        meta: LangMeta { code: "fr", native_name: "Français", script: "Latn", variants: &["fr", "fr-FR"] },
        pack: &packs::fr::PACK,
    },
    LangRow {
        id: LangId::new("nl"),
        meta: LangMeta { code: "nl", native_name: "Nederlands", script: "Latn", variants: &["nl", "nl-NL", "nl-BE"] },
        pack: &packs::nl::PACK,
    },
    LangRow {
        id: LangId::new("es"),
        meta: LangMeta { code: "es", native_name: "Español", script: "Latn", variants: &["es", "es-ES", "es-MX"] },
        pack: &packs::es::PACK,
    },
    LangRow {
        id: LangId::new("it"),
        meta: LangMeta { code: "it", native_name: "Italiano", script: "Latn", variants: &["it", "it-IT"] },
        pack: &packs::it::PACK,
    },
    LangRow {
        id: LangId::new("pt"),
        meta: LangMeta { code: "pt", native_name: "Português", script: "Latn", variants: &["pt", "pt-PT"] },
        pack: &packs::pt::PACK,
    },
    LangRow {
        id: LangId::new("ca"),
        meta: LangMeta { code: "ca", native_name: "Català", script: "Latn", variants: &["ca", "ca-ES"] },
        pack: &packs::ca::PACK,
    },
    LangRow {
        id: LangId::new("ro"),
        meta: LangMeta { code: "ro", native_name: "Română", script: "Latn", variants: &["ro", "ro-RO"] },
        pack: &packs::ro::PACK,
    },
    LangRow {
        id: LangId::new("da"),
        meta: LangMeta { code: "da", native_name: "Dansk", script: "Latn", variants: &["da", "da-DK"] },
        pack: &packs::da::PACK,
    },
    LangRow {
        id: LangId::new("nb"),
        meta: LangMeta { code: "nb", native_name: "Norsk Bokmål", script: "Latn", variants: &["nb", "nb-NO"] },
        pack: &packs::nb::PACK,
    },
    LangRow {
        id: LangId::new("sv"),
        meta: LangMeta { code: "sv", native_name: "Svenska", script: "Latn", variants: &["sv", "sv-SE"] },
        pack: &packs::sv::PACK,
    },
    LangRow {
        id: LangId::new("fi"),
        meta: LangMeta { code: "fi", native_name: "Suomi", script: "Latn", variants: &["fi", "fi-FI"] },
        pack: &packs::fi::PACK,
    },
    LangRow {
        id: LangId::new("de-CH"),
        meta: LangMeta { code: "de-CH", native_name: "Schwyzerdütsch", script: "Latn", variants: &["de-CH"] },
        pack: &packs::de_ch::PACK,
    },
    LangRow {
        id: LangId::new("de-AT"),
        meta: LangMeta { code: "de-AT", native_name: "Deutsch (Österreich)", script: "Latn", variants: &["de-AT"] },
        pack: &packs::de_at::PACK,
    },
    LangRow {
        id: LangId::new("en-GB"),
        meta: LangMeta { code: "en-GB", native_name: "English (UK)", script: "Latn", variants: &["en-GB"] },
        pack: &packs::en_gb::PACK,
    },
    LangRow {
        id: LangId::new("pt-BR"),
        meta: LangMeta { code: "pt-BR", native_name: "Português (Brasil)", script: "Latn", variants: &["pt-BR"] },
        pack: &packs::pt_br::PACK,
    },
    LangRow {
        id: LangId::new("af"),
        meta: LangMeta { code: "af", native_name: "Afrikaans", script: "Latn", variants: &["af", "af-ZA"] },
        pack: &packs::af::PACK,
    },
    LangRow {
        id: LangId::new("cs"),
        meta: LangMeta { code: "cs", native_name: "Čeština", script: "Latn", variants: &["cs", "cs-CZ"] },
        pack: &packs::cs::PACK,
    },
    LangRow {
        id: LangId::new("sk"),
        meta: LangMeta { code: "sk", native_name: "Slovenčina", script: "Latn", variants: &["sk", "sk-SK"] },
        pack: &packs::sk::PACK,
    },
    LangRow {
        id: LangId::new("pl"),
        meta: LangMeta { code: "pl", native_name: "Polski", script: "Latn", variants: &["pl", "pl-PL"] },
        pack: &packs::pl::PACK,
    },
    LangRow {
        id: LangId::new("hu"),
        meta: LangMeta { code: "hu", native_name: "Magyar", script: "Latn", variants: &["hu", "hu-HU"] },
        pack: &packs::hu::PACK,
    },
    LangRow {
        id: LangId::new("hr"),
        meta: LangMeta { code: "hr", native_name: "Hrvatski", script: "Latn", variants: &["hr", "hr-HR"] },
        pack: &packs::hr::PACK,
    },
    LangRow {
        id: LangId::new("sl"),
        meta: LangMeta { code: "sl", native_name: "Slovenščina", script: "Latn", variants: &["sl", "sl-SI"] },
        pack: &packs::sl::PACK,
    },
    LangRow {
        id: LangId::new("bg"),
        meta: LangMeta { code: "bg", native_name: "Български", script: "Cyrl", variants: &["bg", "bg-BG"] },
        pack: &packs::bg::PACK,
    },
    LangRow {
        id: LangId::new("el"),
        meta: LangMeta { code: "el", native_name: "Ελληνικά", script: "Grek", variants: &["el", "el-GR"] },
        pack: &packs::el::PACK,
    },
    LangRow {
        id: LangId::new("sr"),
        meta: LangMeta { code: "sr", native_name: "Српски", script: "Cyrl", variants: &["sr", "sr-RS"] },
        pack: &packs::sr::PACK,
    },
    LangRow {
        id: LangId::new("sr-Latn"),
        meta: LangMeta { code: "sr-Latn", native_name: "Srpski", script: "Latn", variants: &["sr-Latn"] },
        pack: &packs::sr_latn::PACK,
    },
    LangRow {
        id: LangId::new("uk"),
        meta: LangMeta { code: "uk", native_name: "Українська", script: "Cyrl", variants: &["uk", "uk-UA"] },
        pack: &packs::uk::PACK,
    },
    LangRow {
        id: LangId::new("zh-CN"),
        meta: LangMeta { code: "zh-CN", native_name: "简体中文", script: "Hans", variants: &["zh-CN", "zh"] },
        pack: &packs::zh_cn::PACK,
    },
    LangRow {
        id: LangId::new("zh-TW"),
        meta: LangMeta { code: "zh-TW", native_name: "繁體中文（台灣）", script: "Hant", variants: &["zh-TW"] },
        pack: &packs::zh_tw::PACK,
    },
    LangRow {
        id: LangId::new("zh-HK"),
        meta: LangMeta { code: "zh-HK", native_name: "繁體中文（香港）", script: "Hant", variants: &["zh-HK"] },
        pack: &packs::zh_hk::PACK,
    },
    LangRow {
        id: LangId::new("ar"),
        meta: LangMeta { code: "ar", native_name: "العربية", script: "Arab", variants: &["ar", "ar-JO"] },
        pack: &packs::ar::PACK,
    },
    LangRow {
        id: LangId::new("he"),
        meta: LangMeta { code: "he", native_name: "עברית", script: "Hebr", variants: &["he", "he-IL"] },
        pack: &packs::he::PACK,
    },
    LangRow {
        id: LangId::new("fa"),
        meta: LangMeta { code: "fa", native_name: "فارسی", script: "Arab", variants: &["fa", "fa-IR"] },
        pack: &packs::fa::PACK,
    },
    LangRow {
        id: LangId::new("ur"),
        meta: LangMeta { code: "ur", native_name: "اُردُو", script: "Arab", variants: &["ur", "ur-IN"] },
        pack: &packs::ur::PACK,
    },
    LangRow {
        id: LangId::new("tr"),
        meta: LangMeta { code: "tr", native_name: "Türkçe", script: "Latn", variants: &["tr", "tr-TR"] },
        pack: &packs::tr::PACK,
    },
    LangRow {
        id: LangId::new("th"),
        meta: LangMeta { code: "th", native_name: "ภาษาไทย", script: "Thai", variants: &["th", "th-TH"] },
        pack: &packs::th::PACK,
    },
    LangRow {
        id: LangId::new("ko"),
        meta: LangMeta { code: "ko", native_name: "한국어", script: "Hang", variants: &["ko", "ko-KR"] },
        pack: &packs::ko::PACK,
    },
    LangRow {
        id: LangId::new("ja"),
        meta: LangMeta { code: "ja", native_name: "日本語", script: "Jpan", variants: &["ja", "ja-JP"] },
        pack: &packs::ja::PACK,
    },
    LangRow {
        id: LangId::new("cy"),
        meta: LangMeta { code: "cy", native_name: "Cymraeg", script: "Latn", variants: &["cy"] },
        pack: &packs::cy::PACK,
    },
    LangRow {
        id: LangId::new("et"),
        meta: LangMeta { code: "et", native_name: "Eesti", script: "Latn", variants: &["et", "et-EE"] },
        pack: &packs::et::PACK,
    },
    LangRow {
        id: LangId::new("eu"),
        meta: LangMeta { code: "eu", native_name: "Euskara", script: "Latn", variants: &["eu", "eu-ES"] },
        pack: &packs::eu::PACK,
    },
    LangRow {
        id: LangId::new("ga"),
        meta: LangMeta { code: "ga", native_name: "Gaeilge", script: "Latn", variants: &["ga", "ga-IE"] },
        pack: &packs::ga::PACK,
    },
    LangRow {
        id: LangId::new("gl"),
        meta: LangMeta { code: "gl", native_name: "Galician", script: "Latn", variants: &["gl", "gl-ES"] },
        pack: &packs::gl::PACK,
    },
    LangRow {
        id: LangId::new("is"),
        meta: LangMeta { code: "is", native_name: "islenska", script: "Latn", variants: &["is", "is-IS"] },
        pack: &packs::is::PACK,
    },
    LangRow {
        id: LangId::new("lb"),
        meta: LangMeta { code: "lb", native_name: "Letzebuergesch", script: "Latn", variants: &["lb", "lb-LU"] },
        pack: &packs::lb::PACK,
    },
    LangRow {
        id: LangId::new("kw"),
        meta: LangMeta { code: "kw", native_name: "kernewek", script: "Latn", variants: &["kw"] },
        pack: &packs::kw::PACK,
    },
    LangRow {
        id: LangId::new("lt"),
        meta: LangMeta { code: "lt", native_name: "Lietuviu", script: "Latn", variants: &["lt", "lt-LT"] },
        pack: &packs::lt::PACK,
    },
    LangRow {
        id: LangId::new("lv"),
        meta: LangMeta { code: "lv", native_name: "Latviesu", script: "Latn", variants: &["lv", "lv-LV"] },
        pack: &packs::lv::PACK,
    },
    LangRow {
        id: LangId::new("id"),
        meta: LangMeta { code: "id", native_name: "Bahasa Indonesia", script: "Latn", variants: &["id", "id-ID"] },
        pack: &packs::id::PACK,
    },
    LangRow {
        id: LangId::new("ms"),
        meta: LangMeta { code: "ms", native_name: "Bahasa Melayu", script: "Latn", variants: &["ms", "ms-MY"] },
        pack: &packs::ms::PACK,
    },
    LangRow {
        id: LangId::new("sw"),
        meta: LangMeta { code: "sw", native_name: "Kiswahili", script: "Latn", variants: &["sw", "sw-KE"] },
        pack: &packs::sw::PACK,
    },
    LangRow {
        id: LangId::new("vi"),
        meta: LangMeta { code: "vi", native_name: "Tieng Viet", script: "Latn", variants: &["vi", "vi-VN"] },
        pack: &packs::vi::PACK,
    },
    LangRow {
        id: LangId::new("hi"),
        meta: LangMeta { code: "hi", native_name: "Hindi", script: "Deva", variants: &["hi", "hi-IN"] },
        pack: &packs::hi::PACK,
    },
    LangRow {
        id: LangId::new("bn"),
        meta: LangMeta { code: "bn", native_name: "Bangla", script: "Beng", variants: &["bn", "bn-BD"] },
        pack: &packs::bn::PACK,
    },
    LangRow {
        id: LangId::new("gu"),
        meta: LangMeta { code: "gu", native_name: "Gujarati", script: "Gujr", variants: &["gu", "gu-IN"] },
        pack: &packs::gu::PACK,
    },
    LangRow {
        id: LangId::new("kn"),
        meta: LangMeta { code: "kn", native_name: "Kannada", script: "Knda", variants: &["kn", "kn-IN"] },
        pack: &packs::kn::PACK,
    },
    LangRow {
        id: LangId::new("ml"),
        meta: LangMeta { code: "ml", native_name: "Malayalam", script: "Mlym", variants: &["ml", "ml-IN"] },
        pack: &packs::ml::PACK,
    },
    LangRow {
        id: LangId::new("mr"),
        meta: LangMeta { code: "mr", native_name: "Marathi", script: "Deva", variants: &["mr", "mr-IN"] },
        pack: &packs::mr::PACK,
    },
    LangRow {
        id: LangId::new("ta"),
        meta: LangMeta { code: "ta", native_name: "Tamil", script: "Taml", variants: &["ta"] },
        pack: &packs::ta::PACK,
    },
    LangRow {
        id: LangId::new("te"),
        meta: LangMeta { code: "te", native_name: "Telugu", script: "Telu", variants: &["te", "te-IN"] },
        pack: &packs::te::PACK,
    },
    LangRow {
        id: LangId::new("pa"),
        meta: LangMeta { code: "pa", native_name: "Punjabi", script: "Guru", variants: &["pa"] },
        pack: &packs::pa::PACK,
    },
    LangRow {
        id: LangId::new("ne"),
        meta: LangMeta { code: "ne", native_name: "Nepali", script: "Deva", variants: &["ne", "ne-NP"] },
        pack: &packs::ne::PACK,
    },
    LangRow {
        id: LangId::new("hy"),
        meta: LangMeta { code: "hy", native_name: "Armenian", script: "Armn", variants: &["hy", "hy-AM"] },
        pack: &packs::hy::PACK,
    },
    LangRow {
        id: LangId::new("ka"),
        meta: LangMeta { code: "ka", native_name: "Georgian", script: "Geor", variants: &["ka", "ka-GE"] },
        pack: &packs::ka::PACK,
    },
    LangRow {
        id: LangId::new("mn"),
        meta: LangMeta { code: "mn", native_name: "Mongolian", script: "Cyrl", variants: &["mn", "mn-MN"] },
        pack: &packs::mn::PACK,
    },
];

pub fn all_ids() -> &'static [LangId] {
    static IDS: OnceLock<Vec<LangId>> = OnceLock::new();
    IDS.get_or_init(|| LANGS.iter().map(|row| row.id).collect()).as_slice()
}

fn row(code: &str) -> Option<&'static LangRow> {
    static IDX: OnceLock<HashMap<&'static str, usize>> = OnceLock::new();
    let map = IDX.get_or_init(|| LANGS.iter().enumerate().map(|(i, row)| (row.id.code(), i)).collect());
    map.get(code).map(|&i| &LANGS[i])
}

pub fn lookup(code: &str) -> Option<LangId> {
    row(code).map(|item| item.id)
}

pub fn pack(id: LangId) -> &'static LanguagePack {
    row(id.code()).map(|item| item.pack).unwrap_or_else(|| panic!("unregistered LangId `{}`", id.code()))
}

pub fn meta(id: LangId) -> Option<&'static LangMeta> {
    row(id.code()).map(|item| &item.meta)
}

pub fn languages() -> &'static [LangMeta] {
    static METAS: OnceLock<Vec<LangMeta>> = OnceLock::new();
    METAS.get_or_init(|| LANGS.iter().map(|row| row.meta).collect()).as_slice()
}
