"""Slavic, CJK, and MENA calendar lexemes."""

from __future__ import annotations


def east_packs(row, speech) -> dict[str, dict]:
    return {
        "cs": row(
            ["kalendar", "schuzka", "termin"],
            ["nadchazejici"],
            ["pridej", "naplanuj"],
            ["dnes"],
            ["zitra"],
            ["v"],
            ["pokracuj"],
            "co je v kalendari",
            "pridej zubare zitra v 15 kalendar",
            speech("Nerozumel jsem.", "{items}", "Zadne udalosti.", "Zadny kalendar.", "{summary} {when}.", "Jaky nazev?", "Kdy?", "Jen pro cteni.", "Zadny prehravac."),
        ),
        "sk": row(
            ["kalendar", "stretnutie"],
            ["nadchadzajuce"],
            ["pridaj", "naplanuj"],
            ["dnes"],
            ["zajtra"],
            ["o"],
            ["pokracuj"],
            "co je v kalendari",
            "pridaj zubara zajtra o 15 kalendar",
            speech("Nerozumel som.", "{items}", "Ziadne udalosti.", "Ziadny kalendar.", "{summary} {when}.", "Aky nazov?", "Kedy?", "Len na citanie.", "Ziadny prehravac."),
        ),
        "pl": row(
            ["kalendarz", "spotkanie", "wydarzenie"],
            ["nadchodzace"],
            ["dodaj", "zaplanuj"],
            ["dzis"],
            ["jutro"],
            ["o"],
            ["wznow", "kontynuuj"],
            "co jest w kalendarzu",
            "dodaj dentyste jutro o 15 kalendarz",
            speech("Nie zrozumialem.", "{items}", "Brak wydarzen.", "Brak kalendarza.", "{summary} {when}.", "Jaki tytul?", "Kiedy?", "Tylko odczyt.", "Brak odtwarzacza."),
        ),
        "hu": row(
            ["naptar", "talalkozo"],
            ["kovetkezo"],
            ["hozzaad", "tervezz"],
            ["ma"],
            ["holnap"],
            ["kor"],
            ["folytat"],
            "mi van a naptarban",
            "hozzaad fogorvos holnap 15 naptar",
            speech("Nem ertettem.", "{items}", "Nincs esemeny.", "Nincs naptar.", "{summary} {when}.", "Milyen cim?", "Mikor?", "Csak olvashato.", "Nincs lejatszo."),
        ),
        "hr": row(
            ["kalendar", "sastanak"],
            ["nadolazeci"],
            ["dodaj", "zakazi"],
            ["danas"],
            ["sutra"],
            ["u"],
            ["nastavi"],
            "sto je u kalendaru",
            "dodaj zubara sutra u 15 kalendar",
            speech("Nisam razumio.", "{items}", "Nema dogadaja.", "Nema kalendara.", "{summary} {when}.", "Koji naslov?", "Kada?", "Samo citanje.", "Nema sviraca."),
        ),
        "sl": row(
            ["koledar", "sestanek"],
            ["prihajajoci"],
            ["dodaj", "naroci"],
            ["danes"],
            ["jutri"],
            ["ob"],
            ["nadaljuj"],
            "kaj je v koledarju",
            "dodaj zobozdravnika jutri ob 15 koledar",
            speech("Nisem razumel.", "{items}", "Ni dogodkov.", "Ni koledarja.", "{summary} {when}.", "Kaksen naslov?", "Kdaj?", "Samo branje.", "Ni predvajalnika."),
        ),
        "bg": row(
            ["календар", "среща"],
            ["предстоящи"],
            ["добавя", "планирай"],
            ["днес"],
            ["утре"],
            ["в"],
            ["продължи"],
            "какво има в календара",
            "добавя зъболекар утре в 15 календар",
            speech("Не разбрах.", "{items}", "Няма събития.", "Няма календар.", "{summary} {when}.", "Какво заглавие?", "Кога?", "Само четене.", "Няма плеър."),
        ),
        "el": row(
            ["ημερολογιο", "ραντεβου"],
            ["επικειμενα"],
            ["προσθεσε", "κλεισε"],
            ["σημερα"],
            ["αυριο"],
            ["στις"],
            ["συνεχισε"],
            "τι εχει το ημερολογιο",
            "προσθεσε οδοντιατρο αυριο στις 15 ημερολογιο",
            speech("Δεν το καταλαβα.", "{items}", "Δεν υπαρχουν γεγονοτα.", "Δεν υπαρχει ημερολογιο.", "{summary} {when}.", "Τι τιτλος?", "Πότε?", "Μονο αναγνωση.", "Δεν υπαρχει παικτης."),
        ),
        "sr": row(
            ["календар", "састанак"],
            ["предстојећи"],
            ["додај", "закажи"],
            ["данас"],
            ["сутра"],
            ["у"],
            ["настави"],
            "шта је у календару",
            "додај зубара сутра у 15 календар",
            speech("Нисам разумео.", "{items}", "Нема догађаја.", "Нема календара.", "{summary} {when}.", "Који наслов?", "Када?", "Само читање.", "Нема плејера."),
        ),
        "sr-Latn": row(
            ["kalendar", "sastanak"],
            ["predstojeci"],
            ["dodaj", "zakazi"],
            ["danas"],
            ["sutra"],
            ["u"],
            ["nastavi"],
            "sta je u kalendaru",
            "dodaj zubara sutra u 15 kalendar",
            speech("Nisam razumeo.", "{items}", "Nema dogadjaja.", "Nema kalendara.", "{summary} {when}.", "Koji naslov?", "Kada?", "Samo citanje.", "Nema plejera."),
        ),
        "uk": row(
            ["календар", "зустріч"],
            ["найближчі"],
            ["додай", "заплануй"],
            ["сьогодні"],
            ["завтра"],
            ["о"],
            ["продовж"],
            "що в календарі",
            "додай стоматолога завтра о 15 календар",
            speech("Я не зрозумів.", "{items}", "Немає подій.", "Немає календаря.", "{summary} {when}.", "Яка назва?", "Коли?", "Лише читання.", "Немає плеєра."),
        ),
        "zh-CN": row(
            ["rili", "richeng", "日历", "日程"],
            ["jiuyao", "anpai"],
            ["tianjia", "yuyue"],
            ["jintian"],
            ["mingtian"],
            ["dian"],
            ["jixu"],
            "rili you shenme",
            "tianjia yasheng mingtian 15 rili",
            speech("我没听清。", "{items}", "没有日程。", "没有日历。", "{summary} {when}。", "叫什么？", "什么时候？", "日历只读。", "没有播放器。"),
        ),
        "zh-TW": row(
            ["rili", "richeng", "日曆", "行程"],
            ["jiuyao"],
            ["tianjia", "yuyue"],
            ["jintian"],
            ["mingtian"],
            ["dian"],
            ["jixu"],
            "rili you shenme",
            "tianjia yisheng mingtian 15 rili",
            speech("我沒聽清楚。", "{items}", "沒有行程。", "沒有日曆。", "{summary} {when}。", "叫什麼？", "什麼時候？", "日曆唯讀。", "沒有播放器。"),
        ),
        "zh-HK": row(
            ["rili", "richeng", "日曆"],
            ["jiuyao"],
            ["tianjia"],
            ["jintian"],
            ["mingtian"],
            ["dian"],
            ["jixu"],
            "rili you me",
            "tianjia yisang mingtian 15 rili",
            speech("我聽唔明。", "{items}", "冇行程。", "冇日曆。", "{summary} {when}。", "叫咩名？", "幾時？", "日曆唯讀。", "冇播放器。"),
        ),
        "ar": row(
            ["تقويم", "موعد", "مواعيد", "أجندة"],
            ["قادمة", "مواعيد"],
            ["أضف", "احجز"],
            ["اليوم"],
            ["غدا"],
            ["الساعة"],
            ["استأنف", "أكمل"],
            "ما في التقويم",
            "أضف طبيب غدا الساعة 15 تقويم",
            speech("ما فهمت.", "{items}", "لا مواعيد.", "لا تقويم.", "{summary} {when}.", "ما الاسم؟", "متى؟", "للقراءة فقط.", "لا مشغل."),
        ),
        "he": row(
            ["יומן", "לוח", "פגישה"],
            ["קרובות"],
            ["הוסף", "קבע"],
            ["היום"],
            ["מחר"],
            ["ב"],
            ["המשך"],
            "מה ביומן",
            "הוסף רופא מחר ב 15 יומן",
            speech("לא הבנתי.", "{items}", "אין אירועים.", "אין יומן.", "{summary} {when}.", "איזה שם?", "מתי?", "לקריאה בלבד.", "אין נגן."),
        ),
        "fa": row(
            ["تقویم", "قرار"],
            ["آینده"],
            ["اضافه", "ثبت"],
            ["امروز"],
            ["فردا"],
            ["ساعت"],
            ["ادامه"],
            "تقویم چیست",
            "اضافه دندانپزشک فردا ساعت 15 تقویم",
            speech("متوجه نشدم.", "{items}", "رویدادی نیست.", "تقویمی نیست.", "{summary} {when}.", "چه نامی؟", "کی؟", "فقط خواندنی.", "پخش‌کننده‌ای نیست."),
        ),
        "ur": row(
            ["کیلنڈر", "ملاقات"],
            ["آنے والی"],
            ["شامل", "رکھو"],
            ["آج"],
            ["کل"],
            ["بجے"],
            ["جاری"],
            "کیلنڈر میں کیا ہے",
            "شامل دانت کل 15 کیلنڈر",
            speech("سمجھ نہیں آیا۔", "{items}", "کوئی تقریب نہیں۔", "کیلنڈر نہیں۔", "{summary} {when}.", "کیا نام؟", "کب؟", "صرف پڑھنے کے لیے۔", "کوئی پلیئر نہیں۔"),
        ),
        "tr": row(
            ["takvim", "randevu"],
            ["yaklasan"],
            ["ekle", "ayir"],
            ["bugun"],
            ["yarin"],
            ["saat"],
            ["devam"],
            "takvimde ne var",
            "ekle disci yarin saat 15 takvim",
            speech("Anlamadim.", "{items}", "Etkinlik yok.", "Takvim yok.", "{summary} {when}.", "Baslik?", "Ne zaman?", "Salt okunur.", "Oynatici yok."),
        ),
        "th": row(
            ["ปฏิทิน", "นัด"],
            ["ที่จะมา"],
            ["เพิ่ม", "จอง"],
            ["วันนี้"],
            ["พรุ่งนี้"],
            ["โมง"],
            ["ต่อ"],
            "ปฏิทิน มีอะไร",
            "เพิ่ม หมอ พรุ่งนี้ 15 ปฏิทิน",
            speech("ฟังไม่ทัน", "{items}", "ไม่มีนัด", "ไม่มีปฏิทิน", "{summary} {when}", "ชื่ออะไร", "เมื่อไหร่", "อ่านอย่างเดียว", "ไม่มีเครื่องเล่น"),
        ),
        "ko": row(
            ["dallyeok", "iljeong", "캘린더", "일정"],
            ["yajeong"],
            ["chuga", "yeyak"],
            ["oneul"],
            ["naeil"],
            ["si"],
            ["gyesok"],
            "dallyeok e mwo isseo",
            "chuga chigwa naeil 15 dallyeok",
            speech("잘 못 들었어요.", "{items}", "일정이 없어요.", "캘린더가 없어요.", "{summary} {when}.", "제목은요?", "언제요?", "읽기 전용이에요.", "재생기가 없어요."),
        ),
        "ja": row(
            ["karendaa", "yotei", "カレンダー", "予定"],
            ["yotei"],
            ["irete", "tsuika"],
            ["kyou"],
            ["ashita"],
            ["ji"],
            ["saikai", "tsuzuke"],
            "nani yotei",
            "irete haisha ashita 15 karendaa",
            speech("聞き取れませんでした。", "{items}", "予定はありません。", "カレンダーがありません。", "{summary} {when}。", "タイトルは？", "いつ？", "読み取り専用です。", "プレーヤーがありません。"),
        ),
    }
