"""Calendar nouns, query/create cues, when-words, and spoken bodies per pack.

Every Assist code has native (or pack-script) lexemes. extras.py must not be
the only source for CJK / MENA / Indic.
"""

from __future__ import annotations

from lang_packs.calendar_lex_east import east_packs
from lang_packs.calendar_lex_more import merge_more
from lang_packs.calendar_ops_lex import merge_ops
from lang_packs.native_apply import apply_calendar


def _sp(
    unknown: str,
    listed: str,
    empty: str,
    none: str,
    created: str,
    need_title: str,
    need_when: str,
    readonly: str,
    no_music: str,
) -> dict[str, str]:
    return {
        "unknown": unknown,
        "calendar_list": listed,
        "calendar_empty": empty,
        "calendar_none": none,
        "calendar_created": created,
        "calendar_need_title": need_title,
        "calendar_need_when": need_when,
        "calendar_readonly": readonly,
        "no_music_player": no_music,
    }


def _row(
    nouns: list[str],
    query: list[str],
    create: list[str],
    today: list[str],
    tomorrow: list[str],
    when: list[str],
    resume: list[str],
    list_smoke: str,
    create_smoke: str,
    speech: dict[str, str],
) -> dict:
    return {
        "nouns": nouns,
        "query": query,
        "create": create,
        "today": today,
        "tomorrow": tomorrow,
        "when": when,
        "resume": resume,
        "list_smoke": list_smoke,
        "create_smoke": create_smoke,
        "speech": speech,
    }


# code -> lexicon. Keys match ALL_CORES / extras codes plus handwritten de/en.
CALENDAR: dict[str, dict] = {
    "de": _row(
        ["kalender", "termin", "termine", "agenda"],
        ["steht", "anstehend", "kommende", "nächste", "naechste"],
        ["anlegen", "eintragen", "planen", "setz"],
        ["heute"],
        ["morgen"],
        ["um", "uhr", "montag", "dienstag", "mittwoch", "donnerstag", "freitag", "samstag", "sonntag"],
        ["weiter", "fortsetzen"],
        "was steht im kalender",
        "termin zahnarzt morgen um 15 uhr",
        _sp(
            "Das habe ich nicht verstanden.",
            "{items}",
            "Keine anstehenden Termine.",
            "Kein Kalender ist verfügbar.",
            "{summary} {when}.",
            "Wie soll der Termin heißen?",
            "Wann ist der Termin?",
            "Dieser Kalender lässt sich nicht ändern.",
            "Kein Musikspieler ist verfügbar.",
        ),
    ),
    "en": _row(
        ["calendar", "calendars", "event", "events", "agenda", "appointment", "appointments"],
        ["upcoming", "schedule", "agenda"],
        ["schedule", "book", "add"],
        ["today"],
        ["tomorrow"],
        ["at", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
        ["resume", "unpause", "continue"],
        "whats on my calendar",
        "add dentist tomorrow at 3 to my calendar",
        _sp(
            "I did not catch that.",
            "{items}",
            "No upcoming events.",
            "No calendar is available.",
            "{summary} {when}.",
            "What should I call the event?",
            "When is the event?",
            "That calendar cannot be changed.",
            "No music player is available.",
        ),
    ),
    "fr": _row(
        ["calendrier", "agenda", "rendez-vous", "rdv"],
        ["prochains", "venir", "agenda"],
        ["ajoute", "planifie", "cree"],
        ["aujourdhui"],
        ["demain"],
        ["a", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
        ["reprends", "continue"],
        "quels sont mes rendez-vous",
        "ajoute dentiste demain a 15 calendrier",
        _sp("Je n'ai pas compris.", "{items}", "Aucun rendez-vous.", "Pas de calendrier.", "{summary} {when}.", "Quel titre ?", "Quand ?", "Calendrier en lecture seule.", "Pas de lecteur musique."),
    ),
    "nl": _row(
        ["kalender", "agenda", "afspraak", "afspraken"],
        ["komende", "agenda"],
        ["voeg", "plan", "zet"],
        ["vandaag"],
        ["morgen"],
        ["om", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"],
        ["hervat", "verder"],
        "wat staat in de agenda",
        "voeg tandarts morgen om 15 kalender",
        _sp("Dat begreep ik niet.", "{items}", "Geen afspraken.", "Geen kalender.", "{summary} {when}.", "Welke titel?", "Wanneer?", "Kalender is alleen-lezen.", "Geen muziekspeler."),
    ),
    "es": _row(
        ["calendario", "agenda", "cita", "citas", "evento"],
        ["proximos", "agenda"],
        ["anade", "agenda", "crea"],
        ["hoy"],
        ["manana"],
        ["a", "lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"],
        ["reanuda", "continua"],
        "que hay en el calendario",
        "anade dentista manana a 15 calendario",
        _sp("No lo he entendido.", "{items}", "No hay citas.", "No hay calendario.", "{summary} {when}.", "Que titulo?", "Cuando?", "Calendario solo lectura.", "No hay reproductor."),
    ),
    "it": _row(
        ["calendario", "agenda", "appuntamento", "eventi"],
        ["prossimi", "agenda"],
        ["aggiungi", "prenota", "crea"],
        ["oggi"],
        ["domani"],
        ["alle", "lunedi", "martedi", "mercoledi", "giovedi", "venerdi", "sabato", "domenica"],
        ["riprendi", "continua"],
        "cosa c e in calendario",
        "aggiungi dentista domani alle 15 calendario",
        _sp("Non ho capito.", "{items}", "Nessun appuntamento.", "Nessun calendario.", "{summary} {when}.", "Che titolo?", "Quando?", "Calendario in sola lettura.", "Nessun lettore."),
    ),
    "pt": _row(
        ["calendario", "agenda", "compromisso", "eventos"],
        ["proximos", "agenda"],
        ["adiciona", "marca", "cria"],
        ["hoje"],
        ["amanha"],
        ["as", "segunda", "terca", "quarta", "quinta", "sexta", "sabado", "domingo"],
        ["retoma", "continua"],
        "o que esta no calendario",
        "adiciona dentista amanha as 15 calendario",
        _sp("Nao percebi.", "{items}", "Sem eventos.", "Sem calendario.", "{summary} {when}.", "Que titulo?", "Quando?", "Calendario so leitura.", "Sem leitor de musica."),
    ),
    "ca": _row(
        ["calendari", "agenda", "cita"],
        ["propers", "agenda"],
        ["afegeix", "planifica"],
        ["avui"],
        ["dema"],
        ["a", "dilluns", "dimarts"],
        ["repren", "continua"],
        "que hi ha al calendari",
        "afegeix dentista dema a 15 calendari",
        _sp("No ho he entes.", "{items}", "Cap cita.", "Cap calendari.", "{summary} {when}.", "Quin titol?", "Quan?", "Nomes lectura.", "Cap reproductor."),
    ),
    "ro": _row(
        ["calendar", "agenda", "programare"],
        ["urmatoare", "agenda"],
        ["adauga", "programeaza"],
        ["azi"],
        ["maine"],
        ["la", "luni", "marti"],
        ["reia", "continua"],
        "ce e in calendar",
        "adauga dentist maine la 15 calendar",
        _sp("Nu am inteles.", "{items}", "Niciun eveniment.", "Niciun calendar.", "{summary} {when}.", "Ce titlu?", "Cand?", "Doar citire.", "Niciun player."),
    ),
    "da": _row(
        ["kalender", "aftale", "aftaler"],
        ["kommende", "aftaler"],
        ["tilfoj", "book"],
        ["i dag", "idag"],
        ["i morgen", "imorgen"],
        ["kl", "mandag"],
        ["genoptag", "fortsaet"],
        "hvad er i kalenderen",
        "tilfoj tandlaege imorgen kl 15 kalender",
        _sp("Det forstod jeg ikke.", "{items}", "Ingen aftaler.", "Ingen kalender.", "{summary} {when}.", "Hvilken titel?", "Hvornar?", "Skrivebeskyttet.", "Ingen afspiller."),
    ),
    "nb": _row(
        ["kalender", "avtale", "avtaler"],
        ["kommende", "avtaler"],
        ["legg", "book"],
        ["i dag", "idag"],
        ["i morgen", "imorgen"],
        ["kl", "mandag"],
        ["gjenoppta", "fortsett"],
        "hva star i kalenderen",
        "legg tannlege imorgen kl 15 kalender",
        _sp("Det skjonte jeg ikke.", "{items}", "Ingen avtaler.", "Ingen kalender.", "{summary} {when}.", "Hvilken tittel?", "Nar?", "Skrivebeskyttet.", "Ingen spiller."),
    ),
    "sv": _row(
        ["kalender", "mote", "moten"],
        ["kommande", "schema"],
        ["lagg", "boka"],
        ["idag"],
        ["imorgon"],
        ["kl", "mandag"],
        ["aterta", "fortsatt"],
        "vad star i kalendern",
        "lagg tandlakare imorgon kl 15 kalender",
        _sp("Jag hangde inte med.", "{items}", "Inga moten.", "Ingen kalender.", "{summary} {when}.", "Vilken titel?", "Nar?", "Skrivskyddad.", "Ingen spelare."),
    ),
    "fi": _row(
        ["kalenteri", "tapaaminen", "ajat"],
        ["tulevat", "ajat"],
        ["lisaa", "varaa"],
        ["tanaan"],
        ["huomenna"],
        ["klo", "maanantai"],
        ["jatka"],
        "mita kalenterissa",
        "lisaa hammaslaakari huomenna klo 15 kalenteri",
        _sp("En saanut kiinni.", "{items}", "Ei tapahtumia.", "Ei kalenteria.", "{summary} {when}.", "Mika otsikko?", "Milloin?", "Vain luku.", "Ei soitinta."),
    ),
    "de-CH": _row(
        ["kalender", "termin", "träff"],
        ["staht", "chömend"],
        ["ilegeh", "plane"],
        ["hüt"],
        ["morn"],
        ["um", "uhr"],
        ["wiiter", "witer"],
        "was staht im kalender",
        "termin zahnarzt morn um 15 uhr",
        _sp("Das han i nöd verstande.", "{items}", "Kei Terminä.", "Kei Kalender.", "{summary} {when}.", "Wie heisst de Termin?", "Wänn?", "Nur läse.", "Kei Musigspieler."),
    ),
    "de-AT": _row(
        ["kalender", "termin", "termine"],
        ["steht", "anstehend"],
        ["anlegen", "eintragen"],
        ["heute"],
        ["morgen"],
        ["um", "uhr"],
        ["weiter", "fortsetzen"],
        "was steht im kalender",
        "termin zahnarzt morgen um 15 uhr",
        _sp("Des hob i ned verstanden.", "{items}", "Keine Termine.", "Kein Kalender.", "{summary} {when}.", "Wie soll er heissen?", "Wann?", "Nur lesen.", "Kein Musikspieler."),
    ),
    "en-GB": _row(
        ["calendar", "diaries", "appointment"],
        ["upcoming", "diary"],
        ["schedule", "add", "book"],
        ["today"],
        ["tomorrow"],
        ["at"],
        ["resume", "unpause"],
        "whats on my calendar",
        "add dentist tomorrow at 3 to my calendar",
        _sp("I did not catch that.", "{items}", "No upcoming events.", "No calendar is available.", "{summary} {when}.", "What should I call it?", "When is it?", "That calendar cannot be changed.", "No music player is available."),
    ),
    "pt-BR": _row(
        ["calendario", "agenda", "compromisso"],
        ["proximos", "agenda"],
        ["adiciona", "marca"],
        ["hoje"],
        ["amanha"],
        ["as"],
        ["retoma", "continua"],
        "o que tem no calendario",
        "adiciona dentista amanha as 15 calendario",
        _sp("Nao entendi.", "{items}", "Sem eventos.", "Sem calendario.", "{summary} {when}.", "Qual titulo?", "Quando?", "Somente leitura.", "Sem player."),
    ),
    "af": _row(
        ["kalender", "afspraak"],
        ["komende"],
        ["voeg", "skeduleer"],
        ["vandag"],
        ["more"],
        ["om"],
        ["hervat"],
        "wat is op die kalender",
        "voeg tandarts more om 15 kalender",
        _sp("Ek het dit nie verstaan nie.", "{items}", "Geen afsprake.", "Geen kalender.", "{summary} {when}.", "Watter titel?", "Wanneer?", "Leesalleen.", "Geen speler."),
    ),
}

CALENDAR.update(east_packs(_row, _sp))


merge_more(CALENDAR, _row, _sp)
merge_ops(CALENDAR)
apply_calendar(CALENDAR)


def calendar_for(code: str) -> dict:
    return CALENDAR.get(code) or CALENDAR["en"]
