"""Locale-native vacuum dock/return and media-play words for generated packs.

Keep play distinct from light-on. Do not list English `dock` unless that locale
treats it as a dock/off word (en-GB).
"""

from __future__ import annotations

# code -> return/home/station words (VerbKind::Dock)
DOCK = {
    "fr": ["base", "station", "rentrer"],
    "nl": ["terug", "station", "thuis"],
    "es": ["base", "estacion"],
    "it": ["base", "stazione"],
    "pt": ["base", "estacao"],
    "ca": ["base", "estacio"],
    "ro": ["baza", "statie"],
    "da": ["station", "hjem"],
    "nb": ["stasjon", "hjem"],
    "sv": ["station", "hem"],
    "fi": ["asema", "kotiin"],
    "de-CH": ["zurueck", "station"],
    "de-AT": ["zurueck", "station"],
    "en-GB": ["dock", "station", "base"],
    "pt-BR": ["base", "estacao"],
    "af": ["stasie", "terug"],
    "cs": ["stanice", "domu", "zpet"],
    "sk": ["stanica", "domov"],
    "pl": ["stacja", "baza"],
    "hu": ["allomas", "haza"],
    "hr": ["stanica", "baza"],
    "sl": ["postaja", "baza"],
    "bg": ["станция", "база"],
    "el": ["βαση", "σταθμος"],
    "sr": ["станица", "база"],
    "sr-Latn": ["stanica", "baza"],
    "uk": ["станція", "база"],
    "zh-CN": ["huijia", "jichong"],
    "zh-TW": ["huijia", "jichong"],
    "zh-HK": ["huijia", "jichong"],
    "ar": ["قاعدة", "محطة"],
    "he": ["בסיס", "תחנה"],
    "fa": ["پایگاه", "ایستگاه"],
    "ur": ["اسٹیشن", "بیس"],
    "tr": ["istasyon", "us"],
    "th": ["than", "ban"],
    "ko": ["jeonggeojang", "gwijhwan"],
    "ja": ["kidou", "kaiki"],
    "cy": ["gorsaf", "adref"],
    "et": ["jaam", "koju"],
    "eu": ["estazio", "etxe"],
    "ga": ["staisiun", "abhaile"],
    "gl": ["base", "estacion"],
    "is": ["stod", "heim"],
    "lb": ["statioun", "zeréck"],
    "kw": ["savla", "tre"],
    "lt": ["stotele", "namo"],
    "lv": ["stacija", "maja"],
    "id": ["pangkalan", "stasiun"],
    "ms": ["pangkalan", "stesen"],
    "sw": ["kituo", "nyumbani"],
    "vi": ["tram", "ve"],
    "hi": ["station", "ghar"],
    "bn": ["station", "bari"],
    "gu": ["station", "ghar"],
    "kn": ["station", "mane"],
    "ml": ["station", "veedu"],
    "mr": ["station", "ghar"],
    "ta": ["station", "veedu"],
    "te": ["station", "illu"],
    "pa": ["station", "ghar"],
    "ne": ["station", "ghar"],
    "hy": ["kayan", "tun"],
    "ka": ["sadguri", "saxlshi"],
    "mn": ["buudal", "ger"],
}

# code -> media-play words (never the light-on verb)
PLAY = {
    "fr": ["joue", "lecture"],
    "nl": ["speel"],
    "es": ["reproduce"],
    "it": ["riproduci"],
    "pt": ["toca"],
    "ca": ["reprodueix"],
    "ro": ["redata"],
    "da": ["spil"],
    "nb": ["spill"],
    "sv": ["spela"],
    "fi": ["soita"],
    "de-CH": ["spiel"],
    "de-AT": ["spiel"],
    "en-GB": ["play"],
    "pt-BR": ["toca"],
    "af": ["speel"],
    "cs": ["pust", "play"],
    "sk": ["pust"],
    "pl": ["odtworz"],
    "hu": ["jatszd"],
    "hr": ["pokreni"],
    "sl": ["predvajaj"],
    "bg": ["пусни"],
    "el": ["παιξε"],
    "sr": ["пусти"],
    "sr-Latn": ["pusti"],
    "uk": ["грай"],
    "zh-CN": ["bofang"],
    "zh-TW": ["bofang"],
    "zh-HK": ["bofang"],
    "ar": ["تشغيل"],
    "he": ["נגן"],
    "fa": ["پخش"],
    "ur": ["چلاو"],
    "tr": ["oynat"],
    "th": ["len"],
    "ko": ["jaesaeng"],
    "ja": ["saisei"],
    "cy": ["chwarae"],
    "et": ["mangi"],
    "eu": ["erreproduzitu"],
    "ga": ["seinn"],
    "gl": ["reproduce"],
    "is": ["spila"],
    "lb": ["spill"],
    "kw": ["gwari"],
    "lt": ["grotu"],
    "lv": ["atskanot"],
    "id": ["putar"],
    "ms": ["mainkan"],
    "sw": ["cheza"],
    "vi": ["phat"],
    "hi": ["bajao"],
    "bn": ["bajao"],
    "gu": ["vagad"],
    "kn": ["bajisu"],
    "ml": ["okke"],
    "mr": ["vajav"],
    "ta": ["valu"],
    "te": ["vadu"],
    "pa": ["vajao"],
    "ne": ["bajau"],
    "hy": ["nvarel"],
    "ka": ["daukare"],
    "mn": ["toglogch"],
}


def dock_words(code: str) -> list[str]:
    return list(DOCK.get(code, []))


def play_words(code: str) -> list[str]:
    return list(PLAY.get(code, []))
