"""Rust literal helpers for compiled Assist packs."""

from __future__ import annotations

from lang_packs.fold import fold_latin

RUST_BANNER = "// @generated by scripts/lang_packs. DO NOT EDIT.\n"
PY_BANNER = "# @generated by scripts/lang_packs. DO NOT EDIT.\n"

def rust_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rust_slice(values: list[str], indent: str = "        ", fold: bool = True, width: int = 80) -> str:
    items = unique(values) if fold else list(values)
    if not items:
        return "&[]"
    rendered = ", ".join(rust_str(item) for item in items)
    if len(rendered) < width:
        return f"&[{rendered}]"
    inner = ",\n".join(f"{indent}    {rust_str(item)}" for item in items)
    return f"&[\n{inner},\n{indent}]"


def rust_personality(pairs: list[tuple[str, list[str]]], indent: str = "    ") -> str:
    if not pairs:
        return "&[]"
    inner = ",\n".join(f"{indent}    ({rust_str(key)}, {rust_slice(variants, indent + '    ', fold=False, width=72)})" for key, variants in pairs)
    return f"&[\n{inner},\n{indent}]"


def rust_pairs(pairs: list[tuple[str, str]], indent: str = "        ") -> str:
    folded = []
    seen: set[str] = set()
    for left, right in pairs:
        key = fold_latin(left)
        if not key or key in seen:
            continue
        seen.add(key)
        folded.append((key, right))
    if not folded:
        return "&[]"
    inner = ",\n".join(f"{indent}    ({rust_str(a)}, {rust_str(b)})" for a, b in folded)
    return f"&[\n{inner},\n{indent}]"


def unique(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in values:
        key = fold_latin(item.strip())
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(key)
    return sorted(out)


def unique_verbs(verbs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    seen: set[str] = set()
    out: list[tuple[str, str]] = []
    for word, kind in verbs:
        folded = fold_latin(word)
        if not folded or folded in seen:
            continue
        seen.add(folded)
        out.append((folded, kind))
    return sorted(out, key=lambda row: row[0])


rust_list = rust_slice
