#!/usr/bin/env python3
"""Generate compiled Assist language packs.

de/en already live under src/lang/packs/ as hand-written reference packs.
This script never overwrites them; it only registers their paths.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lang_packs.emit import write_pack, write_registry, write_speech, rust_str
from lang_packs.ha_ui import write_ha_translations
from lang_packs.web_ui import write_web_ui_translations
from lang_packs.expand import expand
from lang_packs.lexicons import ALL_CORES, BUILTINS
from lang_packs.speech_slots import slot_gaps
from lang_packs.voices import HAND_BUNDLES, locale_bundle, PERSONALITY_KEYS


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate compiled Assist language packs")
    parser.add_argument("--skip-ha", action="store_true", help="Do not write HA JSON translations")
    parser.add_argument("--skip-web", action="store_true", help="Do not write web UI translations")
    parser.add_argument(
        "--speech-only",
        action="store_true",
        help="Write speech.rs + speech_locale/refine/post-exec only (implies --skip-ha --skip-web)",
    )
    parser.add_argument(
        "--packs-only",
        action="store_true",
        help="Write Rust packs + registry, skip HA/web JSON",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    missing = slot_gaps()
    if missing:
        raise SystemExit("speech slot tables missing: " + ", ".join(missing))
    generated = [expand(core) for core in ALL_CORES]
    if args.speech_only:
        for lang in generated:
            write_speech(lang)
            print("wrote speech", lang["code"])
        write_speech_locale(generated)
        write_refine_shots(generated)
        write_post_exec(generated)
        print("speech-only", len(generated))
        return
    for lang in generated:
        write_pack(lang)
        print("wrote", lang["code"])
    registry = BUILTINS + generated
    write_registry(registry)
    smoke = Path(__file__).resolve().parents[2] / "tests" / "assist_langs.rs"
    cases = []
    for code, text, intent in (
        ("de", "licht wohnzimmer an", "HassTurnOn"),
        ("de", "licht kuche aus", "HassTurnOff"),
        ("de", "was steht an", "KlarGetCalendarEvents"),
        ("de", "termin zahnarzt morgen um 15 uhr", "KlarCreateCalendarEvent"),
        ("de", "loesch zahnarzt kalender", "KlarDeleteCalendarEvent"),
        ("de", "verschieb zahnarzt morgen um 16 kalender", "KlarMoveCalendarEvent"),
        ("en", "turn on the living room light", "HassTurnOn"),
        ("en", "turn off the kitchen light", "HassTurnOff"),
        ("en", "whats on my calendar", "KlarGetCalendarEvents"),
        ("en", "add dentist tomorrow at 3 to my calendar", "KlarCreateCalendarEvent"),
        ("en", "delete dentist calendar", "KlarDeleteCalendarEvent"),
        ("en", "move dentist tomorrow at 4 calendar", "KlarMoveCalendarEvent"),
    ):
        cases.append(f'    ("{code}", "{text}", "{intent}"),')
    for lang in generated:
        for text, intent in lang.get("smoke", []):
            if intent.startswith(("HassTurn", "KlarGetCalendar", "KlarCreateCalendar", "KlarDeleteCalendar", "KlarMoveCalendar")):
                cases.append(f'    ("{lang["code"]}", "{text}", "{intent}"),')
    smoke.write_text(
        """// @generated by scripts/lang_packs. DO NOT EDIT.
use klar_nlu::home::default_home;
use klar_nlu::nlu::parse;
use klar_nlu::session::Session;
use klar_nlu::types::{ParseDecision, Settings};

const CASES: &[(&str, &str, &str)] = &[
"""
        + "\n".join(cases)
        + """
];

#[test]
fn compiled_assist_packs_execute_home_commands() {
    let home = default_home();
    for (lang, text, intent) in CASES {
        assert_ne!(*lang, "ru", "russian is not shipped");
        let settings = Settings { languages: vec![(*lang).into()], ..Settings::default() };
        let mut session = Session::default();
        let outcome = parse(text, &home, &mut session, &[], &settings);
        let names: Vec<_> =
            outcome.plan.as_ref().map(|plan| plan.intents().into_iter().map(|item| item.name).collect()).unwrap_or_default();
        assert!(
            matches!(outcome.decision, ParseDecision::Execute) && names.iter().any(|name| name == intent),
            "{lang} {text} decision={:?} intents={names:?}",
            outcome.decision
        );
    }
}

#[test]
fn russian_is_not_a_compiled_pack() {
    assert!(klar_nlu::lang::LangId::from_code("ru").is_none());
    assert!(!klar_nlu::lang::LangId::all().iter().any(|id| id.code() == "ru"));
}
""",
        encoding="utf-8",
    )
    datasets = Path(__file__).resolve().parents[2] / "tests" / "datasets" / "assist"
    for lang in generated:
        dest = datasets / lang["code"]
        dest.mkdir(parents=True, exist_ok=True)
        rows = []
        for text, intent in lang.get("smoke", []):
            kind = {
                "HassTurnOn": "light_on",
                "HassTurnOff": "light_off",
                "KlarGetCalendarEvents": "calendar_list",
                "KlarCreateCalendarEvent": "calendar_create",
                "KlarDeleteCalendarEvent": "calendar_delete",
                "KlarMoveCalendarEvent": "calendar_move",
                "MassPlayMedia": "play_media",
            }.get(intent, intent.lower())
            rows.append(
                f"- name: {kind}\n  sentences:\n    - {text}\n  nlu_expect:\n    intents:\n      - intent: {intent}\n"
            )
        (dest / "representative.yaml").write_text("".join(rows), encoding="utf-8")
    write_speech_locale(generated)
    write_refine_shots(generated)
    write_post_exec(generated)
    skip_ha = args.skip_ha or args.packs_only
    skip_web = args.skip_web or args.packs_only
    if not skip_ha:
        write_ha_translations()
    if not skip_web:
        write_web_ui_translations()
    print("registry", len(registry), "languages", "skip_ha" if skip_ha else "ha", "skip_web" if skip_web else "web")


def write_speech_locale(generated: list[dict]) -> None:
    packs = dict(HAND_BUNDLES)
    shots: dict[str, dict[str, str]] = {
        "de": {},
        "en": {},
    }
    for lang in generated:
        bundle = locale_bundle(lang)
        packs[lang["code"]] = bundle
        shots[lang["code"]] = refine_shot_rows(bundle)
    dest = Path(__file__).resolve().parents[2] / "custom_components" / "klar_nlu" / "speech_locale.py"
    dest.write_text(
        "# @generated by scripts/lang_packs. DO NOT EDIT.\n\n"
        f"SPEECH_PACKS = {repr(packs)}\n\n"
        f"REFINE_SHOTS = {repr(shots)}\n",
        encoding="utf-8",
    )
    print("wrote speech_locale", dest)


def write_refine_shots(generated: list[dict]) -> None:
    dest = Path(__file__).resolve().parents[2] / "src" / "llm" / "refine_shots.rs"
    chunks: list[list[dict]] = [[] for _ in range(6)]
    for index, lang in enumerate(generated):
        chunks[index % 6].append(lang)
    names = tuple(f"refine_shots_{chr(ord('a') + i)}" for i in range(6))
    mods = []
    for name, langs in zip(names, chunks):
        rows = []
        for lang in langs:
            shots = refine_shot_rows(locale_bundle(lang))
            for key, value in shots.items():
                rows.append(f"    ({rust_str(lang['code'])}, {rust_str(key)}, {rust_str(value)}),")
        part = Path(__file__).resolve().parents[2] / "src" / "llm" / f"{name}.rs"
        part.write_text(
            "// @generated by scripts/lang_packs. DO NOT EDIT.\n"
            "pub(super) const ROWS: &[(&str, &str, &str)] = &[\n"
            + "\n".join(rows)
            + "\n];\n",
            encoding="utf-8",
        )
        mods.append(name)
        print("wrote", part)
    dest.write_text(
        "// @generated by scripts/lang_packs. DO NOT EDIT.\n"
        "//! Refine example shots for generated Assist locales. de/en stay handwritten.\n\n"
        "pub fn locale_shots(pack: &str, personality: &str) -> &'static str {\n"
        "    for rows in ["
        + ", ".join(f"super::{name}::ROWS" for name in mods)
        + "] {\n"
        "        for (code, key, shots) in rows {\n"
        "            if *code == pack && *key == personality {\n"
        "                return shots;\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    \"\"\n"
        "}\n",
        encoding="utf-8",
    )
    print("wrote refine_shots", dest)


def write_post_exec(generated: list[dict]) -> None:
    dest = Path(__file__).resolve().parents[2] / "src" / "speech" / "generated.rs"
    rows = []
    for lang in generated:
        bundle = locale_bundle(lang)
        on = bundle.get("turn_on") or "{target} is on."
        off = bundle.get("turn_off") or "{target} is off."
        temp = bundle.get("get_temp") or "{loc}."
        rows.append(f"    ({rust_str(lang['code'])}, {rust_str(on)}, {rust_str(off)}, {rust_str(temp)}),")
    dest.write_text(
        "// @generated by scripts/lang_packs. DO NOT EDIT.\n"
        "//! Post-exec action templates for generated locales. de/en stay in language packs.\n\n"
        "#[allow(dead_code)]\n"
        "pub const ACTION_TEMPLATES: &[(&str, &str, &str, &str)] = &[\n"
        + "\n".join(rows)
        + "\n];\n"
    )
    print("wrote post_exec", dest)


def refine_shot_rows(bundle: dict) -> dict[str, str]:
    on = (bundle.get("turn_on") or "{target}.").replace("{target}", "X")
    off = (bundle.get("turn_off") or "{target}.").replace("{target}", "X")
    temp = (bundle.get("get_temp") or "{loc}").replace("{loc}", "Y")
    personality = bundle.get("personality") or {}
    rows = {
        "default": f"{on} → {on}\n{off} → {off}\n{temp} → {temp}",
    }
    for key in PERSONALITY_KEYS:
        variants = list(personality.get(key) or ["", "", ""])
        while len(variants) < 3:
            variants.append("")
        rows[key] = "\n".join(
            (
                f"{on} → {variants[0]}{on}",
                f"{off} → {off}",
                f"{temp} → {(variants[0] if not variants[2] else variants[2])}{temp}",
            )
        )
    return rows


if __name__ == "__main__":
    main()
