"""HA UI copy recovered for European Assist locales."""

from __future__ import annotations

EUROPE: dict[str, dict[str, str]] = {
    "de": {
        "user_desc": 'Diese Integration spricht mit Assist. App oder mitgelieferte Engine wählen — später unter Konfigurieren umstellbar. Nicht beides als Engine-Host. Der Release-Kanal lässt sich später ändern.',
        "mode": 'Engine',
        "channel": 'Release-Kanal',
        "url": 'URL der Klar-API',
        "token": 'Write-Token',
        "invalid": 'URL muss http(s) sein, ohne Benutzername.',
        "already": 'Klar NLU ist bereits eingerichtet',
        "opt_desc": 'Stimme, Assist-Sprachen und das LLM liegen in der Klar-Operator-UI (Einstellungen). Dieses Formular verbindet nur die Engine: URL, Token und Kanal.',
        "personality": 'Persönlichkeit',
        "languages": 'Sprachen',
        "fallback": 'Optionaler Legacy-Conversation-Agent',
        "refine_speech": 'NLU-Antworten vom LLM verfeinern',
        "refine_prompt": 'Verfeinerungs-Prompt',
        "assist_filter": 'Nur für Assist freigegebene Entitäten steuern',
        "nlu_rag": 'NLU-RAG (optional)',
        "quiet_ack": 'Kurze Bestätigung (Chime)',
        "calendar_llm": 'Kalenderabfragen an das LLM senden',
        "allow_llm_tools": 'Home-Assistant-Assist-Werkzeuge beim Engine-Chat erlauben',
        "help_personality": 'Liegt in dieser Integration, nicht in der Klar-App. Beim Wechsel wird der Verfeinerungs-Prompt geladen. Assist und die LLM-Stimme folgen ihm.',
        "help_refine_speech": 'Klar steuert weiter die Geräte. Das Fallback-LLM formuliert danach jede fertige Antwort um. Klar schickt enable_thinking=false mit.',
        "help_refine_prompt": 'Systemprompt der Stimme. Persönlichkeit wechseln, absenden, Prompt anpassen. Keine Gerätesteuerung, keine neuen Fakten, gleiche Sprache.',
        "help_token": 'Derselbe Token wie im Klar-Addon. Für Overlay-Schreibzugriffe aus Home Assistant.',
        "help_assist": 'An (Standard): nur was Assist sehen darf. Aus: auch versteckte Entitäten — leichter das falsche Gerät.',
        "help_rag": 'Standard aus. Bei Chat und leerem Reject nur den gematchten Ausschnitt an das Fallback-Modell. Nur Klar-Werkzeuge.',
        "help_quiet": 'Bei einfachem Licht oder Schalter an/aus keine gesprochene Antwort, nur ein kurzer Ton am Satelliten.',
        "help_calendar_llm": 'Standard aus. An: Klar liest den Kalender, das Fallback-LLM spricht die Termine. Aus: Klar spricht die Liste selbst. Anlegen, Löschen und Verschieben bleiben bei Klar.',
        "help_allow_llm_tools": 'Standard aus. An: nach dem Klar-Parse darf das Engine-Chat-Modell Home-Assistant-Assist-Werkzeuge nutzen (Namen kommen von Core, bereits prefixiert). Aus: nur Gespräch.',
        "help_languages": 'Standard ist die Home-Assistant-Systemsprache. Alle Sprachen lässt jede kompilierte Assist-Locale aktiv.',
        "help_channel": 'Stable oder Staging für den Host oben. App nutzt das Add-on; mitgelieferte Engine lädt das GitHub-Release. Eine eigene URL bleibt.',
        "help_mode": 'App oder mitgelieferte Engine. Jederzeit umstellen. Die Integrations-Sidebar erscheint nur bei der mitgelieferten Engine.',
        "help_fallback_agent": 'Leer lassen. Das LLM liegt in der Klar-Operator-UI (Einstellungen → LLM). Assist-Chat und Trainer nutzen denselben Endpoint. Dieses Feld ist nur für eine alte Home-Assistant-Conversation-Integration.',
        "local": 'Mitgelieferte Engine starten (nur HACS)',
        "remote": 'Klar-NLU-App oder Docker verwenden',
        "stable": 'Stable (Produktion)',
        "staging": 'Staging (Release Candidate)',
        "system": 'Systemsprache',
        "all": 'Alle Sprachen',
        "normal": 'Normal',
        "casual": 'Locker',
        "caring": 'Fürsorglich',
        "grumpy": 'Grantig',
        "sarcastic": 'Sarkastisch',
        "pirate": 'Pirat',
        "quiet_name": 'Kurze Bestätigung',
        "heard": 'Zuletzt gehört',
        "decision": 'Letzte Entscheidung',
        "speech": 'Letzte Antwort',
        "area": 'Gehört in',
        "down_title": 'Klar-Engine gestoppt',
        "down_desc": 'Der mitgelieferte Klar-Prozess läuft nicht. Lade Klar NLU unter Einstellungen → Geräte und Dienste neu.',
    },
    "de-CH": {
        "user_desc": "Die Integration redet mit Assist. D'Engine lauft als Klar-NLU-App, mitglieferte Prozess oder Docker. Uf Home Assistant OS d App installiere und Klar-NLU-App wähle. Ohni App Mitglieferte Engine starte. Nöd beides. De Release-Kanal cha mer spöter wächsle.",
        "mode": 'Engine',
        "channel": 'Release-Kanal',
        "url": 'URL vo de Klar-API',
        "token": 'Write-Token',
        "invalid": 'D URL mues http(s) si, ohni Benutzername.',
        "already": 'Klar NLU isch scho ygrichtet',
        "opt_desc": 'Stimm, Assist-Sprache und s LLM liged i de Klar-Operator-UI (Istellige). Das Formular verbindet nur d Engine: URL, Token und Kanal.',
        "personality": 'Persönlichkeit',
        "languages": 'Sprache',
        "fallback": 'Optionaler Legacy-Conversation-Agent',
        "refine_speech": 'NLU-Antworten vom LLM verfyynere',
        "refine_prompt": 'Verfyynerigs-Prompt',
        "assist_filter": 'Nur für Assist freigebeni Entitäte stüre',
        "nlu_rag": 'NLU-RAG (optional)',
        "quiet_ack": 'Churzi Bestätigung (Chime)',
        "calendar_llm": 'Kalenderabfroge ans LLM schicke',
        "allow_llm_tools": 'Home-Assistant-Assist-Wärchzüüg bim Engine-Chat erlaube',
        "help_personality": 'Lyt i dere Integration, nöd i de Klar-App. Assist und d LLM-Stimm folged em Prompt.',
        "help_refine_speech": 'Klar stüret wyter d Grät. S Fallback-LLM formuliert d Antwort um.',
        "help_refine_prompt": 'Systemprompt vo de Stimm. Kei Grätestüürig, kei neui Fakte, gliichi Sprach.',
        "help_token": 'Glyche Token wie im Klar-Addon.',
        "help_assist": 'Aa: nur was Assist gseht. Us: au versteckti Entitäte.',
        "help_rag": 'Standard us. Bi Chat nume de gmatchti Uschnitt ans Fallback-Modell.',
        "help_quiet": 'Bi eifachem Liecht aa/us kei gredti Antwort, nur en churze Ton.',
        "help_calendar_llm": 'Standard us. Aa: Klar liest de Kalender, s Fallback-LLM seit d Termin. Us: Klar seit d Liste sälber. Aalege, Lösche und Verschiebe blibed bi Klar.',
        "help_allow_llm_tools": 'Standard us. Aa: nach em Klar-Parse darf s Engine-Chat-Modell Home-Assistant-Assist-Wärchzüüg nutze (Nämme chömed vo Core, scho prefixiert). Us: nur Gspröch.',
        "help_languages": 'Standard isch d Home-Assistant-Systemsprach.',
        "help_channel": 'Stable oder Staging für de Host obe. App nutzt s Add-on; mitglieferte Engine ladet s GitHub-Release.',
        "help_mode": 'App oder mitglieferte Engine. Jederzit umstelle. D Integrations-Sidebar git s nur bi de mitglieferte Engine.',
        "help_fallback_agent": 'Leer loh. S LLM isch i de Klar-Operator-UI (Iistellige → LLM). Assist-Chat und Trainer nützt de gliich Endpoint. Das Feld isch nur für e alti Home-Assistant-Conversation-Integration.',
        "local": 'Mitglieferte Engine starte (nur HACS)',
        "remote": 'Klar-NLU-App oder Docker bruche',
        "stable": 'Stable (Produktion)',
        "staging": 'Staging (Release Candidate)',
        "system": 'Systemsprach',
        "all": 'Alli Sprache',
        "normal": 'Normal',
        "casual": 'Locker',
        "caring": 'Fürsorglich',
        "grumpy": 'Grantig',
        "sarcastic": 'Sarkastisch',
        "pirate": 'Pirat',
        "quiet_name": 'Churzi Bestätigung',
        "heard": 'Zletzt ghört',
        "decision": 'Letschti Entscheidig',
        "speech": 'Letschti Antwort',
        "area": 'Ghört in',
        "down_title": 'Klar-Engine gstoppt',
        "down_desc": 'De mitglieferte Klar-Prozess lauft nöd. Lad Klar NLU under Istellige → Grät und Dienst neu.',
    },
    "de-AT": {
        "user_desc": 'Diese Integration spricht mit Assist. Die Engine läuft als Klar-NLU-App, mitgelieferter Prozess oder Docker. Unter Home Assistant OS die App installieren und Klar-NLU-App verwenden. Nicht beides. Den Release-Kanal kannst du später ändern.',
        "mode": 'Engine',
        "channel": 'Release-Kanal',
        "url": 'URL der Klar-API',
        "token": 'Write-Token',
        "invalid": 'URL muss http(s) sein, ohne Benutzername.',
        "already": 'Klar NLU ist bereits eingerichtet',
        "opt_desc": 'Stimme, Assist-Sprachen und das LLM liegen in der Klar-Operator-UI (Einstellungen). Dieses Formular verbindet nur die Engine: URL, Token und Kanal.',
        "personality": 'Persönlichkeit',
        "languages": 'Sprachen',
        "fallback": 'Optionaler Legacy-Conversation-Agent',
        "refine_speech": 'NLU-Antworten vom LLM verfeinern',
        "refine_prompt": 'Verfeinerungs-Prompt',
        "assist_filter": 'Nur für Assist freigegebene Entitäten steuern',
        "nlu_rag": 'NLU-RAG (optional)',
        "quiet_ack": 'Kurze Bestätigung (Chime)',
        "calendar_llm": 'Kalenderabfragen an das LLM senden',
        "allow_llm_tools": 'Home-Assistant-Assist-Werkzeuge beim Engine-Chat erlauben',
        "help_personality": 'Liegt in dieser Integration, nicht in der Klar-App.',
        "help_refine_speech": 'Klar steuert weiter die Geräte. Das Fallback-LLM formuliert die Antwort um.',
        "help_refine_prompt": 'Systemprompt der Stimme. Keine Gerätesteuerung, keine neuen Fakten, gleiche Sprache.',
        "help_token": 'Derselbe Token wie im Klar-Addon.',
        "help_assist": 'An: nur was Assist sehen darf. Aus: auch versteckte Entitäten.',
        "help_rag": 'Standard aus. Bei Chat nur den gematchten Ausschnitt an das Fallback-Modell.',
        "help_quiet": 'Bei einfachem Licht an/aus keine gesprochene Antwort, nur ein kurzer Ton.',
        "help_calendar_llm": 'Standard aus. An: Klar liest den Kalender, das Fallback-LLM spricht die Termine. Aus: Klar spricht die Liste selbst. Anlegen, Löschen und Verschieben bleiben bei Klar.',
        "help_allow_llm_tools": 'Standard aus. An: nach dem Klar-Parse darf das Engine-Chat-Modell Home-Assistant-Assist-Werkzeuge nutzen (Namen kommen von Core, bereits prefixiert). Aus: nur Gespräch.',
        "help_languages": 'Standard ist die Home-Assistant-Systemsprache.',
        "help_channel": 'Stable oder Staging für den Host oben. App nutzt das Add-on; mitgelieferte Engine lädt das GitHub-Release. Eine eigene URL bleibt.',
        "help_mode": 'App oder mitgelieferte Engine. Jederzeit umstellen. Die Integrations-Sidebar erscheint nur bei der mitgelieferten Engine.',
        "help_fallback_agent": 'Leer lassen. Das LLM liegt in der Klar-Operator-UI (Einstellungen → LLM). Assist-Chat und Trainer nutzen denselben Endpoint. Dieses Feld ist nur für eine alte Home-Assistant-Conversation-Integration.',
        "local": 'Mitgelieferte Engine starten (nur HACS)',
        "remote": 'Klar-NLU-App oder Docker verwenden',
        "stable": 'Stable (Produktion)',
        "staging": 'Staging (Release Candidate)',
        "system": 'Systemsprache',
        "all": 'Alle Sprachen',
        "normal": 'Normal',
        "casual": 'Locker',
        "caring": 'Fürsorglich',
        "grumpy": 'Grantig',
        "sarcastic": 'Sarkastisch',
        "pirate": 'Pirat',
        "quiet_name": 'Kurze Bestätigung',
        "heard": 'Zuletzt gehört',
        "decision": 'Letzte Entscheidung',
        "speech": 'Letzte Antwort',
        "area": 'Gehört in',
        "down_title": 'Klar-Engine gestoppt',
        "down_desc": 'Der mitgelieferte Klar-Prozess läuft nicht. Lade Klar NLU unter Einstellungen → Geräte und Dienste neu.',
    },
    "en-GB": {
        "user_desc": 'This integration talks to Assist. A separate engine parses speech: the Klar NLU App, this bundled process, or Docker. On Home Assistant OS install the App as well, then pick Use the Klar NLU App. Without the App, pick Start the bundled engine. Do not run both. The release channel can be changed later.',
        "mode": 'Engine',
        "channel": 'Release channel',
        "url": 'Klar API URL',
        "token": 'Write token',
        "invalid": 'URL must be http(s) without userinfo.',
        "already": 'Klar NLU is already set up',
        "opt_desc": 'Voice, Assist languages, and the LLM live in the Klar operator UI (Settings). This form only connects the engine: URL, token, and channel.',
        "personality": 'Personality',
        "languages": 'Languages',
        "fallback": 'Conversation agent for chit-chat',
        "refine_speech": 'Let the LLM refine NLU replies',
        "refine_prompt": 'Refinement prompt',
        "assist_filter": 'Only control entities exposed to Assist',
        "nlu_rag": 'NLU-RAG (opt-in)',
        "quiet_ack": 'Short confirmation (chime)',
        "calendar_llm": 'Send calendar queries to the LLM',
        "allow_llm_tools": 'Allow Home Assistant Assist tools on engine chat',
        "help_personality": 'Stored in this integration, not in the Klar app. Assist and the LLM voice follow the prompt.',
        "help_refine_speech": 'Klar still controls devices. The fallback LLM then rewrites each finished reply.',
        "help_refine_prompt": 'System prompt for the voice. No device control, no new facts, same language.',
        "help_token": 'Same token as the Klar add-on.',
        "help_assist": 'On (default): only what Assist may see. Off: hidden entities too.',
        "help_rag": 'Off by default. Chat and empty rejects send the matched slice to the fallback model.',
        "help_quiet": 'On simple light or switch on/off, skip the spoken reply and play a short chime.',
        "help_calendar_llm": 'Off by default. On: Klar still reads the calendar, then the fallback LLM speaks the events. Off: Klar speaks the list itself. Create, delete, and move stay in Klar.',
        "help_allow_llm_tools": 'Off by default. On: after Klar parses, the engine chat model may call Home Assistant Assist tools (names come from Core, already prefixed). Off: conversation only.',
        "help_languages": 'Default follows the Home Assistant system language.',
        "help_channel": 'Stable vs staging for the host you picked above. App uses that add-on; bundled engine downloads that GitHub release. A custom URL is left alone.',
        "help_mode": 'App vs bundled engine. Switch anytime. The integration sidebar only appears for the bundled engine.',
        "local": 'Start the bundled engine (HACS only)',
        "remote": 'Use the Klar NLU App or Docker',
        "stable": 'Stable (production)',
        "staging": 'Staging (release candidate)',
        "system": 'System language',
        "all": 'All languages',
        "normal": 'Normal',
        "casual": 'Casual',
        "caring": 'Caring',
        "grumpy": 'Grumpy',
        "sarcastic": 'Sarcastic',
        "pirate": 'Pirate',
        "quiet_name": 'Short confirmation',
        "heard": 'Last heard',
        "decision": 'Last decision',
        "speech": 'Last reply',
        "area": 'Heard in',
        "down_title": 'Klar engine stopped',
        "down_desc": 'The bundled Klar process is not running. Reload Klar NLU from Settings → Devices & Services.',
    },
    "fr": {
        "user_desc": 'Cette intégration parle à Assist. Un moteur séparé analyse la parole : l’app Klar NLU, ce processus intégré ou Docker. Sous Home Assistant OS, installez aussi l’app puis choisissez Utiliser l’app Klar NLU. Sans app, démarrez le moteur intégré. Ne lancez pas les deux. Le canal de publication se change plus tard.',
        "mode": 'Moteur',
        "channel": 'Canal de publication',
        "url": 'URL de l’API Klar',
        "token": 'Jeton d’écriture',
        "invalid": 'L’URL doit être en http(s), sans identifiants.',
        "already": 'Klar NLU est déjà configuré',
        "opt_desc": 'La voix, les langues d’Assist et le LLM sont dans l’UI opérateur Klar (Réglages). Ce formulaire ne fait que connecter le moteur : URL, jeton et canal.',
        "personality": 'Personnalité',
        "languages": 'Langues',
        "fallback": 'Agent de conversation pour le bavardage',
        "refine_speech": 'Laisser le LLM reformuler les réponses NLU',
        "refine_prompt": 'Prompt de raffinage',
        "assist_filter": 'Ne commander que les entités exposées à Assist',
        "nlu_rag": 'NLU-RAG (optionnel)',
        "quiet_ack": 'Confirmation courte (carillon)',
        "calendar_llm": 'Envoyer les requêtes agenda à l\'LLM',
        "help_personality": 'Stockée dans cette intégration, pas dans l’app Klar. Assist et la voix LLM suivent le prompt.',
        "help_refine_speech": 'Klar commande toujours les appareils. Le LLM de secours reformule ensuite chaque réponse.',
        "help_refine_prompt": 'Prompt système de la voix. Pas de commande d’appareils, pas de faits nouveaux, même langue.',
        "help_token": 'Le même jeton que dans l’app Klar.',
        "help_assist": 'Activé : seulement ce qu’Assist peut voir. Désactivé : aussi les entités masquées.',
        "help_rag": 'Désactivé par défaut. En discussion, seul l’extrait déjà reconnu va au modèle de secours.',
        "help_quiet": 'Pour un simple allumage ou extinction, pas de phrase : un court carillon sur le satellite.',
        "help_calendar_llm": 'Désactivé par défaut. Activé : Klar lit l\'agenda, puis le LLM de secours dit les événements. Désactivé : Klar dit la liste. Créer, supprimer et déplacer restent dans Klar.',
        "help_languages": 'Par défaut, la langue système de Home Assistant.',
        "help_channel": 'À tout moment. Staging pointe vers Klar NLU (Staging), Stable vers l’app ou le moteur intégré.',
        "local": 'Démarrer le moteur intégré (HACS uniquement)',
        "remote": 'Utiliser l’app Klar NLU ou Docker',
        "stable": 'Stable (production)',
        "staging": 'Staging (candidat)',
        "system": 'Langue du système',
        "all": 'Toutes les langues',
        "normal": 'Normale',
        "casual": 'Décontractée',
        "caring": 'Attentionnée',
        "grumpy": 'Grognon',
        "sarcastic": 'Sarcastique',
        "pirate": 'Pirate',
        "quiet_name": 'Confirmation courte',
        "heard": 'Dernière écoute',
        "decision": 'Dernière décision',
        "speech": 'Dernière réponse',
        "area": 'Entendu dans',
        "down_title": 'Moteur Klar arrêté',
        "down_desc": 'Le processus Klar intégré ne tourne pas. Rechargez Klar NLU dans Paramètres → Appareils et services.',
    },
    "nl": {
        "user_desc": 'Deze integratie praat met Assist. Een aparte engine herkent spraak: de Klar NLU-app, dit meegeleverde proces of Docker. Op Home Assistant OS ook de app installeren en Klar NLU-app gebruiken kiezen. Zonder app de meegeleverde engine starten. Niet allebei. Het releasekanaal kun je later wijzigen.',
        "mode": 'Engine',
        "channel": 'Releasekanaal',
        "url": 'Klar-API-URL',
        "token": 'Schrijftoken',
        "invalid": 'URL moet http(s) zijn, zonder gebruikersnaam.',
        "already": 'Klar NLU is al ingesteld',
        "opt_desc": 'Stem, Assist-talen en de LLM staan in de Klar-operator-UI (Instellingen). Dit formulier koppelt alleen de engine: URL, token en kanaal.',
        "personality": 'Persoonlijkheid',
        "languages": 'Talen',
        "fallback": 'Conversatie-agent voor smalltalk',
        "refine_speech": 'NLU-antwoorden door de LLM laten herschrijven',
        "refine_prompt": 'Verfijningsprompt',
        "assist_filter": 'Alleen aan Assist vrijgegeven entiteiten bedienen',
        "nlu_rag": 'NLU-RAG (optioneel)',
        "quiet_ack": 'Korte bevestiging (chime)',
        "calendar_llm": 'Agenda-vragen naar het LLM sturen',
        "help_personality": 'Staat in deze integratie, niet in de Klar-app. Assist en de LLM-stem volgen de prompt.',
        "help_refine_speech": 'Klar bedient nog steeds de apparaten. De fallback-LLM herschrijft daarna het antwoord.',
        "help_refine_prompt": 'Systeempprompt van de stem. Geen apparaatbediening, geen nieuwe feiten, dezelfde taal.',
        "help_token": 'Dezelfde token als in de Klar-app.',
        "help_assist": 'Aan: alleen wat Assist mag zien. Uit: ook verborgen entiteiten.',
        "help_rag": 'Standaard uit. Bij chat alleen het herkende stuk naar het fallback-model.',
        "help_quiet": 'Bij eenvoudig licht of schakelaar aan/uit geen gesproken antwoord, alleen een korte toon.',
        "help_calendar_llm": 'Standaard uit. Aan: Klar leest de agenda, het fallback-LLM spreekt de afspraken. Uit: Klar spreekt de lijst zelf. Aanmaken, verwijderen en verplaatsen blijven bij Klar.',
        "help_languages": 'Standaard is de Home Assistant-systeemtaal.',
        "help_channel": 'Altijd. Staging wijst naar Klar NLU (Staging), Stable naar de app of de meegeleverde engine.',
        "local": 'Meegeleverde engine starten (alleen HACS)',
        "remote": 'Klar NLU-app of Docker gebruiken',
        "stable": 'Stable (productie)',
        "staging": 'Staging (release candidate)',
        "system": 'Systeemtaal',
        "all": 'Alle talen',
        "normal": 'Normaal',
        "casual": 'Relaxed',
        "caring": 'Zorgzaam',
        "grumpy": 'Knorrig',
        "sarcastic": 'Sarcastisch',
        "pirate": 'Piraat',
        "quiet_name": 'Korte bevestiging',
        "heard": 'Laatst gehoord',
        "decision": 'Laatste beslissing',
        "speech": 'Laatste antwoord',
        "area": 'Gehoord in',
        "down_title": 'Klar-engine gestopt',
        "down_desc": 'Het meegeleverde Klar-proces draait niet. Herlaad Klar NLU via Instellingen → Apparaten en diensten.',
    },
    "es": {
        "user_desc": 'Esta integración habla con Assist. Un motor aparte analiza el habla: la app Klar NLU, este proceso incluido o Docker. En Home Assistant OS instala también la app y elige Usar la app Klar NLU. Sin app, inicia el motor incluido. No ejecutes ambos. El canal de publicación se puede cambiar después.',
        "mode": 'Motor',
        "channel": 'Canal de publicación',
        "url": 'URL de la API de Klar',
        "token": 'Token de escritura',
        "invalid": 'La URL debe ser http(s), sin usuario.',
        "already": 'Klar NLU ya está configurado',
        "opt_desc": 'La voz, los idiomas de Assist y el LLM están en la UI de operador de Klar (Ajustes). Este formulario solo conecta el motor: URL, token y canal.',
        "personality": 'Personalidad',
        "languages": 'Idiomas',
        "fallback": 'Agente de conversación para charla',
        "refine_speech": 'Dejar que el LLM reformule las respuestas NLU',
        "refine_prompt": 'Indicación de refinamiento',
        "assist_filter": 'Controlar solo entidades expuestas a Assist',
        "nlu_rag": 'NLU-RAG (opcional)',
        "quiet_ack": 'Confirmación breve (timbre)',
        "calendar_llm": 'Enviar consultas de calendario al LLM',
        "help_personality": 'Está en esta integración, no en la app Klar. Assist y la voz LLM siguen el prompt.',
        "help_refine_speech": 'Klar sigue controlando los dispositivos. El LLM de reserva reformula la respuesta.',
        "help_refine_prompt": 'Prompt del sistema de la voz. Sin control de dispositivos, sin hechos nuevos, mismo idioma.',
        "help_token": 'El mismo token que en la app Klar.',
        "help_assist": 'Activado: solo lo que Assist puede ver. Desactivado: también entidades ocultas.',
        "help_rag": 'Desactivado por defecto. En el chat solo el fragmento reconocido va al modelo de reserva.',
        "help_quiet": 'En encender o apagar simple, sin frase: solo un timbre corto en el satélite.',
        "help_calendar_llm": 'Desactivado por defecto. Activado: Klar lee el calendario y el LLM de reserva dice los eventos. Desactivado: Klar dice la lista. Crear, borrar y mover siguen en Klar.',
        "help_languages": 'Por defecto, el idioma del sistema de Home Assistant.',
        "help_channel": 'En cualquier momento. Staging apunta a Klar NLU (Staging); Stable a la app o al motor incluido.',
        "local": 'Iniciar el motor incluido (solo HACS)',
        "remote": 'Usar la app Klar NLU o Docker',
        "stable": 'Stable (producción)',
        "staging": 'Staging (candidato)',
        "system": 'Idioma del sistema',
        "all": 'Todos los idiomas',
        "normal": 'Normal',
        "casual": 'Informal',
        "caring": 'Cariñosa',
        "grumpy": 'Gruñona',
        "sarcastic": 'Sarcástica',
        "pirate": 'Pirata',
        "quiet_name": 'Confirmación breve',
        "heard": 'Último oído',
        "decision": 'Última decisión',
        "speech": 'Última respuesta',
        "area": 'Oído en',
        "down_title": 'Motor Klar detenido',
        "down_desc": 'El proceso Klar incluido no está en marcha. Recarga Klar NLU en Ajustes → Dispositivos y servicios.',
    },
    "it": {
        "user_desc": 'Questa integrazione parla con Assist. Un motore separato analizza la voce: l’app Klar NLU, questo processo incluso o Docker. Su Home Assistant OS installa anche l’app e scegli Usa l’app Klar NLU. Senza app avvia il motore incluso. Non eseguire entrambi. Il canale di rilascio si cambia in seguito.',
        "mode": 'Motore',
        "channel": 'Canale di rilascio',
        "url": 'URL API Klar',
        "token": 'Token di scrittura',
        "invalid": 'L’URL deve essere http(s), senza credenziali.',
        "already": 'Klar NLU è già configurato',
        "opt_desc": 'Voce, lingue di Assist e LLM sono nell’UI operatore di Klar (Impostazioni). Questo modulo collega solo il motore: URL, token e canale.',
        "personality": 'Personalità',
        "languages": 'Lingue',
        "fallback": 'Agente di conversazione per chiacchiere',
        "refine_speech": "Lasciare che l'LLM riformuli le risposte NLU",
        "refine_prompt": 'Prompt di raffinamento',
        "assist_filter": 'Controllare solo le entità esposte ad Assist',
        "nlu_rag": 'NLU-RAG (opzionale)',
        "quiet_ack": 'Conferma breve (campanella)',
        "calendar_llm": 'Invia le richieste calendario all\'LLM',
        "help_personality": 'È in questa integrazione, non nell’app Klar. Assist e la voce LLM seguono il prompt.',
        "help_refine_speech": "Klar continua a controllare i dispositivi. L'LLM di riserva riformula la risposta.",
        "help_refine_prompt": 'Prompt di sistema della voce. Nessun controllo dispositivi, nessun fatto nuovo, stessa lingua.',
        "help_token": 'Lo stesso token dell’app Klar.',
        "help_assist": 'On: solo ciò che Assist può vedere. Off: anche entità nascoste.',
        "help_rag": 'Disattivato di default. In chat solo il frammento riconosciuto va al modello di riserva.',
        "help_quiet": 'Per accensione o spegnimento semplice, nessuna frase: solo un suono breve sul satellite.',
        "help_calendar_llm": 'Disattivato di default. Attivo: Klar legge il calendario, l\'LLM di riserva dice gli eventi. Spento: Klar dice l\'elenco. Crea, elimina e sposta restano in Klar.',
        "help_languages": 'L’impostazione predefinita è la lingua di sistema di Home Assistant.',
        "help_channel": 'Sempre. Staging punta a Klar NLU (Staging), Stable all’app o al motore incluso.',
        "local": 'Avvia il motore incluso (solo HACS)',
        "remote": 'Usa l’app Klar NLU o Docker',
        "stable": 'Stable (produzione)',
        "staging": 'Staging (candidato)',
        "system": 'Lingua di sistema',
        "all": 'Tutte le lingue',
        "normal": 'Normale',
        "casual": 'Informale',
        "caring": 'Premurosa',
        "grumpy": 'Scontrosa',
        "sarcastic": 'Sarcastica',
        "pirate": 'Pirata',
        "quiet_name": 'Conferma breve',
        "heard": 'Ultimo ascolto',
        "decision": 'Ultima decisione',
        "speech": 'Ultima risposta',
        "area": 'Ascoltato in',
        "down_title": 'Motore Klar fermo',
        "down_desc": 'Il processo Klar incluso non è in esecuzione. Ricarica Klar NLU in Impostazioni → Dispositivi e servizi.',
    },
    "pt": {
        "user_desc": 'Esta integração fala com o Assist. Um motor separado analisa a fala: a app Klar NLU, este processo incluído ou Docker. No Home Assistant OS instale também a app e escolha Usar a app Klar NLU. Sem app, inicie o motor incluído. Não execute ambos. O canal de lançamento pode ser alterado depois.',
        "mode": 'Motor',
        "channel": 'Canal de lançamento',
        "url": 'URL da API Klar',
        "token": 'Token de escrita',
        "invalid": 'O URL deve ser http(s), sem credenciais.',
        "already": 'O Klar NLU já está configurado',
        "opt_desc": 'A voz, as línguas do Assist e o LLM estão na UI de operador do Klar (Definições). Este formulário só liga o motor: URL, token e canal.',
        "personality": 'Personalidade',
        "languages": 'Idiomas',
        "fallback": 'Agente de conversação para conversa',
        "refine_speech": 'Deixar o LLM reformular as respostas NLU',
        "refine_prompt": 'Prompt de refinamento',
        "assist_filter": 'Controlar só entidades expostas ao Assist',
        "nlu_rag": 'NLU-RAG (opcional)',
        "quiet_ack": 'Confirmação curta (sinal)',
        "calendar_llm": 'Enviar consultas de calendário ao LLM',
        "help_personality": 'Está nesta integração, não na app Klar. O Assist e a voz LLM seguem o prompt.',
        "help_refine_speech": 'O Klar continua a controlar os dispositivos. O LLM de recurso reformula a resposta.',
        "help_refine_prompt": 'Prompt de sistema da voz. Sem controlo de dispositivos, sem factos novos, mesma língua.',
        "help_token": 'O mesmo token da app Klar.',
        "help_assist": 'Ligado: só o que o Assist pode ver. Desligado: também entidades ocultas.',
        "help_rag": 'Desligado por predefinição. No chat só o excerto reconhecido vai para o modelo de recurso.',
        "help_quiet": 'Num ligar ou desligar simples, sem frase: só um sinal curto no satélite.',
        "help_calendar_llm": 'Desligado por predefinição. Ligado: o Klar lê o calendário e o LLM de recurso diz os eventos. Desligado: o Klar diz a lista. Criar, apagar e mover ficam no Klar.',
        "help_languages": 'A predefinição é o idioma do sistema do Home Assistant.',
        "help_channel": 'Em qualquer altura. Staging aponta para Klar NLU (Staging); Stable para a app ou o motor incluído.',
        "local": 'Iniciar o motor incluído (apenas HACS)',
        "remote": 'Usar a app Klar NLU ou Docker',
        "stable": 'Stable (produção)',
        "staging": 'Staging (candidato)',
        "system": 'Idioma do sistema',
        "all": 'Todos os idiomas',
        "normal": 'Normal',
        "casual": 'Descontraída',
        "caring": 'Atenciosa',
        "grumpy": 'Rabugenta',
        "sarcastic": 'Sarcástica',
        "pirate": 'Pirata',
        "quiet_name": 'Confirmação curta',
        "heard": 'Última audição',
        "decision": 'Última decisão',
        "speech": 'Última resposta',
        "area": 'Ouvido em',
        "down_title": 'Motor Klar parado',
        "down_desc": 'O processo Klar incluído não está a correr. Recarregue o Klar NLU em Definições → Dispositivos e serviços.',
    },
    "pt-BR": {
        "user_desc": 'Esta integração fala com o Assist. Um mecanismo separado analisa a fala: o app Klar NLU, este processo incluso ou Docker. No Home Assistant OS instale também o app e escolha Usar o app Klar NLU. Sem o app, inicie o mecanismo incluso. Não execute os dois. O canal de lançamento pode ser alterado depois.',
        "mode": 'Mecanismo',
        "channel": 'Canal de lançamento',
        "url": 'URL da API Klar',
        "token": 'Token de escrita',
        "invalid": 'A URL deve ser http(s), sem usuário.',
        "already": 'O Klar NLU já está configurado',
        "opt_desc": 'A voz, os idiomas do Assist e o LLM ficam na UI do operador Klar (Configurações). Este formulário só conecta o mecanismo: URL, token e canal.',
        "personality": 'Personalidade',
        "languages": 'Idiomas',
        "fallback": 'Agente de conversa para papo',
        "refine_speech": 'Deixar o LLM refinar as respostas NLU',
        "refine_prompt": 'Prompt de refinamento',
        "assist_filter": 'Controlar só entidades expostas ao Assist',
        "nlu_rag": 'NLU-RAG (opcional)',
        "quiet_ack": 'Confirmação curta (som)',
        "calendar_llm": 'Enviar consultas de calendário ao LLM',
        "help_personality": 'Fica nesta integração, não no app Klar. O Assist e a voz do LLM seguem o prompt.',
        "help_refine_speech": 'O Klar continua controlando os dispositivos. O LLM reserva reformula a resposta.',
        "help_refine_prompt": 'Prompt de sistema da voz. Sem controle de dispositivos, sem fatos novos, mesmo idioma.',
        "help_token": 'O mesmo token do app Klar.',
        "help_assist": 'Ligado: só o que o Assist pode ver. Desligado: também entidades ocultas.',
        "help_rag": 'Desligado por padrão. No chat só o trecho reconhecido vai para o modelo reserva.',
        "help_quiet": 'Em ligar ou desligar simples, sem fala: só um som curto no satélite.',
        "help_calendar_llm": 'Desligado por padrão. Ligado: o Klar lê o calendário e o LLM reserva fala os eventos. Desligado: o Klar fala a lista. Criar, apagar e mover ficam no Klar.',
        "help_languages": 'O padrão é o idioma do sistema do Home Assistant.',
        "help_channel": 'A qualquer momento. Staging aponta para Klar NLU (Staging); Stable para o app ou o mecanismo incluso.',
        "local": 'Iniciar o mecanismo incluso (somente HACS)',
        "remote": 'Usar o app Klar NLU ou Docker',
        "stable": 'Stable (produção)',
        "staging": 'Staging (candidato)',
        "system": 'Idioma do sistema',
        "all": 'Todos os idiomas',
        "normal": 'Normal',
        "casual": 'Descontraída',
        "caring": 'Atenciosa',
        "grumpy": 'Ranzinza',
        "sarcastic": 'Sarcástica',
        "pirate": 'Pirata',
        "quiet_name": 'Confirmação curta',
        "heard": 'Última escuta',
        "decision": 'Última decisão',
        "speech": 'Última resposta',
        "area": 'Ouvido em',
        "down_title": 'Mecanismo Klar parado',
        "down_desc": 'O processo Klar incluso não está em execução. Recarregue o Klar NLU em Configurações → Dispositivos e serviços.',
    },
}
