"""HA UI copy recovered for MENA Assist locales."""

from __future__ import annotations

MENA: dict[str, dict[str, str]] = {
    "ar": {
        "user_desc": 'هذا التكامل يتحدث مع Assist. محرك منفصل يحلل الكلام: تطبيق Klar NLU أو العملية المرفقة أو Docker. على Home Assistant OS ثبّت التطبيق واختر استخدام تطبيق Klar NLU. بدون التطبيق شغّل المحرك المرفق. لا تشغّلهما معاً.',
        "mode": 'المحرك',
        "channel": 'قناة الإصدار',
        "url": 'عنوان واجهة Klar',
        "token": 'رمز الكتابة',
        "invalid": 'يجب أن يكون العنوان http(s) دون اسم مستخدم.',
        "already": 'Klar NLU مضبوط مسبقاً',
        "opt_desc": 'الصوت ولغات Assist ونموذج اللغة موجودة في واجهة مشغّل Klar (الإعدادات). هذا النموذج يربط المحرك فقط: العنوان والرمز والقناة.',
        "personality": 'الشخصية',
        "languages": 'اللغات',
        "fallback": 'وكيل محادثة للدردشة',
        "refine_speech": 'دع نموذج اللغة يعيد صياغة ردود NLU',
        "refine_prompt": 'موجه التحسين',
        "assist_filter": 'التحكم فقط بالكيانات الظاهرة لـ Assist',
        "nlu_rag": 'NLU-RAG (اختياري)',
        "quiet_ack": 'تأكيد قصير (رنين)',
        "calendar_llm": 'إرسال استعلامات التقويم إلى نموذج اللغة',
        "help_personality": 'في هذا التكامل وليس في تطبيق Klar.',
        "help_refine_speech": 'Klar ما زال يتحكم بالأجهزة. النموذج الاحتياطي يعيد كتابة الرد.',
        "help_refine_prompt": 'موجه نظام الصوت. بلا تحكم بالأجهزة، بلا حقائق جديدة، نفس اللغة.',
        "help_token": 'نفس الرمز المستخدم في تطبيق Klar.',
        "help_assist": 'تشغيل: ما يراه Assist فقط. إيقاف: يشمل الكيانات المخفية.',
        "help_rag": 'متوقف افتراضياً. في الدردشة يُرسل الجزء المطابق فقط للنموذج الاحتياطي.',
        "help_quiet": 'عند تشغيل أو إطفاء ضوء بسيط لا كلام، رنين قصير على القمر فقط.',
        "help_calendar_llm": 'متوقف افتراضياً. تشغيل: يقرأ كلار التقويم ويتحدث النموذج الاحتياطي بالمواعيد. إيقاف: يتحدث كلار بالقائمة. الإنشاء والحذف والنقل تبقى لدى كلار.',
        "help_languages": 'الافتراضي يتبع لغة نظام Home Assistant.',
        "help_channel": 'في أي وقت. Staging يشير إلى Klar NLU (Staging).',
        "local": 'تشغيل المحرك المرفق (HACS فقط)',
        "remote": 'استخدام تطبيق Klar NLU أو Docker',
        "stable": 'Stable (إنتاج)',
        "staging": 'Staging (مرشح)',
        "system": 'لغة النظام',
        "all": 'كل اللغات',
        "normal": 'عادي',
        "casual": 'عفوي',
        "caring": 'حنون',
        "grumpy": 'متذمر',
        "sarcastic": 'ساخر',
        "pirate": 'قرصان',
        "quiet_name": 'تأكيد قصير',
        "heard": 'آخر ما سُمع',
        "decision": 'آخر قرار',
        "speech": 'آخر رد',
        "area": 'سُمع في',
        "down_title": 'توقف محرك Klar',
        "down_desc": 'عملية Klar المرفقة لا تعمل. أعد تحميل Klar NLU من الإعدادات ← الأجهزة والخدمات.',
    },
    "he": {
        "user_desc": 'האינטגרציה הזו מדברת עם Assist. מנוע נפרד מפענח דיבור: אפליקציית Klar NLU, התהליך המצורף או Docker. ב-Home Assistant OS התקינו גם את האפליקציה ובחרו להשתמש באפליקציית Klar NLU. בלי אפליקציה הפעילו את המנוע המצורף. אל תריצו את שניהם.',
        "mode": 'מנוע',
        "channel": 'ערוץ הפצה',
        "url": 'כתובת API של Klar',
        "token": 'אסימון כתיבה',
        "invalid": 'הכתובת חייבת להיות http(s) בלי שם משתמש.',
        "already": 'Klar NLU כבר מוגדר',
        "opt_desc": 'הקול, שפות Assist והמודל נמצאים בממשק המפעיל של Klar (הגדרות). טופס זה מחבר רק את המנוע: כתובת, אסימון וערוץ.',
        "personality": 'אישיות',
        "languages": 'שפות',
        "fallback": 'סוכן שיחה לפטפוט',
        "refine_speech": 'לתת ל-LLM לנסח מחדש תשובות NLU',
        "refine_prompt": 'הנחיית עידון',
        "assist_filter": 'לשלוט רק בישויות החשופות ל-Assist',
        "nlu_rag": 'NLU-RAG (אופציונלי)',
        "quiet_ack": 'אישור קצר (פעמון)',
        "calendar_llm": 'שלח שאילתות יומן ל-LLM',
        "help_personality": 'באינטגרציה הזו, לא באפליקציית Klar.',
        "help_refine_speech": 'Klar ממשיך לשלוט במכשירים. ה-LLM הרזרבי כותב מחדש את התשובה.',
        "help_refine_prompt": 'הנחיית מערכת לקול. בלי שליטה במכשירים, בלי עובדות חדשות, אותה שפה.',
        "help_token": 'אותו אסימון כמו באפליקציית Klar.',
        "help_assist": 'דלוק: רק מה ש-Assist רואה. כבוי: גם ישויות מוסתרות.',
        "help_rag": "כבוי כברירת מחדל. בצ'אט נשלח למודל הרזרבי רק הקטע שזוהה.",
        "help_quiet": 'בהדלקה/כיבוי פשוט של אור אין דיבור, רק צליל קצר בלוויין.',
        "help_calendar_llm": 'כבוי כברירת מחדל. דלוק: קלאר קורא את היומן וסוכן הגיבוי אומר את האירועים. כבוי: קלאר אומר את הרשימה. יצירה, מחיקה והעברה נשארות אצל קלאר.',
        "help_languages": 'ברירת המחדל היא שפת המערכת של Home Assistant.',
        "help_channel": 'בכל עת. Staging מצביע על Klar NLU (Staging).',
        "local": 'הפעלת המנוע המצורף (HACS בלבד)',
        "remote": 'שימוש באפליקציית Klar NLU או Docker',
        "stable": 'Stable (ייצור)',
        "staging": 'Staging (מועמד)',
        "system": 'שפת המערכת',
        "all": 'כל השפות',
        "normal": 'רגיל',
        "casual": 'רגוע',
        "caring": 'דואג',
        "grumpy": 'עצבני',
        "sarcastic": 'סרקסטי',
        "pirate": 'פיראט',
        "quiet_name": 'אישור קצר',
        "heard": 'נשמע לאחרונה',
        "decision": 'החלטה אחרונה',
        "speech": 'תשובה אחרונה',
        "area": 'נשמע ב',
        "down_title": 'מנוע Klar נעצר',
        "down_desc": 'תהליך Klar המצורף אינו רץ. טענו מחדש את Klar NLU בהגדרות ← מכשירים ושירותים.',
    },
    "fa": {
        "user_desc": 'این یکپارچه\u200cسازی با Assist صحبت می\u200cکند. موتور جداگانه\u200cای گفتار را تحلیل می\u200cکند: برنامه Klar NLU، فرایند همراه یا Docker. در Home Assistant OS برنامه را نصب کنید و استفاده از برنامه Klar NLU را انتخاب کنید. بدون برنامه موتور همراه را شروع کنید. هر دو را با هم اجرا نکنید.',
        "mode": 'موتور',
        "channel": 'کانال انتشار',
        "url": 'نشانی API کلار',
        "token": 'توکن نوشتن',
        "invalid": 'نشانی باید http(s) باشد و نام کاربری نداشته باشد.',
        "already": 'Klar NLU از قبل پیکربندی شده',
        "opt_desc": 'صدا، زبان‌های Assist و مدل زبانی در رابط اپراتور Klar (تنظیمات) هستند. این فرم فقط موتور را وصل می‌کند: نشانی، رمز و کانال.',
        "personality": 'شخصیت',
        "languages": 'زبان\u200cها',
        "fallback": 'عامل گفتگو برای گپ',
        "refine_speech": 'بازنویسی پاسخ\u200cهای NLU توسط LLM',
        "refine_prompt": 'اعلان اصلاح',
        "assist_filter": 'فقط نهادهای نمایان برای Assist را کنترل کن',
        "nlu_rag": 'NLU-RAG (اختیاری)',
        "quiet_ack": 'تأیید کوتاه (زنگ)',
        "calendar_llm": 'پرس‌وجوهای تقویم را به مدل زبانی بفرست',
        "help_personality": 'در این یکپارچه\u200cسازی است، نه در برنامه Klar.',
        "help_refine_speech": 'Klar همچنان دستگاه\u200cها را کنترل می\u200cکند. LLM پشتیبان پاسخ را بازنویسی می\u200cکند.',
        "help_refine_prompt": 'اعلان سیستمی صدا. بدون کنترل دستگاه، بدون واقعیت تازه، همان زبان.',
        "help_token": 'همان توکن برنامه Klar.',
        "help_assist": 'روشن: فقط آنچه Assist می\u200cبیند. خاموش: شامل نهادهای پنهان.',
        "help_rag": 'پیش\u200cفرض خاموش. در گپ فقط قطعه تطبیق\u200cشده به مدل پشتیبان می\u200cرود.',
        "help_quiet": 'روشن/خاموش ساده چراغ بدون جمله؛ فقط صدای کوتاه روی ماهواره.',
        "help_calendar_llm": 'پیش‌فرض خاموش. روشن: کلار تقویم را می‌خواند و مدل پشتیبان رویدادها را می‌گوید. خاموش: خود کلار فهرست را می‌گوید. ساختن، حذف و جابه‌جایی در کلار می‌ماند.',
        "help_languages": 'پیش\u200cفرض زبان سیستم Home Assistant است.',
        "help_channel": 'هر زمان. Staging به Klar NLU (Staging) اشاره می\u200cکند.',
        "local": 'شروع موتور همراه (فقط HACS)',
        "remote": 'استفاده از برنامه Klar NLU یا Docker',
        "stable": 'Stable (تولید)',
        "staging": 'Staging (نامزد)',
        "system": 'زبان سیستم',
        "all": 'همه زبان\u200cها',
        "normal": 'معمولی',
        "casual": 'راحت',
        "caring": 'مهربان',
        "grumpy": 'بدخلق',
        "sarcastic": 'طعنه\u200cآمیز',
        "pirate": 'دزد دریایی',
        "quiet_name": 'تأیید کوتاه',
        "heard": 'آخرین شنیده',
        "decision": 'آخرین تصمیم',
        "speech": 'آخرین پاسخ',
        "area": 'شنیده در',
        "down_title": 'موتور Klar متوقف شد',
        "down_desc": 'فرایند همراه Klar در حال اجرا نیست. Klar NLU را در تنظیمات ← دستگاه\u200cها و خدمات دوباره بارگذاری کنید.',
    },
    "ur": {
        "user_desc": 'یہ انٹیگریشن Assist سے بات کرتی ہے۔ الگ انجن تقریر پڑھتا ہے: Klar NLU ایپ، شامل عمل، یا Docker۔ Home Assistant OS پر ایپ لگائیں اور Klar NLU ایپ استعمال کریں منتخب کریں۔ بغیر ایپ شامل انجن چلائیں۔ دونوں ایک ساتھ نہ چلائیں۔',
        "mode": 'انجن',
        "channel": 'ریلیز چینل',
        "url": 'Klar API یو آر ایل',
        "token": 'لکھنے کا ٹوکن',
        "invalid": 'یو آر ایل http(s) ہو اور صارف نام نہ ہو۔',
        "already": 'Klar NLU پہلے سے سیٹ ہے',
        "opt_desc": 'آواز، Assist زبانیں اور LLM کلار آپریٹر UI (ترتیبات) میں ہیں۔ یہ فارم صرف انجن جوڑتا ہے: URL، ٹوکن اور چینل۔',
        "personality": 'شخصیت',
        "languages": 'زبانیں',
        "fallback": 'گپ شپ کے لیے گفتگو ایجنٹ',
        "refine_speech": 'LLM سے NLU جواب درست کریں',
        "refine_prompt": 'درستگی کا پرامپٹ',
        "assist_filter": 'صرف Assist کو دکھائی گئی ہستیاں کنٹرول کریں',
        "nlu_rag": 'NLU-RAG (اختیاری)',
        "quiet_ack": 'مختصر تصدیق (گھنٹی)',
        "calendar_llm": 'کیلنڈر سوالات ماڈل کو بھیجیں',
        "help_personality": 'اس انٹیگریشن میں ہے، Klar ایپ میں نہیں۔',
        "help_refine_speech": 'Klar آلات کنٹرول کرتا رہتا ہے۔ بیک اپ LLM جواب دوبارہ لکھتا ہے۔',
        "help_refine_prompt": 'آواز کا سسٹم پرامپٹ۔ آلات کنٹرول نہیں، نئی حقیقت نہیں، وہی زبان۔',
        "help_token": 'وہی ٹوکن جو Klar ایپ میں ہے۔',
        "help_assist": 'آن: صرف جو Assist دیکھے۔ آف: چھپی ہستیاں بھی۔',
        "help_rag": 'طے شدہ آف۔ بات چیت میں صرف پہچانا ہوا ٹکڑا بیک اپ ماڈل کو جاتا ہے۔',
        "help_quiet": 'سادہ بتی آن/آف پر بات نہیں، سیٹلائٹ پر صرف مختصر آواز۔',
        "help_calendar_llm": 'طے شدہ بند۔ آن: کلار کیلنڈر پڑھتا ہے، بیک اپ ماڈل تقریبات کہتا ہے۔ آف: کلار فہرست خود کہتا ہے۔ بنانا، مٹانا اور منتقل کلار ہی کرتا ہے۔',
        "help_languages": 'طے شدہ Home Assistant کی سسٹم زبان ہے۔',
        "help_channel": 'کسی بھی وقت۔ Staging Klar NLU (Staging) کی طرف ہے۔',
        "local": 'شامل انجن چلائیں (صرف HACS)',
        "remote": 'Klar NLU ایپ یا Docker استعمال کریں',
        "stable": 'Stable (پروڈکشن)',
        "staging": 'Staging (امیدوار)',
        "system": 'سسٹم زبان',
        "all": 'تمام زبانیں',
        "normal": 'عام',
        "casual": 'آسان',
        "caring": 'خیال رکھنے والی',
        "grumpy": 'چڑچڑی',
        "sarcastic": 'طنزیہ',
        "pirate": 'قزاق',
        "quiet_name": 'مختصر تصدیق',
        "heard": 'آخری سنا',
        "decision": 'آخری فیصلہ',
        "speech": 'آخری جواب',
        "area": 'سنا گیا',
        "down_title": 'Klar انجن رک گیا',
        "down_desc": 'شامل Klar عمل نہیں چل رہا۔ سیٹنگز ← آلات اور سروسز سے Klar NLU دوبارہ لوڈ کریں۔',
    },
    "tr": {
        "user_desc": 'Bu entegrasyon Assist ile konuşur. Ayrı bir motor konuşmayı çözer: Klar NLU uygulaması, paket süreç veya Docker. Home Assistant OS’te uygulamayı kurun ve Klar NLU uygulamasını kullan seçin. Uygulama yoksa paket motoru başlatın. İkisini birden çalıştırmayın.',
        "mode": 'Motor',
        "channel": 'Yayın kanalı',
        "url": 'Klar API URL’si',
        "token": 'Yazma jetonu',
        "invalid": 'URL http(s) olmalı, kullanıcı adı olmamalı.',
        "already": 'Klar NLU zaten kurulu',
        "opt_desc": 'Ses, Assist dilleri ve LLM, Klar operatör arayüzünde (Ayarlar). Bu form yalnızca motoru bağlar: URL, jeton ve kanal.',
        "personality": 'Kişilik',
        "languages": 'Diller',
        "fallback": 'Sohbet için konuşma aracısı',
        "refine_speech": 'LLM NLU yanıtlarını yeniden yazsın',
        "refine_prompt": 'İyileştirme istemi',
        "assist_filter": 'Yalnız Assist’e açık varlıkları denetle',
        "nlu_rag": 'NLU-RAG (isteğe bağlı)',
        "quiet_ack": 'Kısa onay (zil)',
        "calendar_llm": 'Takvim sorgularını LLM\'ye gönder',
        "help_personality": 'Klar uygulamasında değil, bu entegrasyonda.',
        "help_refine_speech": 'Klar cihazları denetlemeye devam eder. Yedek LLM yanıtı yeniden yazar.',
        "help_refine_prompt": 'Sesin sistem istemi. Cihaz denetimi yok, yeni olgu yok, aynı dil.',
        "help_token": 'Klar uygulamasındakiyle aynı jeton.',
        "help_assist": 'Açık: yalnızca Assist’in gördüğü. Kapalı: gizli varlıklar da.',
        "help_rag": 'Varsayılan kapalı. Sohbette yedek modele yalnızca eşleşen dilim gider.',
        "help_quiet": 'Basit ışık aç/kapa konuşulmaz, uydu üzerinde kısa ses.',
        "help_calendar_llm": 'Varsayılan kapalı. Açık: Klar takvimi okur, yedek LLM etkinlikleri söyler. Kapalı: Klar listeyi söyler. Oluşturma, silme ve taşıma Klar\'da kalır.',
        "help_languages": 'Varsayılan Home Assistant sistem dilidir.',
        "help_channel": 'İstediğiniz zaman. Staging, Klar NLU (Staging)’i gösterir.',
        "local": 'Paket motoru başlat (yalnız HACS)',
        "remote": 'Klar NLU uygulaması veya Docker kullan',
        "stable": 'Stable (üretim)',
        "staging": 'Staging (aday)',
        "system": 'Sistem dili',
        "all": 'Tüm diller',
        "normal": 'Normal',
        "casual": 'Rahat',
        "caring": 'Şefkatli',
        "grumpy": 'Huysuz',
        "sarcastic": 'Alaycı',
        "pirate": 'Korsan',
        "quiet_name": 'Kısa onay',
        "heard": 'Son duyulan',
        "decision": 'Son karar',
        "speech": 'Son yanıt',
        "area": 'Duyulduğu yer',
        "down_title": 'Klar motoru durdu',
        "down_desc": 'Paket Klar süreci çalışmıyor. Ayarlar → Cihazlar ve hizmetler’den Klar NLU’yu yeniden yükleyin.',
    },
    "hy": {
        "user_desc": 'Այս ինտեգրումը խոսում է Assist-ի հետ։ Առանձին շարժիչ է վերլուծում խոսքը՝ Klar NLU հավելվածը, կցված գործընթացը կամ Docker։ Home Assistant OS-ում տեղադրեք նաև հավելվածը և ընտրեք Օգտագործել Klar NLU հավելվածը։ Առանց հավելվածի գործարկեք կցված շարժիչը։ Մի գործարկեք երկուսն էլ։',
        "mode": 'Շարժիչ',
        "channel": 'Թողարկման ալիք',
        "url": 'Klar API հասցե',
        "token": 'Գրման նշան',
        "invalid": 'Հասցեն պետք է լինի http(s)՝ առանց օգտանվան։',
        "already": 'Klar NLU արդեն կարգավորված է',
        "opt_desc": 'Ձայնը, Assist-ի լեզուները և LLM-ը Klar օպերատորի միջերեսում են (Կարգավորումներ)։ Այս ձևը միայն շարժիչն է կապում՝ URL, նշան և ալիք։',
        "personality": 'Անհատականություն',
        "languages": 'Լեզուներ',
        "fallback": 'Զրույցի գործակալ շաղակրատանքի համար',
        "refine_speech": 'Թող LLM-ը վերաձևակերպի NLU պատասխանները',
        "refine_prompt": 'Հղկման հուշում',
        "assist_filter": 'Կառավարել միայն Assist-ին երևացող միավորները',
        "nlu_rag": 'NLU-RAG (ըստ ցանկության)',
        "quiet_ack": 'Կարճ հաստատում (զանգ)',
        "calendar_llm": 'Oracuyci harcumnern ugharkel LLM-in',
        "help_personality": 'Այս ինտեգրման մեջ է, ոչ Klar հավելվածում։',
        "help_refine_speech": 'Klar-ը շարունակում է կառավարել սարքերը։ Պահեստային LLM-ը վերագրում է պատասխանը։',
        "help_refine_prompt": 'Ձայնի համակարգային հուշում։ Առանց սարքի կառավարման, առանց նոր փաստերի, նույն լեզուն։',
        "help_token": 'Նույն նշանը, ինչ Klar հավելվածում։',
        "help_assist": 'Միացված՝ միայն այն, ինչ տեսնում է Assist-ը։ Անջատված՝ նաև թաքնված միավորներ։',
        "help_rag": 'Լռելյայն անջատված։ Զրույցում պահեստային մոդելին գնում է միայն համընկած հատվածը։',
        "help_quiet": 'Պարզ լույս միացնել/անջատելիս խոսք չկա, միայն կարճ ձայն արբանյակի վրա։',
        "help_calendar_llm": 'Lreljyayn anjatkan. Miacvac: Klary kardum e oracuycy, reservayin LLM-n asum e iradarjutyunnery. Anjatkan: Klary asum e cucaky. Steghtsumn, jnjumn u teghapoxumn mnun en Klary tesakum.',
        "help_languages": 'Լռելյայն հետևում է Home Assistant համակարգի լեզվին։',
        "help_channel": 'Ցանկացած պահի։ Staging-ը մատնանշում է Klar NLU (Staging)։',
        "local": 'Գործարկել կցված շարժիչը (միայն HACS)',
        "remote": 'Օգտագործել Klar NLU հավելվածը կամ Docker',
        "stable": 'Stable (արտադրություն)',
        "staging": 'Staging (թեկնածու)',
        "system": 'Համակարգի լեզու',
        "all": 'Բոլոր լեզուները',
        "normal": 'Սովորական',
        "casual": 'Ազատ',
        "caring": 'Հոգատար',
        "grumpy": 'Դժգոհ',
        "sarcastic": 'Սարկաստիկ',
        "pirate": 'Ծովահեն',
        "quiet_name": 'Կարճ հաստատում',
        "heard": 'Վերջին լսածը',
        "decision": 'Վերջին որոշումը',
        "speech": 'Վերջին պատասխանը',
        "area": 'Լսվել է',
        "down_title": 'Klar շարժիչը կանգնել է',
        "down_desc": 'Կցված Klar գործընթացը չի աշխատում։ Վերաբեռնեք Klar NLU-ն Կարգավորումներ → Սարքեր և ծառայություններ։',
    },
    "ka": {
        "user_desc": 'ეს ინტეგრაცია Assist-თან საუბრობს. ცალკე ძრავა აანალიზებს მეტყველებას: Klar NLU აპი, ჩართული პროცესი ან Docker. Home Assistant OS-ზე დააყენეთ აპიც და აირჩიეთ Klar NLU აპის გამოყენება. აპის გარეშე გაუშვით ჩართული ძრავა. ორივე ერთად ნუ გაუშვებთ.',
        "mode": 'ძრავა',
        "channel": 'გამოშვების არხი',
        "url": 'Klar API URL',
        "token": 'ჩაწერის ტოკენი',
        "invalid": 'URL უნდა იყოს http(s) მომხმარებლის სახელის გარეშე.',
        "already": 'Klar NLU უკვეა კონფიგურირებული',
        "opt_desc": 'ხმა, Assist-ის ენები და LLM Klar-ის ოპერატორის UI-შია (პარამეტრები). ეს ფორმა მხოლოდ ძრავს აკავშირებს: URL, ტოკენი და არხი.',
        "personality": 'პიროვნება',
        "languages": 'ენები',
        "fallback": 'საუბრის აგენტი ჩატისთვის',
        "refine_speech": 'LLM-მა გადააფორმოს NLU პასუხები',
        "refine_prompt": 'დახვეწის მოთხოვნა',
        "assist_filter": 'მართე მხოლოდ Assist-ისთვის გამოჩენილი ერთეულები',
        "nlu_rag": 'NLU-RAG (არასავალდებულო)',
        "quiet_ack": 'მოკლე დადასტურება (ზარი)',
        "calendar_llm": 'Kalendaris motkhovnebi gaaagzavne LLM-s',
        "help_personality": 'ამ ინტეგრაციაშია, არა Klar აპში.',
        "help_refine_speech": 'Klar კვლავ მართავს მოწყობილობებს. სარეზერვო LLM გადაწერს პასუხს.',
        "help_refine_prompt": 'ხმის სისტემური მოთხოვნა. მოწყობილობის კონტროლი არა, ახალი ფაქტები არა, იგივე ენა.',
        "help_token": 'იგივე ტოკენი, რაც Klar აპში.',
        "help_assist": 'ჩართული: მხოლოდ ის, რასაც Assist ხედავს. გამორთული: დამალული ერთეულებიც.',
        "help_rag": 'ნაგულისხმევად გამორთული. ჩატში სარეზერვო მოდელს მხოლოდ დამთხვეული ნაწილი მიდის.',
        "help_quiet": 'მარტივი სინათლის ჩართვა/გამორთვა უსიტყვოდ, მხოლოდ მოკლე ხმა თანამგზავრზე.',
        "help_calendar_llm": 'Standartulad gamtishulia. Chartuli: Klari kitkhulobs kalendars, rezervuli LLM ambobs movlenebs. Gamortuli: Klari ambobs sias. Shekmna, washla da gadatanili rcheba Klartan.',
        "help_languages": 'ნაგულისხმევი მიჰყვება Home Assistant სისტემის ენას.',
        "help_channel": 'ნებისმიერ დროს. Staging მიუთითებს Klar NLU (Staging).',
        "local": 'ჩართული ძრავის გაშვება (მხოლოდ HACS)',
        "remote": 'Klar NLU აპის ან Docker-ის გამოყენება',
        "stable": 'Stable (წარმოება)',
        "staging": 'Staging (კანდიდატი)',
        "system": 'სისტემის ენა',
        "all": 'ყველა ენა',
        "normal": 'ჩვეულებრივი',
        "casual": 'მშვიდი',
        "caring": 'მზრუნველი',
        "grumpy": 'გაბრაზებული',
        "sarcastic": 'სარკასტული',
        "pirate": 'მეკობრე',
        "quiet_name": 'მოკლე დადასტურება',
        "heard": 'ბოლოს გაგონილი',
        "decision": 'ბოლო გადაწყვეტილება',
        "speech": 'ბოლო პასუხი',
        "area": 'გაიგო',
        "down_title": 'Klar ძრავა გაჩერდა',
        "down_desc": 'ჩართული Klar პროცესი არ მუშაობს. გადატვირთეთ Klar NLU პარამეტრები → მოწყობილობები და სერვისები.',
    },
    "mn": {
        "user_desc": 'Энэ нэгтгэл Assist-тэй ярина. Тусдаа хөдөлгүүр яриаг задлана: Klar NLU апп, багц процесс эсвэл Docker. Home Assistant OS дээр аппыг суулгаад Klar NLU апп ашиглах-ыг сонгоно. Аппгүй бол багц хөдөлгүүрийг асаана. Хоёуланг нь бүү ажиллуул.',
        "mode": 'Хөдөлгүүр',
        "channel": 'Гаргалтын суваг',
        "url": 'Klar API хаяг',
        "token": 'Бичих токен',
        "invalid": 'Хаяг http(s) байх ёстой, хэрэглэгчийн нэргүй.',
        "already": 'Klar NLU аль хэдийн тохируулагдсан',
        "opt_desc": 'Дуу хоолой, Assist хэл, LLM Klar операторын UI (Тохиргоо)-д байна. Энэ маягт зөвхөн хөдөлгүүрийг холбоно: URL, токен, суваг.',
        "personality": 'Зан чанар',
        "languages": 'Хэлнүүд',
        "fallback": 'Чатлах ярианы агент',
        "refine_speech": 'LLM-ээр NLU хариуг дахин бичүүлэх',
        "refine_prompt": 'Засварын сануулга',
        "assist_filter": 'Зөвхөн Assist-д харагдсан нэгжүүдийг удирдах',
        "nlu_rag": 'NLU-RAG (сонголттой)',
        "quiet_ack": 'Богино баталгаа (хонх)',
        "calendar_llm": 'Хуанлийн асуултыг LLM руу илгээх',
        "help_personality": 'Klar апп биш, энэ нэгтгэлд хадгалагдана.',
        "help_refine_speech": 'Klar төхөөрөмжүүдийг удирдсаар байна. Нөөц LLM хариуг дахин бичнэ.',
        "help_refine_prompt": 'Дууны системийн сануулга. Төхөөрөмж удирдахгүй, шинэ баримтгүй, ижил хэл.',
        "help_token": 'Klar апптай ижил токен.',
        "help_assist": 'Асаалттай: зөвхөн Assist харахыг. Унтраалттай: нуугдсан нэгж ч багтана.',
        "help_rag": 'Анхдагч унтраалттай. Чатад нөөц загварт зөвхөн таарсан хэсэг очно.',
        "help_quiet": 'Энгийн гэрэл асаах/унтраахад яриагүй, хиймэл дагуул дээр богино дуу.',
        "help_calendar_llm": 'Анхдагч унтраалттай. Асаалттай: Klar хуанли уншиж, нөөц LLM үйл явдлыг хэлнэ. Унтраалттай: Klar жагсаалтыг өөрөө хэлнэ. Үүсгэх, устгах, зөөх нь Klar дээр үлдэнэ.',
        "help_languages": 'Анхдагч нь Home Assistant системийн хэл.',
        "help_channel": 'Хэзээ ч. Staging нь Klar NLU (Staging) руу заана.',
        "local": 'Багц хөдөлгүүрийг эхлүүлэх (зөвхөн HACS)',
        "remote": 'Klar NLU апп эсвэл Docker ашиглах',
        "stable": 'Stable (үйлдвэрлэл)',
        "staging": 'Staging (нэр дэвшигч)',
        "system": 'Системийн хэл',
        "all": 'Бүх хэл',
        "normal": 'Энгийн',
        "casual": 'Суларсан',
        "caring": 'Халамжтай',
        "grumpy": 'Ууртай',
        "sarcastic": 'Егөөтэй',
        "pirate": 'Далайн дээрэмчин',
        "quiet_name": 'Богино баталгаа',
        "heard": 'Сүүлд сонссон',
        "decision": 'Сүүлийн шийдвэр',
        "speech": 'Сүүлийн хариу',
        "area": 'Сонссон газар',
        "down_title": 'Klar хөдөлгүүр зогссон',
        "down_desc": 'Багц Klar процесс ажиллахгүй байна. Тохиргоо → Төхөөрөмж ба үйлчилгээнээс Klar NLU-г дахин ачаална уу.',
    },
    "af": {
        "user_desc": 'Hierdie integrasie praat met Assist. ’n Aparte enjin ontleed spraak: die Klar NLU-app, hierdie gebundelde proses of Docker. Op Home Assistant OS installeer ook die app en kies Gebruik die Klar NLU-app. Sonder die app, begin die gebundelde enjin. Moenie albei laat loop nie.',
        "mode": 'Enjin',
        "channel": 'Vrystellingskanaal',
        "url": 'Klar API-URL',
        "token": 'Skryf-token',
        "invalid": 'URL moet http(s) wees sonder gebruikersnaam.',
        "already": 'Klar NLU is al opgestel',
        "opt_desc": 'Stem, Assist-tale en die LLM leef in die Klar-operateur-UI (Instellings). Hierdie vorm verbind net die enjin: URL, token en kanaal.',
        "personality": 'Persoonlikheid',
        "languages": 'Tale',
        "fallback": 'Gespreksagent vir kuierpraatjies',
        "refine_speech": 'Laat die LLM NLU-antwoorde herformuleer',
        "refine_prompt": 'Verfynde opdrag',
        "assist_filter": 'Beheer slegs entiteite wat aan Assist blootgestel is',
        "nlu_rag": 'NLU-RAG (opsioneel)',
        "quiet_ack": 'Kort bevestiging (klokkie)',
        "calendar_llm": 'Stuur kalendernavrae na die LLM',
        "help_personality": 'In hierdie integrasie, nie in die Klar-app nie.',
        "help_refine_speech": 'Klar beheer steeds toestelle. Die rugsteun-LLM herskryf die antwoord.',
        "help_refine_prompt": 'Stelselopdrag vir die stem. Geen toestelbeheer, geen nuwe feite, dieselfde taal.',
        "help_token": 'Dieselfde token as in die Klar-app.',
        "help_assist": 'Aan: net wat Assist mag sien. Af: ook versteekte entiteite.',
        "help_rag": 'Verstek af. In gesels stuur slegs die ooreenstemmende stuk na die rugsteunmodel.',
        "help_quiet": 'By eenvoudige lig aan/af geen sin nie, net ’n kort klank op die satelliet.',
        "help_calendar_llm": 'Verstek af. Aan: Klar lees die kalender, die terugval-LLM sê die afsprake. Af: Klar sê self die lys. Skep, skrapping en skuif bly by Klar.',
        "help_languages": 'Verstek volg die Home Assistant-stelseltaal.',
        "help_channel": 'Enige tyd. Staging wys na Klar NLU (Staging).',
        "local": 'Begin die gebundelde enjin (slegs HACS)',
        "remote": 'Gebruik die Klar NLU-app of Docker',
        "stable": 'Stable (produksie)',
        "staging": 'Staging (kandidaat)',
        "system": 'Stelseltaal',
        "all": 'Alle tale',
        "normal": 'Normaal',
        "casual": 'Ontspanne',
        "caring": 'Omgeë',
        "grumpy": 'Knorrig',
        "sarcastic": 'Sarkasties',
        "pirate": 'Seerower',
        "quiet_name": 'Kort bevestiging',
        "heard": 'Laas gehoor',
        "decision": 'Laaste besluit',
        "speech": 'Laaste antwoord',
        "area": 'Gehoor in',
        "down_title": 'Klar-enjin gestop',
        "down_desc": 'Die gebundelde Klar-proses loop nie. Herlaai Klar NLU in Instellings → Toestelle en dienste.',
    },
    "sw": {
        "user_desc": 'Muunganisho huu unazungumza na Assist. Injini tofauti huchambua usemi: programu ya Klar NLU, mchakato uliojumuishwa au Docker. Kwenye Home Assistant OS sakinisha pia programu kisha chagua Tumia programu ya Klar NLU. Bila programu anzisha injini iliyojumuishwa. Usiendeshe zote mbili.',
        "mode": 'Injini',
        "channel": 'Kituo cha toleo',
        "url": 'URL ya API ya Klar',
        "token": 'Tokeni ya kuandika',
        "invalid": 'URL lazima iwe http(s) bila jina la mtumiaji.',
        "already": 'Klar NLU tayari imewekwa',
        "opt_desc": 'Sauti, lugha za Assist na LLM ziko kwenye UI ya opereta ya Klar (Mipangilio). Fomu hii inaunganisha injini tu: URL, tokeni na kituo.',
        "personality": 'Tabia',
        "languages": 'Lugha',
        "fallback": 'Ajenti wa mazungumzo kwa gumzo',
        "refine_speech": 'Acha LLM iandike upya majibu ya NLU',
        "refine_prompt": 'Kidokezo cha kuboresha',
        "assist_filter": 'Dhibiti tu huluki zilizoonekana kwa Assist',
        "nlu_rag": 'NLU-RAG (si lazima)',
        "quiet_ack": 'Uthibitisho mfupi (kengele)',
        "calendar_llm": 'Tuma maswali ya kalenda kwa LLM',
        "help_personality": 'Iko katika muunganisho huu, si katika programu ya Klar.',
        "help_refine_speech": 'Klar bado inadhibiti vifaa. LLM ya akiba inaandika tena jibu.',
        "help_refine_prompt": 'Kidokezo cha mfumo wa sauti. Hakuna udhibiti wa kifaa, hakuna ukweli mpya, lugha ileile.',
        "help_token": 'Tokeni ileile kama katika programu ya Klar.',
        "help_assist": 'Washa: tu kile Assist inaona. Zima: hata huluki zilizofichwa.',
        "help_rag": 'Imezimwa kwa chaguo-msingi. Kwenye gumzo kipande kilicholingana tu huenda kwa modeli ya akiba.',
        "help_quiet": 'Kuwasha/kuzima taa rahisi hakuna sentensi, sauti fupi tu kwenye satelaiti.',
        "help_calendar_llm": 'Zimwa kwa chaguo-msingi. Washa: Klar inasoma kalenda, LLM ya akiba inasema matukio. Zima: Klar inasema orodha. Kuunda, kufuta na kuhamisha vinabaki kwa Klar.',
        "help_languages": 'Chaguo-msingi hufuata lugha ya mfumo wa Home Assistant.',
        "help_channel": 'Wakati wowote. Staging inaelekeza Klar NLU (Staging).',
        "local": 'Anzisha injini iliyojumuishwa (HACS tu)',
        "remote": 'Tumia programu ya Klar NLU au Docker',
        "stable": 'Stable (uzalishaji)',
        "staging": 'Staging (mgombea)',
        "system": 'Lugha ya mfumo',
        "all": 'Lugha zote',
        "normal": 'Kawaida',
        "casual": 'Rahisi',
        "caring": 'Mwenye kujali',
        "grumpy": 'Mwenye hasira',
        "sarcastic": 'Mzaha mkali',
        "pirate": 'Haramia',
        "quiet_name": 'Uthibitisho mfupi',
        "heard": 'Kilichosikika mwisho',
        "decision": 'Uamuzi wa mwisho',
        "speech": 'Jibu la mwisho',
        "area": 'Ilisikika katika',
        "down_title": 'Injini ya Klar imesimama',
        "down_desc": 'Mchakato wa Klar uliojumuishwa hauendi. Pakia tena Klar NLU katika Mipangilio → Vifaa na huduma.',
    },
}
