"""HA UI copy recovered for East and Southeast Asian Assist locales."""

from __future__ import annotations

ASIA: dict[str, dict[str, str]] = {
    "zh-CN": {
        "user_desc": '此集成与 Assist 对话。语音由 Klar NLU 应用、捆绑进程或 Docker 解析。在 Home Assistant OS 上请安装应用并选择使用 Klar NLU 应用；否则启动捆绑引擎。不要同时运行。发布通道可稍后更改。',
        "mode": '引擎',
        "channel": '发布通道',
        "url": 'Klar API 地址',
        "token": '写入令牌',
        "invalid": '网址必须是 http(s)，且不含用户名。',
        "already": 'Klar NLU 已经配置',
        "opt_desc": '语音、Assist 语言和 LLM 在 Klar 操作界面（设置）中。此表单只连接引擎：URL、令牌和通道。',
        "personality": '人格',
        "languages": '语言',
        "fallback": '闲聊对话代理',
        "refine_speech": '用 LLM 润色 NLU 回复',
        "refine_prompt": '润色提示词',
        "assist_filter": '仅控制已向 Assist 公开的实体',
        "nlu_rag": 'NLU-RAG（可选）',
        "quiet_ack": '短确认（提示音）',
        "calendar_llm": '把日历查询发给大模型',
        "help_personality": '保存在此集成中，不在 Klar 应用里。Assist 与 LLM 语音遵循该提示词。',
        "help_refine_speech": 'Klar 仍控制设备。后备 LLM 会改写已完成的回复。',
        "help_refine_prompt": '语音系统提示。不控制设备、不编造事实、保持同一语言。',
        "help_token": '与 Klar 应用相同的令牌。',
        "help_assist": '开：仅 Assist 可见实体。关：也包括隐藏实体。',
        "help_rag": '默认关闭。闲聊时只把已匹配片段送给后备模型。',
        "help_quiet": '简单开关灯时不说话，只在卫星上播放短提示音。',
        "help_calendar_llm": '默认关闭。开：Klar 读取日历，由后备大模型口述日程。关：Klar 自己念列表。创建、删除和移动仍由 Klar 处理。',
        "help_languages": '默认跟随 Home Assistant 系统语言。',
        "help_channel": '随时可改。预发布指向 Klar NLU（Staging）。',
        "local": '启动捆绑引擎（仅 HACS）',
        "remote": '使用 Klar NLU 应用或 Docker',
        "stable": '稳定版（生产）',
        "staging": '预发布（候选）',
        "system": '系统语言',
        "all": '全部语言',
        "normal": '普通',
        "casual": '轻松',
        "caring": '体贴',
        "grumpy": '别扭',
        "sarcastic": '讽刺',
        "pirate": '海盗',
        "quiet_name": '短确认',
        "heard": '上次听到',
        "decision": '上次判定',
        "speech": '上次回复',
        "area": '听到位置',
        "down_title": 'Klar 引擎已停止',
        "down_desc": '捆绑的 Klar 进程未运行。请在设置 → 设备与服务中重新加载 Klar NLU。',
    },
    "zh-TW": {
        "user_desc": '此整合與 Assist 對話。語音由 Klar NLU 應用程式、內建程序或 Docker 解析。在 Home Assistant OS 請安裝應用並選擇使用 Klar NLU 應用；否則啟動內建引擎。不要同時執行。發行通道可稍後變更。',
        "mode": '引擎',
        "channel": '發行通道',
        "url": 'Klar API 網址',
        "token": '寫入權杖',
        "invalid": '網址必須是 http(s)，且不含使用者名稱。',
        "already": 'Klar NLU 已經設定',
        "opt_desc": '語音、Assist 語言和 LLM 在 Klar 操作介面（設定）中。此表單只連接引擎：URL、權杖和通道。',
        "personality": '人格',
        "languages": '語言',
        "fallback": '閒聊對話代理',
        "refine_speech": '用 LLM 潤飾 NLU 回覆',
        "refine_prompt": '潤飾提示',
        "assist_filter": '只控制已向 Assist 公開的實體',
        "nlu_rag": 'NLU-RAG（選用）',
        "quiet_ack": '簡短確認（提示音）',
        "calendar_llm": '把日曆查詢傳給大型語言模型',
        "help_personality": '存在此整合中，不在 Klar 應用裡。',
        "help_refine_speech": 'Klar 仍控制裝置。後援 LLM 會改寫回覆。',
        "help_refine_prompt": '語音系統提示。不控制裝置、不編造事實、維持同一語言。',
        "help_token": '與 Klar 應用相同的權杖。',
        "help_assist": '開：僅 Assist 可見實體。關：也包含隱藏實體。',
        "help_rag": '預設關閉。閒聊時只把已比對片段送給後援模型。',
        "help_quiet": '簡單開關燈時不說話，只在衛星播放短提示音。',
        "help_calendar_llm": '預設關閉。開：Klar 讀取日曆，由後援模型唸行程。關：Klar 自己唸清單。建立、刪除和移動仍由 Klar 處理。',
        "help_languages": '預設跟隨 Home Assistant 系統語言。',
        "help_channel": '隨時可改。預發佈指向 Klar NLU（Staging）。',
        "local": '啟動內建引擎（僅 HACS）',
        "remote": '使用 Klar NLU 應用或 Docker',
        "stable": '穩定版（正式）',
        "staging": '預發佈（候選）',
        "system": '系統語言',
        "all": '所有語言',
        "normal": '一般',
        "casual": '輕鬆',
        "caring": '體貼',
        "grumpy": '彆扭',
        "sarcastic": '諷刺',
        "pirate": '海盜',
        "quiet_name": '簡短確認',
        "heard": '上次聽到',
        "decision": '上次判定',
        "speech": '上次回覆',
        "area": '聽到位置',
        "down_title": 'Klar 引擎已停止',
        "down_desc": '內建 Klar 程序未在執行。請在設定 → 裝置與服務重新載入 Klar NLU。',
    },
    "zh-HK": {
        "user_desc": '此整合同 Assist 對話。語音由 Klar NLU 應用、內建程序或 Docker 解析。喺 Home Assistant OS 請安裝應用並選擇使用 Klar NLU 應用；否則啟動內建引擎。唔好兩個一齊開。',
        "mode": '引擎',
        "channel": '發行通道',
        "url": 'Klar API 網址',
        "token": '寫入權杖',
        "invalid": '網址必須係 http(s)，唔好帶用戶名。',
        "already": 'Klar NLU 已經設定',
        "opt_desc": '語音、Assist 語言和 LLM 在 Klar 操作介面（設定）中。此表格只連接引擎：URL、權杖和頻道。',
        "personality": '人格',
        "languages": '語言',
        "fallback": '閒聊對話代理',
        "refine_speech": '用 LLM 潤飾 NLU 回覆',
        "refine_prompt": '潤飾提示',
        "assist_filter": '只控制已向 Assist 公開嘅實體',
        "nlu_rag": 'NLU-RAG（可選）',
        "quiet_ack": '簡短確認（提示音）',
        "calendar_llm": '將日曆查詢交俾大模型',
        "help_personality": '存在此整合，唔喺 Klar 應用。',
        "help_refine_speech": 'Klar 仍然控制裝置。後備 LLM 會改寫回覆。',
        "help_refine_prompt": '語音系統提示。唔控制裝置、唔編造事實、用返同一語言。',
        "help_token": '同 Klar 應用一樣嘅權杖。',
        "help_assist": '開：只限 Assist 見到嘅實體。關：包括隱藏實體。',
        "help_rag": '預設關閉。傾偈時只將已配對片段交俾後備模型。',
        "help_quiet": '簡單開關燈唔講嘢，只喺衛星播短提示音。',
        "help_calendar_llm": '預設關閉。開：Klar 讀日曆，後備大模型講行程。關：Klar 自己講清單。新增、刪除同搬動仍然由 Klar 處理。',
        "help_languages": '預設跟 Home Assistant 系統語言。',
        "help_channel": '隨時可改。預發佈指向 Klar NLU（Staging）。',
        "local": '啟動內建引擎（只限 HACS）',
        "remote": '使用 Klar NLU 應用或 Docker',
        "stable": '穩定版（正式）',
        "staging": '預發佈（候選）',
        "system": '系統語言',
        "all": '所有語言',
        "normal": '一般',
        "casual": '輕鬆',
        "caring": '體貼',
        "grumpy": '脾氣',
        "sarcastic": '諷刺',
        "pirate": '海盜',
        "quiet_name": '簡短確認',
        "heard": '上次聽到',
        "decision": '上次判定',
        "speech": '上次回覆',
        "area": '聽到位置',
        "down_title": 'Klar 引擎已停止',
        "down_desc": '內建 Klar 程序未運行。請喺設定 → 裝置與服務重新載入 Klar NLU。',
    },
    "ja": {
        "user_desc": 'この連携は Assist と話します。音声は Klar NLU アプリ、同梱プロセス、または Docker が解析します。Home Assistant OS ではアプリも入れ、「Klar NLU アプリを使う」を選んでください。アプリがなければ同梱エンジンを起動します。両方は動かさないでください。',
        "mode": 'エンジン',
        "channel": 'リリースチャネル',
        "url": 'Klar API の URL',
        "token": '書き込みトークン',
        "invalid": 'URL はユーザー情報なしの http(s) である必要があります。',
        "already": 'Klar NLU はすでに設定されています',
        "opt_desc": '音声、Assist の言語、LLM は Klar オペレーター UI（設定）にあります。このフォームはエンジンの接続だけです：URL、トークン、チャネル。',
        "personality": '人格',
        "languages": '言語',
        "fallback": '雑談用会話エージェント',
        "refine_speech": 'LLM で NLU の返答を整える',
        "refine_prompt": '整形プロンプト',
        "assist_filter": 'Assist に公開されたエンティティだけ操作する',
        "nlu_rag": 'NLU-RAG（任意）',
        "quiet_ack": '短い確認（チャイム）',
        "calendar_llm": 'カレンダー照会をLLMに送る',
        "help_personality": 'Klar アプリではなく、この連携に保存されます。',
        "help_refine_speech": 'Klar は機器を操作し続けます。予備の LLM が返答を書き直します。',
        "help_refine_prompt": '声のシステムプロンプト。機器操作なし、新しい事実なし、同じ言語。',
        "help_token": 'Klar アプリと同じトークンです。',
        "help_assist": 'オン：Assist が見えるものだけ。オフ：非表示も含む。',
        "help_rag": '既定はオフ。雑談では一致した断片だけを予備モデルへ送ります。',
        "help_quiet": '単純な照明のオン／オフでは発話せず、衛星で短い音だけ鳴らします。',
        "help_calendar_llm": '初期値はオフ。オン：Klarがカレンダーを読み、予備LLMが予定を話す。オフ：Klar自身が一覧を話す。作成・削除・移動はKlarのまま。',
        "help_languages": '既定は Home Assistant のシステム言語です。',
        "help_channel": 'いつでも変更できます。Staging は Klar NLU（Staging）を指します。',
        "local": '同梱エンジンを起動（HACS のみ）',
        "remote": 'Klar NLU アプリまたは Docker を使う',
        "stable": 'Stable（本番）',
        "staging": 'Staging（候補）',
        "system": 'システム言語',
        "all": 'すべての言語',
        "normal": '標準',
        "casual": 'カジュアル',
        "caring": 'やさしい',
        "grumpy": '不機嫌',
        "sarcastic": '皮肉',
        "pirate": '海賊',
        "quiet_name": '短い確認',
        "heard": '最後に聞いた内容',
        "decision": '最後の判定',
        "speech": '最後の返答',
        "area": '聞いた場所',
        "down_title": 'Klar エンジンが停止',
        "down_desc": '同梱の Klar プロセスが動いていません。設定 → デバイスとサービスで Klar NLU を再読み込みしてください。',
    },
    "ko": {
        "user_desc": '이 통합은 Assist와 대화합니다. 음성은 Klar NLU 앱, 번들 프로세스 또는 Docker가 분석합니다. Home Assistant OS에서는 앱을 설치하고 Klar NLU 앱 사용을 고르세요. 앱이 없으면 번들 엔진을 시작하세요. 둘 다 실행하지 마세요.',
        "mode": '엔진',
        "channel": '릴리스 채널',
        "url": 'Klar API URL',
        "token": '쓰기 토큰',
        "invalid": 'URL은 사용자 정보 없는 http(s)여야 합니다.',
        "already": 'Klar NLU가 이미 설정되어 있습니다',
        "opt_desc": '음성, Assist 언어, LLM은 Klar 운영자 UI(설정)에 있습니다. 이 양식은 엔진만 연결합니다: URL, 토큰, 채널.',
        "personality": '성격',
        "languages": '언어',
        "fallback": '잡담용 대화 에이전트',
        "refine_speech": 'LLM으로 NLU 답변 다듬기',
        "refine_prompt": '다듬기 프롬프트',
        "assist_filter": 'Assist에 공개된 엔티티만 제어',
        "nlu_rag": 'NLU-RAG(선택)',
        "quiet_ack": '짧은 확인(차임)',
        "calendar_llm": '캘린더 질의를 LLM으로 보내기',
        "help_personality": 'Klar 앱이 아니라 이 통합에 저장됩니다.',
        "help_refine_speech": 'Klar는 계속 기기를 제어합니다. 예비 LLM이 답변을 다시 씁니다.',
        "help_refine_prompt": '음성 시스템 프롬프트. 기기 제어 없음, 새 사실 없음, 같은 언어.',
        "help_token": 'Klar 앱과 같은 토큰입니다.',
        "help_assist": '켜짐: Assist가 볼 수 있는 것만. 꺼짐: 숨긴 엔티티 포함.',
        "help_rag": '기본은 꺼짐. 잡담에서는 이미 맞춘 조각만 예비 모델로 보냅니다.',
        "help_quiet": '간단한 조명 켜기/끄기에서는 말하지 않고 위성에서 짧은 소리만 냅니다.',
        "help_calendar_llm": '기본은 끔. 켬: Klar가 캘린더를 읽고 예비 LLM이 일정을 말함. 끔: Klar가 목록을 말함. 만들기, 삭제, 이동은 Klar에 남음.',
        "help_languages": '기본값은 Home Assistant 시스템 언어입니다.',
        "help_channel": '언제든 변경할 수 있습니다. Staging은 Klar NLU(Staging)를 가리킵니다.',
        "local": '번들 엔진 시작(HACS만)',
        "remote": 'Klar NLU 앱 또는 Docker 사용',
        "stable": 'Stable(운영)',
        "staging": 'Staging(후보)',
        "system": '시스템 언어',
        "all": '모든 언어',
        "normal": '기본',
        "casual": '편안한',
        "caring": '다정한',
        "grumpy": '까칠한',
        "sarcastic": '빈정대는',
        "pirate": '해적',
        "quiet_name": '짧은 확인',
        "heard": '마지막으로 들음',
        "decision": '마지막 결정',
        "speech": '마지막 답변',
        "area": '들린 위치',
        "down_title": 'Klar 엔진 중지됨',
        "down_desc": '번들 Klar 프로세스가 실행되지 않습니다. 설정 → 기기 및 서비스에서 Klar NLU를 다시 로드하세요.',
    },
    "th": {
        "user_desc": 'การเชื่อมต่อนี้คุยกับ Assist เครื่องแยกจะถอดเสียง: แอป Klar NLU โปรเซสที่มากับตัว หรือ Docker บน Home Assistant OS ให้ติดตั้งแอปแล้วเลือกใช้แอป Klar NLU ถ้าไม่มีแอป ให้เริ่มเอนจินที่มากับตัว อย่าเปิดทั้งสอง',
        "mode": 'เอนจิน',
        "channel": 'ช่องเผยแพร่',
        "url": 'URL ของ Klar API',
        "token": 'โทเคนเขียน',
        "invalid": 'URL ต้องเป็น http(s) และไม่มีชื่อผู้ใช้',
        "already": 'ตั้งค่า Klar NLU แล้ว',
        "opt_desc": 'เสียง ภาษา Assist และ LLM อยู่ใน UI ผู้ปฏิบัติการของ Klar (การตั้งค่า) แบบฟอร์มนี้เชื่อมต่อเอนจินเท่านั้น: URL โทเค็น และช่องทาง',
        "personality": 'บุคลิก',
        "languages": 'ภาษา',
        "fallback": 'เอเจนต์สนทนาสำหรับคุยเล่น',
        "refine_speech": 'ให้ LLM ปรับคำตอบ NLU',
        "refine_prompt": 'พรอมต์ปรับแต่ง',
        "assist_filter": 'ควบคุมเฉพาะเอนทิตีที่เปิดให้ Assist',
        "nlu_rag": 'NLU-RAG (ไม่บังคับ)',
        "quiet_ack": 'ยืนยันสั้น (เสียง ding)',
        "calendar_llm": 'ส่งคำถามปฏิทินไปยัง LLM',
        "help_personality": 'อยู่ในอินทิเกรชันนี้ ไม่ได้อยู่ในแอป Klar',
        "help_refine_speech": 'Klar ยังควบคุมอุปกรณ์ LLM สำรองจะเขียนคำตอบใหม่',
        "help_refine_prompt": 'พรอมต์ระบบของเสียง ไม่ควบคุมอุปกรณ์ ไม่สร้างข้อเท็จจริงใหม่ ภาษาเดิม',
        "help_token": 'โทเคนเดียวกับแอป Klar',
        "help_assist": 'เปิด: เฉพาะที่ Assist เห็น ปิด: รวมเอนทิตีที่ซ่อน',
        "help_rag": 'ปิดเป็นค่าเริ่มต้น ตอนคุยส่งเฉพาะช่วงที่จับได้ไปยังโมเดลสำรอง',
        "help_quiet": 'เปิดหรือปิดไฟอย่างง่ายจะไม่พูด มีแต่เสียงสั้นที่ดาวเทียม',
        "help_calendar_llm": 'ปิดเป็นค่าเริ่มต้น เปิด: Klar อ่านปฏิทิน แล้ว LLM สำรองพูดนัด ปิด: Klar พูดรายการเอง สร้าง ลบ ย้ายยังอยู่ที่ Klar',
        "help_languages": 'ค่าเริ่มต้นคือภาษาของระบบ Home Assistant',
        "help_channel": 'เปลี่ยนได้ตลอด Staging ชี้ไปที่ Klar NLU (Staging)',
        "local": 'เริ่มเอนจินที่มากับตัว (เฉพาะ HACS)',
        "remote": 'ใช้แอป Klar NLU หรือ Docker',
        "stable": 'Stable (ใช้งานจริง)',
        "staging": 'Staging (ตัวทดลอง)',
        "system": 'ภาษาของระบบ',
        "all": 'ทุกภาษา',
        "normal": 'ปกติ',
        "casual": 'สบาย ๆ',
        "caring": 'ใส่ใจ',
        "grumpy": 'หงุดหงิด',
        "sarcastic": 'ประชด',
        "pirate": 'โจรสลัด',
        "quiet_name": 'ยืนยันสั้น',
        "heard": 'ได้ยินล่าสุด',
        "decision": 'การตัดสินใจล่าสุด',
        "speech": 'คำตอบล่าสุด',
        "area": 'ได้ยินที่',
        "down_title": 'เอนจิน Klar หยุด',
        "down_desc": 'โปรเซส Klar ที่มากับตัวไม่ได้ทำงาน โหลด Klar NLU ใหม่ที่ การตั้งค่า → อุปกรณ์และบริการ',
    },
    "vi": {
        "user_desc": 'Tích hợp này nói chuyện với Assist. Một động cơ riêng phân tích giọng nói: ứng dụng Klar NLU, tiến trình kèm theo hoặc Docker. Trên Home Assistant OS hãy cài ứng dụng và chọn Dùng ứng dụng Klar NLU. Không có ứng dụng thì khởi động động cơ kèm theo. Đừng chạy cả hai.',
        "mode": 'Động cơ',
        "channel": 'Kênh phát hành',
        "url": 'URL API Klar',
        "token": 'Token ghi',
        "invalid": 'URL phải là http(s), không có tên người dùng.',
        "already": 'Klar NLU đã được thiết lập',
        "opt_desc": 'Giọng nói, ngôn ngữ Assist và LLM nằm trong UI vận hành Klar (Cài đặt). Biểu mẫu này chỉ kết nối máy: URL, token và kênh.',
        "personality": 'Tính cách',
        "languages": 'Ngôn ngữ',
        "fallback": 'Tác nhân trò chuyện phiếm',
        "refine_speech": 'Để LLM chỉnh câu trả lời NLU',
        "refine_prompt": 'Lời nhắc tinh chỉnh',
        "assist_filter": 'Chỉ điều khiển thực thể đã mở cho Assist',
        "nlu_rag": 'NLU-RAG (tuỳ chọn)',
        "quiet_ack": 'Xác nhận ngắn (chuông)',
        "calendar_llm": 'Gửi câu hỏi lịch tới LLM',
        "help_personality": 'Nằm trong tích hợp này, không trong ứng dụng Klar.',
        "help_refine_speech": 'Klar vẫn điều khiển thiết bị. LLM dự phòng viết lại câu trả lời.',
        "help_refine_prompt": 'Lời nhắc hệ thống của giọng nói. Không điều khiển thiết bị, không bịa sự thật, cùng ngôn ngữ.',
        "help_token": 'Cùng token với ứng dụng Klar.',
        "help_assist": 'Bật: chỉ những gì Assist thấy. Tắt: cả thực thể ẩn.',
        "help_rag": 'Mặc định tắt. Khi trò chuyện chỉ gửi đoạn đã khớp tới mô hình dự phòng.',
        "help_quiet": 'Bật/tắt đèn đơn giản thì không nói, chỉ một tiếng ngắn trên vệ tinh.',
        "help_calendar_llm": 'Mặc định tắt. Bật: Klar đọc lịch, LLM dự phòng nói sự kiện. Tắt: Klar tự nói danh sách. Tạo, xóa, chuyển vẫn do Klar.',
        "help_languages": 'Mặc định theo ngôn ngữ hệ thống của Home Assistant.',
        "help_channel": 'Đổi bất cứ lúc nào. Staging trỏ tới Klar NLU (Staging).',
        "local": 'Khởi động động cơ kèm theo (chỉ HACS)',
        "remote": 'Dùng ứng dụng Klar NLU hoặc Docker',
        "stable": 'Stable (sản xuất)',
        "staging": 'Staging (ứng viên)',
        "system": 'Ngôn ngữ hệ thống',
        "all": 'Mọi ngôn ngữ',
        "normal": 'Bình thường',
        "casual": 'Thoải mái',
        "caring": 'Ân cần',
        "grumpy": 'Cáu kỉnh',
        "sarcastic": 'Châm biếm',
        "pirate": 'Hải tặc',
        "quiet_name": 'Xác nhận ngắn',
        "heard": 'Nghe gần nhất',
        "decision": 'Quyết định gần nhất',
        "speech": 'Trả lời gần nhất',
        "area": 'Nghe tại',
        "down_title": 'Động cơ Klar đã dừng',
        "down_desc": 'Tiến trình Klar kèm theo không chạy. Tải lại Klar NLU trong Cài đặt → Thiết bị và dịch vụ.',
    },
    "id": {
        "user_desc": 'Integrasi ini berbicara dengan Assist. Mesin terpisah menafsirkan ucapan: aplikasi Klar NLU, proses terbundel, atau Docker. Di Home Assistant OS pasang juga aplikasinya lalu pilih Gunakan aplikasi Klar NLU. Tanpa aplikasi, jalankan mesin terbundel. Jangan jalankan keduanya.',
        "mode": 'Mesin',
        "channel": 'Saluran rilis',
        "url": 'URL API Klar',
        "token": 'Token tulis',
        "invalid": 'URL harus http(s) tanpa nama pengguna.',
        "already": 'Klar NLU sudah diatur',
        "opt_desc": 'Suara, bahasa Assist, dan LLM ada di UI operator Klar (Pengaturan). Formulir ini hanya menghubungkan mesin: URL, token, dan saluran.',
        "personality": 'Kepribadian',
        "languages": 'Bahasa',
        "fallback": 'Agen percakapan untuk ngobrol',
        "refine_speech": 'Biarkan LLM merapikan balasan NLU',
        "refine_prompt": 'Prompt perapian',
        "assist_filter": 'Hanya kendalikan entitas yang terlihat Assist',
        "nlu_rag": 'NLU-RAG (opsional)',
        "quiet_ack": 'Konfirmasi singkat (lonceng)',
        "calendar_llm": 'Kirim pertanyaan kalender ke LLM',
        "help_personality": 'Ada di integrasi ini, bukan di aplikasi Klar.',
        "help_refine_speech": 'Klar tetap mengendalikan perangkat. LLM cadangan menulis ulang balasan.',
        "help_refine_prompt": 'Prompt sistem suara. Tanpa kendali perangkat, tanpa fakta baru, bahasa yang sama.',
        "help_token": 'Token yang sama dengan aplikasi Klar.',
        "help_assist": 'Nyala: hanya yang Assist boleh lihat. Mati: termasuk yang tersembunyi.',
        "help_rag": 'Default mati. Saat ngobrol hanya potongan yang cocok dikirim ke model cadangan.',
        "help_quiet": 'Untuk nyala/mati lampu sederhana, tidak berbicara, hanya bunyi singkat di satelit.',
        "help_calendar_llm": 'Default nonaktif. Aktif: Klar membaca kalender, LLM cadangan mengucapkan acara. Nonaktif: Klar mengucapkan daftar. Buat, hapus, pindah tetap di Klar.',
        "help_languages": 'Default mengikuti bahasa sistem Home Assistant.',
        "help_channel": 'Bisa kapan saja. Staging mengarah ke Klar NLU (Staging).',
        "local": 'Jalankan mesin terbundel (hanya HACS)',
        "remote": 'Gunakan aplikasi Klar NLU atau Docker',
        "stable": 'Stable (produksi)',
        "staging": 'Staging (kandidat)',
        "system": 'Bahasa sistem',
        "all": 'Semua bahasa',
        "normal": 'Biasa',
        "casual": 'Santai',
        "caring": 'Penyayang',
        "grumpy": 'Pemarah',
        "sarcastic": 'Sarkastis',
        "pirate": 'Bajak laut',
        "quiet_name": 'Konfirmasi singkat',
        "heard": 'Terakhir didengar',
        "decision": 'Keputusan terakhir',
        "speech": 'Balasan terakhir',
        "area": 'Didengar di',
        "down_title": 'Mesin Klar berhenti',
        "down_desc": 'Proses Klar terbundel tidak berjalan. Muat ulang Klar NLU di Pengaturan → Perangkat dan layanan.',
    },
    "ms": {
        "user_desc": 'Integrasi ini bercakap dengan Assist. Enjin berasingan mentafsir pertuturan: aplikasi Klar NLU, proses terbungkus atau Docker. Pada Home Assistant OS pasang juga aplikasi lalu pilih Guna aplikasi Klar NLU. Tanpa aplikasi, mulakan enjin terbungkus. Jangan jalankan kedua-duanya.',
        "mode": 'Enjin',
        "channel": 'Saluran keluaran',
        "url": 'URL API Klar',
        "token": 'Token tulis',
        "invalid": 'URL mestilah http(s) tanpa nama pengguna.',
        "already": 'Klar NLU sudah disediakan',
        "opt_desc": 'Suara, bahasa Assist dan LLM ada dalam UI pengendali Klar (Tetapan). Borang ini hanya menyambungkan enjin: URL, token dan saluran.',
        "personality": 'Personaliti',
        "languages": 'Bahasa',
        "fallback": 'Ejen perbualan untuk sembang',
        "refine_speech": 'Biarkan LLM merapikan jawapan NLU',
        "refine_prompt": 'Prom pemurnian',
        "assist_filter": 'Kawal hanya entiti yang terdedah kepada Assist',
        "nlu_rag": 'NLU-RAG (pilihan)',
        "quiet_ack": 'Pengesahan ringkas (loceng)',
        "calendar_llm": 'Hantar pertanyaan kalendar ke LLM',
        "help_personality": 'Ada dalam integrasi ini, bukan dalam aplikasi Klar.',
        "help_refine_speech": 'Klar masih mengawal peranti. LLM sandaran menulis semula jawapan.',
        "help_refine_prompt": 'Prom sistem suara. Tiada kawalan peranti, tiada fakta baharu, bahasa yang sama.',
        "help_token": 'Token yang sama dengan aplikasi Klar.',
        "help_assist": 'Hidup: hanya yang Assist boleh lihat. Mati: termasuk entiti tersembunyi.',
        "help_rag": 'Lalai mati. Semasa sembang hanya potongan yang sepadan dihantar ke model sandaran.',
        "help_quiet": 'Untuk hidup/mati lampu ringkas, tiada ayat, hanya bunyi pendek pada satelit.',
        "help_calendar_llm": 'Lalai dimatikan. Hidup: Klar baca kalendar, LLM sandaran sebut acara. Mati: Klar sebut senarai. Cipta, padam, pindah kekal di Klar.',
        "help_languages": 'Lalai mengikut bahasa sistem Home Assistant.',
        "help_channel": 'Boleh bila-bila masa. Staging menunjuk ke Klar NLU (Staging).',
        "local": 'Mulakan enjin terbungkus (HACS sahaja)',
        "remote": 'Guna aplikasi Klar NLU atau Docker',
        "stable": 'Stable (pengeluaran)',
        "staging": 'Staging (calon)',
        "system": 'Bahasa sistem',
        "all": 'Semua bahasa',
        "normal": 'Biasa',
        "casual": 'Santai',
        "caring": 'Prihatin',
        "grumpy": 'Merajuk',
        "sarcastic": 'Sarkastik',
        "pirate": 'Lanun',
        "quiet_name": 'Pengesahan ringkas',
        "heard": 'Terakhir didengar',
        "decision": 'Keputusan terakhir',
        "speech": 'Jawapan terakhir',
        "area": 'Didengar di',
        "down_title": 'Enjin Klar berhenti',
        "down_desc": 'Proses Klar terbungkus tidak berjalan. Muat semula Klar NLU dalam Tetapan → Peranti dan perkhidmatan.',
    },
}
