"""HA UI copy recovered for Central European Assist locales."""

from __future__ import annotations

MORE: dict[str, dict[str, str]] = {
    "ro": {
        "user_desc": 'Această integrare vorbește cu Assist. Un motor separat analizează vorbirea: aplicația Klar NLU, procesul inclus sau Docker. Pe Home Assistant OS instalați și aplicația, apoi alegeți Folosește aplicația Klar NLU. Fără aplicație porniți motorul inclus. Nu rulați ambele.',
        "mode": 'Motor',
        "channel": 'Canal de lansare',
        "url": 'URL API Klar',
        "token": 'Token de scriere',
        "invalid": 'URL-ul trebuie să fie http(s), fără utilizator.',
        "already": 'Klar NLU este deja configurat',
        "opt_desc": 'Vocea, limbile Assist și LLM-ul sunt în UI-ul operator Klar (Setări). Acest formular conectează doar motorul: URL, token și canal.',
        "personality": 'Personalitate',
        "languages": 'Limbi',
        "fallback": 'Agent de conversație pentru vorbărie',
        "refine_speech": 'Lasă LLM-ul să reformuleze răspunsurile NLU',
        "refine_prompt": 'Prompt de rafinare',
        "assist_filter": 'Controlează doar entitățile expuse către Assist',
        "nlu_rag": 'NLU-RAG (opțional)',
        "quiet_ack": 'Confirmare scurtă (clopoțel)',
        "calendar_llm": 'Trimite interogările de calendar la LLM',
        "help_personality": 'Este în această integrare, nu în aplicația Klar.',
        "help_refine_speech": 'Klar controlează în continuare dispozitivele. LLM-ul de rezervă reformulează răspunsul.',
        "help_refine_prompt": 'Promptul de sistem al vocii. Fără control de dispozitive, fără fapte noi, aceeași limbă.',
        "help_token": 'Același token ca în aplicația Klar.',
        "help_assist": 'Pornit: doar ce vede Assist. Oprit: și entități ascunse.',
        "help_rag": 'Dezactivat implicit. La conversație doar fragmentul recunoscut merge la modelul de rezervă.',
        "help_quiet": 'La aprindere/stingere simplă nu vorbește, doar un sunet scurt pe satelit.',
        "help_calendar_llm": 'Dezactivat implicit. Pornit: Klar citește calendarul, LLM-ul de rezervă spune evenimentele. Oprit: Klar spune lista. Crearea, ștergerea și mutarea rămân în Klar.',
        "help_languages": 'Implicit urmează limba sistemului Home Assistant.',
        "help_channel": 'Oricând. Staging indică Klar NLU (Staging).',
        "local": 'Pornește motorul inclus (doar HACS)',
        "remote": 'Folosește aplicația Klar NLU sau Docker',
        "stable": 'Stable (producție)',
        "staging": 'Staging (candidat)',
        "system": 'Limba sistemului',
        "all": 'Toate limbile',
        "normal": 'Normal',
        "casual": 'Dezinvolt',
        "caring": 'Grijuliu',
        "grumpy": 'Morocănos',
        "sarcastic": 'Sarcastic',
        "pirate": 'Pirat',
        "quiet_name": 'Confirmare scurtă',
        "heard": 'Ultima audire',
        "decision": 'Ultima decizie',
        "speech": 'Ultimul răspuns',
        "area": 'Auzit în',
        "down_title": 'Motorul Klar s-a oprit',
        "down_desc": 'Procesul Klar inclus nu rulează. Reîncărcați Klar NLU din Setări → Dispozitive și servicii.',
    },
    "hu": {
        "user_desc": 'Ez az integráció az Assisttel beszél. A beszédet külön motor elemzi: a Klar NLU alkalmazás, a csomagolt folyamat vagy Docker. Home Assistant OS-en telepítse az alkalmazást, és válassza a Klar NLU alkalmazás használata. Alkalmazás nélkül indítsa a csomagolt motort. Ne futtassa mindkettőt.',
        "mode": 'Motor',
        "channel": 'Kiadási csatorna',
        "url": 'Klar API URL',
        "token": 'Írási token',
        "invalid": 'Az URL http(s) legyen, felhasználónév nélkül.',
        "already": 'A Klar NLU már be van állítva',
        "opt_desc": 'A hang, az Assist nyelvei és az LLM a Klar operátori felületén vannak (Beállítások). Ez az űrlap csak a motort köti: URL, token és csatorna.',
        "personality": 'Személyiség',
        "languages": 'Nyelvek',
        "fallback": 'Csevegő beszélgetési ügynök',
        "refine_speech": 'Az LLM fogalmazza újra az NLU válaszokat',
        "refine_prompt": 'Finomító prompt',
        "assist_filter": 'Csak az Assistnek kitett entitások vezérlése',
        "nlu_rag": 'NLU-RAG (opcionális)',
        "quiet_ack": 'Rövid megerősítés (csengő)',
        "calendar_llm": 'Naptárlekérdezések küldése az LLM-nek',
        "help_personality": 'Ebben az integrációban van, nem a Klar alkalmazásban.',
        "help_refine_speech": 'A Klar továbbra is vezérli az eszközöket. A tartalék LLM átírja a választ.',
        "help_refine_prompt": 'A hang rendszerpromptja. Nincs eszközvezérlés, nincs új tény, ugyanaz a nyelv.',
        "help_token": 'Ugyanaz a token, mint a Klar alkalmazásban.',
        "help_assist": 'Be: csak amit az Assist lát. Ki: rejtett entitások is.',
        "help_rag": 'Alapból ki. Csevegéskor csak az illeszkedő szelet megy a tartalék modellnek.',
        "help_quiet": 'Egyszerű lámpa ki/be esetén nincs beszéd, csak rövid hang a műholdon.',
        "help_calendar_llm": 'Alapból ki. Be: a Klar olvassa a naptárt, a tartalék LLM mondja az eseményeket. Ki: a Klar mondja a listát. Létrehozás, törlés, áthelyezés a Klarnál marad.',
        "help_languages": 'Alapértelmezés a Home Assistant rendszer nyelve.',
        "help_channel": 'Bármikor. A Staging a Klar NLU (Staging) felé mutat.',
        "local": 'Csomagolt motor indítása (csak HACS)',
        "remote": 'Klar NLU alkalmazás vagy Docker használata',
        "stable": 'Stable (éles)',
        "staging": 'Staging (jelölt)',
        "system": 'Rendszer nyelve',
        "all": 'Minden nyelv',
        "normal": 'Normál',
        "casual": 'Laza',
        "caring": 'Gondoskodó',
        "grumpy": 'Mogorva',
        "sarcastic": 'Szarkasztikus',
        "pirate": 'Kalóz',
        "quiet_name": 'Rövid megerősítés',
        "heard": 'Utoljára hallott',
        "decision": 'Utolsó döntés',
        "speech": 'Utolsó válasz',
        "area": 'Hallva itt',
        "down_title": 'A Klar motor leállt',
        "down_desc": 'A csomagolt Klar folyamat nem fut. Töltse újra a Klar NLU-t: Beállítások → Eszközök és szolgáltatások.',
    },
    "hr": {
        "user_desc": 'Ova integracija razgovara s Assistom. Zaseban motor tumači govor: aplikacija Klar NLU, uključeni proces ili Docker. Na Home Assistant OS instalirajte i aplikaciju pa odaberite Koristi aplikaciju Klar NLU. Bez aplikacije pokrenite uključeni motor. Ne pokrećite oboje.',
        "mode": 'Motor',
        "channel": 'Kanal izdanja',
        "url": 'URL Klar API-ja',
        "token": 'Token za pisanje',
        "invalid": 'URL mora biti http(s), bez korisničkog imena.',
        "already": 'Klar NLU je već postavljen',
        "opt_desc": 'Glas, jezici Assista i LLM su u Klar operator UI-ju (Postavke). Ovaj obrazac samo povezuje motor: URL, token i kanal.',
        "personality": 'Osobnost',
        "languages": 'Jezici',
        "fallback": 'Razgovorni agent za čavrljanje',
        "refine_speech": 'Neka LLM preformulira NLU odgovore',
        "refine_prompt": 'Prompt za doradu',
        "assist_filter": 'Upravljaj samo entitetima izloženima Assistu',
        "nlu_rag": 'NLU-RAG (neobavezno)',
        "quiet_ack": 'Kratka potvrda (zvončić)',
        "calendar_llm": 'Šalji upite kalendara LLM-u',
        "help_personality": 'U ovoj integraciji, ne u aplikaciji Klar.',
        "help_refine_speech": 'Klar i dalje upravlja uređajima. Rezervni LLM prepisuje odgovor.',
        "help_refine_prompt": 'Sistemski prompt glasa. Bez upravljanja uređajima, bez novih činjenica, isti jezik.',
        "help_token": 'Isti token kao u aplikaciji Klar.',
        "help_assist": 'Uključeno: samo što Assist vidi. Isključeno: i skriveni entiteti.',
        "help_rag": 'Zadano isključeno. U razgovoru samo prepoznati odsječak ide rezervnom modelu.',
        "help_quiet": 'Kod jednostavnog paljenja/gašenja svjetla nema govora, samo kratki zvuk na satelitu.',
        "help_calendar_llm": 'Po defaultu isključeno. Uključeno: Klar čita kalendar, pričuvni LLM izgovara događaje. Isključeno: Klar izgovara popis. Stvaranje, brisanje i premještanje ostaju u Klaru.',
        "help_languages": 'Zadano prati jezik sustava Home Assistant.',
        "help_channel": 'Bilo kada. Staging pokazuje na Klar NLU (Staging).',
        "local": 'Pokreni uključeni motor (samo HACS)',
        "remote": 'Koristi aplikaciju Klar NLU ili Docker',
        "stable": 'Stable (produkcija)',
        "staging": 'Staging (kandidat)',
        "system": 'Jezik sustava',
        "all": 'Svi jezici',
        "normal": 'Normalno',
        "casual": 'Opusteno',
        "caring": 'Brižno',
        "grumpy": 'Mrzovoljno',
        "sarcastic": 'Sarkastično',
        "pirate": 'Pirat',
        "quiet_name": 'Kratka potvrda',
        "heard": 'Zadnje čuto',
        "decision": 'Zadnja odluka',
        "speech": 'Zadnji odgovor',
        "area": 'Čuto u',
        "down_title": 'Klar motor je stao',
        "down_desc": 'Uključeni Klar proces ne radi. Ponovno učitajte Klar NLU u Postavke → Uređaji i usluge.',
    },
    "sl": {
        "user_desc": 'Ta integracija se pogovarja z Assistom. Ločen pogon razčleni govor: aplikacija Klar NLU, priložen proces ali Docker. Na Home Assistant OS namestite tudi aplikacijo in izberite Uporabi aplikacijo Klar NLU. Brez aplikacije zaženite priložen pogon. Ne zaganjajte obojega.',
        "mode": 'Pogon',
        "channel": 'Kanal izdaje',
        "url": 'URL Klar API',
        "token": 'Žeton za pisanje',
        "invalid": 'URL mora biti http(s) brez uporabniškega imena.',
        "already": 'Klar NLU je že nastavljen',
        "opt_desc": 'Glas, jeziki Assist in LLM so v Klarjevem operatorskem vmesniku (Nastavitve). Ta obrazec samo poveže motor: URL, žeton in kanal.',
        "personality": 'Osebnost',
        "languages": 'Jeziki',
        "fallback": 'Pogovorni agent za klepet',
        "refine_speech": 'Naj LLM preoblikuje odgovore NLU',
        "refine_prompt": 'Poziv za izboljšavo',
        "assist_filter": 'Upravljaj samo entitete, izpostavljene Assistu',
        "nlu_rag": 'NLU-RAG (izbirno)',
        "quiet_ack": 'Kratka potrditev (zvonček)',
        "calendar_llm": 'Pošlji koledarska vprašanja LLM-ju',
        "help_personality": 'Je v tej integraciji, ne v aplikaciji Klar.',
        "help_refine_speech": 'Klar še vedno upravlja naprave. Rezervni LLM prepiše odgovor.',
        "help_refine_prompt": 'Sistemski poziv glasu. Brez upravljanja naprav, brez novih dejstev, isti jezik.',
        "help_token": 'Isti žeton kot v aplikaciji Klar.',
        "help_assist": 'Vklopljeno: samo kar vidi Assist. Izklopljeno: tudi skrite entitete.',
        "help_rag": 'Privzeto izklopljeno. Pri klepetu gre rezervnemu modelu samo ujemajoči se del.',
        "help_quiet": 'Pri preprostem vklopu/izklopu luči ni govora, le kratek zvok na satelitu.',
        "help_calendar_llm": 'Privzeto izklopljeno. Vklopljeno: Klar prebere koledar, nadomestni LLM pove dogodke. Izklopljeno: Klar pove seznam. Ustvarjanje, brisanje in premikanje ostanejo pri Klarju.',
        "help_languages": 'Privzeto sledi jeziku sistema Home Assistant.',
        "help_channel": 'Kadarkoli. Staging kaže na Klar NLU (Staging).',
        "local": 'Zaženi priložen pogon (samo HACS)',
        "remote": 'Uporabi aplikacijo Klar NLU ali Docker',
        "stable": 'Stable (produkcija)',
        "staging": 'Staging (kandidat)',
        "system": 'Jezik sistema',
        "all": 'Vsi jeziki',
        "normal": 'Običajno',
        "casual": 'Sproščeno',
        "caring": 'Skrbno',
        "grumpy": 'Godrnjavo',
        "sarcastic": 'Sarkastično',
        "pirate": 'Pirat',
        "quiet_name": 'Kratka potrditev',
        "heard": 'Nazadnje slišano',
        "decision": 'Zadnja odločitev',
        "speech": 'Zadnji odgovor',
        "area": 'Slišano v',
        "down_title": 'Pogon Klar se je ustavil',
        "down_desc": 'Priložen proces Klar ne teče. Ponovno naložite Klar NLU v Nastavitve → Naprave in storitve.',
    },
    "sk": {
        "user_desc": 'Táto integrácia hovorí s Assistom. Samostatný engine rozoberá reč: aplikácia Klar NLU, priložený proces alebo Docker. Na Home Assistant OS nainštalujte aj aplikáciu a zvoľte Použiť aplikáciu Klar NLU. Bez aplikácie spustite priložený engine. Nespúšťajte oboje.',
        "mode": 'Engine',
        "channel": 'Kanál vydania',
        "url": 'URL Klar API',
        "token": 'Zapisovací token',
        "invalid": 'URL musí byť http(s) bez mena používateľa.',
        "already": 'Klar NLU je už nastavené',
        "opt_desc": 'Hlas, jazyky Assist a LLM sú v operátorskom UI Klar (Nastavenia). Tento formulár len pripája engine: URL, token a kanál.',
        "personality": 'Osobnosť',
        "languages": 'Jazyky',
        "fallback": 'Konverzačný agent na pokec',
        "refine_speech": 'Nech LLM preformuluje odpovede NLU',
        "refine_prompt": 'Výzva na vylepšenie',
        "assist_filter": 'Ovládať len entity vystavené Assistu',
        "nlu_rag": 'NLU-RAG (voliteľné)',
        "quiet_ack": 'Krátke potvrdenie (zvonček)',
        "calendar_llm": 'Posielať dopyty na kalendár do LLM',
        "help_personality": 'Je v tejto integrácii, nie v aplikácii Klar.',
        "help_refine_speech": 'Klar naďalej ovláda zariadenia. Záložné LLM prepíše odpoveď.',
        "help_refine_prompt": 'Systémová výzva hlasu. Bez ovládania zariadení, bez nových faktov, rovnaký jazyk.',
        "help_token": 'Rovnaký token ako v aplikácii Klar.',
        "help_assist": 'Zapnuté: len to, čo vidí Assist. Vypnuté: aj skryté entity.',
        "help_rag": 'Predvolene vypnuté. Pri chate ide záložnému modelu len zhodný úsek.',
        "help_quiet": 'Pri jednoduchom zapnutí/vypnutí svetla bez vety, len krátky zvuk na satelite.',
        "help_calendar_llm": 'Predvolene vypnuté. Zapnuté: Klar prečíta kalendár, záložné LLM povie udalosti. Vypnuté: Klar povie zoznam. Vytvorenie, zmazanie a presun zostanú v Klar.',
        "help_languages": 'Predvolene nasleduje jazyk systému Home Assistant.',
        "help_channel": 'Kedykoľvek. Staging ukazuje na Klar NLU (Staging).',
        "local": 'Spustiť priložený engine (iba HACS)',
        "remote": 'Použiť aplikáciu Klar NLU alebo Docker',
        "stable": 'Stable (produkcia)',
        "staging": 'Staging (kandidát)',
        "system": 'Jazyk systému',
        "all": 'Všetky jazyky',
        "normal": 'Bežná',
        "casual": 'Uvoľnená',
        "caring": 'Starostlivá',
        "grumpy": 'Mrzutá',
        "sarcastic": 'Sarkastická',
        "pirate": 'Pirát',
        "quiet_name": 'Krátke potvrdenie',
        "heard": 'Naposledy počuté',
        "decision": 'Posledné rozhodnutie',
        "speech": 'Posledná odpoveď',
        "area": 'Počuté v',
        "down_title": 'Klar engine zastavený',
        "down_desc": 'Priložený proces Klar nebeží. Znova načítajte Klar NLU v Nastavenia → Zariadenia a služby.',
    },
    "bg": {
        "user_desc": 'Тази интеграция говори с Assist. Отделен двигател разпознава речта: приложението Klar NLU, включеният процес или Docker. На Home Assistant OS инсталирайте и приложението и изберете Използвай приложението Klar NLU. Без приложение стартирайте включения двигател. Не пускайте и двете.',
        "mode": 'Двигател',
        "channel": 'Канал за издание',
        "url": 'URL на Klar API',
        "token": 'Токен за запис',
        "invalid": 'URL трябва да е http(s) без потребител.',
        "already": 'Klar NLU вече е настроено',
        "opt_desc": 'Гласът, езиците на Assist и LLM са в операторския интерфейс на Klar (Настройки). Този формуляр свързва само двигателя: URL, токен и канал.',
        "personality": 'Личност',
        "languages": 'Езици',
        "fallback": 'Разговорен агент за бъбрене',
        "refine_speech": 'LLM да преформулира отговорите на NLU',
        "refine_prompt": 'Подсказка за дооформяне',
        "assist_filter": 'Управлявай само обекти, показани на Assist',
        "nlu_rag": 'NLU-RAG (по избор)',
        "quiet_ack": 'Кратко потвърждение (звънец)',
        "calendar_llm": 'Изпращай календарните запитвания към LLM',
        "help_personality": 'В тази интеграция, не в приложението Klar.',
        "help_refine_speech": 'Klar продължава да управлява устройствата. Резервният LLM пренаписва отговора.',
        "help_refine_prompt": 'Системна подсказка за гласа. Без управление на устройства, без нови факти, същият език.',
        "help_token": 'Същият токен като в приложението Klar.',
        "help_assist": 'Вкл.: само каквото вижда Assist. Изкл.: и скрити обекти.',
        "help_rag": 'По подразбиране изкл. При разговор към резервния модел отива само разпознатият отрязък.',
        "help_quiet": 'При просто вкл./изкл. на лампа няма говор, само кратък звук на сателита.',
        "help_calendar_llm": 'По подразбиране изключено. Включено: Klar чете календара, резервният LLM казва събитията. Изключено: Klar казва списъка. Създаване, изтриване и преместване остават в Klar.',
        "help_languages": 'По подразбиране следва езика на системата Home Assistant.',
        "help_channel": 'По всяко време. Staging сочи към Klar NLU (Staging).',
        "local": 'Стартирай включения двигател (само HACS)',
        "remote": 'Използвай приложението Klar NLU или Docker',
        "stable": 'Stable (продукция)',
        "staging": 'Staging (кандидат)',
        "system": 'Език на системата',
        "all": 'Всички езици',
        "normal": 'Обикновена',
        "casual": 'Непринудена',
        "caring": 'Грижовна',
        "grumpy": 'Сърдита',
        "sarcastic": 'Саркастична',
        "pirate": 'Пират',
        "quiet_name": 'Кратко потвърждение',
        "heard": 'Последно чуто',
        "decision": 'Последно решение',
        "speech": 'Последен отговор',
        "area": 'Чуто в',
        "down_title": 'Двигателят Klar е спрял',
        "down_desc": 'Включеният процес Klar не работи. Презаредете Klar NLU в Настройки → Устройства и услуги.',
    },
    "el": {
        "user_desc": 'Αυτή η ενσωμάτωση μιλά με το Assist. Ξεχωριστή μηχανή αναλύει την ομιλία: εφαρμογή Klar NLU, ενσωματωμένη διεργασία ή Docker. Στο Home Assistant OS εγκαταστήστε και την εφαρμογή και επιλέξτε Χρήση εφαρμογής Klar NLU. Χωρίς εφαρμογή ξεκινήστε την ενσωματωμένη μηχανή. Μην τρέχετε και τα δύο.',
        "mode": 'Μηχανή',
        "channel": 'Κανάλι έκδοσης',
        "url": 'URL API Klar',
        "token": 'Διακριτικό εγγραφής',
        "invalid": 'Το URL πρέπει να είναι http(s) χωρίς όνομα χρήστη.',
        "already": 'Το Klar NLU είναι ήδη ρυθμισμένο',
        "opt_desc": 'Η φωνή, οι γλώσσες του Assist και το LLM βρίσκονται στο UI χειριστή του Klar (Ρυθμίσεις). Αυτή η φόρμα συνδέει μόνο τη μηχανή: URL, διακριτικό και κανάλι.',
        "personality": 'Προσωπικότητα',
        "languages": 'Γλώσσες',
        "fallback": 'Πράκτορας συνομιλίας για κουβέντα',
        "refine_speech": 'Το LLM να ξαναγράψει τις απαντήσεις NLU',
        "refine_prompt": 'Προτροπή βελτίωσης',
        "assist_filter": 'Έλεγχος μόνο οντοτήτων εκτεθειμένων στο Assist',
        "nlu_rag": 'NLU-RAG (προαιρετικό)',
        "quiet_ack": 'Σύντομη επιβεβαίωση (κουδούνι)',
        "calendar_llm": 'Αποστολή ερωτημάτων ημερολογίου στο LLM',
        "help_personality": 'Είναι σε αυτή την ενσωμάτωση, όχι στην εφαρμογή Klar.',
        "help_refine_speech": 'Το Klar συνεχίζει να ελέγχει συσκευές. Το εφεδρικό LLM ξαναγράφει την απάντηση.',
        "help_refine_prompt": 'Προτροπή συστήματος φωνής. Χωρίς έλεγχο συσκευών, χωρίς νέα γεγονότα, ίδια γλώσσα.',
        "help_token": 'Το ίδιο διακριτικό με την εφαρμογή Klar.',
        "help_assist": 'Ενεργό: μόνο όσα βλέπει το Assist. Ανενεργό: και κρυφές οντότητες.',
        "help_rag": 'Απενεργοποιημένο από προεπιλογή. Στη συνομιλία μόνο το αναγνωρισμένο απόσπασμα πάει στο εφεδρικό μοντέλο.',
        "help_quiet": 'Σε απλό άναμμα/σβήσιμο φωτός χωρίς ομιλία, μόνο σύντομο ήχο στον δορυφόρο.',
        "help_calendar_llm": 'Ανενεργό από προεπιλογή. Ενεργό: το Klar διαβάζει το ημερολόγιο και το εφεδρικό LLM λέει τα γεγονότα. Ανενεργό: το Klar λέει τη λίστα. Δημιουργία, διαγραφή και μετακίνηση μένουν στο Klar.',
        "help_languages": 'Η προεπιλογή ακολουθεί τη γλώσσα συστήματος του Home Assistant.',
        "help_channel": 'Οποτεδήποτε. Το Staging δείχνει στο Klar NLU (Staging).',
        "local": 'Εκκίνηση ενσωματωμένης μηχανής (μόνο HACS)',
        "remote": 'Χρήση εφαρμογής Klar NLU ή Docker',
        "stable": 'Stable (παραγωγή)',
        "staging": 'Staging (υποψήφιο)',
        "system": 'Γλώσσα συστήματος',
        "all": 'Όλες οι γλώσσες',
        "normal": 'Κανονική',
        "casual": 'Χαλαρή',
        "caring": 'Φροντιστική',
        "grumpy": 'Γκρινιάρικη',
        "sarcastic": 'Σαρκαστική',
        "pirate": 'Πειρατής',
        "quiet_name": 'Σύντομη επιβεβαίωση',
        "heard": 'Τελευταία ακρόαση',
        "decision": 'Τελευταία απόφαση',
        "speech": 'Τελευταία απάντηση',
        "area": 'Ακούστηκε σε',
        "down_title": 'Η μηχανή Klar σταμάτησε',
        "down_desc": 'Η ενσωματωμένη διεργασία Klar δεν τρέχει. Επαναφορτώστε το Klar NLU στις Ρυθμίσεις → Συσκευές και υπηρεσίες.',
    },
    "sr": {
        "user_desc": 'Ова интеграција разговара са Assist-ом. Посебан мотор тумачи говор: апликација Klar NLU, укључени процес или Docker. На Home Assistant OS инсталирајте и апликацију па изаберите Користи апликацију Klar NLU. Без апликације покрените укључени мотор. Не покрећите оба.',
        "mode": 'Мотор',
        "channel": 'Канал издања',
        "url": 'URL Klar API-ја',
        "token": 'Токен за упис',
        "invalid": 'URL мора бити http(s), без корисничког имена.',
        "already": 'Klar NLU је већ подешен',
        "opt_desc": 'Глас, језици Assist-а и LLM су у Klar операторском UI-ју (Подешавања). Овај образац само повезује мотор: URL, токен и канал.',
        "personality": 'Личност',
        "languages": 'Језици',
        "fallback": 'Разговорни агент за ћаскање',
        "refine_speech": 'Нека LLM преформулише NLU одговоре',
        "refine_prompt": 'Упит за дораду',
        "assist_filter": 'Управљај само ентитетима изложеним Assist-у',
        "nlu_rag": 'NLU-RAG (опционо)',
        "quiet_ack": 'Кратка потврда (звонце)',
        "calendar_llm": 'Шаљи упите календара LLM-у',
        "help_personality": 'У овој интеграцији, не у апликацији Klar.',
        "help_refine_speech": 'Klar и даље управља уређајима. Резервни LLM преписује одговор.',
        "help_refine_prompt": 'Системски упит гласа. Без управљања уређајима, без нових чињеница, исти језик.',
        "help_token": 'Исти токен као у апликацији Klar.',
        "help_assist": 'Укључено: само што Assist види. Искључено: и скривени ентитети.',
        "help_rag": 'Подразумевано искључено. У разговору само препознати одсечак иде резервном моделу.',
        "help_quiet": 'Код простог укључивања/искључивања светла нема говора, само кратак звук на сателиту.',
        "help_calendar_llm": 'Подразумевано искључено. Укључено: Клар чита календар, резервни LLM изговара догађаје. Искључено: Клар изговара списак. Прављење, брисање и премештање остају у Клару.',
        "help_languages": 'Подразумевано прати језик система Home Assistant.',
        "help_channel": 'Било када. Staging показује на Klar NLU (Staging).',
        "local": 'Покрени укључени мотор (само HACS)',
        "remote": 'Користи апликацију Klar NLU или Docker',
        "stable": 'Stable (продукција)',
        "staging": 'Staging (кандидат)',
        "system": 'Језик система',
        "all": 'Сви језици',
        "normal": 'Обично',
        "casual": 'Опуштено',
        "caring": 'Брижно',
        "grumpy": 'Мрзовољно',
        "sarcastic": 'Саркастично',
        "pirate": 'Пират',
        "quiet_name": 'Кратка потврда',
        "heard": 'Последње чуто',
        "decision": 'Последња одлука',
        "speech": 'Последњи одговор',
        "area": 'Чуто у',
        "down_title": 'Klar мотор је стао',
        "down_desc": 'Укључени Klar процес не ради. Поново учитајте Klar NLU у Подешавања → Уређаји и услуге.',
    },
    "sr-Latn": {
        "user_desc": 'Ova integracija razgovara sa Assist-om. Poseban motor tumači govor: aplikacija Klar NLU, uključeni proces ili Docker. Na Home Assistant OS instalirajte i aplikaciju pa izaberite Koristi aplikaciju Klar NLU. Bez aplikacije pokrenite uključeni motor. Ne pokrećite oba.',
        "mode": 'Motor',
        "channel": 'Kanal izdanja',
        "url": 'URL Klar API-ja',
        "token": 'Token za upis',
        "invalid": 'URL mora biti http(s), bez korisničkog imena.',
        "already": 'Klar NLU je već podešen',
        "opt_desc": 'Glas, jezici Assist-a i LLM su u Klar operatorskom UI-ju (Podešavanja). Ovaj obrazac samo povezuje motor: URL, token i kanal.',
        "personality": 'Ličnost',
        "languages": 'Jezici',
        "fallback": 'Razgovorni agent za ćaskanje',
        "refine_speech": 'Neka LLM preformuliše NLU odgovore',
        "refine_prompt": 'Upit za doradu',
        "assist_filter": 'Upravljaj samo entitetima izloženim Assist-u',
        "nlu_rag": 'NLU-RAG (opciono)',
        "quiet_ack": 'Kratka potvrda (zvonce)',
        "calendar_llm": 'Šalji upite kalendara LLM-u',
        "help_personality": 'U ovoj integraciji, ne u aplikaciji Klar.',
        "help_refine_speech": 'Klar i dalje upravlja uređajima. Rezervni LLM prepisuje odgovor.',
        "help_refine_prompt": 'Sistemski upit glasa. Bez upravljanja uređajima, bez novih činjenica, isti jezik.',
        "help_token": 'Isti token kao u aplikaciji Klar.',
        "help_assist": 'Uključeno: samo što Assist vidi. Isključeno: i skriveni entiteti.',
        "help_rag": 'Podrazumevano isključeno. U razgovoru samo prepoznati odsečak ide rezervnom modelu.',
        "help_quiet": 'Kod prostog uključivanja/isključivanja svetla nema govora, samo kratak zvuk na satelitu.',
        "help_calendar_llm": 'Podrazumevano isključeno. Uključeno: Klar čita kalendar, rezervni LLM izgovara događaje. Isključeno: Klar izgovara spisak. Pravljenje, brisanje i premeštanje ostaju u Klaru.',
        "help_languages": 'Podrazumevano prati jezik sistema Home Assistant.',
        "help_channel": 'Bilo kada. Staging pokazuje na Klar NLU (Staging).',
        "local": 'Pokreni uključeni motor (samo HACS)',
        "remote": 'Koristi aplikaciju Klar NLU ili Docker',
        "stable": 'Stable (produkcija)',
        "staging": 'Staging (kandidat)',
        "system": 'Jezik sistema',
        "all": 'Svi jezici',
        "normal": 'Obično',
        "casual": 'Opušteno',
        "caring": 'Brižno',
        "grumpy": 'Mrzovoljno',
        "sarcastic": 'Sarkastično',
        "pirate": 'Pirat',
        "quiet_name": 'Kratka potvrda',
        "heard": 'Poslednje čuto',
        "decision": 'Poslednja odluka',
        "speech": 'Poslednji odgovor',
        "area": 'Čuto u',
        "down_title": 'Klar motor je stao',
        "down_desc": 'Uključeni Klar proces ne radi. Ponovo učitajte Klar NLU u Podešavanja → Uređaji i usluge.',
    },
    "uk": {
        "user_desc": 'Ця інтеграція розмовляє з Assist. Окремий рушій розбирає мовлення: застосунок Klar NLU, вбудований процес або Docker. На Home Assistant OS встановіть також застосунок і виберіть Використовувати застосунок Klar NLU. Без застосунку запустіть вбудований рушій. Не запускайте обидва.',
        "mode": 'Рушій',
        "channel": 'Канал випуску',
        "url": 'URL API Klar',
        "token": 'Токен запису',
        "invalid": 'URL має бути http(s) без імені користувача.',
        "already": 'Klar NLU уже налаштовано',
        "opt_desc": 'Голос, мови Assist і LLM у операторському інтерфейсі Klar (Налаштування). Ця форма лише підключає рушій: URL, токен і канал.',
        "personality": 'Особистість',
        "languages": 'Мови',
        "fallback": 'Розмовний агент для балачок',
        "refine_speech": 'Нехай LLM переформулює відповіді NLU',
        "refine_prompt": 'Підказка уточнення',
        "assist_filter": 'Керувати лише сутностями, відкритими для Assist',
        "nlu_rag": 'NLU-RAG (необов’язково)',
        "quiet_ack": 'Коротке підтвердження (дзвінок)',
        "calendar_llm": 'Надсилати запити календаря до LLM',
        "help_personality": 'У цій інтеграції, не в застосунку Klar.',
        "help_refine_speech": 'Klar і далі керує пристроями. Резервна LLM переписує відповідь.',
        "help_refine_prompt": 'Системна підказка голосу. Без керування пристроями, без нових фактів, та сама мова.',
        "help_token": 'Той самий токен, що в застосунку Klar.',
        "help_assist": 'Увімкнено: лише те, що бачить Assist. Вимкнено: також приховані сутності.',
        "help_rag": 'Типово вимкнено. У розмові до резервної моделі йде лише розпізнаний фрагмент.',
        "help_quiet": 'При простому вмиканні/вимиканні світла без фрази, лише короткий звук на супутнику.',
        "help_calendar_llm": 'Типово вимкнено. Увімкнено: Klar читає календар, резервна LLM озвучує події. Вимкнено: Klar озвучує список. Створення, видалення й переміщення лишаються в Klar.',
        "help_languages": 'Типово відповідає мові системи Home Assistant.',
        "help_channel": 'Будь-коли. Staging вказує на Klar NLU (Staging).',
        "local": 'Запустити вбудований рушій (лише HACS)',
        "remote": 'Використовувати застосунок Klar NLU або Docker',
        "stable": 'Stable (продукція)',
        "staging": 'Staging (кандидат)',
        "system": 'Мова системи',
        "all": 'Усі мови',
        "normal": 'Звичайна',
        "casual": 'Невимушена',
        "caring": 'Турботлива',
        "grumpy": 'Бурчлива',
        "sarcastic": 'Саркастична',
        "pirate": 'Пірат',
        "quiet_name": 'Коротке підтвердження',
        "heard": 'Останнє почуте',
        "decision": 'Останнє рішення',
        "speech": 'Остання відповідь',
        "area": 'Почуто в',
        "down_title": 'Рушій Klar зупинено',
        "down_desc": 'Вбудований процес Klar не запущено. Перезавантажте Klar NLU у Налаштування → Пристрої та служби.',
    },
}
