"""HA UI copy recovered for West European Assist locales."""

from __future__ import annotations

WEST: dict[str, dict[str, str]] = {
    "cy": {
        "user_desc": 'Mae’r integreiddiad hwn yn siarad ag Assist. Peiriant ar wahân sy’n dadansoddi lleferydd: ap Klar NLU, y broses ynghlwm, neu Docker. Ar Home Assistant OS gosodwch yr ap hefyd a dewiswch Defnyddio ap Klar NLU. Heb yr ap, cychwynnwch y peiriant ynghlwm. Peidiwch â rhedeg y ddau.',
        "mode": 'Peiriant',
        "channel": 'Sianel rhyddhau',
        "url": 'URL API Klar',
        "token": 'Tocyn ysgrifennu',
        "invalid": 'Rhaid i’r URL fod yn http(s) heb enw defnyddiwr.',
        "already": 'Mae Klar NLU eisoes wedi’i osod',
        "opt_desc": 'Mae’r llais, ieithoedd Assist, a’r LLM yn UI gweithredwr Klar (Gosodiadau). Dim ond cysylltu’r peiriant mae’r ffurflen hon: URL, tocyn a sianel.',
        "personality": 'Personoliaeth',
        "languages": 'Ieithoedd',
        "fallback": 'Asiant sgwrs ar gyfer siarad hamddenol',
        "refine_speech": 'Gadael i’r LLM ailysgrifennu atebion NLU',
        "refine_prompt": 'Anogwr mireinio',
        "assist_filter": 'Rheoli dim ond endidau sy’n weladwy i Assist',
        "nlu_rag": 'NLU-RAG (dewisol)',
        "quiet_ack": 'Cadarnhad byr (cloch)',
        "calendar_llm": 'Anfon ymholiadau calendr at yr LLM',
        "help_personality": 'Yn yr integreiddiad hwn, nid yn ap Klar.',
        "help_refine_speech": 'Mae Klar yn dal i reoli dyfeisiau. Mae’r LLM wrth gefn yn ailysgrifennu’r ateb.',
        "help_refine_prompt": 'Anogwr system y llais. Dim rheoli dyfais, dim ffeithiau newydd, yr un iaith.',
        "help_token": 'Yr un tocyn ag yn ap Klar.',
        "help_assist": 'Ymlaen: dim ond beth mae Assist yn ei weld. I ffwrdd: endidau cudd hefyd.',
        "help_rag": 'I ffwrdd yn ddiofyn. Mewn sgwrs dim ond y darn sy’n cyfateb sy’n mynd at y model wrth gefn.',
        "help_quiet": 'Ar oleuadau syml ymlaen/i ffwrdd, dim brawddeg, dim ond sain fer ar y lloeren.',
        "help_calendar_llm": 'I ffwrdd yn ddiofyn. Ymlaen: Mae Klar yn darllen y calendr, y LLM wrth gefn sy\'n dweud y digwyddiadau. I ffwrdd: Klar sy\'n dweud y rhestr. Creu, dileu a symud yn aros gyda Klar.',
        "help_languages": 'Yn ddiofyn, iaith system Home Assistant.',
        "help_channel": 'Unrhyw bryd. Mae Staging yn pwyntio at Klar NLU (Staging).',
        "local": 'Cychwyn y peiriant ynghlwm (HACS yn unig)',
        "remote": 'Defnyddio ap Klar NLU neu Docker',
        "stable": 'Stable (cynhyrchu)',
        "staging": 'Staging (ymgeisydd)',
        "system": 'Iaith y system',
        "all": 'Pob iaith',
        "normal": 'Arferol',
        "casual": 'Hamddenol',
        "caring": 'Gofalgar',
        "grumpy": 'Swnllyd',
        "sarcastic": 'Sarcastig',
        "pirate": 'Môr-leidr',
        "quiet_name": 'Cadarnhad byr',
        "heard": 'Clywyd ddiwethaf',
        "decision": 'Penderfyniad diwethaf',
        "speech": 'Ateb diwethaf',
        "area": 'Clywyd yn',
        "down_title": 'Peiriant Klar wedi stopio',
        "down_desc": 'Nid yw proses Klar ynghlwm yn rhedeg. Ail-lwythwch Klar NLU yn Gosodiadau → Dyfeisiau a gwasanaethau.',
    },
    "et": {
        "user_desc": 'See integratsioon räägib Assistiga. Eraldi mootor parsib kõne: Klar NLU rakendus, kaasasolev protsess või Docker. Home Assistant OS-is paigalda ka rakendus ja vali Kasuta Klar NLU rakendust. Ilma rakenduseta käivita kaasasolev mootor. Ära jooksuta mõlemat.',
        "mode": 'Mootor',
        "channel": 'Väljalaskekanal',
        "url": 'Klar API URL',
        "token": 'Kirjutamistõend',
        "invalid": 'URL peab olema http(s) ilma kasutajanimega.',
        "already": 'Klar NLU on juba seadistatud',
        "opt_desc": 'Hääl, Assisti keeled ja LLM on Klari operaatori UI-s (Seaded). See vorm ühendab ainult mootori: URL, token ja kanal.',
        "personality": 'Isiksus',
        "languages": 'Keeled',
        "fallback": 'Vestlusagent vestluseks',
        "refine_speech": 'Las LLM sõnastab NLU vastused ümber',
        "refine_prompt": 'Viimistlusviip',
        "assist_filter": 'Juhi ainult Assistile nähtavaid olemeid',
        "nlu_rag": 'NLU-RAG (valikuline)',
        "quiet_ack": 'Lühike kinnitus (kelluke)',
        "calendar_llm": 'Saada kalendripäringud LLM-ile',
        "help_personality": 'Selles integratsioonis, mitte Klar rakenduses.',
        "help_refine_speech": 'Klar juhib endiselt seadmeid. Varumudel LLM kirjutab vastuse ümber.',
        "help_refine_prompt": 'Hääle süsteemiviip. Ilma seadmejuhtimiseta, ilma uute faktideta, sama keel.',
        "help_token": 'Sama tõend mis Klar rakenduses.',
        "help_assist": 'Sees: ainult see, mida Assist näeb. Väljas: ka peidetud olemid.',
        "help_rag": 'Vaikimisi väljas. Vestluses läheb varumudelile ainult vastav lõik.',
        "help_quiet": 'Lihtsa tule sisse/välja korral ei räägi, ainult lühike heli satelliidil.',
        "help_calendar_llm": 'Vaikimisi väljas. Sees: Klar loeb kalendrit, varumudel ütleb sündmused. Väljas: Klar ütleb loendi ise. Loomine, kustutamine ja teisaldamine jäävad Klari juurde.',
        "help_languages": 'Vaikimisi järgib Home Assistanti süsteemikeelt.',
        "help_channel": 'Igal ajal. Staging osutab Klar NLU (Staging).',
        "local": 'Käivita kaasasolev mootor (ainult HACS)',
        "remote": 'Kasuta Klar NLU rakendust või Dockerit',
        "stable": 'Stable (tootmine)',
        "staging": 'Staging (kandidaat)',
        "system": 'Süsteemi keel',
        "all": 'Kõik keeled',
        "normal": 'Tavaline',
        "casual": 'Vaba',
        "caring": 'Hooliv',
        "grumpy": 'Tige',
        "sarcastic": 'Sarkastiline',
        "pirate": 'Piraat',
        "quiet_name": 'Lühike kinnitus',
        "heard": 'Viimati kuuldud',
        "decision": 'Viimane otsus',
        "speech": 'Viimane vastus',
        "area": 'Kuuldud kohas',
        "down_title": 'Klar mootor seiskus',
        "down_desc": 'Kaasasolev Klar protsess ei tööta. Laadi Klar NLU uuesti jaotisest Seaded → Seadmed ja teenused.',
    },
    "eu": {
        "user_desc": 'Integrazio honek Assist-ekin hitz egiten du. Motor bereizi batek aztertzen du ahotsa: Klar NLU aplikazioa, prozesu bildua edo Docker. Home Assistant OS-en instalatu aplikazioa eta aukeratu Erabili Klar NLU aplikazioa. Aplikaziorik gabe, abiarazi motor bildua. Ez exekutatu biak.',
        "mode": 'Motorra',
        "channel": 'Argitalpen kanala',
        "url": 'Klar API URLa',
        "token": 'Idazteko tokena',
        "invalid": 'URLak http(s) izan behar du, erabiltzaile-izenik gabe.',
        "already": 'Klar NLU dagoeneko konfiguratuta dago',
        "opt_desc": 'Ahotsa, Assist hizkuntzak eta LLM Klar operadorearen UIan daude (Ezarpenak). Inprimaki honek motorra soilik konektatzen du: URL, tokena eta kanala.',
        "personality": 'Nortasuna',
        "languages": 'Hizkuntzak',
        "fallback": 'Berriketarako elkarrizketa-agentea',
        "refine_speech": 'Utzi LLM-ari NLU erantzunak birformulatzeko',
        "refine_prompt": 'Fintzeko gonbita',
        "assist_filter": 'Kontrolatu Assist-i agertutako entitateak soilik',
        "nlu_rag": 'NLU-RAG (aukerakoa)',
        "quiet_ack": 'Berrespen laburra (kanpaia)',
        "calendar_llm": 'Bidali egutegi-kontsultak LLM-ra',
        "help_personality": 'Integrazio honetan dago, ez Klar aplikazioan.',
        "help_refine_speech": 'Klar-ek gailuak kontrolatzen jarraitzen du. Ordezko LLM-ak erantzuna berridazten du.',
        "help_refine_prompt": 'Ahotsaren sistema-gonbita. Gailu-kontrolik ez, datu berririk ez, hizkuntza bera.',
        "help_token": 'Klar aplikazioko token bera.',
        "help_assist": 'Piztuta: Assist-ek ikusten duena soilik. Itzalita: ezkutuko entitateak ere.',
        "help_rag": 'Itzalita lehenetsita. Berriketan bat datorren zatia bakarrik doa ordezko eredura.',
        "help_quiet": 'Argia piztu/itzali sinplean ez da hitzik, soinu laburra satelitean.',
        "help_calendar_llm": 'Itzalita lehenetsita. Piztuta: Klarrek egutegia irakurri eta ordezko LLM-k gertaerak esaten ditu. Itzalita: Klarrek zerrenda esaten du. Sortu, ezabatu eta mugitu Klarrenean geratzen dira.',
        "help_languages": 'Lehenetsita Home Assistant sistemaren hizkuntza da.',
        "help_channel": 'Edozein unetan. Staging-ek Klar NLU (Staging) seinalatzen du.',
        "local": 'Abiarazi motor bildua (HACS soilik)',
        "remote": 'Erabili Klar NLU aplikazioa edo Docker',
        "stable": 'Stable (ekoizpena)',
        "staging": 'Staging (hautagaia)',
        "system": 'Sistemaren hizkuntza',
        "all": 'Hizkuntza guztiak',
        "normal": 'Normala',
        "casual": 'Lasai',
        "caring": 'Zaintzailea',
        "grumpy": 'Haserre',
        "sarcastic": 'Sarkastikoa',
        "pirate": 'Pirata',
        "quiet_name": 'Berrespen laburra',
        "heard": 'Azken entzundakoa',
        "decision": 'Azken erabakia',
        "speech": 'Azken erantzuna',
        "area": 'Hemen entzuna',
        "down_title": 'Klar motorra gelditu da',
        "down_desc": 'Klar prozesu bildua ez dago martxan. Kargatu berriro Klar NLU Ezarpenak → Gailuak eta zerbitzuak atalean.',
    },
    "ga": {
        "user_desc": 'Labhraíonn an comhtháthú seo le Assist. Déanann inneall ar leith anailís ar chaint: aip Klar NLU, an próiseas cuachta, nó Docker. Ar Home Assistant OS suiteáil an aip freisin agus roghnaigh Úsáid aip Klar NLU. Gan an aip, tosaigh an t-inneall cuachta. Ná rith an dá cheann.',
        "mode": 'Inneall',
        "channel": 'Cainéal eisiúna',
        "url": 'URL API Klar',
        "token": 'Comhartha scríofa',
        "invalid": 'Ní mór don URL a bheith http(s) gan ainm úsáideora.',
        "already": 'Tá Klar NLU socraithe cheana',
        "opt_desc": 'Tá an guth, teangacha Assist, agus an LLM i gcomhéadan oibreora Klar (Socruithe). Ní dhéanann an fhoirm seo ach an t-inneall a cheangal: URL, comhartha agus cainéal.',
        "personality": 'Pearsantacht',
        "languages": 'Teangacha',
        "fallback": 'Gníomhaire comhrá le haghaidh cainte',
        "refine_speech": 'Lig don LLM freagraí NLU a athscríobh',
        "refine_prompt": 'Leid mhionchoigeartaithe',
        "assist_filter": 'Rialaigh eintitis nochta do Assist amháin',
        "nlu_rag": 'NLU-RAG (roghnach)',
        "quiet_ack": 'Deimhniú gearr (clog)',
        "calendar_llm": 'Seol fiosrúcháin fhéilire chuig an LLM',
        "help_personality": 'San chomhtháthú seo, ní in aip Klar.',
        "help_refine_speech": 'Rialaíonn Klar gléasanna fós. Athscríobhann an LLM cúltaca an freagra.',
        "help_refine_prompt": 'Leid chórais na gutha. Gan rialú gléis, gan fíricí nua, an teanga chéanna.',
        "help_token": 'An comhartha céanna is atá in aip Klar.',
        "help_assist": 'Ar: an méid a fheiceann Assist amháin. As: eintitis fholaithe freisin.',
        "help_rag": 'As de réir réamhshocraithe. Sa chomhrá téann an slisne meaitseáilte amháin chuig an tsamhail chúltaca.',
        "help_quiet": 'Ar lasadh/mhúchadh simplí solais, gan abairt, fuaim ghearr ar an satailít amháin.',
        "help_calendar_llm": 'As de réir réamhshocraithe. Air: Léann Klar an fhéilire agus deir an LLM cúltaca na himeachtaí. As: Deir Klar an liosta. Fanann cruthú, scriosadh agus bogadh ag Klar.',
        "help_languages": 'Leanann an réamhshocrú teanga an chórais Home Assistant.',
        "help_channel": 'Am ar bith. Díríonn Staging ar Klar NLU (Staging).',
        "local": 'Tosaigh an t-inneall cuachta (HACS amháin)',
        "remote": 'Úsáid aip Klar NLU nó Docker',
        "stable": 'Stable (táirgeadh)',
        "staging": 'Staging (iarrthóir)',
        "system": 'Teanga an chórais',
        "all": 'Gach teanga',
        "normal": 'Gnáth',
        "casual": 'Réchúiseach',
        "caring": 'Cúramach',
        "grumpy": 'Greannmhar',
        "sarcastic": 'Searbhasach',
        "pirate": 'Foghlaí mara',
        "quiet_name": 'Deimhniú gearr',
        "heard": 'Cloiste deireanach',
        "decision": 'Cinneadh deireanach',
        "speech": 'Freagra deireanach',
        "area": 'Cloiste i',
        "down_title": 'Stop inneall Klar',
        "down_desc": 'Níl an próiseas Klar cuachta ag rith. Athlódáil Klar NLU i Socruithe → Gléasanna agus seirbhísí.',
    },
    "gl": {
        "user_desc": 'Esta integración fala con Assist. Un motor separado analiza a fala: a app Klar NLU, este proceso incluído ou Docker. En Home Assistant OS instala tamén a app e escolle Usar a app Klar NLU. Sen a app, inicia o motor incluído. Non executes ambos.',
        "mode": 'Motor',
        "channel": 'Canle de publicación',
        "url": 'URL da API Klar',
        "token": 'Token de escritura',
        "invalid": 'O URL debe ser http(s) sen nome de usuario.',
        "already": 'Klar NLU xa está configurado',
        "opt_desc": 'A voz, as linguas de Assist e o LLM están na IU de operador de Klar (Configuración). Este formulario só conecta o motor: URL, token e canle.',
        "personality": 'Personalidade',
        "languages": 'Linguas',
        "fallback": 'Axente de conversa para charla',
        "refine_speech": 'Deixar que o LLM reformule as respostas NLU',
        "refine_prompt": 'Indicación de refinamento',
        "assist_filter": 'Controlar só entidades expostas a Assist',
        "nlu_rag": 'NLU-RAG (opcional)',
        "quiet_ack": 'Confirmación breve (timbre)',
        "calendar_llm": 'Enviar as consultas de calendario ao LLM',
        "help_personality": 'Está nesta integración, non na app Klar.',
        "help_refine_speech": 'Klar segue controlando os dispositivos. O LLM de reserva reescribe a resposta.',
        "help_refine_prompt": 'Indicación de sistema da voz. Sen control de dispositivos, sen feitos novos, mesma lingua.',
        "help_token": 'O mesmo token que na app Klar.',
        "help_assist": 'Activado: só o que Assist pode ver. Desactivado: tamén entidades ocultas.',
        "help_rag": 'Desactivado por defecto. Na charla só o anaco recoñecido vai ao modelo de reserva.',
        "help_quiet": 'Ao acender ou apagar unha luz simple, sen frase: só un son curto no satélite.',
        "help_calendar_llm": 'Desactivado por defecto. Activado: Klar le o calendario e o LLM de reserva di os eventos. Desactivado: Klar di a lista. Crear, borrar e mover quedan en Klar.',
        "help_languages": 'Por defecto segue a lingua do sistema de Home Assistant.',
        "help_channel": 'En calquera momento. Staging apunta a Klar NLU (Staging).',
        "local": 'Iniciar o motor incluído (só HACS)',
        "remote": 'Usar a app Klar NLU ou Docker',
        "stable": 'Stable (produción)',
        "staging": 'Staging (candidato)',
        "system": 'Lingua do sistema',
        "all": 'Todas as linguas',
        "normal": 'Normal',
        "casual": 'Informal',
        "caring": 'Coidadosa',
        "grumpy": 'Resentida',
        "sarcastic": 'Sarcástica',
        "pirate": 'Pirata',
        "quiet_name": 'Confirmación breve',
        "heard": 'Última escoita',
        "decision": 'Última decisión',
        "speech": 'Última resposta',
        "area": 'Oído en',
        "down_title": 'O motor Klar detívose',
        "down_desc": 'O proceso Klar incluído non se está a executar. Recarga Klar NLU en Configuración → Dispositivos e servizos.',
    },
    "is": {
        "user_desc": 'Þessi samþætting talar við Assist. Sérstök vél greinir tal: Klar NLU appið, innifalinn ferill eða Docker. Á Home Assistant OS settu einnig appið upp og veldu Nota Klar NLU appið. Án apps skaltu ræsa innifalda vélina. Ekki keyra bæði.',
        "mode": 'Vél',
        "channel": 'Útgáfurás',
        "url": 'Klar API slóð',
        "token": 'Skriftóki',
        "invalid": 'Slóðin verður að vera http(s) án notandanafns.',
        "already": 'Klar NLU er þegar sett upp',
        "opt_desc": 'Rödd, Assist-tungumál og LLM eru í Klar-stjórnendaviðmótinu (Stillingar). Þetta eyðublað tengir aðeins vélina: slóð, teikn og rás.',
        "personality": 'Persónuleiki',
        "languages": 'Tungumál',
        "fallback": 'Samræðuumsjónarmaður fyrir spjall',
        "refine_speech": 'Láta LLM endurskrifa NLU svör',
        "refine_prompt": 'Fínstillingarvísbending',
        "assist_filter": 'Stýra aðeins einingum sem Assist sér',
        "nlu_rag": 'NLU-RAG (valfrjálst)',
        "quiet_ack": 'Stutt staðfesting (bjalla)',
        "calendar_llm": 'Senda dagatalsfyrirspurnir til LLM',
        "help_personality": 'Í þessari samþættingu, ekki í Klar appinu.',
        "help_refine_speech": 'Klar stýrir áfram tækjum. Varas LLM endurskrifar svarið.',
        "help_refine_prompt": 'Kerfisvísbending raddarinnar. Engin tækjastýring, engar nýjar staðreyndir, sama tungumál.',
        "help_token": 'Sami tóki og í Klar appinu.',
        "help_assist": 'Kveikt: aðeins það sem Assist sér. Slökkt: líka faldar einingar.',
        "help_rag": 'Slökkt sjálfgefið. Í spjalli fer aðeins samsvarandi sneið til varalíkansins.',
        "help_quiet": 'Við einfalda kveikingu/slökkvun ljóss er ekkert talað, aðeins stuttur hljóð á gervihnettinum.',
        "help_calendar_llm": 'Slökkt sjálfgefið. Kveikt: Klar les dagatalið, varakerfið segir atburðina. Slökkt: Klar segir listann. Búa til, eyða og færa verða áfram hjá Klar.',
        "help_languages": 'Sjálfgefið fylgir kerfistungumáli Home Assistant.',
        "help_channel": 'Hvenær sem er. Staging vísar á Klar NLU (Staging).',
        "local": 'Ræsa innifalda vélina (aðeins HACS)',
        "remote": 'Nota Klar NLU appið eða Docker',
        "stable": 'Stable (framleiðsla)',
        "staging": 'Staging (umsækjandi)',
        "system": 'Kerfistungumál',
        "all": 'Öll tungumál',
        "normal": 'Venjulegt',
        "casual": 'Afslappað',
        "caring": 'Umhyggjusamt',
        "grumpy": 'Fýlt',
        "sarcastic": 'Háðskt',
        "pirate": 'Sjóræningi',
        "quiet_name": 'Stutt staðfesting',
        "heard": 'Síðast heyrt',
        "decision": 'Síðasta ákvörðun',
        "speech": 'Síðasta svar',
        "area": 'Heyrt í',
        "down_title": 'Klar vélin stöðvaðist',
        "down_desc": 'Innifalinn Klar ferill er ekki í gangi. Endurhladdu Klar NLU undir Stillingar → Tæki og þjónustur.',
    },
    "lb": {
        "user_desc": 'Dës Integratioun schwätzt mat Assist. Eng separat Engine analyséiert Sprooch: d’Klar-NLU-App, dëse gebëndelte Prozess oder Docker. Op Home Assistant OS installéiert och d’App a wielt Klar-NLU-App benotzen. Ouni App start d’gebëndelt Engine. Net béid lafen.',
        "mode": 'Engine',
        "channel": 'Release-Kanal',
        "url": 'Klar API URL',
        "token": 'Schreif-Token',
        "invalid": 'D’URL muss http(s) sinn ouni Benotzernumm.',
        "already": 'Klar NLU ass scho konfiguréiert',
        "opt_desc": 'Stëmm, Assist-Sproochen an d’LLM sinn an der Klar-Operator-UI (Astellungen). Dëse Formulaire verbënnt nëmmen d’Engine: URL, Token a Kanal.',
        "personality": 'Perséinlechkeet',
        "languages": 'Sproochen',
        "fallback": 'Gespréichsagënt fir Smalltalk',
        "refine_speech": 'Den LLM NLU-Äntwerten ëmformuléieren loossen',
        "refine_prompt": 'Verfeinerungsprompt',
        "assist_filter": 'Nëmmen Entitéiten steieren, déi Assist gesäit',
        "nlu_rag": 'NLU-RAG (optional)',
        "quiet_ack": 'Kuerz Bestätegung (Klack)',
        "calendar_llm": 'Kalennerfroen un d\'LLM schécken',
        "help_personality": 'An dëser Integratioun, net an der Klar-App.',
        "help_refine_speech": 'Klar steiert weider Apparater. Den Ersatz-LLM schreift d’Äntwert ëm.',
        "help_refine_prompt": 'Systemprompt vun der Stëmm. Keng Apparatsteierung, keng nei Fakten, selwecht Sprooch.',
        "help_token": 'Deeselwechten Token wéi an der Klar-App.',
        "help_assist": 'Un: nëmmen wat Assist gesäit. Aus: och verstoppt Entitéiten.',
        "help_rag": 'Standard aus. Am Chat geet nëmmen de passenden Ausschnëtt un d’Ersatzmodell.',
        "help_quiet": 'Bei einfachem Luucht un/aus keng Saz, nëmme kuerze Toun um Satellit.',
        "help_calendar_llm": 'Standard aus. Un: Klar liest de Kalenner, d\'Ersatz-LLM seet d\'Terminer. Aus: Klar seet d\'Lëscht selwer. Uleeën, läschen a réckelen bleiwen bei Klar.',
        "help_languages": 'Standard ass d’Systemsprooch vun Home Assistant.',
        "help_channel": 'Jäerzäit. Staging weist op Klar NLU (Staging).',
        "local": 'Gebëndelt Engine starten (nëmmen HACS)',
        "remote": 'Klar-NLU-App oder Docker benotzen',
        "stable": 'Stable (Produktioun)',
        "staging": 'Staging (Kandidat)',
        "system": 'Systemsprooch',
        "all": 'All Sproochen',
        "normal": 'Normal',
        "casual": 'Locker',
        "caring": 'Fürsorgeresch',
        "grumpy": 'Mürrësch',
        "sarcastic": 'Sarkastesch',
        "pirate": 'Pirat',
        "quiet_name": 'Kuerz Bestätegung',
        "heard": 'Lescht héieren',
        "decision": 'Lescht Decisioun',
        "speech": 'Lescht Äntwert',
        "area": 'Héieren zu',
        "down_title": 'Klar-Engine gestoppt',
        "down_desc": 'De gebëndelte Klar-Prozess leeft net. Lued Klar NLU ënner Astellungen → Apparater a Servicer nei.',
    },
    "kw": {
        "user_desc": 'An kesunwans ma a gews orth Assist. Jynn dyffrans a dhiskwedh kows: an app Klar NLU, an argerdh kessyss, po Docker. War Home Assistant OS gwra installya an app ynwedh ha dewis Usya an app Klar NLU. Heb an app, dalleth an jynn kessyss. Na wra rewlya an dhew.',
        "mode": 'Jynn',
        "channel": 'Kanel dyllo',
        "url": 'URL API Klar',
        "token": 'Tokyn skrifa',
        "invalid": 'Res yw dhe’n URL bos http(s) heb hanow usyer.',
        "already": 'Klar NLU yw settys seulabrys',
        "opt_desc": "Y lev, yethow Assist, ha'n LLM yw y'n UI gwithyas Klar (Settyansow). An furvlen ma a jun an jynn hepken: URL, tokn ha kanel.",
        "personality": 'Personoleth',
        "languages": 'Yethow',
        "fallback": 'Agent keskows rag hwedhlow',
        "refine_speech": 'Gas dhe’n LLM dasskrifa gorthypow NLU',
        "refine_prompt": 'Prompt finheans',
        "assist_filter": 'Kontrollya yn unnik entites diskudhys dhe Assist',
        "nlu_rag": 'NLU-RAG (dewisyel)',
        "quiet_ack": 'Afydhyans berr (klogh)',
        "calendar_llm": 'Danvon govynnow kalender dhe\'n LLM',
        "help_personality": 'Y’n kesunwans ma, a-napp Klar.',
        "help_refine_speech": 'Klar a wra hwath kontrollya devisys. An LLM reserv a dhasskrif an gorthyp.',
        "help_refine_prompt": 'Prompt system an lev. Heb kontrol devis, heb feythow nowydh, an keth yeth.',
        "help_token": 'An keth tokyn avel y’n app Klar.',
        "help_assist": 'War: yn unnik an pyth a wel Assist. Dhe-ves: entites kudh ynwedh.',
        "help_rag": 'Dhe-ves dre dhefowt. Yn keskows yn unnik an tamm kevys a ydh dhe’n model reserv.',
        "help_quiet": 'War golow sempel war/dhe-ves, heb lavar, son berr war an loer yn unnik.',
        "help_calendar_llm": 'Degewys dhe-ves. Warbarth: Klar a red an kalender, an LLM reserv a lever an hwarvosow. Dhe-ves: Klar a lever an rol. Gwruthyl, dilea ha gwaya a wort yn Klar.',
        "help_languages": 'Defowt a hol yeth system Home Assistant.',
        "help_channel": 'Pub termyn. Staging a boynt orth Klar NLU (Staging).',
        "local": 'Dalleth an jynn kessyss (HACS yn unnik)',
        "remote": 'Usya an app Klar NLU po Docker',
        "stable": 'Stable (askorrans)',
        "staging": 'Staging (ombrofyer)',
        "system": 'Yeth an system',
        "all": 'Pub yeth',
        "normal": 'Usadow',
        "casual": 'Dibryder',
        "caring": 'Omwithus',
        "grumpy": 'Sornus',
        "sarcastic": 'Sarkastek',
        "pirate": 'Morladron',
        "quiet_name": 'Afydhyans berr',
        "heard": 'Klewys diwettha',
        "decision": 'Ernans diwettha',
        "speech": 'Gorthyp diwettha',
        "area": 'Klewys yn',
        "down_title": 'Jynn Klar a hedhis',
        "down_desc": 'Nyns yw an argerdh Klar kessyss ow rewlya. Dasgarga Klar NLU yn Settyansow → Devisys ha gonisyow.',
    },
    "lt": {
        "user_desc": 'Ši integracija kalba su Assist. Atskiras variklis analizuoja kalbą: Klar NLU programa, pridedamas procesas arba Docker. Home Assistant OS įdiekite ir programą, tada rinkitės Naudoti Klar NLU programą. Be programos paleiskite pridedamą variklį. Nenaudokite abiejų.',
        "mode": 'Variklis',
        "channel": 'Leidimo kanalas',
        "url": 'Klar API URL',
        "token": 'Rašymo prieigos raktas',
        "invalid": 'URL turi būti http(s) be naudotojo vardo.',
        "already": 'Klar NLU jau sukonfigūruotas',
        "opt_desc": 'Balsas, Assist kalbos ir LLM yra Klar operatoriaus sąsajoje (Nuostatos). Ši forma tik prijungia variklį: URL, prieigos raktas ir kanalas.',
        "personality": 'Asmenybė',
        "languages": 'Kalbos',
        "fallback": 'Pokalbių agentas plepėjimui',
        "refine_speech": 'Leisti LLM perrašyti NLU atsakymus',
        "refine_prompt": 'Tobulinimo užklausa',
        "assist_filter": 'Valdyti tik Assist matomus objektus',
        "nlu_rag": 'NLU-RAG (neprivaloma)',
        "quiet_ack": 'Trumpas patvirtinimas (skambutis)',
        "calendar_llm": 'Siųsti kalendoriaus užklausas LLM',
        "help_personality": 'Šioje integracijoje, ne Klar programoje.',
        "help_refine_speech": 'Klar ir toliau valdo įrenginius. Atsarginis LLM perrašo atsakymą.',
        "help_refine_prompt": 'Balso sistemos užklausa. Be įrenginių valdymo, be naujų faktų, ta pati kalba.',
        "help_token": 'Tas pats raktas kaip Klar programoje.',
        "help_assist": 'Įjungta: tik tai, ką mato Assist. Išjungta: ir paslėpti objektai.',
        "help_rag": 'Pagal numatymą išjungta. Pokalbyje atsarginiam modeliui eina tik atpažinta dalis.',
        "help_quiet": 'Paprastai įjungiant / išjungiant šviesą be sakinio, tik trumpas garsas palydove.',
        "help_calendar_llm": 'Pagal numatymą išjungta. Įjungta: Klar skaito kalendorių, atsarginis LLM sako įvykius. Išjungta: Klar sako sąrašą. Kūrimas, trynimas ir perkėlimas lieka Klar.',
        "help_languages": 'Pagal numatymą seka Home Assistant sistemos kalbą.',
        "help_channel": 'Bet kada. Staging nurodo Klar NLU (Staging).',
        "local": 'Paleisti pridedamą variklį (tik HACS)',
        "remote": 'Naudoti Klar NLU programą arba Docker',
        "stable": 'Stable (gamyba)',
        "staging": 'Staging (kandidatas)',
        "system": 'Sistemos kalba',
        "all": 'Visos kalbos',
        "normal": 'Įprasta',
        "casual": 'Laisva',
        "caring": 'Rūpestinga',
        "grumpy": 'Niūri',
        "sarcastic": 'Sarkastiška',
        "pirate": 'Piratų',
        "quiet_name": 'Trumpas patvirtinimas',
        "heard": 'Paskutinį kartą girdėta',
        "decision": 'Paskutinis sprendimas',
        "speech": 'Paskutinis atsakymas',
        "area": 'Girdėta',
        "down_title": 'Klar variklis sustojo',
        "down_desc": 'Pridedamas Klar procesas neveikia. Įkelkite Klar NLU iš naujo: Nuostatos → Įrenginiai ir paslaugos.',
    },
    "lv": {
        "user_desc": 'Šī integrācija runā ar Assist. Atsevišķs dzinējs analizē runu: Klar NLU lietotne, iekļautais process vai Docker. Home Assistant OS instalējiet arī lietotni un izvēlieties Izmantot Klar NLU lietotni. Bez lietotnes palaidiet iekļauto dzinēju. Nedarbojiet abus.',
        "mode": 'Dzinējs',
        "channel": 'Izlaides kanāls',
        "url": 'Klar API URL',
        "token": 'Rakstīšanas marķieris',
        "invalid": 'URL jābūt http(s) bez lietotājvārda.',
        "already": 'Klar NLU jau ir iestatīts',
        "opt_desc": 'Balss, Assist valodas un LLM ir Klar operatora saskarnē (Iestatījumi). Šī veidlapa savieno tikai dzinēju: URL, marķieris un kanāls.',
        "personality": 'Personība',
        "languages": 'Valodas',
        "fallback": 'Sarunu aģents tērzēšanai',
        "refine_speech": 'Ļaut LLM pārfrāzēt NLU atbildes',
        "refine_prompt": 'Uzlabošanas uzvedne',
        "assist_filter": 'Vadīt tikai Assist redzamās entītijas',
        "nlu_rag": 'NLU-RAG (pēc izvēles)',
        "quiet_ack": 'Īsa apstiprināšana (zvans)',
        "calendar_llm": 'Sūtīt kalendāra vaicājumus uz LLM',
        "help_personality": 'Šajā integrācijā, nevis Klar lietotnē.',
        "help_refine_speech": 'Klar joprojām vada ierīces. Rezerves LLM pārraksta atbildi.',
        "help_refine_prompt": 'Balss sistēmas uzvedne. Bez ierīču vadības, bez jauniem faktiem, tā pati valoda.',
        "help_token": 'Tas pats marķieris kā Klar lietotnē.',
        "help_assist": 'Ieslēgts: tikai to, ko redz Assist. Izslēgts: arī slēptās entītijas.',
        "help_rag": 'Pēc noklusējuma izslēgts. Tērzēšanā rezerves modelim iet tikai atpazītais fragments.',
        "help_quiet": 'Vienkāršai gaismas ieslēgšanai/izslēgšanai nav teikuma, tikai īss skaņa uz satelīta.',
        "help_calendar_llm": 'Pēc noklusējuma izslēgts. Ieslēgts: Klar lasa kalendāru, rezerves LLM saka notikumus. Izslēgts: Klar saka sarakstu. Izveide, dzēšana un pārvietošana paliek Klar.',
        "help_languages": 'Pēc noklusējuma seko Home Assistant sistēmas valodai.',
        "help_channel": 'Jebkurā laikā. Staging norāda uz Klar NLU (Staging).',
        "local": 'Palaist iekļauto dzinēju (tikai HACS)',
        "remote": 'Izmantot Klar NLU lietotni vai Docker',
        "stable": 'Stable (ražošana)',
        "staging": 'Staging (kandidāts)',
        "system": 'Sistēmas valoda',
        "all": 'Visas valodas',
        "normal": 'Parasta',
        "casual": 'Neformāla',
        "caring": 'Gādīga',
        "grumpy": 'Nikna',
        "sarcastic": 'Sarkastiska',
        "pirate": 'Pirāts',
        "quiet_name": 'Īsa apstiprināšana',
        "heard": 'Pēdējoreiz dzirdēts',
        "decision": 'Pēdējais lēmums',
        "speech": 'Pēdējā atbilde',
        "area": 'Dzirdēts',
        "down_title": 'Klar dzinējs apstājās',
        "down_desc": 'Iekļautais Klar process nedarbojas. Pārlādējiet Klar NLU sadaļā Iestatījumi → Ierīces un pakalpojumi.',
    },
}
