"""HA UI copy recovered for Indic Assist locales."""

from __future__ import annotations

INDIC: dict[str, dict[str, str]] = {
    "hi": {
        "user_desc": 'यह इंटीग्रेशन Assist से बात करता है। अलग इंजन वाणी पढ़ता है: Klar NLU ऐप, बंडल प्रक्रिया, या Docker। Home Assistant OS पर ऐप भी लगाएँ और Klar NLU ऐप इस्तेमाल करें चुनें। बिना ऐप बंडल इंजन चलाएँ। दोनों एक साथ न चलाएँ।',
        "mode": 'इंजन',
        "channel": 'रिलीज़ चैनल',
        "url": 'Klar API URL',
        "token": 'लेखन टोकन',
        "invalid": 'URL http(s) होना चाहिए, बिना उपयोगकर्ता नाम।',
        "already": 'Klar NLU पहले से सेट है',
        "opt_desc": 'आवाज़, Assist भाषाएँ और LLM Klar ऑपरेटर UI (सेटिंग्स) में हैं। यह फ़ॉर्म केवल इंजन जोड़ता है: URL, टोकन और चैनल।',
        "personality": 'व्यक्तित्व',
        "languages": 'भाषाएँ',
        "fallback": 'गपशप के लिए बातचीत एजेंट',
        "refine_speech": 'LLM से NLU उत्तर सुधारें',
        "refine_prompt": 'सुधार संकेत',
        "assist_filter": 'केवल Assist को दिखाई इकाइयाँ नियंत्रित करें',
        "nlu_rag": 'NLU-RAG (वैकल्पिक)',
        "quiet_ack": 'छोटी पुष्टि (घंटी)',
        "calendar_llm": 'कैलेंडर प्रश्न LLM को भेजें',
        "help_personality": 'इस इंटीग्रेशन में है, Klar ऐप में नहीं।',
        "help_refine_speech": 'Klar उपकरण नियंत्रित करता रहता है। बैकअप LLM उत्तर फिर लिखता है।',
        "help_refine_prompt": 'आवाज़ का सिस्टम संकेत। उपकरण नियंत्रण नहीं, नए तथ्य नहीं, वही भाषा।',
        "help_token": 'Klar ऐप जैसा ही टोकन।',
        "help_assist": 'चालू: केवल जो Assist देखे। बंद: छिपी इकाइयाँ भी।',
        "help_rag": 'डिफ़ॉल्ट बंद। बातचीत में केवल मिला टुकड़ा बैकअप मॉडल को जाता है।',
        "help_quiet": 'साधारण बत्ती चालू/बंद पर वाक्य नहीं, उपग्रह पर छोटी ध्वनि।',
        "help_calendar_llm": 'डिफ़ॉल्ट बंद। चालू: क्लार कैलेंडर पढ़ता है, बैकअप LLM कार्यक्रम कहता है। बंद: क्लार सूची स्वयं कहता है। बनाना, मिटाना और सरकाना क्लार पर रहता है।',
        "help_languages": 'डिफ़ॉल्ट Home Assistant की सिस्टम भाषा है।',
        "help_channel": 'कभी भी। Staging Klar NLU (Staging) की ओर है।',
        "local": 'बंडल इंजन शुरू करें (केवल HACS)',
        "remote": 'Klar NLU ऐप या Docker इस्तेमाल करें',
        "stable": 'Stable (उत्पादन)',
        "staging": 'Staging (उम्मीदवार)',
        "system": 'सिस्टम भाषा',
        "all": 'सभी भाषाएँ',
        "normal": 'सामान्य',
        "casual": 'आरामदायक',
        "caring": 'ध्यान रखने वाला',
        "grumpy": 'चिड़चिड़ा',
        "sarcastic": 'व्यंग्यात्मक',
        "pirate": 'समुद्री डाकू',
        "quiet_name": 'छोटी पुष्टि',
        "heard": 'आखिरी सुना',
        "decision": 'आखिरी निर्णय',
        "speech": 'आखिरी उत्तर',
        "area": 'सुना गया',
        "down_title": 'Klar इंजन रुक गया',
        "down_desc": 'बंडल Klar प्रक्रिया नहीं चल रही। सेटिंग्स → डिवाइस और सेवाएँ से Klar NLU फिर लोड करें।',
    },
    "bn": {
        "user_desc": 'এই ইন্টিগ্রেশন Assist-এর সঙ্গে কথা বলে। আলাদা ইঞ্জিন কথা বিশ্লেষণ করে: Klar NLU অ্যাপ, বান্ডিল প্রক্রিয়া, বা Docker। Home Assistant OS-এ অ্যাপও ইনস্টল করে Klar NLU অ্যাপ ব্যবহার করুন বেছে নিন। অ্যাপ ছাড়া বান্ডিল ইঞ্জিন চালান। দুটো একসঙ্গে চালাবেন না।',
        "mode": 'ইঞ্জিন',
        "channel": 'রিলিজ চ্যানেল',
        "url": 'Klar API URL',
        "token": 'লেখার টোকেন',
        "invalid": 'URL হতে হবে http(s), ব্যবহারকারীর নাম ছাড়া।',
        "already": 'Klar NLU ইতিমধ্যে সেটআপ আছে',
        "opt_desc": 'ভয়েস, Assist ভাষা এবং LLM Klar অপারেটর UI (সেটিংস)-এ আছে। এই ফর্ম শুধু ইঞ্জিন সংযোগ করে: URL, টোকেন এবং চ্যানেল।',
        "personality": 'ব্যক্তিত্ব',
        "languages": 'ভাষা',
        "fallback": 'আড্ডার জন্য কথোপকথন এজেন্ট',
        "refine_speech": 'LLM দিয়ে NLU উত্তর লিখুন',
        "refine_prompt": 'পরিমার্জন প্রম্পট',
        "assist_filter": 'শুধু Assist-এ দেখা সত্তা নিয়ন্ত্রণ করুন',
        "nlu_rag": 'NLU-RAG (ঐচ্ছিক)',
        "quiet_ack": 'সংক্ষিপ্ত নিশ্চিতকরণ (ঘণ্টা)',
        "calendar_llm": 'ক্যালেন্ডার প্রশ্ন LLM-এ পাঠান',
        "help_personality": 'এই ইন্টিগ্রেশনে, Klar অ্যাপে নয়।',
        "help_refine_speech": 'Klar এখনও ডিভাইস নিয়ন্ত্রণ করে। ব্যাকআপ LLM উত্তর আবার লেখে।',
        "help_refine_prompt": 'কণ্ঠের সিস্টেম প্রম্পট। ডিভাইস নিয়ন্ত্রণ নেই, নতুন তথ্য নেই, একই ভাষা।',
        "help_token": 'Klar অ্যাপের মতোই টোকেন।',
        "help_assist": 'চালু: শুধু Assist যা দেখে। বন্ধ: লুকোনো সত্তাও।',
        "help_rag": 'ডিফল্ট বন্ধ। আড্ডায় শুধু মিলে যাওয়া অংশ ব্যাকআপ মডেলে যায়।',
        "help_quiet": 'সাধারণ আলো চালু/বন্ধে বাক্য নেই, স্যাটেলাইটে শুধু ছোট শব্দ।',
        "help_calendar_llm": 'ডিফল্ট বন্ধ। চালু: ক্লার ক্যালেন্ডার পড়ে, ব্যাকআপ LLM অনুষ্ঠান বলে। বন্ধ: ক্লার তালিকা নিজে বলে। তৈরি, মুছা ও সরানো ক্লারেই থাকে।',
        "help_languages": 'ডিফল্ট Home Assistant সিস্টেম ভাষা।',
        "help_channel": 'যখন খুশি। Staging Klar NLU (Staging) দেখায়।',
        "local": 'বান্ডিল ইঞ্জিন চালু করুন (শুধু HACS)',
        "remote": 'Klar NLU অ্যাপ বা Docker ব্যবহার করুন',
        "stable": 'Stable (উৎপাদন)',
        "staging": 'Staging (প্রার্থী)',
        "system": 'সিস্টেম ভাষা',
        "all": 'সব ভাষা',
        "normal": 'সাধারণ',
        "casual": 'আরামদায়ক',
        "caring": 'যত্নশীল',
        "grumpy": 'খিটখিটে',
        "sarcastic": 'ব্যঙ্গাত্মক',
        "pirate": 'জলদস্যু',
        "quiet_name": 'সংক্ষিপ্ত নিশ্চিতকরণ',
        "heard": 'শেষ শোনা',
        "decision": 'শেষ সিদ্ধান্ত',
        "speech": 'শেষ উত্তর',
        "area": 'শোনা গেছে',
        "down_title": 'Klar ইঞ্জিন থেমেছে',
        "down_desc": 'বান্ডিল Klar প্রক্রিয়া চলছে না। সেটিংস → ডিভাইস ও পরিষেবা থেকে Klar NLU আবার লোড করুন।',
    },
    "gu": {
        "user_desc": 'This integration talks to Assist. A separate engine parses speech: the Klar NLU App, this bundled process, or Docker. On Home Assistant OS install the App as well, then pick Use the Klar NLU App. Without the App, pick Start the bundled engine. Do not run both.',
        "mode": 'એન્જિન',
        "channel": 'રિલીઝ ચેનલ',
        "url": 'Klar API URL',
        "token": 'લેખન ટોકન',
        "invalid": 'URL http(s) હોવું જોઈએ, વપરાશકર્તા નામ વગર.',
        "already": 'Klar NLU પહેલેથી સેટ છે',
        "opt_desc": 'અવાજ, Assist ભાષાઓ અને LLM Klar ઓપરેટર UI (સેટિંગ્સ)માં છે. આ ફોર્મ ફક્ત એન્જિન જોડે છે: URL, ટોકન અને ચેનલ.',
        "personality": 'વ્યક્તિત્વ',
        "languages": 'ભાષાઓ',
        "fallback": 'વાતચીત માટે વાર્તાલાપ એજન્ટ',
        "refine_speech": 'LLM પાસે NLU જવાબ સુધારાવો',
        "refine_prompt": 'સુધારા પ્રોમ્પ્ટ',
        "assist_filter": 'ફક્ત Assistને દેખાતી એકમો નિયંત્રિત કરો',
        "nlu_rag": 'NLU-RAG (વૈકલ્પિક)',
        "quiet_ack": 'ટૂંકી પુષ્ટિ (ઘંટડી)',
        "calendar_llm": 'કેલેન્ડર પ્રશ્નો LLMને મોકલો',
        "help_personality": 'આ એકીકરણમાં છે, Klar એપમાં નહીં.',
        "help_refine_speech": 'Klar ઉપકરણો નિયંત્રિત કરે છે. બેકઅપ LLM જવાબ ફરી લખે છે.',
        "help_refine_prompt": 'અવાજનું સિસ્ટમ પ્રોમ્પ્ટ. ઉપકરણ નિયંત્રણ નહીં, નવી હકીકત નહીં, એ જ ભાષા.',
        "help_token": 'Klar એપ જેવું જ ટોકન.',
        "help_assist": 'ચાલુ: ફક્ત Assist જુએ તે. બંધ: છુપાયેલા એકમો પણ.',
        "help_rag": 'મૂળભૂત બંધ. વાતમાં ફક્ત મળેલો ટુકડો બેકઅપ મોડેલને જાય છે.',
        "help_quiet": 'સાદી લાઇટ ચાલુ/બંધ પર વાક્ય નહીં, સેટેલાઇટ પર ટૂંકો અવાજ.',
        "help_calendar_llm": 'મૂળભૂત બંધ. વાતમાં ફક્ત મળેલો ટુકડો બેકઅપ મોડેલને જાય છે. કેલેન્ડર પ્રશ્નો LLMને મોકલો.',
        "help_languages": 'મૂળભૂત Home Assistant સિસ્ટમ ભાષા છે.',
        "help_channel": 'ગમે ત્યારે. Staging Klar NLU (Staging) તરફ છે.',
        "local": 'બંડલ એન્જિન શરૂ કરો (ફક્ત HACS)',
        "remote": 'Klar NLU એપ અથવા Docker વાપરો',
        "stable": 'Stable (ઉત્પાદન)',
        "staging": 'Staging (ઉમેદવાર)',
        "system": 'સિસ્ટમ ભાષા',
        "all": 'બધી ભાષાઓ',
        "normal": 'સામાન્ય',
        "casual": 'આરામદાયક',
        "caring": 'કાળજી રાખનાર',
        "grumpy": 'ચિડાયેલું',
        "sarcastic": 'વ્યંગ્યાત્મક',
        "pirate": 'ચાંચિયો',
        "quiet_name": 'ટૂંકી પુષ્ટિ',
        "heard": 'છેલ્લે સાંભળ્યું',
        "decision": 'છેલ્લો નિર્ણય',
        "speech": 'છેલ્લો જવાબ',
        "area": 'સાંભળ્યું',
        "down_title": 'Klar એન્જિન અટક્યું',
        "down_desc": 'બંડલ Klar પ્રક્રિયા ચાલતી નથી. સેટિંગ્સ → ઉપકરણો અને સેવાઓમાંથી Klar NLU ફરી લોડ કરો.',
    },
    "kn": {
        "user_desc": 'This integration talks to Assist. A separate engine parses speech: the Klar NLU App, this bundled process, or Docker. On Home Assistant OS install the App as well, then pick Use the Klar NLU App. Without the App, pick Start the bundled engine. Do not run both.',
        "mode": 'ಎಂಜಿನ್',
        "channel": 'ಬಿಡುಗಡೆ ಚಾನಲ್',
        "url": 'Klar API URL',
        "token": 'ಬರೆಯುವ ಟೋಕನ್',
        "invalid": 'URL http(s) ಆಗಿರಬೇಕು, ಬಳಕೆದಾರ ಹೆಸರಿಲ್ಲದೆ.',
        "already": 'Klar NLU ಈಗಾಗಲೇ ಹೊಂದಿಸಲಾಗಿದೆ',
        "opt_desc": 'ಧ್ವನಿ, Assist ಭಾಷೆಗಳು ಮತ್ತು LLM Klar ಆಪರೇಟರ್ UI (ಸೆಟ್ಟಿಂಗ್‌ಗಳು)ಯಲ್ಲಿವೆ. ಈ ನಮೂನೆ ಇಂಜಿನ್ ಮಾತ್ರ ಸಂಪರ್ಕಿಸುತ್ತದೆ: URL, ಟೋಕನ್ ಮತ್ತು ಚಾನಲ್.',
        "personality": 'ವ್ಯಕ್ತಿತ್ವ',
        "languages": 'ಭಾಷೆಗಳು',
        "fallback": 'ಮಾತುಕತೆಗೆ ಸಂಭಾಷಣಾ ಏಜೆಂಟ್',
        "refine_speech": 'LLM NLU ಉತ್ತರಗಳನ್ನು ಬರೆಯಲಿ',
        "refine_prompt": 'ಸುಧಾರಣೆ ಪ್ರಾಂಪ್ಟ್',
        "assist_filter": 'Assistಗೆ ಕಾಣುವ ಘಟಕಗಳನ್ನು ಮಾತ್ರ ನಿಯಂತ್ರಿಸಿ',
        "nlu_rag": 'NLU-RAG (ಐಚ್ಛಿಕ)',
        "quiet_ack": 'ಚಿಕ್ಕ ದೃಢೀಕರಣ (ಗಂಟೆ)',
        "calendar_llm": 'ಕ್ಯಾಲೆಂಡರ್ ಪ್ರಶ್ನೆಗಳನ್ನು LLM ಗೆ ಕಳುಹಿಸಿ',
        "help_personality": 'ಈ ಏಕೀಕರಣದಲ್ಲಿ, Klar ಅಪ್ಲಿಯಲ್ಲಿ ಅಲ್ಲ.',
        "help_refine_speech": 'Klar ಸಾಧನಗಳನ್ನು ನಿಯಂತ್ರಿಸುತ್ತಲೇ ಇರುತ್ತದೆ. ಬ್ಯಾಕಪ್ LLM ಉತ್ತರವನ್ನು ಬರೆಯುತ್ತದೆ.',
        "help_refine_prompt": 'ಧ್ವನಿಯ ಸಿಸ್ಟಂ ಪ್ರಾಂಪ್ಟ್. ಸಾಧನ ನಿಯಂತ್ರಣವಿಲ್ಲ, ಹೊಸ ಸಂಗತಿಗಳಿಲ್ಲ, ಅದೇ ಭಾಷೆ.',
        "help_token": 'Klar ಅಪ್ಲಿಯಂತೆಯೇ ಟೋಕನ್.',
        "help_assist": 'On: only what Assist may see. Off: hidden entities too.',
        "help_rag": 'ಡೀಫಾಲ್ಟ್ ಆಫ್. ಮಾತಿನಲ್ಲಿ ಹೊಂದಿದ ತುಣುಕು ಮಾತ್ರ ಬ್ಯಾಕಪ್ ಮಾದರಿಗೆ ಹೋಗುತ್ತದೆ.',
        "help_quiet": 'ಸರಳ ಬೆಳಕು ಆನ್/ಆಫ್\u200cನಲ್ಲಿ ವಾಕ್ಯವಿಲ್ಲ, ಉಪಗ್ರಹದಲ್ಲಿ ಚಿಕ್ಕ ಧ್ವನಿ.',
        "help_calendar_llm": 'ಡೀಫಾಲ್ಟ್ ಆಫ್. ಮಾತಿನಲ್ಲಿ ಹೊಂದಿದ ತುಣುಕು ಮಾತ್ರ ಬ್ಯಾಕಪ್ ಮಾದರಿಗೆ ಹೋಗುತ್ತದೆ. ಕ್ಯಾಲೆಂಡರ್ ಪ್ರಶ್ನೆಗಳನ್ನು LLM ಗೆ ಕಳುಹಿಸಿ.',
        "help_languages": 'ಡೀಫಾಲ್ಟ್ Home Assistant ಸಿಸ್ಟಂ ಭಾಷೆ.',
        "help_channel": 'ಯಾವಾಗ ಬೇಕಾದರೂ. Staging Klar NLU (Staging) ಕಡೆಗೆ.',
        "local": 'ಬಂಡಲ್ ಎಂಜಿನ್ ಪ್ರಾರಂಭಿಸಿ (HACS ಮಾತ್ರ)',
        "remote": 'Klar NLU ಅಪ್ಲಿ ಅಥವಾ Docker ಬಳಸಿ',
        "stable": 'Stable (ಉತ್ಪಾದನೆ)',
        "staging": 'Staging (ಅಭ್ಯರ್ಥಿ)',
        "system": 'ಸಿಸ್ಟಂ ಭಾಷೆ',
        "all": 'ಎಲ್ಲಾ ಭಾಷೆಗಳು',
        "normal": 'ಸಾಮಾನ್ಯ',
        "casual": 'ಸಡಿಲ',
        "caring": 'ಕಾಳಜಿಯುಳ್ಳ',
        "grumpy": 'ಕೋಪಗೊಂಡ',
        "sarcastic": 'ವ್ಯಂಗ್ಯ',
        "pirate": 'ಕಡಲ್ಗಳ್ಳ',
        "quiet_name": 'ಚಿಕ್ಕ ದೃಢೀಕರಣ',
        "heard": 'ಕೊನೆಯದಾಗಿ ಕೇಳಿದ್ದು',
        "decision": 'ಕೊನೆಯ ನಿರ್ಧಾರ',
        "speech": 'ಕೊನೆಯ ಉತ್ತರ',
        "area": 'ಕೇಳಿದ ಸ್ಥಳ',
        "down_title": 'Klar ಎಂಜಿನ್ ನಿಂತಿದೆ',
        "down_desc": 'ಬಂಡಲ್ Klar ಪ್ರಕ್ರಿಯೆ ಓಡುತ್ತಿಲ್ಲ. ಸೆಟ್ಟಿಂಗ್\u200cಗಳು → ಸಾಧನಗಳು ಮತ್ತು ಸೇವೆಗಳಲ್ಲಿ Klar NLU ಮರುಲೋಡ್ ಮಾಡಿ.',
    },
    "ml": {
        "user_desc": 'This integration talks to Assist. A separate engine parses speech: the Klar NLU App, this bundled process, or Docker. On Home Assistant OS install the App as well, then pick Use the Klar NLU App. Without the App, pick Start the bundled engine. Do not run both.',
        "mode": 'എഞ്ചിൻ',
        "channel": 'റിലീസ് ചാനൽ',
        "url": 'Klar API URL',
        "token": 'എഴുത്ത് ടോക്കൺ',
        "invalid": 'URL http(s) ആയിരിക്കണം, ഉപയോക്തൃനാമമില്ലാതെ.',
        "already": 'Klar NLU ഇതിനകം സജ്ജമാണ്',
        "opt_desc": 'ശബ്ദവും Assist ഭാഷകളും LLM-ഉം Klar ഓപ്പറേറ്റർ UI-യിലാണ് (ക്രമീകരണങ്ങൾ). ഈ ഫോം എഞ്ചിൻ മാത്രം ബന്ധിപ്പിക്കുന്നു: URL, ടോക്കൺ, ചാനൽ.',
        "personality": 'വ്യക്തിത്വം',
        "languages": 'ഭാഷകൾ',
        "fallback": 'സംസാരത്തിനുള്ള സംഭാഷണ ഏജന്റ്',
        "refine_speech": 'LLM NLU മറുപടികൾ തിരുത്തട്ടെ',
        "refine_prompt": 'മെച്ചപ്പെടുത്തൽ പ്രോംപ്റ്റ്',
        "assist_filter": 'Assist കാണുന്ന യൂണിറ്റുകൾ മാത്രം നിയന്ത്രിക്കുക',
        "nlu_rag": 'NLU-RAG (ഓപ്ഷണൽ)',
        "quiet_ack": 'ചെറിയ സ്ഥിരീകരണം (മണി)',
        "calendar_llm": 'കലണ്ടർ ചോദ്യങ്ങൾ LLM-ലേക്ക് അയയ്ക്കുക',
        "help_personality": 'ഈ ഇന്റഗ്രേഷനിലാണ്, Klar ആപ്പിലല്ല.',
        "help_refine_speech": 'Klar ഉപകരണങ്ങൾ നിയന്ത്രിക്കുന്നത് തുടരും. ബാക്കപ്പ് LLM മറുപടി വീണ്ടും എഴുതും.',
        "help_refine_prompt": 'ശബ്ദത്തിന്റെ സിസ്റ്റം പ്രോംപ്റ്റ്. ഉപകരണ നിയന്ത്രണമില്ല, പുതിയ വസ്തുതകളില്ല, അതേ ഭാഷ.',
        "help_token": 'Klar ആപ്പിലേതു പോലെ തന്നെ ടോക്കൺ.',
        "help_assist": 'ഓൺ: Assist കാണുന്നത് മാത്രം. ഓഫ്: മറച്ച യൂണിറ്റുകളും.',
        "help_rag": 'ഡിഫോൾട്ട് ഓഫ്. സംസാരത്തിൽ പൊരുത്തപ്പെട്ട ഭാഗം മാത്രം ബാക്കപ്പ് മോഡലിലേക്ക്.',
        "help_quiet": 'ലളിതമായ ലൈറ്റ് ഓൺ/ഓഫിൽ വാക്യമില്ല, സാറ്റലൈറ്റിൽ ചെറിയ ശബ്ദം മാത്രം.',
        "help_calendar_llm": 'ഡിഫോൾട്ട് ഓഫ്. സംസാരത്തിൽ പൊരുത്തപ്പെട്ട ഭാഗം മാത്രം ബാക്കപ്പ് മോഡലിലേക്ക്. കലണ്ടർ ചോദ്യങ്ങൾ LLM-ലേക്ക് അയയ്ക്കുക.',
        "help_languages": 'ഡിഫോൾട്ട് Home Assistant സിസ്റ്റം ഭാഷയാണ്.',
        "help_channel": 'Works anytime. Staging points at Klar NLU (Staging).',
        "local": 'ബണ്ടിൽ എഞ്ചിൻ ആരംഭിക്കുക (HACS മാത്രം)',
        "remote": 'Klar NLU ആപ്പ് അല്ലെങ്കിൽ Docker ഉപയോഗിക്കുക',
        "stable": 'Stable (ഉത്പാദനം)',
        "staging": 'Staging (സ്ഥാനാർത്ഥി)',
        "system": 'സിസ്റ്റം ഭാഷ',
        "all": 'എല്ലാ ഭാഷകളും',
        "normal": 'സാധാരണ',
        "casual": 'അയഞ്ഞ',
        "caring": 'ശ്രദ്ധയുള്ള',
        "grumpy": 'ദേഷ്യമുള്ള',
        "sarcastic": 'പരിഹാസം',
        "pirate": 'കടൽക്കൊള്ളക്കാരൻ',
        "quiet_name": 'ചെറിയ സ്ഥിരീകരണം',
        "heard": 'അവസാനം കേട്ടത്',
        "decision": 'അവസാന തീരുമാനം',
        "speech": 'അവസാന മറുപടി',
        "area": 'കേട്ട സ്ഥലം',
        "down_title": 'Klar എഞ്ചിൻ നിന്നു',
        "down_desc": 'ബണ്ടിൽ Klar പ്രക്രിയ ഓടുന്നില്ല. ക്രമീകരണങ്ങൾ → ഉപകരണങ്ങളും സേവനങ്ങളും എന്നതിൽ Klar NLU വീണ്ടും ലോഡ് ചെയ്യുക.',
    },
    "mr": {
        "user_desc": 'हे एकत्रीकरण Assist शी बोलते. वेगळे इंजिन बोलणे वाचते: Klar NLU अॅप, बंडल प्रक्रिया, किंवा Docker. Home Assistant OS वर अॅपही बसवा आणि Klar NLU अॅप वापरा निवडा. अॅप नसल्यास बंडल इंजिन सुरू करा. दोन्ही एकत्र चालवू नका.',
        "mode": 'इंजिन',
        "channel": 'रिलीझ चॅनेल',
        "url": 'Klar API URL',
        "token": 'लेखन टोकन',
        "invalid": 'URL http(s) असावा, वापरकर्ता नावाशिवाय.',
        "already": 'Klar NLU आधीच सेट आहे',
        "opt_desc": 'आवाज, Assist भाषा आणि LLM Klar ऑपरेटर UI (सेटिंग्ज) मध्ये आहेत. हा फॉर्म फक्त इंजिन जोडतो: URL, टोकन आणि चॅनेल.',
        "personality": 'व्यक्तिमत्त्व',
        "languages": 'भाषा',
        "fallback": 'गप्पांसाठी संभाषण एजंट',
        "refine_speech": 'LLM ने NLU उत्तरे सुधारू द्या',
        "refine_prompt": 'सुधारणा प्रॉम्प्ट',
        "assist_filter": 'फक्त Assist ला दिसणाऱ्या घटक नियंत्रित करा',
        "nlu_rag": 'NLU-RAG (पर्यायी)',
        "quiet_ack": 'थोडी पुष्टी (घंटा)',
        "calendar_llm": 'दिनदर्शिका प्रश्न LLM ला पाठवा',
        "help_personality": 'या एकत्रीकरणात आहे, Klar अॅपमध्ये नाही.',
        "help_refine_speech": 'Klar उपकरणे नियंत्रित करत राहतो. बॅकअप LLM उत्तर पुन्हा लिहितो.',
        "help_refine_prompt": 'आवाजाचा सिस्टम प्रॉम्प्ट. उपकरण नियंत्रण नाही, नवीन तथ्ये नाहीत, तीच भाषा.',
        "help_token": 'Klar अॅपसारखेच टोकन.',
        "help_assist": 'चालू: फक्त Assist जे पाहतो. बंद: लपवलेले घटकही.',
        "help_rag": 'डीफॉल्ट बंद. गप्पांमध्ये फक्त जुळलेला तुकडा बॅकअप मॉडेलकडे जातो.',
        "help_quiet": 'साधी दिवा चालू/बंद करताना वाक्य नाही, उपग्रहावर थोडा आवाज.',
        "help_calendar_llm": 'डीफॉल्ट बंद. चालू: क्लार दिनदर्शिका वाचतो, बॅकअप LLM कार्यक्रम सांगतो. बंद: क्लार यादी स्वतः सांगतो. तयार, हटवणे, हलवणे क्लारकडेच राहते.',
        "help_languages": 'डीफॉल्ट Home Assistant ची सिस्टम भाषा आहे.',
        "help_channel": 'कधीही. Staging Klar NLU (Staging) कडे दर्शवते.',
        "local": 'बंडल इंजिन सुरू करा (फक्त HACS)',
        "remote": 'Klar NLU अॅप किंवा Docker वापरा',
        "stable": 'Stable (उत्पादन)',
        "staging": 'Staging (उमेदवार)',
        "system": 'सिस्टम भाषा',
        "all": 'सर्व भाषा',
        "normal": 'सामान्य',
        "casual": 'सहज',
        "caring": 'काळजी घेणारे',
        "grumpy": 'चिडखोर',
        "sarcastic": 'उपहासात्मक',
        "pirate": 'चांचेगिरी',
        "quiet_name": 'थोडी पुष्टी',
        "heard": 'शेवटचे ऐकले',
        "decision": 'शेवटचा निर्णय',
        "speech": 'शेवटचे उत्तर',
        "area": 'ऐकले',
        "down_title": 'Klar इंजिन थांबले',
        "down_desc": 'बंडल Klar प्रक्रिया चालत नाही. सेटिंग्ज → उपकरणे आणि सेवा येथे Klar NLU पुन्हा लोड करा.',
    },
    "ta": {
        "user_desc": 'இந்த ஒருங்கிணைப்பு Assist உடன் பேசுகிறது. தனி இயந்திரம் பேச்சைப் பகுக்கிறது: Klar NLU செயலி, தொகுப்பு செயல், அல்லது Docker. Home Assistant OS இல் செயலியையும் நிறுவி Klar NLU செயலியைப் பயன்படுத்து என்பதைத் தேர்ந்தெடுக்கவும். செயலி இல்லையெனில் தொகுப்பு இயந்திரத்தைத் தொடங்கவும். இரண்டையும் ஒன்றாக இயக்க வேண்டாம்.',
        "mode": 'இயந்திரம்',
        "channel": 'வெளியீட்டு சேனல்',
        "url": 'Klar API URL',
        "token": 'எழுதும் டோக்கன்',
        "invalid": 'URL http(s) ஆக இருக்க வேண்டும், பயனர் பெயர் இல்லாமல்.',
        "already": 'Klar NLU ஏற்கனவே அமைக்கப்பட்டுள்ளது',
        "opt_desc": 'குரல், Assist மொழிகள் மற்றும் LLM Klar இயக்குநர் UI (அமைப்புகள்) இல் உள்ளன. இந்த படிவம் இயந்திரத்தை மட்டும் இணைக்கிறது: URL, டோக்கன் மற்றும் சேனல்.',
        "personality": 'ஆளுமை',
        "languages": 'மொழிகள்',
        "fallback": 'அரட்டைக்கான உரையாடல் முகவர்',
        "refine_speech": 'LLM NLU பதில்களை மீண்டும் எழுதட்டும்',
        "refine_prompt": 'மேம்பாட்டு அறிவுறுத்தல்',
        "assist_filter": 'Assist காணும் அலகுகளை மட்டும் கட்டுப்படுத்து',
        "nlu_rag": 'NLU-RAG (விருப்பம்)',
        "quiet_ack": 'குறுகிய உறுதி (மணி)',
        "calendar_llm": 'நாட்காட்டி கேள்விகளை LLM-க்கு அனுப்பு',
        "help_personality": 'இந்த ஒருங்கிணைப்பில் உள்ளது, Klar செயலியில் இல்லை.',
        "help_refine_speech": 'Klar சாதனங்களைக் கட்டுப்படுத்துகிறது. காப்பு LLM பதிலை மீண்டும் எழுதுகிறது.',
        "help_refine_prompt": 'குரலின் அமைப்பு அறிவுறுத்தல். சாதனக் கட்டுப்பாடு இல்லை, புதிய உண்மை இல்லை, அதே மொழி.',
        "help_token": 'Klar செயலியில் உள்ள அதே டோக்கன்.',
        "help_assist": 'ஆன்: Assist காண்பது மட்டும். ஆஃப்: மறைந்த அலகுகளும்.',
        "help_rag": 'இயல்பு ஆஃப். அரட்டையில் பொருந்திய பகுதி மட்டும் காப்பு மாதிரிக்குச் செல்லும்.',
        "help_quiet": 'எளிய விளக்கு ஆன்/ஆஃப்பில் வாக்கியம் இல்லை, செயற்கைக்கோளில் குறுகிய ஒலி.',
        "help_calendar_llm": 'இயல்பு ஆஃப். ஆன்: க்ளாா் நாட்காட்டியைப் படிக்கும், காப்பு LLM நிகழ்வைச் சொல்லும். ஆஃப்: க்ளாா் பட்டியலைத் தானே சொல்லும். உருவாக்குதல், நீக்குதல், நகர்த்துதல் க்ளாரிலேயே இருக்கும்.',
        "help_languages": 'இயல்பு Home Assistant கணினி மொழி.',
        "help_channel": 'எப்போது வேண்டுமானாலும். Staging Klar NLU (Staging) ஐச் சுட்டுகிறது.',
        "local": 'தொகுப்பு இயந்திரத்தைத் தொடங்கு (HACS மட்டும்)',
        "remote": 'Klar NLU செயலி அல்லது Docker பயன்படுத்து',
        "stable": 'Stable (தயாரிப்பு)',
        "staging": 'Staging (வேட்பாளர்)',
        "system": 'கணினி மொழி',
        "all": 'அனைத்து மொழிகள்',
        "normal": 'சாதாரண',
        "casual": 'தளர்வான',
        "caring": 'கவனமான',
        "grumpy": 'கோபமான',
        "sarcastic": 'நையாண்டி',
        "pirate": 'கடற்கொள்ளை',
        "quiet_name": 'குறுகிய உறுதி',
        "heard": 'கடைசியாகக் கேட்டது',
        "decision": 'கடைசி முடிவு',
        "speech": 'கடைசி பதில்',
        "area": 'கேட்ட இடம்',
        "down_title": 'Klar இயந்திரம் நின்றது',
        "down_desc": 'தொகுப்பு Klar செயல் இயங்கவில்லை. அமைப்புகள் → சாதனங்கள் மற்றும் சேவைகளில் Klar NLU ஐ மீண்டும் ஏற்றவும்.',
    },
    "te": {
        "user_desc": 'This integration talks to Assist. A separate engine parses speech: the Klar NLU App, this bundled process, or Docker. On Home Assistant OS install the App as well, then pick Use the Klar NLU App. Without the App, pick Start the bundled engine. Do not run both.',
        "mode": 'ఇంజిన్',
        "channel": 'రిలీజ్ ఛానల్',
        "url": 'Klar API URL',
        "token": 'రాత టోకెన్',
        "invalid": 'URL must be http(s) without userinfo.',
        "already": 'Klar NLU ఇప్పటికే సెటప్ అయింది',
        "opt_desc": 'వాయిస్, భాషలు, LLM Klar operator UI (అమరికలు). This form only connects the engine: URL, token, and channel.',
        "personality": 'వ్యక్తిత్వం',
        "languages": 'భాషలు',
        "fallback": 'సంభాషణకు చాట్ ఏజెంట్',
        "refine_speech": 'LLM NLU సమాధానాలను మళ్లీ రాయనివ్వండి',
        "refine_prompt": 'మెరుగుదల ప్రాంప్ట్',
        "assist_filter": 'Assistకు కనిపించే అంశాలను మాత్రమే నియంత్రించండి',
        "nlu_rag": 'NLU-RAG (ఐచ్ఛికం)',
        "quiet_ack": 'చిన్న నిర్ధారణ (గంట)',
        "calendar_llm": 'క్యాలెండర్ ప్రశ్నలను LLMకి పంపండి',
        "help_personality": 'ఈ ఇంటిగ్రేషన్\u200cలో ఉంది, Klar యాప్\u200cలో కాదు.',
        "help_refine_speech": 'Klar still controls devices. The fallback LLM rewrites the reply.',
        "help_refine_prompt": 'Voice system prompt. No device control, no new facts, same language.',
        "help_token": 'Klar యాప్\u200cలో ఉన్నట్టే టోకెన్.',
        "help_assist": 'ఆన్: Assist చూసేది మాత్రమే. ఆఫ్: దాచిన అంశాలు కూడా.',
        "help_rag": 'డిఫాల్ట్ ఆఫ్. చాట్\u200cలో సరిపోయిన భాగం మాత్రమే బ్యాకప్ మోడల్\u200cకు వెళ్తుంది.',
        "help_quiet": 'సాధారణ లైట్ ఆన్/ఆఫ్\u200cలో వాక్యం లేదు, ఉపగ్రహంపై చిన్న ధ్వని మాత్రమే.',
        "help_calendar_llm": 'డిఫాల్ట్ ఆఫ్. చాట్‌లో సరిపోయిన భాగం మాత్రమే బ్యాకప్ మోడల్‌కు వెళ్తుంది. క్యాలెండర్ ప్రశ్నలను LLMకి పంపండి.',
        "help_languages": 'డిఫాల్ట్ Home Assistant సిస్టమ్ భాష.',
        "help_channel": 'ఎప్పుడైనా. Staging Klar NLU (Staging) వైపు చూపిస్తుంది.',
        "local": 'బండిల్ ఇంజిన్ ప్రారంభించు (HACS మాత్రమే)',
        "remote": 'Klar NLU యాప్ లేదా Docker ఉపయోగించు',
        "stable": 'Stable (ఉత్పత్తి)',
        "staging": 'Staging (అభ్యర్థి)',
        "system": 'సిస్టమ్ భాష',
        "all": 'అన్ని భాషలు',
        "normal": 'సాధారణ',
        "casual": 'సడలిన',
        "caring": 'శ్రద్ధగల',
        "grumpy": 'కోపంగా',
        "sarcastic": 'వ్యంగ్యం',
        "pirate": 'సముద్రదొంగ',
        "quiet_name": 'చిన్న నిర్ధారణ',
        "heard": 'చివరిగా విన్నది',
        "decision": 'చివరి నిర్ణయం',
        "speech": 'చివరి సమాధానం',
        "area": 'విన్న చోటు',
        "down_title": 'Klar ఇంజిన్ ఆగింది',
        "down_desc": 'బండిల్ Klar ప్రక్రియ నడవడం లేదు. సెట్టింగ్\u200cలు → పరికరాలు మరియు సేవలలో Klar NLUను మళ్లీ లోడ్ చేయండి.',
    },
    "pa": {
        "user_desc": 'This integration talks to Assist. A separate engine parses speech: the Klar NLU App, this bundled process, or Docker. On Home Assistant OS install the App as well, then pick Use the Klar NLU App. Without the App, pick Start the bundled engine. Do not run both.',
        "mode": 'ਇੰਜਣ',
        "channel": 'ਰਿਲੀਜ਼ ਚੈਨਲ',
        "url": 'Klar API URL',
        "token": 'ਲਿਖਣ ਟੋਕਨ',
        "invalid": 'URL http(s) ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ, ਵਰਤੋਂਕਾਰ ਨਾਂ ਤੋਂ ਬਿਨਾਂ।',
        "already": 'Klar NLU ਪਹਿਲਾਂ ਹੀ ਸੈੱਟ ਹੈ',
        "opt_desc": 'ਆਵਾਜ਼, ਭਾਸ਼ਾਵਾਂ ਅਤੇ LLM Klar operator UI (ਸੈਟਿੰਗਾਂ). This form only connects the engine: URL, token, and channel.',
        "personality": 'ਸ਼ਖਸੀਅਤ',
        "languages": 'ਭਾਸ਼ਾਵਾਂ',
        "fallback": 'ਗੱਲਬਾਤ ਲਈ ਗੱਲਬਾਤ ਏਜੰਟ',
        "refine_speech": 'LLM ਨੂੰ NLU ਜਵਾਬ ਠੀਕ ਕਰਨ ਦਿਓ',
        "refine_prompt": 'ਸੁਧਾਰ ਪ੍ਰੋੰਪਟ',
        "assist_filter": 'Only control entities exposed to Assist',
        "nlu_rag": 'NLU-RAG (ਵਿਕਲਪਿਕ)',
        "quiet_ack": 'Short confirmation (chime)',
        "calendar_llm": 'ਕੈਲੰਡਰ ਸਵਾਲ LLM ਨੂੰ ਭੇਜੋ',
        "help_personality": 'ਇਸ ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਵਿੱਚ ਹੈ, Klar ਐਪ ਵਿੱਚ ਨਹੀਂ।',
        "help_refine_speech": 'Klar still controls devices. The fallback LLM rewrites the reply.',
        "help_refine_prompt": 'ਆਵਾਜ਼ ਦਾ ਸਿਸਟਮ ਪ੍ਰੋੰਪਟ। ਡਿਵਾਈਸ ਕੰਟਰੋਲ ਨਹੀਂ, ਨਵੇਂ ਤੱਥ ਨਹੀਂ, ਉਹੀ ਭਾਸ਼ਾ।',
        "help_token": 'Klar ਐਪ ਵਾਲਾ ਹੀ ਟੋਕਨ।',
        "help_assist": 'On: only what Assist may see. Off: hidden entities too.',
        "help_rag": 'ਡਿਫਾਲਟ ਬੰਦ। ਗੱਲਬਾਤ ਵਿੱਚ ਸਿਰਫ਼ ਮਿਲਿਆ ਟੁਕੜਾ ਬੈਕਅੱਪ ਮਾਡਲ ਨੂੰ ਜਾਂਦਾ ਹੈ।',
        "help_quiet": 'ਸਧਾਰਨ ਲਾਈਟ ਚਾਲੂ/ਬੰਦ ਤੇ ਵਾਕ ਨਹੀਂ, ਉਪਗ੍ਰਹਿ ਤੇ ਛੋਟੀ ਆਵਾਜ਼।',
        "help_calendar_llm": 'ਡਿਫਾਲਟ ਬੰਦ। ਗੱਲਬਾਤ ਵਿੱਚ ਸਿਰਫ਼ ਮਿਲਿਆ ਟੁਕੜਾ ਬੈਕਅੱਪ ਮਾਡਲ ਨੂੰ ਜਾਂਦਾ ਹੈ। ਕੈਲੰਡਰ ਸਵਾਲ LLM ਨੂੰ ਭੇਜੋ.',
        "help_languages": 'ਡਿਫਾਲਟ Home Assistant ਸਿਸਟਮ ਭਾਸ਼ਾ ਹੈ।',
        "help_channel": 'ਕਿਸੇ ਵੀ ਵੇਲੇ। Staging Klar NLU (Staging) ਵੱਲ ਹੈ।',
        "local": 'ਬੰਡਲ ਇੰਜਣ ਚਾਲੂ ਕਰੋ (ਸਿਰਫ਼ HACS)',
        "remote": 'Klar NLU ਐਪ ਜਾਂ Docker ਵਰਤੋ',
        "stable": 'Stable (ਉਤਪਾਦਨ)',
        "staging": 'Staging (ਉਮੀਦਵਾਰ)',
        "system": 'ਸਿਸਟਮ ਭਾਸ਼ਾ',
        "all": 'ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ',
        "normal": 'ਆਮ',
        "casual": 'ਆਰਾਮਦਾਇਕ',
        "caring": 'ਧਿਆਨ ਰੱਖਣ ਵਾਲੀ',
        "grumpy": 'ਚਿੜਚਿੜੀ',
        "sarcastic": 'ਵਿਅੰਗਮਈ',
        "pirate": 'ਸਮੁੰਦਰੀ ਡਾਕੂ',
        "quiet_name": 'ਛੋਟੀ ਪੁਸ਼ਟੀ',
        "heard": 'ਆਖਰੀ ਵਾਰ ਸੁਣਿਆ',
        "decision": 'ਆਖਰੀ ਫ਼ੈਸਲਾ',
        "speech": 'ਆਖਰੀ ਜਵਾਬ',
        "area": 'ਸੁਣਿਆ',
        "down_title": 'Klar ਇੰਜਣ ਰੁਕ ਗਿਆ',
        "down_desc": 'ਬੰਡਲ Klar ਪ੍ਰਕਿਰਿਆ ਨਹੀਂ ਚੱਲ ਰਹੀ। ਸੈਟਿੰਗਾਂ → ਡਿਵਾਈਸਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਤੋਂ Klar NLU ਮੁੜ ਲੋਡ ਕਰੋ।',
    },
    "ne": {
        "user_desc": 'यो एकीकरण Assist सँग बोल्छ। छुट्टै इन्जिन वाणी पढ्छ: Klar NLU एप, बन्डल प्रक्रिया, वा Docker। Home Assistant OS मा एप पनि राखेर Klar NLU एप प्रयोग गर्नुहोस् रोज्नुहोस्। एप नभए बन्डल इन्जिन सुरु गर्नुहोस्। दुवै सँगै नचलाउनुहोस्।',
        "mode": 'इन्जिन',
        "channel": 'रिलिज च्यानल',
        "url": 'Klar API URL',
        "token": 'लेख्ने टोकन',
        "invalid": 'URL http(s) हुनुपर्छ, प्रयोगकर्ता नामबिना।',
        "already": 'Klar NLU पहिले नै सेट छ',
        "opt_desc": 'आवाज, Assist भाषा र LLM Klar अपरेटर UI (सेटिङ) मा छन्। यो फारमले इन्जिन मात्र जोड्छ: URL, टोकन र च्यानल।',
        "personality": 'व्यक्तित्व',
        "languages": 'भाषाहरू',
        "fallback": 'गफगाफका लागि कुराकानी एजेन्ट',
        "refine_speech": 'LLM लाई NLU जवाफ सच्याउन दिनुहोस्',
        "refine_prompt": 'सुधार संकेत',
        "assist_filter": 'Assist लाई देखिने एकाइ मात्र नियन्त्रण गर्नुहोस्',
        "nlu_rag": 'NLU-RAG (वैकल्पिक)',
        "quiet_ack": 'छोटो पुष्टि (घन्टी)',
        "calendar_llm": 'पात्रो प्रश्न LLM मा पठाउनुहोस्',
        "help_personality": 'यो एकीकरणमा छ, Klar एपमा होइन।',
        "help_refine_speech": 'Klar उपकरण नियन्त्रण गरिरहन्छ। ब्याकअप LLM जवाफ फेरि लेख्छ।',
        "help_refine_prompt": 'आवाजको सिस्टम संकेत। उपकरण नियन्त्रण छैन, नयाँ तथ्य छैन, उही भाषा।',
        "help_token": 'Klar एपकै जस्तो टोकन।',
        "help_assist": 'अन: Assist ले देख्ने मात्र। अफ: लुकेका एकाइ पनि।',
        "help_rag": 'पूर्वनिर्धारित अफ। कुराकानीमा मिलेको टुक्रा मात्र ब्याकअप मोडेलमा जान्छ।',
        "help_quiet": 'साधारण बत्ती अन/अफमा वाक्य छैन, उपग्रहमा छोटो आवाज मात्र।',
        "help_calendar_llm": 'पूर्वनिर्धारित बन्द। अन: क्लारले पात्रो पढ्छ, ब्याकअप LLM ले कार्यक्रम भन्छ। अफ: क्लारले सूची आफैं भन्छ। बनाउने, मेट्ने, सार्ने क्लारमै रहन्छ।',
        "help_languages": 'पूर्वनिर्धारित Home Assistant प्रणाली भाषा हो।',
        "help_channel": 'जुनसुकै बेला। Staging Klar NLU (Staging) तर्फ देखाउँछ।',
        "local": 'बन्डल इन्जिन सुरु गर्नुहोस् (HACS मात्र)',
        "remote": 'Klar NLU एप वा Docker प्रयोग गर्नुहोस्',
        "stable": 'Stable (उत्पादन)',
        "staging": 'Staging (उम्मेदवार)',
        "system": 'प्रणाली भाषा',
        "all": 'सबै भाषा',
        "normal": 'सामान्य',
        "casual": 'आरामदायी',
        "caring": 'हेरचाह गर्ने',
        "grumpy": 'रिसाहा',
        "sarcastic": 'व्यङ्ग्यात्मक',
        "pirate": 'समुद्री डाकू',
        "quiet_name": 'छोटो पुष्टि',
        "heard": 'पछिल्लो सुनेको',
        "decision": 'पछिल्लो निर्णय',
        "speech": 'पछिल्लो जवाफ',
        "area": 'सुनिएको',
        "down_title": 'Klar इन्जिन रोकियो',
        "down_desc": 'बन्डल Klar प्रक्रिया चलिरहेको छैन। सेटिङ → यन्त्र र सेवाबाट Klar NLU फेरि लोड गर्नुहोस्।',
    },
}
