"""Lane chrome for RTL, Indic, and other script Assist locales."""

from __future__ import annotations

from lang_packs.lanes import lane

PACKS: dict[str, dict[str, str]] = {
    "ar": lane(
        process_path="المسار", path_match="مطابقة", path_seed="بذرة", path_house="البيت", path_band="النطاق",
        lane_match="مطابقة", lane_match_engine="مطابقة (المحرك)", lane_language="اللغة", lane_house="البيت", lane_tabs="المسارات",
        lexicon_overlay="طبقة المعجم", lexicon_overlay_plus="طبقة المعجم +{count}",
        lexicon_empty="لا فروق لطبقة المعجم.", govern_seed="بذرة الحوكمة",
        govern_empty="بذور الأمان تأتي مع كل حزمة. الإيقاف يكتب تجاوز البيت؛ الأرضية المجمّعة تبقى شغّالة.",
        match_catalog="مطابقات مجمّعة", match_read_only="الصف الناقص يستخدم افتراضي المحرك. الطبقة الفارغة قائمة المرشحين اليوم.",
        match_enabled="تشغيل", match_disabled="إيقاف", match_precedence="الأسبقية",
        match_disable_warning="إيقاف area_command أو all_lights يغيّر أوامر الغرفة والبيت كله.",
        lexicon_path="مسار المجموعة", lexicon_token="رمز", lexicon_add="إضافة", lexicon_remove="إزالة",
        origin_engine="المحرك", origin_operator="المشغّل", origin_seed="بذرة", origin_trainer="المدرّب",
        compiled_floor="الأرضية المجمّعة", seed_on="تشغيل", seed_off="إيقاف",
    ),
    "he": lane(
        process_path="נתיב", path_match="התאמה", path_seed="זרע", path_house="בית", path_band="פס",
        lane_match="התאמה", lane_match_engine="התאמה (מנוע)", lane_language="שפה", lane_house="בית", lane_tabs="נתיבים",
        lexicon_overlay="שכבת לקסיקון", lexicon_overlay_plus="שכבת לקסיקון +{count}",
        lexicon_empty="אין דלתות של שכבת לקסיקון.", govern_seed="זרע משילות",
        govern_empty="זרעי בטיחות מגיעים עם כל חבילה. כיבוי כותב דריסת בית; הרצפה המהודרת נשארת דלוקה.",
        match_catalog="מתאימים מהודרים", match_read_only="שורה חסרה משתמשת בברירת המנוע. שכבה ריקה היא רשימת המועמדים של היום.",
        match_enabled="פועל", match_disabled="כבוי", match_precedence="עדיפות",
        match_disable_warning="כיבוי area_command או all_lights משנה פקודות חדר וכל הבית.",
        lexicon_path="נתיב הסט", lexicon_token="אסימון", lexicon_add="הוספה", lexicon_remove="הסרה",
        origin_engine="מנוע", origin_operator="מפעיל", origin_seed="זרע", origin_trainer="מאמן",
        compiled_floor="רצפה מהודרת", seed_on="פועל", seed_off="כבוי",
    ),
    "fa": lane(
        process_path="مسیر", path_match="تطبیق", path_seed="بذر", path_house="خانه", path_band="باند",
        lane_match="تطبیق", lane_match_engine="تطبیق (موتور)", lane_language="زبان", lane_house="خانه", lane_tabs="لاین‌ها",
        lexicon_overlay="همپوشانی واژگان", lexicon_overlay_plus="همپوشانی واژگان +{count}",
        lexicon_empty="دلتای همپوشانی واژگان نیست.", govern_seed="بذر حکمرانی",
        govern_empty="بذرهای ایمنی با هر بسته می‌آیند. خاموش بازنویسی خانه می‌نویسد؛ کف کامپایل‌شده روشن می‌ماند.",
        match_catalog="تطبیق‌گرهای کامپایل‌شده", match_read_only="ردیف غایب پیش‌فرض موتور را می‌گیرد. همپوشانی خالی فهرست نامزد امروز است.",
        match_enabled="روشن", match_disabled="خاموش", match_precedence="تقدم",
        match_disable_warning="خاموش کردن area_command یا all_lights فرمان‌های اتاق و کل خانه را عوض می‌کند.",
        lexicon_path="مسیر مجموعه", lexicon_token="توکن", lexicon_add="افزودن", lexicon_remove="حذف",
        origin_engine="موتور", origin_operator="اپراتور", origin_seed="بذر", origin_trainer="مربی",
        compiled_floor="کف کامپایل‌شده", seed_on="روشن", seed_off="خاموش",
    ),
    "ur": lane(
        process_path="راستہ", path_match="میچ", path_seed="بیج", path_house="گھر", path_band="بینڈ",
        lane_match="میچ", lane_match_engine="میچ (انجن)", lane_language="زبان", lane_house="گھر", lane_tabs="لینز",
        lexicon_overlay="لغت اوورلے", lexicon_overlay_plus="لغت اوورلے +{count}",
        lexicon_empty="لغت اوورلے کے ڈیلٹا نہیں۔", govern_seed="حکمرانی بیج",
        govern_empty="حفاظتی بیج ہر پیک کے ساتھ آتے ہیں۔ بند گھر کا اووررائیڈ لکھتا ہے؛ مرتب فرش آن رہتا ہے۔",
        match_catalog="مرتب میچرز", match_read_only="غائب قطار انجن کی ڈیفالٹ لیتی ہے۔ خالی اوورلے آج کی امیدوار فہرست ہے۔",
        match_enabled="آن", match_disabled="آف", match_precedence="ترجیح",
        match_disable_warning="area_command یا all_lights بند کرنے سے کمرے اور پورے گھر کے احکامات بدل جاتے ہیں۔",
        lexicon_path="سیٹ کا راستہ", lexicon_token="ٹوکن", lexicon_add="شامل", lexicon_remove="ہٹائیں",
        origin_engine="انجن", origin_operator="آپریٹر", origin_seed="بیج", origin_trainer="ٹرینر",
        compiled_floor="مرتب فرش", seed_on="آن", seed_off="آف",
    ),
    "tr": lane(
        process_path="Yol", path_match="Eşleşme", path_seed="Tohum", path_house="Ev", path_band="Bant",
        lane_match="Eşleşme", lane_match_engine="Eşleşme (motor)", lane_language="Dil", lane_house="Ev", lane_tabs="Şeritler",
        lexicon_overlay="Sözlük katmanı", lexicon_overlay_plus="Sözlük katmanı +{count}",
        lexicon_empty="Sözlük katmanı deltası yok.", govern_seed="Yönetim tohumu",
        govern_empty="Güvenlik tohumları her pakette gelir. Kapalı ev üzerine yazar; derlenmiş taban açık kalır.",
        match_catalog="Derlenmiş eşleştiriciler", match_read_only="Eksik satır motor varsayılanını kullanır. Boş katman bugünün aday listesidir.",
        match_enabled="Açık", match_disabled="Kapalı", match_precedence="Öncelik",
        match_disable_warning="area_command veya all_lights kapatmak oda ve tüm ev komutlarını değiştirir.",
        lexicon_path="Küme yolu", lexicon_token="Belirteç", lexicon_add="Ekle", lexicon_remove="Kaldır",
        origin_engine="motor", origin_operator="operatör", origin_seed="tohum", origin_trainer="eğitmen",
        compiled_floor="derlenmiş taban", seed_on="Açık", seed_off="Kapalı",
    ),
    "el": lane(
        process_path="Διαδρομή", path_match="Ταίριασμα", path_seed="Σπόρος", path_house="Σπίτι", path_band="Ζώνη",
        lane_match="Ταίριασμα", lane_match_engine="Ταίριασμα (μηχανή)", lane_language="Γλώσσα", lane_house="Σπίτι", lane_tabs="Λωρίδες",
        lexicon_overlay="Επικάλυψη λεξικού", lexicon_overlay_plus="Επικάλυψη λεξικού +{count}",
        lexicon_empty="Δεν υπάρχουν δέλτα επικάλυψης λεξικού.", govern_seed="Σπόρος διακυβέρνησης",
        govern_empty="Οι σπόροι ασφαλείας έρχονται με κάθε πακέτο. Ανενεργό γράφει παράκαμψη σπιτιού· το μεταγλωττισμένο δάπεδο μένει ενεργό.",
        match_catalog="Μεταγλωττισμένοι ταιριαστές", match_read_only="Η ελλείπουσα γραμμή χρησιμοποιεί την προεπιλογή της μηχανής. Άδεια επικάλυψη είναι η σημερινή λίστα υποψηφίων.",
        match_enabled="Ενεργό", match_disabled="Ανενεργό", match_precedence="Προτεραιότητα",
        match_disable_warning="Η απενεργοποίηση area_command ή all_lights αλλάζει εντολές δωματίου και όλου του σπιτιού.",
        lexicon_path="Διαδρομή συνόλου", lexicon_token="Διακριτικό", lexicon_add="Προσθήκη", lexicon_remove="Αφαίρεση",
        origin_engine="μηχανή", origin_operator="χειριστής", origin_seed="σπόρος", origin_trainer="εκπαιδευτής",
        compiled_floor="μεταγλωττισμένο δάπεδο", seed_on="Ενεργό", seed_off="Ανενεργό",
    ),
    "hy": lane(
        process_path="Ճանապարհ", path_match="Համընկնում", path_seed="Սերմ", path_house="Տուն", path_band="Գոտի",
        lane_match="Համընկնում", lane_match_engine="Համընկնում (շարժիչ)", lane_language="Լեզու", lane_house="Տուն", lane_tabs="Գծեր",
        lexicon_overlay="Բառարանի ծածկ", lexicon_overlay_plus="Բառարանի ծածկ +{count}",
        lexicon_empty="Բառարանի ծածկի դելտաներ չկան։", govern_seed="Կառավարման սերմ",
        govern_empty="Անվտանգության սերմերը գալիս են յուրաքանչյուր փաթեթով։ Անջատվածը գրում է տան վերագրում; կազմված հատակը մնում է միացված։",
        match_catalog="Կազմված համընկնողներ", match_read_only="Բացակա տողը վերցնում է շարժիչի լռելյայնը։ Դատարկ ծածկը այսօրվա թեկնածուների ցանկն է։",
        match_enabled="Միաց", match_disabled="Անջ", match_precedence="Առաջնություն",
        match_disable_warning="area_command կամ all_lights անջատելը փոխում է սենյակի և ամբողջ տան հրամանները։",
        lexicon_path="Հավաքածուի ճանապարհ", lexicon_token="Նշան", lexicon_add="Ավելացնել", lexicon_remove="Հանել",
        origin_engine="շարժիչ", origin_operator="օպերատոր", origin_seed="սերմ", origin_trainer="մարզիչ",
        compiled_floor="կազմված հատակ", seed_on="Միաց", seed_off="Անջ",
    ),
    "ka": lane(
        process_path="გზა", path_match="დამთხვევა", path_seed="თესლი", path_house="სახლი", path_band="ზოლი",
        lane_match="დამთხვევა", lane_match_engine="დამთხვევა (ძრავა)", lane_language="ენა", lane_house="სახლი", lane_tabs="ზოლები",
        lexicon_overlay="ლექსიკონის ფენა", lexicon_overlay_plus="ლექსიკონის ფენა +{count}",
        lexicon_empty="ლექსიკონის ფენის დელტა არ არის.", govern_seed="მმართველობის თესლი",
        govern_empty="უსაფრთხოების თესლები ყოველ პაკეტთან მოდის. გამორთვა წერს სახლის გადაწერას; კომპილირებული იატაკი ჩართული რჩება.",
        match_catalog="კომპილირებული დამთხვევები", match_read_only="აკლებული სტრიქონი იღებს ძრავის ნაგულისხმევს. ცარიელი ფენა დღევანდელი კანდიდატების სიაა.",
        match_enabled="ჩართ", match_disabled="გამორთ", match_precedence="პრიორიტეტი",
        match_disable_warning="area_command ან all_lights გამორთვა ცვლის ოთახისა და მთელი სახლის ბრძანებებს.",
        lexicon_path="ნაკრების გზა", lexicon_token="ჟეტონი", lexicon_add="დამატება", lexicon_remove="წაშლა",
        origin_engine="ძრავა", origin_operator="ოპერატორი", origin_seed="თესლი", origin_trainer="მწვრთნელი",
        compiled_floor="კომპილირებული იატაკი", seed_on="ჩართ", seed_off="გამორთ",
    ),
    "hi": lane(
        process_path="पथ", path_match="मेल", path_seed="बीज", path_house="घर", path_band="पट्टी",
        lane_match="मेल", lane_match_engine="मेल (इंजन)", lane_language="भाषा", lane_house="घर", lane_tabs="लेन",
        lexicon_overlay="शब्दकोश ओवरले", lexicon_overlay_plus="शब्दकोश ओवरले +{count}",
        lexicon_empty="शब्दकोश ओवरले डेल्टा नहीं हैं।", govern_seed="शासन बीज",
        govern_empty="सुरक्षा बीज हर पैक के साथ आते हैं। बंद घर ओवरराइड लिखता है; संकलित फ़र्श चालू रहता है।",
        match_catalog="संकलित मैचर", match_read_only="गायब पंक्ति इंजन डिफ़ॉल्ट लेती है। खाली ओवरले आज की उम्मीदवार सूची है।",
        match_enabled="चालू", match_disabled="बंद", match_precedence="प्राथमिकता",
        match_disable_warning="area_command या all_lights बंद करने से कमरे और पूरे घर के आदेश बदलते हैं।",
        lexicon_path="सेट पथ", lexicon_token="टोकन", lexicon_add="जोड़ें", lexicon_remove="हटाएँ",
        origin_engine="इंजन", origin_operator="संचालक", origin_seed="बीज", origin_trainer="प्रशिक्षक",
        compiled_floor="संकलित फ़र्श", seed_on="चालू", seed_off="बंद",
    ),
    "bn": lane(
        process_path="পথ", path_match="মিল", path_seed="বীজ", path_house="বাড়ি", path_band="ব্যান্ড",
        lane_match="মিল", lane_match_engine="মিল (ইঞ্জিন)", lane_language="ভাষা", lane_house="বাড়ি", lane_tabs="লেন",
        lexicon_overlay="অভিধান ওভারলে", lexicon_overlay_plus="অভিধান ওভারলে +{count}",
        lexicon_empty="অভিধান ওভারলে ডেল্টা নেই।", govern_seed="শাসন বীজ",
        govern_empty="নিরাপত্তা বীজ প্রতি প্যাকের সঙ্গে আসে। বন্ধ বাড়ির ওভাররাইড লেখে; কম্পাইল করা মেঝে চালু থাকে।",
        match_catalog="কম্পাইল করা ম্যাচার", match_read_only="অনুপস্থিত সারি ইঞ্জিন ডিফল্ট নেয়। খালি ওভারলে আজকের প্রার্থী তালিকা।",
        match_enabled="চালু", match_disabled="বন্ধ", match_precedence="অগ্রাধিকার",
        match_disable_warning="area_command বা all_lights বন্ধ করলে ঘর ও পুরো বাড়ির নির্দেশ বদলায়।",
        lexicon_path="সেট পথ", lexicon_token="টোকেন", lexicon_add="যোগ", lexicon_remove="সরান",
        origin_engine="ইঞ্জিন", origin_operator="অপারেটর", origin_seed="বীজ", origin_trainer="প্রশিক্ষক",
        compiled_floor="কম্পাইল করা মেঝে", seed_on="চালু", seed_off="বন্ধ",
    ),
    "gu": lane(
        process_path="પથ", path_match="મેળ", path_seed="બીજ", path_house="ઘર", path_band="પટ્ટી",
        lane_match="મેળ", lane_match_engine="મેળ (એન્જિન)", lane_language="ભાષા", lane_house="ઘર", lane_tabs="લેન",
        lexicon_overlay="શબ્દકોશ ઓવરલે", lexicon_overlay_plus="શબ્દકોશ ઓવરલે +{count}",
        lexicon_empty="શબ્દકોશ ઓવરલે ડેલ્ટા નથી.", govern_seed="શાસન બીજ",
        govern_empty="સુરક્ષા બીજ દરેક પેક સાથે આવે છે. બંધ ઘર ઓવરરાઇડ લખે છે; કમ્પાઇલ થયેલ ફર્શ ચાલુ રહે છે.",
        match_catalog="કમ્પાઇલ થયેલ મેચર", match_read_only="ગાયબ પંક્તિ એન્જિન ડિફોલ્ટ લે છે. ખાલી ઓવરલે આજની ઉમેદવાર યાદી છે.",
        match_enabled="ચાલુ", match_disabled="બંધ", match_precedence="પ્રાથમિકતા",
        match_disable_warning="area_command અથવા all_lights બંધ કરવાથી રૂમ અને આખા ઘરના આદેશ બદલાય છે.",
        lexicon_path="સેટ પથ", lexicon_token="ટોકન", lexicon_add="ઉમેરો", lexicon_remove="કાઢો",
        origin_engine="એન્જિન", origin_operator="ઓપરેટર", origin_seed="બીજ", origin_trainer="તાલીમકાર",
        compiled_floor="કમ્પાઇલ થયેલ ફર્શ", seed_on="ચાલુ", seed_off="બંધ",
    ),
    "kn": lane(
        process_path="ಮಾರ್ಗ", path_match="ಹೊಂದಾಣಿಕೆ", path_seed="ಬೀಜ", path_house="ಮನೆ", path_band="ಪಟ್ಟಿ",
        lane_match="ಹೊಂದಾಣಿಕೆ", lane_match_engine="ಹೊಂದಾಣಿಕೆ (ಎಂಜಿನ್)", lane_language="ಭಾಷೆ", lane_house="ಮನೆ", lane_tabs="ಲೇನ್‌ಗಳು",
        lexicon_overlay="ಶಬ್ದಕೋಶ ಓವರ್‌ಲೇ", lexicon_overlay_plus="ಶಬ್ದಕೋಶ ಓವರ್‌ಲೇ +{count}",
        lexicon_empty="ಶಬ್ದಕೋಶ ಓವರ್‌ಲೇ ಡೆಲ್ಟಾ ಇಲ್ಲ.", govern_seed="ಆಡಳಿತ ಬೀಜ",
        govern_empty="ಸುರಕ್ಷತೆ ಬೀಜಗಳು ಪ್ರತಿ ಪ್ಯಾಕ್‌ನೊಂದಿಗೆ ಬರುತ್ತವೆ. ಆಫ್ ಮನೆ ಓವರ್‌ರೈಟ್ ಬರೆಯುತ್ತದೆ; ಕಂಪೈಲ್ ಆದ ನೆಲ ಆನ್ ಉಳಿಯುತ್ತದೆ.",
        match_catalog="ಕಂಪೈಲ್ ಆದ ಮ್ಯಾಚರ್‌ಗಳು", match_read_only="ಕಾಣೆಯಾದ ಸಾಲು ಎಂಜಿನ್ ಡೀಫಾಲ್ಟ್ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ. ಖಾಲಿ ಓವರ್‌ಲೇ ಇಂದಿನ ಅಭ್ಯರ್ಥಿ ಪಟ್ಟಿ.",
        match_enabled="ಆನ್", match_disabled="ಆಫ್", match_precedence="ಆದ್ಯತೆ",
        match_disable_warning="area_command ಅಥವಾ all_lights ಆಫ್ ಮಾಡಿದರೆ ಕೋಣೆ ಮತ್ತು ಮನೆ ಆಜ್ಞೆಗಳು ಬದಲಾಗುತ್ತವೆ.",
        lexicon_path="ಸೆಟ್ ಮಾರ್ಗ", lexicon_token="ಟೋಕನ್", lexicon_add="ಸೇರಿಸಿ", lexicon_remove="ತೆಗೆದುಹಾಕಿ",
        origin_engine="ಎಂಜಿನ್", origin_operator="ಆಪರೇಟರ್", origin_seed="ಬೀಜ", origin_trainer="ತರಬೇತುದಾರ",
        compiled_floor="ಕಂಪೈಲ್ ಆದ ನೆಲ", seed_on="ಆನ್", seed_off="ಆಫ್",
    ),
    "ml": lane(
        process_path="പാത", path_match="പൊരുത്തം", path_seed="വിത്ത്", path_house="വീട്", path_band="ബാൻഡ്",
        lane_match="പൊരുത്തം", lane_match_engine="പൊരുത്തം (എഞ്ചിൻ)", lane_language="ഭാഷ", lane_house="വീട്", lane_tabs="ലെയിനുകൾ",
        lexicon_overlay="നിഘണ്ടു ഓവർലേ", lexicon_overlay_plus="നിഘണ്ടു ഓവർലേ +{count}",
        lexicon_empty="നിഘണ്ടു ഓവർലേ ഡെൽറ്റയില്ല.", govern_seed="ഭരണ വിത്ത്",
        govern_empty="സുരക്ഷാ വിത്തുകൾ ഓരോ പായ്ക്കിനോടും വരുന്നു. ഓഫ് വീട് ഓവർറൈറ്റ് എഴുതുന്നു; കംപൈൽ ചെയ്ത തറ ഓണായി നിൽക്കും.",
        match_catalog="കംപൈൽ ചെയ്ത മാച്ചറുകൾ", match_read_only="വിട്ടുപോയ വരി എഞ്ചിൻ ഡിഫോൾട്ട് എടുക്കുന്നു. ശൂന്യ ഓവർലേ ഇന്നത്തെ സ്ഥാനാർഥി പട്ടികയാണ്.",
        match_enabled="ഓൺ", match_disabled="ഓഫ്", match_precedence="മുൻഗണന",
        match_disable_warning="area_command അല്ലെങ്കിൽ all_lights ഓഫാക്കിയാൽ മുറിയുടെയും വീടാകെയുള്ള കൽപ്പനകൾ മാറും.",
        lexicon_path="സെറ്റ് പാത", lexicon_token="ടോക്കൺ", lexicon_add="ചേർക്കുക", lexicon_remove="നീക്കം",
        origin_engine="എഞ്ചിൻ", origin_operator="ഓപ്പറേറ്റർ", origin_seed="വിത്ത്", origin_trainer="പരിശീലകൻ",
        compiled_floor="കംപൈൽ ചെയ്ത തറ", seed_on="ഓൺ", seed_off="ഓഫ്",
    ),
    "mr": lane(
        process_path="मार्ग", path_match="जुळणी", path_seed="बी", path_house="घर", path_band="पट्टी",
        lane_match="जुळणी", lane_match_engine="जुळणी (इंजिन)", lane_language="भाषा", lane_house="घर", lane_tabs="लेन",
        lexicon_overlay="शब्दकोश ओव्हरले", lexicon_overlay_plus="शब्दकोश ओव्हरले +{count}",
        lexicon_empty="शब्दकोश ओव्हरले डेल्टा नाहीत.", govern_seed="शासन बी",
        govern_empty="सुरक्षा बी प्रत्येक पॅकसोबत येतात. बंद घर ओव्हराइड लिहितो; संकलित फरशी सुरू राहते.",
        match_catalog="संकलित मॅचर", match_read_only="गहाळ ओळ इंजिन डीफॉल्ट घेते. रिकामे ओव्हरले आजची उमेदवार यादी आहे.",
        match_enabled="सुरू", match_disabled="बंद", match_precedence="प्राधान्य",
        match_disable_warning="area_command किंवा all_lights बंद केल्याने खोली व संपूर्ण घराचे आदेश बदलतात.",
        lexicon_path="सेट मार्ग", lexicon_token="टोकन", lexicon_add="जोडा", lexicon_remove="काढा",
        origin_engine="इंजिन", origin_operator="ऑपरेटर", origin_seed="बी", origin_trainer="प्रशिक्षक",
        compiled_floor="संकलित फरशी", seed_on="सुरू", seed_off="बंद",
    ),
    "ta": lane(
        process_path="பாதை", path_match="பொருத்தம்", path_seed="விதை", path_house="வீடு", path_band="பட்டை",
        lane_match="பொருத்தம்", lane_match_engine="பொருத்தம் (இயந்திரம்)", lane_language="மொழி", lane_house="வீடு", lane_tabs="தடங்கள்",
        lexicon_overlay="அகராதி மேலடுக்கு", lexicon_overlay_plus="அகராதி மேலடுக்கு +{count}",
        lexicon_empty="அகராதி மேலடுக்கு டெல்டா இல்லை.", govern_seed="ஆட்சி விதை",
        govern_empty="பாதுகாப்பு விதைகள் ஒவ்வொரு தொகுப்புடனும் வரும். அணைத்தால் வீட்டு மேலெழுத்து எழுதும்; தொகுக்கப்பட்ட தளம் இயங்கிக்கொண்டே இருக்கும்.",
        match_catalog="தொகுக்கப்பட்ட பொருத்திகள்", match_read_only="காணாத வரி இயந்திர இயல்பைப் பயன்படுத்தும். வெற்று மேலடுக்கு இன்றைய வேட்பாளர் பட்டியல்.",
        match_enabled="இயக்கு", match_disabled="அணை", match_precedence="முன்னுரிமை",
        match_disable_warning="area_command அல்லது all_lights அணைத்தால் அறை மற்றும் முழு வீட்டு கட்டளைகள் மாறும்.",
        lexicon_path="தொகுப்பு பாதை", lexicon_token="டோக்கன்", lexicon_add="சேர்", lexicon_remove="அகற்று",
        origin_engine="இயந்திரம்", origin_operator="இயக்குபவர்", origin_seed="விதை", origin_trainer="பயிற்றுனர்",
        compiled_floor="தொகுக்கப்பட்ட தளம்", seed_on="இயக்கு", seed_off="அணை",
    ),
    "te": lane(
        process_path="మార్గం", path_match="సరిపోలిక", path_seed="విత్తనం", path_house="ఇల్లు", path_band="బ్యాండ్",
        lane_match="సరిపోలిక", lane_match_engine="సరిపోలిక (ఇంజిన్)", lane_language="భాష", lane_house="ఇల్లు", lane_tabs="లేన్లు",
        lexicon_overlay="నిఘంటువు ఓవర్‌లే", lexicon_overlay_plus="నిఘంటువు ఓవర్‌లే +{count}",
        lexicon_empty="నిఘంటువు ఓవర్‌లే డెల్టాలు లేవు.", govern_seed="పాలన విత్తనం",
        govern_empty="భద్రతా విత్తనాలు ప్రతి ప్యాక్‌తో వస్తాయి. ఆఫ్ ఇంటి ఓవర్‌రైట్ రాస్తుంది; కంపైల్ అయిన నేల ఆన్‌లో ఉంటుంది.",
        match_catalog="కంపైల్ అయిన మ్యాచర్లు", match_read_only="లేని వరుస ఇంజిన్ డిఫాల్ట్ తీసుకుంటుంది. ఖాళీ ఓవర్‌లే నేటి అభ్యర్థుల జాబితా.",
        match_enabled="ఆన్", match_disabled="ఆఫ్", match_precedence="ప్రాధాన్యం",
        match_disable_warning="area_command లేదా all_lights ఆఫ్ చేస్తే గది మరియు ఇల్లంతా ఆదేశాలు మారతాయి.",
        lexicon_path="సెట్ మార్గం", lexicon_token="టోకెన్", lexicon_add="జోడించు", lexicon_remove="తీసివేయి",
        origin_engine="ఇంజిన్", origin_operator="ఆపరేటర్", origin_seed="విత్తనం", origin_trainer="శిక్షకుడు",
        compiled_floor="కంపైల్ అయిన నేల", seed_on="ఆన్", seed_off="ఆఫ్",
    ),
    "pa": lane(
        process_path="ਰਾਹ", path_match="ਮੇਲ", path_seed="ਬੀਜ", path_house="ਘਰ", path_band="ਪੱਟੀ",
        lane_match="ਮੇਲ", lane_match_engine="ਮੇਲ (ਇੰਜਣ)", lane_language="ਭਾਸ਼ਾ", lane_house="ਘਰ", lane_tabs="ਲੇਨ",
        lexicon_overlay="ਸ਼ਬਦਕੋਸ਼ ਓਵਰਲੇ", lexicon_overlay_plus="ਸ਼ਬਦਕੋਸ਼ ਓਵਰਲੇ +{count}",
        lexicon_empty="ਸ਼ਬਦਕੋਸ਼ ਓਵਰਲੇ ਡੈਲਟਾ ਨਹੀਂ।", govern_seed="ਸ਼ਾਸਨ ਬੀਜ",
        govern_empty="ਸੁਰੱਖਿਆ ਬੀਜ ਹਰ ਪੈਕ ਨਾਲ ਆਉਂਦੇ ਹਨ। ਬੰਦ ਘਰ ਓਵਰਰਾਈਡ ਲਿਖਦਾ ਹੈ; ਕੰਪਾਈਲ ਫਰਸ਼ ਚਾਲੂ ਰਹਿੰਦਾ ਹੈ।",
        match_catalog="ਕੰਪਾਈਲ ਮੈਚਰ", match_read_only="ਗੁੰਮ ਕਤਾਰ ਇੰਜਣ ਡਿਫਾਲਟ ਲੈਂਦੀ ਹੈ। ਖਾਲੀ ਓਵਰਲੇ ਅੱਜ ਦੀ ਉਮੀਦਵਾਰ ਸੂਚੀ ਹੈ।",
        match_enabled="ਚਾਲੂ", match_disabled="ਬੰਦ", match_precedence="ਤਰਜੀਹ",
        match_disable_warning="area_command ਜਾਂ all_lights ਬੰਦ ਕਰਨ ਨਾਲ ਕਮਰੇ ਤੇ ਸਾਰੇ ਘਰ ਦੇ ਹੁਕਮ ਬਦਲਦੇ ਹਨ।",
        lexicon_path="ਸੈੱਟ ਰਾਹ", lexicon_token="ਟੋਕਨ", lexicon_add="ਜੋੜੋ", lexicon_remove="ਹਟਾਓ",
        origin_engine="ਇੰਜਣ", origin_operator="ਆਪਰੇਟਰ", origin_seed="ਬੀਜ", origin_trainer="ਟਰੇਨਰ",
        compiled_floor="ਕੰਪਾਈਲ ਫਰਸ਼", seed_on="ਚਾਲੂ", seed_off="ਬੰਦ",
    ),
    "ne": lane(
        process_path="बाटो", path_match="मिल्नु", path_seed="बीउ", path_house="घर", path_band="पट्टी",
        lane_match="मिल्नु", lane_match_engine="मिल्नु (इन्जिन)", lane_language="भाषा", lane_house="घर", lane_tabs="लेन",
        lexicon_overlay="शब्दकोश ओभरले", lexicon_overlay_plus="शब्दकोश ओभरले +{count}",
        lexicon_empty="शब्दकोश ओभरले डेल्टा छैनन्।", govern_seed="शासन बीउ",
        govern_empty="सुरक्षा बीउ हरेक प्याकसाथ आउँछन्। बन्द घर ओभरराइड लेख्छ; कम्पाइल भुइँ अन रहन्छ।",
        match_catalog="कम्पाइल भएका म्याचर", match_read_only="हराएको पङ्क्ति इन्जिन डिफल्ट लिन्छ। खाली ओभरले आजको उम्मेदवार सूची हो।",
        match_enabled="अन", match_disabled="अफ", match_precedence="प्राथमिकता",
        match_disable_warning="area_command वा all_lights बन्द गर्दा कोठा र पूरै घरका आदेश बदलिन्छन्।",
        lexicon_path="सेट बाटो", lexicon_token="टोकन", lexicon_add="थप्नुहोस्", lexicon_remove="हटाउनुहोस्",
        origin_engine="इन्जिन", origin_operator="अपरेटर", origin_seed="बीउ", origin_trainer="प्रशिक्षक",
        compiled_floor="कम्पाइल भुइँ", seed_on="अन", seed_off="अफ",
    ),
    "sw": lane(
        process_path="Njia", path_match="Linganisha", path_seed="Mbegu", path_house="Nyumba", path_band="Bendi",
        lane_match="Linganisha", lane_match_engine="Linganisha (injini)", lane_language="Lugha", lane_house="Nyumba", lane_tabs="Njia",
        lexicon_overlay="Kifuniko cha kamusi", lexicon_overlay_plus="Kifuniko cha kamusi +{count}",
        lexicon_empty="Hakuna delta za kifuniko cha kamusi.", govern_seed="Mbegu ya utawala",
        govern_empty="Mbegu za usalama huja na kila pakiti. Zima huandika kubatilisha nyumba; sakafu iliyokusanywa inabaki washa.",
        match_catalog="Vilinganishi vilivyokusanywa", match_read_only="Safu inayokosa hutumia chaguo-msingi la injini. Kifuniko tupu ni orodha ya wagombea leo.",
        match_enabled="Washa", match_disabled="Zima", match_precedence="Kipaumbele",
        match_disable_warning="Kuzima area_command au all_lights hubadilisha amri za chumba na nyumba nzima.",
        lexicon_path="Njia ya seti", lexicon_token="Tokeni", lexicon_add="Ongeza", lexicon_remove="Ondoa",
        origin_engine="injini", origin_operator="opereta", origin_seed="mbegu", origin_trainer="mkufunzi",
        compiled_floor="sakafu iliyokusanywa", seed_on="Washa", seed_off="Zima",
    ),
}
