"""Lane chrome for East European and Asian Assist locales."""

from __future__ import annotations

from lang_packs.lanes import lane

PACKS: dict[str, dict[str, str]] = {
    "cs": lane(
        process_path="Cesta", path_match="Match", path_seed="Seed", path_house="Dům", path_band="Pásmo",
        lane_match="Match", lane_match_engine="Match (engine)", lane_language="Jazyk", lane_house="Dům", lane_tabs="Dráhy",
        lexicon_overlay="Lexikon overlay", lexicon_overlay_plus="Lexikon overlay +{count}",
        lexicon_empty="Žádné delty lexikon overlay.", govern_seed="Govern seed",
        govern_empty="Bezpečnostní seedy jsou u každého packu. Vypnuto zapíše přepis domu; zkompilovaná podlaha zůstane zapnutá.",
        match_catalog="Zkompilované matchery", match_read_only="Chybějící řádek použije výchozí engine. Prázdný overlay je dnešní seznam kandidátů.",
        match_enabled="Zap", match_disabled="Vyp", match_precedence="Přednost",
        match_disable_warning="Vypnutí area_command nebo all_lights změní příkazy v místnosti i v celém domě.",
        lexicon_path="Cesta sady", lexicon_token="Token", lexicon_add="Přidat", lexicon_remove="Odebrat",
        origin_engine="engine", origin_operator="operátor", origin_seed="seed", origin_trainer="trenér",
        compiled_floor="zkompilovaná podlaha", seed_on="Zap", seed_off="Vyp",
    ),
    "sk": lane(
        process_path="Cesta", path_match="Match", path_seed="Seed", path_house="Dom", path_band="Pásmo",
        lane_match="Match", lane_match_engine="Match (engine)", lane_language="Jazyk", lane_house="Dom", lane_tabs="Dráhy",
        lexicon_overlay="Lexikón overlay", lexicon_overlay_plus="Lexikón overlay +{count}",
        lexicon_empty="Žiadne delty lexikón overlay.", govern_seed="Govern seed",
        govern_empty="Bezpečnostné seedy sú pri každom packu. Vypnuté zapíše prepis domu; skompilovaná podlaha ostane zapnutá.",
        match_catalog="Skompilované matchery", match_read_only="Chýbajúci riadok použije predvolené engine. Prázdny overlay je dnešný zoznam kandidátov.",
        match_enabled="Zap", match_disabled="Vyp", match_precedence="Prednosť",
        match_disable_warning="Vypnutie area_command alebo all_lights zmení príkazy v miestnosti aj v celom dome.",
        lexicon_path="Cesta sady", lexicon_token="Token", lexicon_add="Pridať", lexicon_remove="Odstrániť",
        origin_engine="engine", origin_operator="operátor", origin_seed="seed", origin_trainer="tréner",
        compiled_floor="skompiovaná podlaha", seed_on="Zap", seed_off="Vyp",
    ),
    "pl": lane(
        process_path="Ścieżka", path_match="Match", path_seed="Seed", path_house="Dom", path_band="Pasmo",
        lane_match="Match", lane_match_engine="Match (silnik)", lane_language="Język", lane_house="Dom", lane_tabs="Tory",
        lexicon_overlay="Nakładka leksykonu", lexicon_overlay_plus="Nakładka leksykonu +{count}",
        lexicon_empty="Brak delt nakładki leksykonu.", govern_seed="Seed ładu",
        govern_empty="Seedy bezpieczeństwa są w każdym packu. Wyłączone zapisuje nadpis domu; skompilowana podłoga zostaje włączona.",
        match_catalog="Skompilowane matchery", match_read_only="Brakujący wiersz używa domyślnego silnika. Pusta nakładka to dzisiejsza lista kandydatów.",
        match_enabled="Wł", match_disabled="Wył", match_precedence="Pierwszeństwo",
        match_disable_warning="Wyłączenie area_command lub all_lights zmienia polecenia w pokoju i w całym domu.",
        lexicon_path="Ścieżka zestawu", lexicon_token="Token", lexicon_add="Dodaj", lexicon_remove="Usuń",
        origin_engine="silnik", origin_operator="operator", origin_seed="seed", origin_trainer="trener",
        compiled_floor="skompiowana podłoga", seed_on="Wł", seed_off="Wył",
    ),
    "hu": lane(
        process_path="Útvonal", path_match="Match", path_seed="Seed", path_house="Ház", path_band="Sáv",
        lane_match="Match", lane_match_engine="Match (motor)", lane_language="Nyelv", lane_house="Ház", lane_tabs="Sávok",
        lexicon_overlay="Lexikon-overlay", lexicon_overlay_plus="Lexikon-overlay +{count}",
        lexicon_empty="Nincs lexikon-overlay delta.", govern_seed="Govern seed",
        govern_empty="A biztonsági seedek minden packkel jönnek. Ki házfelülírást ír; a fordított padló bekapcsolva marad.",
        match_catalog="Fordított matcherek", match_read_only="Hiányzó sor a motor alapértelmezettjét használja. Üres overlay a mai jelöltlista.",
        match_enabled="Be", match_disabled="Ki", match_precedence="Elsőbbség",
        match_disable_warning="Az area_command vagy all_lights kikapcsolása a szoba- és házszintű parancsokat változtatja.",
        lexicon_path="Készlet útvonal", lexicon_token="Token", lexicon_add="Hozzáad", lexicon_remove="Eltávolít",
        origin_engine="motor", origin_operator="operátor", origin_seed="seed", origin_trainer="edző",
        compiled_floor="fordított padló", seed_on="Be", seed_off="Ki",
    ),
    "hr": lane(
        process_path="Put", path_match="Match", path_seed="Seed", path_house="Kuća", path_band="Pojas",
        lane_match="Match", lane_match_engine="Match (engine)", lane_language="Jezik", lane_house="Kuća", lane_tabs="Trake",
        lexicon_overlay="Leksikon overlay", lexicon_overlay_plus="Leksikon overlay +{count}",
        lexicon_empty="Nema delti leksikon overlaya.", govern_seed="Govern seed",
        govern_empty="Sigurnosni seedovi dolaze uz svaki pack. Isključeno piše kućni override; kompilirani pod ostaje uključen.",
        match_catalog="Kompilirani matcheri", match_read_only="Nedostajući red koristi zadano enginea. Prazan overlay je današnji popis kandidata.",
        match_enabled="Uklj", match_disabled="Isklj", match_precedence="Prednost",
        match_disable_warning="Isključivanje area_command ili all_lights mijenja naredbe u sobi i cijeloj kući.",
        lexicon_path="Put skupa", lexicon_token="Token", lexicon_add="Dodaj", lexicon_remove="Ukloni",
        origin_engine="engine", origin_operator="operator", origin_seed="seed", origin_trainer="trener",
        compiled_floor="kompilirani pod", seed_on="Uklj", seed_off="Isklj",
    ),
    "sl": lane(
        process_path="Pot", path_match="Match", path_seed="Seed", path_house="Hiša", path_band="Pas",
        lane_match="Match", lane_match_engine="Match (poganj)", lane_language="Jezik", lane_house="Hiša", lane_tabs="Steze",
        lexicon_overlay="Leksikon overlay", lexicon_overlay_plus="Leksikon overlay +{count}",
        lexicon_empty="Ni delte leksikon overlaya.", govern_seed="Govern seed",
        govern_empty="Varnostni seedi pridejo z vsakim packom. Izklop zapiše hišni override; prevedena tla ostanejo vklopljena.",
        match_catalog="Prevedeni matcherji", match_read_only="Manjkajoča vrstica uporabi privzeto pogona. Prazen overlay je današnji seznam kandidatov.",
        match_enabled="Vkl", match_disabled="Izk", match_precedence="Prednost",
        match_disable_warning="Izklop area_command ali all_lights spremeni ukaze v sobi in po celi hiši.",
        lexicon_path="Pot nabora", lexicon_token="Žeton", lexicon_add="Dodaj", lexicon_remove="Odstrani",
        origin_engine="pogon", origin_operator="operater", origin_seed="seed", origin_trainer="trener",
        compiled_floor="prevedena tla", seed_on="Vkl", seed_off="Izk",
    ),
    "bg": lane(
        process_path="Път", path_match="Match", path_seed="Seed", path_house="Дом", path_band="Лента",
        lane_match="Match", lane_match_engine="Match (двигател)", lane_language="Език", lane_house="Дом", lane_tabs="Ленти",
        lexicon_overlay="Лексикон overlay", lexicon_overlay_plus="Лексикон overlay +{count}",
        lexicon_empty="Няма делти на лексикон overlay.", govern_seed="Govern seed",
        govern_empty="Предпазните seed-ове идват с всеки pack. Изключено записва домашен override; компилираният под остава включен.",
        match_catalog="Компилирани matcher-и", match_read_only="Липсващ ред ползва подразбирането на двигателя. Празен overlay е днешният списък с кандидати.",
        match_enabled="Вкл", match_disabled="Изкл", match_precedence="Предимство",
        match_disable_warning="Изключването на area_command или all_lights променя командите в стаята и в целия дом.",
        lexicon_path="Път на набора", lexicon_token="Токен", lexicon_add="Добави", lexicon_remove="Премахни",
        origin_engine="двигател", origin_operator="оператор", origin_seed="seed", origin_trainer="треньор",
        compiled_floor="компилиран под", seed_on="Вкл", seed_off="Изкл",
    ),
    "sr": lane(
        process_path="Пут", path_match="Match", path_seed="Seed", path_house="Кућа", path_band="Појас",
        lane_match="Match", lane_match_engine="Match (енџин)", lane_language="Језик", lane_house="Кућа", lane_tabs="Траке",
        lexicon_overlay="Лексикон overlay", lexicon_overlay_plus="Лексикон overlay +{count}",
        lexicon_empty="Нема делти лексикон overlay-а.", govern_seed="Govern seed",
        govern_empty="Сигурносни seed-ови долазе уз сваки pack. Искључено уписује кућни override; компајлирани под остаје укључен.",
        match_catalog="Компајлирани matcher-и", match_read_only="Недостајући ред користи подразумевано енџина. Празан overlay је данашња листа кандидата.",
        match_enabled="Укљ", match_disabled="Искљ", match_precedence="Предност",
        match_disable_warning="Искључивање area_command или all_lights мења наредбе у соби и целој кући.",
        lexicon_path="Пут скупа", lexicon_token="Токен", lexicon_add="Додај", lexicon_remove="Уклони",
        origin_engine="енџин", origin_operator="оператор", origin_seed="seed", origin_trainer="тренер",
        compiled_floor="компајлирани под", seed_on="Укљ", seed_off="Искљ",
    ),
    "sr-Latn": lane(
        process_path="Put", path_match="Match", path_seed="Seed", path_house="Kuća", path_band="Pojas",
        lane_match="Match", lane_match_engine="Match (engine)", lane_language="Jezik", lane_house="Kuća", lane_tabs="Trake",
        lexicon_overlay="Leksikon overlay", lexicon_overlay_plus="Leksikon overlay +{count}",
        lexicon_empty="Nema delti leksikon overlaya.", govern_seed="Govern seed",
        govern_empty="Sigurnosni seedovi dolaze uz svaki pack. Isključeno upisuje kućni override; kompajlirani pod ostaje uključen.",
        match_catalog="Kompajlirani matcheri", match_read_only="Nedostajući red koristi podrazumevano enginea. Prazan overlay je današnja lista kandidata.",
        match_enabled="Uklj", match_disabled="Isklj", match_precedence="Prednost",
        match_disable_warning="Isključivanje area_command ili all_lights menja naredbe u sobi i celoj kući.",
        lexicon_path="Put skupa", lexicon_token="Token", lexicon_add="Dodaj", lexicon_remove="Ukloni",
        origin_engine="engine", origin_operator="operator", origin_seed="seed", origin_trainer="trener",
        compiled_floor="kompajlirani pod", seed_on="Uklj", seed_off="Isklj",
    ),
    "uk": lane(
        process_path="Шлях", path_match="Match", path_seed="Seed", path_house="Дім", path_band="Смуга",
        lane_match="Match", lane_match_engine="Match (рушій)", lane_language="Мова", lane_house="Дім", lane_tabs="Смуги",
        lexicon_overlay="Оверлей лексикону", lexicon_overlay_plus="Оверлей лексикону +{count}",
        lexicon_empty="Немає дельт оверлею лексикону.", govern_seed="Govern seed",
        govern_empty="Насінини безпеки йдуть з кожним pack. Вимкнено записує перевизначення дому; скомпільована підлога лишається увімкненою.",
        match_catalog="Скомпільовані matcherи", match_read_only="Відсутній рядок бере типове значення рушія. Порожній оверлей — сьогоднішній список кандидатів.",
        match_enabled="Увімк", match_disabled="Вимк", match_precedence="Першість",
        match_disable_warning="Вимкнення area_command або all_lights змінює команди кімнати й усього дому.",
        lexicon_path="Шлях набору", lexicon_token="Токен", lexicon_add="Додати", lexicon_remove="Прибрати",
        origin_engine="рушій", origin_operator="оператор", origin_seed="seed", origin_trainer="тренер",
        compiled_floor="скомпільована підлога", seed_on="Увімк", seed_off="Вимк",
    ),
    "zh-CN": lane(
        process_path="路径", path_match="匹配", path_seed="种子", path_house="房屋", path_band="频段",
        lane_match="匹配", lane_match_engine="匹配（引擎）", lane_language="语言", lane_house="房屋", lane_tabs="车道",
        lexicon_overlay="词库覆盖", lexicon_overlay_plus="词库覆盖 +{count}",
        lexicon_empty="没有词库覆盖增量。", govern_seed="治理种子",
        govern_empty="每个语言包都带安全种子。关闭会写入房屋覆盖；编译下限仍保持开启。",
        match_catalog="已编译匹配器", match_read_only="缺行使用引擎默认。空覆盖就是今天的候选列表。",
        match_enabled="开", match_disabled="关", match_precedence="优先级",
        match_disable_warning="关闭 area_command 或 all_lights 会改变房间和全屋命令。",
        lexicon_path="集合路径", lexicon_token="词元", lexicon_add="添加", lexicon_remove="移除",
        origin_engine="引擎", origin_operator="操作员", origin_seed="种子", origin_trainer="训练器",
        compiled_floor="编译下限", seed_on="开", seed_off="关",
    ),
    "zh-TW": lane(
        process_path="路徑", path_match="匹配", path_seed="種子", path_house="房屋", path_band="頻段",
        lane_match="匹配", lane_match_engine="匹配（引擎）", lane_language="語言", lane_house="房屋", lane_tabs="車道",
        lexicon_overlay="詞庫覆蓋", lexicon_overlay_plus="詞庫覆蓋 +{count}",
        lexicon_empty="沒有詞庫覆蓋增量。", govern_seed="治理種子",
        govern_empty="每個語言包都帶安全種子。關閉會寫入房屋覆蓋；編譯下限仍保持開啟。",
        match_catalog="已編譯匹配器", match_read_only="缺列使用引擎預設。空覆蓋就是今天的候選清單。",
        match_enabled="開", match_disabled="關", match_precedence="優先順序",
        match_disable_warning="關閉 area_command 或 all_lights 會改變房間與全屋命令。",
        lexicon_path="集合路徑", lexicon_token="詞元", lexicon_add="新增", lexicon_remove="移除",
        origin_engine="引擎", origin_operator="操作員", origin_seed="種子", origin_trainer="訓練器",
        compiled_floor="編譯下限", seed_on="開", seed_off="關",
    ),
    "zh-HK": lane(
        process_path="路徑", path_match="匹配", path_seed="種子", path_house="房屋", path_band="頻段",
        lane_match="匹配", lane_match_engine="匹配（引擎）", lane_language="語言", lane_house="房屋", lane_tabs="車道",
        lexicon_overlay="詞庫覆蓋", lexicon_overlay_plus="詞庫覆蓋 +{count}",
        lexicon_empty="冇詞庫覆蓋增量。", govern_seed="治理種子",
        govern_empty="每個語言包都帶安全種子。關閉會寫入房屋覆蓋；編譯下限仍然開住。",
        match_catalog="已編譯匹配器", match_read_only="缺行用引擎預設。空覆蓋就係今日嘅候選清單。",
        match_enabled="開", match_disabled="關", match_precedence="優先",
        match_disable_warning="關閉 area_command 或 all_lights 會改房間同全屋指令。",
        lexicon_path="集合路徑", lexicon_token="詞元", lexicon_add="加", lexicon_remove="移除",
        origin_engine="引擎", origin_operator="操作員", origin_seed="種子", origin_trainer="訓練器",
        compiled_floor="編譯下限", seed_on="開", seed_off="關",
    ),
    "ja": lane(
        process_path="経路", path_match="マッチ", path_seed="シード", path_house="家", path_band="帯",
        lane_match="マッチ", lane_match_engine="マッチ（エンジン）", lane_language="言語", lane_house="家", lane_tabs="レーン",
        lexicon_overlay="語彙オーバーレイ", lexicon_overlay_plus="語彙オーバーレイ +{count}",
        lexicon_empty="語彙オーバーレイの差分はありません。", govern_seed="ガバナンスシード",
        govern_empty="安全シードは各パックに付きます。オフは家の上書きを書き、コンパイル下限はオンのままです。",
        match_catalog="コンパイル済みマッチャー", match_read_only="欠けた行はエンジン既定を使います。空のオーバーレイは今日の候補一覧です。",
        match_enabled="オン", match_disabled="オフ", match_precedence="優先",
        match_disable_warning="area_command や all_lights を切ると部屋と家全体の命令が変わります。",
        lexicon_path="セット経路", lexicon_token="トークン", lexicon_add="追加", lexicon_remove="削除",
        origin_engine="エンジン", origin_operator="オペレーター", origin_seed="シード", origin_trainer="トレーナー",
        compiled_floor="コンパイル下限", seed_on="オン", seed_off="オフ",
    ),
    "ko": lane(
        process_path="경로", path_match="매치", path_seed="시드", path_house="집", path_band="대역",
        lane_match="매치", lane_match_engine="매치(엔진)", lane_language="언어", lane_house="집", lane_tabs="레인",
        lexicon_overlay="어휘 오버레이", lexicon_overlay_plus="어휘 오버레이 +{count}",
        lexicon_empty="어휘 오버레이 차이가 없습니다.", govern_seed="거버넌스 시드",
        govern_empty="안전 시드는 모든 팩에 들어 있습니다. 끔은 집 덮어쓰기를 쓰고, 컴파일 하한은 켜진 채로 남습니다.",
        match_catalog="컴파일된 매처", match_read_only="없는 행은 엔진 기본값을 씁니다. 빈 오버레이가 오늘의 후보 목록입니다.",
        match_enabled="켜짐", match_disabled="꺼짐", match_precedence="우선",
        match_disable_warning="area_command 또는 all_lights를 끄면 방·집 전체 명령이 바뀝니다.",
        lexicon_path="세트 경로", lexicon_token="토큰", lexicon_add="추가", lexicon_remove="제거",
        origin_engine="엔진", origin_operator="운영자", origin_seed="시드", origin_trainer="트레이너",
        compiled_floor="컴파일 하한", seed_on="켜짐", seed_off="꺼짐",
    ),
    "th": lane(
        process_path="เส้นทาง", path_match="แมตช์", path_seed="ซีด", path_house="บ้าน", path_band="แถบ",
        lane_match="แมตช์", lane_match_engine="แมตช์ (เอนจิน)", lane_language="ภาษา", lane_house="บ้าน", lane_tabs="เลน",
        lexicon_overlay="โอเวอร์เลย์คำศัพท์", lexicon_overlay_plus="โอเวอร์เลย์คำศัพท์ +{count}",
        lexicon_empty="ไม่มีเดลตาโอเวอร์เลย์คำศัพท์", govern_seed="ซีดกำกับ",
        govern_empty="ซีดความปลอดภัยมากับทุกแพ็ก ปิดจะเขียนทับบ้าน พื้นที่คอมไพล์ยังเปิดอยู่",
        match_catalog="ตัวจับคู่ที่คอมไพล์แล้ว", match_read_only="แถวที่ขาดใช้ค่าเริ่มต้นของเอนจิน โอเวอร์เลย์ว่างคือรายชื่อผู้สมัครวันนี้",
        match_enabled="เปิด", match_disabled="ปิด", match_precedence="ลำดับก่อน",
        match_disable_warning="ปิด area_command หรือ all_lights จะเปลี่ยนคำสั่งทั้งห้องและทั้งบ้าน",
        lexicon_path="เส้นทางชุด", lexicon_token="โทเคน", lexicon_add="เพิ่ม", lexicon_remove="ลบ",
        origin_engine="เอนจิน", origin_operator="ผู้ปฏิบัติ", origin_seed="ซีด", origin_trainer="เทรนเนอร์",
        compiled_floor="พื้นคอมไพล์", seed_on="เปิด", seed_off="ปิด",
    ),
    "vi": lane(
        process_path="Đường", path_match="Khớp", path_seed="Hạt", path_house="Nhà", path_band="Dải",
        lane_match="Khớp", lane_match_engine="Khớp (engine)", lane_language="Ngôn ngữ", lane_house="Nhà", lane_tabs="Làn",
        lexicon_overlay="Lớp từ vựng", lexicon_overlay_plus="Lớp từ vựng +{count}",
        lexicon_empty="Không có delta lớp từ vựng.", govern_seed="Hạt quản trị",
        govern_empty="Hạt an toàn đi với mỗi gói. Tắt ghi đè nhà; sàn biên dịch vẫn bật.",
        match_catalog="Bộ khớp đã biên dịch", match_read_only="Hàng thiếu dùng mặc định engine. Overlay trống là danh sách ứng viên hôm nay.",
        match_enabled="Bật", match_disabled="Tắt", match_precedence="Ưu tiên",
        match_disable_warning="Tắt area_command hoặc all_lights đổi lệnh cả phòng và cả nhà.",
        lexicon_path="Đường tập", lexicon_token="Token", lexicon_add="Thêm", lexicon_remove="Gỡ",
        origin_engine="engine", origin_operator="vận hành", origin_seed="hạt", origin_trainer="huấn luyện",
        compiled_floor="sàn biên dịch", seed_on="Bật", seed_off="Tắt",
    ),
    "id": lane(
        process_path="Jalur", path_match="Cocok", path_seed="Benih", path_house="Rumah", path_band="Pita",
        lane_match="Cocok", lane_match_engine="Cocok (mesin)", lane_language="Bahasa", lane_house="Rumah", lane_tabs="Jalur",
        lexicon_overlay="Overlay leksikon", lexicon_overlay_plus="Overlay leksikon +{count}",
        lexicon_empty="Tidak ada delta overlay leksikon.", govern_seed="Benih tata kelola",
        govern_empty="Benih aman ikut setiap paket. Mati menulis override rumah; lantai terkompilasi tetap menyala.",
        match_catalog="Matcher terkompilasi", match_read_only="Baris hilang memakai bawaan mesin. Overlay kosong adalah daftar kandidat hari ini.",
        match_enabled="Nyala", match_disabled="Mati", match_precedence="Prioritas",
        match_disable_warning="Mematikan area_command atau all_lights mengubah perintah seisi ruangan dan rumah.",
        lexicon_path="Jalur set", lexicon_token="Token", lexicon_add="Tambah", lexicon_remove="Hapus",
        origin_engine="mesin", origin_operator="operator", origin_seed="benih", origin_trainer="pelatih",
        compiled_floor="lantai terkompilasi", seed_on="Nyala", seed_off="Mati",
    ),
    "ms": lane(
        process_path="Laluan", path_match="Padan", path_seed="Biji", path_house="Rumah", path_band="Jalur",
        lane_match="Padan", lane_match_engine="Padan (enjin)", lane_language="Bahasa", lane_house="Rumah", lane_tabs="Lorong",
        lexicon_overlay="Overlay leksikon", lexicon_overlay_plus="Overlay leksikon +{count}",
        lexicon_empty="Tiada delta overlay leksikon.", govern_seed="Biji tadbir",
        govern_empty="Biji keselamatan datang dengan setiap pek. Mati menulis override rumah; lantai dikompil kekal hidup.",
        match_catalog="Pemadan dikompil", match_read_only="Baris hilang guna lalai enjin. Overlay kosong ialah senarai calon hari ini.",
        match_enabled="Hidup", match_disabled="Mati", match_precedence="Keutamaan",
        match_disable_warning="Mematikan area_command atau all_lights mengubah arahan bilik dan seluruh rumah.",
        lexicon_path="Laluan set", lexicon_token="Token", lexicon_add="Tambah", lexicon_remove="Buang",
        origin_engine="enjin", origin_operator="pengendali", origin_seed="biji", origin_trainer="jurulatih",
        compiled_floor="lantai dikompil", seed_on="Hidup", seed_off="Mati",
    ),
    "mn": lane(
        process_path="Зам", path_match="Таарах", path_seed="Үр", path_house="Гэр", path_band="Тууз",
        lane_match="Таарах", lane_match_engine="Таарах (хөдөлгүүр)", lane_language="Хэл", lane_house="Гэр", lane_tabs="Зурвас",
        lexicon_overlay="Үгсийн overlay", lexicon_overlay_plus="Үгсийн overlay +{count}",
        lexicon_empty="Үгсийн overlay-ийн дельта байхгүй.", govern_seed="Засаглалын үр",
        govern_empty="Аюулгүй үр бүр pack-тай ирнэ. Унтраахад гэрийн override бичнэ; эмхэтгэсэн шал асаалттай үлдэнэ.",
        match_catalog="Эмхэтгэсэн matcher", match_read_only="Дутуу мөр хөдөлгүүрийн өгөгдмөлийг авна. Хоосон overlay бол өнөөдрийн нэр дэвшигчдийн жагсаалт.",
        match_enabled="Асаах", match_disabled="Унтраах", match_precedence="Давуу эрх",
        match_disable_warning="area_command эсвэл all_lights унтраавал өрөө болон бүх гэрийн тушаал өөрчлөгдөнө.",
        lexicon_path="Багцын зам", lexicon_token="Токен", lexicon_add="Нэмэх", lexicon_remove="Хасах",
        origin_engine="хөдөлгүүр", origin_operator="оператор", origin_seed="үр", origin_trainer="дасгалжуулагч",
        compiled_floor="эмхэтгэсэн шал", seed_on="Асаах", seed_off="Унтраах",
    ),
}
