"""French core plus the assembled Assist lexicon table."""

from __future__ import annotations

from lang_packs.core import C, nums, w
from lang_packs.lexicons_north import north
from lang_packs.lexicons_rest import leftover
from lang_packs.lexicons_script import script
from lang_packs.lexicons_slavic import slavic
from lang_packs.lexicons_west import west
from lang_packs.native_apply import apply_native
from lang_packs.speech_tmpl import chat, speech
from lang_packs.voices import triples

BUILTINS = [
    {
        "code": "de",
        "mod": "de",
        "native": "Deutsch",
        "script": "Latn",
        "variants": ["de", "de-DE"],
        "path": "packs::de::PACK",
    },
    {
        "code": "en",
        "mod": "en",
        "native": "English",
        "script": "Latn",
        "variants": ["en", "en-US"],
        "path": "packs::en::PACK",
    },
]


FR_ROOMS = [
    ("salon", "wohnzimmer"),
    ("salle", "esszimmer"),
    ("chambre", "schlafzimmer"),
    ("cuisine", "kuche"),
    ("salledebain", "badezimmer"),
    ("bureau", "arbeitszimmer"),
    ("couloir", "flur"),
    ("balcon", "balkon"),
    ("maison", "wohnung"),
]

ALL_CORES = [
    C(
        "fr",
        "Français",
        ["fr", "fr-FR"],
        w(
            on=["allume", "allumer", "allumes", "active", "activer", "demarre", "demarrer"],
            off=["eteins", "eteindre", "eteint", "desactive", "desactiver", "ferme", "fermer"],
            open_=["ouvre", "ouvrir", "monte", "monter"],
            close=["ferme", "fermer", "baisse", "baisser"],
            query=["quel", "quelle", "quels", "quoi", "comment", "etat", "status", "montre"],
            set_=["mets", "mettre", "regle", "regler", "ajuste"],
            light=["lumiere", "lampe", "eclairage", "luminosite"],
            cover=["store", "stores", "rideau", "rideaux", "volet", "volets"],
            climate=["chauffage", "temperature", "climatisation", "degres", "clim"],
            media=["tv", "tele", "musique", "media", "volume"],
            lock=["serrure", "verrou"],
            door=["porte"],
            timer=["minuteur", "minuterie", "timer"],
            list_=["liste", "courses"],
            fan=["ventilateur"],
            vacuum=["aspirateur"],
            scene=["scene"],
            fillers=["le", "la", "les", "un", "une", "de", "du", "des", "dans", "svp", "sil", "te", "plaît", "plait", "moi", "mon", "ma"],
            and_=["et", "puis"],
            or_=["ou"],
            yes=["oui", "ok", "daccord"],
            all_=["tout", "tous", "toute", "toutes"],
            unlock=["deverrouille", "deverrouiller"],
            lock_v=["verrouille", "verrouiller"],
            add=["ajoute", "ajouter"],
            done=["fait", "coche"],
            stop=["stop", "arrete", "arreter"],
            play=["joue", "lecture"],
            pause=["pause"],
            percent=["pourcent", "pourcentage"],
            kitchen=["cuisine"],
            switch=["interrupteur"],
            hours=["heure", "heures"],
            minutes=["minute", "minutes"],
            seconds=["seconde", "secondes"],
            garage=["garage"],
            laundry=["buanderie"],
            washer=["lave"],
            left=["gauche"],
            right=["droite"],
            island=["ilot"],
            ceiling=["plafond"],
            one=["un", "une"],
            wrong=["non", "faux"],
            status=["etat"],
            scenes=["film", "cinema"],
        ),
        speech(
            "Je n'ai pas compris. Dis-moi par exemple quelle lumiere allumer.",
            "Que dois-je allumer?",
            "Que dois-je eteindre?",
            "Dis-moi quel appareil tu veux.",
            "D'accord, j'oublie la derniere phrase.",
            "Tu veux dire {names}?",
            " ou ",
            " et ",
            "{names} sont allumes.",
            "{names} sont eteints.",
            "{target} est allume.",
            "{target} est lance.",
            "{target} est eteint.",
            "{target} bascule.",
            "{target} est a {n} pour cent.",
            "{target} est {color}.",
            "{noun} {target} est a {n} degres.",
            "Chauffage",
            "Climatisation",
            "La temperature {loc}.",
            "Je regarde {target}.",
            "Lecture en pause.",
            "Lecture reprise.",
            "Piste suivante.",
            "Piste precedente.",
            "Son coupe.",
            "Son reactive.",
            "Le volume est regle.",
            "Musique lancee.",
            "Musique deplacee.",
            "Titre ajoute.",
            "Ventilateur a {n} pour cent.",
            "{target} aspire.",
            "{target} rentre a la base.",
            "L'aspirateur",
            "Minuteur lance.",
            "Minuteur arrete.",
            "Minuteur en pause.",
            "Ajoute a la liste.",
            "Fait: {name}.",
            " lumiere",
            "la lumiere {loc}",
            "dans le {room}",
            "dans la {room}",
            "dans la maison",
            "l'appareil",
            "Je dois vraiment le faire?",
        ),
        chat(
            ["bonjour", "salut", "coucou", "bonsoir"],
            ["merci"],
            ["humeur", "ennui"],
            ["qui"],
            ["raconte"],
            ["histoire", "blague"],
            ["capitale", "meteo"],
            ["idee"],
            ["qui", "pourquoi", "quand", "ou", "comment"],
            ["actu", "infos"],
            ["stop", "assez"],
            "Voici un court resume des actualites.",
            "Tu veux en savoir plus?",
            "D'accord.",
        ),
        FR_ROOMS,
        [
            ("rouge", "red"),
            ("bleu", "blue"),
            ("vert", "green"),
            ("jaune", "yellow"),
            ("orange", "orange"),
            ("rose", "pink"),
            ("noir", "black"),
            ("blanc", "white"),
            ("violet", "purple"),
        ],
        nums(
            [
                "zero",
                "un",
                "deux",
                "trois",
                "quatre",
                "cinq",
                "six",
                "sept",
                "huit",
                "neuf",
                "dix",
                "onze",
                "douze",
                "treize",
                "quatorze",
                "quinze",
                "seize",
                "dixsept",
                "dixhuit",
                "dixneuf",
                "vingt",
                "trente",
                "quarante",
                "cinquante",
                "soixante",
                "soixantedix",
                "quatrevingts",
                "quatrevingtDix",
                "cent",
            ]
        ),
        [("allume la lumiere salon", "HassTurnOn"), ("eteins la lumiere cuisine", "HassTurnOff")],
        personality=triples(
            ("Tres bien. ", "Avec plaisir. ", ""),
            ("C'est bon. ", "Carre. ", ""),
            ("Je m'en occupe. ", "Tout va bien. ", ""),
            ("C'est parti. ", "Super. ", ""),
            ("Bon. ", "S'il le faut. ", ""),
            ("Evidemment. ", "Quelle surprise. ", ""),
            ("Aye. ", "Capitaine. ", ""),
            ("Cool. ", "Tranquille. ", ""),
            ("Oui. ", "Oui, mon precieux. ", ""),
        ),
        scene_synonyms=[("cinema", "film")],
        extra_verbs=[("next", "Next"), ("suivant", "Next")],
    ),
]

ALL_CORES.extend(west() + north() + slavic() + script() + leftover())
for _core in ALL_CORES:
    apply_native(_core)
