"""Dutch and Romance Assist lexicons."""

from __future__ import annotations

from lang_packs.core import C, euro_chat, nums, pack, rooms, w
from lang_packs.speech_tmpl import speech
from lang_packs.voices import spoken_home, triples


def west() -> list[dict]:
    return [nl(), es(), it(), pt(), ca(), ro()]


def nl() -> dict:
    return C(
        "nl",
        "Nederlands",
        ["nl", "nl-NL", "nl-BE"],
        w(
            on=["aanzetten", "doe", "start", "activeer"],
            off=["uitzetten", "deactiveer", "stop"],
            open_=["open", "openen"],
            close=["dicht", "sluit", "sluiten"],
            query=["wat", "hoe", "status", "staat"],
            set_=["stel"],
            light=["licht", "lamp", "verlichting"],
            cover=["gordijn", "gordijnen", "jaloezie", "rolluik"],
            climate=["verwarming", "temperatuur", "airco", "graden"],
            media=["tv", "muziek", "volume"],
            lock=["slot"],
            door=["deur"],
            timer=["timer"],
            list_=["lijst", "boodschappen"],
            fan=["ventilator"],
            vacuum=["stofzuiger"],
            scene=["scene"],
            fillers=["de", "het", "een", "in", "alsjeblieft", "me", "mijn"],
            and_=["en"],
            or_=["of"],
            yes=["ja", "ok"],
            all_=["alle", "overal"],
            unlock=["ontgrendel"],
            lock_v=["vergrendel"],
            add=["voeg"],
            done=["klaar"],
            pause=["pauze"],
            kitchen=["keuken"],
            hours=["uur"],
            minutes=["minuut", "minuten"],
            seconds=["seconde"],
            one=["een"],
            on_particles=["aan"],
            off_particles=["uit"],
            play=["speel"],
            dock=["terug", "station", "thuis"],
        ),
        speech(
            "Dat begreep ik niet. Zeg bijvoorbeeld welk licht aan moet.",
            "Wat moet ik aanzetten?",
            "Wat moet ik uitzetten?",
            "Welk apparaat bedoel je?",
            "Oké, die laatste zin laat ik vallen.",
            "Bedoel je {names}?",
            " of ",
            " en ",
            "{names} staan aan.",
            "{names} staan uit.",
            "{target} staat aan.",
            "{target} is gestart.",
            "{target} staat uit.",
            "{target} wisselt.",
            "{target} staat op {n} procent.",
            "{target} is {color}.",
            "{noun} {target} staat op {n} graden.",
            "Verwarming",
            "Airco",
            "De temperatuur {loc}.",
            "Ik kijk naar {target}.",
            "Afspelen is gepauzeerd.",
            "Afspelen gaat verder.",
            "Volgende nummer.",
            "Vorige nummer.",
            "Geluid is uit.",
            "Geluid is aan.",
            "Volume staat.",
            "Muziek start.",
            "Muziek verplaatst.",
            "Favoriet.",
            "Ventilator op {n} procent.",
            "{target} stofzuigt.",
            "{target} gaat naar het station.",
            "De stofzuiger",
            "Timer loopt.",
            "Timer uit.",
            "Timer pauze.",
            "Staat op de lijst.",
            "Klaar: {name}.",
            " licht",
            "het licht {loc}",
            "in de {room}",
            "in de {room}",
            "in huis",
            "het apparaat",
            "Moet ik dat echt doen?",
        ),
        euro_chat(["hallo", "hoi"], ["dank"], ["wie"], ["verhaal"], ["nieuws"], "Kort nieuws.", "Meer?", "Ok."),
        rooms(("woonkamer", "wohnzimmer"), ("keuken", "kuche"), ("slaapkamer", "schlafzimmer"), ("badkamer", "badezimmer"), ("kantoor", "arbeitszimmer"), ("gang", "flur"), ("huis", "wohnung")),
        [("rood", "red"), ("blauw", "blue"), ("groen", "green"), ("geel", "yellow"), ("oranje", "orange"), ("roze", "pink"), ("zwart", "black"), ("wit", "white"), ("paars", "purple")],
        nums(["nul", "een", "twee", "drie", "vier", "vijf", "zes", "zeven", "acht", "negen", "tien", "elf", "twaalf", "dertien", "veertien", "vijftien", "zestien", "zeventien", "achttien", "negentien", "twintig", "dertig", "veertig", "vijftig", "zestig", "zeventig", "tachtig", "negentig", "honderd"]),
        [("zet het licht woonkamer aan", "HassTurnOn"), ("zet het licht keuken uit", "HassTurnOff")],
        extra_verbs=[("zet", "Switch"), ("aan", "OnParticle"), ("uit", "Off")],
        personality=triples(
            ("Goed. ", "Graag. ", ""),
            ("Oké. ", "Prima. ", ""),
            ("Ik doe het meteen. ", "Alles goed. ", ""),
            ("Lekker bezig. ", "Mooi. ", ""),
            ("Nou goed. ", "Als het moet. ", ""),
            ("Natuurlijk. ", "Wat een verrassing. ", ""),
            ("Aye. ", "Kapitein. ", ""),
            ("Relax. ", "Rustig. ", ""),
            ("Ja. ", "Ja, mijn schat. ", ""),
        ),
    )


def es() -> dict:
    return pack(
        "es",
        "Español",
        ["es", "es-ES", "es-MX"],
        on=["enciende", "activar", "prende"],
        off=["apaga", "desactiva"],
        open_=["abre"],
        close=["cierra"],
        query=["que", "como", "estado"],
        set_=["pon"],
        light=["luz", "lampara"],
        cover=["cortina", "persiana"],
        climate=["calefaccion", "temperatura", "aire"],
        media=["tv", "musica"],
        lock=["cerradura"],
        door=["puerta"],
        timer=["temporizador"],
        list_=["lista"],
        fan=["ventilador"],
        vacuum=["aspiradora"],
        scene=["escena"],
        fillers=["el", "la", "los", "las", "en", "por", "favor"],
        and_=["y"],
        or_=["o"],
        yes=["si", "ok"],
        all_=["todo", "todas"],
        living="salon",
        kitchen="cocina",
        unknown="No lo he entendido. Dime por ejemplo que luz encender.",
        need_on="Que enciendo?",
        need_off="Que apago?",
        confirm="Debo hacerlo de verdad?",
        spoken=spoken_home("Vale, dejo la ultima frase.", "{target} esta encendido.", "{target} esta apagado.", "{target} cambia.", "La temperatura {loc}.", "Miro {target}.", "Reproduccion en pausa.", "Reproduccion sigue.", "Siguiente pista.", "Pista anterior.", "Sin sonido.", "Sonido activado.", "El volumen esta puesto.", "Esta en la lista."),
        personality=triples(("Muy bien. ", "Con gusto. ", ""), ("Hecho. ", "Vale. ", ""), ("Ahora mismo. ", "Todo bien. ", ""), ("Vamos. ", "Que bien. ", ""), ("Bueno. ", "Si hace falta. ", ""), ("Claro. ", "Que sorpresa. ", ""), ("Aye. ", "Capitan. ", ""), ("Tranqui. ", "Suave. ", ""), ("Si. ", "Si, mi tesoro. ", "")),
        numbers=["cero", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", "diez", "once", "doce", "trece", "catorce", "quince", "dieciseis", "diecisiete", "dieciocho", "diecinueve", "veinte", "treinta", "cuarenta", "cincuenta", "sesenta", "setenta", "ochenta", "noventa", "cien"],
        colors=[("rojo", "red"), ("azul", "blue"), ("verde", "green"), ("amarillo", "yellow"), ("naranja", "orange"), ("rosa", "pink"), ("negro", "black"), ("blanco", "white"), ("morado", "purple")],
        and_join=" y ",
        or_join=" o ",
        extra_w={"unlock": ["abre"], "lock_v": ["bloquea"], "add": ["anade"], "done": ["hecho"], "pause": ["pausa"], "play": ["reproduce"], "dock": ["base", "estacion"], "hours": ["hora"], "minutes": ["minuto"], "seconds": ["segundo"]},
    )


def it() -> dict:
    return pack(
        "it",
        "Italiano",
        ["it", "it-IT"],
        on=["accendi", "attiva"],
        off=["spegni", "disattiva"],
        open_=["apri"],
        close=["chiudi"],
        query=["cosa", "come", "stato"],
        set_=["metti"],
        light=["luce", "lampada"],
        cover=["tenda", "tapparella"],
        climate=["riscaldamento", "temperatura", "clima"],
        media=["tv", "musica"],
        lock=["serratura"],
        door=["porta"],
        timer=["timer"],
        list_=["lista"],
        fan=["ventola"],
        vacuum=["aspirapolvere"],
        scene=["scena"],
        fillers=["il", "la", "lo", "gli", "le", "in", "per", "favore"],
        and_=["e"],
        or_=["o"],
        yes=["si", "ok"],
        all_=["tutti", "tutto"],
        living="soggiorno",
        kitchen="cucina",
        unknown="Non ho capito. Dimmi per esempio quale luce accendere.",
        need_on="Cosa accendo?",
        need_off="Cosa spengo?",
        confirm="Devo farlo davvero?",
        spoken=spoken_home("Va bene, lascio cadere l'ultima frase.", "{target} e acceso.", "{target} e spento.", "{target} cambia.", "La temperatura {loc}.", "Controllo {target}.", "Riproduzione in pausa.", "Riproduzione ripresa.", "Brano successivo.", "Brano precedente.", "Audio spento.", "Audio acceso.", "Il volume e impostato.", "In lista."),
        personality=triples(("Molto bene. ", "Con piacere. ", ""), ("Fatto. ", "Ok. ", ""), ("Subito. ", "Tutto bene. ", ""), ("Andiamo. ", "Bello. ", ""), ("Va be'. ", "Se serve. ", ""), ("Certo. ", "Che sorpresa. ", ""), ("Aye. ", "Capitano. ", ""), ("Easy. ", "Piano. ", ""), ("Si. ", "Si, mio tesoro. ", "")),
        numbers=["zero", "uno", "due", "tre", "quattro", "cinque", "sei", "sette", "otto", "nove", "dieci", "undici", "dodici", "tredici", "quattordici", "quindici", "sedici", "diciassette", "diciotto", "diciannove", "venti", "trenta", "quaranta", "cinquanta", "sessanta", "settanta", "ottanta", "novanta", "cento"],
        colors=[("rosso", "red"), ("blu", "blue"), ("verde", "green"), ("giallo", "yellow"), ("arancione", "orange"), ("rosa", "pink"), ("nero", "black"), ("bianco", "white"), ("viola", "purple")],
        and_join=" e ",
        or_join=" o ",
        extra_w={"unlock": ["apri"], "lock_v": ["blocca"], "add": ["aggiungi"], "done": ["fatto"], "pause": ["pausa"], "hours": ["ora"], "minutes": ["minuto"], "seconds": ["secondo"]},
    )


def pt() -> dict:
    return pack(
        "pt",
        "Português",
        ["pt", "pt-PT"],
        on=["liga", "acende", "ativa"],
        off=["desliga", "apaga"],
        open_=["abre"],
        close=["fecha"],
        query=["que", "como", "estado"],
        set_=["poe"],
        light=["luz", "lampada"],
        cover=["cortina", "persiana"],
        climate=["aquecimento", "temperatura", "ar"],
        media=["tv", "musica"],
        lock=["fechadura"],
        door=["porta"],
        timer=["temporizador"],
        list_=["lista"],
        fan=["ventoinha"],
        vacuum=["aspirador"],
        scene=["cena"],
        fillers=["a", "o", "as", "os", "em", "por", "favor"],
        and_=["e"],
        or_=["ou"],
        yes=["sim", "ok"],
        all_=["tudo", "todos"],
        living="sala",
        kitchen="cozinha",
        unknown="Nao percebi. Diz-me por exemplo que luz ligar.",
        need_on="O que ligo?",
        need_off="O que desligo?",
        confirm="Devo mesmo fazer isso?",
        spoken=spoken_home("Certo, deixo a ultima frase.", "{target} esta ligado.", "{target} esta desligado.", "{target} muda.", "A temperatura {loc}.", "Estou a ver {target}.", "Reproducao em pausa.", "Reproducao continua.", "Faixa seguinte.", "Faixa anterior.", "Som desligado.", "Som ligado.", "O volume esta definido.", "Na lista."),
        personality=triples(("Muito bem. ", "Com gosto. ", ""), ("Feito. ", "Ok. ", ""), ("Ja faco. ", "Tudo bem. ", ""), ("Vamos. ", "Fixe. ", ""), ("Pronto. ", "Se for preciso. ", ""), ("Claro. ", "Que surpresa. ", ""), ("Aye. ", "Capitao. ", ""), ("Easy. ", "Calma. ", ""), ("Sim. ", "Sim, meu tesouro. ", "")),
        numbers=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito", "nove", "dez", "onze", "doze", "treze", "catorze", "quinze", "dezasseis", "dezassete", "dezoito", "dezanove", "vinte", "trinta", "quarenta", "cinquenta", "sessenta", "setenta", "oitenta", "noventa", "cem"],
        colors=[("vermelho", "red"), ("azul", "blue"), ("verde", "green"), ("amarelo", "yellow"), ("laranja", "orange"), ("rosa", "pink"), ("preto", "black"), ("branco", "white"), ("roxo", "purple")],
        and_join=" e ",
        or_join=" ou ",
        extra_w={"unlock": ["abre"], "lock_v": ["tranca"], "add": ["adiciona"], "done": ["feito"], "pause": ["pausa"], "hours": ["hora"], "minutes": ["minuto"], "seconds": ["segundo"]},
    )


def ca() -> dict:
    return pack(
        "ca",
        "Català",
        ["ca", "ca-ES"],
            on=["encen", "activa"],
        off=["apaga", "desactiva"],
        open_=["obri"],
        close=["tanca"],
        query=["que", "com", "estat"],
        set_=["posa"],
        light=["llum", "lampada"],
        cover=["cortina", "persiana"],
        climate=["calefaccio", "temperatura", "aire"],
        media=["tv", "musica"],
        lock=["pany"],
        door=["porta"],
        timer=["temporitzador"],
        list_=["llista"],
        fan=["ventilador"],
        vacuum=["aspiradora"],
        scene=["escena"],
        fillers=["el", "la", "els", "les", "siusplau"],
        and_=["i"],
        or_=["o"],
        yes=["si", "ok"],
        all_=["tot", "tots"],
        living="sala",
        kitchen="cuina",
        unknown="No ho he entes. Digues per exemple quin llum encendre.",
        need_on="Que encenc?",
        need_off="Que apago?",
        confirm="Ho faig de veritat?",
        spoken=spoken_home("D'acord, deixo la darrera frase.", "{target} esta encès.", "{target} esta apagat.", "{target} canvia.", "La temperatura {loc}.", "Miro {target}.", "Reproduccio en pausa.", "Reproduccio continua.", "Pista seguent.", "Pista anterior.", "So apagat.", "So encès.", "El volum esta posat.", "A la llista."),
        personality=triples(("Molt be. ", "Amb gust. ", ""), ("Fet. ", "D'acord. ", ""), ("Ara mateix. ", "Tot be. ", ""), ("Som-hi. ", "Genial. ", ""), ("Be. ", "Si cal. ", ""), ("Esclar. ", "Quina sorpresa. ", ""), ("Aye. ", "Capita. ", ""), ("Tranqui. ", "Suaument. ", ""), ("Si. ", "Si, el meu tesoro. ", "")),
        numbers=["zero", "un", "dos", "tres", "quatre", "cinc", "sis", "set", "vuit", "nou", "deu", "onze", "dotze", "tretze", "catorze", "quinze", "setze", "disset", "divuit", "dinou", "vint", "trenta", "quaranta", "cinquanta", "seixanta", "setanta", "vuitanta", "noranta", "cent"],
        colors=[("vermell", "red"), ("blau", "blue"), ("verd", "green"), ("groc", "yellow"), ("taronja", "orange"), ("rosa", "pink"), ("negre", "black"), ("blanc", "white"), ("lila", "purple")],
        and_join=" i ",
        or_join=" o ",
        extra_w={"unlock": ["obri"], "lock_v": ["bloqueja"], "add": ["afegeix"], "done": ["fet"], "pause": ["pausa"], "hours": ["hora"], "minutes": ["minut"], "seconds": ["segon"]},
    )


def ro() -> dict:
    return pack(
        "ro",
        "Română",
        ["ro", "ro-RO"],
        on=["aprinde", "porneste"],
        off=["stinge", "opreste"],
        open_=["deschide"],
        close=["inchide"],
        query=["ce", "cum", "stare"],
        set_=["pune"],
        light=["lumina", "lampa"],
        cover=["perdea", "jaluzea"],
        climate=["incalzire", "temperatura", "aer"],
        media=["tv", "muzica"],
        lock=["yala"],
        door=["usa"],
        timer=["cronometru"],
        list_=["lista"],
        fan=["ventilator"],
        vacuum=["aspirator"],
        scene=["scena"],
        fillers=["o", "un", "in", "te", "rog"],
        and_=["si"],
        or_=["sau"],
        yes=["da", "ok"],
        all_=["tot", "toate"],
        living="sufragerie",
        kitchen="bucatarie",
        unknown="Nu am inteles. Spune-mi de exemplu ce lumina sa aprind.",
        need_on="Ce aprind?",
        need_off="Ce sting?",
        confirm="Chiar sa fac asta?",
        spoken=spoken_home("Bine, las ultima fraza.", "{target} este aprins.", "{target} este stins.", "{target} se schimba.", "Temperatura {loc}.", "Ma uit la {target}.", "Redarea e in pauza.", "Redarea continua.", "Piesa urmatoare.", "Piesa anterioara.", "Sunet oprit.", "Sunet pornit.", "Volumul e setat.", "E pe lista."),
        personality=triples(("Foarte bine. ", "Cu placere. ", ""), ("Gata. ", "Ok. ", ""), ("Imediat. ", "Totul e bine. ", ""), ("Hai. ", "Super. ", ""), ("Bine. ", "Daca trebuie. ", ""), ("Sigur. ", "Ce surpriza. ", ""), ("Aye. ", "Capitane. ", ""), ("Relax. ", "Linistit. ", ""), ("Da. ", "Da, comoara mea. ", "")),
        numbers=["zero", "unu", "doi", "trei", "patru", "cinci", "sase", "sapte", "opt", "noua", "zece", "unsprezece", "doisprezece", "treisprezece", "paisprezece", "cincisprezece", "saisprezece", "saptesprezece", "optsprezece", "nouasprezece", "douazeci", "treizeci", "patruzeci", "cincizeci", "saizeci", "saptezeci", "optzeci", "nouazeci", "suta"],
        colors=[("rosu", "red"), ("albastru", "blue"), ("verde", "green"), ("galben", "yellow"), ("portocaliu", "orange"), ("roz", "pink"), ("negru", "black"), ("alb", "white"), ("mov", "purple")],
        and_join=" si ",
        or_join=" sau ",
        extra_w={"unlock": ["deschide"], "lock_v": ["blocheaza"], "add": ["adauga"], "done": ["gata"], "pause": ["pauza"], "hours": ["ora"], "minutes": ["minut"], "seconds": ["secunda"]},
    )
