"""West Slavic, South Slavic, Greek, Hungarian, Ukrainian, Bulgarian."""

from __future__ import annotations

from lang_packs.core import pack
from lang_packs.voices import spoken_home, triples


def slavic() -> list[dict]:
    return [
        pack(
            "cs",
            "Čeština",
            ["cs", "cs-CZ"],
            on=["zapni"],
            off=["vypni"],
            open_=["otevri"],
            close=["zavri"],
            query=["co", "jak"],
            set_=["nastav"],
            light=["svetlo"],
            cover=["zaves"],
            climate=["topeni", "teplota", "klima"],
            media=["televize", "hudba"],
            lock=["zamek"],
            door=["dvere"],
            timer=["casovac"],
            list_=["seznam"],
            fan=["ventilator"],
            vacuum=["vysavac"],
            scene=["scena"],
            fillers=["to", "v", "na"],
            and_=["a"],
            or_=["nebo"],
            yes=["ano", "ok"],
            all_=["vse"],
            extra_w={
                "play": ["play", "pust"],
                "pause": ["pause"],
                "lock_v": ["zamkni"],
                "unlock": ["odemkni"],
                "add": ["pridej"],
                "done": ["hotovo"],
                "minutes": ["minut", "minuty"],
            },
            extra_verbs=[("next", "Next"), ("dalsi", "Next")],
            living="obyvak",
            kitchen="kuchyne",
            unknown="Nerozumel jsem. Rekněte treba, ktere svetlo zapnout.",
            need_on="Co zapnout?",
            need_off="Co vypnout?",
            confirm="Mam to opravdu udelat?",
            spoken=spoken_home("Dobre, posledni vetu nechavam byt.", "{target} je zapnute.", "{target} je vypnute.", "{target} se prepina.", "Teplota {loc}.", "Divam se na {target}.", "Prehravani je pozastaveno.", "Prehravani pokracuje.", "Dalsi skladba.", "Predchozi skladba.", "Zvuk je vypnuty.", "Zvuk je zapnuty.", "Hlasitost je nastavena.", "Je na seznamu."),
            personality=triples(("Velmi dobre. ", "Rád. ", ""), ("Jasne. ", "Hotovo. ", ""), ("Hned to udelam. ", "Vsechno v poradku. ", ""), ("Jedeme. ", "Super. ", ""), ("No dobre. ", "Kdyz musim. ", ""), ("Samozrejme. ", "Jake prekvapeni. ", ""), ("Aye. ", "Kapitane. ", ""), ("Pohoda. ", "V klidu. ", ""), ("Ano. ", "Ano, muj poklade. ", "")),
            numbers=["nula", "jedna", "dva", "tri", "ctyri", "pet", "sest", "sedm", "osm", "devet", "deset", "jedenact", "dvanact", "trinact", "ctrnact", "patnact", "sestnact", "sedmnact", "osmnact", "devatenact", "dvacet", "tricet", "ctyricet", "padesat", "sedesat", "sedmdesat", "osmdesat", "devadesat", "sto"],
            colors=[("cervena", "red"), ("modra", "blue"), ("zelena", "green"), ("zluta", "yellow"), ("oranzova", "orange"), ("ruzova", "pink"), ("cerna", "black"), ("bila", "white"), ("fialova", "purple")],
            and_join=" a ",
            or_join=" nebo ",
        ),
        pack(
            "sk",
            "Slovenčina",
            ["sk", "sk-SK"],
            on=["zapni"],
            off=["vypni"],
            open_=["otvor"],
            close=["zatvor"],
            query=["co", "ako"],
            set_=["nastav"],
            light=["svetlo"],
            cover=["zaves"],
            climate=["kurenie", "teplota"],
            media=["televizia", "hudba"],
            lock=["zamok"],
            door=["dvere"],
            timer=["casovac"],
            list_=["zoznam"],
            fan=["ventilator"],
            vacuum=["vysavac"],
            scene=["scena"],
            fillers=["to", "v", "na"],
            and_=["a"],
            or_=["alebo"],
            yes=["ano", "ok"],
            all_=["vsetko"],
            living="obyvacka",
            kitchen="kuchyne",
            unknown="Nerozumel som. Povedzte napríklad, ktore svetlo zapnut.",
            need_on="Co zapnut?",
            need_off="Co vypnut?",
            confirm="Mam to naozaj spravit?",
            spoken=spoken_home("Dobre, poslednu vetu nechavam tak.", "{target} je zapnute.", "{target} je vypnute.", "{target} sa prepina.", "Teplota {loc}.", "Pozeram na {target}.", "Prehravanie je pozastavene.", "Prehravanie pokracuje.", "Dalsia skladba.", "Predosla skladba.", "Zvuk je vypnuty.", "Zvuk je zapnuty.", "Hlasitost je nastavena.", "Je na zozname."),
            personality=triples(("Velmi dobre. ", "Rad. ", ""), ("Jasne. ", "Hotovo. ", ""), ("Hned to spravim. ", "Vsetko v poriadku. ", ""), ("Ideme. ", "Super. ", ""), ("No dobre. ", "Ak musim. ", ""), ("Samozrejme. ", "Ake prekvapenie. ", ""), ("Aye. ", "Kapitan. ", ""), ("Pohoda. ", "V klude. ", ""), ("Ano. ", "Ano, moj poklad. ", "")),
            numbers=["nula", "jeden", "dva", "tri", "styri", "pat", "sest", "sedem", "osem", "devat", "desat", "jedenast", "dvanast", "trinast", "strnast", "patnast", "sestnast", "sedemnast", "osemnast", "devatnast", "dvadsat", "tridsat", "styridsat", "padest", "sestdesiat", "sedemdesiat", "osemdesiat", "devatdesiat", "sto"],
            and_join=" a ",
            or_join=" alebo ",
        ),
        pack(
            "pl",
            "Polski",
            ["pl", "pl-PL"],
            on=["wlacz"],
            off=["wylacz"],
            open_=["otworz"],
            close=["zamknij"],
            query=["co", "jak"],
            set_=["ustaw"],
            light=["swiatlo"],
            cover=["zaslona"],
            climate=["ogrzewanie", "temperatura"],
            media=["telewizor", "muzyka"],
            lock=["zamek"],
            door=["drzwi"],
            timer=["minutnik"],
            list_=["lista"],
            fan=["wentylator"],
            vacuum=["odkurzacz"],
            scene=["scena"],
            fillers=["to", "w", "na"],
            and_=["i"],
            or_=["lub"],
            yes=["tak", "ok"],
            all_=["wszystko"],
            living="salon",
            kitchen="kuchnia",
            unknown="Nie zrozumialem. Powiedz na przyklad, ktore swiatlo wlaczyc.",
            need_on="Co wlaczyc?",
            need_off="Co wylaczyc?",
            confirm="Naprawde to zrobic?",
            spoken=spoken_home("Dobrze, pomijam ostatnie zdanie.", "{target} jest wlaczone.", "{target} jest wylaczone.", "{target} sie przelacza.", "Temperatura {loc}.", "Sprawdzam {target}.", "Odtwarzanie jest wstrzymane.", "Odtwarzanie trwa dalej.", "Nastepny utwor.", "Poprzedni utwor.", "Dzwiek jest wylaczony.", "Dzwiek jest wlaczony.", "Glosnosc jest ustawiona.", "Jest na liscie."),
            personality=triples(("Bardzo dobrze. ", "Chetnie. ", ""), ("Jasne. ", "Zrobione. ", ""), ("Zrobie to od razu. ", "Wszystko dobrze. ", ""), ("Jedziemy. ", "Fajnie. ", ""), ("No dobra. ", "Jesli musze. ", ""), ("Oczywiscie. ", "Co za niespodzianka. ", ""), ("Aye. ", "Kapitanie. ", ""), ("Spoko. ", "Luz. ", ""), ("Tak. ", "Tak, moj skarbie. ", "")),
            numbers=["zero", "jeden", "dwa", "trzy", "cztery", "piec", "szesc", "siedem", "osiem", "dziewiec", "dziesiec", "jedenascie", "dwanascie", "trzynascie", "czternascie", "pietnascie", "szesnascie", "siedemnascie", "osiemnascie", "dziewietnascie", "dwadziescia", "trzydziesci", "czterdziesci", "piecdziesiat", "szescdziesiat", "siedemdziesiat", "osiemdziesiat", "dziewiecdziesiat", "sto"],
            colors=[("czerwony", "red"), ("niebieski", "blue"), ("zielony", "green"), ("zolty", "yellow"), ("pomaranczowy", "orange"), ("rozowy", "pink"), ("czarny", "black"), ("bialy", "white"), ("fioletowy", "purple")],
            and_join=" i ",
            or_join=" lub ",
        ),
        pack(
            "hu",
            "Magyar",
            ["hu", "hu-HU"],
            on=["kapcsold"],
            off=["oltsd"],
            open_=["nyisd"],
            close=["csukd"],
            query=["mi", "hogy"],
            set_=["allitsd"],
            light=["villany"],
            cover=["fuggony"],
            climate=["futes", "homerseklet"],
            media=["tv", "zene"],
            lock=["zar"],
            door=["ajto"],
            timer=["idomer"],
            list_=["lista"],
            fan=["ventilator"],
            vacuum=["porszivo"],
            scene=["jelenet"],
            fillers=["a", "az", "be"],
            and_=["es"],
            or_=["vagy"],
            yes=["igen", "ok"],
            all_=["mind"],
            living="nappali",
            kitchen="konyha",
            unknown="Nem ertettem. Mondd peldaul, melyik villanyt kapcsoljam fel.",
            need_on="Mit kapcsoljak?",
            need_off="Mit oltsak?",
            confirm="Tenyleg megcsinaljam?",
            spoken=spoken_home("Rendben, az utolso mondatot elhagyom.", "{target} be van kapcsolva.", "{target} ki van kapcsolva.", "{target} valt.", "A homerseklet {loc}.", "Megnezem: {target}.", "A lejatszas szunetel.", "A lejatszas megy tovabb.", "Kovetkezo szam.", "Elozo szam.", "A hang ki van kapcsolva.", "A hang be van kapcsolva.", "A hangerő be van allitva.", "Felkerult a listara."),
            personality=triples(("Nagyon jol. ", "Szivesen. ", ""), ("Oké. ", "Kesz. ", ""), ("Azonnal megcsinalom. ", "Minden rendben. ", ""), ("Gyerunk. ", "Szep. ", ""), ("Hát jo. ", "Ha muszaj. ", ""), ("Persze. ", "Micsoda meglepetes. ", ""), ("Aye. ", "Kapitany. ", ""), ("Laza. ", "Nyugi. ", ""), ("Igen. ", "Igen, kincsem. ", "")),
            numbers=["nulla", "egy", "ketto", "harom", "negy", "ot", "hat", "het", "nyolc", "kilenc", "tiz", "tizenegy", "tizenketto", "tizenharom", "tizennegy", "tizenot", "tizenhat", "tizenhet", "tizennyolc", "tizenkilenc", "husz", "harminc", "negyven", "otven", "hatvan", "hetven", "nyolcvan", "kilencven", "szaz"],
            and_join=" es ",
            or_join=" vagy ",
        ),
        pack(
            "hr",
            "Hrvatski",
            ["hr", "hr-HR"],
            on=["upali"],
            off=["ugasi"],
            open_=["otvori"],
            close=["zatvori"],
            query=["kako", "sto"],
            set_=["stavi"],
            light=["svjetlo"],
            cover=["zavjesa"],
            climate=["grijanje", "temperatura"],
            media=["televizor", "glazba"],
            lock=["brava"],
            door=["vrata"],
            timer=["tajmer"],
            list_=["lista"],
            fan=["ventilator"],
            vacuum=["usisivac"],
            scene=["scena"],
            fillers=["to", "u", "na"],
            and_=["i"],
            or_=["ili"],
            yes=["da", "ok"],
            all_=["sve"],
            living="dnevni",
            kitchen="kuhinja",
            unknown="Nisam razumio. Reci na primjer koje svjetlo upaliti.",
            need_on="Sto upaliti?",
            need_off="Sto ugasiti?",
            confirm="Trebam li to stvarno?",
            spoken=spoken_home("U redu, zadnju recenicu preskacem.", "{target} je upaljen.", "{target} je ugasen.", "{target} se prebacuje.", "Temperatura {loc}.", "Gledam {target}.", "Reprodukcija je pauzirana.", "Reprodukcija se nastavlja.", "Sljedeca pjesma.", "Prethodna pjesma.", "Zvuk je ugasen.", "Zvuk je upaljen.", "Glasnoća je postavljena.", "Na je popisu."),
            personality=triples(("Vrlo dobro. ", "Rado. ", ""), ("U redu. ", "Gotovo. ", ""), ("Odmah to radim. ", "Sve je u redu. ", ""), ("Idemo. ", "Super. ", ""), ("Dobro. ", "Ako moram. ", ""), ("Naravno. ", "Kakvo iznenadenje. ", ""), ("Aye. ", "Kapetane. ", ""), ("Opusteno. ", "Mirno. ", ""), ("Da. ", "Da, slatko moje. ", "")),
            numbers=["nula", "jedan", "dva", "tri", "cetiri", "pet", "sest", "sedam", "osam", "devet", "deset", "jedanaest", "dvanaest", "trinaest", "cetrnaest", "petnaest", "sesnaest", "sedamnaest", "osamnaest", "devetnaest", "dvadeset", "trideset", "cetrdeset", "pedeset", "sezdeset", "sedamdeset", "osamdeset", "devedeset", "sto"],
            and_join=" i ",
            or_join=" ili ",
        ),
        pack(
            "sl",
            "Slovenščina",
            ["sl", "sl-SI"],
            on=["prizgi"],
            off=["ugasni"],
            open_=["odpri"],
            close=["zapri"],
            query=["kaj", "kako"],
            set_=["nastavi"],
            light=["luc"],
            cover=["zavesa"],
            climate=["ogrevanje", "temperatura"],
            media=["televizor", "glasba"],
            lock=["kljucavnica"],
            door=["vrata"],
            timer=["casovnik"],
            list_=["seznam"],
            fan=["ventilator"],
            vacuum=["sesalnik"],
            scene=["scena"],
            fillers=["to", "v", "na"],
            and_=["in"],
            or_=["ali"],
            yes=["da", "ok"],
            all_=["vse"],
            living="dnevna",
            kitchen="kuhinja",
            unknown="Nisem razumel. Reci na primer, katero luc prizgati.",
            need_on="Kaj prizgati?",
            need_off="Kaj ugasniti?",
            confirm="Naj res naredim?",
            spoken=spoken_home("V redu, zadnji stavek izpustim.", "{target} je prizgan.", "{target} je ugasnjen.", "{target} se preklaplja.", "Temperatura {loc}.", "Preverjam {target}.", "Predvajanje je zaustavljeno.", "Predvajanje tece naprej.", "Naslednja skladba.", "Prejsnja skladba.", "Zvok je izklopljen.", "Zvok je vklopljen.", "Glasnost je nastavljena.", "Je na seznamu."),
            personality=triples(("Zelo dobro. ", "Rad. ", ""), ("V redu. ", "Opravljeno. ", ""), ("Naredim takoj. ", "Vse je v redu. ", ""), ("Gremo. ", "Super. ", ""), ("No dobro. ", "Ce moram. ", ""), ("Seveda. ", "Kakšno presenecenje. ", ""), ("Aye. ", "Kapitan. ", ""), ("Sproščeno. ", "Mirno. ", ""), ("Da. ", "Da, moj zaklad. ", "")),
            numbers=["nic", "ena", "dva", "tri", "stiri", "pet", "sest", "sedem", "osem", "devet", "deset", "enajst", "dvanajst", "trinajst", "stirinajst", "petnajst", "sesnajst", "sedemnajst", "osemnajst", "devetnajst", "dvajset", "trideset", "stirideset", "petdeset", "sestdeset", "sedemdeset", "osemdeset", "devetdeset", "sto"],
            and_join=" in ",
            or_join=" ali ",
        ),
        pack(
            "bg",
            "Български",
            ["bg", "bg-BG"],
            script="Cyrl",
            on=["включи"],
            off=["изключи"],
            open_=["отвори"],
            close=["затвори"],
            query=["какво", "как"],
            set_=["сложи"],
            light=["светлина"],
            cover=["завеса"],
            climate=["парно", "температура"],
            media=["телевизор", "музика"],
            lock=["ключалка"],
            door=["врата"],
            timer=["таймер"],
            list_=["списък"],
            fan=["вентилатор"],
            vacuum=["прахосмукачка"],
            scene=["сцена"],
            fillers=["в", "на", "то"],
            and_=["и"],
            or_=["или"],
            yes=["да", "ок"],
            all_=["всичко"],
            living="хол",
            kitchen="кухня",
            unknown="Не разбрах. Кажи например коя светлина да включа.",
            need_on="Какво да включа?",
            need_off="Какво да изключа?",
            confirm="Наистина ли да го направя?",
            spoken=spoken_home("Добре, пропускам последното изречение.", "{target} е включен.", "{target} е изключен.", "{target} превключва.", "Температурата {loc}.", "Гледам {target}.", "Възпроизвеждането е на пауза.", "Възпроизвеждането продължава.", "Следваща песен.", "Предишна песен.", "Звукът е спрян.", "Звукът е включен.", "Силата е зададена.", "Е в списъка."),
            personality=triples(("Много добре. ", "С удоволствие. ", ""), ("Ок. ", "Готово. ", ""), ("Правя го веднага. ", "Всичко е наред. ", ""), ("Давай. ", "Супер. ", ""), ("Добре де. ", "Ако трябва. ", ""), ("Разбира се. ", "Каква изненада. ", ""), ("Aye. ", "Капитане. ", ""), ("Спокойно. ", "Леко. ", ""), ("Да. ", "Да, съкровище мое. ", "")),
            numbers=["нула", "едно", "две", "три", "четири", "пет", "шест", "седем", "осем", "девет", "десет", "единадесет", "дванадесет", "тринадесет", "четиринадесет", "петнадесет", "шестнадесет", "седемнадесет", "осемнадесет", "деветнадесет", "двадесет", "тридесет", "четиридесет", "петдесет", "шестдесет", "седемдесет", "осемдесет", "деветдесет", "сто"],
            and_join=" и ",
            or_join=" или ",
        ),
        pack(
            "el",
            "Ελληνικά",
            ["el", "el-GR"],
            script="Grek",
            on=["αναψε"],
            off=["σβησε"],
            open_=["ανοιξε"],
            close=["κλεισε"],
            query=["τι", "πως"],
            set_=["βαλε"],
            light=["φως"],
            cover=["κουρτινα"],
            climate=["θερμανση", "θερμοκρασια"],
            media=["τηλεοραση", "μουσικη"],
            lock=["κλειδαρια"],
            door=["πορτα"],
            timer=["χρονομετρο"],
            list_=["λιστα"],
            fan=["ανεμιστηρας"],
            vacuum=["σκουπα"],
            scene=["σκηνη"],
            fillers=["το", "στο", "την"],
            and_=["και"],
            or_=["η"],
            yes=["ναι", "οκ"],
            all_=["ολα"],
            living="σαλονι",
            kitchen="κουζινα",
            unknown="Δεν το καταλαβα. Πες για παραδειγμα ποιο φως να ανοίξω.",
            need_on="Τι να ανοιξω;",
            need_off="Τι να κλεισω;",
            confirm="Να το κανω οντως;",
            spoken=spoken_home("Ενταξει, αφηνω την τελευταια προταση.", "{target} ειναι ανοιχτο.", "{target} ειναι κλειστο.", "{target} αλλαζει.", "Η θερμοκρασια {loc}.", "Κοιταζω το {target}.", "Η αναπαραγωγη ειναι σε παυση.", "Η αναπαραγωγη συνεχιζει.", "Επομενο κομματι.", "Προηγουμενο κομματι.", "Ο ηχος ειναι κλειστος.", "Ο ηχος ειναι ανοιχτος.", "Η ενταση ειναι ρυθμισμενη.", "Ειναι στη λιστα."),
            personality=triples(("Πολυ καλα. ", "Με χαρα. ", ""), ("Ενταξει. ", "Εγινε. ", ""), ("Το κανω αμεσως. ", "Ολα καλα. ", ""), ("Πάμε. ", "Ωραια. ", ""), ("Καλα. ", "Αν πρεπει. ", ""), ("Φυσικα. ", "Τι εκπληξη. ", ""), ("Aye. ", "Καπετανιε. ", ""), ("Χαλαρα. ", "Ηρεμα. ", ""), ("Ναι. ", "Ναι, θησαυρε μου. ", "")),
            numbers=["μηδεν", "ενα", "δυο", "τρια", "τεσσερα", "πεντε", "εξι", "επτα", "οκτω", "εννια", "δεκα", "εντεκα", "δωδεκα", "δεκατρια", "δεκατεσσερα", "δεκαπεντε", "δεκαεξι", "δεκαεπτα", "δεκαοκτω", "δεκαεννια", "εικοσι", "τριαντα", "σαραντα", "πενηντα", "εξηντα", "εβδομηντα", "ογδοντα", "ενενηντα", "εκατο"],
            extra_w={"unlock": ["ξεκλειδωσε"], "lock_v": ["κλειδωσε"]},
            and_join=" και ",
            or_join=" η ",
        ),
        pack(
            "sr",
            "Српски",
            ["sr", "sr-RS"],
            script="Cyrl",
            on=["укључи"],
            off=["искључи"],
            open_=["отвори"],
            close=["затвори"],
            query=["шта", "како"],
            set_=["стави"],
            light=["светло"],
            cover=["завеса"],
            climate=["грејање", "температура"],
            media=["телевизор", "музика"],
            lock=["брава"],
            door=["врата"],
            timer=["тајмер"],
            list_=["листа"],
            fan=["вентилатор"],
            vacuum=["усисивач"],
            scene=["сцена"],
            fillers=["у", "на", "то"],
            and_=["и"],
            or_=["или"],
            yes=["да", "ок"],
            all_=["све"],
            living="дневна",
            kitchen="кухиња",
            unknown="Нисам разумео. Реци на пример које светло да упалим.",
            need_on="Шта да укључим?",
            need_off="Шта да искључим?",
            confirm="Да ли заиста?",
            spoken=spoken_home("У реду, последњу реченицу прескачем.", "{target} је упаљен.", "{target} је угашен.", "{target} се пребацује.", "Температура {loc}.", "Гледам {target}.", "Репродукција је паузирана.", "Репродукција наставља.", "Следећа песма.", "Претходна песма.", "Звук је угашен.", "Звук је упаљен.", "Јачина је подешена.", "На је списку."),
            personality=triples(("Врло добро. ", "Радо. ", ""), ("У реду. ", "Готово. ", ""), ("Одмах то радим. ", "Све је у реду. ", ""), ("Идемо. ", "Супер. ", ""), ("Добро. ", "Ако морам. ", ""), ("Наравно. ", "Какво изненађење. ", ""), ("Aye. ", "Капетане. ", ""), ("Опуштено. ", "Мирно. ", ""), ("Да. ", "Да, благо моје. ", "")),
            numbers=["нула", "један", "два", "три", "четири", "пет", "шест", "седам", "осам", "девет", "десет", "једанаест", "дванаест", "тринаест", "четрнаест", "петнаест", "шеснаест", "седамнаест", "осамнаест", "деветнаест", "двадесет", "тридесет", "четрдесет", "педесет", "шездесет", "седамдесет", "осамдесет", "деведесет", "сто"],
            and_join=" и ",
            or_join=" или ",
        ),
        pack(
            "sr-Latn",
            "Srpski",
            ["sr-Latn"],
            on=["ukljuci"],
            off=["iskljuci"],
            open_=["otvori"],
            close=["zatvori"],
            query=["sta", "kako"],
            set_=["stavi"],
            light=["svetlo"],
            cover=["zavesa"],
            climate=["grejanje", "temperatura"],
            media=["televizor", "muzika"],
            lock=["brava"],
            door=["vrata"],
            timer=["tajmer"],
            list_=["lista"],
            fan=["ventilator"],
            vacuum=["usisivac"],
            scene=["scena"],
            fillers=["u", "na", "to"],
            and_=["i"],
            or_=["ili"],
            yes=["da", "ok"],
            all_=["sve"],
            living="dnevna",
            kitchen="kuhinja",
            unknown="Nisam razumeo. Reci na primer koje svetlo da upalim.",
            need_on="Sta da ukljucim?",
            need_off="Sta da iskljucim?",
            confirm="Da li zaista?",
            spoken=spoken_home("U redu, poslednju recenicu preskacem.", "{target} je upaljen.", "{target} je ugasen.", "{target} se prebacuje.", "Temperatura {loc}.", "Gledam {target}.", "Reprodukcija je pauzirana.", "Reprodukcija nastavlja.", "Sledeca pesma.", "Prethodna pesma.", "Zvuk je ugasen.", "Zvuk je upaljen.", "Jacina je podesena.", "Na je spisku."),
            personality=triples(("Vrlo dobro. ", "Rado. ", ""), ("U redu. ", "Gotovo. ", ""), ("Odmah to radim. ", "Sve je u redu. ", ""), ("Idemo. ", "Super. ", ""), ("Dobro. ", "Ako moram. ", ""), ("Naravno. ", "Kakvo iznenadenje. ", ""), ("Aye. ", "Kapetane. ", ""), ("Opusteno. ", "Mirno. ", ""), ("Da. ", "Da, blago moje. ", "")),
            numbers=["nula", "jedan", "dva", "tri", "cetiri", "pet", "sest", "sedam", "osam", "devet", "deset", "jedanaest", "dvanaest", "trinaest", "cetrnaest", "petnaest", "sesnaest", "sedamnaest", "osamnaest", "devetnaest", "dvadeset", "trideset", "cetrdeset", "pedeset", "sezdeset", "sedamdeset", "osamdeset", "devedeset", "sto"],
            and_join=" i ",
            or_join=" ili ",
        ),
        pack(
            "uk",
            "Українська",
            ["uk", "uk-UA"],
            script="Cyrl",
            on=["увімкни"],
            off=["вимкни"],
            open_=["відкрий"],
            close=["закрий"],
            query=["що", "як"],
            set_=["постав"],
            light=["світло"],
            cover=["штора"],
            climate=["опалення", "температура"],
            media=["телевізор", "музика"],
            lock=["замок"],
            door=["двері"],
            timer=["таймер"],
            list_=["список"],
            fan=["вентилятор"],
            vacuum=["пилосос"],
            scene=["сцена"],
            fillers=["в", "на", "це"],
            and_=["і"],
            or_=["або"],
            yes=["так", "ок"],
            all_=["все"],
            living="вітальня",
            kitchen="кухня",
            unknown="Я не зрозумів. Скажи наприклад, яке світло увімкнути.",
            need_on="Що увімкнути?",
            need_off="Що вимкнути?",
            confirm="Справді це зробити?",
            spoken=spoken_home("Гаразд, останнє речення пропускаю.", "{target} увімкнено.", "{target} вимкнено.", "{target} перемикається.", "Температура {loc}.", "Дивлюсь на {target}.", "Відтворення на паузі.", "Відтворення триває.", "Наступний трек.", "Попередній трек.", "Звук вимкнено.", "Звук увімкнено.", "Гучність встановлено.", "У списку."),
            personality=triples(("Дуже добре. ", "Із задоволенням. ", ""), ("Гаразд. ", "Готово. ", ""), ("Зроблю зараз. ", "Все добре. ", ""), ("Ходімо. ", "Класно. ", ""), ("Ну добре. ", "Якщо треба. ", ""), ("Звісно. ", "Яке здивування. ", ""), ("Aye. ", "Капітане. ", ""), ("Спокійно. ", "Легко. ", ""), ("Так. ", "Так, мій скарбе. ", "")),
            numbers=["нуль", "один", "два", "три", "чотири", "пять", "шість", "сім", "вісім", "девять", "десять", "одинадцять", "дванадцять", "тринадцять", "чотирнадцять", "пятнадцять", "шістнадцять", "сімнадцять", "вісімнадцять", "девятнадцять", "двадцять", "тридцять", "сорок", "пятдесят", "шістдесят", "сімдесят", "вісімдесят", "девяносто", "сто"],
            and_join=" і ",
            or_join=" або ",
        ),
    ]
