"""Remaining Assist lexicons with native domain words."""

from __future__ import annotations

from lang_packs.core import pack
from lang_packs.voices import spoken_home, triples


def leftover() -> list[dict]:
    out: list[dict] = []
    for group in (_eu_west(), _baltics(), _se_asia(), _indic(), _caucasus()):
        out.extend(group)
    return out


def _eu_west() -> list[dict]:
    return [
        pack(
            "cy", "Cymraeg", ["cy"],
            on=["tro"], off=["diffodd"], open_=["agor"], close=["cau"], query=["beth"], set_=["gosod"],
            light=["golau"], cover=["llen"], climate=["gwres"], media=["teledu"], lock=["clo"], door=["drws"],
            timer=["amserydd"], list_=["rhestr"], fan=["gwyntyll"], vacuum=["sugnwr"], scene=["golygfa"],
            fillers=["y", "yn"], and_=["a"], or_=["neu"], yes=["ie"], all_=["pob"],
            living="ystafell", kitchen="cegin",
            unknown="Do ddeallais i ddim. Dywedwch pa olau i'w droi ymlaen, er enghraifft.", need_on="Beth i droi ymlaen?", need_off="Beth i ddiffodd?", confirm="Wir?",
            spoken=spoken_home("Iawn, rwy'n gollwng y frawddeg olaf.", "{target} yn ymlaen.", "{target} yn diffodd.", "{target} yn newid.", "Y tymheredd {loc}.", "Rwy'n edrych ar {target}.", "Mae'r chwarae wedi seibio.", "Mae'r chwarae yn parhau.", "Y trac nesaf.", "Y trac blaenorol.", "Sain wedi'i dawelu.", "Sain yn ol.", "Mae'r sain wedi'i gosod.", "Ar y rhestr."),
            personality=triples(("Iawn. ", "Gyda phleser. ", ""), ("Wedi dal. ", "Wedi gwneud. ", ""), ("Gwnaf hynny nawr. ", "Popeth yn iawn. ", ""), ("Ymlaen a ni. ", "Neis. ", ""), ("Iawn te. ", "Os rhaid. ", ""), ("Wrth gwrs. ", "Beth o syndod. ", ""), ("Aye. ", "Gapten. ", ""), ("Hawdd. ", "Tawel. ", ""), ("Ie. ", "Ie, fy nhrysor. ", "")),
            numbers=["dim", "un", "dau", "tri", "pedwar", "pump", "chwech", "saith", "wyth", "naw", "deg", "unarddeg", "deuddeg", "triardeg", "pedwarardeg", "pymtheg", "unarsbymtheg", "dauarsbymtheg", "deunaw", "pedwararbytheg", "ugain", "degarddeg", "deugain", "degadeugain", "trigain", "degatrigain", "pedwarugain", "degapedwarugain", "cant"],
            and_join=" a ", or_join=" neu ",
        ),
        pack(
            "et", "Eesti", ["et", "et-EE"],
            on=["lulita"], off=["kustuta"], open_=["ava"], close=["sulge"], query=["mis"], set_=["sea"],
            light=["vali"], cover=["kardin"], climate=["kyte"], media=["teler"], lock=["lukk"], door=["uks"],
            timer=["taimer"], list_=["nimekiri"], fan=["ventilaator"], vacuum=["tolmuimeja"], scene=["stseen"],
            fillers=["see", "ja"], and_=["ja"], or_=["voi"], yes=["jah"], all_=["koik"],
            living="elutuba", kitchen="kook",
            unknown="Ma ei saanud aru. Utle naiteks, milline valgus sisse panna.", need_on="Mis sisse?", need_off="Mis valja?", confirm="Kas toesti?",
            spoken=spoken_home("Selge, viimase lause jatan vahele.", "{target} on sees.", "{target} on valjas.", "{target} vahetub.", "Temperatuur {loc}.", "Vaatan {target}.", "Taasesitus on pausil.", "Taasesitus jatkuu.", "Jargmine lugu.", "Eelmine lugu.", "Heli on maas.", "Heli on peal.", "Helitugevus on seatud.", "On nimekirjas."),
            personality=triples(("Hasti. ", "Meelsasti. ", ""), ("Selge. ", "Tehtud. ", ""), ("Teen kohe. ", "Koik korras. ", ""), ("Laks. ", "Kenake. ", ""), ("Olgu. ", "Kui peab. ", ""), ("Muidugi. ", "Milline ullatus. ", ""), ("Aye. ", "Kapten. ", ""), ("Rahulikult. ", "Kerge. ", ""), ("Jah. ", "Jah, mu kallis. ", "")),
            numbers=["null", "uks", "kaks", "kolm", "neli", "viis", "kuus", "seitse", "kaheksa", "uheksa", "kymme", "uksteist", "kaksteist", "kolmteist", "neliteist", "viisteist", "kuusteist", "seitseteist", "kaheksateist", "uheksateist", "kakskymmend", "kolmkymmend", "nelikymmend", "viiskymmend", "kuuskymmend", "seitsekymmend", "kaheksakymmend", "uheksakymmend", "sada"],
            and_join=" ja ", or_join=" voi ",
        ),
        pack(
            "eu", "Euskara", ["eu", "eu-ES"],
            on=["piztu"], off=["itzali"], open_=["ireki"], close=["itxi"], query=["zer"], set_=["jarri"],
            light=["argia"], cover=["gortina"], climate=["berogailu"], media=["telebista"], lock=["sarraila"], door=["atea"],
            timer=["tenporizadorea"], list_=["zerrenda"], fan=["haizagailua"], vacuum=["xurgagailua"], scene=["eszena"],
            fillers=["bat", "eta"], and_=["eta"], or_=["edo"], yes=["bai"], all_=["denak"],
            living="egongela", kitchen="sukaldea",
            unknown="Ez dut ulertu. Esan adibidez zein argi piztu.", need_on="Zer piztu?", need_off="Zer itzali?", confirm="Benetan?",
            spoken=spoken_home("Ados, azken esaldia alde batera uzten dut.", "{target} piztuta dago.", "{target} itzalita dago.", "{target} aldatzen da.", "Tenperatura {loc}.", "{target} begiratzen ari naiz.", "Erreprodukzioa pausatuta dago.", "Erreprodukzioak jarraitzen du.", "Hurrengo pista.", "Aurreko pista.", "Soinua isilduta.", "Soinua piztuta.", "Bolumena ezarrita dago.", "Zerrendan dago."),
            personality=triples(("Oso ondo. ", "Pozik. ", ""), ("Ados. ", "Eginda. ", ""), ("Oraintxe. ", "Denak ondo. ", ""), ("Goazen. ", "Polita. ", ""), ("Tira. ", "Behar bada. ", ""), ("Noski. ", "Ze sorpresa. ", ""), ("Aye. ", "Kapitaina. ", ""), ("Lasai. ", "Erraza. ", ""), ("Bai. ", "Bai, nire altxorra. ", "")),
            numbers=["zero", "bat", "bi", "hiru", "lau", "bost", "sei", "zazpi", "zortzi", "bederatzi", "hamar", "hamaika", "hamabi", "hamahiru", "hamalau", "hamabost", "hamasei", "hamazazpi", "hemezortzi", "hemeretzi", "hogei", "hogeitahamar", "berrogei", "berrogeitahamar", "hirurogei", "hirurogeitahamar", "laurogei", "laurogeitahamar", "ehun"],
            and_join=" eta ", or_join=" edo ",
        ),
        pack(
            "ga", "Gaeilge", ["ga", "ga-IE"],
            on=["cas"], off=["much"], open_=["oscail"], close=["dun"], query=["cad"], set_=["socraigh"],
            light=["solas"], cover=["cuirtin"], climate=["teas"], media=["teilifis"], lock=["glas"], door=["doras"],
            timer=["amadoir"], list_=["liosta"], fan=["fean"], vacuum=["folusaire"], scene=["radharc"],
            fillers=["an", "sa"], and_=["agus"], or_=["no"], yes=["ta"], all_=["uile"],
            living="seomra", kitchen="cistin",
            unknown="Nior thuig me. Abair mar shampla cen solas le casadh.", need_on="Cad a chasfaidh me?", need_off="Cad a mhuchfaidh me?", confirm="I ndairire?",
            spoken=spoken_home("Ceart go leor, fagaim an abairt dheireanach ar lar.", "Ta {target} ar siul.", "Ta {target} muchta.", "Ta {target} ag athru.", "An teocht {loc}.", "Taim ag seiceail {target}.", "Ta an seinm ar sos.", "Ta an seinm ar siul aris.", "An chead rian eile.", "An rian roimhe.", "Fuaim muchta.", "Fuaim ar siul.", "Ta an airde socraithe.", "Ar an liosta."),
            personality=triples(("Go maith. ", "Le pleisiur. ", ""), ("Faighte. ", "Deanta. ", ""), ("Deanaim e anois. ", "Ta gach rud ceart. ", ""), ("Ar aghaidh linn. ", "Deas. ", ""), ("Ceart go leor. ", "Mas eigean. ", ""), ("Ar ndoigh. ", "Nach ionadh. ", ""), ("Aye. ", "Captaen. ", ""), ("Easca. ", "Socair. ", ""), ("Ta. ", "Ta, a stor. ", "")),
            numbers=["naid", "aon", "do", "tri", "ceathair", "cuig", "se", "seacht", "ocht", "naoi", "deich", "aonndead", "doceag", "triceag", "ceathairdeag", "cuigdeag", "sedeag", "seachtdead", "ochtdead", "naoideag", "fiche", "triocha", "daichead", "caoga", "seasca", "seachtod", "ochto", "nocad", "cead"],
            and_join=" agus ", or_join=" no ",
        ),
        pack(
            "gl", "Galician", ["gl", "gl-ES"],
            on=["acende"], off=["apaga"], open_=["abre"], close=["pecha"], query=["que"], set_=["pon"],
            light=["luz"], cover=["cortina"], climate=["calefaccion"], media=["tele"], lock=["pechadura"], door=["porta"],
            timer=["temporizador"], list_=["lista"], fan=["ventilador"], vacuum=["aspiradora"], scene=["escena"],
            fillers=["a", "o", "en"], and_=["e"], or_=["ou"], yes=["si"], all_=["todo"],
            living="salon", kitchen="cociña",
            unknown="Non o entendin. Di por exemplo que luz acender.", need_on="Que acendo?", need_off="Que apago?", confirm="De verdade?",
            spoken=spoken_home("Vale, deixo a ultima frase.", "{target} esta aceso.", "{target} esta apagado.", "{target} cambia.", "A temperatura {loc}.", "Miro {target}.", "Reproducion en pausa.", "Reproducion segue.", "Pista seguinte.", "Pista anterior.", "Son apagado.", "Son aceso.", "O volume esta posto.", "Esta na lista."),
            personality=triples(("Moi ben. ", "Con pracer. ", ""), ("Feito. ", "Vale. ", ""), ("Agora mesmo. ", "Todo ben. ", ""), ("Imos. ", "Que ben. ", ""), ("Bueno. ", "Se fai falta. ", ""), ("Claro. ", "Que sorpresa. ", ""), ("Aye. ", "Capitan. ", ""), ("Tranqui. ", "Suave. ", ""), ("Si. ", "Si, meu tesouro. ", "")),
            numbers=["cero", "un", "dous", "tres", "catro", "cinco", "seis", "sete", "oito", "nove", "dez", "once", "doce", "trece", "catorce", "quince", "dezaseis", "dezasete", "dezaoito", "dezanove", "vinte", "trinta", "corenta", "cincuenta", "sesenta", "setenta", "oitenta", "noventa", "cen"],
            and_join=" e ", or_join=" ou ",
        ),
        pack(
            "is", "islenska", ["is", "is-IS"],
            on=["kveiktu"], off=["slokktu"], open_=["opnadu"], close=["lokadu"], query=["hvad"], set_=["settu"],
            light=["ljos"], cover=["gardina"], climate=["hiti"], media=["sjonvarp"], lock=["las"], door=["hurd"],
            timer=["timi"], list_=["listi"], fan=["viftu"], vacuum=["ryksuga"], scene=["sena"],
            fillers=["thad", "i"], and_=["og"], or_=["eda"], yes=["ja"], all_=["allt"],
            living="stofa", kitchen="eldhus",
            unknown="Eg skildi thetta ekki. Segdu til daemis hvada ljos a ad kveikja.", need_on="Hvad a ad kveikja?", need_off="Hvad a ad slokkva?", confirm="I alvoru?",
            spoken=spoken_home("Allt i lagi, eg sleppi sidustu setningunni.", "{target} er kveikt.", "{target} er slokkt.", "{target} skiptir.", "Hitinn {loc}.", "Eg skoda {target}.", "Spilun er i bid.", "Spilun heldur afram.", "Naesta lag.", "Fyrra lag.", "Hljod er slokkt.", "Hljod er kveikt.", "Hljodstyrkurinn er stilltur.", "A listanum."),
            personality=triples(("Gott. ", "Gjarnan. ", ""), ("Skil. ", "Buid. ", ""), ("Geri thad strax. ", "Allt i lagi. ", ""), ("Forum. ", "Fint. ", ""), ("Allt i lagi. ", "Ef eg verd. ", ""), ("Audvitad. ", "Hvada undrun. ", ""), ("Aye. ", "Skipstjori. ", ""), ("Rolegt. ", "Lett. ", ""), ("Ja. ", "Ja, minn dyrgripur. ", "")),
            numbers=["null", "einn", "tveir", "thrir", "fjorir", "fimm", "sex", "sjo", "atta", "niu", "tiu", "ellefu", "tolf", "threttan", "fjortan", "fimtan", "sextan", "saujan", "atjan", "nitjan", "tuttugu", "thrjatiu", "fjortiu", "fimmtiu", "sextiu", "sjotiu", "attatiu", "niutiu", "hundrad"],
            and_join=" og ", or_join=" eda ",
        ),
        pack(
            "lb", "Letzebuergesch", ["lb", "lb-LU"],
            on=["maach"], off=["maachaus"], open_=["opmaachen"], close=["zoumaachen"], query=["wat"], set_=["stell"],
            light=["luucht"], cover=["riddo"], climate=["heizung", "ac"], media=["tele"], lock=["schlass"], door=["dir"],
            timer=["timer"], list_=["lescht"], fan=["ventilator"], vacuum=["staubsauger"], scene=["szen"],
            fillers=["d", "am"], and_=["an"], or_=["oder"], yes=["jo"], all_=["all"],
            living="wunnen", kitchen="kichen",
            unknown="Dat hunn ech net verstan. So zum Beispill, wei eng Luucht un soll.", need_on="Wat uschalten?", need_off="Wat ausschalten?", confirm="Wierklech?",
            spoken=spoken_home("Okay, de leschte Saz loossen ech ewech.", "{target} ass un.", "{target} ass aus.", "{target} wiesselt.", "D Temperatur {loc}.", "Ech kucken no {target}.", "Ofspilung ass pauseiert.", "Ofspilung leeft weider.", "Nachsten Titel.", "Viregten Titel.", "Toun ass aus.", "Toun ass un.", "D Lautstaerkt ass gesat.", "Steet op der Lescht."),
            personality=triples(("Ganz gutt. ", "Garen. ", ""), ("Geet. ", "Passt. ", ""), ("Machen ech direkt. ", "Alles gutt. ", ""), ("Loosst eis. ", "Schein. ", ""), ("Schon gutt. ", "Wann et muss sinn. ", ""), ("Natierlech. ", "Wat eng Iwwerraschung. ", ""), ("Aye. ", "Kapitan. ", ""), ("Easy. ", "Roueg. ", ""), ("Jo. ", "Jo, meng Schatz. ", "")),
            numbers=["null", "eent", "zwee", "drai", "veier", "fennef", "sechs", "siwen", "aacht", "neng", "zeng", "eelf", "zwielef", "draizeng", "veierzeng", "fofzeng", "siechzeng", "siwwenzeng", "uechtzeng", "nonzeng", "zwanzeg", "dresseg", "veierzeg", "fofzeg", "sechzeg", "siwwenzeg", "achtzeg", "nonzeg", "honnert"],
            extra_w={"on_particles": ["un"], "off_particles": ["aus"]},
            and_join=" an ", or_join=" oder ",
        ),
        pack(
            "kw", "kernewek", ["kw"],
            on=["enow"], off=["diffyg"], open_=["igeri"], close=["degea"], query=["pyth"], set_=["settya"],
            light=["golow"], cover=["curtayn"], climate=["tomder"], media=["pellwolok"], lock=["alhwedh"], door=["daras"],
            timer=["termyn"], list_=["rol"], fan=["gwyns"], vacuum=["sughva"], scene=["gweles"],
            fillers=["an", "yn"], and_=["ha"], or_=["po"], yes=["ya"], all_=["oll"],
            living="stafell", kitchen="kegin",
            unknown="Ny gonvedhis. Lever un golow dhe enowi, rag ensampel.", need_on="Pandra enowi?", need_off="Pandra dhiffygi?", confirm="Yn hwir?",
            spoken=spoken_home("Da lowr, an lavar diwettha a wraff vy gasa.", "{target} yw enowys.", "{target} yw difygys.", "{target} a janj.", "An tempredh {loc}.", "Yth esov ow mires orth {target}.", "An seni yw pausys.", "An seni a bes.", "An kerdh nessa.", "An kerdh kyns.", "Son yw difygys.", "Son yw enowys.", "An lev yw settys.", "War an rol."),
            personality=triples(("Da lowr. ", "Gans plesour. ", ""), ("Komprenys. ", "Gwrys. ", ""), ("Y hwrav henna lemmyn. ", "Puptra da. ", ""), ("Deun yn-rag. ", "Teg. ", ""), ("Da. ", "Mar kodh. ", ""), ("Yn sur. ", "Pyth a marth. ", ""), ("Aye. ", "Kapten. ", ""), ("Esbos. ", "Kosm. ", ""), ("Ya. ", "Ya, ow thesor. ", "")),
            numbers=["mann", "onan", "dew", "tri", "peswar", "pymp", "hwegh", "seyth", "eth", "naw", "dek", "udnek", "dewdhek", "trydhek", "peswardhek", "pymthek", "hwetek", "seytek", "etek", "nownsek", "ugens", "degwarnugens", "dewgens", "deghadewgens", "trigens", "deghatrigens", "peswarugens", "deghapeswarugens", "kans"],
            and_join=" ha ", or_join=" po ",
        ),
    ]


def _baltics() -> list[dict]:
    return [
        pack(
            "lt", "Lietuviu", ["lt", "lt-LT"],
            on=["ijunk"], off=["isjunk"], open_=["atidaryk"], close=["uzdaryk"], query=["kas"], set_=["nustatyk"],
            light=["sviesa"], cover=["uzuolaida"], climate=["sildymas"], media=["televizorius"], lock=["spyna"], door=["durys"],
            timer=["laikmatis"], list_=["sarasas"], fan=["ventiliatorius"], vacuum=["siurblys"], scene=["scena"],
            fillers=["tai", "ir"], and_=["ir"], or_=["arba"], yes=["taip"], all_=["viskas"],
            living="svetaine", kitchen="virtuve",
            unknown="Nesupratau. Pasakyk pavyzdziui, kokia sviesa ijungti.", need_on="Ka ijungti?", need_off="Ka isjungti?", confirm="Tikrai?",
            spoken=spoken_home("Gerai, paskutini sakini praleidziu.", "{target} ijungta.", "{target} isjungta.", "{target} persijungia.", "Temperatura {loc}.", "Ziuriu i {target}.", "Atkurimas pristabdytas.", "Atkurimas testiamas.", "Kitas takelis.", "Ankstesnis takelis.", "Garsas isjungtas.", "Garsas ijungtas.", "Garsumas nustatytas.", "Sarase."),
            personality=triples(("Labai gerai. ", "Mielai. ", ""), ("Aisku. ", "Atlikta. ", ""), ("Padarysiu iskart. ", "Viskas gerai. ", ""), ("Vaziuojam. ", "Smagu. ", ""), ("Gerai. ", "Jei reikia. ", ""), ("Zinoma. ", "Koks netiketumas. ", ""), ("Aye. ", "Kapitone. ", ""), ("Ramiai. ", "Lengva. ", ""), ("Taip. ", "Taip, mano brangusis. ", "")),
            numbers=["nulis", "vienas", "du", "trys", "keturi", "penki", "sesi", "septyni", "astuoni", "devyni", "desimt", "vienuolika", "dvylika", "trylika", "keturiolika", "penkiolika", "sesiolika", "septyniolika", "astuoniolika", "devyniolika", "dvidesimt", "trisdesimt", "keturiasdesimt", "penkiasdesimt", "sesiasdesimt", "septyniasdesimt", "astuoniasdesimt", "devyniasdesimt", "simtas"],
            and_join=" ir ", or_join=" arba ",
        ),
        pack(
            "lv", "Latviesu", ["lv", "lv-LV"],
            on=["iesledz"], off=["izsledz"], open_=["atver"], close=["aizver"], query=["kas"], set_=["iestati"],
            light=["gaisma"], cover=["aizkars"], climate=["apkure"], media=["televizors"], lock=["sledzene"], door=["durvis"],
            timer=["taimeris"], list_=["saraksts"], fan=["ventilators"], vacuum=["puteklusucejs"], scene=["scena"],
            fillers=["to", "un"], and_=["un"], or_=["vai"], yes=["ja"], all_=["viss"],
            living="istaba", kitchen="virtuve",
            unknown="Nesapratu. Pasaki piemeram, kuru gaismu ieslegt.", need_on="Ko ieslegt?", need_off="Ko izslegt?", confirm="Tiesam?",
            spoken=spoken_home("Labi, pedejo teikumu izlaidisu.", "{target} ir ieslegts.", "{target} ir izslegts.", "{target} parsledzas.", "Temperatura {loc}.", "Skatos uz {target}.", "Atskanosana ir pauzeta.", "Atskanosana turpinas.", "Nakama dziesma.", "Iepriekseja dziesma.", "Skana ir izslegta.", "Skana ir ieslegta.", "Skanjums ir iestatits.", "Saraksta."),
            personality=triples(("Labi. ", "Ar prieku. ", ""), ("Skaidrs. ", "Gatavs. ", ""), ("Darisu tulit. ", "Viss kartiba. ", ""), ("Ejam. ", "Jauki. ", ""), ("Labi. ", "Ja vajag. ", ""), ("Protams. ", "Kads parsteigums. ", ""), ("Aye. ", "Kapteini. ", ""), ("Mierigi. ", "Viegli. ", ""), ("Ja. ", "Ja, mans dargums. ", "")),
            numbers=["nulle", "viens", "divi", "tris", "cetri", "pieci", "sesi", "septini", "astoni", "devini", "desmit", "vienpadsmit", "divpadsmit", "trispadsmit", "cetrpadsmit", "piecpadsmit", "sespadsmit", "septinpadsmit", "astonpadsmit", "devinpadsmit", "divdesmit", "trisdesmit", "cetrdesmit", "piecdesmit", "sesdesmit", "septindesmit", "astondesmit", "devindesmit", "simts"],
            and_join=" un ", or_join=" vai ",
        ),
    ]


def _se_asia() -> list[dict]:
    return [
        pack(
            "id", "Bahasa Indonesia", ["id", "id-ID"],
            on=["nyalakan"], off=["matikan"], open_=["buka"], close=["tutup"], query=["apa"], set_=["setel"],
            light=["lampu"], cover=["tirai"], climate=["pemanas", "suhu", "ac"], media=["tv"], lock=["kunci"], door=["pintu"],
            timer=["timer"], list_=["daftar"], fan=["kipas"], vacuum=["vakum"], scene=["adegan"],
            fillers=["yang", "di"], and_=["dan"], or_=["atau"], yes=["ya"], all_=["semua"],
            living="ruang", kitchen="dapur",
            unknown="Saya tidak mengerti. Sebutkan misalnya lampu mana yang dinyalakan.", need_on="Nyalakan apa?", need_off="Matikan apa?", confirm="Benar?",
            spoken=spoken_home("Baik, saya melewatkan kalimat terakhir.", "{target} menyala.", "{target} mati.", "{target} berganti.", "Suhu {loc}.", "Saya cek {target}.", "Putar dijeda.", "Putar lanjut.", "Lagu berikutnya.", "Lagu sebelumnya.", "Suara dimatikan.", "Suara dinyalakan.", "Volume sudah diatur.", "Ada di daftar."),
            personality=triples(("Baik. ", "Dengan senang. ", ""), ("Oke. ", "Selesai. ", ""), ("Saya kerjakan sekarang. ", "Semua baik. ", ""), ("Ayo. ", "Bagus. ", ""), ("Ya sudah. ", "Kalau harus. ", ""), ("Tentu saja. ", "Sungguh kejutan. ", ""), ("Aye. ", "Kapten. ", ""), ("Santai. ", "Tenang. ", ""), ("Ya. ", "Ya, hartaku. ", "")),
            numbers=["nol", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan", "sembilan", "sepuluh", "sebelas", "duabelas", "tigabelas", "empatbelas", "limabelas", "enambelas", "tujuhbelas", "delapanbelas", "sembilanbelas", "duapuluh", "tigapuluh", "empatpuluh", "limapuluh", "enampuluh", "tujuhpuluh", "delapanpuluh", "sembilanpuluh", "seratus"],
            and_join=" dan ", or_join=" atau ",
        ),
        pack(
            "ms", "Bahasa Melayu", ["ms", "ms-MY"],
            on=["hidupkan"], off=["matikan"], open_=["buka"], close=["tutup"], query=["apa"], set_=["tetapkan"],
            light=["lampu"], cover=["langsir"], climate=["pendingin"], media=["tv"], lock=["kunci"], door=["pintu"],
            timer=["pemasa"], list_=["senarai"], fan=["kipas"], vacuum=["vakum"], scene=["adegan"],
            fillers=["yang", "di"], and_=["dan"], or_=["atau"], yes=["ya"], all_=["semua"],
            living="ruang", kitchen="dapur",
            unknown="Saya tidak faham. Contohnya beritahu lampu mana nak dihidupkan.", need_on="Hidupkan apa?", need_off="Matikan apa?", confirm="Betul?",
            spoken=spoken_home("Baik, saya tinggalkan ayat terakhir.", "{target} hidup.", "{target} mati.", "{target} bertukar.", "Suhu {loc}.", "Saya semak {target}.", "Mainan dijeda.", "Mainan diteruskan.", "Lagu seterusnya.", "Lagu sebelumnya.", "Bunyi dimatikan.", "Bunyi dihidupkan.", "Kelantangan sudah ditetapkan.", "Ada dalam senarai."),
            personality=triples(("Baik. ", "Dengan senang. ", ""), ("Faham. ", "Siap. ", ""), ("Saya buat sekarang. ", "Semua baik. ", ""), ("Jom. ", "Cantik. ", ""), ("Baiklah. ", "Kalau perlu. ", ""), ("Sudah tentu. ", "Alamak kejutan. ", ""), ("Aye. ", "Kapten. ", ""), ("Santai. ", "Tenang. ", ""), ("Ya. ", "Ya, permata ku. ", "")),
            numbers=["kosong", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "lapan", "sembilan", "sepuluh", "sebelas", "duabelas", "tigabelas", "empatbelas", "limabelas", "enambelas", "tujuhbelas", "lapanbelas", "sembilanbelas", "duapuluh", "tigapuluh", "empatpuluh", "limapuluh", "enampuluh", "tujuhpuluh", "lapanpuluh", "sembilanpuluh", "seratus"],
            and_join=" dan ", or_join=" atau ",
            extra_w={"lock_v": ["kuncikan"]},
        ),
        pack(
            "sw", "Kiswahili", ["sw", "sw-KE"],
            on=["washa"], off=["zima"], open_=["fungua"], close=["funga"], query=["nini"], set_=["weka"],
            light=["taa"], cover=["pazia"], climate=["joto"], media=["runinga"], lock=["kufuli"], door=["mlango"],
            timer=["kipima"], list_=["orodha"], fan=["feni"], vacuum=["kifagio"], scene=["tukio"],
            fillers=["ya", "katika"], and_=["na"], or_=["au"], yes=["ndiyo"], all_=["yote"],
            living="sebuleni", kitchen="jikonini",
            unknown="Sikuelewa. Sema kwa mfano taa gani iwaka.", need_on="Niwasha nini?", need_off="Nizime nini?", confirm="Kweli?",
            spoken=spoken_home("Sawa, ninaacha sentensi ya mwisho.", "{target} imewashwa.", "{target} imezimwa.", "{target} inabadilika.", "Joto {loc}.", "Ninatazama {target}.", "Uchezaji umesimamishwa.", "Uchezaji unaendelea.", "Wimbo unaofuata.", "Wimbo uliopita.", "Sauti imezimwa.", "Sauti imewashwa.", "Sauti imewekwa.", "Iko kwenye orodha."),
            personality=triples(("Vizuri. ", "Kwa furaha. ", ""), ("Sawa. ", "Imekamilika. ", ""), ("Nafanya sasa. ", "Yote sawa. ", ""), ("Twende. ", "Nzuri. ", ""), ("Sawa basi. ", "Ikiwa lazima. ", ""), ("Bila shaka. ", "Ajabu gani. ", ""), ("Aye. ", "Kapteni. ", ""), ("Poa. ", "Tulia. ", ""), ("Ndiyo. ", "Ndiyo, hazina yangu. ", "")),
            numbers=["sifuri", "moja", "mbili", "tatu", "nne", "tano", "sita", "saba", "nane", "tisa", "kumi", "kumimamoja", "kumimambili", "kumimataatu", "kumimanane", "kumimatano", "kumimasita", "kumimasaba", "kumimanane2", "kumimatisa", "ishirini", "thelathini", "arobaini", "hamsini", "sitini", "sabini", "themanini", "tisini", "mia"],
            and_join=" na ", or_join=" au ",
        ),
        pack(
            "vi", "Tieng Viet", ["vi", "vi-VN"],
            on=["bat"], off=["tat"], open_=["mo"], close=["dong"], query=["gi"], set_=["dat"],
            light=["bongden"], cover=["rem"], climate=["dieuhoa"], media=["tivi"], lock=["khoa"], door=["cua"],
            timer=["hen"], list_=["danhsach"], fan=["quat"], vacuum=["hutbui"], scene=["canh"],
            fillers=["cai", "o"], and_=["va"], or_=["hoac"], yes=["co"], all_=["tatca"],
            living="phongkhach", kitchen="bep",
            unknown="Toi khong hieu. Vi du hay noi den nao can bat.", need_on="Bat gi?", need_off="Tat gi?", confirm="That su?",
            spoken=spoken_home("Duoc, toi bo cau cuoi.", "{target} dang bat.", "{target} dang tat.", "{target} dang doi.", "Nhiet do {loc}.", "Toi dang xem {target}.", "Phat nhac dang tam dung.", "Phat nhac tiep tuc.", "Bai tiep theo.", "Bai truoc.", "Am thanh tat.", "Am thanh bat.", "Am luong da dat.", "Da vao danhsach."),
            personality=triples(("Tot. ", "San long. ", ""), ("Hieu. ", "Xong. ", ""), ("Toi lam ngay. ", "On het. ", ""), ("Di nao. ", "Hay. ", ""), ("Thoi duoc. ", "Neu bat buoc. ", ""), ("Duong nhien. ", "That bat ngo. ", ""), ("Aye. ", "Thuyen truong. ", ""), ("De. ", "Yen. ", ""), ("Co. ", "Co, kho bau cua toi. ", "")),
            numbers=["khong", "mot", "hai", "ba", "bon", "nam", "sau", "bay", "tam", "chin", "muoi", "muoimot", "muoihai", "muoiba", "muoibon", "muoinam", "muoisau", "muoibay", "muoitam", "muoichin", "haimuoi", "bamuoi", "bonmuoi", "nammuoi", "saumuoi", "baymuoi", "tammuoi", "chinmuoi", "tram"],
            and_join=" va ", or_join=" hoac ",
        ),
    ]


def _indic() -> list[dict]:
    return [
        pack(
            "hi", "Hindi", ["hi", "hi-IN"], script="Deva",
            on=["jalao"], off=["bujhao"], open_=["kholo"], close=["band"], query=["kya"], set_=["set"],
            light=["batti"], cover=["parda"], climate=["garmi"], media=["tivi"], lock=["tala"], door=["darwaza"],
            timer=["timer"], list_=["suchi"], fan=["pankha"], vacuum=["jhadu"], scene=["drishya"],
            fillers=["ko", "mein"], and_=["aur"], or_=["ya"], yes=["haan"], all_=["sab"],
            living="baithak", kitchen="rasoi",
            unknown="Samajh nahi aaya. Jaise batao kaunsi batti jalani hai.", need_on="Kya jalana hai?", need_off="Kya bujhana hai?", confirm="Sach mein?",
            spoken=spoken_home("Theek hai, aakhri vakya chhod raha hoon.", "{target} jal raha hai.", "{target} band hai.", "{target} badal raha hai.", "Tapman {loc}.", "Main {target} dekh raha hoon.", "Playback ruk gaya.", "Playback chalu hai.", "Agli track.", "Pichli track.", "Aawaz band hai.", "Aawaz chalu hai.", "Aawaz set hai.", "Suchi par hai."),
            personality=triples(("Theek. ", "Khushi se. ", ""), ("Samajh gaya. ", "Ho gaya. ", ""), ("Abhi karta hoon. ", "Sab theek. ", ""), ("Chalo. ", "Achha. ", ""), ("Theek hai. ", "Agar zaroori hai. ", ""), ("Zaroor. ", "Kya aashcharya. ", ""), ("Aye. ", "Captain. ", ""), ("Aaram se. ", "Shaant. ", ""), ("Haan. ", "Haan, mere khazane. ", "")),
            numbers=["shunya", "ek", "do", "teen", "char", "panch", "chhah", "saat", "aath", "nau", "das", "gyarah", "barah", "terah", "chaudah", "pandrah", "solah", "satrah", "atharah", "unnis", "bees", "tees", "chalis", "pachas", "saath", "sattar", "assi", "nabbe", "sau"],
            and_join=" aur ", or_join=" ya ",
        ),
        pack(
            "bn", "Bangla", ["bn", "bn-BD"], script="Beng",
            on=["jalao"], off=["nibhao"], open_=["khol"], close=["bondho"], query=["ki"], set_=["set"],
            light=["alo"], cover=["porda"], climate=["gorom"], media=["tivi"], lock=["tala"], door=["dorja"],
            timer=["timer"], list_=["talika"], fan=["pakha"], vacuum=["jharu"], scene=["drishyo"],
            fillers=["ke", "te"], and_=["ebong"], or_=["ba"], yes=["hyan"], all_=["sob"],
            living="bosar", kitchen="ranna",
            unknown="Bujhte parini. Jemon bolo kon alo jalate hobe.", need_on="Ki jalabo?", need_off="Ki nibhabo?", confirm="Sotti?",
            spoken=spoken_home("Thik ache, shesh bakyo chhere dichhi.", "{target} jwalchhe.", "{target} nibhano.", "{target} badlachhe.", "Tapmatra {loc}.", "Ami {target} dekhchhi.", "Playback theme ache.", "Playback cholchhe.", "Porer gaan.", "Ager gaan.", "Awaj bondho.", "Awaj chalu.", "Awaj set kora.", "Talikay ache."),
            personality=triples(("Bhalo. ", "Khushi te. ", ""), ("Bujhechi. ", "Hoyeche. ", ""), ("Ekhon korchi. ", "Sob thik. ", ""), ("Cholo. ", "Sundor. ", ""), ("Thik. ", "Jodi lage. ", ""), ("Obosshoi. ", "Ki chomotkar. ", ""), ("Aye. ", "Captain. ", ""), ("Aaram. ", "Shanto. ", ""), ("Hyan. ", "Hyan, amar ratno. ", "")),
            numbers=["shunno", "ek", "dui", "tin", "char", "panch", "chhoy", "sat", "at", "noy", "dosh", "egaro", "baro", "tero", "choddo", "ponero", "sholo", "shotero", "atharo", "unish", "bish", "trish", "chollish", "ponchash", "shat", "shottor", "ashi", "nobboi", "sho"],
            and_join=" ebong ", or_join=" ba ",
        ),
        pack(
            "gu", "Gujarati", ["gu", "gu-IN"], script="Gujr",
            on=["chalu"], off=["bandh"], open_=["kholo"], close=["bandhkaro"], query=["shu"], set_=["set"],
            light=["prakash"], cover=["pado"], climate=["garmi"], media=["tivi"], lock=["talu"], door=["darwajo"],
            timer=["timer"], list_=["yadi"], fan=["pankho"], vacuum=["jhadu"], scene=["drashya"],
            fillers=["ne", "ma"], and_=["ane"], or_=["athva"], yes=["ha"], all_=["badhu"],
            living="orado", kitchen="rasodu",
            unknown="Samajayu nahi. Udaharan tarike kaho ke prakaash chalu karvu.", need_on="Shu chalu?", need_off="Shu bandh?", confirm="Kharu?",
            spoken=spoken_home("Saras, chhelo vakya hu chhodu chhu.", "{target} chalu chhe.", "{target} bandh chhe.", "{target} badle chhe.", "Tapman {loc}.", "Hu {target} jovu chhu.", "Playback thaambyu.", "Playback chalu chhe.", "Aagli track.", "Paachhli track.", "Avaj bandh.", "Avaj chalu.", "Avaj set chhe.", "Yadi par chhe."),
            personality=triples(("Saras. ", "Anand thi. ", ""), ("Samajyu. ", "Thayu. ", ""), ("Have karu chhu. ", "Badhu saras. ", ""), ("Chalo. ", "Saru. ", ""), ("Theek. ", "Jo joiye. ", ""), ("Chek. ", "Shu aashcharya. ", ""), ("Aye. ", "Captain. ", ""), ("Shaant. ", "Saral. ", ""), ("Ha. ", "Ha, mara khajana. ", "")),
            numbers=["shunya", "ek", "be", "tran", "char", "panch", "chha", "sat", "ath", "nav", "das", "agiyar", "bar", "ter", "chaud", "pandar", "sol", "sattar", "adhar", "oganish", "vis", "tris", "chalis", "pachas", "sath", "sitter", "ensi", "nevu", "so"],
            and_join=" ane ", or_join=" athva ",
        ),
        pack(
            "kn", "Kannada", ["kn", "kn-IN"], script="Knda",
            on=["hachchu"], off=["arisu"], open_=["tere"], close=["muchchu"], query=["enu"], set_=["hondisu"],
            light=["belaku"], cover=["parade"], climate=["bisi"], media=["tivi"], lock=["biga"], door=["bagilu"],
            timer=["timer"], list_=["patti"], fan=["fanu"], vacuum=["gudisu"], scene=["drishya"],
            fillers=["annu", "alli"], and_=["mattu"], or_=["athava"], yes=["haudu"], all_=["ella"],
            living="hallige", kitchen="aduge",
            unknown="Artha agalilla. Udaharanege yava belaku hachchabeku endu heli.", need_on="Enu hachchuvudu?", need_off="Enu arisuvudu?", confirm="Nijavagi?",
            spoken=spoken_home("Sari, koneya vaakya bittu biduttene.", "{target} hachchide.", "{target} ariside.", "{target} badaluttide.", "Ushnata {loc}.", "Naanu {target} noduttiddene.", "Playback nintide.", "Playback munduvariyuttide.", "Munde haadu.", "Hinde haadu.", "Dhvani ariside.", "Dhvani hachchide.", "Dhvani hondiside.", "Pattiyalli ide."),
            personality=triples(("Chennagide. ", "Santosha. ", ""), ("Tiliyitu. ", "Aayitu. ", ""), ("Eega maduttene. ", "Ella chennagide. ", ""), ("Hogona. ", "Chennagide. ", ""), ("Sari. ", "Aagabekadre. ", ""), ("Khandita. ", "Enu surprise. ", ""), ("Aye. ", "Captain. ", ""), ("Nidhanavagide. ", "Shaanta. ", ""), ("Haudu. ", "Haudu, nanna ratna. ", "")),
            numbers=["sonne", "ondu", "eradu", "muru", "nalku", "aidu", "aru", "elu", "entu", "ombattu", "hattu", "hannondu", "hanneradu", "hadimuru", "hadinalku", "hadinaidu", "hadinaru", "hadinelu", "hadinentu", "hattombattu", "ipattu", "muvattu", "nalavattu", "aivattu", "aravattu", "eppattu", "embattu", "tombattu", "nuru"],
            and_join=" mattu ", or_join=" athava ",
        ),
        pack(
            "ml", "Malayalam", ["ml", "ml-IN"], script="Mlym",
            on=["theli"], off=["anaykku"], open_=["thurakku"], close=["adaykku"], query=["enth"], set_=["set"],
            light=["vilakku"], cover=["jada"], climate=["chudu"], media=["tivi"], lock=["poott"], door=["vathil"],
            timer=["timer"], list_=["pattika"], fan=["fan"], vacuum=["varal"], scene=["rangam"],
            fillers=["ennu", "il"], and_=["um"], or_=["allenkil"], yes=["athe"], all_=["ellam"],
            living="muriyil", kitchen="adukkala",
            unknown="Manasilayilla. Udaharanathinu ethu vilakku thelikkanam ennu parayu.", need_on="Enth thelikkanam?", need_off="Enth anaykkanam?", confirm="Sherikkum?",
            spoken=spoken_home("Sheri, avasanam sentence njan ozhivakku.", "{target} thelinju.", "{target} ananju.", "{target} maattunnu.", "Temperature {loc}.", "Njan {target} nokkunnu.", "Playback ninnirikkunnu.", "Playback thudarunnu.", "Adutha paattu.", "Munpathe paattu.", "Shabdam ananju.", "Shabdam thelinju.", "Shabdam set aayi.", "Pattikayil undu."),
            personality=triples(("Nannayi. ", "Santhoshathode. ", ""), ("Manasilayi. ", "Aayi. ", ""), ("Ippol cheyyunnu. ", "Ellam sheriyanu. ", ""), ("Pokaam. ", "Nalla. ", ""), ("Sheri. ", "Vendi engil. ", ""), ("Theerchayayi. ", "Enthu surprise. ", ""), ("Aye. ", "Captain. ", ""), ("Shaantam. ", "Easy. ", ""), ("Athe. ", "Athe, ente nidhi. ", "")),
            numbers=["poojyam", "onnu", "randu", "munnu", "naalu", "anchu", "aaru", "ezhu", "ettu", "onpathu", "pathu", "pathinonnu", "panthrandu", "pathimunnu", "pathinaalu", "pathinanchu", "pathinaaru", "pathinezhu", "pathinettu", "pathonpathu", "irupathu", "muppathu", "nalpathu", "anpathu", "arupathu", "ezhupathu", "enpathu", "thonnooru", "nooru"],
            and_join=" um ", or_join=" allenkil ",
        ),
        pack(
            "mr", "Marathi", ["mr", "mr-IN"], script="Deva",
            on=["chalu"], off=["band"], open_=["ughad"], close=["bandkar"], query=["kay"], set_=["set"],
            light=["diva"], cover=["padda"], climate=["ushnata"], media=["tivi"], lock=["kulup"], door=["darwaja"],
            timer=["timer"], list_=["yadi"], fan=["pankha"], vacuum=["jhadu"], scene=["drishya"],
            fillers=["la", "madhye"], and_=["ani"], or_=["kinva"], yes=["ho"], all_=["sarva"],
            living="baithak", kitchen="svayampak",
            unknown="Kalale nahi. Udahranarth sanga konta diva chalu karaycha.", need_on="Kay chalu?", need_off="Kay band?", confirm="Kharokhar?",
            spoken=spoken_home("Theek, shevatche vakya mi sodto.", "{target} chalu aahe.", "{target} band aahe.", "{target} badalte.", "Tapman {loc}.", "Mi {target} baghto.", "Playback thambale.", "Playback suru aahe.", "Pudhcha gaana.", "Magcha gaana.", "Aawaj band.", "Aawaj chalu.", "Aawaj set aahe.", "Yadi var aahe."),
            personality=triples(("Theek. ", "Anandane. ", ""), ("Kalale. ", "Zale. ", ""), ("Aata karto. ", "Sagla theek. ", ""), ("Chala. ", "Chhan. ", ""), ("Theek aahe. ", "Jar garaj asel. ", ""), ("Nakkich. ", "Kay surprise. ", ""), ("Aye. ", "Captain. ", ""), ("Shant. ", "Soppa. ", ""), ("Ho. ", "Ho, majhya khajinaya. ", "")),
            numbers=["shunya", "ek", "don", "tin", "char", "pach", "saha", "sat", "aath", "nau", "daha", "akra", "bara", "tera", "chauda", "pandhra", "sola", "satra", "athra", "ekonis", "vis", "tis", "chalis", "pannas", "sath", "sattar", "aishi", "navvad", "shambhar"],
            and_join=" ani ", or_join=" kinva ",
        ),
        pack(
            "ta", "Tamil", ["ta"], script="Taml",
            on=["eru"], off=["anai"], open_=["thira"], close=["moodu"], query=["enna"], set_=["amai"],
            light=["vilakku"], cover=["thirai"], climate=["veppam"], media=["tivi"], lock=["poottu"], door=["kathavu"],
            timer=["timer"], list_=["pattiyal"], fan=["visiri"], vacuum=["thudaippu"], scene=["kaatchi"],
            fillers=["ai", "il"], and_=["matrum"], or_=["allathu"], yes=["aam"], all_=["ellam"],
            living="arai", kitchen="samaiyal",
            unknown="Puriyavillai. Udaharanamaga eppadi vilakku eru endru sollu.", need_on="Enna erukka?", need_off="Enna anaikka?", confirm="Unmaiyil?",
            spoken=spoken_home("Sari, last vaakiyam vidaikkiren.", "{target} eriyuthu.", "{target} anaithu.", "{target} maatrugirathu.", "Veppam {loc}.", "Naan {target} paarkiren.", "Playback nindrathu.", "Playback thodarugirathu.", "Adutha paattu.", "Munthaia paattu.", "Oli anaithu.", "Oli eriyuthu.", "Oli amaikkappattathu.", "Pattiyalil ullathu."),
            personality=triples(("Nandraga. ", "Santhoshama. ", ""), ("Purinjiduchu. ", "Aachu. ", ""), ("Ippo seiren. ", "Ellam nandraga. ", ""), ("Povom. ", "Nalla. ", ""), ("Sari. ", "Vendi irundha. ", ""), ("Kandippa. ", "Enna surprise. ", ""), ("Aye. ", "Captain. ", ""), ("Amaidhi. ", "Easy. ", ""), ("Aam. ", "Aam, en nidhi. ", "")),
            numbers=["poojyam", "onru", "irandu", "moondru", "naangu", "ainthu", "aaru", "ezhu", "ettu", "onpathu", "pathu", "pathinonru", "pannirandu", "pathimoondru", "pathinaangu", "pathinainthu", "pathinaaru", "pathinezhu", "pathinettu", "pathonpathu", "irupathu", "muppathu", "naarpathu", "aimpathu", "arupathu", "ezhupathu", "enpathu", "thonnooru", "nooru"],
            and_join=" matrum ", or_join=" allathu ",
        ),
        pack(
            "te", "Telugu", ["te", "te-IN"], script="Telu",
            on=["veliginchu"], off=["arpu"], open_=["theruvu"], close=["mooyi"], query=["emi"], set_=["set"],
            light=["velugu"], cover=["thera"], climate=["vedi"], media=["tivi"], lock=["talam"], door=["talupu"],
            timer=["timer"], list_=["jabita"], fan=["fanu"], vacuum=["udchu"], scene=["drishyam"],
            fillers=["ni", "lo"], and_=["mariyu"], or_=["leda"], yes=["avunu"], all_=["anni"],
            living="gadi", kitchen="vantagadi",
            unknown="Ardham kaledu. Udaharanaki evi velugu veliginchalo cheppu.", need_on="Emi veliginchali?", need_off="Emi arpali?", confirm="Nijanga?",
            spoken=spoken_home("Sare, chivari vaakya vadilesthunnanu.", "{target} veligindi.", "{target} aripoyindi.", "{target} marustundi.", "Ushnota {loc}.", "Nenu {target} chustunnanu.", "Playback aagindi.", "Playback nadustundi.", "Tarvata paata.", "Mundu paata.", "Dhvani aripoyindi.", "Dhvani veligindi.", "Dhvani set ayindi.", "Jabitallo undi."),
            personality=triples(("Baagundi. ", "Santoshamga. ", ""), ("Ardham ayindi. ", "Ayindi. ", ""), ("Ippudu chestunnanu. ", "Anni baagunnayi. ", ""), ("Podam. ", "Bagundi. ", ""), ("Sare. ", "Avassaram aithe. ", ""), ("Kesam. ", "Emi surprise. ", ""), ("Aye. ", "Captain. ", ""), ("Prashantam. ", "Easy. ", ""), ("Avunu. ", "Avunu, naa nidhi. ", "")),
            numbers=["sunna", "okati", "rendu", "moodu", "nalugu", "aidu", "aaru", "edu", "enimidi", "tommidi", "padi", "padakond", "pannendu", "padamudu", "padhnalugu", "padihenu", "padaharu", "padihedu", "paddenimidi", "pandommidi", "iravai", "muppai", "nalabhai", "yabhai", "aravai", "debbhai", "enabhai", "tombhai", "vanda"],
            and_join=" mariyu ", or_join=" leda ",
        ),
        pack(
            "pa", "Punjabi", ["pa"], script="Guru",
            on=["chalu"], off=["band"], open_=["kholh"], close=["bandkar"], query=["ki"], set_=["set"],
            light=["roshni"], cover=["parda"], climate=["garmi"], media=["tivi"], lock=["tala"], door=["darwaza"],
            timer=["timer"], list_=["suchi"], fan=["pakha"], vacuum=["jharu"], scene=["drish"],
            fillers=["nu", "vich"], and_=["ate"], or_=["jaan"], yes=["haan"], all_=["sabh"],
            living="vithak", kitchen="rasoi",
            unknown="Samajh nahi aya. Jiven daso kaunsi roshni chalu karni hai.", need_on="Ki chalu?", need_off="Ki band?", confirm="Sachmuch?",
            spoken=spoken_home("Theek, aakhri jumla chhad denda haan.", "{target} chalu hai.", "{target} band hai.", "{target} badalda hai.", "Tapman {loc}.", "Main {target} vekh riha haan.", "Playback rukia.", "Playback chalu hai.", "Agla gaana.", "Pichla gaana.", "Aawaz band.", "Aawaz chalu.", "Aawaz set hai.", "Suchi te hai."),
            personality=triples(("Theek. ", "Khushi naal. ", ""), ("Samajh gaya. ", "Ho gaya. ", ""), ("Hun karda haan. ", "Sab theek. ", ""), ("Chalo. ", "Vadiya. ", ""), ("Theek hai. ", "Je zaroorat hai. ", ""), ("Zaroor. ", "Ki hairani. ", ""), ("Aye. ", "Captain. ", ""), ("Aram naal. ", "Shaant. ", ""), ("Haan. ", "Haan, mere khazane. ", "")),
            numbers=["sifar", "ikk", "do", "tinn", "char", "panj", "che", "satt", "atth", "nau", "das", "gyaran", "baran", "teran", "chaudan", "pandran", "solan", "sataran", "atharan", "unni", "vih", "tih", "chali", "panjah", "satth", "sattar", "assi", "nabbe", "sau"],
            and_join=" ate ", or_join=" jaan ",
        ),
        pack(
            "ne", "Nepali", ["ne", "ne-NP"], script="Deva",
            on=["bal"], off=["nibhau"], open_=["khol"], close=["banda"], query=["ke"], set_=["set"],
            light=["batti"], cover=["parda"], climate=["tato"], media=["tivi"], lock=["tala"], door=["dhoka"],
            timer=["timer"], list_=["suchi"], fan=["pankha"], vacuum=["kucho"], scene=["drishya"],
            fillers=["lai", "ma"], and_=["ra"], or_=["wa"], yes=["ho"], all_=["sabai"],
            living="baithak", kitchen="bhansa",
            unknown="Bujhina. Udahran ko lagi kun batti balne ho bhanides.", need_on="Ke balne?", need_off="Ke nibhaune?", confirm="Sachai?",
            spoken=spoken_home("Thik cha, antim vakya chhodchu.", "{target} balyo.", "{target} nibhyo.", "{target} badlincha.", "Tapman {loc}.", "Ma {target} herchu.", "Playback rokio.", "Playback chaliraheko cha.", "Arko geet.", "Agillo geet.", "Awaj band.", "Awaj chalu.", "Awaj set cha.", "Suchima cha."),
            personality=triples(("Thik. ", "Khusi sath. ", ""), ("Bujhe. ", "Bhayo. ", ""), ("Ahile garchu. ", "Sabai thik. ", ""), ("Chalaun. ", "Ramro. ", ""), ("Thik cha. ", "Yadi parchha. ", ""), ("Avashya. ", "Ke aashcharya. ", ""), ("Aye. ", "Captain. ", ""), ("Shanta. ", "Sajilo. ", ""), ("Ho. ", "Ho, mero khajana. ", "")),
            numbers=["shunya", "ek", "dui", "tin", "char", "panch", "chha", "sat", "aath", "nau", "das", "eghara", "bahra", "tehra", "chaudha", "pandhra", "sorha", "satra", "athara", "unnais", "bis", "tis", "chalis", "pachas", "sathi", "sattari", "assi", "nabbe", "saya"],
            and_join=" ra ", or_join=" wa ",
        ),
    ]


def _caucasus() -> list[dict]:
    return [
        pack(
            "hy", "Armenian", ["hy", "hy-AM"], script="Armn",
            on=["miatsu"], off=["anjatir"], open_=["batsir"], close=["pakir"], query=["inch"], set_=["dir"],
            light=["luys"], cover=["varaguyr"], climate=["jerutsum"], media=["herustatsuyts"], lock=["kogpek"], door=["dur"],
            timer=["zhamachap"], list_=["tsutsak"], fan=["odapokhich"], vacuum=["poshekul"], scene=["tesaran"],
            fillers=["y", "um"], and_=["yev"], or_=["kam"], yes=["ayo"], all_=["bolor"],
            living="hyurasenyak", kitchen="khohanots",
            unknown="Chhasetskatsi. Asa orinak vor luysy miatsnem.", need_on="Inch miatsnem?", need_off="Inch anjatem?", confirm="Iskapes?",
            spoken=spoken_home("Lav, verjin nakadasutyune toghnum em.", "{target} miatsvats e.", "{target} anjatvats e.", "{target} poxvum e.", "Jermastichane {loc}.", "Yes nayum em {target}.", "Nvagarkume dadrvats e.", "Nvagarkume sharunakvum e.", "Hajord yerg.", "Nakhorde yerg.", "Dzayne anjatvats e.", "Dzayne miatsvats e.", "Tsayne sahmanvats e.", "Tsutsakum e."),
            personality=triples(("Lav. ", "Hachuyqov. ", ""), ("Hasatsa. ", "Arvats e. ", ""), ("Hima k anem. ", "Amen inch lav e. ", ""), ("Gnanq. ", "Geghetsik. ", ""), ("Lav. ", "Ete petq e. ", ""), ("Ihayt. ", "Inch anhakut. ", ""), ("Aye. ", "Kapitan. ", ""), ("Hangelist. ", "Hehst. ", ""), ("Ayo. ", "Ayo, im gandze. ", "")),
            numbers=["zro", "mek", "yerku", "yerek", "chors", "hing", "vets", "yot", "ut", "iny", "tasy", "tasnmek", "tasnyerku", "tasnyerek", "tasnchors", "tasnhing", "tasnvets", "tasnyot", "tasnut", "tasniny", "ksan", "yeresun", "karrasun", "hisun", "vatsun", "yotanasun", "utsun", "innsun", "haryur"],
            and_join=" yev ", or_join=" kam ",
        ),
        pack(
            "ka", "Georgian", ["ka", "ka-GE"], script="Geor",
            on=["charte"], off=["gamorte"], open_=["gakhseni"], close=["dakhure"], query=["ra"], set_=["daayene"],
            light=["sinatle"], cover=["parda"], climate=["gatboba"], media=["televizori"], lock=["saketi"], door=["kari"],
            timer=["taimeri"], list_=["sia"], fan=["ventilatori"], vacuum=["mtversasruti"], scene=["stsena"],
            fillers=["s", "shi"], and_=["da"], or_=["an"], yes=["ki"], all_=["kvela"],
            living="misagebi", kitchen="samzareulo",
            unknown="Ver gavige. Magalithad ra sinatle unda chavrtо.", need_on="Ra chavrtо?", need_off="Ra gamovrtо?", confirm="Martla?",
            spoken=spoken_home("Kargi, bolo winadadebas vtoveb.", "{target} chartulia.", "{target} gamortulia.", "{target} icvleba.", "Temperatura {loc}.", "Vukureb {target}.", "Dakvra shecherebulia.", "Dakvra grdzeldeba.", "Shemdegi trek.", "Tsina trek.", "Khma gamortulia.", "Khma chartulia.", "Khma dayenebulia.", "Siaze aris."),
            personality=triples(("Kargi. ", "Siasiaghnit. ", ""), ("Gavige. ", "Gaiketda. ", ""), ("Ekhla vaketeb. ", "Qvela kargi. ", ""), ("Tsavidet. ", "Lamazia. ", ""), ("Kargi. ", "Tu unda. ", ""), ("Rataqmaunda. ", "Ra siakhle. ", ""), ("Aye. ", "Kapitani. ", ""), ("Mshvidad. ", "Advilad. ", ""), ("Ki. ", "Ki, chemi sagandzuri. ", "")),
            numbers=["nuli", "erti", "ori", "sami", "otkhi", "khuti", "ekvsi", "shvidi", "rva", "tskhra", "ati", "tertmeti", "tormeti", "tsameti", "totkhmeti", "tkhutmeti", "tekvsmeti", "chvidmeti", "tvrameti", "tskhrameti", "otsi", "otsdaati", "ormotsi", "ormotsdaati", "samotsi", "samotsdaati", "otkhmotsi", "otkhmotsdaati", "asi"],
            and_join=" da ", or_join=" an ",
        ),
        pack(
            "mn", "Mongolian", ["mn", "mn-MN"], script="Cyrl",
            on=["asaa"], off=["untraa"], open_=["nee"], close=["khaa"], query=["yuu"], set_=["tokhiruul"],
            light=["gerel"], cover=["khoshig"], climate=["khalaalt"], media=["televiz"], lock=["tugjee"], door=["khaalga"],
            timer=["timer"], list_=["jagsaalt"], fan=["sens"], vacuum=["toos"], scene=["uzegdel"],
            fillers=["yg", "d"], and_=["ba"], or_=["esvel"], yes=["tiim"], all_=["bugd"],
            living="zochny", kitchen="galtogoo",
            unknown="Oilgosongui. Jishee n yamar gerel asaah ve gej khel.", need_on="Yuu asaakh ve?", need_off="Yuu untraakh ve?", confirm="Uneheer uu?",
            spoken=spoken_home("Za, suuliin ogulberiig orkhiy.", "{target} asaa.", "{target} untraa.", "{target} soligdono.", "Temperatur {loc}.", "Bi {target} shalgaj baina.", "Tokhioolt zogsson.", "Tokhioolt urgeljilne.", "Daraagiin duu.", "Omnokh duu.", "Duugui.", "Duu asaa.", "Duu tohiruulsan.", "Jagsaaltad baina."),
            personality=triples(("Za saikhan. ", "Bayartai. ", ""), ("Oilgoloo. ", "Hiilee. ", ""), ("Odoo khine. ", "Bugd saikhan. ", ""), ("Yavya. ", "Saikhan. ", ""), ("Za. ", "Heregtei bol. ", ""), ("Medeej. ", "Yamar gaihal. ", ""), ("Aye. ", "Captain. ", ""), ("Amjuun. ", "Amarkhan. ", ""), ("Tiim. ", "Tiim, minii erdene. ", "")),
            numbers=["teg", "neg", "khoyor", "gurav", "dorov", "tav", "zurgaa", "doloo", "naim", "yos", "arav", "arvanneg", "arvankhoyor", "arvangurav", "arvandorov", "arvantav", "arvanzurgaa", "arvandoloo", "arvannaim", "arvanyos", "khori", "guch", "doch", "tavi", "jar", "dal", "naya", "yer", "zuu"],
            and_join=" ba ", or_join=" esvel ",
        ),
    ]
