"""Nordic, German dialects, English UK, Portuguese BR, Afrikaans."""

from __future__ import annotations

from lang_packs.core import pack
from lang_packs.voices import spoken_home, triples


def north() -> list[dict]:
    return [
        pack(
            "da",
            "Dansk",
            ["da", "da-DK"],
            on=["taend"],
            off=["sluk"],
            open_=["aabn"],
            close=["luk"],
            query=["hvad", "hvordan"],
            set_=["saet"],
            light=["lys"],
            cover=["gardin"],
            climate=["varme", "temperatur"],
            media=["tv", "musik"],
            lock=["laas"],
            door=["doer"],
            timer=["timer"],
            list_=["liste"],
            fan=["ventilator"],
            vacuum=["stoevsuger"],
            scene=["scene"],
            fillers=["det", "en", "i"],
            and_=["og"],
            or_=["eller"],
            yes=["ja", "ok"],
            all_=["alle"],
            living="stue",
            kitchen="kokken",
            unknown="Det forstod jeg ikke. Sig for eksempel hvilket lys der skal taendes.",
            need_on="Hvad skal taendes?",
            need_off="Hvad skal slukkes?",
            confirm="Skal jeg virkelig?",
            spoken=spoken_home("Okay, den sidste saetning lader jeg falde.", "{target} er taendt.", "{target} er slukket.", "{target} skifter.", "Temperaturen {loc}.", "Jeg kigger pa {target}.", "Afspilning er sat pa pause.", "Afspilning korer igen.", "Naeste nummer.", "Forrige nummer.", "Lyden er slukket.", "Lyden er pa.", "Lydstyrken er sat.", "Star pa listen."),
            personality=triples(("Godt. ", "Gerne. ", ""), ("Okay. ", "Klaret. ", ""), ("Det gor jeg med det samme. ", "Alt i orden. ", ""), ("Sa korer vi. ", "Dejligt. ", ""), ("Na godt. ", "Hvis det skal vaere. ", ""), ("Selvfolgelig. ", "Sikken en overraskelse. ", ""), ("Aye. ", "Kaptajn. ", ""), ("Afslappet. ", "Rolig. ", ""), ("Ja. ", "Ja, min skat. ", "")),
            numbers=["nul", "en", "to", "tre", "fire", "fem", "seks", "syv", "otte", "ni", "ti", "elleve", "tolv", "tretten", "fjorten", "femten", "seksten", "sytten", "atten", "nitten", "tyve", "tredive", "fyrre", "halvtreds", "tres", "halvfjerds", "firs", "halvfems", "hundrede"],
            colors=[("rod", "red"), ("bla", "blue"), ("gron", "green"), ("gul", "yellow"), ("orange", "orange"), ("pink", "pink"), ("sort", "black"), ("hvid", "white"), ("lilla", "purple")],
            and_join=" og ",
            or_join=" eller ",
        ),
        pack(
            "nb",
            "Norsk Bokmål",
            ["nb", "nb-NO"],
            on=["skru"],
            off=["slaa"],
            open_=["apne"],
            close=["lukk"],
            query=["hva", "hvordan"],
            set_=["sett"],
            light=["lys"],
            cover=["gardin"],
            climate=["varme", "temperatur"],
            media=["tv", "musikk"],
            lock=["laas"],
            door=["dor"],
            timer=["timer"],
            list_=["liste"],
            fan=["vifte"],
            vacuum=["stovsuger"],
            scene=["scene"],
            fillers=["det", "en", "i"],
            and_=["og"],
            or_=["eller"],
            yes=["ja", "ok"],
            all_=["alle"],
            living="stue",
            kitchen="kjokken",
            unknown="Det skjonte jeg ikke. Si for eksempel hvilket lys som skal slas pa.",
            need_on="Hva skal skrus pa?",
            need_off="Hva skal slas av?",
            confirm="Skal jeg virkelig?",
            spoken=spoken_home("Greit, den siste setningen dropper jeg.", "{target} er pa.", "{target} er av.", "{target} bytter.", "Temperaturen {loc}.", "Jeg ser pa {target}.", "Avspilling er satt pa pause.", "Avspilling fortsetter.", "Neste spor.", "Forrige spor.", "Lyden er av.", "Lyden er pa.", "Volumet er satt.", "Star pa listen."),
            personality=triples(("Godt. ", "Gjerne. ", ""), ("Greit. ", "Fikset. ", ""), ("Gjor det med en gang. ", "Alt bra. ", ""), ("Da kjorer vi. ", "Fint. ", ""), ("Na vel. ", "Hvis jeg ma. ", ""), ("Selvsagt. ", "For en overraskelse. ", ""), ("Aye. ", "Kaptein. ", ""), ("Chill. ", "Rolig. ", ""), ("Ja. ", "Ja, min skatt. ", "")),
            numbers=["null", "en", "to", "tre", "fire", "fem", "seks", "sju", "atte", "ni", "ti", "elleve", "tolv", "tretten", "fjorten", "femten", "seksten", "sytten", "atten", "nitten", "tjue", "tretti", "forti", "femti", "seksti", "sytti", "atti", "nitti", "hundre"],
            colors=[("rod", "red"), ("bla", "blue"), ("gronn", "green"), ("gul", "yellow"), ("oransje", "orange"), ("rosa", "pink"), ("svart", "black"), ("hvit", "white"), ("lilla", "purple")],
            extra_w={"on_particles": ["pa"], "off_particles": ["av"]},
            and_join=" og ",
            or_join=" eller ",
        ),
        pack(
            "sv",
            "Svenska",
            ["sv", "sv-SE"],
            on=["tand"],
            off=["slack"],
            open_=["oppna"],
            close=["stang"],
            query=["vad", "hur"],
            set_=["satt"],
            light=["ljus"],
            cover=["gardin"],
            climate=["varme", "temperatur"],
            media=["tv", "musik"],
            lock=["las"],
            door=["dorr"],
            timer=["timer"],
            list_=["lista"],
            fan=["flakt"],
            vacuum=["dammsugare"],
            scene=["scen"],
            fillers=["det", "en", "i"],
            and_=["och"],
            or_=["eller"],
            yes=["ja", "ok"],
            all_=["alla"],
            living="vardagsrum",
            kitchen="kok",
            unknown="Jag hängde inte med. Säg till exempel vilket ljus som ska tändas.",
            need_on="Vad ska tandas?",
            need_off="Vad ska slackas?",
            confirm="Ska jag verkligen?",
            spoken=spoken_home("Okej, jag släpper den sista meningen.", "{target} är på.", "{target} är av.", "{target} växlar.", "Temperaturen {loc}.", "Jag tittar på {target}.", "Uppspelningen är pausad.", "Uppspelningen fortsätter.", "Nästa spår.", "Föregående spår.", "Ljudet är av.", "Ljudet är på.", "Volymen är satt.", "Står på listan."),
            personality=triples(("Mycket väl. ", "Gärna. ", ""), ("Okej. ", "Klart. ", ""), ("Gör det genast. ", "Allt bra. ", ""), ("Nu kör vi. ", "Fint. ", ""), ("Nåväl. ", "Om jag måste. ", ""), ("Javisst. ", "Vilken överraskning. ", ""), ("Aye. ", "Kapten. ", ""), ("Lugnt. ", "Schysst. ", ""), ("Ja. ", "Ja, min skatt. ", "")),
            numbers=["noll", "ett", "tva", "tre", "fyra", "fem", "sex", "sju", "atta", "nio", "tio", "elva", "tolv", "tretton", "fjorton", "femton", "sexton", "sjutton", "arton", "nitton", "tjugo", "trettio", "fyrtio", "femtio", "sextio", "sjuttio", "attio", "nittio", "hundra"],
            colors=[("rod", "red"), ("bla", "blue"), ("gron", "green"), ("gul", "yellow"), ("orange", "orange"), ("rosa", "pink"), ("svart", "black"), ("vit", "white"), ("lila", "purple")],
            and_join=" och ",
            or_join=" eller ",
        ),
        pack(
            "fi",
            "Suomi",
            ["fi", "fi-FI"],
            on=["sytyta"],
            off=["sammuta"],
            open_=["avaa"],
            close=["sulje"],
            query=["mika", "miten"],
            set_=["aseta"],
            light=["valo"],
            cover=["verho"],
            climate=["lampo", "lammitys"],
            media=["tv", "musiikki"],
            lock=["lukko"],
            door=["ovi"],
            timer=["ajastin"],
            list_=["lista"],
            fan=["tuuletin"],
            vacuum=["imuri"],
            scene=["kohtaus"],
            fillers=["se", "on", "ja"],
            and_=["ja"],
            or_=["tai"],
            yes=["kylla", "ok"],
            all_=["kaikki"],
            living="olohuone",
            kitchen="keittio",
            unknown="En saanut tuosta kiinni. Sano vaikka mika valo pitaa sytyttaa.",
            need_on="Mika sytytetaan?",
            need_off="Mika sammutetaan?",
            confirm="Teenko tama oikeasti?",
            spoken=spoken_home("Selva, jaan viimeisen lauseen pois.", "{target} on paalla.", "{target} on pois.", "{target} vaihtuu.", "Lampotila {loc}.", "Katson kohdetta {target}.", "Toisto on tauolla.", "Toisto jatkuu.", "Seuraava kappale.", "Edellinen kappale.", "Aani on pois.", "Aani on paalla.", "Voimakkuus on asetettu.", "On listalla."),
            personality=triples(("Hyva on. ", "Mielellani. ", ""), ("Okei. ", "Hoidettu. ", ""), ("Teen sen heti. ", "Kaikki hyvin. ", ""), ("Mennään. ", "Hienoa. ", ""), ("No selva. ", "Jos on pakko. ", ""), ("Totta kai. ", "Mika yllatys. ", ""), ("Aye. ", "Kapteeni. ", ""), ("Rennosti. ", "Rauhallisesti. ", ""), ("Kylla. ", "Kylla, kultaseni. ", "")),
            numbers=["nolla", "yksi", "kaksi", "kolme", "nelja", "viisi", "kuusi", "seitseman", "kahdeksan", "yhdeksan", "kymmenen", "yksitoista", "kaksitoista", "kolmetoista", "neljatoista", "viisitoista", "kuusitoista", "seitsemantoista", "kahdeksantoista", "yhdeksantoista", "kaksikymmenta", "kolmekymmenta", "neljakymmenta", "viisikymmenta", "kuusikymmenta", "seitsemankymmenta", "kahdeksankymmenta", "yhdeksankymmenta", "sata"],
            colors=[("punainen", "red"), ("sininen", "blue"), ("vihrea", "green"), ("keltainen", "yellow"), ("oranssi", "orange"), ("vaaleanpunainen", "pink"), ("musta", "black"), ("valkoinen", "white"), ("violetti", "purple")],
            and_join=" ja ",
            or_join=" tai ",
        ),
        pack(
            "de-CH",
            "Schwyzerdütsch",
            ["de-CH"],
            on=["mach"],
            off=["loesch"],
            open_=["ufmache"],
            close=["zue"],
            query=["was", "wie"],
            set_=["stell"],
            light=["liecht"],
            cover=["store", "vorhang"],
            climate=["heizig", "temperatur"],
            media=["fernseh", "musig"],
            lock=["schloss"],
            door=["tuer"],
            timer=["timer"],
            list_=["liste"],
            fan=["ventilator"],
            vacuum=["staubsauger"],
            scene=["szene"],
            fillers=["s", "im", "d", "bitte"],
            and_=["und"],
            or_=["oder"],
            yes=["ja", "ok"],
            all_=["alli"],
            living="wohnzimmer",
            kitchen="chuchi",
            unknown="Das han i nöd verstande. Sägs mer zum Biispil, weles Liecht aa söll.",
            need_on="Was söll i aamache?",
            need_off="Was söll i usmache?",
            confirm="Soll i das würklich mache?",
            spoken=spoken_home("Guet, de letscht Satz loh i weg.", "{target} isch aa.", "{target} isch uus.", "{target} wechselt.", "D Temperatur {loc}.", "I luege nach {target}.", "Wiedergab isch pausiert.", "Wiedergab lauft wieder.", "Nächste Titel.", "Vorherige Titel.", "Ton isch uus.", "Ton isch aa.", "Luutsterki steht.", "Stat uf de Liste."),
            personality=triples(("Guet. ", "Gärn. ", ""), ("Passt. ", "Klar. ", ""), ("Mach i gli. ", "Alles guet. ", ""), ("Lauft. ", "Schön. ", ""), ("Scho guet. ", "Wenns si muess. ", ""), ("Na klar. ", "Was für e Überraschig. ", ""), ("Aye. ", "Käpt'n. ", ""), ("Easy. ", "Ganz ruhig. ", ""), ("Ja. ", "Ja, mis Schätzli. ", "")),
            numbers=["null", "eis", "zwai", "drue", "vier", "foif", "saechs", "sibe", "acht", "nuen", "zae", "elf", "zwoelf", "drizae", "vierzae", "fuefzae", "saechzae", "sibzae", "achtzae", "nuenzae", "zwanzg", "drissg", "vierzg", "fuefzg", "saechzg", "sibzg", "achtzg", "nuenzg", "hundert"],
            extra_w={"on_particles": ["aa"], "off_particles": ["uus"], "scenes": ["filmabend"], "named": ["kugel"], "island": ["insel"], "ceiling": ["decke"]},
            colors=[("rot", "red"), ("blau", "blue"), ("gruen", "green"), ("gelb", "yellow"), ("orange", "orange"), ("rosa", "pink"), ("schwarz", "black"), ("weiss", "white"), ("violett", "purple")],
            and_join=" und ",
            or_join=" oder ",
        ),
        pack(
            "de-AT",
            "Deutsch (Österreich)",
            ["de-AT"],
            on=["mach"],
            off=["schalt"],
            open_=["oeffne"],
            close=["schliesse"],
            query=["was", "wie"],
            set_=["stell"],
            light=["licht", "leuchte"],
            cover=["vorhang", "jalousie"],
            climate=["heizung", "temperatur"],
            media=["fernseher", "musik"],
            lock=["schloss"],
            door=["tuer"],
            timer=["timer"],
            list_=["liste"],
            fan=["ventilator"],
            vacuum=["staubsauger"],
            scene=["szene"],
            fillers=["das", "den", "im", "bitte"],
            and_=["und"],
            or_=["oder"],
            yes=["ja", "ok"],
            all_=["alle"],
            living="wohnzimmer",
            kitchen="kuche",
            unknown="Des hob i ned verstanden. Sags ma zum Beispiel, welches Licht an soll.",
            need_on="Was soll ich einschalten?",
            need_off="Was soll ich ausschalten?",
            confirm="Soll ich das wirklich tun?",
            spoken=spoken_home("Passt, den letzten Satz lass i weg.", "{target} is an.", "{target} is aus.", "{target} wechselt.", "Die Temperatur {loc}.", "I schau nach {target}.", "Wiedergabe is pausiert.", "Wiedergabe lauft weiter.", "Nächster Titel.", "Vorheriger Titel.", "Ton is aus.", "Ton is an.", "Lautstärke steht.", "Steht auf der Liste."),
            personality=triples(("Sehr wohl. ", "Gern. ", ""), ("Passt. ", "Geht. ", ""), ("Mach i gleich. ", "Alles gut. ", ""), ("Lauft. ", "Schön. ", ""), ("Schon gut. ", "Wenn's sein muss. ", ""), ("Na klar. ", "Was für eine Überraschung. ", ""), ("Aye. ", "Käpt'n. ", ""), ("Alles easy. ", "Ganz ruhig. ", ""), ("Ja. ", "Ja, mein Schatz. ", "")),
            numbers=["null", "eins", "zwei", "drei", "vier", "fuenf", "sechs", "sieben", "acht", "neun", "zehn", "elf", "zwoelf", "dreizehn", "vierzehn", "fuenfzehn", "sechzehn", "siebzehn", "achtzehn", "neunzehn", "zwanzig", "dreissig", "vierzig", "fuenfzig", "sechzig", "siebzig", "achtzig", "neunzig", "hundert"],
            extra_w={"on_particles": ["an"], "off_particles": ["aus"], "scenes": ["filmabend"], "named": ["kugel"], "island": ["insel"], "ceiling": ["decke", "deckenlampe"]},
            colors=[("rot", "red"), ("blau", "blue"), ("gruen", "green"), ("gelb", "yellow"), ("orange", "orange"), ("rosa", "pink"), ("schwarz", "black"), ("weiss", "white"), ("violett", "purple")],
            and_join=" und ",
            or_join=" oder ",
        ),
        pack(
            "en-GB",
            "English (UK)",
            ["en-GB"],
            on=["enable"],
            off=["extinguish"],
            open_=["open"],
            close=["close"],
            query=["what", "how"],
            set_=["set"],
            light=["light", "bulb"],
            cover=["curtain", "blind"],
            climate=["heating", "temperature"],
            media=["telly", "music"],
            lock=["lock"],
            door=["door"],
            timer=["timer"],
            list_=["list"],
            fan=["fan"],
            vacuum=["hoover"],
            scene=["scene"],
            fillers=["the", "a", "in"],
            and_=["and"],
            or_=["or"],
            yes=["yes", "ok"],
            all_=["all"],
            living="lounge",
            kitchen="kitchen",
            unknown="I did not catch that. Tell me which light to turn on, for example.",
            need_on="What should I turn on?",
            need_off="What should I turn off?",
            confirm="Should I really do that?",
            spoken=spoken_home("All right, I will drop the last sentence.", "{target} is on.", "{target} is off.", "{target} is switched.", "The temperature {loc}.", "I am checking {target}.", "Playback is paused.", "Playback is back on.", "Next track.", "Previous track.", "Muted.", "Unmuted.", "Volume is set.", "Added to the list."),
            personality=triples(("Very well. ", "Gladly. ", ""), ("Got it. ", "Done. ", ""), ("Doing that now. ", "All good. ", ""), ("Let's go. ", "Nice. ", ""), ("Fine. ", "If I must. ", ""), ("Of course. ", "What a surprise. ", ""), ("Aye. ", "Captain. ", ""), ("All good. ", "Easy. ", ""), ("Yes. ", "Yes, my precious. ", "")),
            numbers=["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "hundred"],
            colors=[("red", "red"), ("blue", "blue"), ("green", "green"), ("yellow", "yellow"), ("orange", "orange"), ("pink", "pink"), ("black", "black"), ("white", "white"), ("purple", "purple")],
            extra_verbs=[("colour", "Color"), ("turn", "Switch"), ("switch", "Switch"), ("on", "OnParticle"), ("off", "Off")],
            extra_w={"on_particles": ["on"], "off_particles": ["off"]},
            smoke=[("turn on the lounge light", "HassTurnOn"), ("switch off the kitchen light", "HassTurnOff")],
            and_join=" and ",
            or_join=" or ",
        ),
        pack(
            "pt-BR",
            "Português (Brasil)",
            ["pt-BR"],
            on=["liga"],
            off=["desliga"],
            open_=["abre"],
            close=["fecha"],
            query=["que", "como"],
            set_=["poe"],
            light=["luz"],
            cover=["cortina"],
            climate=["ar", "temperatura"],
            media=["tv", "musica"],
            lock=["fechadura"],
            door=["porta"],
            timer=["timer"],
            list_=["lista"],
            fan=["ventilador"],
            vacuum=["aspirador"],
            scene=["cena"],
            fillers=["a", "o", "da", "do"],
            and_=["e"],
            or_=["ou"],
            yes=["sim", "ok"],
            all_=["tudo"],
            living="sala",
            kitchen="cozinha",
            unknown="Nao entendi. Diz por exemplo qual luz ligar.",
            need_on="O que ligo?",
            need_off="O que desligo?",
            confirm="Devo mesmo fazer isso?",
            spoken=spoken_home("Beleza, deixo a ultima frase.", "{target} esta ligado.", "{target} esta desligado.", "{target} muda.", "A temperatura {loc}.", "Estou olhando {target}.", "Reproducao em pausa.", "Reproducao continua.", "Proxima faixa.", "Faixa anterior.", "Som desligado.", "Som ligado.", "O volume esta definido.", "Na lista."),
            personality=triples(("Muito bem. ", "Com prazer. ", ""), ("Feito. ", "Beleza. ", ""), ("Ja faco. ", "Tudo bem. ", ""), ("Bora. ", "Legal. ", ""), ("Tudo bem. ", "Se for preciso. ", ""), ("Claro. ", "Que surpresa. ", ""), ("Aye. ", "Capitao. ", ""), ("De boa. ", "Calma. ", ""), ("Sim. ", "Sim, meu tesouro. ", "")),
            numbers=["zero", "um", "dois", "tres", "quatro", "cinco", "seis", "sete", "oito", "nove", "dez", "onze", "doze", "treze", "catorze", "quinze", "dezesseis", "dezessete", "dezoito", "dezenove", "vinte", "trinta", "quarenta", "cinquenta", "sessenta", "setenta", "oitenta", "noventa", "cem"],
            colors=[("vermelho", "red"), ("azul", "blue"), ("verde", "green"), ("amarelo", "yellow"), ("laranja", "orange"), ("rosa", "pink"), ("preto", "black"), ("branco", "white"), ("roxo", "purple")],
            extra_w={"unlock": ["abre"], "lock_v": ["tranca"]},
            and_join=" e ",
            or_join=" ou ",
        ),
        pack(
            "af",
            "Afrikaans",
            ["af", "af-ZA"],
            on=["skakel"],
            off=["doof"],
            open_=["oop"],
            close=["toe"],
            query=["wat", "hoe"],
            set_=["stel"],
            light=["lig"],
            cover=["gordyn"],
            climate=["verwarming", "temperatuur"],
            media=["tv", "musiek"],
            lock=["slot"],
            door=["deur"],
            timer=["timer"],
            list_=["lys"],
            fan=["waaier"],
            vacuum=["stofsuier"],
            scene=["toneel"],
            fillers=["die", "n", "in"],
            and_=["en"],
            or_=["of"],
            yes=["ja", "ok"],
            all_=["almal"],
            living="sitkamer",
            kitchen="kombuis",
            unknown="Ek het dit nie verstaan nie. Se byvoorbeeld watter lig moet aan.",
            need_on="Wat moet ek aanskakel?",
            need_off="Wat moet ek afskakel?",
            confirm="Moet ek dit regtig doen?",
            spoken=spoken_home("Reg, ek laat die laaste sin weg.", "{target} is aan.", "{target} is af.", "{target} wissel.", "Die temperatuur {loc}.", "Ek kyk na {target}.", "Afspeel is onderbreek.", "Afspeel gaan voort.", "Volgende snit.", "Vorige snit.", "Klank is af.", "Klank is aan.", "Volume is gestel.", "Op die lys."),
            personality=triples(("Baie goed. ", "Graag. ", ""), ("Reg. ", "Klaar. ", ""), ("Ek doen dit nou. ", "Alles goed. ", ""), ("Kom ons gaan. ", "Mooi. ", ""), ("Goed. ", "As ek moet. ", ""), ("Natuurlik. ", "Watter verrassing. ", ""), ("Aye. ", "Kaptein. ", ""), ("Easy. ", "Kalm. ", ""), ("Ja. ", "Ja, my skat. ", "")),
            numbers=["nul", "een", "twee", "drie", "vier", "vyf", "ses", "sewe", "agt", "nege", "tien", "elf", "twaalf", "dertien", "veertien", "vyftien", "sestien", "sewentien", "agtien", "negentien", "twintig", "dertig", "veertig", "vyftig", "sestig", "sewentig", "tagtig", "negentig", "honderd"],
            extra_w={"on_particles": ["aan"], "off_particles": ["af"]},
            colors=[("rooi", "red"), ("blou", "blue"), ("groen", "green"), ("geel", "yellow"), ("oranje", "orange"), ("pienk", "pink"), ("swart", "black"), ("wit", "white"), ("pers", "purple")],
            and_join=" en ",
            or_join=" of ",
        ),
    ]
