"""CJK, RTL, Thai, Korean, Japanese, Turkish."""

from __future__ import annotations

from lang_packs.core import pack
from lang_packs.voices import spoken_home, triples


def script() -> list[dict]:
    return [
        pack(
            "zh-CN",
            "简体中文",
            ["zh-CN", "zh"],
            script="Hans",
            on=["dakai"],
            off=["guanbi"],
            open_=["kaiqi"],
            close=["heshang"],
            query=["shenme", "zenme"],
            set_=["shezhi"],
            light=["deng"],
            cover=["lianzi"],
            climate=["kongtiao"],
            media=["dianshi", "yinyue"],
            lock=["suo"],
            door=["men"],
            timer=["dingshi"],
            list_=["qingdan"],
            fan=["fengshan"],
            vacuum=["saodi"],
            scene=["changjing"],
            fillers=["把", "的", "一下"],
            and_=["和"],
            or_=["或"],
            yes=["好", "行"],
            all_=["全部"],
            extra_w={"play": ["bofang"], "dock": ["huijia", "jichong"], "done": ["wancheng"], "pause": ["zanting"]},
            living="keting",
            kitchen="chufang",
            unknown="我没听清。比如说，告诉我要开哪盏灯。",
            need_on="打开什么？",
            need_off="关闭什么？",
            confirm="真的要执行吗？",
            spoken=spoken_home("好的，上一句我就不算了。", "{target}开了。", "{target}关了。", "{target}切换了。", "温度{loc}。", "我在看{target}。", "暂停了。", "继续播放。", "下一首。", "上一首。", "静音了。", "取消静音。", "音量设好了。", "已加入清单。"),
            personality=triples(("好的。 ", "乐意。 ", ""), ("行。 ", "搞定。 ", ""), ("马上就做。 ", "没事。 ", ""), ("走起。 ", "不错。 ", ""), ("行吧。 ", "非做不可。 ", ""), ("当然。 ", "真是惊喜。 ", ""), ("Aye. ", "船长。 ", ""), ("放松。 ", "慢慢来。 ", ""), ("是。 ", "是的，我的宝贝。 ", "")),
            numbers=["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十", "百"],
            and_join="和",
            or_join="或",
        ),
        pack(
            "zh-TW",
            "繁體中文（台灣）",
            ["zh-TW"],
            script="Hant",
            on=["dakai"],
            off=["guanbi"],
            open_=["kaiqi"],
            close=["heshang"],
            query=["shenme", "zenme"],
            set_=["shezhi"],
            light=["deng"],
            cover=["lianzi"],
            climate=["kongtiao"],
            media=["dianshi", "yinyue"],
            lock=["suo"],
            door=["men"],
            timer=["dingshi"],
            list_=["qingdan"],
            fan=["fengshan"],
            vacuum=["saodi"],
            scene=["changjing"],
            fillers=["把", "的", "一下"],
            and_=["和"],
            or_=["或"],
            yes=["好", "行"],
            all_=["全部"],
            extra_w={"play": ["bofang"], "dock": ["huijia", "jichong"], "done": ["wancheng"], "pause": ["zanting"]},
            living="keting",
            kitchen="chufang",
            unknown="我沒聽清楚。比方說，告訴我要開哪盞燈。",
            need_on="打開什麼？",
            need_off="關閉什麼？",
            confirm="真的要執行嗎？",
            spoken=spoken_home("好的，上一句我就不算了。", "{target}開了。", "{target}關了。", "{target}切換了。", "溫度{loc}。", "我在看{target}。", "暫停了。", "繼續播放。", "下一首。", "上一首。", "靜音了。", "取消靜音。", "音量設好了。", "已加入清單。"),
            personality=triples(("好的。 ", "樂意。 ", ""), ("行。 ", "搞定。 ", ""), ("馬上就做。 ", "沒問題。 ", ""), ("走起。 ", "不錯。 ", ""), ("行吧。 ", "非做不可。 ", ""), ("當然。 ", "真是驚喜。 ", ""), ("Aye. ", "船長。 ", ""), ("放鬆。 ", "慢慢來。 ", ""), ("是。 ", "是的，我的寶貝。 ", "")),
            numbers=["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十", "百"],
            and_join="和",
            or_join="或",
        ),
        pack(
            "zh-HK",
            "繁體中文（香港）",
            ["zh-HK"],
            script="Hant",
            on=["dakai"],
            off=["guanbi"],
            open_=["kaiqi"],
            close=["heshang"],
            query=["shenme", "zenme"],
            set_=["shezhi"],
            light=["deng"],
            cover=["lianzi"],
            climate=["kongtiao"],
            media=["dianshi", "yinyue"],
            lock=["suo"],
            door=["men"],
            timer=["dingshi"],
            list_=["qingdan"],
            fan=["fengshan"],
            vacuum=["saodi"],
            scene=["changjing"],
            fillers=["把", "嘅", "吓"],
            and_=["同"],
            or_=["定"],
            yes=["好", "得"],
            all_=["全部"],
            extra_w={"play": ["bofang"], "dock": ["huijia", "jichong"], "done": ["wancheng"], "pause": ["zanting"]},
            living="keting",
            kitchen="chufang",
            unknown="我聽唔明。例如話我知開邊盞燈。",
            need_on="開咩？",
            need_off="關咩？",
            confirm="真係要做？",
            spoken=spoken_home("得，上一句當冇講過。", "{target}開咗。", "{target}關咗。", "{target}轉咗。", "溫度{loc}。", "我睇緊{target}。", "暫停咗。", "繼續播。", "下一首。", "上一首。", "靜音咗。", "取消靜音。", "音量調好。", "加咗入清單。"),
            personality=triples(("好呀。 ", "樂意。 ", ""), ("得。 ", "搞掂。 ", ""), ("而家就做。 ", "冇問題。 ", ""), ("嚟啦。 ", "唔錯。 ", ""), ("算啦。 ", "一定要嘅話。 ", ""), ("當然啦。 ", "真係驚喜。 ", ""), ("Aye. ", "船長。 ", ""), ("放鬆啲。 ", "慢慢嚟。 ", ""), ("係。 ", "係呀，我嘅寶貝。 ", "")),
            numbers=["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十", "百"],
            and_join="同",
            or_join="定",
        ),
        pack(
            "ar",
            "العربية",
            ["ar", "ar-JO"],
            script="Arab",
            on=["شغل"],
            off=["اطفئ"],
            open_=["افتح"],
            close=["اغلق"],
            query=["ايش", "كيف"],
            set_=["حط"],
            light=["ضوء"],
            cover=["ستارة"],
            climate=["تكييف", "حرارة"],
            media=["تلفاز", "موسيقى"],
            lock=["قفل"],
            door=["باب"],
            timer=["مؤقت"],
            list_=["قائمة"],
            fan=["مروحة"],
            vacuum=["مكنسة"],
            scene=["مشهد"],
            fillers=["ال", "في", "على"],
            and_=["و"],
            or_=["أو"],
            yes=["نعم", "حسنا"],
            all_=["كل"],
            living="صالون",
            kitchen="مطبخ",
            unknown="ما فهمت. قل لي مثلا أي ضوء تريد تشغيله.",
            need_on="ماذا أشغل؟",
            need_off="ماذا أطفئ؟",
            confirm="هل أفعل ذلك حقا؟",
            spoken=spoken_home("حسنا، سأتجاهل الجملة الأخيرة.", "{target} يعمل.", "{target} مطفأ.", "{target} يتبدل.", "درجة الحرارة {loc}.", "أنظر إلى {target}.", "التشغيل متوقف.", "التشغيل مستمر.", "المقطع التالي.", "المقطع السابق.", "الصوت مكتوم.", "الصوت مفتوح.", "مستوى الصوت مضبوط.", "أضيف إلى القائمة."),
            personality=triples(("حسنا. ", "بكل سرور. ", ""), ("تمام. ", "خلص. ", ""), ("الآن أفعل ذلك. ", "كله تمام. ", ""), ("يلا. ", "حلو. ", ""), ("طيب. ", "إذا لزم. ", ""), ("طبعا. ", "يا للمفاجأة. ", ""), ("Aye. ", "كابتن. ", ""), ("على مهلك. ", "بهدوء. ", ""), ("نعم. ", "نعم، كنزي. ", "")),
            numbers=["صفر", "واحد", "اثنان", "ثلاثة", "اربعة", "خمسة", "ستة", "سبعة", "ثمانية", "تسعة", "عشرة", "احد عشر", "اثنا عشر", "ثلاثة عشر", "اربعة عشر", "خمسة عشر", "ستة عشر", "سبعة عشر", "ثمانية عشر", "تسعة عشر", "عشرون", "ثلاثون", "اربعون", "خمسون", "ستون", "سبعون", "ثمانون", "تسعون", "مائة"],
            and_join=" و ",
            or_join=" أو ",
        ),
        pack(
            "he",
            "עברית",
            ["he", "he-IL"],
            script="Hebr",
            on=["הדלק"],
            off=["כבה"],
            open_=["פתח"],
            close=["סגור"],
            query=["מה", "איך"],
            set_=["שים"],
            light=["אור"],
            cover=["וילון"],
            climate=["חימום", "טמפרטורה"],
            media=["טלוויזיה", "מוזיקה"],
            lock=["מנעול"],
            door=["דלת"],
            timer=["טיימר"],
            list_=["רשימה"],
            fan=["מאוורר"],
            vacuum=["שואב"],
            scene=["סצנה"],
            fillers=["את", "ב", "של"],
            and_=["ו"],
            or_=["או"],
            yes=["כן", "אוקיי"],
            all_=["הכל"],
            living="סלון",
            kitchen="מטבח",
            unknown="לא הבנתי. תגיד לי למשל איזה אור להדליק.",
            need_on="מה להדליק?",
            need_off="מה לכבות?",
            confirm="באמת לבצע?",
            spoken=spoken_home("בסדר, אני מוותר על המשפט האחרון.", "{target} דולק.", "{target} כבוי.", "{target} מתחלף.", "הטמפרטורה {loc}.", "אני בודק את {target}.", "ההשמעה מושהית.", "ההשמעה ממשיכה.", "השיר הבא.", "השיר הקודם.", "הקול מושתק.", "הקול פתוח.", "הווליום מוגדר.", "נוסף לרשימה."),
            personality=triples(("בסדר. ", "בשמחה. ", ""), ("הבנתי. ", "בוצע. ", ""), ("אני עושה את זה עכשיו. ", "הכל בסדר. ", ""), ("יאללה. ", "יפה. ", ""), ("טוב. ", "אם חייבים. ", ""), ("ברור. ", "איזו הפתעה. ", ""), ("Aye. ", "קפטן. ", ""), ("בקלות. ", "בשקט. ", ""), ("כן. ", "כן, היקר שלי. ", "")),
            numbers=["אפס", "אחת", "שתיים", "שלוש", "ארבע", "חמש", "שש", "שבע", "שמונה", "תשע", "עשר", "אחת עשרה", "שתים עשרה", "שלוש עשרה", "ארבע עשרה", "חמש עשרה", "שש עשרה", "שבע עשרה", "שמונה עשרה", "תשע עשרה", "עשרים", "שלושים", "ארבעים", "חמישים", "שישים", "שבעים", "שמונים", "תשעים", "מאה"],
            and_join=" ו ",
            or_join=" או ",
        ),
        pack(
            "fa",
            "فارسی",
            ["fa", "fa-IR"],
            script="Arab",
            on=["روشن"],
            off=["خاموش"],
            open_=["باز"],
            close=["بسته"],
            query=["چی", "چطور"],
            set_=["بگذار"],
            light=["چراغ"],
            cover=["پرده"],
            climate=["سرما", "دما"],
            media=["تلویزیون", "موسیقی"],
            lock=["قفل"],
            door=["در"],
            timer=["تایمر"],
            list_=["فهرست"],
            fan=["پنکه"],
            vacuum=["جارو"],
            scene=["صحنه"],
            fillers=["را", "در", "به"],
            and_=["و"],
            or_=["یا"],
            yes=["بله", "باشه"],
            all_=["همه"],
            living="پذیرایی",
            kitchen="آشپزخانه",
            unknown="متوجه نشدم. مثلا بگو کدام چراغ روشن شود.",
            need_on="چه چیزی روشن شود؟",
            need_off="چه چیزی خاموش شود؟",
            confirm="واقعا انجام بدهم؟",
            spoken=spoken_home("باشه، جمله آخر را کنار میگذارم.", "{target} روشن است.", "{target} خاموش است.", "{target} عوض میشود.", "دما {loc}.", "دارم {target} را نگاه میکنم.", "پخش متوقف شد.", "پخش ادامه دارد.", "آهنگ بعدی.", "آهنگ قبلی.", "صدا قطع است.", "صدا باز است.", "صدا تنظیم شد.", "به فهرست اضافه شد."),
            personality=triples(("باشه. ", "با میل. ", ""), ("فهمیدم. ", "انجام شد. ", ""), ("الان انجام میدهم. ", "همه چیز خوب است. ", ""), ("بزن بریم. ", "عالی. ", ""), ("خب. ", "اگر باید. ", ""), ("البته. ", "چه سورپرایزی. ", ""), ("Aye. ", "کاپیتان. ", ""), ("آروم. ", "راحت. ", ""), ("بله. ", "بله، گنج من. ", "")),
            numbers=["صفر", "یک", "دو", "سه", "چهار", "پنج", "شش", "هفت", "هشت", "نه", "ده", "یازده", "دوازده", "سیزده", "چهارده", "پانزده", "شانزده", "هفده", "هجده", "نوزده", "بیست", "سی", "چهل", "پنجاه", "شصت", "هفتاد", "هشتاد", "نود", "صد"],
            and_join=" و ",
            or_join=" یا ",
        ),
        pack(
            "ur",
            "اُردُو",
            ["ur", "ur-IN"],
            script="Arab",
            on=["چالو"],
            off=["بند"],
            open_=["کھولو"],
            close=["بندکرو"],
            query=["کیا", "کیسے"],
            set_=["رکھو"],
            light=["روشنی"],
            cover=["پردہ"],
            climate=["گرمی", "درجہ"],
            media=["ٹی وی", "موسیقی"],
            lock=["تالا"],
            door=["دروازہ"],
            timer=["ٹائمر"],
            list_=["فہرست"],
            fan=["پنکھا"],
            vacuum=["جھاڑو"],
            scene=["منظر"],
            fillers=["کو", "میں", "کی"],
            and_=["اور"],
            or_=["یا"],
            yes=["ہاں", "ٹھیک"],
            all_=["سب"],
            living="لانج",
            kitchen="باورچی",
            unknown="سمجھ نہیں آیا۔ مثلا بتاؤ کون سی روشنی چالو کروں۔",
            need_on="کیا چالو کروں؟",
            need_off="کیا بند کروں؟",
            confirm="کیا واقعی کروں؟",
            spoken=spoken_home("ٹھیک ہے، آخری جملہ چھوڑ دیتا ہوں۔", "{target} چالو ہے۔", "{target} بند ہے۔", "{target} بدل رہا ہے۔", "درجہ حرارت {loc}۔", "میں {target} دیکھ رہا ہوں۔", "پلے رک گیا۔", "پلے جاری ہے۔", "اگلا گانا۔", "پچھلا گانا۔", "آواز بند ہے۔", "آواز کھلی ہے۔", "آواز سیٹ ہو گئی۔", "فہرست میں شامل۔"),
            personality=triples(("ٹھیک ہے۔ ", "خوشی سے۔ ", ""), ("سمجھ گیا۔ ", "ہو گیا۔ ", ""), ("ابھی کرتا ہوں۔ ", "سب ٹھیک ہے۔ ", ""), ("چلو۔ ", "اچھا۔ ", ""), ("ہاں جی۔ ", "اگر ضروری ہے۔ ", ""), ("یقینا۔ ", "کیا حیرت۔ ", ""), ("Aye. ", "کپتان. ", ""), ("آرام سے۔ ", "پرسکون۔ ", ""), ("ہاں۔ ", "ہاں، میرا خزانہ۔ ", "")),
            numbers=["صفر", "ایک", "دو", "تین", "چار", "پانچ", "چھ", "سات", "آٹھ", "نو", "دس", "گیارہ", "بارہ", "تیرہ", "چودہ", "پندرہ", "سولہ", "سترہ", "اٹھارہ", "انیس", "بیس", "تیس", "چالیس", "پچاس", "ساٹھ", "ستر", "اسی", "نوے", "سو"],
            and_join=" اور ",
            or_join=" یا ",
        ),
        pack(
            "tr",
            "Türkçe",
            ["tr", "tr-TR"],
            on=["yak"],
            off=["sondur"],
            open_=["ac"],
            close=["kapat"],
            query=["ne", "nasil"],
            set_=["ayarla"],
            light=["isik"],
            cover=["perde"],
            climate=["sicaklik", "klima"],
            media=["televizyon", "muzik"],
            lock=["kilit"],
            door=["kapi"],
            timer=["zamanlayici"],
            list_=["liste"],
            fan=["vantilator"],
            vacuum=["supurge"],
            scene=["sahne"],
            fillers=["bir", "de", "mi"],
            and_=["ve"],
            or_=["veya"],
            yes=["evet", "tamam"],
            all_=["hepsi"],
            living="salon",
            kitchen="mutfak",
            unknown="Anlamadim. Ornegin hangi isigin acilacagini soyle.",
            need_on="Neyi acayim?",
            need_off="Neyi kapatayim?",
            confirm="Bunu gercekten yapayim mi?",
            spoken=spoken_home("Tamam, son cumleyi birakiyorum.", "{target} acik.", "{target} kapali.", "{target} degisiyor.", "Sicaklik {loc}.", "Bakiyorum {target}.", "Oynatma duraklatildi.", "Oynatma devam ediyor.", "Sonraki parca.", "Onceki parca.", "Ses kapali.", "Ses acik.", "Ses seviyesi ayarlandi.", "Listeye eklendi."),
            personality=triples(("Peki. ", "Memnuniyetle. ", ""), ("Tamam. ", "Oldu. ", ""), ("Hemen yapiyorum. ", "Her sey yolunda. ", ""), ("Hadi. ", "Guzel. ", ""), ("Peki o zaman. ", "Zorundaysam. ", ""), ("Tabii. ", "Ne surpriz. ", ""), ("Aye. ", "Kaptan. ", ""), ("Rahat. ", "Sakin. ", ""), ("Evet. ", "Evet, hazinem. ", "")),
            numbers=["sifir", "bir", "iki", "uc", "dort", "bes", "alti", "yedi", "sekiz", "dokuz", "on", "onbir", "oniki", "onuc", "ondort", "onbes", "onalti", "onyedi", "onsekiz", "ondokuz", "yirmi", "otuz", "kirk", "elli", "altmis", "yetmis", "seksen", "doksan", "yuz"],
            extra_w={"unlock": ["kilidiac"], "lock_v": ["kilitle"]},
            and_join=" ve ",
            or_join=" veya ",
        ),
        pack(
            "th",
            "ภาษาไทย",
            ["th", "th-TH"],
            script="Thai",
            on=["poetfai"],
            off=["pitfai"],
            open_=["poet"],
            close=["pit"],
            query=["arai", "yangngai"],
            set_=["tang"],
            light=["fai"],
            cover=["man"],
            climate=["air"],
            media=["thiwi", "phleng"],
            lock=["kunjae"],
            door=["pratu"],
            timer=["tangwela"],
            list_=["raikan"],
            fan=["phat"],
            vacuum=["dutfun"],
            scene=["chak"],
            fillers=["ที่", "ใน", "หน่อย"],
            and_=["และ"],
            or_=["หรือ"],
            yes=["ok", "chai"],
            all_=["ทั้งหมด"],
            living="hongnang",
            kitchen="hongkrua",
            unknown="ฟังไม่ทัน บอกได้ไหมว่าจะเปิดไฟดวงไหน เช่น",
            need_on="เปิดอะไร",
            need_off="ปิดอะไร",
            confirm="ทำจริงหรือ",
            spoken=spoken_home("ได้ ฉันจะไม่นับประโยคที่แล้ว.", "{target} เปิดแล้ว.", "{target} ปิดแล้ว.", "{target} สลับแล้ว.", "อุณหภูมิ {loc}.", "ฉันกำลังดู {target}.", "หยุดเล่นชั่วคราว.", "เล่นต่อแล้ว.", "เพลงถัดไป.", "เพลงก่อนหน้า.", "ปิดเสียงแล้ว.", "เปิดเสียงแล้ว.", "ตั้งระดับเสียงแล้ว.", "ใส่ในรายการแล้ว."),
            personality=triples(("ได้เลย. ", "ยินดี. ", ""), ("โอเค. ", "เสร็จแล้ว. ", ""), ("ทำให้เลย. ", "ไม่เป็นไร. ", ""), ("ไปเลย. ", "ดีจัง. ", ""), ("ก็ได้. ", "ถ้าต้องทำ. ", ""), ("แน่นอน. ", "ช่างเซอร์ไพรส์. ", ""), ("Aye. ", "กัปตัน. ", ""), ("สบายๆ. ", "ช้าๆ. ", ""), ("ใช่. ", "ใช่ ของมีค่าของฉัน. ", "")),
            numbers=["ศูนย์", "หนึ่ง", "สอง", "สาม", "สี่", "ห้า", "หก", "เจ็ด", "แปด", "เก้า", "สิบ", "สิบเอ็ด", "สิบสอง", "สิบสาม", "สิบสี่", "สิบห้า", "สิบหก", "สิบเจ็ด", "สิบแปด", "สิบเก้า", "ยี่สิบ", "สามสิบ", "สี่สิบ", "ห้าสิบ", "หกสิบ", "เจ็ดสิบ", "แปดสิบ", "เก้าสิบ", "ร้อย"],
            and_join=" และ ",
            or_join=" หรือ ",
        ),
        pack(
            "ko",
            "한국어",
            ["ko", "ko-KR"],
            script="Hang",
            on=["kyeo"],
            off=["kkaeo"],
            open_=["yeolo"],
            close=["dada"],
            query=["mwo", "eotteoke"],
            set_=["seoljeong"],
            light=["bul"],
            cover=["keoteun"],
            climate=["nanbang"],
            media=["tibi", "eumak"],
            lock=["jamulsoe"],
            door=["mun"],
            timer=["taimeo"],
            list_=["mongnok"],
            fan=["seonpunggi"],
            vacuum=["cheongsogi"],
            scene=["jangmyeon"],
            fillers=["을", "를", "에"],
            and_=["그리고"],
            or_=["또는"],
            yes=["응", "네"],
            all_=["모두"],
            living="geosil",
            kitchen="bueok",
            unknown="잘 못 들었어요. 예를 들어 어떤 불을 켤지 말해 주세요.",
            need_on="뭘 켤까요?",
            need_off="뭘 끌까요?",
            confirm="정말 할까요?",
            spoken=spoken_home("알겠어요, 마지막 문장은 빼둘게요.", "{target} 켜졌어요.", "{target} 꺼졌어요.", "{target} 바뀌어요.", "온도 {loc}.", "{target} 보고 있어요.", "재생이 멈췄어요.", "다시 재생해요.", "다음 곡.", "이전 곡.", "음소거됐어요.", "소리가 켜졌어요.", "볼륨이 맞춰졌어요.", "목록에 넣었어요."),
            personality=triples(("알겠습니다. ", "기꺼이. ", ""), ("오케이. ", "됐어. ", ""), ("지금 할게요. ", "괜찮아요. ", ""), ("가자. ", "좋다. ", ""), ("그래. ", "해야 한다면. ", ""), ("당연하지. ", "놀라운걸. ", ""), ("Aye. ", "선장. ", ""), ("편하게. ", "천천히. ", ""), ("네. ", "네, 내 보물. ", "")),
            numbers=["영", "일", "이", "삼", "사", "오", "육", "칠", "팔", "구", "십", "십일", "십이", "십삼", "십사", "십오", "십육", "십칠", "십팔", "십구", "이십", "삼십", "사십", "오십", "육십", "칠십", "팔십", "구십", "백"],
            and_join=" 그리고 ",
            or_join=" 또는 ",
        ),
        pack(
            "ja",
            "日本語",
            ["ja", "ja-JP"],
            script="Jpan",
            on=["tsukete"],
            off=["keshite"],
            open_=["akete"],
            close=["shimete"],
            query=["nani", "dou"],
            set_=["setto"],
            light=["raito"],
            cover=["kaaten"],
            climate=["eakon"],
            media=["terebi", "ongaku"],
            lock=["kagi"],
            door=["doa"],
            timer=["taimaa"],
            list_=["risuto"],
            fan=["fan"],
            vacuum=["soujiki"],
            scene=["shiin"],
            fillers=["を", "に", "の"],
            and_=["と"],
            or_=["か"],
            yes=["ok", "hai"],
            all_=["全部"],
            extra_w={
                "play": ["play"],
                "pause": ["pause"],
                "add": ["add"],
                "done": ["done"],
                "minutes": ["fun", "minutes"],
            },
            extra_verbs=[("next", "Next"), ("tsugi", "Next")],
            living="ribingu",
            kitchen="kitchin",
            unknown="聞き取れませんでした。例えば、どのライトを点けるか教えてください。",
            need_on="何をつけますか",
            need_off="何をけしますか",
            confirm="本当に実行しますか？",
            spoken=spoken_home("わかりました、最後の文は取り消します。", "{target}はついています。", "{target}は消えています。", "{target}が切り替わります。", "温度{loc}。", "{target}を確認しています。", "再生を一時停止しました。", "再生を再開しました。", "次の曲です。", "前の曲です。", "消音しました。", "消音を解除しました。", "音量を設定しました。", "リストに追加しました。"),
            personality=triples(("わかりました。 ", "喜んで。 ", ""), ("了解。 ", "できた。 ", ""), ("今やります。 ", "大丈夫です。 ", ""), ("いこう。 ", "いいね。 ", ""), ("わかった。 ", "仕方ない。 ", ""), ("もちろん。 ", "驚いたな。 ", ""), ("Aye. ", "船長。 ", ""), ("のんびり。 ", "ゆっくり。 ", ""), ("はい。 ", "はい、宝物。 ", "")),
            numbers=["ゼロ", "いち", "に", "さん", "よん", "ご", "ろく", "なな", "はち", "きゅう", "じゅう", "じゅういち", "じゅうに", "じゅうさん", "じゅうよん", "じゅうご", "じゅうろく", "じゅうなな", "じゅうはち", "じゅうきゅう", "にじゅう", "さんじゅう", "よんじゅう", "ごじゅう", "ろくじゅう", "ななじゅう", "はちじゅう", "きゅうじゅう", "ひゃく"],
            and_join="と",
            or_join="か",
        ),
    ]
