"""Lotse chrome for West / Nordic Assist locales."""

from __future__ import annotations

from lang_packs.lotse_chrome import lotse

PACKS: dict[str, dict[str, str]] = {
    "fr": lotse(
        hint="Questions sur Klar tout de suite. Les écritures attendent Autoriser.",
        empty="Demande comment Klar fonctionne — ou une lacune.",
        empty_hint="Lotse n’écrit rien tant que tu n’as pas autorisé.",
        you="Toi", permit="Écriture", send="Envoyer", allow="Autoriser", allow_once="Une fois",
        deny="Refuser", ask="Redemander", need="Configure d’abord un LLM dans Réglages. Pas d’autre agent HA.",
        open_settings="Ouvrir Réglages", streaming="Flux…", ok="Valide", fail="Invalide",
        tool="Outil", clear="Effacer", composer="Message à Lotse",
        gaps="Quels appareils n’ont pas de pièce ?", night="Propose une règle maison pour bonne nuit.",
        matchers="Quels matchers sont actifs, et dans quel ordre ?",
        precedence="Explique la priorité des matchers. Ne change rien.",
        lexicon="Quels chemins de lexique existent pour l’allemand ?",
        slang="Propose un argot pour un chemin de lexique. N’écris pas encore.",
        for_lane="Lotse pour cette piste",
    ),
    "nl": lotse(
        hint="Vragen over Klar meteen. Schrijven wacht op Toestaan.",
        empty="Vraag hoe Klar werkt — of naar een gat.",
        empty_hint="Lotse schrijft niets tot je Toestaan tikt.",
        you="Jij", permit="Schrijven", send="Sturen", allow="Toestaan", allow_once="Een keer",
        deny="Weigeren", ask="Opnieuw vragen", need="Zet eerst een LLM in Instellingen. Geen extra HA-agent.",
        open_settings="Instellingen openen", streaming="Stream…", ok="Geldig", fail="Ongeldig",
        tool="Hulpmiddel", clear="Wis chat", composer="Bericht aan Lotse",
        gaps="Welke apparaten hebben geen kamer?", night="Stel een huisregel voor goedenacht voor.",
        matchers="Welke matchers staan aan, en in welke volgorde?",
        precedence="Leg matcher-voorrang uit. Niets wijzigen.",
        lexicon="Welke lexiconpaden bestaan voor Duits?",
        slang="Stel slang voor een lexiconpad voor. Nog niet schrijven.",
        for_lane="Lotse voor dit spoor",
    ),
    "es": lotse(
        hint="Preguntas sobre Klar al momento. Los escritos esperan Permitir.",
        empty="Pregunta cómo funciona Klar — o por un hueco.",
        empty_hint="Lotse no escribe hasta que pulses Permitir.",
        you="Tú", permit="Escritura", send="Enviar", allow="Permitir", allow_once="Una vez",
        deny="Denegar", ask="Preguntar otra vez", need="Configura primero un LLM en Ajustes. No otro agente de HA.",
        open_settings="Abrir Ajustes", streaming="Flujo…", ok="Válido", fail="Inválido",
        tool="Herramienta", clear="Borrar chat", composer="Mensaje a Lotse",
        gaps="¿Qué dispositivos no tienen habitación?", night="Propón una regla de casa para buenas noches.",
        matchers="¿Qué matchers están activos y en qué orden?",
        precedence="Explica la prioridad de los matchers. No cambies nada.",
        lexicon="¿Qué rutas de lexico hay para el alemán?",
        slang="Propón jerga para una ruta de lexico. Aún no escribas.",
        for_lane="Lotse para este carril",
    ),
    "it": lotse(
        hint="Domande su Klar subito. Le scritture aspettano Consenti.",
        empty="Chiedi come funziona Klar — o un buco.",
        empty_hint="Lotse non scrive finché non tocchi Consenti.",
        you="Tu", permit="Scrittura", send="Invia", allow="Consenti", allow_once="Una volta",
        deny="Nega", ask="Chiedi di nuovo", need="Configura prima un LLM in Impostazioni. Nessun altro agente HA.",
        open_settings="Apri Impostazioni", streaming="Flusso…", ok="Valido", fail="Non valido",
        tool="Strumento", clear="Cancella chat", composer="Messaggio a Lotse",
        gaps="Quali dispositivi non hanno una stanza?", night="Proponi una regola di casa per la buonanotte.",
        matchers="Quali matcher sono attivi e in che ordine?",
        precedence="Spiega la precedenza dei matcher. Non cambiare.",
        lexicon="Quali percorsi di lessico esistono per il tedesco?",
        slang="Proponi slang per un percorso di lessico. Non scrivere ancora.",
        for_lane="Lotse per questa corsia",
    ),
    "pt": lotse(
        hint="Perguntas sobre o Klar já. As escritas esperam Permitir.",
        empty="Pergunta como o Klar funciona — ou por um buraco.",
        empty_hint="O Lotse não escreve até tocares em Permitir.",
        you="Tu", permit="Escrita", send="Enviar", allow="Permitir", allow_once="Uma vez",
        deny="Recusar", ask="Perguntar de novo", need="Configura primeiro um LLM em Definições. Sem outro agente HA.",
        open_settings="Abrir Definições", streaming="Fluxo…", ok="Válido", fail="Inválido",
        tool="Ferramenta", clear="Limpar chat", composer="Mensagem ao Lotse",
        gaps="Que dispositivos não têm divisão?", night="Propõe uma regra de casa para boa noite.",
        matchers="Que matchers estão ligados e por que ordem?",
        precedence="Explica a precedência dos matchers. Não alters.",
        lexicon="Que caminhos de léxico existem para alemão?",
        slang="Propõe calão para um caminho de léxico. Ainda não escrevas.",
        for_lane="Lotse para esta faixa",
    ),
    "ca": lotse(
        hint="Preguntes sobre Klar de seguida. Les escriptures esperen Permetre.",
        empty="Pregunta com funciona Klar — o per un forat.",
        empty_hint="Lotse no escriu fins que toquis Permetre.",
        you="Tu", permit="Escriptura", send="Envia", allow="Permetre", allow_once="Un cop",
        deny="Denega", ask="Torna a preguntar", need="Configura primer un LLM a Configuració. Sense un altre agent HA.",
        open_settings="Obre Configuració", streaming="Flux…", ok="Vàlid", fail="Invàlid",
        tool="Eina", clear="Esborra el xat", composer="Missatge a Lotse",
        gaps="Quins aparells no tenen habitació?", night="Proposar una regla de casa per a bona nit.",
        matchers="Quins matchers estan actius i en quin ordre?",
        precedence="Explica la precedència dels matchers. No ho canviïs.",
        lexicon="Quins camins de lèxic hi ha per a l’alemany?",
        slang="Proposar argot per a un camí de lèxic. Encara no escriguis.",
        for_lane="Lotse per a aquest carril",
    ),
    "ro": lotse(
        hint="Întrebări despre Klar imediat. Scrierile așteaptă Permite.",
        empty="Întreabă cum funcționează Klar — sau despre un gol.",
        empty_hint="Lotse nu scrie până nu apeși Permite.",
        you="Tu", permit="Scriere", send="Trimite", allow="Permite", allow_once="O dată",
        deny="Refuză", ask="Întreabă din nou", need="Configurează mai întâi un LLM la Setări. Fără alt agent HA.",
        open_settings="Deschide Setări", streaming="Flux…", ok="Valid", fail="Invalid",
        tool="Instrument", clear="Șterge chatul", composer="Mesaj către Lotse",
        gaps="Ce dispozitive nu au cameră?", night="Propune o regulă de casă pentru noapte bună.",
        matchers="Ce matchere sunt active și în ce ordine?",
        precedence="Explică prioritatea matcherelor. Nu schimba.",
        lexicon="Ce căi de lexicon există pentru germană?",
        slang="Propune slang pentru o cale de lexicon. Nu scrie încă.",
        for_lane="Lotse pentru această pistă",
    ),
    "pt-BR": lotse(
        hint="Perguntas sobre o Klar na hora. As escritas esperam Permitir.",
        empty="Pergunte como o Klar funciona — ou por uma lacuna.",
        empty_hint="O Lotse não escreve até você tocar em Permitir.",
        you="Você", permit="Escrita", send="Enviar", allow="Permitir", allow_once="Uma vez",
        deny="Recusar", ask="Perguntar de novo", need="Configure primeiro um LLM em Ajustes. Sem outro agente do HA.",
        open_settings="Abrir Ajustes", streaming="Fluxo…", ok="Válido", fail="Inválido",
        tool="Ferramenta", clear="Limpar chat", composer="Mensagem para o Lotse",
        gaps="Quais dispositivos não têm cômodo?", night="Sugira uma regra da casa para boa noite.",
        matchers="Quais matchers estão ligados e em que ordem?",
        precedence="Explique a precedência dos matchers. Não altere.",
        lexicon="Quais caminhos de léxico existem para o alemão?",
        slang="Sugira gíria para um caminho de léxico. Ainda não escreva.",
        for_lane="Lotse para esta faixa",
    ),
    "gl": lotse(
        hint="Preguntas sobre Klar agora. As escritas agardan Permitir.",
        empty="Pregunta como funciona Klar — ou por un oco.",
        empty_hint="Lotse non escribe ata que toques Permitir.",
        you="Ti", permit="Escritura", send="Enviar", allow="Permitir", allow_once="Unha vez",
        deny="Rexeitar", ask="Preguntar outra vez", need="Configura primeiro un LLM en Axustes. Sen outro axente HA.",
        open_settings="Abrir Axustes", streaming="Fluxo…", ok="Válido", fail="Inválido",
        tool="Ferramenta", clear="Borrar o chat", composer="Mensaxe a Lotse",
        gaps="Que dispositivos non teñen habitación?", night="Propón unha regra da casa para boa noite.",
        matchers="Que matchers están activos e en que orde?",
        precedence="Explica a precedencia dos matchers. Non cambies.",
        lexicon="Que camiños de léxico hai para o alemán?",
        slang="Propón argot para un camiño de léxico. Aínda non escribas.",
        for_lane="Lotse para este carril",
    ),
    "de-CH": lotse(
        hint="Frage zu Klar sofort. Schriibe warte uf Freigäh.",
        empty="Frag, wie Klar schafft — oder nach ere Lücke.",
        empty_hint="Lotse schriibt nüt, bis du Freigäh tippsch.",
        you="Du", permit="Schriibzuegriff", send="Sende", allow="Freigäh", allow_once="Einisch",
        deny="Ablehne", ask="Nomol frage", need="Zersch es LLM under Iistellige setze. Kei anderi HA-Conversation.",
        open_settings="Iistellige öffne", streaming="Stream…", ok="Gültig", fail="Ungültig",
        tool="Wärchzüüg", clear="Verlauf lösche", composer="Nochricht a de Lots",
        gaps="Weli Grät händ kei Ruum?", night="Schlag e Huusregle für Guet Nacht vor.",
        matchers="Weli Matcher sind aa, und i wele Reihefolg?",
        precedence="Erklär d Matcher-Precedence. Nüt ändere.",
        lexicon="Weli Lexikon-Pfad gits für Dütsch?",
        slang="Schlag Slang für en Lexikon-Pfad vor. No nöd schriibe.",
        for_lane="Lotse für die Spur",
        trainer="Lotse",
    ),
    "de-AT": lotse(
        hint="Fragen zu Klar sofort. Schreiben erst nach Freigabe.",
        empty="Frag, wie Klar arbeitet — oder nach einer Lücke.",
        empty_hint="Lotse ändert nichts, bis du Freigeben tippst.",
        you="Du", permit="Schreibzugriff", send="Senden", allow="Freigeben", allow_once="Einmal",
        deny="Ablehnen", ask="Wieder fragen", need="Zuerst ein LLM unter Einstellungen setzen. Keine andere HA-Conversation.",
        open_settings="Einstellungen öffnen", streaming="Stream…", ok="Gültig", fail="Ungültig",
        tool="Werkzeug", clear="Verlauf löschen", composer="Nachricht an den Lotsen",
        gaps="Welche Geräte haben keinen Raum?", night="Schlage eine Hausregel für gute Nacht vor.",
        matchers="Welche Matcher sind an, und in welcher Reihenfolge?",
        precedence="Erkläre die Matcher-Precedence. Nicht ändern.",
        lexicon="Welche Lexikon-Pfade gibt es für Deutsch?",
        slang="Schlage Slang für einen Lexikon-Pfad vor. Noch nicht schreiben.",
        for_lane="Lotse für diese Spur",
        trainer="Lotse",
    ),
    "en-GB": lotse(
        hint="Ask about Klar anytime. Writes wait for Allow in this chat.",
        empty="Ask how Klar works — or about a gap.",
        empty_hint="Lotse writes nothing until you tap Allow.",
        you="You", permit="Write access", send="Send", allow="Allow", allow_once="Once",
        deny="Deny", ask="Ask again", need="Configure an LLM in Settings first. No other Home Assistant conversation agent.",
        open_settings="Open Settings", streaming="Streaming…", ok="Valid", fail="Invalid",
        tool="Tool", clear="Clear chat", composer="Message Lotse",
        gaps="Which devices have no room?", night="Suggest a house rule for good night.",
        matchers="Which matchers are on, and in what order?",
        precedence="Explain matcher precedence. Do not change it.",
        lexicon="Which lexicon paths exist for German?",
        slang="Suggest slang for a lexicon path. Do not write yet.",
        for_lane="Lotse for this lane",
    ),
    "af": lotse(
        hint="Vrae oor Klar dadelik. Skryf wag vir Laat toe.",
        empty="Vra hoe Klar werk — of oor ’n gaping.",
        empty_hint="Lotse skryf niks tot jy Laat toe tik.",
        you="Jy", permit="Skryftoegang", send="Stuur", allow="Laat toe", allow_once="Een keer",
        deny="Weier", ask="Vra weer", need="Stel eers ’n LLM in Instellings. Geen ander HA-agent nie.",
        open_settings="Maak Instellings oop", streaming="Stroom…", ok="Geldig", fail="Ongeldig",
        tool="Gereedskap", clear="Maak klets skoon", composer="Boodskap aan Lotse",
        gaps="Watter toestelle het geen kamer nie?", night="Stel ’n huisreël vir goeie nag voor.",
        matchers="Watter matchers is aan, en in watter volgorde?",
        precedence="Verduidelik matcher-voorrang. Moenie verander nie.",
        lexicon="Watter leksikonpaaie bestaan vir Duits?",
        slang="Stel slang vir ’n leksikonpad voor. Moenie nog skryf nie.",
        for_lane="Lotse vir hierdie baan",
    ),
    "lb": lotse(
        hint="Froe iwwer Klar direkt. Schreiwen waart op Fräiginn.",
        empty="Fro, wéi Klar schafft — oder no enger Lück.",
        empty_hint="Lotse schreift näischt, bis s de Fräiginn tipps.",
        you="Du", permit="Schreifzougang", send="Schécken", allow="Fräiginn", allow_once="Eemol",
        deny="Ofleenen", ask="Nees froen", need="Setz als éischt en LLM ënner Astellungen. Keng aner HA-Conversation.",
        open_settings="Astellungen opmaachen", streaming="Stream…", ok="Gülteg", fail="Ongülteg",
        tool="Geschier", clear="Verlaf läschen", composer="Message un de Lots",
        gaps="Wéi Geräter hunn kee Raum?", night="Schlo eng Hausregel fir Gutt Nuecht vir.",
        matchers="Wéi Matcher sinn un, an a wéienger Reiefolleg?",
        precedence="Erklär d’Matcher-Precedence. Näischt änneren.",
        lexicon="Wéi Lexikon-Pade gëtt et fir Däitsch?",
        slang="Schlo Slang fir e Lexikon-Pad vir. Nach net schreiwen.",
        for_lane="Lotse fir dës Spur",
    ),
    "cy": lotse(
        hint="Cwestiynau am Klar ar unwaith. Ysgrifennu’n aros am Caniatáu.",
        empty="Gofyn sut mae Klar yn gweithio — neu am fwlch.",
        empty_hint="Does Lotse ddim yn ysgrifennu nes i chi dapio Caniatáu.",
        you="Chi", permit="Mynediad ysgrifennu", send="Anfon", allow="Caniatáu", allow_once="Unwaith",
        deny="Gwrthod", ask="Gofyn eto", need="Ffurfweddwch LLM yn Gosodiadau yn gyntaf. Dim asiant HA arall.",
        open_settings="Agor Gosodiadau", streaming="Ffrwd…", ok="Dilys", fail="Annilys",
        tool="Offeryn", clear="Clirio’r sgwrs", composer="Neges at Lotse",
        gaps="Pa ddyfeisiau sydd heb ystafell?", night="Awgrymwch reol tŷ ar gyfer nos da.",
        matchers="Pa matchers sydd ymlaen, ac ym mha drefn?",
        precedence="Esboniwch flaenoriaeth matchers. Peidiwch â newid.",
        lexicon="Pa lwybrau geirfa sydd ar gyfer Almaeneg?",
        slang="Awgrymwch slang ar gyfer llwybr geirfa. Peidiwch ag ysgrifennu eto.",
        for_lane="Lotse ar gyfer y lôn hon",
    ),
    "eu": lotse(
        hint="Klarri buruzko galderak berehala. Idatziek Baimendu itxaroten dute.",
        empty="Galdetu nola dabilen Klar — edo hutsune bati buruz.",
        empty_hint="Lotsek ez du idazten Baimendu sakatu arte.",
        you="Zu", permit="Idazketa", send="Bidali", allow="Baimendu", allow_once="Behin",
        deny="Ukatu", ask="Berriro galdetu", need="Konfiguratu LLM bat Ezarpenetan lehenik. Ez HA agente gehigarririk.",
        open_settings="Ireki Ezarpenak", streaming="Jarioa…", ok="Baliozkoa", fail="Baliogabea",
        tool="Tresna", clear="Garbitu txata", composer="Mezua Lotseri",
        gaps="Zein gailuk ez dute gelarik?", night="Proposatu etxeko arau bat gau onetarako.",
        matchers="Zein matcher daude piztuta, eta zein ordenatan?",
        precedence="Azaldu matcher lehentasuna. Ez aldatu.",
        lexicon="Zein lexiko-bide daude alemanerarako?",
        slang="Proposatu slanga lexiko-bide baterako. Oraindik ez idatzi.",
        for_lane="Lotse errail honetarako",
    ),
    "ga": lotse(
        hint="Ceisteanna faoi Klar láithreach. Fanann scríobh le Ceadaigh.",
        empty="Fiafraigh conas a oibríonn Klar — nó faoi bhearna.",
        empty_hint="Ní scríobhann Lotse go dtí go sconnaíonn tú Ceadaigh.",
        you="Tusa", permit="Rochtain scríofa", send="Seol", allow="Ceadaigh", allow_once="Uair amháin",
        deny="Diúltaigh", ask="Fiafraigh arís", need="Cumraigh LLM i Socruithe ar dtús. Gan gníomhaire HA eile.",
        open_settings="Oscail Socruithe", streaming="Sruth…", ok="Bailí", fail="Neamhbhailí",
        tool="Uirlis", clear="Glan an comhrá", composer="Teachtaireacht chuig Lotse",
        gaps="Cé na gléasanna gan seomra?", night="Mol riail tí don oíche mhaith.",
        matchers="Cé na matchers atá ar siúl, agus cén t-ord?",
        precedence="Mínigh tosaíocht na matchers. Ná hathraigh.",
        lexicon="Cé na cosáin foclóra atá ann don Ghearmáinis?",
        slang="Mol slang do chosán foclóra. Ná scríobh fós.",
        for_lane="Lotse don lána seo",
    ),
    "kw": lotse(
        hint="Govynnow a-dro dhe Klar a-dhesempis. Skrifa a wort Omprofi.",
        empty="Govyn fatel ober Klar — po a-dro dhe autonom.",
        empty_hint="Ny skriva Lotse erna wrewgh hwi omprofi.",
        you="Hwi", permit="Hedh skrifa", send="Danvon", allow="Omprofi", allow_once="Unnweyth",
        deny="Nagha", ask="Govyn arta", need="Kefidhewgh LLM yn Settyansow kynsa. Ny HA agent aral.",
        open_settings="Ygeri Settyansow", streaming="Fros…", ok="Dilegys", fail="Andilegys",
        tool="Toulys", clear="Klerhe an geskows", composer="Messach dhe Lotse",
        gaps="Py devisys yw heb stevel?", night="Prof rewl chi rag nos dha.",
        matchers="Py matchers yw yn-rag, hag yn py order?",
        precedence="Displegya ragvreus matchers. Na chanjyewgh.",
        lexicon="Py hynsyow gerlyver a-dro dhe Almaynek?",
        slang="Prof slang rag hyns gerlyver. Na skrifewgh hwath.",
        for_lane="Lotse rag an hyns ma",
    ),
    "da": lotse(
        hint="Spørgsmål om Klar med det samme. Skrivning venter på Tillad.",
        empty="Spørg hvordan Klar virker — eller om et hul.",
        empty_hint="Lotse skriver intet, før du trykker Tillad.",
        you="Dig", permit="Skriveadgang", send="Send", allow="Tillad", allow_once="Én gang",
        deny="Afvis", ask="Spørg igen", need="Sæt først en LLM under Indstillinger. Ingen anden HA-agent.",
        open_settings="Åbn Indstillinger", streaming="Stream…", ok="Gyldig", fail="Ugyldig",
        tool="Værktøj", clear="Ryd chat", composer="Besked til Lotse",
        gaps="Hvilke enheder har intet rum?", night="Foreslå en husregel til godnat.",
        matchers="Hvilke matchere er tændt, og i hvilken rækkefølge?",
        precedence="Forklar matcher-rækkefølge. Ændr den ikke.",
        lexicon="Hvilke leksikonstier findes for tysk?",
        slang="Foreslå slang til en leksikonsti. Skriv ikke endnu.",
        for_lane="Lotse til dette spor",
    ),
    "nb": lotse(
        hint="Spørsmål om Klar med en gang. Skriving venter på Tillat.",
        empty="Spør hvordan Klar virker — eller om et hull.",
        empty_hint="Lotse skriver ingenting før du trykker Tillat.",
        you="Deg", permit="Skrivetilgang", send="Send", allow="Tillat", allow_once="Én gang",
        deny="Avvis", ask="Spør igjen", need="Sett først en LLM under Innstillinger. Ingen annen HA-agent.",
        open_settings="Åpne Innstillinger", streaming="Strøm…", ok="Gyldig", fail="Ugyldig",
        tool="Verktøy", clear="Tøm chat", composer="Melding til Lotse",
        gaps="Hvilke enheter har ikke rom?", night="Foreslå en husregel for god natt.",
        matchers="Hvilke matchere er på, og i hvilken rekkefølge?",
        precedence="Forklar matcher-rekkefølge. Ikke endre den.",
        lexicon="Hvilke leksikonstier finnes for tysk?",
        slang="Foreslå slang til en leksikonsti. Ikke skriv ennå.",
        for_lane="Lotse for dette sporet",
    ),
    "sv": lotse(
        hint="Frågor om Klar direkt. Skrivningar väntar på Tillåt.",
        empty="Fråga hur Klar fungerar — eller om ett hål.",
        empty_hint="Lotse skriver inget förrän du trycker Tillåt.",
        you="Du", permit="Skrivåtkomst", send="Skicka", allow="Tillåt", allow_once="En gång",
        deny="Neka", ask="Fråga igen", need="Sätt först en LLM under Inställningar. Ingen annan HA-agent.",
        open_settings="Öppna Inställningar", streaming="Ström…", ok="Giltig", fail="Ogiltig",
        tool="Verktyg", clear="Rensa chatten", composer="Meddelande till Lotse",
        gaps="Vilka enheter saknar rum?", night="Föreslå en husregel för god natt.",
        matchers="Vilka matchers är på, och i vilken ordning?",
        precedence="Förklara matcher-ordning. Ändra den inte.",
        lexicon="Vilka lexikonvägar finns för tyska?",
        slang="Föreslå slang för en lexikonväg. Skriv inte än.",
        for_lane="Lotse för detta spår",
    ),
    "fi": lotse(
        hint="Kysymykset Klarista heti. Kirjoitukset odottavat Salli.",
        empty="Kysy miten Klar toimii — tai aukosta.",
        empty_hint="Lotse ei kirjoita ennen kuin napautat Salli.",
        you="Sinä", permit="Kirjoitus", send="Lähetä", allow="Salli", allow_once="Kerran",
        deny="Kiellä", ask="Kysy uudestaan", need="Aseta ensin LLM Asetuksissa. Ei toista HA-agenttia.",
        open_settings="Avaa Asetukset", streaming="Virta…", ok="Kelvollinen", fail="Virheellinen",
        tool="Työkalu", clear="Tyhjennä keskustelu", composer="Viesti Lotselle",
        gaps="Millä laitteilla ei ole huonetta?", night="Ehdota kotisääntöä hyvää yötä varten.",
        matchers="Mitkä matcherit ovat päällä ja missä järjestyksessä?",
        precedence="Selitä matcherien järjestys. Älä muuta.",
        lexicon="Mitkä leksikonpolut ovat saksalle?",
        slang="Ehdota slangia leksikonpolulle. Älä kirjoita vielä.",
        for_lane="Lotse tälle kaistalle",
    ),
    "is": lotse(
        hint="Spurningar um Klar strax. Skrif bíða Leyfa.",
        empty="Spurðu hvernig Klar virkar — eða um eyðu.",
        empty_hint="Lotse skrifar ekkert fyrr en þú ýtir á Leyfa.",
        you="Þú", permit="Skrifaðgangur", send="Senda", allow="Leyfa", allow_once="Einu sinni",
        deny="Hafna", ask="Spyrja aftur", need="Settu fyrst LLM undir Stillingar. Enginn annar HA-umboðsmaður.",
        open_settings="Opna Stillingar", streaming="Streymi…", ok="Gilt", fail="Ógilt",
        tool="Tól", clear="Hreinsa spjall", composer="Skilaboð til Lotse",
        gaps="Hvaða tæki eru án herbergis?", night="Stingdu upp á húsreglu fyrir góða nótt.",
        matchers="Hvaða matchers eru á, og í hvaða röð?",
        precedence="Útskýrðu forgang matchers. Ekki breyta.",
        lexicon="Hvaða lexikonslóðir eru til fyrir þýsku?",
        slang="Stingdu upp á slangri fyrir lexikonslóð. Ekki skrifa enn.",
        for_lane="Lotse fyrir þessa braut",
    ),
    "et": lotse(
        hint="Küsimused Klari kohta kohe. Kirjutised ootavad Luba.",
        empty="Küsi, kuidas Klar töötab — või lünga kohta.",
        empty_hint="Lotse ei kirjuta enne, kui toksad Luba.",
        you="Sina", permit="Kirjutus", send="Saada", allow="Luba", allow_once="Korra",
        deny="Keeldu", ask="Küsi uuesti", need="Sea esmalt LLM seadetes. Pole teist HA-agenti.",
        open_settings="Ava seaded", streaming="Voog…", ok="Kehtiv", fail="Kehtetu",
        tool="Tööriist", clear="Tühjenda vestlus", composer="Sõnum Lotsile",
        gaps="Millistel seadmetel pole ruumi?", night="Paku kodureeglit head ööd jaoks.",
        matchers="Millised matcherid on sees ja millises järjekorras?",
        precedence="Selgita matcherite järjekorda. Ära muuda.",
        lexicon="Millised leksikoniteed on saksa jaoks?",
        slang="Paku slängi leksikonitee jaoks. Ära kirjuta veel.",
        for_lane="Lotse selle raja jaoks",
    ),
    "lt": lotse(
        hint="Klausimai apie Klar iškart. Rašymai laukia Leisti.",
        empty="Klausk, kaip veikia Klar — arba apie spragą.",
        empty_hint="Lotse nieko nerašo, kol nepaliesi Leisti.",
        you="Tu", permit="Rašymas", send="Siųsti", allow="Leisti", allow_once="Kartą",
        deny="Atmesti", ask="Klausti vėl", need="Pirmiausia nustatyk LLM nuostatose. Jokio kito HA agento.",
        open_settings="Atidaryti nuostatas", streaming="Srautas…", ok="Galioja", fail="Negalioja",
        tool="Įrankis", clear="Išvalyti pokalbį", composer="Žinutė Lotsui",
        gaps="Kurie įrenginiai neturi kambario?", night="Pasiūlyk namų taisyklę labanakt.",
        matchers="Kurie matcheriai įjungti ir kokia tvarka?",
        precedence="Paaiškink matcheriu eilę. Nekeisk.",
        lexicon="Kokie leksikono keliai yra vokiečių kalbai?",
        slang="Pasiūlyk slengą leksikono keliui. Dar nerašyk.",
        for_lane="Lotse šiai juostai",
    ),
    "lv": lotse(
        hint="Jautājumi par Klar uzreiz. Rakstīšana gaida Atļaut.",
        empty="Jautā, kā Klar strādā — vai par robu.",
        empty_hint="Lotse neraksta, kamēr nepieskaraties Atļaut.",
        you="Tu", permit="Rakstīšana", send="Sūtīt", allow="Atļaut", allow_once="Reizi",
        deny="Noraidīt", ask="Jautāt vēlreiz", need="Vispirms iestatiet LLM iestatījumos. Nav cita HA aģenta.",
        open_settings="Atvērt iestatījumus", streaming="Straume…", ok="Derīgs", fail="Nederīgs",
        tool="Rīks", clear="Notīrīt tērzēšanu", composer="Ziņa Lotsem",
        gaps="Kuriem ierīcēm nav telpas?", night="Iesaki mājas noteikumu arlabunakti.",
        matchers="Kuri matcheri ir ieslēgti un kādā secībā?",
        precedence="Paskaidro matcheru secību. Nemaini.",
        lexicon="Kādi leksikona ceļi ir vācu valodai?",
        slang="Iesaki slengu leksikona ceļam. Vēl neraksti.",
        for_lane="Lotse šai joslai",
    ),
}
