"""Lotse chrome for East European and East Asian Assist locales."""

from __future__ import annotations

from lang_packs.lotse_chrome import lotse

PACKS: dict[str, dict[str, str]] = {
    "cs": lotse(
        hint="Otázky na Klar hned. Zápisy čekají na Povolit.",
        empty="Zeptej se, jak Klar funguje — nebo na mezeru.",
        empty_hint="Lotse nic nezapíše, dokud neklepneš na Povolit.",
        you="Ty", permit="Zápis", send="Odeslat", allow="Povolit", allow_once="Jednou",
        deny="Odmítnout", ask="Zeptat se znovu", need="Nejdřív nastav LLM v Nastavení. Žádný další HA agent.",
        open_settings="Otevřít Nastavení", streaming="Proud…", ok="Platné", fail="Neplatné",
        tool="Nástroj", clear="Vymazat chat", composer="Zpráva Lotsovi",
        gaps="Které spotřebiče nemají místnost?", night="Navrhni domácí pravidlo na dobrou noc.",
        matchers="Které matchery jsou zapnuté a v jakém pořadí?",
        precedence="Vysvětli pořadí matcherů. Nic neměň.",
        lexicon="Které lexikonové cesty existují pro němčinu?",
        slang="Navrhni slang pro lexikonovou cestu. Zatím nepiš.",
        for_lane="Lotse pro tuto stopu",
    ),
    "sk": lotse(
        hint="Otázky na Klar hneď. Zápisy čakajú na Povoliť.",
        empty="Opýtaj sa, ako Klar funguje — alebo na medzeru.",
        empty_hint="Lotse nič nezapíše, kým neťukneš na Povoliť.",
        you="Ty", permit="Zápis", send="Odoslať", allow="Povoliť", allow_once="Raz",
        deny="Odmietnuť", ask="Opýtať sa znova", need="Najprv nastav LLM v Nastaveniach. Žiadny ďalší HA agent.",
        open_settings="Otvoriť Nastavenia", streaming="Prúd…", ok="Platné", fail="Neplatné",
        tool="Nástroj", clear="Vymazať chat", composer="Správa Lotsovi",
        gaps="Ktoré zariadenia nemajú miestnosť?", night="Navrhni domáce pravidlo na dobrú noc.",
        matchers="Ktoré matchery sú zapnuté a v akom poradí?",
        precedence="Vysvetli poradie matcherov. Nič nemeň.",
        lexicon="Ktoré lexikónové cesty existujú pre nemčinu?",
        slang="Navrhni slang pre lexikónovú cestu. Zatiaľ nepíš.",
        for_lane="Lotse pre túto stopu",
    ),
    "pl": lotse(
        hint="Pytania o Klar od razu. Zapisy czekają na Zezwól.",
        empty="Zapytaj, jak działa Klar — albo o lukę.",
        empty_hint="Lotse nic nie zapisze, dopóki nie stukniesz Zezwól.",
        you="Ty", permit="Zapis", send="Wyślij", allow="Zezwól", allow_once="Raz",
        deny="Odrzuć", ask="Zapytaj ponownie", need="Najpierw ustaw LLM w Ustawieniach. Bez innego agenta HA.",
        open_settings="Otwórz Ustawienia", streaming="Strumień…", ok="Poprawne", fail="Niepoprawne",
        tool="Narzędzie", clear="Wyczyść czat", composer="Wiadomość do Lotsa",
        gaps="Które urządzenia nie mają pokoju?", night="Zaproponuj regułę domu na dobranoc.",
        matchers="Które matchery są włączone i w jakiej kolejności?",
        precedence="Wyjaśnij kolejność matcherów. Nic nie zmieniaj.",
        lexicon="Jakie ścieżki leksykonu są dla niemieckiego?",
        slang="Zaproponuj slang na ścieżkę leksykonu. Jeszcze nie zapisuj.",
        for_lane="Lotse dla tego toru",
    ),
    "hu": lotse(
        hint="Kérdések Klarról azonnal. Az írások az Engedélyez-re várnak.",
        empty="Kérdezd, hogyan működik a Klar — vagy egy hiányról.",
        empty_hint="A Lotse nem ír, amíg nem koppintasz az Engedélyez-re.",
        you="Te", permit="Írás", send="Küldés", allow="Engedélyez", allow_once="Egyszer",
        deny="Tiltás", ask="Kérdezz újra", need="Először állíts be egy LLM-et a Beállításokban. Nincs másik HA-ügynök.",
        open_settings="Beállítások megnyitása", streaming="Folyam…", ok="Érvényes", fail="Érvénytelen",
        tool="Eszköz", clear="Csevegés törlése", composer="Üzenet a Lotsénak",
        gaps="Mely eszközöknek nincs szobájuk?", night="Javasolj házi szabályt jó éjt-re.",
        matchers="Mely matcherek vannak bekapcsolva, és milyen sorrendben?",
        precedence="Magyarázd el a matcher sorrendet. Ne változtasd.",
        lexicon="Milyen lexikonutak vannak némethez?",
        slang="Javasolj szlenget egy lexikonútra. Még ne írj.",
        for_lane="Lotse ehhez a sávhoz",
    ),
    "hr": lotse(
        hint="Pitanja o Klar odmah. Zapisi čekaju Dopusti.",
        empty="Pitaj kako Klar radi — ili o praznini.",
        empty_hint="Lotse ništa ne piše dok ne tapneš Dopusti.",
        you="Ti", permit="Zapis", send="Pošalji", allow="Dopusti", allow_once="Jednom",
        deny="Odbij", ask="Pitaj ponovo", need="Prvo postavi LLM u Postavkama. Nema drugog HA agenta.",
        open_settings="Otvori Postavke", streaming="Tok…", ok="Valjano", fail="Nevaljano",
        tool="Alat", clear="Obriši chat", composer="Poruka Lotsu",
        gaps="Koji uređaji nemaju sobu?", night="Predloži kućno pravilo za laku noć.",
        matchers="Koji matcheri su uključeni i kojim redom?",
        precedence="Objasni redoslijed matchera. Nemoj mijenjati.",
        lexicon="Koji leksikonski putevi postoje za njemački?",
        slang="Predloži slang za leksikonski put. Još ne piši.",
        for_lane="Lotse za ovu traku",
    ),
    "sl": lotse(
        hint="Vprašanja o Klar takoj. Zapisi čakajo Dovoli.",
        empty="Vprašaj, kako Klar deluje — ali o vrzeli.",
        empty_hint="Lotse ne piše, dokler ne tapneš Dovoli.",
        you="Ti", permit="Zapis", send="Pošlji", allow="Dovoli", allow_once="Enkrat",
        deny="Zavrni", ask="Vprašaj znova", need="Najprej nastavi LLM v Nastavitvah. Brez drugega HA agenta.",
        open_settings="Odpri Nastavitve", streaming="Tok…", ok="Veljavno", fail="Neveljavno",
        tool="Orodje", clear="Počisti klepet", composer="Sporočilo Lotsu",
        gaps="Kateri napravi nimajo prostora?", night="Predlagaj hišno pravilo za lahko noč.",
        matchers="Kateri matcherji so vklopljeni in v kakšnem vrstnem redu?",
        precedence="Razloži vrstni red matcherjev. Ne spreminjaj.",
        lexicon="Katere leksikonske poti obstajajo za nemščino?",
        slang="Predlagaj sleng za leksikonsko pot. Še ne piši.",
        for_lane="Lotse za to stezo",
    ),
    "bg": lotse(
        hint="Въпроси за Klar веднага. Записите чакат Разреши.",
        empty="Попитай как работи Klar — или за празнина.",
        empty_hint="Lotse не пише, докато не докоснеш Разреши.",
        you="Ти", permit="Запис", send="Изпрати", allow="Разреши", allow_once="Веднъж",
        deny="Откажи", ask="Попитай пак", need="Първо настрой LLM в Настройки. Без друг HA агент.",
        open_settings="Отвори Настройки", streaming="Поток…", ok="Валидно", fail="Невалидно",
        tool="Инструмент", clear="Изчисти чата", composer="Съобщение до Lotse",
        gaps="Кои устройства нямат стая?", night="Предложи домашна правило за лека нощ.",
        matchers="Кои matchers са включени и в какъв ред?",
        precedence="Обясни реда на matchers. Не променяй.",
        lexicon="Кои лексиконни пътища има за немски?",
        slang="Предложи жаргон за лексиконен път. Още не пиши.",
        for_lane="Lotse за тази лента",
    ),
    "sr": lotse(
        hint="Питања о Klar одмах. Уписи чекају Дозволи.",
        empty="Питај како Klar ради — или о празнини.",
        empty_hint="Lotse не пише док не тапнеш Дозволи.",
        you="Ти", permit="Упис", send="Пошаљи", allow="Дозволи", allow_once="Једном",
        deny="Одбиј", ask="Питај поново", need="Прво постави LLM у Подешавањима. Нема другог HA агента.",
        open_settings="Отвори Подешавања", streaming="Ток…", ok="Ваљано", fail="Неваљано",
        tool="Алат", clear="Обриши ћеркање", composer="Порука Lotsu",
        gaps="Који уређаји немају собу?", night="Предложи кућно правило за лаку ноћ.",
        matchers="Који matcheri су укључени и којим редом?",
        precedence="Објасни редослед matchera. Не мењај.",
        lexicon="Који лексиконски путеви постоје за немачки?",
        slang="Предложи сленг за лексиконски пут. Још не пиши.",
        for_lane="Lotse за ову траку",
    ),
    "sr-Latn": lotse(
        hint="Pitanja o Klar odmah. Upisi čekaju Dozvoli.",
        empty="Pitaj kako Klar radi — ili o praznini.",
        empty_hint="Lotse ne piše dok ne tapneš Dozvoli.",
        you="Ti", permit="Upis", send="Pošalji", allow="Dozvoli", allow_once="Jednom",
        deny="Odbij", ask="Pitaj ponovo", need="Prvo postavi LLM u Podešavanjima. Nema drugog HA agenta.",
        open_settings="Otvori Podešavanja", streaming="Tok…", ok="Valjano", fail="Nevaljano",
        tool="Alat", clear="Obriši ćaskanje", composer="Poruka Lotsu",
        gaps="Koji uređaji nemaju sobu?", night="Predloži kućno pravilo za laku noć.",
        matchers="Koji matcheri su uključeni i kojim redom?",
        precedence="Objasni redosled matchera. Ne menjaj.",
        lexicon="Koji leksikonski putevi postoje za nemački?",
        slang="Predloži sleng za leksikonski put. Još ne piši.",
        for_lane="Lotse za ovu traku",
    ),
    "uk": lotse(
        hint="Питання про Klar одразу. Записи чекають Дозволити.",
        empty="Запитай, як працює Klar — або про прогалину.",
        empty_hint="Lotse нічого не пише, доки не натиснеш Дозволити.",
        you="Ти", permit="Запис", send="Надіслати", allow="Дозволити", allow_once="Один раз",
        deny="Відхилити", ask="Запитати знову", need="Спочатку налаштуй LLM у Налаштуваннях. Без іншого агента HA.",
        open_settings="Відкрити Налаштування", streaming="Потік…", ok="Чинно", fail="Нечинно",
        tool="Інструмент", clear="Очистити чат", composer="Повідомлення Lotsе",
        gaps="Які пристрої не мають кімнати?", night="Запропонуй домашнє правило на надобраніч.",
        matchers="Які matchers увімкнені і в якому порядку?",
        precedence="Поясни порядок matchers. Не змінюй.",
        lexicon="Які шляхи лексикону є для німецької?",
        slang="Запропонуй сленг для шляху лексикону. Ще не пиши.",
        for_lane="Lotse для цієї смуги",
    ),
    "zh-CN": lotse(
        hint="随时问 Klar。写入需先点允许。",
        empty="问 Klar 怎么工作 — 或哪里有缺口。",
        empty_hint="未点允许前，Lotse 不会写入。",
        you="你", permit="写入", send="发送", allow="允许", allow_once="一次",
        deny="拒绝", ask="再问", need="先在设置里配置 LLM。不要另加 HA 对话代理。",
        open_settings="打开设置", streaming="传输…", ok="有效", fail="无效",
        tool="工具", clear="清空对话", composer="给 Lotse 发消息",
        gaps="哪些设备没有房间？", night="建议一条晚安房屋规则。",
        matchers="哪些匹配器开着，顺序如何？",
        precedence="解释匹配器优先级。先不要改。",
        lexicon="德语有哪些词库路径？",
        slang="给某条词库路径建议俚语。先不要写入。",
        for_lane="此通道的 Lotse",
    ),
    "zh-TW": lotse(
        hint="隨時問 Klar。寫入需先點允許。",
        empty="問 Klar 怎麼運作 — 或哪裡有缺口。",
        empty_hint="未點允許前，Lotse 不會寫入。",
        you="你", permit="寫入", send="傳送", allow="允許", allow_once="一次",
        deny="拒絕", ask="再問", need="先在設定裡配置 LLM。不要另加 HA 對話代理。",
        open_settings="開啟設定", streaming="串流…", ok="有效", fail="無效",
        tool="工具", clear="清除對話", composer="傳訊息給 Lotse",
        gaps="哪些裝置沒有房間？", night="建議一條晚安房屋規則。",
        matchers="哪些匹配器開著，順序如何？",
        precedence="解釋匹配器優先順序。先不要改。",
        lexicon="德語有哪些詞庫路徑？",
        slang="給某條詞庫路徑建議俚語。先不要寫入。",
        for_lane="此通道的 Lotse",
    ),
    "zh-HK": lotse(
        hint="隨時問 Klar。寫入要先撳允許。",
        empty="問 Klar 點運作 — 或者邊度有缺口。",
        empty_hint="未撳允許之前，Lotse 唔會寫入。",
        you="你", permit="寫入", send="傳送", allow="允許", allow_once="一次",
        deny="拒絕", ask="再問", need="先喺設定度配置 LLM。唔好再加 HA 對話代理。",
        open_settings="打開設定", streaming="串流…", ok="有效", fail="無效",
        tool="工具", clear="清空對話", composer="傳訊息畀 Lotse",
        gaps="邊啲裝置冇房間？", night="建議一條晚安房屋規則。",
        matchers="邊啲匹配器開住，次序點？",
        precedence="解釋匹配器優先次序。暫時唔好改。",
        lexicon="德文有邊啲詞庫路徑？",
        slang="俾某條詞庫路徑建議俚語。暫時唔好寫入。",
        for_lane="呢條通道嘅 Lotse",
    ),
    "ja": lotse(
        hint="Klar への質問はすぐ。書き込みは許可待ち。",
        empty="Klar の動きを聞く — または欠けを聞く。",
        empty_hint="許可をタップするまで Lotse は書きません。",
        you="あなた", permit="書き込み", send="送信", allow="許可", allow_once="一度だけ",
        deny="拒否", ask="もう一度聞く", need="先に設定で LLM を入れてください。別の HA 会話エージェントは不要。",
        open_settings="設定を開く", streaming="ストリーム…", ok="有効", fail="無効",
        tool="ツール", clear="チャットを消去", composer="Lotse へメッセージ",
        gaps="部屋のないデバイスはどれ？", night="おやすみ用の家ルールを提案して。",
        matchers="どのマッチャーがオンで、どの順？",
        precedence="マッチャーの優先を説明。まだ変えない。",
        lexicon="ドイツ語の語彙パスはどれ？",
        slang="語彙パスへスラングを提案。まだ書かない。",
        for_lane="このレーンの Lotse",
    ),
    "ko": lotse(
        hint="Klar 질문은 바로. 쓰기는 허용을 기다립니다.",
        empty="Klar가 어떻게 일하는지 — 또는 빈틈을 물어보세요.",
        empty_hint="허용을 누르기 전 Lotse는 쓰지 않습니다.",
        you="나", permit="쓰기", send="보내기", allow="허용", allow_once="한 번",
        deny="거부", ask="다시 묻기", need="먼저 설정에서 LLM을 넣으세요. 다른 HA 대화 에이전트는 필요 없습니다.",
        open_settings="설정 열기", streaming="스트림…", ok="유효", fail="무효",
        tool="도구", clear="채팅 지우기", composer="Lotse에게 메시지",
        gaps="방이 없는 기기는?", night="잘 자요 집 규칙을 제안해 주세요.",
        matchers="어떤 매처가 켜져 있고 순서는?",
        precedence="매처 우선순위를 설명하세요. 아직 바꾸지 마세요.",
        lexicon="독일어 어휘 경로는?",
        slang="어휘 경로에 속어를 제안하세요. 아직 쓰지 마세요.",
        for_lane="이 레인의 Lotse",
    ),
    "th": lotse(
        hint="ถาม Klar ได้ทันที การเขียนรออนุญาต",
        empty="ถามว่า Klar ทำงานอย่างไร — หรือช่องว่าง",
        empty_hint="Lotse จะไม่เขียนจนกว่าจะแตะอนุญาต",
        you="คุณ", permit="การเขียน", send="ส่ง", allow="อนุญาต", allow_once="ครั้งเดียว",
        deny="ปฏิเสธ", ask="ถามอีก", need="ตั้ง LLM ในการตั้งค่าก่อน ไม่ต้องมีเอเจนต์ HA อื่น",
        open_settings="เปิดการตั้งค่า", streaming="สตรีม…", ok="ถูกต้อง", fail="ไม่ถูกต้อง",
        tool="เครื่องมือ", clear="ล้างแชท", composer="ข้อความถึง Lotse",
        gaps="อุปกรณ์ใดยังไม่มีห้อง?", night="เสนอกฎบ้านสำหรับราตรีสวัสดิ์",
        matchers="แมตเชอร์ใดเปิดอยู่ และลำดับใด?",
        precedence="อธิบายลำดับแมตเชอร์ อย่าเพิ่งเปลี่ยน",
        lexicon="เส้นทางศัพท์เยอรมันมีอะไรบ้าง?",
        slang="เสนอสแลงให้เส้นทางศัพท์ อย่าเพิ่งเขียน",
        for_lane="Lotse สำหรับเลนนี้",
    ),
    "vi": lotse(
        hint="Hỏi Klar ngay. Ghi chờ Cho phép.",
        empty="Hỏi Klar hoạt động ra sao — hoặc chỗ trống.",
        empty_hint="Lotse không ghi cho đến khi bạn chạm Cho phép.",
        you="Bạn", permit="Ghi", send="Gửi", allow="Cho phép", allow_once="Một lần",
        deny="Từ chối", ask="Hỏi lại", need="Hãy cấu hình LLM trong Cài đặt trước. Không cần tác nhân HA khác.",
        open_settings="Mở Cài đặt", streaming="Luồng…", ok="Hợp lệ", fail="Không hợp lệ",
        tool="Công cụ", clear="Xóa trò chuyện", composer="Tin nhắn tới Lotse",
        gaps="Thiết bị nào chưa có phòng?", night="Đề xuất quy tắc nhà cho chúc ngủ ngon.",
        matchers="Matcher nào đang bật và thứ tự ra sao?",
        precedence="Giải thích thứ tự matcher. Đừng đổi.",
        lexicon="Đường từ điển nào cho tiếng Đức?",
        slang="Đề xuất biệt ngữ cho một đường từ điển. Chưa ghi.",
        for_lane="Lotse cho làn này",
    ),
    "id": lotse(
        hint="Tanya Klar sekarang. Tulis menunggu Izinkan.",
        empty="Tanya cara Klar bekerja — atau soal celah.",
        empty_hint="Lotse tidak menulis sebelum kamu mengetuk Izinkan.",
        you="Kamu", permit="Tulis", send="Kirim", allow="Izinkan", allow_once="Sekali",
        deny="Tolak", ask="Tanya lagi", need="Atur LLM di Pengaturan dulu. Tanpa agen HA lain.",
        open_settings="Buka Pengaturan", streaming="Aliran…", ok="Sah", fail="Tidak sah",
        tool="Alat", clear="Hapus obrolan", composer="Pesan ke Lotse",
        gaps="Perangkat mana yang belum punya ruangan?", night="Usulkan aturan rumah untuk selamat malam.",
        matchers="Matcher mana yang nyala, dan urutannya?",
        precedence="Jelaskan urutan matcher. Jangan ubah.",
        lexicon="Jalur leksikon mana untuk Jerman?",
        slang="Usulkan slang untuk jalur leksikon. Jangan tulis dulu.",
        for_lane="Lotse untuk jalur ini",
    ),
    "ms": lotse(
        hint="Tanya Klar sekarang. Tulis menunggu Benarkan.",
        empty="Tanya cara Klar bekerja — atau tentang jurang.",
        empty_hint="Lotse tidak menulis sehingga anda ketik Benarkan.",
        you="Anda", permit="Tulis", send="Hantar", allow="Benarkan", allow_once="Sekali",
        deny="Tolak", ask="Tanya lagi", need="Tetapkan LLM dalam Tetapan dahulu. Tiada ejen HA lain.",
        open_settings="Buka Tetapan", streaming="Strim…", ok="Sah", fail="Tidak sah",
        tool="Alat", clear="Kosongkan sembang", composer="Mesej kepada Lotse",
        gaps="Peranti manakah tiada bilik?", night="Cadangkan peraturan rumah untuk selamat malam.",
        matchers="Matcher manakah hidup, dan dalam tertib apa?",
        precedence="Terangkan tertib matcher. Jangan ubah.",
        lexicon="Laluan leksikon manakah untuk Jerman?",
        slang="Cadangkan slang untuk laluan leksikon. Jangan tulis lagi.",
        for_lane="Lotse untuk lorong ini",
    ),
    "mn": lotse(
        hint="Klar-ийн асуулт шууд. Бичилт Зөвшөөр-ийг хүлээнэ.",
        empty="Klar хэрхэн ажилладгийг — эсвэл цоорхойг асуу.",
        empty_hint="Зөвшөөр дартал Lotse бичихгүй.",
        you="Чи", permit="Бичих", send="Илгээх", allow="Зөвшөөр", allow_once="Нэг удаа",
        deny="Татгалз", ask="Дахин асуу", need="Эхлээд Тохиргоонд LLM тавь. Өөр HA агент хэрэггүй.",
        open_settings="Тохиргоо нээх", streaming="Урсгал…", ok="Хүчинтэй", fail="Хүчингүй",
        tool="Хэрэгсэл", clear="Чатыг цэвэрлэх", composer="Lotsed зурвас",
        gaps="Аль төхөөрөмжид өрөө байхгүй вэ?", night="Сайн шөнө гэрийн дүрэм санал болго.",
        matchers="Аль matcher асаалттай, ямар дарааллаар вэ?",
        precedence="Matcher-ийн дарааллыг тайлбарла. Бүү өөрчил.",
        lexicon="Германд ямар лексикон зам байдаг вэ?",
        slang="Лексикон замд слэнг санал болго. Одоохон битгий бич.",
        for_lane="Энэ замын Lotse",
    ),
}
