"""Yes / no / not-now chips for every Assist locale."""

from __future__ import annotations

YESNO: dict[str, tuple[str, str, str]] = {
    "af": ("Ja", "Nee", "Nie nou nie"),
    "ar": ("نعم", "لا", "ليس الآن"),
    "bg": ("Да", "Не", "Не сега"),
    "bn": ("হ্যাঁ", "না", "এখন নয়"),
    "ca": ("Sí", "No", "Ara no"),
    "cs": ("Ano", "Ne", "Teď ne"),
    "cy": ("Ie", "Na", "Nid nawr"),
    "da": ("Ja", "Nej", "Ikke nu"),
    "de-AT": ("Ja", "Nein", "Nicht jetzt"),
    "de-CH": ("Ja", "Nei", "Nöd jetzt"),
    "el": ("Ναι", "Όχι", "Όχι τώρα"),
    "en-GB": ("Yes", "No", "Not now"),
    "es": ("Sí", "No", "Ahora no"),
    "et": ("Jah", "Ei", "Mitte praegu"),
    "eu": ("Bai", "Ez", "Orain ez"),
    "fa": ("بله", "خیر", "الان نه"),
    "fi": ("Kyllä", "Ei", "Ei nyt"),
    "fr": ("Oui", "Non", "Pas maintenant"),
    "ga": ("Tá", "Níl", "Ní anois"),
    "gl": ("Si", "Non", "Agora non"),
    "gu": ("હા", "ના", "હમણાં નહીં"),
    "he": ("כן", "לא", "לא עכשיו"),
    "hi": ("हाँ", "नहीं", "अभी नहीं"),
    "hr": ("Da", "Ne", "Ne sada"),
    "hu": ("Igen", "Nem", "Most nem"),
    "hy": ("Այո", "Ոչ", "Հիմա ոչ"),
    "id": ("Ya", "Tidak", "Tidak sekarang"),
    "is": ("Já", "Nei", "Ekki núna"),
    "it": ("Sì", "No", "Non ora"),
    "ja": ("はい", "いいえ", "今はしない"),
    "ka": ("კი", "არა", "ახლა არა"),
    "kn": ("ಹೌದು", "ಇಲ್ಲ", "ಈಗ ಬೇಡ"),
    "ko": ("예", "아니요", "지금은 아님"),
    "kw": ("Ya", "Na", "Nyns yw lemmyn"),
    "lb": ("Jo", "Nee", "Net elo"),
    "lt": ("Taip", "Ne", "Ne dabar"),
    "lv": ("Jā", "Nē", "Ne tagad"),
    "ml": ("അതെ", "ഇല്ല", "ഇപ്പോൾ വേണ്ട"),
    "mn": ("Тийм", "Үгүй", "Одоо биш"),
    "mr": ("हो", "नाही", "आत्ता नाही"),
    "ms": ("Ya", "Tidak", "Bukan sekarang"),
    "nb": ("Ja", "Nei", "Ikke nå"),
    "ne": ("हो", "होइन", "अहिले होइन"),
    "nl": ("Ja", "Nee", "Niet nu"),
    "pa": ("ਹਾਂ", "ਨਹੀਂ", "ਹੁਣ ਨਹੀਂ"),
    "pl": ("Tak", "Nie", "Nie teraz"),
    "pt": ("Sim", "Não", "Agora não"),
    "pt-BR": ("Sim", "Não", "Agora não"),
    "ro": ("Da", "Nu", "Nu acum"),
    "sk": ("Áno", "Nie", "Teraz nie"),
    "sl": ("Da", "Ne", "Ne zdaj"),
    "sr": ("Да", "Не", "Не сада"),
    "sr-Latn": ("Da", "Ne", "Ne sada"),
    "sv": ("Ja", "Nej", "Inte nu"),
    "sw": ("Ndiyo", "Hapana", "Sio sasa"),
    "ta": ("ஆம்", "இல்லை", "இப்போது வேண்டாம்"),
    "te": ("అవును", "కాదు", "ఇప్పుడు కాదు"),
    "th": ("ใช่", "ไม่", "ยังไม่ตอนนี้"),
    "tr": ("Evet", "Hayır", "Şimdi değil"),
    "uk": ("Так", "Ні", "Не зараз"),
    "ur": ("ہاں", "نہیں", "ابھی نہیں"),
    "vi": ("Có", "Không", "Không phải bây giờ"),
    "zh-CN": ("是", "否", "先不"),
    "zh-HK": ("係", "唔係", "而家唔好"),
    "zh-TW": ("是", "否", "先不要"),
}


def apply_yesno(packs: dict[str, dict[str, str]]) -> None:
    for code, fields in packs.items():
        yes, no, later = YESNO.get(code, ("Yes", "No", "Not now"))
        fields["trainerYes"] = yes
        fields["trainerNo"] = no
        fields["trainerNotNow"] = later
