"""Trainer prompt chips for RTL, Caucasian, Indic, and Swahili locales."""

from __future__ import annotations

PACKS: dict[str, dict[str, str]] = {'ar': {'trainerPromptGaps': 'أي الأجهزة بلا غرفة؟',
        'trainerPromptNight': 'اقترح قاعدة منزل لتصبح على خير.',
        'trainerPromptMatchers': 'أي matchers شغّالة، وبأي ترتيب؟',
        'trainerPromptPrecedence': 'اشرح أسبقية الـ matchers. لا تغيّرها.',
        'trainerPromptLexicon': 'أي مسارات معجم توجد للألمانية؟',
        'trainerPromptSlang': 'اقترح عامية لمسار معجم. لا تكتب بعد.'},
 'he': {'trainerPromptGaps': 'אילו מכשירים בלי חדר?',
        'trainerPromptNight': 'הצע כלל בית ללילה טוב.',
        'trainerPromptMatchers': 'אילו matchers פעילים, ובאיזה סדר?',
        'trainerPromptPrecedence': 'הסבר את עדיפות ה-matchers. אל תשנה.',
        'trainerPromptLexicon': 'אילו נתיבי לקסיקון יש לגרמנית?',
        'trainerPromptSlang': 'הצע סלנג לנתיב לקסיקון. אל תכתוב עדיין.'},
 'fa': {'trainerPromptGaps': 'کدام دستگاه\u200cها اتاق ندارند؟',
        'trainerPromptNight': 'یک قانون خانه برای شب بخیر پیشنهاد کن.',
        'trainerPromptMatchers': 'کدام matcherها روشن\u200cاند و به چه ترتیب؟',
        'trainerPromptPrecedence': 'تقدم matcherها را توضیح بده. تغییرش نده.',
        'trainerPromptLexicon': 'کدام مسیرهای واژگان برای آلمانی هست؟',
        'trainerPromptSlang': 'برای یک مسیر واژگان عامیانه پیشنهاد کن. هنوز ننویس.'},
 'ur': {'trainerPromptGaps': 'کن آلات کا کمرہ نہیں؟',
        'trainerPromptNight': 'شب بخیر کے لیے گھر کا قاعدہ تجویز کریں۔',
        'trainerPromptMatchers': 'کون سے matchers آن ہیں، اور کس ترتیب میں؟',
        'trainerPromptPrecedence': 'matcher کی ترجیح بیان کریں۔ اسے نہ بدلیں۔',
        'trainerPromptLexicon': 'جرمن کے لیے کون سے لغت راستے ہیں؟',
        'trainerPromptSlang': 'لغت راستے کے لیے سلینگ تجویز کریں۔ ابھی نہ لکھیں۔'},
 'tr': {'trainerPromptGaps': 'Hangi cihazların odası yok?',
        'trainerPromptNight': 'İyi geceler için bir ev kuralı öner.',
        'trainerPromptMatchers': 'Hangi matcherlar açık ve hangi sırada?',
        'trainerPromptPrecedence': 'Matcher önceliğini açıkla. Değiştirme.',
        'trainerPromptLexicon': 'Almanca için hangi sözlük yolları var?',
        'trainerPromptSlang': 'Bir sözlük yoluna argo öner. Henüz yazma.'},
 'el': {'trainerPromptGaps': 'Ποιες συσκευές δεν έχουν δωμάτιο;',
        'trainerPromptNight': 'Πρότεινε έναν οικιακό κανόνα για καληνύχτα.',
        'trainerPromptMatchers': 'Ποιοι matchers είναι ενεργοί και με ποια σειρά;',
        'trainerPromptPrecedence': 'Εξήγησε την προτεραιότητα των matchers. Μην την αλλάξεις.',
        'trainerPromptLexicon': 'Ποια μονοπάτια λεξικού υπάρχουν για τα γερμανικά;',
        'trainerPromptSlang': 'Πρότεινε αργκό για ένα μονοπάτι λεξικού. Μην γράψεις ακόμα.'},
 'sw': {'trainerPromptGaps': 'Vifaa vipi havina chumba?',
        'trainerPromptNight': 'Pendekeza sheria ya nyumba kwa usiku mwema.',
        'trainerPromptMatchers': 'Matcher zipi zimewashwa, na kwa mpangilio upi?',
        'trainerPromptPrecedence': 'Eleza kipaumbele cha matcher. Usibadilishe.',
        'trainerPromptLexicon': 'Njia zipi za kamusi zipo kwa Kijerumani?',
        'trainerPromptSlang': 'Pendekeza misamiati ya kamusi. Usiandike bado.'},
 'hy': {'trainerPromptGaps': 'Ո՞ր սարքերն են առանց սենյակի։',
        'trainerPromptNight': 'Առաջարկիր տնային կանոն բարի գիշերի համար։',
        'trainerPromptMatchers': 'Ո՞ր matcher-ներն են միացված և ի՞նչ հերթականությամբ։',
        'trainerPromptPrecedence': 'Բացատրիր matcher-ների առաջնությունը։ Մի փոխիր։',
        'trainerPromptLexicon': 'Գերմաներենի համար ո՞ր բառարանային ուղիներն են։',
        'trainerPromptSlang': 'Առաջարկիր ժարգոն բառարանային ուղու համար։ Դեռ մի գրիր։'},
 'ka': {'trainerPromptGaps': 'რომელ მოწყობილობებს არ აქვთ ოთახი?',
        'trainerPromptNight': 'შემოგვთავაზე სახლის წესი ძილი ნებისთვის.',
        'trainerPromptMatchers': 'რომელი matcher-ებია ჩართული და რა თანმიმდევრობით?',
        'trainerPromptPrecedence': 'ახსენი matcher-ების პრიორიტეტი. ნუ შეცვლი.',
        'trainerPromptLexicon': 'რომელი ლექსიკონის გზებია გერმანულისთვის?',
        'trainerPromptSlang': 'შემოგვთავაზე სლენგი ლექსიკონის გზისთვის. ჯერ ნუ დაწერ.'},
 'hi': {'trainerPromptGaps': 'किन उपकरणों का कमरा नहीं है?',
        'trainerPromptNight': 'शुभ रात्रि के लिए घर का नियम सुझाएँ।',
        'trainerPromptMatchers': 'कौन से matcher चालू हैं, और किस क्रम में?',
        'trainerPromptPrecedence': 'matcher की प्राथमिकता समझाएँ। बदलें नहीं।',
        'trainerPromptLexicon': 'जर्मन के लिए कौन से शब्दकोश पथ हैं?',
        'trainerPromptSlang': 'शब्दकोश पथ के लिए स्लैंग सुझाएँ। अभी न लिखें।'},
 'bn': {'trainerPromptGaps': 'কোন যন্ত্রের ঘর নেই?',
        'trainerPromptNight': 'শুভ রাত্রির জন্য ঘরের নিয়ম প্রস্তাব করুন।',
        'trainerPromptMatchers': 'কোন matcher চালু, এবং কোন ক্রমে?',
        'trainerPromptPrecedence': 'matcher-এর অগ্রাধিকার ব্যাখ্যা করুন। পরিবর্তন করবেন না।',
        'trainerPromptLexicon': 'জার্মানের জন্য কোন অভিধান পথ আছে?',
        'trainerPromptSlang': 'অভিধান পথের জন্য স্ল্যাং প্রস্তাব করুন। এখনই লিখবেন না।'},
 'mr': {'trainerPromptGaps': 'कोणत्या उपकरणांना खोली नाही?',
        'trainerPromptNight': 'शुभ रात्रीसाठी घरचा नियम सुचवा.',
        'trainerPromptMatchers': 'कोणते matcher चालू आहेत, आणि कोणत्या क्रमाने?',
        'trainerPromptPrecedence': 'matcher ची प्राधान्य समजावून सांगा. बदलू नका.',
        'trainerPromptLexicon': 'जर्मनसाठी कोणते शब्दकोश मार्ग आहेत?',
        'trainerPromptSlang': 'शब्दकोश मार्गासाठी स्लँग सुचवा. अजून लिहू नका.'},
 'ne': {'trainerPromptGaps': 'कुन यन्त्रहरूको कोठा छैन?',
        'trainerPromptNight': 'शुभ रात्रीका लागि घरको नियम सुझाव दिनुहोस्।',
        'trainerPromptMatchers': 'कुन matcher चालू छन्, र कुन क्रममा?',
        'trainerPromptPrecedence': 'matcher को प्राथमिकता व्याख्या गर्नुहोस्। नबदल्नुहोस्।',
        'trainerPromptLexicon': 'जर्मनका लागि कुन शब्दकोश पथ छन्?',
        'trainerPromptSlang': 'शब्दकोश पथका लागि स्ल्याङ सुझाव दिनुहोस्। अहिले नलेख्नुहोस्।'},
 'gu': {'trainerPromptGaps': 'કયા ઉપકરણોને ઓરડો નથી?',
        'trainerPromptNight': 'શુભ રાત્રિ માટે ઘરનો નિયમ સૂચવો.',
        'trainerPromptMatchers': 'કયા matcher ચાલુ છે, અને કયા ક્રમમાં?',
        'trainerPromptPrecedence': 'matcherની પ્રાથમિકતા સમજાવો. બદલશો નહીં.',
        'trainerPromptLexicon': 'જર્મન માટે કયા શબ્દકોશ પથ છે?',
        'trainerPromptSlang': 'શબ્દકોશ પથ માટે સ્લેંગ સૂચવો. હજુ ન લખો.'},
 'kn': {'trainerPromptGaps': 'ಯಾವ ಸಾಧನಗಳಿಗೆ ಕೋಣೆ ಇಲ್ಲ?',
        'trainerPromptNight': 'ಶುಭ ರಾತ್ರಿಗೆ ಮನೆಯ ನಿಯಮ ಸೂಚಿಸಿ.',
        'trainerPromptMatchers': 'ಯಾವ matcherಗಳು ಆನ್, ಯಾವ ಕ್ರಮದಲ್ಲಿ?',
        'trainerPromptPrecedence': 'matcher ಆದ್ಯತೆ ವಿವರಿಸಿ. ಬದಲಾಯಿಸಬೇಡಿ.',
        'trainerPromptLexicon': 'ಜರ್ಮನ್\u200cಗೆ ಯಾವ ಶಬ್ದಕೋಶ ಮಾರ್ಗಗಳಿವೆ?',
        'trainerPromptSlang': 'ಶಬ್ದಕೋಶ ಮಾರ್ಗಕ್ಕೆ ಸ್ಲ್ಯಾಂಗ್ ಸೂಚಿಸಿ. ಈಗ ಬರೆಯಬೇಡಿ.'},
 'ml': {'trainerPromptGaps': 'ഏതു ഉപകരണങ്ങൾക്ക് മുറിയില്ല?',
        'trainerPromptNight': 'ശുഭ രാത്രിക്ക് വീട്ടു നിയമം നിർദേശിക്കുക.',
        'trainerPromptMatchers': 'ഏതു matcher ഓണാണ്, ഏത് ക്രമത്തിൽ?',
        'trainerPromptPrecedence': 'matcher മുൻഗണന വിശദീകരിക്കുക. മാറ്റരുത്.',
        'trainerPromptLexicon': 'ജർമന് ഏതു നിഘണ്ടു പാതകളുണ്ട്?',
        'trainerPromptSlang': 'നിഘണ്ടു പാതയ്ക്ക് സ്ലാങ് നിർദേശിക്കുക. ഇപ്പോൾ എഴുതരുത്.'},
 'ta': {'trainerPromptGaps': 'எந்த சாதனங்களுக்கு அறை இல்லை?',
        'trainerPromptNight': 'இனிய இரவுக்கு வீட்டு விதி பரிந்துரைக்கவும்.',
        'trainerPromptMatchers': 'எந்த matcher-கள் இயக்கத்தில், எந்த வரிசையில்?',
        'trainerPromptPrecedence': 'matcher முன்னுரிமையை விளக்குங்கள். மாற்ற வேண்டாம்.',
        'trainerPromptLexicon': 'ஜெர்மனுக்கு எந்த அகராதி பாதைகள் உள்ளன?',
        'trainerPromptSlang': 'அகராதி பாதைக்கு ஸ்லாங் பரிந்துரைக்கவும். இப்போது எழுத வேண்டாம்.'},
 'te': {'trainerPromptGaps': 'ఏ పరికరాలకు గది లేదు?',
        'trainerPromptNight': 'శుభ రాత్రికి ఇంటి నియమం సూచించండి.',
        'trainerPromptMatchers': 'ఏ matcherలు ఆన్\u200cలో ఉన్నాయి, ఏ క్రమంలో?',
        'trainerPromptPrecedence': 'matcher ప్రాధాన్యాన్ని వివరించండి. మార్చవద్దు.',
        'trainerPromptLexicon': 'జర్మన్\u200cకు ఏ నిఘంటువు మార్గాలున్నాయి?',
        'trainerPromptSlang': 'నిఘంటువు మార్గానికి స్లాంగ్ సూచించండి. ఇప్పుడు రాయవద్దు.'},
 'pa': {'trainerPromptGaps': 'ਕਿਹੜੇ ਉਪਕਰਣਾਂ ਦਾ ਕਮਰਾ ਨਹੀਂ?',
        'trainerPromptNight': 'ਸ਼ੁਭ ਰਾਤ ਲਈ ਘਰ ਦਾ ਨਿਯਮ ਸੁਝਾਓ।',
        'trainerPromptMatchers': 'ਕਿਹੜੇ matcher ਚਾਲੂ ਹਨ, ਅਤੇ ਕਿਸ ਕ੍ਰਮ ਵਿੱਚ?',
        'trainerPromptPrecedence': 'matcher ਦੀ ਤਰਜੀਹ ਸਮਝਾਓ। ਬਦਲੋ ਨਾ।',
        'trainerPromptLexicon': 'ਜਰਮਨ ਲਈ ਕਿਹੜੇ ਸ਼ਬਦਕੋਸ਼ ਰਾਹ ਹਨ?',
        'trainerPromptSlang': 'ਸ਼ਬਦਕੋਸ਼ ਰਾਹ ਲਈ ਸਲੈਂਗ ਸੁਝਾਓ। ਹੁਣੇ ਨਾ ਲਿਖੋ।'}}
