"""Settings hint chrome: West European Assist locales."""

from __future__ import annotations

from lang_packs.settings_hints import row

PACKS: dict[str, dict[str, str]] = {
    "fr": row(
        "Résoudre les appareils : Klar choisit l’entité. Pièces seulement : il s’arrête à la pièce.",
        "Activé : serrures, fermeture de volets et commandes risquées larges ou pour toute une pièce demandent d’abord confirmation. Désactivé : elles s’exécutent tout de suite.",
        "Activé : Klar garde les 200 derniers tours pendant 24 h. Nécessaire pour les téléchargements ci-dessous.",
        "Activé : les téléchargements incluent la phrase dite. Désactivé : seulement expurgé.",
        "Désactivé par défaut. Activé : après un échec, une correspondance de sens locale peut encore retrouver l’intention. Pas un LLM.",
        "Requis pour enregistrer depuis cet écran. La même valeur que le jeton de l’App.",
        "État",
        "Réponses comme l’état d’une pièce ou d’un appareil. Activé : le LLM reformule la phrase finie.",
        "Commandes",
        "Accusé après que Klar a déjà exécuté la commande. Activé : « la lumière est allumée » prend cette voix.",
        "Questions de suivi",
        "Questions quelle-pièce et quel-appareil. Activé : la question de Klar est reformulée.",
        "Rejet",
        "Réponses du type je-n’ai-pas-compris. Activé : ces phrases prennent cette voix.",
        "Les réponses LLM du chat et du calendrier restent telles quelles — pas de second raffinage.",
        "Enregistré.",
        "Enregistrement impossible.",
        "Non enregistré. Saisis le jeton d’écriture sous Engine.",
    ),
    "nl": row(
        "Apparaten oplossen: Klar kiest de entiteit. Alleen ruimtes: het stopt bij de ruimte.",
        "Aan: sloten, sluitende rolluiken en grote of ruimtebrede riskante commando’s vragen eerst een keer. Uit: ze worden meteen uitgevoerd.",
        "Aan: Klar bewaart de laatste 200 beurten 24 uur. Nodig voor de downloads hieronder.",
        "Aan: downloads bevatten de gesproken zin. Uit: alleen onleesbaar gemaakt.",
        "Standaard uit. Aan: na een misser kan een lokale betekenismatch de intentie nog vinden. Geen LLM.",
        "Nodig om vanaf dit scherm op te slaan. Dezelfde waarde als het App-token.",
        "Status",
        "Antwoorden zoals kamer- of apparaatstatus. Aan: de LLM herschrijft de afgeronde zin.",
        "Commando’s",
        "Bevestiging nadat Klar het commando al heeft uitgevoerd. Aan: «licht is aan» krijgt deze stem.",
        "Vervolgvragen",
        "Welke-kamer- en welk-apparaatvragen. Aan: Klars vraag wordt herschreven.",
        "Afwijzing",
        "Antwoorden zoals ik-begreep-het-niet. Aan: die zinnen krijgen deze stem.",
        "Chat- en agenda-LLM-antwoorden blijven zoals ze zijn — geen tweede herschrijving.",
        "Opgeslagen.",
        "Opslaan mislukt.",
        "Niet opgeslagen. Vul het schrijftoken in onder Engine.",
    ),
    "es": row(
        "Resolver dispositivos: Klar elige la entidad. Solo habitaciones: se detiene en la estancia.",
        "Activado: cerraduras, cierre de persianas y órdenes arriesgadas grandes o de toda la habitación preguntan primero. Desactivado: se ejecutan al momento.",
        "Activado: Klar guarda los últimos 200 turnos 24 horas. Hace falta para las descargas de abajo.",
        "Activado: las descargas incluyen la frase dicha. Desactivado: solo redactado.",
        "Desactivado por defecto. Activado: tras un fallo, una coincidencia de sentido local aún puede recuperar la intención. No es un LLM.",
        "Hace falta para guardar desde esta pantalla. El mismo valor que el token de la App.",
        "Estado",
        "Respuestas como el estado de una habitación o un dispositivo. Activado: el LLM reescribe la frase terminada.",
        "Órdenes",
        "Acuse después de que Klar ya ejecutó la orden. Activado: «la luz está encendida» usa esta voz.",
        "Preguntas de seguimiento",
        "Preguntas de qué habitación y qué dispositivo. Activado: la pregunta de Klar se reescribe.",
        "Rechazo",
        "Respuestas de no-he-entendido. Activado: esas frases usan esta voz.",
        "Las respuestas LLM del chat y del calendario se quedan como están: sin un segundo refinamiento.",
        "Guardado.",
        "No se pudo guardar.",
        "No guardado. Introduce el token de escritura en Engine.",
    ),
    "it": row(
        "Risolvi dispositivi: Klar sceglie l’entità. Solo stanze: si ferma all’area.",
        "Attivo: serrature, chiusura di tapparelle e comandi rischiosi ampi o per tutta la stanza chiedono prima conferma. Spento: partono subito.",
        "Attivo: Klar tiene gli ultimi 200 turni per 24 ore. Serve per i download sotto.",
        "Attivo: i download includono la frase detta. Spento: solo redatto.",
        "Spento di default. Attivo: dopo un errore, una corrispondenza di senso locale può ancora recuperare l’intento. Non è un LLM.",
        "Serve per salvare da questa schermata. Lo stesso valore del token dell’App.",
        "Stato",
        "Risposte come lo stato di una stanza o di un dispositivo. Attivo: l’LLM riscrive la frase finita.",
        "Comandi",
        "Conferma dopo che Klar ha già eseguito il comando. Attivo: «la luce è accesa» usa questa voce.",
        "Domande di seguito",
        "Domande quale-stanza e quale-dispositivo. Attivo: la domanda di Klar viene riscritta.",
        "Rifiuto",
        "Risposte del tipo non-ho-capito. Attivo: quelle frasi usano questa voce.",
        "Le risposte LLM di chat e calendario restano com’è — niente secondo raffinamento.",
        "Salvato.",
        "Salvataggio non riuscito.",
        "Non salvato. Inserisci il token di scrittura sotto Engine.",
    ),
    "pt": row(
        "Resolver dispositivos: o Klar escolhe a entidade. Só divisões: pára na área.",
        "Ligado: fechaduras, fecho de estores e comandos arriscados grandes ou de toda a divisão perguntam primeiro. Desligado: executam de imediato.",
        "Ligado: o Klar guarda as últimas 200 turnos durante 24 h. Precisa-se para as transferências abaixo.",
        "Ligado: as transferências incluem a frase dita. Desligado: só redigido.",
        "Desligado por predefinição. Ligado: após um falhanço, uma correspondência de sentido local ainda pode recuperar a intenção. Não é um LLM.",
        "Necessário para guardar neste ecrã. O mesmo valor que o token da App.",
        "Estado",
        "Respostas como o estado de uma divisão ou dispositivo. Ligado: o LLM reescreve a frase concluída.",
        "Comandos",
        "Confirmação depois de o Klar já ter executado o comando. Ligado: «a luz está ligada» usa esta voz.",
        "Perguntas de seguimento",
        "Perguntas que-divisão e que-dispositivo. Ligado: a pergunta do Klar é reescrita.",
        "Rejeição",
        "Respostas do tipo não-percebi. Ligado: essas frases usam esta voz.",
        "As respostas LLM do chat e do calendário ficam como estão — sem segundo refinamente.",
        "Guardado.",
        "Não foi possível guardar.",
        "Não guardado. Introduz o token de escrita em Engine.",
    ),
    "ca": row(
        "Resoldre dispositius: Klar tria l’entitat. Només habitacions: s’atura a l’àrea.",
        "Activat: panys, tancar persianes i ordres arriscades grans o de tota l’habitació pregunten primer. Desactivat: s’executen de seguida.",
        "Activat: Klar guarda els darrers 200 torns 24 hores. Cal per a les baixades de sota.",
        "Activat: les baixades inclouen la frase dita. Desactivat: només redactat.",
        "Desactivat per defecte. Activat: després d’un error, una coincidència de sentit local encara pot recuperar la intenció. No és un LLM.",
        "Cal per desar des d’aquesta pantalla. El mateix valor que el testimoni de l’App.",
        "Estat",
        "Respostes com l’estat d’una habitació o un dispositiu. Activat: l’LLM reescriu la frase acabada.",
        "Ordres",
        "Confirmació després que Klar ja ha executat l’ordre. Activat: «el llum està encès» usa aquesta veu.",
        "Preguntes de seguiment",
        "Preguntes quina-habitació i quin-dispositiu. Activat: la pregunta de Klar es reescriu.",
        "Rebuig",
        "Respostes del tipus no-ho-he-entès. Activat: aquestes frases usen aquesta veu.",
        "Les respostes LLM del xat i del calendari es queden com estan — sense un segon refinament.",
        "Desat.",
        "No s’ha pogut desar.",
        "No desat. Introdueix el testimoni d’escriptura a Engine.",
    ),
    "ro": row(
        "Rezolvă dispozitivele: Klar alege entitatea. Doar camere: se oprește la zonă.",
        "Pornit: yale, închiderea jaluzelelor și comenzi riscante mari sau pe toată camera întreabă mai întâi. Oprit: se execută imediat.",
        "Pornit: Klar păstrează ultimele 200 de tururi 24 de ore. Necesar pentru descărcările de mai jos.",
        "Pornit: descărcările includ propoziția rostită. Oprit: doar redactat.",
        "Oprit implicit. Pornit: după o rată, o potrivire locală de sens poate încă recupera intenția. Nu e un LLM.",
        "Necesar ca să salvezi de pe acest ecran. Aceeași valoare ca tokenul aplicației.",
        "Stare",
        "Răspunsuri precum starea unei camere sau a unui dispozitiv. Pornit: LLM-ul rescrie propoziția gata.",
        "Comenzi",
        "Confirmare după ce Klar a executat deja comanda. Pornit: «lumina e aprinsă» folosește această voce.",
        "Întrebări de urmărire",
        "Întrebări care-cameră și care-dispozitiv. Pornit: întrebarea lui Klar e rescrisă.",
        "Respingere",
        "Răspunsuri de tip nu-am-înțeles. Pornit: acele propoziții folosesc această voce.",
        "Răspunsurile LLM din chat și calendar rămân cum sunt — fără un al doilea rafinament.",
        "Salvat.",
        "Salvarea a eșuat.",
        "Nesalvat. Introdu tokenul de scriere la Engine.",
    ),
    "pt-BR": row(
        "Resolver dispositivos: o Klar escolhe a entidade. Só cômodos: para na área.",
        "Ligado: fechaduras, fechar persianas e comandos arriscados grandes ou do cômodo inteiro perguntam primeiro. Desligado: executam na hora.",
        "Ligado: o Klar guarda os últimos 200 turnos por 24 h. Precisa disso para os downloads abaixo.",
        "Ligado: os downloads incluem a frase falada. Desligado: só redigido.",
        "Desligado por padrão. Ligado: depois de um erro, uma correspondência de sentido local ainda pode recuperar a intenção. Não é um LLM.",
        "Necessário para salvar nesta tela. O mesmo valor do token do App.",
        "Estado",
        "Respostas como o estado de um cômodo ou dispositivo. Ligado: o LLM reescreve a frase pronta.",
        "Comandos",
        "Confirmação depois que o Klar já executou o comando. Ligado: «a luz está acesa» usa esta voz.",
        "Perguntas de acompanhamento",
        "Perguntas qual-cômodo e qual-dispositivo. Ligado: a pergunta do Klar é reescrita.",
        "Recusa",
        "Respostas do tipo não-entendi. Ligado: essas frases usam esta voz.",
        "As respostas LLM do chat e do calendário ficam como estão — sem um segundo refino.",
        "Salvo.",
        "Não foi possível salvar.",
        "Não salvo. Insira o token de escrita em Engine.",
    ),
    "gl": row(
        "Resolver dispositivos: Klar escolle a entidade. Só estancias: para na área.",
        "Activado: pechaduras, peche de persianas e ordes arriscadas grandes ou de toda a estancia preguntan primeiro. Desactivado: execútanse de seguida.",
        "Activado: Klar garda as últimas 200 quendas 24 horas. Fai falta para as descargas de abaixo.",
        "Activado: as descargas inclúen a frase dita. Desactivado: só redactado.",
        "Desactivado por defecto. Activado: tras un erro, unha coincidencia de sentido local aínda pode recuperar a intención. Non é un LLM.",
        "Fai falta para gardar nesta pantalla. O mesmo valor que o token da App.",
        "Estado",
        "Respostas como o estado dunha estancia ou dispositivo. Activado: o LLM reescribe a frase rematada.",
        "Ordes",
        "Confirmación despois de que Klar xa executou a orde. Activado: «a luz está acesa» usa esta voz.",
        "Preguntas de seguimento",
        "Preguntas que-estancia e que-dispositivo. Activado: a pregunta de Klar reescríbese.",
        "Rexeitamento",
        "Respostas do tipo non-entendín. Activado: esas frases usan esta voz.",
        "As respostas LLM do chat e do calendario quedan como están — sen un segundo refinamento.",
        "Gardado.",
        "Non se puido gardar.",
        "Non gardado. Introduce o token de escritura en Engine.",
    ),
    "de-CH": row(
        "Grät uflöse: Klar wählt s Entity. Nur Rüüm: es blibt bi de Area.",
        "Aa: Schlösser, zueladendi Rolllade und grossi oder rüumwiti riskanti Befähl fröge zersch eimal. Us: si laufe sofort.",
        "Aa: Klar bhaltet di letschte 200 Turns 24 Stunde. Bruucht s für d Downloads drunter.",
        "Aa: Downloads enthalted de gredt Satz. Us: nur gschwärzt.",
        "Standard us. Aa: nach eme Miss cha en lokale Bedütigsabglich de Intent no finde. Keis LLM.",
        "Zum Spychere uf däm Bildschirm. De gliich Wärt wie s App-Token.",
        "Status",
        "Antwort wie Ruum- oder Grätstatus. Aa: s LLM schriibt de fertig Satz um.",
        "Befähl",
        "Bestätigung, nachdem Klar de Befähl scho usgführt het. Aa: «Liecht isch aa» bechunnt die Stimm.",
        "Rückfrage",
        "Rückfrage zu Ruum oder Grät. Aa: Klars Frag wird umgschribe.",
        "Ablehnig",
        "Sätz wie «Das han i nöd verstande». Aa: au die bechömmed die Stimm.",
        "Chat und Kalender-LLM bliibed unagfasst — keis zwöits Refine.",
        "Gspycheret.",
        "Spychere fehlgschlage.",
        "Nöd gspycheret. Schriib-Token under Engine iitrage.",
    ),
    "de-AT": row(
        "Geräte auflösen: Klar wählt das Entity. Nur Räume: es bleibt bei der Area.",
        "An: Schlösser, schließende Rollläden und große oder raumweite riskante Befehle fragen zuerst einmal nach. Aus: sie laufen sofort.",
        "An: Klar behält die letzten 200 Turns 24 Stunden. Braucht es für die Downloads darunter.",
        "An: Downloads enthalten den gesprochenen Satz. Aus: nur geschwärzt.",
        "Standard aus. An: nach einem Miss kann ein lokaler Bedeutungsabgleich den Intent noch finden. Kein LLM.",
        "Zum Speichern auf diesem Bildschirm. Derselbe Wert wie das App-Token.",
        "Status",
        "Antworten wie Raum- oder Gerätestatus. An: das LLM schreibt den fertigen Satz um.",
        "Befehle",
        "Bestätigung, nachdem Klar den Befehl schon ausgeführt hat. An: „Licht ist an“ bekommt diese Stimme.",
        "Rückfragen",
        "Rückfragen zu Raum oder Gerät. An: Klars Frage wird umgeschrieben.",
        "Ablehnung",
        "Sätze wie „Das habe ich nicht verstanden“. An: auch die bekommen diese Stimme.",
        "Chat und Kalender-LLM bleiben unangetastet — kein zweites Refine.",
        "Gespeichert.",
        "Speichern fehlgeschlagen.",
        "Nicht gespeichert. Schreib-Token unter Engine eintragen.",
    ),
    "en-GB": row(
        "Resolve devices: Klar picks the entity. Rooms only: it stops at the area.",
        "On: locks, closing covers, and large or room-wide risky commands ask once first. Off: they run immediately.",
        "On: Klar keeps the last 200 turns for 24 hours. Needed for the downloads below.",
        "On: downloads include the spoken sentence. Off: redacted only.",
        "Off by default. On: after a miss, a local meaning match may still recover the intent. Not an LLM.",
        "Required to save from this screen. Same value as the App token.",
        "Status",
        "Answers like room or device status. On: the LLM rewrites the finished sentence.",
        "Commands",
        "Spoken acknowledgement after Klar already ran the command. On: “light is on” gets this voice.",
        "Follow-up questions",
        "Which-room and which-device questions. On: Klar’s question is rewritten.",
        "Rejection",
        "I-didn’t-understand replies. On: those sentences get this voice.",
        "Chat and calendar LLM replies stay as they are — no second refine.",
        "Saved.",
        "Could not save.",
        "Not saved. Enter the write token under Engine.",
    ),
    "af": row(
        "Toestelle oplos: Klar kies die entiteit. Net kamers: dit stop by die area.",
        "Aan: slotte, toemaak van rolluike en groot of kamervye riskante bevele vra eers een keer. Af: hulle loop dadelik.",
        "Aan: Klar hou die laaste 200 beurte 24 uur. Nodig vir die aflaaie hieronder.",
        "Aan: aflaaie sluit die gesproke sin in. Af: net geredigeer.",
        "Standaard af. Aan: ná ’n misser kan ’n plaaslike betekenispassing die intensie nog vind. Nie ’n LLM nie.",
        "Nodig om van hierdie skerm te stoor. Dieselfde waarde as die App-token.",
        "Status",
        "Antwoorde soos kamer- of toestelstatus. Aan: die LLM herskryf die voltooide sin.",
        "Bevele",
        "Bevestiging nadat Klar die bevel al uitgevoer het. Aan: «lig is aan» kry hierdie stem.",
        "Opvolgvrae",
        "Watter-kamer- en watter-toestelvrae. Aan: Klar se vraag word herskryf.",
        "Verwerping",
        "Antwoorde soos ek-het-nie-verstaan. Aan: daardie sinne kry hierdie stem.",
        "Klets- en kalender-LLM-antwoorde bly soos hulle is — geen tweede herskryf nie.",
        "Gestoor.",
        "Kon nie stoor nie.",
        "Nie gestoor nie. Vul die skryftoken onder Engine in.",
    ),
    "lb": row(
        "Apparater opléisen: Klar wielt d’Entity. Nëmme Raim: et bleift bei der Area.",
        "Un: Schlässer, zoumaachend Rolllied an grouss oder raumwäit riskant Befehler froen éischt eemol. Aus: si lafen direkt.",
        "Un: Klar behält déi lescht 200 Touren 24 Stonnen. Brauch een et fir d’Downloads drënner.",
        "Un: Downloads enthalen de geschwate Saz. Aus: nëmme geschwärzt.",
        "Standard aus. Un: no engem Miss kann e lokale Bedeitungsvergläich den Intent nach fannen. Kee LLM.",
        "Fir vun dësem Ecran ze späicheren. Deeselwechte Wäert wéi d’App-Token.",
        "Status",
        "Äntwerten wéi Raum- oder Apparatstatus. Un: den LLM schreift de fäerdege Saz ëm.",
        "Befehler",
        "Confirmatioun, nodeems Klar de Befeel scho ausgefouert huet. Un: «Luucht ass un» kritt dës Stëmm.",
        "Réckfroen",
        "Réckfroen iwwer Raum oder Apparat. Un: Klars Fro gëtt ëmgeschriwwen.",
        "Oflehnung",
        "Sätz wéi «Dat hunn ech net verstan». Un: och déi kréien dës Stëmm.",
        "Chat- an Kalenner-LLM bleiwen onberéiert — kee zweet Refine.",
        "Gespäichert.",
        "Späicheren feelgeschloen.",
        "Net gespäichert. Schreif-Token ënner Engine androen.",
    ),
    "cy": row(
        "Datrys dyfeisiau: mae Klar yn dewis yr endid. Ystafelloedd yn unig: mae’n stopio yn yr ardal.",
        "Ymlaen: cloion, cau llenni a gorchmynion peryglus mawr neu ar draws yr ystafell yn gofyn unwaith yn gyntaf. I ffwrdd: maen nhw’n rhedeg ar unwaith.",
        "Ymlaen: mae Klar yn cadw’r 200 tro diwethaf am 24 awr. Angenrheidiol ar gyfer y lawrlwythiadau isod.",
        "Ymlaen: mae lawrlwythiadau’n cynnwys y frawddeg a lefarwyd. I ffwrdd: wedi’i golygu’n unig.",
        "I ffwrdd yn ddiofyn. Ymlaen: ar ôl methiant, gall cyfatebiaeth ystyr leol adfer y bwriad o hyd. Nid LLM.",
        "Angenrheidiol i gadw o’r sgrin hon. Yr un gwerth â thocyn yr Ap.",
        "Statws",
        "Atebion fel statws ystafell neu ddyfais. Ymlaen: mae’r LLM yn ailysgrifennu’r frawddeg orffenedig.",
        "Gorchmynion",
        "Cydnabyddiaeth ar ôl i Klar redeg y gorchymyn eisoes. Ymlaen: «mae’r golau ymlaen» yn cael y llais hwn.",
        "Cwestiynau dilynol",
        "Cwestiynau pa-ystafell a pha-ddyfais. Ymlaen: mae cwestiwn Klar yn cael ei ailysgrifennu.",
        "Gwrthod",
        "Atebion fel wnes-i-ddim-deall. Ymlaen: mae’r brawddegau hynny’n cael y llais hwn.",
        "Mae atebion LLM sgwrs a chalendr yn aros fel y maent — dim ail fireinio.",
        "Wedi cadw.",
        "Methu cadw.",
        "Heb ei gadw. Rhowch y tocyn ysgrifennu o dan Engine.",
    ),
    "eu": row(
        "Gailuak ebatzi: Klarrek entitatea aukeratzen du. Gelak bakarrik: arean geratzen da.",
        "Aktibatuta: sarrailak, persiana ixtea eta agindu arriskutsu handiak edo gela osokoak lehenik galdetzen dute. Desaktibatuta: berehala exekutatzen dira.",
        "Aktibatuta: Klarrek azken 200 txandak 24 orduz gordetzen ditu. Beheko deskargetarako behar da.",
        "Aktibatuta: deskargek esandako esaldia dute. Desaktibatuta: soilik redactatuta.",
        "Desaktibatuta lehenetsita. Aktibatuta: huts baten ondoren, tokiko esanahi-bat-etortze batek asmoa berreskura dezake oraindik. Ez da LLM bat.",
        "Pantaila honetatik gordetzeko beharrezkoa. App-aren tokenaren balio bera.",
        "Egoera",
        "Gela edo gailuaren egoera bezalako erantzunak. Aktibatuta: LLMak amaitutako esaldia berridazten du.",
        "Aginduak",
        "Klarrek agindua dagoeneko exekutatu ondoren. Aktibatuta: «argia piztuta dago» ahots hau erabiltzen du.",
        "Jarraipen-galderak",
        "Zein-gela eta zein-gailu galderak. Aktibatuta: Klarren galdera berridazten da.",
        "Ukapena",
        "Ez-dut-ulertu motako erantzunak. Aktibatuta: esaldi horiek ahots hau erabiltzen dute.",
        "Txat eta egutegiko LLM erantzunak dauden bezala geratzen dira — bigarren findurik ez.",
        "Gordeta.",
        "Ezin izan da gorde.",
        "Ez da gorde. Idatzi idazketa-tokena Engine atalean.",
    ),
    "ga": row(
        "Réitigh gléasanna: roghnaíonn Klar an t-eintiteas. Seomraí amháin: stopann sé ag an limistéar.",
        "Ar siúl: glais, dúnadh dallóg agus orduithe contúirteacha móra nó ar fud an tseomra a fhiafraíonn ar dtús. As: ritheann siad láithreach.",
        "Ar siúl: coinníonn Klar an 200 casadh deireanach ar feadh 24 uair. Teastaíonn sé do na híoslódálacha thíos.",
        "Ar siúl: cuimsíonn íoslódálacha an abairt labhartha. As: deargtha amháin.",
        "As de réir réamhshocraithe. Ar siúl: tar éis teipe, féadfaidh comhoiriúnú brí áitiúil an rún a fháil fós. Ní LLM é.",
        "Ag teastáil chun sábháil ón scáileán seo. An luach céanna le comhartha an Aip.",
        "Stádas",
        "Freagraí mar stádas seomra nó gléis. Ar siúl: athscríobhann an LLM an abairt chríochnaithe.",
        "Orduithe",
        "Admháil tar éis do Klar an t-ordú a rith cheana. Ar siúl: faigheann «tá an solas ar siúl» an guth seo.",
        "Ceisteanna leantacha",
        "Ceisteanna cén-seomra agus cén-ghléas. Ar siúl: athscríobhtar ceist Klar.",
        "Diúltú",
        "Freagraí mar níor-thuig-mé. Ar siúl: faigheann na habairtí sin an guth seo.",
        "Fanann freagraí LLM comhrá agus féilire mar atá siad — gan an dara mionchoigeartú.",
        "Sábháilte.",
        "Níorbh fhéidir sábháil.",
        "Níor sábháladh. Cuir an comhartha scríofa isteach faoi Engine.",
    ),
    "kw": row(
        "Diskwedh devisys: Klar a dhewis an entite. Sommennow hepken: ev a hedh y’n ranndir.",
        "War: alhwedhow, degea gwiskow ha gorhemmynnow peryllus bras po dre’n sommen a wovyn kynsa. Dheges: i a fir a-dhesempis.",
        "War: Klar a with an 200 tro dewetha rag 24 our. Res yw rag an iskargansow a-woles.",
        "War: iskargansow a syns an lavar kewsys. Dheges: redaktys hepken.",
        "Dheges dre dhefowt. War: wosa fowt, parth styr leel a yll hwath kavoes an intent. Nyns yw LLM.",
        "Res yw rag gwitha dhyworth an screen ma. An keth gwerth ha token an App.",
        "Studh",
        "Gorthypow kepar studh sommen po devis. War: an LLM a skrif arta an lavar gorfennys.",
        "Gorhemmynnow",
        "Afydhyans wosa Klar dhe wruthyl an gorhemmynn seulabrys. War: «golow yw war» a gev an lev ma.",
        "Govynnow sywya",
        "Govynnow py-sommen ha py-dhevis. War: govyn Klar yw skrifs arta.",
        "Nagha",
        "Gorthypow kepar ny-wrug-vy-konvedhes. War: an lavarow na a gev an lev ma.",
        "Gorthypow LLM chats ha de syntel a wort kepar dell yns — heb eyl finhe.",
        "Gwithys.",
        "Ny ylli gwitha.",
        "Ny veu gwithys. Gorr an token skrifa yn-dann Engine.",
    ),
}
