"""Settings / LLM / trainer chrome for RTL, Indic, and other script Assist locales."""

from __future__ import annotations

PACKS: dict[str, dict[str, str]] = {
    "ar": {
        "engineHint": "الصوت واللغات وLLM هنا. Home Assistant يصل المحرك فقط.",
        "languageHint": "القائمة الفارغة تُبقي كل محلية Assist المجمّعة. تثبيت حزمة واحدة هو المنزل المعتاد.",
        "personalityHa": "الصوت واللغات وLLM على صفحة Settings هذه.",
        "assistLanguages": "لغات Assist",
        "assistLanguagesHint": "أي الحزم يجوز لـ Klar تحليلها. القمر الصناعي ما زال يرسل لغة واحدة لكل طلب. فارغ = كل المحليات المجمّعة.",
        "allAssistLanguages": "كل محلية مجمّعة",
        "pinLanguage": "ثبّت حزمة واحدة",
        "voice": "الصوت",
        "voiceHint": "الشخصية والردود المنطوقة. Assist يقرأها من المحرك لا من خيارات Home Assistant.",
        "extraPrompt": "موجه إضافي",
        "extraPromptHint": "سطر اختياري فوق شخصية الحزمة. اتركه فارغًا ما لم تحتج قاعدة خاصة بالمنزل.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "صقل LLM",
        "refineSpeechHint": "Klar ما زال يتحكم بالأجهزة. ثم يعيد LLM المحرك كتابة ردود NLU الجاهزة بهذا الصوت.",
        "quietAck": "تأكيد قصير",
        "quietAckHint": "عند ضوء أو مفتاح بسيط تشغيل/إيقاف، تجاوز TTS وشغّل رنينًا على القمر الصناعي.",
        "calendarLlm": "التقويم عبر LLM",
        "calendarLlmHint": "Klar ما زال يقرأ التقويم. تشغيل: LLM ينطق الأحداث. إيقاف: Klar ينطق القائمة.",
        "allowLlmTools": "السماح بأدوات Assist في الدردشة",
        "allowLlmToolsHint": "إيقاف افتراضيًا. تشغيل: نموذج الدردشة قد يتحكم بـ Home Assistant. إيقاف: Klar يتخطى ذلك الوكيل إن كانت لديه أدوات.",
        "missTitle": "عندما يخطئ Klar",
        "missHint": "طبقات اختيارية بعد رفض حتمي. لا واحدة تضع نموذجًا على التحليل.",
        "operatorChrome": "هذه الشاشة",
        "operatorChromeHint": "السمة ولغة الواجهة للمشغّلين. ليست Assist.",
        "haGlueHint": "Home Assistant Configure يحتاج فقط عنوان المحرك والرمز والقناة ووكيل محادثة متبقٍ اختياري. الصوت وLLM يبقيان هنا.",
        "settingsGuide": "اضبط هذه الثلاثة ثم اربط المنزل.",
        "settingsGuideVoice": "الصوت",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "لغة Assist",
        "appearanceDark": "داكن",
        "appearanceLight": "فاتح",
        "setupReplay": "إعادة تشغيل الإعداد",
        "personalityDefault": "عادي",
        "personalityButler": "Butler",
        "personalityLocker": "عفوي",
        "personalityFuersorglich": "حنون",
        "personalityParty": "حفلة",
        "personalityGrantig": "متذمر",
        "personalitySarkastisch": "ساخر",
        "personalityPirat": "قرصان",
        "personalityHippie": "هيبي",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "لغة المشغّل",
        "operatorLanguageHint": "هذا التطبيق فقط. محفوظ هنا، أو KLAR_UI_LOCALE قبل أول حفظ. ليست Assist وليست ملف Home Assistant.",
        "nluRag": "سياق المنزل عند الخطأ",
        "modeFull": "حل الأجهزة",
        "modeContext": "الغرف فقط",
        "inLab": "في المختبر",
        "undoLastCommand": "تراجع عن آخر أمر",
        "applyDone": "طُبّقت {count} اقتراحات غرف",
        "applyUndone": "أُلغيت اقتراحات الغرف",
        "applyUndoFailed": "تعذّر التراجع عن اقتراحات الغرف",
        "llm": "LLM",
        "llmHint": "Klar يتحدث إلى نقطة نهاية متوافقة مع OpenAI. دردشة Assist والمدرب يستخدمان الإعداد نفسه. لا حاجة لتكامل OpenAI أو Ollama في Home Assistant.",
        "llmBaseUrl": "عنوان الأساس",
        "llmModel": "النموذج",
        "llmApiKey": "مفتاح API",
        "llmApiKeyHint": "اتركه فارغًا للاحتفاظ بالمفتاح المخزَّن. يمكن أن يبقى Ollama فارغًا.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "مضبوط",
        "llmNotConfigured": "غير مضبوط",
        "llmClear": "مسح",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "المدرب",
        "trainerForLane": "مدرب لهذا المسار",
        "trainerHint": "Klar يستدعي نموذجًا متوافقًا مع OpenAI في Rust. دردش ثم تحقق ثم طبّق لكل مسار. لا حاجة لتكامل LLM في Home Assistant. JSON المتقدم للتصحيح.",
        "trainerContext": "السياق",
        "trainerValidate": "تحقق",
        "trainerApply": "تطبيق",
        "trainerProposal": "JSON المقترح",
        "trainerOk": "صالح",
        "trainerFail": "غير صالح",
        "trainerSend": "إرسال",
        "trainerNeedLlm": "اضبط LLM في Settings أولًا. Klar لا يحتاج تكامل محادثة آخر من Home Assistant.",
        "trainerOpenSettings": "فتح Settings",
        "trainerApplyHouse": "تطبيق House",
        "trainerApplyMatch": "تطبيق Match",
        "trainerApplyLanguage": "تطبيق Language",
        "trainerAdvanced": "JSON متقدم",
        "trainerStreaming": "بث…",
    },
    "he": {
        "engineHint": "קול, שפות וה־LLM נמצאים כאן. Home Assistant רק מחבר את המנוע.",
        "languageHint": "רשימה ריקה משאירה כל locale של Assist המהודר. נעיצת חבילה אחת היא הבית הרגיל.",
        "personalityHa": "קול, שפות וה־LLM נמצאים בדף Settings הזה.",
        "assistLanguages": "שפות Assist",
        "assistLanguagesHint": "אילו חבילות Klar רשאי לנתח. הלוויין עדיין שולח שפה אחת לכל בקשה. ריק = כל ה־locale המהודרים.",
        "allAssistLanguages": "כל locale מהודר",
        "pinLanguage": "נעץ חבילה אחת",
        "voice": "קול",
        "voiceHint": "אישיות ותשובות מדוברות. Assist קורא זאת מהמנוע, לא מאפשרויות Home Assistant.",
        "extraPrompt": "הנחיה נוספת",
        "extraPromptHint": "שורה אופציונלית מעל אישיות החבילה. השאירו ריק אלא אם הבית צריך כלל משלו.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "ליטוש LLM",
        "refineSpeechHint": "Klar עדיין שולט במכשירים. ה־LLM של המנוע אחר כך כותב מחדש תשובות NLU מוכנות בקול הזה.",
        "quietAck": "אישור קצר",
        "quietAckHint": "באור או מתג פשוט הדלקה/כיבוי דלגו על TTS ונגנו פעמון בלוויין.",
        "calendarLlm": "יומן דרך ה־LLM",
        "calendarLlmHint": "Klar עדיין קורא את היומן. פועל: ה־LLM אומר את האירועים. כבוי: Klar אומר את הרשימה.",
        "allowLlmTools": "אפשר כלי Assist בצ׳אט",
        "allowLlmToolsHint": "כבוי כברירת מחדל. פועל: מודל הצ׳אט רשאי לשלוט ב־Home Assistant. כבוי: Klar מדלג על הסוכן אם יש לו כלים.",
        "missTitle": "כש־Klar מחטיא",
        "missHint": "שכבות אופציונליות אחרי דחייה דטרמיניסטית. אף אחת לא שמה מודל על הניתוח.",
        "operatorChrome": "המסך הזה",
        "operatorChromeHint": "ערכת נושא ושפת ממשק למפעילים. לא Assist.",
        "haGlueHint": "Home Assistant Configure צריך רק כתובת מנוע, אסימון, ערוץ וסוכן שיחה שאריות אופציונלי. קול ו־LLM נשארים כאן.",
        "settingsGuide": "הגדירו את שלושת אלה ואז ממפו את הבית.",
        "settingsGuideVoice": "קול",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "שפת Assist",
        "appearanceDark": "כהה",
        "appearanceLight": "בהיר",
        "setupReplay": "הפעלת ההתקנה מחדש",
        "personalityDefault": "רגיל",
        "personalityButler": "Butler",
        "personalityLocker": "נינוח",
        "personalityFuersorglich": "דואג",
        "personalityParty": "מסיבה",
        "personalityGrantig": "עצבני",
        "personalitySarkastisch": "סרקסטי",
        "personalityPirat": "פיראט",
        "personalityHippie": "היפי",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "שפת מפעיל",
        "operatorLanguageHint": "האפליקציה הזו בלבד. נשמר כאן, או KLAR_UI_LOCALE לפני השמירה הראשונה. לא Assist, לא פרופיל Home Assistant.",
        "nluRag": "הקשר הבית בהחטאה",
        "modeFull": "פתרו מכשירים",
        "modeContext": "חדרים בלבד",
        "inLab": "במעבדה",
        "undoLastCommand": "בטל את הפקודה האחרונה",
        "applyDone": "הוחלו {count} הצעות חדרים",
        "applyUndone": "הצעות החדרים בוטלו",
        "applyUndoFailed": "לא ניתן לבטל הצעות חדרים",
        "llm": "LLM",
        "llmHint": "Klar מדבר עם נקודת קצה תואמת OpenAI. צ׳אט Assist והמאמן משתמשים באותה config. אין צורך באינטגרציית OpenAI או Ollama ב־Home Assistant.",
        "llmBaseUrl": "כתובת בסיס",
        "llmModel": "מודל",
        "llmApiKey": "מפתח API",
        "llmApiKeyHint": "השאירו ריק כדי לשמור את המפתח המאוחסן. Ollama יכול להישאר ריק.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "מוגדר",
        "llmNotConfigured": "לא מוגדר",
        "llmClear": "נקה",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "מאמן",
        "trainerForLane": "מאמן למסלול הזה",
        "trainerHint": "Klar קורא למודל תואם OpenAI ב־Rust. צ׳אט, אימות, ואז החלה לפי מסלול. אין צורך באינטגרציית LLM של Home Assistant. JSON מתקדם לדיבאג.",
        "trainerContext": "הקשר",
        "trainerValidate": "אמת",
        "trainerApply": "החל",
        "trainerProposal": "JSON הצעה",
        "trainerOk": "תקין",
        "trainerFail": "לא תקין",
        "trainerSend": "שלח",
        "trainerNeedLlm": "הגדירו קודם LLM ב־Settings. Klar לא צריך אינטגרציית שיחה אחרת של Home Assistant.",
        "trainerOpenSettings": "פתח Settings",
        "trainerApplyHouse": "החל House",
        "trainerApplyMatch": "החל Match",
        "trainerApplyLanguage": "החל Language",
        "trainerAdvanced": "JSON מתקדם",
        "trainerStreaming": "סטרימינג…",
    },
    "fa": {
        "engineHint": "صدا، زبان‌ها و LLM این‌جا هستند. Home Assistant فقط موتور را وصل می‌کند.",
        "languageHint": "فهرست خالی هر locale کامپایل‌شدهٔ Assist را فعال نگه می‌دارد. سنجاق‌کردن یک بسته خانهٔ معمول است.",
        "personalityHa": "صدا، زبان‌ها و LLM در این صفحهٔ Settings هستند.",
        "assistLanguages": "زبان‌های Assist",
        "assistLanguagesHint": "Klar کدام بسته‌ها را می‌تواند تجزیه کند. ماهواره همچنان یک زبان در هر درخواست می‌فرستد. خالی = همهٔ localeهای کامپایل‌شده.",
        "allAssistLanguages": "هر locale کامپایل‌شده",
        "pinLanguage": "سنجاق یک بسته",
        "voice": "صدا",
        "voiceHint": "شخصیت و پاسخ‌های گفتاری. Assist این را از موتور می‌خواند، نه از گزینه‌های Home Assistant.",
        "extraPrompt": "پرامپت اضافه",
        "extraPromptHint": "خط اختیاری روی شخصیت بسته. خالی بگذارید مگر خانه به قاعدهٔ خودش نیاز دارد.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "پرداخت LLM",
        "refineSpeechHint": "Klar همچنان دستگاه‌ها را کنترل می‌کند. سپس LLM موتور پاسخ‌های NLU تمام‌شده را با این صدا بازنویسی می‌کند.",
        "quietAck": "تأیید کوتاه",
        "quietAckHint": "روی چراغ یا کلید ساده روشن/خاموش، TTS را رد کنید و زنگ را روی ماهواره پخش کنید.",
        "calendarLlm": "تقویم از راه LLM",
        "calendarLlmHint": "Klar همچنان تقویم را می‌خواند. روشن: LLM رویدادها را می‌گوید. خاموش: Klar فهرست را می‌گوید.",
        "allowLlmTools": "اجازهٔ ابزار Assist در گفتگو",
        "allowLlmToolsHint": "پیش‌فرض خاموش. روشن: مدل گفتگو می‌تواند Home Assistant را کنترل کند. خاموش: Klar آن عامل را اگر ابزار داشته باشد رد می‌کند.",
        "missTitle": "وقتی Klar خطا می‌کند",
        "missHint": "لایه‌های اختیاری پس از رد قطعی. هیچ‌کدام مدل را روی تجزیه نمی‌گذارد.",
        "operatorChrome": "این صفحه",
        "operatorChromeHint": "پوسته و زبان رابط برای اپراتورها. Assist نیست.",
        "haGlueHint": "Home Assistant Configure فقط به نشانی موتور، رمز، کانال و عامل گفتگوی باقی‌ماندهٔ اختیاری نیاز دارد. صدا و LLM این‌جا می‌مانند.",
        "settingsGuide": "این سه را تنظیم کنید، بعد خانه را نقشه‌گذاری کنید.",
        "settingsGuideVoice": "صدا",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "زبان Assist",
        "appearanceDark": "تیره",
        "appearanceLight": "روشن",
        "setupReplay": "بازپخش setup",
        "personalityDefault": "معمولی",
        "personalityButler": "Butler",
        "personalityLocker": "راحت",
        "personalityFuersorglich": "مراقب",
        "personalityParty": "جشن",
        "personalityGrantig": "بدخلق",
        "personalitySarkastisch": "طعنه‌آمیز",
        "personalityPirat": "دزد دریایی",
        "personalityHippie": "هیپی",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "زبان اپراتور",
        "operatorLanguageHint": "فقط این برنامه. این‌جا ذخیره می‌شود، یا KLAR_UI_LOCALE پیش از نخستین ذخیره. Assist نیست، نمایهٔ Home Assistant هم نیست.",
        "nluRag": "بافت خانه هنگام خطا",
        "modeFull": "حل دستگاه‌ها",
        "modeContext": "فقط اتاق‌ها",
        "inLab": "در آزمایشگاه",
        "undoLastCommand": "واگرد آخرین فرمان",
        "applyDone": "{count} پیشنهاد اتاق اعمال شد",
        "applyUndone": "پیشنهادهای اتاق واگرد شد",
        "applyUndoFailed": "پیشنهادهای اتاق واگرد نشد",
        "llm": "LLM",
        "llmHint": "Klar با نقطهٔ پایانی سازگار با OpenAI حرف می‌زند. گفتگوی Assist و مربی همین config را به کار می‌برند. یکپارچگی OpenAI یا Ollama در Home Assistant لازم نیست.",
        "llmBaseUrl": "نشانی پایه",
        "llmModel": "مدل",
        "llmApiKey": "کلید API",
        "llmApiKeyHint": "خالی بگذارید تا کلید ذخیره‌شده بماند. Ollama می‌تواند خالی بماند.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "پیکربندی‌شده",
        "llmNotConfigured": "پیکربندی نشده",
        "llmClear": "پاک کردن",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "مربی",
        "trainerForLane": "مربی برای این مسیر",
        "trainerHint": "Klar مدلی سازگار با OpenAI را در Rust صدا می‌زند. گفتگو، اعتبارسنجی، سپس اعمال در هر مسیر. یکپارچگی LLM در Home Assistant لازم نیست. JSON پیشرفته برای اشکال‌زدایی است.",
        "trainerContext": "بافت",
        "trainerValidate": "اعتبارسنجی",
        "trainerApply": "اعمال",
        "trainerProposal": "JSON پیشنهاد",
        "trainerOk": "معتبر",
        "trainerFail": "نامعتبر",
        "trainerSend": "ارسال",
        "trainerNeedLlm": "اول در Settings یک LLM پیکربندی کنید. Klar به یکپارچگی گفتگوی دیگری از Home Assistant نیاز ندارد.",
        "trainerOpenSettings": "باز کردن Settings",
        "trainerApplyHouse": "اعمال House",
        "trainerApplyMatch": "اعمال Match",
        "trainerApplyLanguage": "اعمال Language",
        "trainerAdvanced": "JSON پیشرفته",
        "trainerStreaming": "جریان…",
    },
    "ur": {
        "engineHint": "آواز، زبانیں اور LLM یہاں ہیں۔ Home Assistant صرف انجن جوڑتا ہے۔",
        "languageHint": "خالی فہرست ہر مرتب Assist locale کو فعال رکھتی ہے۔ ایک پیک پن کرنا عام گھر ہے۔",
        "personalityHa": "آواز، زبانیں اور LLM اس Settings صفحے پر ہیں۔",
        "assistLanguages": "Assist زبانیں",
        "assistLanguagesHint": "Klar کن پیک کو پارس کر سکتا ہے۔ سیٹلائٹ پھر بھی ہر درخواست پر ایک زبان بھیجتا ہے۔ خالی = تمام مرتب locale۔",
        "allAssistLanguages": "ہر مرتب locale",
        "pinLanguage": "ایک پیک پن کریں",
        "voice": "آواز",
        "voiceHint": "شخصیت اور بولی گئی جوابات۔ Assist یہ انجن سے پڑھتا ہے، Home Assistant اختیارات سے نہیں۔",
        "extraPrompt": "اضافی پرامپٹ",
        "extraPromptHint": "پیک کی شخصیت کے اوپر اختیاری سطر۔ خالی چھوڑیں جب تک گھر کو اپنا قاعدہ نہ چاہیے۔",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM صفائی",
        "refineSpeechHint": "Klar آلات کو کنٹرول کرتا رہتا ہے۔ پھر انجن کا LLM تیار NLU جوابات اس آواز میں دوبارہ لکھتا ہے۔",
        "quietAck": "مختصر تصدیق",
        "quietAckHint": "سادہ بتی یا سوئچ آن/آف پر TTS چھوڑیں اور سیٹلائٹ پر گھنٹی چلائیں۔",
        "calendarLlm": "کیلنڈر LLM کے ذریعے",
        "calendarLlmHint": "Klar کیلنڈر پڑھتا رہتا ہے۔ آن: LLM واقعات بولتا ہے۔ آف: Klar فہرست بولتا ہے۔",
        "allowLlmTools": "چیٹ پر Assist اوزار اجازت دیں",
        "allowLlmToolsHint": "طے شدہ آف۔ آن: چیٹ ماڈل Home Assistant کنٹرول کر سکتا ہے۔ آف: اگر اوزار ہوں تو Klar اس ایجنٹ کو چھوڑ دیتا ہے۔",
        "missTitle": "جب Klar چوک جائے",
        "missHint": "قطعی انکار کے بعد اختیاری تہیں۔ کوئی ماڈل parse پر نہیں رکھتی۔",
        "operatorChrome": "یہ اسکرین",
        "operatorChromeHint": "آپریٹرز کے لیے تھیم اور انٹرفیس کی زبان۔ Assist نہیں۔",
        "haGlueHint": "Home Assistant Configure کو صرف انجن URL، ٹوکن، چینل اور اختیاری بچا ہوا گفتگو ایجنٹ چاہیے۔ آواز اور LLM یہاں رہتے ہیں۔",
        "settingsGuide": "یہ تین سیٹ کریں، پھر گھر نقشہ بنائیں۔",
        "settingsGuideVoice": "آواز",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist زبان",
        "appearanceDark": "گہرا",
        "appearanceLight": "ہلکا",
        "setupReplay": "setup دوبارہ چلائیں",
        "personalityDefault": "عام",
        "personalityButler": "Butler",
        "personalityLocker": "آسان",
        "personalityFuersorglich": "خیال رکھنے والا",
        "personalityParty": "پارٹی",
        "personalityGrantig": "چڑچڑا",
        "personalitySarkastisch": "طنزیہ",
        "personalityPirat": "قزاق",
        "personalityHippie": "ہپی",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "آپریٹر کی زبان",
        "operatorLanguageHint": "صرف یہ ایپ۔ یہاں محفوظ، یا پہلی محفوظ سے پہلے KLAR_UI_LOCALE۔ Assist نہیں، Home Assistant پروفائل نہیں۔",
        "nluRag": "چوک پر گھر کا سیاق",
        "modeFull": "آلات حل کریں",
        "modeContext": "صرف کمرے",
        "inLab": "لیب میں",
        "undoLastCommand": "آخری حکم کالعدم",
        "applyDone": "{count} کمرے کی تجاویز لگائیں",
        "applyUndone": "کمرے کی تجاویز کالعدم",
        "applyUndoFailed": "کمرے کی تجاویز کالعدم نہ ہو سکیں",
        "llm": "LLM",
        "llmHint": "Klar OpenAI سے ہم آہنگ اختتام سے بات کرتا ہے۔ Assist چیٹ اور ٹرینر یہی config استعمال کرتے ہیں۔ Home Assistant میں OpenAI یا Ollama انضمام کی ضرورت نہیں۔",
        "llmBaseUrl": "بنیادی URL",
        "llmModel": "ماڈل",
        "llmApiKey": "API کلید",
        "llmApiKeyHint": "محفوظ کلید رکھنے کے لیے خالی چھوڑیں۔ Ollama خالی رہ سکتا ہے۔",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ترتیب شدہ",
        "llmNotConfigured": "ترتیب نہیں",
        "llmClear": "صاف",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "ٹرینر",
        "trainerForLane": "اس لین کا ٹرینر",
        "trainerHint": "Klar Rust میں OpenAI ہم آہنگ ماڈل بلاتا ہے۔ چیٹ، تصدیق، پھر لین کے مطابق لگائیں۔ Home Assistant LLM انضمام کی ضرورت نہیں۔ اعلیٰ JSON ڈیبگ کے لیے ہے۔",
        "trainerContext": "سیاق",
        "trainerValidate": "تصدیق",
        "trainerApply": "لگائیں",
        "trainerProposal": "تجویز JSON",
        "trainerOk": "درست",
        "trainerFail": "غلط",
        "trainerSend": "بھیجیں",
        "trainerNeedLlm": "پہلے Settings میں LLM ترتیب دیں۔ Klar کو دوسرا Home Assistant گفتگو انضمام نہیں چاہیے۔",
        "trainerOpenSettings": "Settings کھولیں",
        "trainerApplyHouse": "House لگائیں",
        "trainerApplyMatch": "Match لگائیں",
        "trainerApplyLanguage": "Language لگائیں",
        "trainerAdvanced": "اعلیٰ JSON",
        "trainerStreaming": "سلسلہ…",
    },
    "tr": {
        "engineHint": "Ses, diller ve LLM burada. Home Assistant yalnızca motoru bağlar.",
        "languageHint": "Boş liste her derlenmiş Assist locale’ini açık tutar. Bir paketi sabitlemek olağan evdir.",
        "personalityHa": "Ses, diller ve LLM bu Settings sayfasında.",
        "assistLanguages": "Assist dilleri",
        "assistLanguagesHint": "Klar’ın ayrıştırabileceği paketler. Uydu yine her istekte bir dil gönderir. Boş = tüm derlenmiş locale’ler.",
        "allAssistLanguages": "Her derlenmiş locale",
        "pinLanguage": "Bir paketi sabitle",
        "voice": "Ses",
        "voiceHint": "Kişilik ve konuşulan yanıtlar. Assist bunu motordan okur, Home Assistant seçeneklerinden değil.",
        "extraPrompt": "Ek prompt",
        "extraPromptHint": "Paket kişiliğinin üstünde isteğe bağlı satır. Ev kendi kuralını istemiyorsa boş bırak.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM cilası",
        "refineSpeechHint": "Klar hâlâ cihazları kontrol eder. Motor LLM’i bitmiş NLU yanıtlarını bu sesle yeniden yazar.",
        "quietAck": "Kısa onay",
        "quietAckHint": "Basit bir ışık veya anahtar aç/kapa’da TTS’i atla ve uyduda bir zil çal.",
        "calendarLlm": "Takvim LLM üzerinden",
        "calendarLlmHint": "Klar takvimi okumaya devam eder. Açık: LLM olayları söyler. Kapalı: Klar listeyi söyler.",
        "allowLlmTools": "Sohbette Assist araçlarına izin ver",
        "allowLlmToolsHint": "Varsayılan kapalı. Açık: sohbet modeli Home Assistant’ı kontrol edebilir. Kapalı: Klar, aracı araçlıysa atlar.",
        "missTitle": "Klar kaçırınca",
        "missHint": "Belirlenimci reddin ardından isteğe bağlı katmanlar. Hiçbiri parse’a model koymaz.",
        "operatorChrome": "Bu ekran",
        "operatorChromeHint": "Operatörler için tema ve arayüz dili. Assist değil.",
        "haGlueHint": "Home Assistant Configure yalnızca motor URL’si, jeton, kanal ve isteğe bağlı artakalan konuşma aracısı ister. Ses ve LLM burada kalır.",
        "settingsGuide": "Bu üçü ayarla, sonra evi eşle.",
        "settingsGuideVoice": "Ses",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist dili",
        "appearanceDark": "Koyu",
        "appearanceLight": "Açık",
        "setupReplay": "Kurulumu yeniden oynat",
        "personalityDefault": "Normal",
        "personalityButler": "Butler",
        "personalityLocker": "Rahat",
        "personalityFuersorglich": "Şefkatli",
        "personalityParty": "Parti",
        "personalityGrantig": "Huysuz",
        "personalitySarkastisch": "Alaycı",
        "personalityPirat": "Korsan",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Operatör dili",
        "operatorLanguageHint": "Yalnızca bu uygulama. Burada kaydedilir veya ilk kayıttan önce KLAR_UI_LOCALE. Assist değil, Home Assistant profili değil.",
        "nluRag": "Kaçırmada ev bağlamı",
        "modeFull": "Cihazları çöz",
        "modeContext": "Yalnızca odalar",
        "inLab": "Labda",
        "undoLastCommand": "Son komutu geri al",
        "applyDone": "{count} oda önerisi uygulandı",
        "applyUndone": "Oda önerileri geri alındı",
        "applyUndoFailed": "Oda önerileri geri alınamadı",
        "llm": "LLM",
        "llmHint": "Klar OpenAI uyumlu bir uç noktayla konuşur. Assist sohbeti ve eğitici aynı config’i kullanır. Home Assistant’ta OpenAI veya Ollama entegrasyonu gerekmez.",
        "llmBaseUrl": "Taban URL",
        "llmModel": "Model",
        "llmApiKey": "API anahtarı",
        "llmApiKeyHint": "Saklanan anahtarı tutmak için boş bırak. Ollama boş kalabilir.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Yapılandırıldı",
        "llmNotConfigured": "Yapılandırılmadı",
        "llmClear": "Temizle",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Eğitici",
        "trainerForLane": "Bu şerit için eğitici",
        "trainerHint": "Klar Rust’ta OpenAI uyumlu bir modeli çağırır. Sohbet et, doğrula, sonra şerit başına uygula. Home Assistant LLM entegrasyonu gerekmez. Gelişmiş JSON hata ayıklama içindir.",
        "trainerContext": "Bağlam",
        "trainerValidate": "Doğrula",
        "trainerApply": "Uygula",
        "trainerProposal": "Öneri JSON",
        "trainerOk": "Geçerli",
        "trainerFail": "Geçersiz",
        "trainerSend": "Gönder",
        "trainerNeedLlm": "Önce Settings’te bir LLM yapılandır. Klar başka bir Home Assistant konuşma entegrasyonu istemez.",
        "trainerOpenSettings": "Settings’i aç",
        "trainerApplyHouse": "House uygula",
        "trainerApplyMatch": "Match uygula",
        "trainerApplyLanguage": "Language uygula",
        "trainerAdvanced": "Gelişmiş JSON",
        "trainerStreaming": "Akış…",
    },
    "el": {
        "engineHint": "Η φωνή, οι γλώσσες και το LLM είναι εδώ. Το Home Assistant συνδέει μόνο τη μηχανή.",
        "languageHint": "Κενή λίστα κρατά κάθε μεταγλωττισμένη Assist locale ενεργή. Καρφίτσωμα ενός πακέτου είναι το συνηθισμένο σπίτι.",
        "personalityHa": "Η φωνή, οι γλώσσες και το LLM είναι σε αυτή τη σελίδα Settings.",
        "assistLanguages": "Γλώσσες Assist",
        "assistLanguagesHint": "Ποια πακέτα επιτρέπεται να αναλύει το Klar. Ο δορυφόρος στέλνει ακόμα μία γλώσσα ανά αίτημα. Κενό = όλες οι μεταγλωττισμένες locale.",
        "allAssistLanguages": "Κάθε μεταγλωττισμένη locale",
        "pinLanguage": "Καρφίτσωσε ένα πακέτο",
        "voice": "Φωνή",
        "voiceHint": "Προσωπικότητα και προφορικές απαντήσεις. Το Assist τις διαβάζει από τη μηχανή, όχι από επιλογές Home Assistant.",
        "extraPrompt": "Επιπλέον προτροπή",
        "extraPromptHint": "Προαιρετική γραμμή πάνω από την προσωπικότητα του πακέτου. Άφησέ την κενή αν το σπίτι δεν χρειάζεται δικό του κανόνα.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "Λείανση LLM",
        "refineSpeechHint": "Το Klar συνεχίζει να ελέγχει συσκευές. Το LLM της μηχανής ξαναγράφει έπειτα τις έτοιμες απαντήσεις NLU με αυτή τη φωνή.",
        "quietAck": "Σύντομη επιβεβαίωση",
        "quietAckHint": "Σε απλό φως ή διακόπτη on/off παράλειψε TTS και παίξε κουδούνι στον δορυφόρο.",
        "calendarLlm": "Ημερολόγιο μέσω LLM",
        "calendarLlmHint": "Το Klar συνεχίζει να διαβάζει το ημερολόγιο. On: το LLM λέει τα γεγονότα. Off: το Klar λέει τη λίστα.",
        "allowLlmTools": "Επίτρεψε εργαλεία Assist στη συνομιλία",
        "allowLlmToolsHint": "Off από προεπιλογή. On: το μοντέλο συνομιλίας μπορεί να ελέγχει το Home Assistant. Off: το Klar προσπερνά εκείνον τον πράκτορα αν έχει εργαλεία.",
        "missTitle": "Όταν το Klar αστοχεί",
        "missHint": "Προαιρετικά στρώματα μετά από ντετερμινιστική απόρριψη. Κανένα δεν βάζει μοντέλο στο parse.",
        "operatorChrome": "Αυτή η οθόνη",
        "operatorChromeHint": "Θέμα και γλώσσα διεπαφής για χειριστές. Όχι Assist.",
        "haGlueHint": "Το Home Assistant Configure χρειάζεται μόνο URL μηχανής, διακριτικό, κανάλι και προαιρετικό εναπομείναντα πράκτορα συνομιλίας. Φωνή και LLM μένουν εδώ.",
        "settingsGuide": "Όρισε αυτά τα τρία, μετά χαρτογράφησε το σπίτι.",
        "settingsGuideVoice": "Φωνή",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Γλώσσα Assist",
        "appearanceDark": "Σκοτεινό",
        "appearanceLight": "Φωτεινό",
        "setupReplay": "Επανάληψη setup",
        "personalityDefault": "Κανονικό",
        "personalityButler": "Butler",
        "personalityLocker": "Χαλαρό",
        "personalityFuersorglich": "Φροντιστικό",
        "personalityParty": "Πάρτι",
        "personalityGrantig": "Γκρινιάρικο",
        "personalitySarkastisch": "Σαρκαστικό",
        "personalityPirat": "Πειρατής",
        "personalityHippie": "Χίπις",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Γλώσσα χειριστή",
        "operatorLanguageHint": "Μόνο αυτή η εφαρμογή. Αποθηκεύεται εδώ ή KLAR_UI_LOCALE πριν την πρώτη αποθήκευση. Όχι Assist, όχι το προφίλ Home Assistant.",
        "nluRag": "Πλαίσιο σπιτιού σε αστοχία",
        "modeFull": "Επίλυση συσκευών",
        "modeContext": "Μόνο δωμάτια",
        "inLab": "Στο εργαστήριο",
        "undoLastCommand": "Αναίρεση τελευταίας εντολής",
        "applyDone": "Εφαρμόστηκαν {count} προτάσεις δωματίων",
        "applyUndone": "Οι προτάσεις δωματίων αναιρέθηκαν",
        "applyUndoFailed": "Δεν ήταν δυνατή η αναίρεση προτάσεων δωματίων",
        "llm": "LLM",
        "llmHint": "Το Klar μιλά σε τελικό σημείο συμβατό με OpenAI. Η συνομιλία Assist και ο εκπαιδευτής χρησιμοποιούν την ίδια config. Δεν χρειάζεται ενσωμάτωση OpenAI ή Ollama στο Home Assistant.",
        "llmBaseUrl": "Βασικό URL",
        "llmModel": "Μοντέλο",
        "llmApiKey": "Κλειδί API",
        "llmApiKeyHint": "Άφησέ το κενό για να κρατήσεις το αποθηκευμένο κλειδί. Το Ollama μπορεί να μείνει κενό.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Ρυθμισμένο",
        "llmNotConfigured": "Μη ρυθμισμένο",
        "llmClear": "Καθαρισμός",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Εκπαιδευτής",
        "trainerForLane": "Εκπαιδευτής για αυτή τη λωρίδα",
        "trainerHint": "Το Klar καλεί μοντέλο συμβατό με OpenAI σε Rust. Συνομιλία, έλεγχος, εφαρμογή ανά λωρίδα. Δεν χρειάζεται ενσωμάτωση LLM στο Home Assistant. Το προχωρημένο JSON είναι για αποσφαλμάτωση.",
        "trainerContext": "Πλαίσιο",
        "trainerValidate": "Έλεγχος",
        "trainerApply": "Εφαρμογή",
        "trainerProposal": "JSON πρότασης",
        "trainerOk": "Έγκυρο",
        "trainerFail": "Άκυρο",
        "trainerSend": "Αποστολή",
        "trainerNeedLlm": "Ρύθμισε πρώτα LLM στα Settings. Το Klar δεν χρειάζεται άλλη ενσωμάτωση συνομιλίας Home Assistant.",
        "trainerOpenSettings": "Άνοιγμα Settings",
        "trainerApplyHouse": "Εφαρμογή House",
        "trainerApplyMatch": "Εφαρμογή Match",
        "trainerApplyLanguage": "Εφαρμογή Language",
        "trainerAdvanced": "Προχωρημένο JSON",
        "trainerStreaming": "Ροή…",
    },
    "hy": {
        "engineHint": "Ձայնը, լեզուները և LLM-ը այստեղ են։ Home Assistant-ը միայն միացնում է շարժիչը։",
        "languageHint": "Դատարկ ցանկը պահում է յուրաքանչյուր կազմված Assist locale։ Մեկ փաթեթ ամրացնելը սովորական տուն է։",
        "personalityHa": "Ձայնը, լեզուները և LLM-ը այս Settings էջում են։",
        "assistLanguages": "Assist լեզուներ",
        "assistLanguagesHint": "Որ փաթեթները Klar-ը կարող է վերլուծել։ Արբանյակը դեռ ուղարկում է մեկ լեզու յուրաքանչյուր հարցման։ Դատարկ = բոլոր կազմված locale-ները։",
        "allAssistLanguages": "Յուրաքանչյուր կազմված locale",
        "pinLanguage": "Ամրացնել մեկ փաթեթ",
        "voice": "Ձայն",
        "voiceHint": "Անհատականություն և խոսված պատասխաններ։ Assist-ը կարդում է շարժիչից, ոչ Home Assistant ընտրանքներից։",
        "extraPrompt": "Լրացուցիչ հուշում",
        "extraPromptHint": "Ընտրովի տող փաթեթի անհատականության վրա։ Թող դատարկ, եթե տունը սեփական կանոն չի ուզում։",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM հղկում",
        "refineSpeechHint": "Klar-ը շարունակում է կառավարել սարքերը։ Շարժիչի LLM-ը հետո վերագրում է ավարտված NLU պատասխանները այս ձայնով։",
        "quietAck": "Կարճ հաստատում",
        "quietAckHint": "Պարզ լույսի կամ անջատիչի միացում/անջատումում բաց թող TTS և նվագիր զանգ արբանյակի վրա։",
        "calendarLlm": "Օրացույց LLM-ով",
        "calendarLlmHint": "Klar-ը շարունակում է կարդալ օրացույցը։ Միացված՝ LLM-ը ասում է իրադարձությունները։ Անջատված՝ Klar-ը ասում է ցանկը։",
        "allowLlmTools": "Թույլատրել Assist գործիքներ զրույցում",
        "allowLlmToolsHint": "Լռելյայն անջատված։ Միացված՝ զրույցի մոդելը կարող է կառավարել Home Assistant։ Անջատված՝ Klar-ը բաց է թողնում այդ գործակալը, եթե գործիքներ ունի։",
        "missTitle": "Երբ Klar-ը վրիպում է",
        "missHint": "Ընտրովի շերտեր որոշիչ մերժումից հետո։ Ոչ մեկը մոդել չի դնում parse-ի վրա։",
        "operatorChrome": "Այս էկրանը",
        "operatorChromeHint": "Թեմա և միջերեսի լեզու օպերատորների համար։ Ոչ Assist։",
        "haGlueHint": "Home Assistant Configure-ին պետք է միայն շարժիչի URL, նշան, ալիք և ընտրովի մնացած խոսակցության գործակալ։ Ձայնն ու LLM-ը մնում են այստեղ։",
        "settingsGuide": "Սահմանիր այս երեքը, հետո քարտեզագրիր տունը։",
        "settingsGuideVoice": "Ձայն",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist լեզու",
        "appearanceDark": "Մուգ",
        "appearanceLight": "Բաց",
        "setupReplay": "Կրկնել setup",
        "personalityDefault": "Սովորական",
        "personalityButler": "Butler",
        "personalityLocker": "Ազատ",
        "personalityFuersorglich": "Հոգատար",
        "personalityParty": "Խնջույք",
        "personalityGrantig": "Տրտնջան",
        "personalitySarkastisch": "Ծաղրական",
        "personalityPirat": "Ծովահեն",
        "personalityHippie": "Հիպի",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Օպերատորի լեզու",
        "operatorLanguageHint": "Միայն այս հավելվածը։ Պահված այստեղ կամ KLAR_UI_LOCALE առաջին պահումից առաջ։ Ոչ Assist, ոչ Home Assistant պրոֆիլ։",
        "nluRag": "Տան համատեքստ վրիպման ժամանակ",
        "modeFull": "Լուծել սարքերը",
        "modeContext": "Միայն սենյակներ",
        "inLab": "Լաբորատորիայում",
        "undoLastCommand": "Հետարկել վերջին հրամանը",
        "applyDone": "Կիրառվել է {count} սենյակի առաջարկ",
        "applyUndone": "Սենյակի առաջարկները հետարկված են",
        "applyUndoFailed": "Չհաջողվեց հետարկել սենյակի առաջարկները",
        "llm": "LLM",
        "llmHint": "Klar-ը խոսում է OpenAI-համատեղելի վերջնակետի հետ։ Assist զրույցն ու մարզիչը օգտագործում են նույն config։ Home Assistant-ում OpenAI կամ Ollama ինտեգրում պետք չէ։",
        "llmBaseUrl": "Հիմնական URL",
        "llmModel": "Մոդել",
        "llmApiKey": "API բանալի",
        "llmApiKeyHint": "Թող դատարկ՝ պահված բանալին պահելու համար։ Ollama կարող է դատարկ մնալ։",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Կարգավորված",
        "llmNotConfigured": "Չկարգավորված",
        "llmClear": "Մաքրել",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Մարզիչ",
        "trainerForLane": "Մարզիչ այս ուղու համար",
        "trainerHint": "Klar-ը կանչում է OpenAI-համատեղելի մոդել Rust-ում։ Զրուցիր, ստուգիր, ապա կիրառիր ըստ ուղու։ Home Assistant LLM ինտեգրում պետք չէ։ Ընդլայնված JSON-ը վրիպազերծման համար է։",
        "trainerContext": "Համատեքստ",
        "trainerValidate": "Ստուգել",
        "trainerApply": "Կիրառել",
        "trainerProposal": "Առաջարկի JSON",
        "trainerOk": "Վավեր",
        "trainerFail": "Անվավեր",
        "trainerSend": "Ուղարկել",
        "trainerNeedLlm": "Նախ կարգավորիր LLM Settings-ում։ Klar-ին այլ Home Assistant խոսակցության ինտեգրում պետք չէ։",
        "trainerOpenSettings": "Բացել Settings",
        "trainerApplyHouse": "Կիրառել House",
        "trainerApplyMatch": "Կիրառել Match",
        "trainerApplyLanguage": "Կիրառել Language",
        "trainerAdvanced": "Ընդլայնված JSON",
        "trainerStreaming": "Հոսք…",
    },
    "ka": {
        "engineHint": "ხმა, ენები და LLM აქაა. Home Assistant მხოლოდ ძრავას აკავშირებს.",
        "languageHint": "ცარიელი სია ყოველ კომპილირებულ Assist locale-ს აქტიურს ტოვებს. ერთი პაკეტის მიმაგრება ჩვეულებრივი სახლია.",
        "personalityHa": "ხმა, ენები და LLM ამ Settings გვერდზეა.",
        "assistLanguages": "Assist ენები",
        "assistLanguagesHint": "რომელი პაკეტების გარჩევა შეუძლია Klar-ს. თანამგზავრი მაინც აგზავნის ერთ ენას თითო მოთხოვნაზე. ცარიელი = ყველა კომპილირებული locale.",
        "allAssistLanguages": "ყოველი კომპილირებული locale",
        "pinLanguage": "ერთი პაკეტის მიმაგრება",
        "voice": "ხმა",
        "voiceHint": "პიროვნება და ნათქვამი პასუხები. Assist ამას ძრავიდან კითხულობს, არა Home Assistant პარამეტრებიდან.",
        "extraPrompt": "დამატებითი prompt",
        "extraPromptHint": "არასავალდებულო ხაზი პაკეტის პიროვნების თავზე. დატოვე ცარიელი, თუ სახლს საკუთარი წესი არ სჭირდება.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM გაპრიალება",
        "refineSpeechHint": "Klar კვლავ აკონტროლებს მოწყობილობებს. ძრავის LLM შემდეგ გადაწერს დასრულებულ NLU პასუხებს ამ ხმით.",
        "quietAck": "მოკლე დადასტურება",
        "quietAckHint": "მარტივ ნათურაზე ან ჩართვა/გამორთვის გადამრთველზე გამოტოვე TTS და დაუკარი ზარი თანამგზავრზე.",
        "calendarLlm": "კალენდარი LLM-ით",
        "calendarLlmHint": "Klar კვლავ კითხულობს კალენდარს. ჩართული: LLM ამბობს მოვლენებს. გამორთული: Klar ამბობს სიას.",
        "allowLlmTools": "Assist ხელსაწყოების დაშვება ჩატში",
        "allowLlmToolsHint": "ნაგულისხმევად გამორთული. ჩართული: ჩატის მოდელს შეუძლია Home Assistant-ის მართვა. გამორთული: Klar გამოტოვებს იმ აგენტს, თუ ხელსაწყოები აქვს.",
        "missTitle": "როცა Klar აცდება",
        "missHint": "არასავალდებულო ფენები დეტერმინისტული უარის შემდეგ. არცერთი მოდელს parse-ზე არ სვამს.",
        "operatorChrome": "ეს ეკრანი",
        "operatorChromeHint": "თემა და ინტერფეისის ენა ოპერატორებისთვის. არა Assist.",
        "haGlueHint": "Home Assistant Configure-ს სჭირდება მხოლოდ ძრავის URL, ჟეტონი, არხი და არასავალდებულო დარჩენილი საუბრის აგენტი. ხმა და LLM აქ რჩება.",
        "settingsGuide": "დააყენე ეს სამი, შემდეგ დაამაპე სახლი.",
        "settingsGuideVoice": "ხმა",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist ენა",
        "appearanceDark": "ბნელი",
        "appearanceLight": "ნათელი",
        "setupReplay": "setup-ის გამეორება",
        "personalityDefault": "ჩვეულებრივი",
        "personalityButler": "Butler",
        "personalityLocker": "მშვიდი",
        "personalityFuersorglich": "მზრუნველი",
        "personalityParty": "წვეულება",
        "personalityGrantig": "წუწუნა",
        "personalitySarkastisch": "სარკასტული",
        "personalityPirat": "მეკობრე",
        "personalityHippie": "ჰიპი",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ოპერატორის ენა",
        "operatorLanguageHint": "მხოლოდ ეს აპი. აქ შენახული, ან KLAR_UI_LOCALE პირველ შენახვამდე. არა Assist, არა Home Assistant პროფილი.",
        "nluRag": "სახლის კონტექსტი აცდენისას",
        "modeFull": "მოწყობილობების ამოხსნა",
        "modeContext": "მხოლოდ ოთახები",
        "inLab": "ლაბორატორიაში",
        "undoLastCommand": "ბოლო ბრძანების გაუქმება",
        "applyDone": "გამოყენებულია {count} ოთახის შემოთავაზება",
        "applyUndone": "ოთახის შემოთავაზებები გაუქმდა",
        "applyUndoFailed": "ოთახის შემოთავაზებების გაუქმება ვერ მოხერხდა",
        "llm": "LLM",
        "llmHint": "Klar საუბრობს OpenAI-თავსებად ბოლო წერტილთან. Assist ჩატი და მწვრთნელი იყენებენ იმავე config-ს. Home Assistant-ში OpenAI ან Ollama ინტეგრაცია არაა საჭირო.",
        "llmBaseUrl": "საბაზისო URL",
        "llmModel": "მოდელი",
        "llmApiKey": "API გასაღები",
        "llmApiKeyHint": "დატოვე ცარიელი შენახული გასაღების შესანარჩუნებლად. Ollama შეიძლება ცარიელი დარჩეს.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "მორგებული",
        "llmNotConfigured": "არ არის მორგებული",
        "llmClear": "გასუფთავება",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "მწვრთნელი",
        "trainerForLane": "მწვრთნელი ამ ბილიკისთვის",
        "trainerHint": "Klar იძახებს OpenAI-თავსებად მოდელს Rust-ში. ჩატი, შემოწმება, შემდეგ გამოყენება ბილიკის მიხედვით. Home Assistant LLM ინტეგრაცია არაა საჭირო. გაფართოებული JSON გამართვისთვისაა.",
        "trainerContext": "კონტექსტი",
        "trainerValidate": "შემოწმება",
        "trainerApply": "გამოყენება",
        "trainerProposal": "შემოთავაზების JSON",
        "trainerOk": "მართებული",
        "trainerFail": "არასწორი",
        "trainerSend": "გაგზავნა",
        "trainerNeedLlm": "ჯერ დააყენე LLM Settings-ში. Klar-ს სხვა Home Assistant საუბრის ინტეგრაცია არ სჭირდება.",
        "trainerOpenSettings": "Settings-ის გახსნა",
        "trainerApplyHouse": "House-ის გამოყენება",
        "trainerApplyMatch": "Match-ის გამოყენება",
        "trainerApplyLanguage": "Language-ის გამოყენება",
        "trainerAdvanced": "გაფართოებული JSON",
        "trainerStreaming": "ნაკადი…",
    },
    "hi": {
        "engineHint": "आवाज़, भाषाएँ और LLM यहीं हैं। Home Assistant केवल इंजन जोड़ता है।",
        "languageHint": "खाली सूची हर संकलित Assist locale चालू रखती है। एक पैक पिन करना सामान्य घर है।",
        "personalityHa": "आवाज़, भाषाएँ और LLM इस Settings पृष्ठ पर हैं।",
        "assistLanguages": "Assist भाषाएँ",
        "assistLanguagesHint": "Klar किन पैकों का विश्लेषण कर सकता है। उपग्रह फिर भी हर अनुरोध पर एक भाषा भेजता है। खाली = सभी संकलित locale।",
        "allAssistLanguages": "हर संकलित locale",
        "pinLanguage": "एक पैक पिन करें",
        "voice": "आवाज़",
        "voiceHint": "व्यक्तित्व और बोले गए उत्तर। Assist इसे इंजन से पढ़ता है, Home Assistant विकल्पों से नहीं।",
        "extraPrompt": "अतिरिक्त प्रॉम्प्ट",
        "extraPromptHint": "पैक व्यक्तित्व के ऊपर वैकल्पिक पंक्ति। घर के अपने नियम की ज़रूरत न हो तो खाली छोड़ें।",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM परिष्करण",
        "refineSpeechHint": "Klar अभी भी उपकरण नियंत्रित करता है। इंजन LLM फिर पूरे NLU उत्तर इस आवाज़ में लिखता है।",
        "quietAck": "संक्षिप्त पुष्टि",
        "quietAckHint": "साधारण बत्ती या स्विच चालू/बंद पर TTS छोड़ें और उपग्रह पर घंटी बजाएँ।",
        "calendarLlm": "कैलेंडर LLM से",
        "calendarLlmHint": "Klar कैलेंडर पढ़ता रहता है। चालू: LLM घटनाएँ बोलता है। बंद: Klar सूची बोलता है।",
        "allowLlmTools": "चैट पर Assist उपकरण अनुमति दें",
        "allowLlmToolsHint": "मूल रूप से बंद। चालू: चैट मॉडल Home Assistant नियंत्रित कर सकता है। बंद: औज़ार हों तो Klar उस एजेंट को छोड़ देता है।",
        "missTitle": "जब Klar चूके",
        "missHint": "निर्धारित अस्वीकार के बाद वैकल्पिक परतें। कोई भी मॉडल को parse पर नहीं रखती।",
        "operatorChrome": "यह स्क्रीन",
        "operatorChromeHint": "संचालकों के लिए थीम और इंटरफ़ेस भाषा। Assist नहीं।",
        "haGlueHint": "Home Assistant Configure को केवल इंजन URL, टोकन, चैनल और वैकल्पिक बचा हुआ बातचीत एजेंट चाहिए। आवाज़ और LLM यहीं रहते हैं।",
        "settingsGuide": "ये तीन सेट करें, फिर घर नक्शा करें।",
        "settingsGuideVoice": "आवाज़",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist भाषा",
        "appearanceDark": "गहरा",
        "appearanceLight": "हल्का",
        "setupReplay": "सेटअप दोहराएँ",
        "personalityDefault": "सामान्य",
        "personalityButler": "Butler",
        "personalityLocker": "आरामदायक",
        "personalityFuersorglich": "देखभाल करने वाला",
        "personalityParty": "पार्टी",
        "personalityGrantig": "चिड़चिड़ा",
        "personalitySarkastisch": "व्यंग्यात्मक",
        "personalityPirat": "समुद्री डाकू",
        "personalityHippie": "हिप्पी",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "संचालक भाषा",
        "operatorLanguageHint": "केवल यह ऐप। यहाँ सहेजा गया, या पहली सहेज से पहले KLAR_UI_LOCALE। Assist नहीं, Home Assistant प्रोफ़ाइल नहीं।",
        "nluRag": "चूक पर घर का संदर्भ",
        "modeFull": "उपकरण सुलझाएँ",
        "modeContext": "केवल कमरे",
        "inLab": "प्रयोगशाला में",
        "undoLastCommand": "अंतिम आदेश पूर्ववत",
        "applyDone": "{count} कमरे के सुझाव लागू",
        "applyUndone": "कमरे के सुझाव पूर्ववत",
        "applyUndoFailed": "कमरे के सुझाव पूर्ववत नहीं हो सके",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-संगत अंतबिंदु से बात करता है। Assist चैट और प्रशिक्षक यही config इस्तेमाल करते हैं। Home Assistant में OpenAI या Ollama एकीकरण ज़रूरी नहीं।",
        "llmBaseUrl": "आधार URL",
        "llmModel": "मॉडल",
        "llmApiKey": "API कुंजी",
        "llmApiKeyHint": "संग्रहीत कुंजी रखने के लिए खाली छोड़ें। Ollama खाली रह सकता है।",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "विन्यस्त",
        "llmNotConfigured": "अविन्यस्त",
        "llmClear": "साफ़ करें",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "प्रशिक्षक",
        "trainerForLane": "इस लेन का प्रशिक्षक",
        "trainerHint": "Klar Rust में OpenAI-संगत मॉडल बुलाता है। चैट करें, जाँचें, फिर लेन के अनुसार लागू करें। Home Assistant LLM एकीकरण ज़रूरी नहीं। उन्नत JSON डिबग के लिए है।",
        "trainerContext": "संदर्भ",
        "trainerValidate": "जाँचें",
        "trainerApply": "लागू करें",
        "trainerProposal": "प्रस्ताव JSON",
        "trainerOk": "मान्य",
        "trainerFail": "अमान्य",
        "trainerSend": "भेजें",
        "trainerNeedLlm": "पहले Settings में LLM सेट करें। Klar को दूसरा Home Assistant बातचीत एकीकरण नहीं चाहिए।",
        "trainerOpenSettings": "Settings खोलें",
        "trainerApplyHouse": "House लागू करें",
        "trainerApplyMatch": "Match लागू करें",
        "trainerApplyLanguage": "Language लागू करें",
        "trainerAdvanced": "उन्नत JSON",
        "trainerStreaming": "स्ट्रीमिंग…",
    },
    "bn": {
        "engineHint": "কণ্ঠ, ভাষা এবং LLM এখানে। Home Assistant শুধু ইঞ্জিন জোড়ে।",
        "languageHint": "খালি তালিকা প্রতিটি সংকলিত Assist locale চালু রাখে। একটি প্যাক পিন করা সাধারণ ঘর।",
        "personalityHa": "কণ্ঠ, ভাষা এবং LLM এই Settings পাতায়।",
        "assistLanguages": "Assist ভাষা",
        "assistLanguagesHint": "Klar কোন প্যাক বিশ্লেষণ করতে পারে। উপগ্রহ তবুও প্রতি অনুরোধে একটি ভাষা পাঠায়। খালি = সব সংকলিত locale।",
        "allAssistLanguages": "প্রতিটি সংকলিত locale",
        "pinLanguage": "একটি প্যাক পিন করুন",
        "voice": "কণ্ঠ",
        "voiceHint": "ব্যক্তিত্ব ও কথ্য উত্তর। Assist এটি ইঞ্জিন থেকে পড়ে, Home Assistant বিকল্প থেকে নয়।",
        "extraPrompt": "অতিরিক্ত প্রম্পট",
        "extraPromptHint": "প্যাক ব্যক্তিত্বের উপর ঐচ্ছিক লাইন। ঘরের নিজস্ব নিয়ম না চাইলে খালি রাখুন।",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM পরিমার্জন",
        "refineSpeechHint": "Klar এখনও ডিভাইস নিয়ন্ত্রণ করে। ইঞ্জিন LLM তারপর শেষ NLU উত্তর এই কণ্ঠে লেখে।",
        "quietAck": "সংক্ষিপ্ত নিশ্চিতকরণ",
        "quietAckHint": "সাধারণ আলো বা সুইচ চালু/বন্ধে TTS বাদ দিন এবং উপগ্রহে ঘণ্টা বাজান।",
        "calendarLlm": "ক্যালেন্ডার LLM দিয়ে",
        "calendarLlmHint": "Klar ক্যালেন্ডার পড়েই যায়। চালু: LLM ঘটনা বলে। বন্ধ: Klar তালিকা বলে।",
        "allowLlmTools": "চ্যাটে Assist সরঞ্জাম অনুমতি দিন",
        "allowLlmToolsHint": "ডিফল্ট বন্ধ। চালু: চ্যাট মডেল Home Assistant নিয়ন্ত্রণ করতে পারে। বন্ধ: সরঞ্জাম থাকলে Klar সেই এজেন্ট এড়িয়ে যায়।",
        "missTitle": "Klar যখন চুকে",
        "missHint": "নির্ধারিত প্রত্যাখ্যানের পর ঐচ্ছিক স্তর। কোনোটিই parse-এ মডেল রাখে না।",
        "operatorChrome": "এই পর্দা",
        "operatorChromeHint": "অপারেটরদের থিম ও ইন্টারফেস ভাষা। Assist নয়।",
        "haGlueHint": "Home Assistant Configure-এর শুধু ইঞ্জিন URL, টোকেন, চ্যানেল ও ঐচ্ছিক অবশিষ্ট কথোপকথন এজেন্ট লাগে। কণ্ঠ ও LLM এখানেই থাকে।",
        "settingsGuide": "এই তিনটি সেট করুন, তারপর ঘর ম্যাপ করুন।",
        "settingsGuideVoice": "কণ্ঠ",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist ভাষা",
        "appearanceDark": "গাঢ়",
        "appearanceLight": "হালকা",
        "setupReplay": "সেটআপ আবার চালান",
        "personalityDefault": "সাধারণ",
        "personalityButler": "Butler",
        "personalityLocker": "আরামদায়ক",
        "personalityFuersorglich": "যত্নশীল",
        "personalityParty": "পার্টি",
        "personalityGrantig": "বদমেজাজি",
        "personalitySarkastisch": "ব্যঙ্গাত্মক",
        "personalityPirat": "জলদস্যু",
        "personalityHippie": "হিপি",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "অপারেটর ভাষা",
        "operatorLanguageHint": "শুধু এই অ্যাপ। এখানে সংরক্ষিত, বা প্রথম সংরক্ষণের আগে KLAR_UI_LOCALE। Assist নয়, Home Assistant প্রোফাইল নয়।",
        "nluRag": "চুকে ঘরের প্রসঙ্গ",
        "modeFull": "ডিভাইস সমাধান",
        "modeContext": "শুধু ঘর",
        "inLab": "ল্যাবে",
        "undoLastCommand": "শেষ নির্দেশ পূর্বাবস্থা",
        "applyDone": "{count} ঘরের পরামর্শ প্রয়োগ",
        "applyUndone": "ঘরের পরামর্শ পূর্বাবস্থা",
        "applyUndoFailed": "ঘরের পরামর্শ পূর্বাবস্থা যায়নি",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-সামঞ্জস্যপূর্ণ প্রান্তবিন্দুর সাথে কথা বলে। Assist চ্যাট ও প্রশিক্ষক একই config ব্যবহার করে। Home Assistant-এ OpenAI বা Ollama ইন্টিগ্রেশন লাগে না।",
        "llmBaseUrl": "ভিত্তি URL",
        "llmModel": "মডেল",
        "llmApiKey": "API চাবি",
        "llmApiKeyHint": "সংরক্ষিত চাবি রাখতে খালি রাখুন। Ollama খালি থাকতে পারে।",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "কনফিগার করা",
        "llmNotConfigured": "কনফিগার হয়নি",
        "llmClear": "মুছুন",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "প্রশিক্ষক",
        "trainerForLane": "এই লেনের প্রশিক্ষক",
        "trainerHint": "Klar Rust-এ OpenAI-সামঞ্জস্যপূর্ণ মডেল ডাকে। চ্যাট, যাচাই, তারপর লেন অনুসারে প্রয়োগ। Home Assistant LLM ইন্টিগ্রেশন লাগে না। উন্নত JSON ডিবাগের জন্য।",
        "trainerContext": "প্রসঙ্গ",
        "trainerValidate": "যাচাই",
        "trainerApply": "প্রয়োগ",
        "trainerProposal": "প্রস্তাব JSON",
        "trainerOk": "বৈধ",
        "trainerFail": "অবৈধ",
        "trainerSend": "পাঠান",
        "trainerNeedLlm": "আগে Settings-এ LLM সেট করুন। Klar-এর অন্য Home Assistant কথোপকথন ইন্টিগ্রেশন লাগে না।",
        "trainerOpenSettings": "Settings খুলুন",
        "trainerApplyHouse": "House প্রয়োগ",
        "trainerApplyMatch": "Match প্রয়োগ",
        "trainerApplyLanguage": "Language প্রয়োগ",
        "trainerAdvanced": "উন্নত JSON",
        "trainerStreaming": "স্ট্রিমিং…",
    },
    "gu": {
        "engineHint": "અવાજ, ભાષાઓ અને LLM અહીં છે. Home Assistant ફક્ત એન્જિન જોડે છે.",
        "languageHint": "ખાલી યાદી દરેક સંકલિત Assist locale ચાલુ રાખે છે. એક પૅક પિન કરવું સામાન્ય ઘર છે.",
        "personalityHa": "અવાજ, ભાષાઓ અને LLM આ Settings પાના પર છે.",
        "assistLanguages": "Assist ભાષાઓ",
        "assistLanguagesHint": "Klar કયા પૅક વિશ્લેષણ કરી શકે. ઉપગ્રહ હજુ પણ દર વિનંતીએ એક ભાષા મોકલે છે. ખાલી = બધી સંકલિત locale.",
        "allAssistLanguages": "દરેક સંકલિત locale",
        "pinLanguage": "એક પૅક પિન કરો",
        "voice": "અવાજ",
        "voiceHint": "વ્યક્તિત્વ અને બોલાયેલા જવાબો. Assist આ એન્જિનથી વાંચે છે, Home Assistant વિકલ્પોથી નહીં.",
        "extraPrompt": "વધારાનો પ્રોમ્પ્ટ",
        "extraPromptHint": "પૅક વ્યક્તિત્વ ઉપર વૈકલ્પિક પંક્તિ. ઘરને પોતાનો નિયમ ન જોઈએ તો ખાલી રાખો.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM ચળકાવ",
        "refineSpeechHint": "Klar હજુ ઉપકરણ નિયંત્રિત કરે છે. એન્જિન LLM પછી પૂર્ણ NLU જવાબો આ અવાજમાં લખે છે.",
        "quietAck": "ટૂંકી પુષ્ટિ",
        "quietAckHint": "સાદી લાઇટ કે સ્વિચ ચાલુ/બંધ પર TTS છોડો અને ઉપગ્રહ પર ઘંટ વગાડો.",
        "calendarLlm": "કૅલેન્ડર LLM દ્વારા",
        "calendarLlmHint": "Klar કૅલેન્ડર વાંચતું રહે છે. ચાલુ: LLM ઘટનાઓ બોલે. બંધ: Klar યાદી બોલે.",
        "allowLlmTools": "ચેટ પર Assist સાધનો મંજૂરી આપો",
        "allowLlmToolsHint": "મૂળભૂત બંધ. ચાલુ: ચેટ મોડલ Home Assistant નિયંત્રિત કરી શકે. બંધ: સાધનો હોય તો Klar તે એજન્ટ છોડે.",
        "missTitle": "જ્યારે Klar ચૂકે",
        "missHint": "નિશ્ચિત નકાર પછી વૈકલ્પિક સ્તર. કોઈ પણ parse પર મોડલ મૂકતું નથી.",
        "operatorChrome": "આ સ્ક્રીન",
        "operatorChromeHint": "ઓપરેટરો માટે થીમ અને ઇન્ટરફેસ ભાષા. Assist નહીં.",
        "haGlueHint": "Home Assistant Configure ને ફક્ત એન્જિન URL, ટોકન, ચૅનલ અને વૈકલ્પિક બચેલો વાતચીત એજન્ટ જોઈએ. અવાજ અને LLM અહીં રહે છે.",
        "settingsGuide": "આ ત્રણ સેટ કરો, પછી ઘર નકશો કરો.",
        "settingsGuideVoice": "અવાજ",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist ભાષા",
        "appearanceDark": "ઘાટું",
        "appearanceLight": "આછું",
        "setupReplay": "સેટઅપ ફરી ચલાવો",
        "personalityDefault": "સામાન્ય",
        "personalityButler": "Butler",
        "personalityLocker": "આરામદાયક",
        "personalityFuersorglich": "કાળજીવાળું",
        "personalityParty": "પાર્ટી",
        "personalityGrantig": "ચીડિયું",
        "personalitySarkastisch": "વ્યંગ્યાત્મક",
        "personalityPirat": "ચાંચિયું",
        "personalityHippie": "હિપ્પી",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ઓપરેટર ભાષા",
        "operatorLanguageHint": "ફક્ત આ ઍપ. અહીં સાચવેલ, અથવા પહેલી સાચવણી પહેલાં KLAR_UI_LOCALE. Assist નહીં, Home Assistant પ્રોફાઇલ નહીં.",
        "nluRag": "ચૂક પર ઘરનો સંદર્ભ",
        "modeFull": "ઉપકરણ ઉકેલો",
        "modeContext": "ફક્ત ઓરડા",
        "inLab": "પ્રયોગશાળામાં",
        "undoLastCommand": "છેલ્લો આદેશ પૂર્વવત્",
        "applyDone": "{count} ઓરડાના સૂચનો લાગુ",
        "applyUndone": "ઓરડાના સૂચનો પૂર્વવત્",
        "applyUndoFailed": "ઓરડાના સૂચનો પૂર્વવત્ ન થયાં",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-સુસંગત અંતિમબિંદુ સાથે વાત કરે છે. Assist ચેટ અને પ્રશિક્ષક એ જ config વાપરે છે. Home Assistantમાં OpenAI કે Ollama એકીકરણ જરૂરી નથી.",
        "llmBaseUrl": "આધાર URL",
        "llmModel": "મોડલ",
        "llmApiKey": "API કી",
        "llmApiKeyHint": "સંગ્રહિત કી રાખવા ખાલી રાખો. Ollama ખાલી રહી શકે.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ગોઠવેલ",
        "llmNotConfigured": "ગોઠવ્યું નથી",
        "llmClear": "સાફ કરો",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "પ્રશિક્ષક",
        "trainerForLane": "આ લેનનો પ્રશિક્ષક",
        "trainerHint": "Klar Rustમાં OpenAI-સુસંગત મોડલ બોલાવે છે. ચેટ, ચકાસો, પછી લેન મુજબ લાગુ કરો. Home Assistant LLM એકીકરણ જરૂરી નથી. અદ્યતન JSON ડિબગ માટે છે.",
        "trainerContext": "સંદર્ભ",
        "trainerValidate": "ચકાસો",
        "trainerApply": "લાગુ કરો",
        "trainerProposal": "પ્રસ્તાવ JSON",
        "trainerOk": "માન્ય",
        "trainerFail": "અમાન્ય",
        "trainerSend": "મોકલો",
        "trainerNeedLlm": "પહેલાં Settingsમાં LLM ગોઠવો. Klarને બીજું Home Assistant વાતચીત એકીકરણ નથી જોઈતું.",
        "trainerOpenSettings": "Settings ખોલો",
        "trainerApplyHouse": "House લાગુ કરો",
        "trainerApplyMatch": "Match લાગુ કરો",
        "trainerApplyLanguage": "Language લાગુ કરો",
        "trainerAdvanced": "અદ્યતન JSON",
        "trainerStreaming": "સ્ટ્રીમિંગ…",
    },
    "kn": {
        "engineHint": "ಧ್ವನಿ, ಭಾಷೆಗಳು ಮತ್ತು LLM ಇಲ್ಲಿವೆ. Home Assistant ಕೇವಲ ಎಂಜಿನ್ ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
        "languageHint": "ಖಾಲಿ ಪಟ್ಟಿ ಪ್ರತಿ ಸಂಕಲಿತ Assist locale ಅನ್ನು ಸಕ್ರಿಯವಾಗಿಡುತ್ತದೆ. ಒಂದು ಪ್ಯಾಕ್ ಪಿನ್ ಮಾಡುವುದು ಸಾಮಾನ್ಯ ಮನೆ.",
        "personalityHa": "ಧ್ವನಿ, ಭಾಷೆಗಳು ಮತ್ತು LLM ಈ Settings ಪುಟದಲ್ಲಿವೆ.",
        "assistLanguages": "Assist ಭಾಷೆಗಳು",
        "assistLanguagesHint": "Klar ಯಾವ ಪ್ಯಾಕ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಬಹುದು. ಉಪಗ್ರಹ ಇನ್ನೂ ಪ್ರತಿ ವಿನಂತಿಗೆ ಒಂದು ಭಾಷೆ ಕಳುಹಿಸುತ್ತದೆ. ಖಾಲಿ = ಎಲ್ಲ ಸಂಕಲಿತ locale.",
        "allAssistLanguages": "ಪ್ರತಿ ಸಂಕಲಿತ locale",
        "pinLanguage": "ಒಂದು ಪ್ಯಾಕ್ ಪಿನ್ ಮಾಡಿ",
        "voice": "ಧ್ವನಿ",
        "voiceHint": "ವ್ಯಕ್ತಿತ್ವ ಮತ್ತು ಮಾತಿನ ಉತ್ತರಗಳು. Assist ಇದನ್ನು ಎಂಜಿನ್‌ನಿಂದ ಓದುತ್ತದೆ, Home Assistant ಆಯ್ಕೆಗಳಿಂದ ಅಲ್ಲ.",
        "extraPrompt": "ಹೆಚ್ಚುವರಿ ಪ್ರಾಂಪ್ಟ್",
        "extraPromptHint": "ಪ್ಯಾಕ್ ವ್ಯಕ್ತಿತ್ವದ ಮೇಲಿನ ಐಚ್ಛಿಕ ಸಾಲು. ಮನೆಗೆ ಸ್ವಂತ ನಿಯಮ ಬೇಕಿಲ್ಲದಿದ್ದರೆ ಖಾಲಿ ಬಿಡಿ.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM ಹದಗೊಳಿಸುವಿಕೆ",
        "refineSpeechHint": "Klar ಇನ್ನೂ ಸಾಧನಗಳನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ಎಂಜಿನ್ LLM ನಂತರ ಮುಗಿದ NLU ಉತ್ತರಗಳನ್ನು ಈ ಧ್ವನಿಯಲ್ಲಿ ಬರೆಯುತ್ತದೆ.",
        "quietAck": "ಸಂಕ್ಷಿಪ್ತ ದೃಢೀಕರಣ",
        "quietAckHint": "ಸರಳ ಬೆಳಕು ಅಥವಾ ಸ್ವಿಚ್ ಆನ್/ಆಫ್‌ನಲ್ಲಿ TTS ಬಿಟ್ಟು ಉಪಗ್ರಹದಲ್ಲಿ ಗಂಟೆ ಬಾರಿಸಿ.",
        "calendarLlm": "ಕ್ಯಾಲೆಂಡರ್ LLM ಮೂಲಕ",
        "calendarLlmHint": "Klar ಕ್ಯಾಲೆಂಡರ್ ಓದುತ್ತಲೇ ಇರುತ್ತದೆ. ಆನ್: LLM ಘಟನೆಗಳನ್ನು ಹೇಳುತ್ತದೆ. ಆಫ್: Klar ಪಟ್ಟಿ ಹೇಳುತ್ತದೆ.",
        "allowLlmTools": "ಚಾಟ್‌ನಲ್ಲಿ Assist ಸಾಧನಗಳನ್ನು ಅನುಮತಿಸಿ",
        "allowLlmToolsHint": "ಪೂರ್ವನಿಯೋಜಿತವಾಗಿ ಆಫ್. ಆನ್: ಚಾಟ್ ಮಾದರಿ Home Assistant ನಿಯಂತ್ರಿಸಬಹುದು. ಆಫ್: ಸಾಧನಗಳಿದ್ದರೆ Klar ಆ ಏಜೆಂಟ್ ಬಿಡುತ್ತದೆ.",
        "missTitle": "Klar ತಪ್ಪಿದಾಗ",
        "missHint": "ನಿರ್ಧಾರಿತ ನಿರಾಕರಣೆಯ ನಂತರದ ಐಚ್ಛಿಕ ಪದರಗಳು. ಯಾವುದೂ parse ಮೇಲೆ ಮಾದರಿ ಇಡುವುದಿಲ್ಲ.",
        "operatorChrome": "ಈ ಪರದೆ",
        "operatorChromeHint": "ನಿರ್ವಾಹಕರಿಗೆ ಥೀಮ್ ಮತ್ತು ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ. Assist ಅಲ್ಲ.",
        "haGlueHint": "Home Assistant Configureಗೆ ಕೇವಲ ಎಂಜಿನ್ URL, ಟೋಕನ್, ಚಾನಲ್ ಮತ್ತು ಐಚ್ಛಿಕ ಉಳಿದ ಸಂಭಾಷಣೆ ಏಜೆಂಟ್ ಬೇಕು. ಧ್ವನಿ ಮತ್ತು LLM ಇಲ್ಲೇ ಉಳಿಯುತ್ತವೆ.",
        "settingsGuide": "ಈ ಮೂರನ್ನು ಹೊಂದಿಸಿ, ನಂತರ ಮನೆ ನಕ್ಷೆ ಮಾಡಿ.",
        "settingsGuideVoice": "ಧ್ವನಿ",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist ಭಾಷೆ",
        "appearanceDark": "ಗಾಢ",
        "appearanceLight": "ತಿಳಿ",
        "setupReplay": "ಸೆಟಪ್ ಮತ್ತೆ ಚಲಾಯಿಸಿ",
        "personalityDefault": "ಸಾಮಾನ್ಯ",
        "personalityButler": "Butler",
        "personalityLocker": "ಸಡಿಲ",
        "personalityFuersorglich": "ಕಾಳಜಿಯುಳ್ಳ",
        "personalityParty": "ಪಾರ್ಟಿ",
        "personalityGrantig": "ಕೋಪಗೊಂಡ",
        "personalitySarkastisch": "ವ್ಯಂಗ್ಯ",
        "personalityPirat": "ಕಡಲ್ಗಳ್ಳ",
        "personalityHippie": "ಹಿಪ್ಪಿ",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ನಿರ್ವಾಹಕ ಭಾಷೆ",
        "operatorLanguageHint": "ಈ ಅಪ್ಲಿಕೇಶನ್ ಮಾತ್ರ. ಇಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ, ಅಥವಾ ಮೊದಲ ಉಳಿಸುವಿಕೆಯ ಮೊದಲು KLAR_UI_LOCALE. Assist ಅಲ್ಲ, Home Assistant ಪ್ರೊಫೈಲ್ ಅಲ್ಲ.",
        "nluRag": "ತಪ್ಪಿದಾಗ ಮನೆಯ ಸಂದರ್ಭ",
        "modeFull": "ಸಾಧನಗಳನ್ನು ಬಿಡಿಸಿ",
        "modeContext": "ಕೋಣೆಗಳು ಮಾತ್ರ",
        "inLab": "ಪ್ರಯೋಗಾಲಯದಲ್ಲಿ",
        "undoLastCommand": "ಕೊನೆಯ ಆದೇಶ ರದ್ದುಮಾಡು",
        "applyDone": "{count} ಕೋಣೆ ಸಲಹೆಗಳನ್ನು ಅನ್ವಯಿಸಲಾಗಿದೆ",
        "applyUndone": "ಕೋಣೆ ಸಲಹೆಗಳು ರದ್ದು",
        "applyUndoFailed": "ಕೋಣೆ ಸಲಹೆಗಳನ್ನು ರದ್ದುಮಾಡಲಾಗಲಿಲ್ಲ",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-ಹೊಂದಾಣಿಕೆಯ ಅಂತ್ಯಬಿಂದುವಿಗೆ ಮಾತನಾಡುತ್ತದೆ. Assist ಚಾಟ್ ಮತ್ತು ತರಬೇತುದಾರ ಒಂದೇ config ಬಳಸುತ್ತಾರೆ. Home Assistantನಲ್ಲಿ OpenAI ಅಥವಾ Ollama ಏಕೀಕರಣ ಬೇಕಿಲ್ಲ.",
        "llmBaseUrl": "ಮೂಲ URL",
        "llmModel": "ಮಾದರಿ",
        "llmApiKey": "API ಕೀ",
        "llmApiKeyHint": "ಸಂಗ್ರಹಿತ ಕೀ ಉಳಿಸಲು ಖಾಲಿ ಬಿಡಿ. Ollama ಖಾಲಿ ಉಳಿಯಬಹುದು.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ಸಂರಚಿಸಲಾಗಿದೆ",
        "llmNotConfigured": "ಸಂರಚಿಸಿಲ್ಲ",
        "llmClear": "ಅಳಿಸು",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "ತರಬೇತುದಾರ",
        "trainerForLane": "ಈ ಪಥದ ತರಬೇತುದಾರ",
        "trainerHint": "Klar Rustನಲ್ಲಿ OpenAI-ಹೊಂದಾಣಿಕೆಯ ಮಾದರಿ ಕರೆಯುತ್ತದೆ. ಚಾಟ್, ಪರಿಶೀಲಿಸಿ, ನಂತರ ಪಥದ ಪ್ರಕಾರ ಅನ್ವಯಿಸಿ. Home Assistant LLM ಏಕೀಕರಣ ಬೇಕಿಲ್ಲ. ಸುಧಾರಿತ JSON ಡೀಬಗ್‌ಗಾಗಿ.",
        "trainerContext": "ಸಂದರ್ಭ",
        "trainerValidate": "ಪರಿಶೀಲಿಸು",
        "trainerApply": "ಅನ್ವಯಿಸು",
        "trainerProposal": "ಪ್ರಸ್ತಾಪ JSON",
        "trainerOk": "ಮಾನ್ಯ",
        "trainerFail": "ಅಮಾನ್ಯ",
        "trainerSend": "ಕಳುಹಿಸು",
        "trainerNeedLlm": "ಮೊದಲು Settingsನಲ್ಲಿ LLM ಹೊಂದಿಸಿ. Klarಗೆ ಇನ್ನೊಂದು Home Assistant ಸಂಭಾಷಣೆ ಏಕೀಕರಣ ಬೇಕಿಲ್ಲ.",
        "trainerOpenSettings": "Settings ತೆರೆ",
        "trainerApplyHouse": "House ಅನ್ವಯಿಸು",
        "trainerApplyMatch": "Match ಅನ್ವಯಿಸು",
        "trainerApplyLanguage": "Language ಅನ್ವಯಿಸು",
        "trainerAdvanced": "ಸುಧಾರಿತ JSON",
        "trainerStreaming": "ಸ್ಟ್ರೀಮಿಂಗ್…",
    },
    "ml": {
        "engineHint": "ശബ്ദവും ഭാഷകളും LLM-ഉം ഇവിടെയാണ്. Home Assistant എഞ്ചിൻ മാത്രം ബന്ധിപ്പിക്കുന്നു.",
        "languageHint": "ശൂന്യമായ ലിസ്റ്റ് ഓരോ സമാഹരിച്ച Assist locale-ഉം സജീവമായി നിലനിർത്തുന്നു. ഒരു പായ്ക്ക് പിൻ ചെയ്യുക എന്നതാണ് സാധാരണ വീട്.",
        "personalityHa": "ശബ്ദവും ഭാഷകളും LLM-ഉം ഈ Settings പേജിലാണ്.",
        "assistLanguages": "Assist ഭാഷകൾ",
        "assistLanguagesHint": "Klar ഏതൊക്കെ പായ്ക്കുകൾ വിശകലനം ചെയ്യാം. ഉപഗ്രഹം ഇപ്പോഴും ഓരോ അഭ്യർത്ഥനയ്ക്കും ഒരു ഭാഷ അയയ്ക്കുന്നു. ശൂന്യം = എല്ലാ സമാഹരിച്ച locale.",
        "allAssistLanguages": "ഓരോ സമാഹരിച്ച locale",
        "pinLanguage": "ഒരു പായ്ക്ക് പിൻ ചെയ്യുക",
        "voice": "ശബ്ദം",
        "voiceHint": "വ്യക്തിത്വവും സംസാരിച്ച മറുപടികളും. Assist ഇത് എഞ്ചിനിൽ നിന്ന് വായിക്കുന്നു, Home Assistant ഓപ്ഷനുകളിൽ നിന്നല്ല.",
        "extraPrompt": "അധിക പ്രോംപ്റ്റ്",
        "extraPromptHint": "പായ്ക്ക് വ്യക്തിത്വത്തിന് മുകളിലുള്ള ഐച്ഛിക വരി. വീടിന് സ്വന്തം നിയമം വേണ്ടെങ്കിൽ ശൂന്യമായി വിടുക.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM മിനുക്കൽ",
        "refineSpeechHint": "Klar ഉപകരണങ്ങൾ നിയന്ത്രിക്കുന്നത് തുടരുന്നു. എഞ്ചിൻ LLM പിന്നീട് പൂർത്തിയായ NLU മറുപടികൾ ഈ ശബ്ദത്തിൽ എഴുതുന്നു.",
        "quietAck": "ചെറിയ സ്ഥിരീകരണം",
        "quietAckHint": "ലളിതമായ വിളക്കോ സ്വിച്ചോ ഓൺ/ഓഫിൽ TTS ഒഴിവാക്കി ഉപഗ്രഹത്തിൽ മണി മുഴക്കുക.",
        "calendarLlm": "കലണ്ടർ LLM വഴി",
        "calendarLlmHint": "Klar കലണ്ടർ വായിക്കുന്നത് തുടരുന്നു. ഓൺ: LLM സംഭവങ്ങൾ പറയുന്നു. ഓഫ്: Klar ലിസ്റ്റ് പറയുന്നു.",
        "allowLlmTools": "ചാറ്റിൽ Assist ഉപകരണങ്ങൾ അനുവദിക്കുക",
        "allowLlmToolsHint": "സ്ഥിരമായി ഓഫ്. ഓൺ: ചാറ്റ് മോഡലിന് Home Assistant നിയന്ത്രിക്കാം. ഓഫ്: ഉപകരണങ്ങളുണ്ടെങ്കിൽ Klar ആ ഏജന്റിനെ ഒഴിവാക്കുന്നു.",
        "missTitle": "Klar തെറ്റുമ്പോൾ",
        "missHint": "നിശ്ചിത നിരാകരണത്തിന് ശേഷമുള്ള ഐച്ഛിക പാളികൾ. ഒന്നും parse-ൽ മോഡൽ വയ്ക്കുന്നില്ല.",
        "operatorChrome": "ഈ സ്ക്രീൻ",
        "operatorChromeHint": "ഓപ്പറേറ്റർമാർക്കുള്ള തീമും ഇന്റർഫേസ് ഭാഷയും. Assist അല്ല.",
        "haGlueHint": "Home Assistant Configure-ന് എഞ്ചിൻ URL, ടോക്കൺ, ചാനൽ, ഐച്ഛിക ബാക്കി സംഭാഷണ ഏജന്റ് മാത്രം വേണം. ശബ്ദവും LLM-ഉം ഇവിടെ നിൽക്കുന്നു.",
        "settingsGuide": "ഈ മൂന്ന് സജ്ജമാക്കി പിന്നെ വീട് മാപ്പ് ചെയ്യുക.",
        "settingsGuideVoice": "ശബ്ദം",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist ഭാഷ",
        "appearanceDark": "ഇരുണ്ടത്",
        "appearanceLight": "വെളിച്ചം",
        "setupReplay": "സെറ്റപ്പ് വീണ്ടും",
        "personalityDefault": "സാധാരണ",
        "personalityButler": "Butler",
        "personalityLocker": "അയഞ്ഞത്",
        "personalityFuersorglich": "ശ്രദ്ധയുള്ള",
        "personalityParty": "പാർട്ടി",
        "personalityGrantig": "ദേഷ്യക്കാരൻ",
        "personalitySarkastisch": "പരിഹാസം",
        "personalityPirat": "കടൽക്കൊള്ളക്കാരൻ",
        "personalityHippie": "ഹിപ്പി",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ഓപ്പറേറ്റർ ഭാഷ",
        "operatorLanguageHint": "ഈ ആപ്പ് മാത്രം. ഇവിടെ സൂക്ഷിച്ചത്, അല്ലെങ്കിൽ ആദ്യ സേവിന് മുമ്പ് KLAR_UI_LOCALE. Assist അല്ല, Home Assistant പ്രൊഫൈൽ അല്ല.",
        "nluRag": "തെറ്റുമ്പോൾ വീട്ടിന്റെ സന്ദർഭം",
        "modeFull": "ഉപകരണങ്ങൾ പരിഹരിക്കുക",
        "modeContext": "മുറികൾ മാത്രം",
        "inLab": "ലാബിൽ",
        "undoLastCommand": "അവസാന കമാൻഡ് പഴയപടിയാക്കുക",
        "applyDone": "{count} മുറി നിർദേശങ്ങൾ പ്രയോഗിച്ചു",
        "applyUndone": "മുറി നിർദേശങ്ങൾ പഴയപടിയാക്കി",
        "applyUndoFailed": "മുറി നിർദേശങ്ങൾ പഴയപടിയാക്കാനായില്ല",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-അനുയോജ്യമായ എൻഡ്‌പോയിന്റുമായി സംസാരിക്കുന്നു. Assist ചാറ്റും പരിശീലകനും ഒരേ config ഉപയോഗിക്കുന്നു. Home Assistant-ൽ OpenAI അല്ലെങ്കിൽ Ollama സംയോജനം വേണ്ട.",
        "llmBaseUrl": "അടിസ്ഥാന URL",
        "llmModel": "മോഡൽ",
        "llmApiKey": "API കീ",
        "llmApiKeyHint": "സൂക്ഷിച്ച കീ നിലനിർത്താൻ ശൂന്യമായി വിടുക. Ollama ശൂന്യമായി നിൽക്കാം.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ക്രമീകരിച്ചു",
        "llmNotConfigured": "ക്രമീകരിച്ചിട്ടില്ല",
        "llmClear": "മായ്ക്കുക",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "പരിശീലകൻ",
        "trainerForLane": "ഈ ലെയ്നിന്റെ പരിശീലകൻ",
        "trainerHint": "Klar Rust-ൽ OpenAI-അനുയോജ്യമായ മോഡൽ വിളിക്കുന്നു. ചാറ്റ്, പരിശോധിക്കുക, പിന്നെ ലെയൻ അനുസരിച്ച് പ്രയോഗിക്കുക. Home Assistant LLM സംയോജനം വേണ്ട. വിപുലമായ JSON ഡീബഗിനാണ്.",
        "trainerContext": "സന്ദർഭം",
        "trainerValidate": "പരിശോധിക്കുക",
        "trainerApply": "പ്രയോഗിക്കുക",
        "trainerProposal": "നിർദേശ JSON",
        "trainerOk": "സാധുവാണ്",
        "trainerFail": "അസാധു",
        "trainerSend": "അയയ്ക്കുക",
        "trainerNeedLlm": "ആദ്യം Settings-ൽ LLM ക്രമീകരിക്കുക. Klar-ന് മറ്റൊരു Home Assistant സംഭാഷണ സംയോജനം വേണ്ട.",
        "trainerOpenSettings": "Settings തുറക്കുക",
        "trainerApplyHouse": "House പ്രയോഗിക്കുക",
        "trainerApplyMatch": "Match പ്രയോഗിക്കുക",
        "trainerApplyLanguage": "Language പ്രയോഗിക്കുക",
        "trainerAdvanced": "വിപുലമായ JSON",
        "trainerStreaming": "സ്ട്രീമിംഗ്…",
    },
    "mr": {
        "engineHint": "आवाज, भाषा आणि LLM इथे आहेत. Home Assistant फक्त इंजिन जोडतो.",
        "languageHint": "रिकामी यादी प्रत्येक संकलित Assist locale चालू ठेवते. एक पॅक पिन करणे हे सामान्य घर आहे.",
        "personalityHa": "आवाज, भाषा आणि LLM या Settings पानावर आहेत.",
        "assistLanguages": "Assist भाषा",
        "assistLanguagesHint": "Klar कोणते पॅक विश्लेषित करू शकतो. उपग्रह तरीही प्रत्येक विनंतीवर एक भाषा पाठवतो. रिकामा = सर्व संकलित locale.",
        "allAssistLanguages": "प्रत्येक संकलित locale",
        "pinLanguage": "एक पॅक पिन करा",
        "voice": "आवाज",
        "voiceHint": "व्यक्तिमत्त्व आणि बोललेली उत्तरे. Assist हे इंजिनातून वाचतो, Home Assistant पर्यायांतून नाही.",
        "extraPrompt": "अतिरिक्त प्रॉम्प्ट",
        "extraPromptHint": "पॅक व्यक्तिमत्त्वावर वैकल्पिक ओळ. घराला स्वतःचा नियम नको असेल तर रिकामी ठेवा.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM सुधारणा",
        "refineSpeechHint": "Klar अजून उपकरणे नियंत्रित करतो. इंजिन LLM नंतर पूर्ण NLU उत्तरे या आवाजात लिहितो.",
        "quietAck": "थोडक्यात पुष्टी",
        "quietAckHint": "साध्या दिव्यावर किंवा स्विच चालू/बंद वर TTS सोडा आणि उपग्रहावर घंटा वाजवा.",
        "calendarLlm": "कॅलेंडर LLM द्वारे",
        "calendarLlmHint": "Klar कॅलेंडर वाचत राहतो. चालू: LLM घटना बोलतो. बंद: Klar यादी बोलतो.",
        "allowLlmTools": "चॅटवर Assist साधने परवानगी द्या",
        "allowLlmToolsHint": "मूळतः बंद. चालू: चॅट मॉडेल Home Assistant नियंत्रित करू शकतो. बंद: साधने असतील तर Klar तो एजंट सोडतो.",
        "missTitle": "जेव्हा Klar चुकतो",
        "missHint": "निश्चित नकारानंतर वैकल्पिक थर. कोणीही parse वर मॉडेल ठेवत नाही.",
        "operatorChrome": "ही स्क्रीन",
        "operatorChromeHint": "ऑपरेटरसाठी थीम आणि इंटरफेस भाषा. Assist नाही.",
        "haGlueHint": "Home Assistant Configure ला फक्त इंजिन URL, टोकन, चॅनेल आणि वैकल्पिक उरलेला संभाषण एजंट हवा. आवाज आणि LLM इथे राहतात.",
        "settingsGuide": "हे तीन सेट करा, मग घर नकाशा करा.",
        "settingsGuideVoice": "आवाज",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist भाषा",
        "appearanceDark": "गडद",
        "appearanceLight": "फिकट",
        "setupReplay": "सेटअप पुन्हा चालवा",
        "personalityDefault": "सामान्य",
        "personalityButler": "Butler",
        "personalityLocker": "सैल",
        "personalityFuersorglich": "काळजी घेणारा",
        "personalityParty": "पार्टी",
        "personalityGrantig": "चिडचिडा",
        "personalitySarkastisch": "उपहासात्मक",
        "personalityPirat": "समुद्री डाकू",
        "personalityHippie": "हिप्पी",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ऑपरेटर भाषा",
        "operatorLanguageHint": "फक्त हे अॅप. इथे जतन, किंवा पहिल्या जतनापूर्वी KLAR_UI_LOCALE. Assist नाही, Home Assistant प्रोफाइल नाही.",
        "nluRag": "चुकीवर घराचा संदर्भ",
        "modeFull": "उपकरणे सोडवा",
        "modeContext": "फक्त खोल्या",
        "inLab": "प्रयोगशाळेत",
        "undoLastCommand": "शेवटची आज्ञा पूर्ववत",
        "applyDone": "{count} खोली सूचना लागू",
        "applyUndone": "खोली सूचना पूर्ववत",
        "applyUndoFailed": "खोली सूचना पूर्ववत करता आल्या नाहीत",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-सुसंगत एंडपॉइंटशी बोलतो. Assist चॅट आणि प्रशिक्षक तोच config वापरतात. Home Assistant मध्ये OpenAI किंवा Ollama एकत्रीकरण नको.",
        "llmBaseUrl": "मूळ URL",
        "llmModel": "मॉडेल",
        "llmApiKey": "API की",
        "llmApiKeyHint": "साठवलेली की ठेवण्यासाठी रिकामी ठेवा. Ollama रिकामी राहू शकते.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "संरचित",
        "llmNotConfigured": "असंरचित",
        "llmClear": "साफ करा",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "प्रशिक्षक",
        "trainerForLane": "या लेनचा प्रशिक्षक",
        "trainerHint": "Klar Rust मध्ये OpenAI-सुसंगत मॉडेल बोलावतो. चॅट, तपासा, मग लेननुसार लागू करा. Home Assistant LLM एकत्रीकरण नको. प्रगत JSON डीबगसाठी आहे.",
        "trainerContext": "संदर्भ",
        "trainerValidate": "तपासा",
        "trainerApply": "लागू करा",
        "trainerProposal": "प्रस्ताव JSON",
        "trainerOk": "वैध",
        "trainerFail": "अवैध",
        "trainerSend": "पाठवा",
        "trainerNeedLlm": "आधी Settings मध्ये LLM सेट करा. Klar ला दुसरे Home Assistant संभाषण एकत्रीकरण नको.",
        "trainerOpenSettings": "Settings उघडा",
        "trainerApplyHouse": "House लागू करा",
        "trainerApplyMatch": "Match लागू करा",
        "trainerApplyLanguage": "Language लागू करा",
        "trainerAdvanced": "प्रगत JSON",
        "trainerStreaming": "स्ट्रीमिंग…",
    },
    "ta": {
        "engineHint": "குரல், மொழிகள், LLM இங்கே உள்ளன. Home Assistant இயந்திரத்தை மட்டும் இணைக்கிறது.",
        "languageHint": "காலி பட்டியல் ஒவ்வொரு தொகுக்கப்பட்ட Assist locale-ஐயும் இயக்கத்தில் வைக்கும். ஒரு பொதியை பின் செய்வதே வழக்கமான வீடு.",
        "personalityHa": "குரல், மொழிகள், LLM இந்த Settings பக்கத்தில் உள்ளன.",
        "assistLanguages": "Assist மொழிகள்",
        "assistLanguagesHint": "Klar எந்த பொதிகளை பகுக்கலாம். செயற்கைக்கோள் இன்னும் கோரிக்கைக்கு ஒரு மொழி அனுப்பும். காலி = அனைத்து தொகுக்கப்பட்ட locale.",
        "allAssistLanguages": "ஒவ்வொரு தொகுக்கப்பட்ட locale",
        "pinLanguage": "ஒரு பொதியை பின் செய்",
        "voice": "குரல்",
        "voiceHint": "ஆளுமை மற்றும் பேசும் பதில்கள். Assist இதை இயந்திரத்திலிருந்து படிக்கும், Home Assistant விருப்பங்களிலிருந்து அல்ல.",
        "extraPrompt": "கூடுதல் தூண்டல்",
        "extraPromptHint": "பொதி ஆளுமைக்கு மேல் விருப்ப வரி. வீட்டுக்கு சொந்த விதி தேவையில்லை என்றால் காலியாக விடு.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM மெருகேற்றம்",
        "refineSpeechHint": "Klar இன்னும் சாதனங்களை கட்டுப்படுத்துகிறது. இயந்திர LLM பிறகு முடிந்த NLU பதில்களை இந்த குரலில் எழுதும்.",
        "quietAck": "குறுகிய உறுதி",
        "quietAckHint": "எளிய விளக்கு அல்லது சுவிட்ச் ஆன்/ஆஃப்பில் TTS தவிர்த்து செயற்கைக்கோளில் மணி அடிக்கவும்.",
        "calendarLlm": "நாட்காட்டி LLM வழியாக",
        "calendarLlmHint": "Klar நாட்காட்டியை தொடர்ந்து படிக்கும். ஆன்: LLM நிகழ்வுகளை சொல்லும். ஆஃப்: Klar பட்டியலை சொல்லும்.",
        "allowLlmTools": "அரட்டையில் Assist கருவிகளை அனுமதி",
        "allowLlmToolsHint": "இயல்பாக ஆஃப். ஆன்: அரட்டை மாதிரி Home Assistant கட்டுப்படுத்தலாம். ஆஃப்: கருவிகள் இருந்தால் Klar அந்த முகவரை தவிர்க்கும்.",
        "missTitle": "Klar தவறும்போது",
        "missHint": "உறுதியான மறுப்புக்கு பின் விருப்ப அடுக்குகள். எதுவும் parse-இல் மாதிரியை வைக்காது.",
        "operatorChrome": "இந்த திரை",
        "operatorChromeHint": "இயக்குநர்களுக்கான தீம் மற்றும் இடைமுக மொழி. Assist அல்ல.",
        "haGlueHint": "Home Assistant Configure-க்கு இயந்திர URL, டோக்கன், சேனல், விருப்ப எஞ்சிய உரையாடல் முகவர் மட்டுமே வேண்டும். குரலும் LLM-உம் இங்கே இருக்கும்.",
        "settingsGuide": "இந்த மூன்றையும் அமைத்து பிறகு வீட்டை வரைபடமாக்கு.",
        "settingsGuideVoice": "குரல்",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist மொழி",
        "appearanceDark": "இருள்",
        "appearanceLight": "ஒளி",
        "setupReplay": "அமைப்பை மீண்டும் இயக்கு",
        "personalityDefault": "சாதாரணம்",
        "personalityButler": "Butler",
        "personalityLocker": "தளர்வு",
        "personalityFuersorglich": "அக்கறை",
        "personalityParty": "விருந்து",
        "personalityGrantig": "முணுமுணுப்பு",
        "personalitySarkastisch": "ஏளனம்",
        "personalityPirat": "கடற்கொள்ளையர்",
        "personalityHippie": "ஹிப்பி",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "இயக்குநர் மொழி",
        "operatorLanguageHint": "இந்த செயலி மட்டும். இங்கே சேமிக்கப்பட்டது, அல்லது முதல் சேமிப்புக்கு முன் KLAR_UI_LOCALE. Assist அல்ல, Home Assistant சுயவிவரம் அல்ல.",
        "nluRag": "தவறும்போது வீட்டு சூழல்",
        "modeFull": "சாதனங்களை தீர்க்க",
        "modeContext": "அறைகள் மட்டும்",
        "inLab": "ஆய்வகத்தில்",
        "undoLastCommand": "கடைசி கட்டளையை செயல்தவிர்",
        "applyDone": "{count} அறை பரிந்துரைகள் பயன்படுத்தப்பட்டன",
        "applyUndone": "அறை பரிந்துரைகள் செயல்தவிர்க்கப்பட்டன",
        "applyUndoFailed": "அறை பரிந்துரைகளை செயல்தவிர்க்க முடியவில்லை",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-இணக்க முனையத்துடன் பேசுகிறது. Assist அரட்டையும் பயிற்சியாளரும் அதே config பயன்படுத்துவர். Home Assistant-இல் OpenAI அல்லது Ollama ஒருங்கிணைப்பு தேவையில்லை.",
        "llmBaseUrl": "அடிப்படை URL",
        "llmModel": "மாதிரி",
        "llmApiKey": "API திறவுகோல்",
        "llmApiKeyHint": "சேமித்த திறவுகோலை வைக்க காலியாக விடு. Ollama காலியாக இருக்கலாம்.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "அமைக்கப்பட்டது",
        "llmNotConfigured": "அமைக்கப்படவில்லை",
        "llmClear": "அழி",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "பயிற்சியாளர்",
        "trainerForLane": "இந்த பாதைக்கான பயிற்சியாளர்",
        "trainerHint": "Klar Rust-இல் OpenAI-இணக்க மாதிரியை அழைக்கிறது. அரட்டை, சரிபார், பிறகு பாதைக்கு ஏற்ப பயன்படுத்து. Home Assistant LLM ஒருங்கிணைப்பு தேவையில்லை. மேம்பட்ட JSON பிழைதிருத்தத்திற்கு.",
        "trainerContext": "சூழல்",
        "trainerValidate": "சரிபார்",
        "trainerApply": "பயன்படுத்து",
        "trainerProposal": "முன்மொழிவு JSON",
        "trainerOk": "செல்லுபடியானது",
        "trainerFail": "செல்லாது",
        "trainerSend": "அனுப்பு",
        "trainerNeedLlm": "முதலில் Settings-இல் LLM அமை. Klar-க்கு வேறு Home Assistant உரையாடல் ஒருங்கிணைப்பு தேவையில்லை.",
        "trainerOpenSettings": "Settings திற",
        "trainerApplyHouse": "House பயன்படுத்து",
        "trainerApplyMatch": "Match பயன்படுத்து",
        "trainerApplyLanguage": "Language பயன்படுத்து",
        "trainerAdvanced": "மேம்பட்ட JSON",
        "trainerStreaming": "ஒளிபரப்பு…",
    },
    "te": {
        "engineHint": "వాయిస్, భాషలు, LLM ఇక్కడ ఉన్నాయి. Home Assistant కేవలం ఇంజిన్‌ను కలుపుతుంది.",
        "languageHint": "ఖాళీ జాబితా ప్రతి సంకలిత Assist localeని చురుకుగా ఉంచుతుంది. ఒక ప్యాక్ పిన్ చేయడం సాధారణ ఇల్లు.",
        "personalityHa": "వాయిస్, భాషలు, LLM ఈ Settings పేజీలో ఉన్నాయి.",
        "assistLanguages": "Assist భాషలు",
        "assistLanguagesHint": "Klar ఏ ప్యాక్‌లను విశ్లేషించవచ్చు. ఉపగ్రహం ఇంకా ప్రతి అభ్యర్థనకు ఒక భాష పంపుతుంది. ఖాళీ = అన్ని సంకలిత locale.",
        "allAssistLanguages": "ప్రతి సంకలిత locale",
        "pinLanguage": "ఒక ప్యాక్ పిన్ చేయి",
        "voice": "వాయిస్",
        "voiceHint": "వ్యక్తిత్వం మరియు మాట్లాడిన సమాధానాలు. Assist దీన్ని ఇంజిన్ నుండి చదువుతుంది, Home Assistant ఎంపికల నుండి కాదు.",
        "extraPrompt": "అదనపు ప్రాంప్ట్",
        "extraPromptHint": "ప్యాక్ వ్యక్తిత్వం పైన ఐచ్ఛిక పంక్తి. ఇంటికి సొంత నియమం అవసరం లేకపోతే ఖాళీగా ఉంచు.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM మెరుగుదల",
        "refineSpeechHint": "Klar ఇంకా పరికరాలను నియంత్రిస్తుంది. ఇంజిన్ LLM తర్వాత పూర్తయిన NLU సమాధానాలను ఈ వాయిస్‌లో రాస్తుంది.",
        "quietAck": "చిన్న నిర్ధారణ",
        "quietAckHint": "సాధారణ లైట్ లేదా స్విచ్ ఆన్/ఆఫ్‌లో TTS దాటవేసి ఉపగ్రహంపై గంట వాయించు.",
        "calendarLlm": "క్యాలెండర్ LLM ద్వారా",
        "calendarLlmHint": "Klar క్యాలెండర్ చదవడం కొనసాగిస్తుంది. ఆన్: LLM ఈవెంట్‌లు చెబుతుంది. ఆఫ్: Klar జాబితా చెబుతుంది.",
        "allowLlmTools": "చాట్‌లో Assist సాధనాలు అనుమతించు",
        "allowLlmToolsHint": "డిఫాల్ట్‌గా ఆఫ్. ఆన్: చాట్ మోడల్ Home Assistant నియంత్రించవచ్చు. ఆఫ్: సాధనాలు ఉంటే Klar ఆ ఏజెంట్‌ను దాటవేస్తుంది.",
        "missTitle": "Klar తప్పినప్పుడు",
        "missHint": "నిర్ణయాత్మక తిరస్కరణ తర్వాత ఐచ్ఛిక పొరలు. ఏదీ parseపై మోడల్ పెట్టదు.",
        "operatorChrome": "ఈ స్క్రీన్",
        "operatorChromeHint": "ఆపరేటర్ల కోసం థీమ్ మరియు ఇంటర్‌ఫేస్ భాష. Assist కాదు.",
        "haGlueHint": "Home Assistant Configureకు ఇంజిన్ URL, టోకెన్, ఛానెల్, ఐచ్ఛిక మిగిలిన సంభాషణ ఏజెంట్ మాత్రమే కావాలి. వాయిస్ మరియు LLM ఇక్కడే ఉంటాయి.",
        "settingsGuide": "ఈ మూడింటిని సెట్ చేసి, తర్వాత ఇల్లు మ్యాప్ చేయి.",
        "settingsGuideVoice": "వాయిస్",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist భాష",
        "appearanceDark": "ముదురు",
        "appearanceLight": "లేత",
        "setupReplay": "సెటప్ మళ్లీ ఆడు",
        "personalityDefault": "సాధారణం",
        "personalityButler": "Butler",
        "personalityLocker": "సడలింపు",
        "personalityFuersorglich": "శ్రద్ధగల",
        "personalityParty": "పార్టీ",
        "personalityGrantig": "చిరాకు",
        "personalitySarkastisch": "వ్యంగ్యం",
        "personalityPirat": "సముద్రదొంగ",
        "personalityHippie": "హిప్పీ",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ఆపరేటర్ భాష",
        "operatorLanguageHint": "ఈ యాప్ మాత్రమే. ఇక్కడ సేవ్, లేదా మొదటి సేవ్ ముందు KLAR_UI_LOCALE. Assist కాదు, Home Assistant ప్రొఫైల్ కాదు.",
        "nluRag": "తప్పినప్పుడు ఇంటి సందర్భం",
        "modeFull": "పరికరాలు పరిష్కరించు",
        "modeContext": "గదులు మాత్రమే",
        "inLab": "ల్యాబ్‌లో",
        "undoLastCommand": "చివరి ఆదేశం రద్దు",
        "applyDone": "{count} గది సూచనలు వర్తింపజేశారు",
        "applyUndone": "గది సూచనలు రద్దు",
        "applyUndoFailed": "గది సూచనలు రద్దు కాలేదు",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-అనుకూల ఎండ్‌పాయింట్‌తో మాట్లాడుతుంది. Assist చాట్ మరియు శిక్షకుడు అదే config వాడతారు. Home Assistantలో OpenAI లేదా Ollama ఏకీకరణ అవసరం లేదు.",
        "llmBaseUrl": "బేస్ URL",
        "llmModel": "మోడల్",
        "llmApiKey": "API కీ",
        "llmApiKeyHint": "నిల్వ కీ ఉంచడానికి ఖాళీగా ఉంచు. Ollama ఖాళీగా ఉండవచ్చు.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ఆకృతీకరించబడింది",
        "llmNotConfigured": "ఆకృతీకరించలేదు",
        "llmClear": "తుడుచు",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "శిక్షకుడు",
        "trainerForLane": "ఈ లేన్ శిక్షకుడు",
        "trainerHint": "Klar Rustలో OpenAI-అనుకూల మోడల్ పిలుస్తుంది. చాట్, ధృవీకరించు, తర్వాత లేన్ ప్రకారం వర్తింపజేయి. Home Assistant LLM ఏకీకరణ అవసరం లేదు. అధునాతన JSON డీబగ్ కోసం.",
        "trainerContext": "సందర్భం",
        "trainerValidate": "ధృవీకరించు",
        "trainerApply": "వర్తింపజేయి",
        "trainerProposal": "ప్రతిపాదన JSON",
        "trainerOk": "చెల్లుబాటు",
        "trainerFail": "చెల్లదు",
        "trainerSend": "పంపు",
        "trainerNeedLlm": "ముందు Settingsలో LLM సెట్ చేయి. Klarకు మరో Home Assistant సంభాషణ ఏకీకరణ అవసరం లేదు.",
        "trainerOpenSettings": "Settings తెరువు",
        "trainerApplyHouse": "House వర్తింపజేయి",
        "trainerApplyMatch": "Match వర్తింపజేయి",
        "trainerApplyLanguage": "Language వర్తింపజేయి",
        "trainerAdvanced": "అధునాతన JSON",
        "trainerStreaming": "స్ట్రీమింగ్…",
    },
    "pa": {
        "engineHint": "ਆਵਾਜ਼, ਭਾਸ਼ਾਵਾਂ ਅਤੇ LLM ਇੱਥੇ ਹਨ। Home Assistant ਸਿਰਫ਼ ਇੰਜਣ ਜੋੜਦਾ ਹੈ।",
        "languageHint": "ਖਾਲੀ ਸੂਚੀ ਹਰ ਸੰਕਲਿਤ Assist locale ਚਾਲੂ ਰੱਖਦੀ ਹੈ। ਇੱਕ ਪੈਕ ਪਿੰਨ ਕਰਨਾ ਆਮ ਘਰ ਹੈ।",
        "personalityHa": "ਆਵਾਜ਼, ਭਾਸ਼ਾਵਾਂ ਅਤੇ LLM ਇਸ Settings ਪੰਨੇ ਤੇ ਹਨ।",
        "assistLanguages": "Assist ਭਾਸ਼ਾਵਾਂ",
        "assistLanguagesHint": "Klar ਕਿਹੜੇ ਪੈਕ ਪਾਰਸ ਕਰ ਸਕਦਾ ਹੈ। ਉਪਗ੍ਰਹਿ ਫਿਰ ਵੀ ਹਰ ਬੇਨਤੀ ਤੇ ਇੱਕ ਭਾਸ਼ਾ ਭੇਜਦਾ ਹੈ। ਖਾਲੀ = ਸਾਰੀਆਂ ਸੰਕਲਿਤ locale।",
        "allAssistLanguages": "ਹਰ ਸੰਕਲਿਤ locale",
        "pinLanguage": "ਇੱਕ ਪੈਕ ਪਿੰਨ ਕਰੋ",
        "voice": "ਆਵਾਜ਼",
        "voiceHint": "ਸ਼ਖਸੀਅਤ ਅਤੇ ਬੋਲੇ ਜਵਾਬ। Assist ਇਹ ਇੰਜਣ ਤੋਂ ਪੜ੍ਹਦਾ ਹੈ, Home Assistant ਚੋਣਾਂ ਤੋਂ ਨਹੀਂ।",
        "extraPrompt": "ਵਾਧੂ ਪ੍ਰਾਂਪਟ",
        "extraPromptHint": "ਪੈਕ ਸ਼ਖਸੀਅਤ ਉੱਤੇ ਵਿਕਲਪਿਕ ਲਾਈਨ। ਘਰ ਨੂੰ ਆਪਣਾ ਨਿਯਮ ਨਾ ਚਾਹੀਦਾ ਹੋਵੇ ਤਾਂ ਖਾਲੀ ਛੱਡੋ।",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM ਸੁਧਾਰ",
        "refineSpeechHint": "Klar ਅਜੇ ਵੀ ਡਿਵਾਈਸਾਂ ਨੂੰ ਕੰਟਰੋਲ ਕਰਦਾ ਹੈ। ਇੰਜਣ LLM ਫਿਰ ਮੁਕੰਮਲ NLU ਜਵਾਬ ਇਸ ਆਵਾਜ਼ ਵਿੱਚ ਲਿਖਦਾ ਹੈ।",
        "quietAck": "ਛੋਟੀ ਪੁਸ਼ਟੀ",
        "quietAckHint": "ਸਧਾਰਨ ਲਾਈਟ ਜਾਂ ਸਵਿੱਚ ਆਨ/ਆਫ ਤੇ TTS ਛੱਡੋ ਅਤੇ ਉਪਗ੍ਰਹਿ ਤੇ ਘੰਟੀ ਵਜਾਓ।",
        "calendarLlm": "ਕੈਲੰਡਰ LLM ਰਾਹੀਂ",
        "calendarLlmHint": "Klar ਕੈਲੰਡਰ ਪੜ੍ਹਦਾ ਰਹਿੰਦਾ ਹੈ। ਆਨ: LLM ਘਟਨਾਵਾਂ ਬੋਲਦਾ ਹੈ। ਆਫ: Klar ਸੂਚੀ ਬੋਲਦਾ ਹੈ।",
        "allowLlmTools": "ਚੈਟ ਤੇ Assist ਸੰਦ ਇਜਾਜ਼ਤ ਦਿਓ",
        "allowLlmToolsHint": "ਮੂਲ ਤੌਰ ਤੇ ਆਫ। ਆਨ: ਚੈਟ ਮਾਡਲ Home Assistant ਕੰਟਰੋਲ ਕਰ ਸਕਦਾ ਹੈ। ਆਫ: ਸੰਦ ਹੋਣ ਤੇ Klar ਉਸ ਏਜੰਟ ਨੂੰ ਛੱਡਦਾ ਹੈ।",
        "missTitle": "ਜਦੋਂ Klar ਚੂਕੇ",
        "missHint": "ਨਿਸ਼ਚਿਤ ਇਨਕਾਰ ਤੋਂ ਬਾਅਦ ਵਿਕਲਪਿਕ ਪਰਤਾਂ। ਕੋਈ parse ਤੇ ਮਾਡਲ ਨਹੀਂ ਰੱਖਦੀ।",
        "operatorChrome": "ਇਹ ਸਕਰੀਨ",
        "operatorChromeHint": "ਆਪਰੇਟਰਾਂ ਲਈ ਥੀਮ ਅਤੇ ਇੰਟਰਫੇਸ ਭਾਸ਼ਾ। Assist ਨਹੀਂ।",
        "haGlueHint": "Home Assistant Configure ਨੂੰ ਸਿਰਫ਼ ਇੰਜਣ URL, ਟੋਕਨ, ਚੈਨਲ ਅਤੇ ਵਿਕਲਪਿਕ ਬਚਿਆ ਗੱਲਬਾਤ ਏਜੰਟ ਚਾਹੀਦਾ ਹੈ। ਆਵਾਜ਼ ਅਤੇ LLM ਇੱਥੇ ਰਹਿੰਦੇ ਹਨ।",
        "settingsGuide": "ਇਹ ਤਿੰਨ ਸੈੱਟ ਕਰੋ, ਫਿਰ ਘਰ ਨਕਸ਼ਾ ਕਰੋ।",
        "settingsGuideVoice": "ਆਵਾਜ਼",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist ਭਾਸ਼ਾ",
        "appearanceDark": "ਗੂੜ੍ਹਾ",
        "appearanceLight": "ਹਲਕਾ",
        "setupReplay": "ਸੈੱਟਅੱਪ ਮੁੜ ਚਲਾਓ",
        "personalityDefault": "ਆਮ",
        "personalityButler": "Butler",
        "personalityLocker": "ਆਰਾਮਦਾਇਕ",
        "personalityFuersorglich": "ਦੇਖਭਾਲ ਵਾਲਾ",
        "personalityParty": "ਪਾਰਟੀ",
        "personalityGrantig": "ਚਿੜਚਿੜਾ",
        "personalitySarkastisch": "ਵਿਅੰਗ",
        "personalityPirat": "ਸਮੁੰਦਰੀ ਡਾਕੂ",
        "personalityHippie": "ਹਿਪੀ",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ਆਪਰੇਟਰ ਭਾਸ਼ਾ",
        "operatorLanguageHint": "ਸਿਰਫ਼ ਇਹ ਐਪ। ਇੱਥੇ ਸੰਭਾਲੀ, ਜਾਂ ਪਹਿਲੀ ਸੇਵ ਤੋਂ ਪਹਿਲਾਂ KLAR_UI_LOCALE। Assist ਨਹੀਂ, Home Assistant ਪ੍ਰੋਫਾਈਲ ਨਹੀਂ।",
        "nluRag": "ਚੂਕ ਤੇ ਘਰ ਦਾ ਸੰਦਰਭ",
        "modeFull": "ਡਿਵਾਈਸ ਹੱਲ ਕਰੋ",
        "modeContext": "ਸਿਰਫ਼ ਕਮਰੇ",
        "inLab": "ਲੈਬ ਵਿੱਚ",
        "undoLastCommand": "ਆਖਰੀ ਹੁਕਮ ਵਾਪਸ",
        "applyDone": "{count} ਕਮਰੇ ਦੀਆਂ ਸੁਝਾਵਾਂ ਲਾਗੂ",
        "applyUndone": "ਕਮਰੇ ਦੀਆਂ ਸੁਝਾਵਾਂ ਵਾਪਸ",
        "applyUndoFailed": "ਕਮਰੇ ਦੀਆਂ ਸੁਝਾਵਾਂ ਵਾਪਸ ਨਹੀਂ ਹੋ ਸਕੀਆਂ",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-ਅਨੁਕੂਲ ਐਂਡਪੁਆਇੰਟ ਨਾਲ ਗੱਲ ਕਰਦਾ ਹੈ। Assist ਚੈਟ ਅਤੇ ਟ੍ਰੇਨਰ ਇਹੀ config ਵਰਤਦੇ ਹਨ। Home Assistant ਵਿੱਚ OpenAI ਜਾਂ Ollama ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਲੋੜੀਂਦੀ ਨਹੀਂ।",
        "llmBaseUrl": "ਬੇਸ URL",
        "llmModel": "ਮਾਡਲ",
        "llmApiKey": "API ਕੁੰਜੀ",
        "llmApiKeyHint": "ਸੰਭਾਲੀ ਕੁੰਜੀ ਰੱਖਣ ਲਈ ਖਾਲੀ ਛੱਡੋ। Ollama ਖਾਲੀ ਰਹਿ ਸਕਦਾ ਹੈ।",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ਸੰਰਚਿਤ",
        "llmNotConfigured": "ਅਸੰਰਚਿਤ",
        "llmClear": "ਸਾਫ਼ ਕਰੋ",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "ਟ੍ਰੇਨਰ",
        "trainerForLane": "ਇਸ ਲੇਨ ਦਾ ਟ੍ਰੇਨਰ",
        "trainerHint": "Klar Rust ਵਿੱਚ OpenAI-ਅਨੁਕੂਲ ਮਾਡਲ ਬੁਲਾਉਂਦਾ ਹੈ। ਚੈਟ, ਜਾਂਚ, ਫਿਰ ਲੇਨ ਅਨੁਸਾਰ ਲਾਗੂ। Home Assistant LLM ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਲੋੜੀਂਦੀ ਨਹੀਂ। ਉੱਨਤ JSON ਡੀਬੱਗ ਲਈ ਹੈ।",
        "trainerContext": "ਸੰਦਰਭ",
        "trainerValidate": "ਜਾਂਚੋ",
        "trainerApply": "ਲਾਗੂ ਕਰੋ",
        "trainerProposal": "ਪ੍ਰਸਤਾਵ JSON",
        "trainerOk": "ਵੈਧ",
        "trainerFail": "ਅਵੈਧ",
        "trainerSend": "ਭੇਜੋ",
        "trainerNeedLlm": "ਪਹਿਲਾਂ Settings ਵਿੱਚ LLM ਸੈੱਟ ਕਰੋ। Klar ਨੂੰ ਹੋਰ Home Assistant ਗੱਲਬਾਤ ਇੰਟੀਗ੍ਰੇਸ਼ਨ ਨਹੀਂ ਚਾਹੀਦੀ।",
        "trainerOpenSettings": "Settings ਖੋਲ੍ਹੋ",
        "trainerApplyHouse": "House ਲਾਗੂ ਕਰੋ",
        "trainerApplyMatch": "Match ਲਾਗੂ ਕਰੋ",
        "trainerApplyLanguage": "Language ਲਾਗੂ ਕਰੋ",
        "trainerAdvanced": "ਉੱਨਤ JSON",
        "trainerStreaming": "ਸਟ੍ਰੀਮਿੰਗ…",
    },
    "ne": {
        "engineHint": "आवाज, भाषाहरू र LLM यहाँ छन्। Home Assistant ले इन्जिन मात्र जोड्छ।",
        "languageHint": "खाली सूचीले हरेक संकलित Assist locale सक्रिय राख्छ। एउटा प्याक पिन गर्नु सामान्य घर हो।",
        "personalityHa": "आवाज, भाषाहरू र LLM यो Settings पृष्ठमा छन्।",
        "assistLanguages": "Assist भाषाहरू",
        "assistLanguagesHint": "Klar कुन प्याक विश्लेषण गर्न सक्छ। उपग्रह अझै प्रत्येक अनुरोधमा एउटा भाषा पठाउँछ। खाली = सबै संकलित locale।",
        "allAssistLanguages": "हरेक संकलित locale",
        "pinLanguage": "एउटा प्याक पिन गर्नुहोस्",
        "voice": "आवाज",
        "voiceHint": "व्यक्तित्व र बोलिएका जवाफ। Assist यो इन्जिनबाट पढ्छ, Home Assistant विकल्पबाट होइन।",
        "extraPrompt": "थप प्रम्प्ट",
        "extraPromptHint": "प्याक व्यक्तित्वमाथि वैकल्पिक पङ्क्ति। घरलाई आफ्नै नियम नचाहिने भए खाली राख्नुहोस्।",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM परिष्कार",
        "refineSpeechHint": "Klar अझै यन्त्र नियन्त्रण गर्छ। इन्जिन LLM त्यसपछि सकिएका NLU जवाफ यो आवाजमा लेख्छ।",
        "quietAck": "छोटो पुष्टि",
        "quietAckHint": "साधारण बत्ती वा स्विच अन/अफमा TTS छोडेर उपग्रहमा घण्टी बजाउनुहोस्।",
        "calendarLlm": "क्यालेन्डर LLM मार्फत",
        "calendarLlmHint": "Klar क्यालेन्डर पढिरहन्छ। अन: LLM घटना बोल्छ। अफ: Klar सूची बोल्छ।",
        "allowLlmTools": "च्याटमा Assist औजार अनुमति दिनुहोस्",
        "allowLlmToolsHint": "पूर्वनिर्धारित अफ। अन: च्याट मोडेलले Home Assistant नियन्त्रण गर्न सक्छ। अफ: औजार भए Klar त्यो एजेन्ट छोड्छ।",
        "missTitle": "Klar चुक्दा",
        "missHint": "निर्धारित अस्वीकारपछि वैकल्पिक तह। कुनैले पनि parse मा मोडेल राख्दैन।",
        "operatorChrome": "यो स्क्रिन",
        "operatorChromeHint": "अपरेटरका लागि थिम र इन्टरफेस भाषा। Assist होइन।",
        "haGlueHint": "Home Assistant Configure लाई इन्जिन URL, टोकन, च्यानल र वैकल्पिक बाँकी कुराकानी एजेन्ट मात्र चाहिन्छ। आवाज र LLM यहाँ रहन्छन्।",
        "settingsGuide": "यी तीन सेट गर्नुहोस्, अनि घर नक्सा गर्नुहोस्।",
        "settingsGuideVoice": "आवाज",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist भाषा",
        "appearanceDark": "गाढा",
        "appearanceLight": "हल्का",
        "setupReplay": "सेटअप फेरि चलाउनुहोस्",
        "personalityDefault": "सामान्य",
        "personalityButler": "Butler",
        "personalityLocker": "खुला",
        "personalityFuersorglich": "हेरचाह गर्ने",
        "personalityParty": "पार्टी",
        "personalityGrantig": "रिसाहा",
        "personalitySarkastisch": "व्यङ्ग्यात्मक",
        "personalityPirat": "समुद्री डाकू",
        "personalityHippie": "हिप्पी",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "अपरेटर भाषा",
        "operatorLanguageHint": "यो एप मात्र। यहाँ सुरक्षित, वा पहिलो बचत अघि KLAR_UI_LOCALE। Assist होइन, Home Assistant प्रोफाइल होइन।",
        "nluRag": "चुकमा घरको सन्दर्भ",
        "modeFull": "यन्त्र समाधान गर्नुहोस्",
        "modeContext": "कोठा मात्र",
        "inLab": "प्रयोगशालामा",
        "undoLastCommand": "पछिल्लो आदेश पूर्ववत",
        "applyDone": "{count} कोठा सुझाव लागू",
        "applyUndone": "कोठा सुझाव पूर्ववत",
        "applyUndoFailed": "कोठा सुझाव पूर्ववत हुन सकेन",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-अनुरूप अन्तिमबिन्दुसँग बोल्छ। Assist च्याट र प्रशिक्षकले यही config प्रयोग गर्छन्। Home Assistant मा OpenAI वा Ollama एकीकरण चाहिँदैन।",
        "llmBaseUrl": "आधार URL",
        "llmModel": "मोडेल",
        "llmApiKey": "API कुञ्जी",
        "llmApiKeyHint": "भण्डारित कुञ्जी राख्न खाली छोड्नुहोस्। Ollama खाली रहन सक्छ।",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "कन्फिगर गरिएको",
        "llmNotConfigured": "कन्फिगर छैन",
        "llmClear": "खाली गर्नुहोस्",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "प्रशिक्षक",
        "trainerForLane": "यो लेनको प्रशिक्षक",
        "trainerHint": "Klar Rust मा OpenAI-अनुरूप मोडेल बोलाउँछ। च्याट, जाँच, अनि लेनअनुसार लागू। Home Assistant LLM एकीकरण चाहिँदैन। उन्नत JSON डिबगका लागि हो।",
        "trainerContext": "सन्दर्भ",
        "trainerValidate": "जाँच गर्नुहोस्",
        "trainerApply": "लागू गर्नुहोस्",
        "trainerProposal": "प्रस्ताव JSON",
        "trainerOk": "मान्य",
        "trainerFail": "अमान्य",
        "trainerSend": "पठाउनुहोस्",
        "trainerNeedLlm": "पहिले Settings मा LLM सेट गर्नुहोस्। Klar लाई अर्को Home Assistant कुराकानी एकीकरण चाहिँदैन।",
        "trainerOpenSettings": "Settings खोल्नुहोस्",
        "trainerApplyHouse": "House लागू गर्नुहोस्",
        "trainerApplyMatch": "Match लागू गर्नुहोस्",
        "trainerApplyLanguage": "Language लागू गर्नुहोस्",
        "trainerAdvanced": "उन्नत JSON",
        "trainerStreaming": "स्ट्रिमिङ…",
    },
    "sw": {
        "engineHint": "Sauti, lugha na LLM ziko hapa. Home Assistant inaunganisha injini tu.",
        "languageHint": "Orodha tupu inaacha kila locale ya Assist iliyokusanywa ikiwashwa. Kubandika pakiti moja ndiyo nyumba ya kawaida.",
        "personalityHa": "Sauti, lugha na LLM ziko kwenye ukurasa huu wa Settings.",
        "assistLanguages": "Lugha za Assist",
        "assistLanguagesHint": "Pakiti zipi Klar inaweza kuchambua. Satelaiti bado inatuma lugha moja kwa kila ombi. Tupu = locale zote zilizokusanywa.",
        "allAssistLanguages": "Kila locale iliyokusanywa",
        "pinLanguage": "Bandika pakiti moja",
        "voice": "Sauti",
        "voiceHint": "Tabia na majibu yanayozungumzwa. Assist inasoma hii kutoka injini, si kutoka chaguo za Home Assistant.",
        "extraPrompt": "Prompt ya ziada",
        "extraPromptHint": "Mstari wa hiari juu ya tabia ya pakiti. Acha tupu isipokuwa nyumba inahitaji kanuni yake.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "Kukamilisha LLM",
        "refineSpeechHint": "Klar bado inadhibiti vifaa. LLM ya injini kisha inaandika upya majibu ya NLU yaliyokamilika kwa sauti hii.",
        "quietAck": "Uthibitisho mfupi",
        "quietAckHint": "Kwenye taa au swichi rahisi washa/zima, ruka TTS na cheza kengele kwenye satelaiti.",
        "calendarLlm": "Kalenda kupitia LLM",
        "calendarLlmHint": "Klar bado inasoma kalenda. Washa: LLM inasema matukio. Zima: Klar inasema orodha.",
        "allowLlmTools": "Ruhusu zana za Assist kwenye gumzo",
        "allowLlmToolsHint": "Imezimwa kwa chaguo-msingi. Washa: modeli ya gumzo inaweza kudhibiti Home Assistant. Zima: Klar inaruka wakala huyo akiwa na zana.",
        "missTitle": "Klar inapokosa",
        "missHint": "Tabaka za hiari baada ya kukataa kwa uhakika. Hakuna inayoweka modeli kwenye parse.",
        "operatorChrome": "Skrini hii",
        "operatorChromeHint": "Mandhari na lugha ya kiolesura kwa waendeshaji. Si Assist.",
        "haGlueHint": "Home Assistant Configure inahitaji tu URL ya injini, tokeni, kituo na wakala wa mazungumzo uliosalia wa hiari. Sauti na LLM zinabaki hapa.",
        "settingsGuide": "Weka hizi tatu, kisha ramani nyumba.",
        "settingsGuideVoice": "Sauti",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Lugha ya Assist",
        "appearanceDark": "Giza",
        "appearanceLight": "Mwanga",
        "setupReplay": "Cheza setup tena",
        "personalityDefault": "Kawaida",
        "personalityButler": "Butler",
        "personalityLocker": "Rahisi",
        "personalityFuersorglich": "Mwenye kujali",
        "personalityParty": "Sherehe",
        "personalityGrantig": "Mwenye hasira",
        "personalitySarkastisch": "Mwenye kejeli",
        "personalityPirat": "Maharamia",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Lugha ya opereta",
        "operatorLanguageHint": "Programu hii tu. Imehifadhiwa hapa, au KLAR_UI_LOCALE kabla ya kuhifadhi mara ya kwanza. Si Assist, si wasifu wa Home Assistant.",
        "nluRag": "Muktadha wa nyumba wakati wa kukosa",
        "modeFull": "Tatua vifaa",
        "modeContext": "Vyumba tu",
        "inLab": "Kwenye maabara",
        "undoLastCommand": "Tendua amri ya mwisho",
        "applyDone": "Imetumika mapendekezo {count} ya vyumba",
        "applyUndone": "Mapendekezo ya vyumba yametenduliwa",
        "applyUndoFailed": "Haikuweza kutendua mapendekezo ya vyumba",
        "llm": "LLM",
        "llmHint": "Klar inazungumza na sehemu ya mwisho inayolingana na OpenAI. Gumzo la Assist na mkufunzi wanatumia config ile ile. Muunganisho wa OpenAI au Ollama katika Home Assistant hauhitajiki.",
        "llmBaseUrl": "URL ya msingi",
        "llmModel": "Modeli",
        "llmApiKey": "Ufunguo wa API",
        "llmApiKeyHint": "Acha tupu ili kuweka ufunguo uliohifadhiwa. Ollama inaweza kubaki tupu.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Imesanidiwa",
        "llmNotConfigured": "Haijasanidiwa",
        "llmClear": "Futa",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Mkufunzi",
        "trainerForLane": "Mkufunzi wa njia hii",
        "trainerHint": "Klar inaita modeli inayolingana na OpenAI katika Rust. Gumzo, thibitisha, kisha tumia kwa njia. Muunganisho wa LLM wa Home Assistant hauhitajiki. JSON ya kina ni kwa debug.",
        "trainerContext": "Muktadha",
        "trainerValidate": "Thibitisha",
        "trainerApply": "Tumia",
        "trainerProposal": "JSON ya pendekezo",
        "trainerOk": "Sahihi",
        "trainerFail": "Si sahihi",
        "trainerSend": "Tuma",
        "trainerNeedLlm": "Sanidi LLM katika Settings kwanza. Klar haitaji muunganisho mwingine wa mazungumzo wa Home Assistant.",
        "trainerOpenSettings": "Fungua Settings",
        "trainerApplyHouse": "Tumia House",
        "trainerApplyMatch": "Tumia Match",
        "trainerApplyLanguage": "Tumia Language",
        "trainerAdvanced": "JSON ya kina",
        "trainerStreaming": "Inatiririsha…",
    },
}





