"""Settings hint chrome: Nordic and Slavic Assist locales."""

from __future__ import annotations

from lang_packs.settings_hints import row

PACKS: dict[str, dict[str, str]] = {
    "da": row(
        "Opløs enheder: Klar vælger entiteten. Kun rum: den stopper ved området.",
        "Til: låse, lukning af persienner og store eller rumbredte risikable kommandoer spørger først én gang. Fra: de kører med det samme.",
        "Til: Klar gemmer de sidste 200 ture i 24 timer. Nødvendigt til downloadene nedenfor.",
        "Til: downloads indeholder den sagte sætning. Fra: kun redigeret.",
        "Fra som standard. Til: efter et miss kan et lokalt betydningsmatch stadig finde intentionen. Ikke en LLM.",
        "Påkrævet for at gemme fra denne skærm. Samme værdi som App-tokenet.",
        "Status",
        "Svar som rum- eller enhedsstatus. Til: LLM’en omskriver den færdige sætning.",
        "Kommandoer",
        "Bekræftelse efter Klar allerede har kørt kommandoen. Til: «lyset er tændt» får denne stemme.",
        "Opfølgende spørgsmål",
        "Hvilket-rum- og hvilken-enhed-spørgsmål. Til: Klars spørgsmål omskrives.",
        "Afvisning",
        "Svar som jeg-forstod-ikke. Til: de sætninger får denne stemme.",
        "Chat- og kalender-LLM-svar bliver som de er — ingen anden omskrivning.",
        "Gemt.",
        "Kunne ikke gemme.",
        "Ikke gemt. Indtast skrivetokenet under Engine.",
    ),
    "nb": row(
        "Løs enheter: Klar velger entiteten. Bare rom: den stopper ved området.",
        "På: låser, lukking av persienner og store eller romvide risikable kommandoer spør først én gang. Av: de kjører med en gang.",
        "På: Klar beholder de siste 200 turene i 24 timer. Trengs til nedlastingene under.",
        "På: nedlastinger inneholder den sagte setningen. Av: bare redigert.",
        "Av som standard. På: etter et miss kan et lokalt betydningsmatch fortsatt finne intensjonen. Ikke en LLM.",
        "Påkrevd for å lagre fra denne skjermen. Samme verdi som App-tokenet.",
        "Status",
        "Svar som rom- eller enhetsstatus. På: LLM-en skriver om den ferdige setningen.",
        "Kommandoer",
        "Bekreftelse etter at Klar allerede har kjørt kommandoen. På: «lyset er på» får denne stemmen.",
        "Oppfølgingsspørsmål",
        "Hvilket-rom- og hvilken-enhet-spørsmål. På: Klars spørsmål skrives om.",
        "Avvisning",
        "Svar som jeg-skjønte-ikke. På: de setningene får denne stemmen.",
        "Chat- og kalender-LLM-svar blir som de er — ingen andre omskrivning.",
        "Lagret.",
        "Kunne ikke lagre.",
        "Ikke lagret. Skriv inn skrivetokenet under Engine.",
    ),
    "sv": row(
        "Lös enheter: Klar väljer entiteten. Bara rum: den stannar vid området.",
        "På: lås, stängning av persienner och stora eller rumsvida riskabla kommandon frågar först en gång. Av: de körs genast.",
        "På: Klar sparar de senaste 200 turerna i 24 timmar. Behövs för nedladdningarna nedan.",
        "På: nedladdningar innehåller den sagda meningen. Av: bara redigerat.",
        "Av som standard. På: efter en miss kan en lokal betydelsematch fortfarande hitta avsikten. Inte en LLM.",
        "Krävs för att spara från den här skärmen. Samma värde som App-tokenet.",
        "Status",
        "Svar som rums- eller enhetsstatus. På: LLM:en skriver om den färdiga meningen.",
        "Kommandon",
        "Bekräftelse efter att Klar redan kört kommandot. På: «ljuset är på» får den här rösten.",
        "Uppföljningsfrågor",
        "Vilket-rum- och vilken-enhet-frågor. På: Klars fråga skrivs om.",
        "Avvisning",
        "Svar som jag-förstod-inte. På: de meningarna får den här rösten.",
        "Chatt- och kalender-LLM-svar förblir som de är — ingen andra omskrivning.",
        "Sparat.",
        "Kunde inte spara.",
        "Inte sparat. Ange skrivtokenet under Engine.",
    ),
    "fi": row(
        "Ratkaise laitteet: Klar valitsee entiteetin. Vain huoneet: se pysähtyy alueeseen.",
        "Päällä: lukot, kaihtimien sulkeminen ja suuret tai huoneenlaajuiset riskikomennot kysyvät ensin kerran. Pois: ne ajetaan heti.",
        "Päällä: Klar pitää viimeiset 200 vuoroa 24 tuntia. Tarvitaan alla oleviin latauksiin.",
        "Päällä: lataukset sisältävät lausutun lauseen. Pois: vain peitettynä.",
        "Pois oletuksena. Päällä: osumattomuuden jälkeen paikallinen merkitysvastine voi yhä löytää aikomuksen. Ei LLM.",
        "Tarvitaan tallentamiseen tältä näytöltä. Sama arvo kuin App-tunnus.",
        "Tila",
        "Vastauksia kuten huoneen tai laitteen tila. Päällä: LLM kirjoittaa valmiin lauseen uudelleen.",
        "Komennot",
        "Vahvistus sen jälkeen kun Klar on jo ajanut komennon. Päällä: «valo on päällä» saa tämän äänen.",
        "Jatkokysymykset",
        "Mikä-huone- ja mikä-laite-kysymykset. Päällä: Klarin kysymys kirjoitetaan uudelleen.",
        "Hylkäys",
        "Vastauksia kuten en-ymmärtänyt. Päällä: nuo lauseet saavat tämän äänen.",
        "Chatin ja kalenterin LLM-vastaukset jäävät ennalleen — ei toista hienosäätöä.",
        "Tallennettu.",
        "Tallennus epäonnistui.",
        "Ei tallennettu. Syötä kirjoitustunnus kohdassa Engine.",
    ),
    "is": row(
        "Leysa tæki: Klar velur eininguna. Aðeins herbergi: það stoppar við svæðið.",
        "Kveikt: lásar, lokun gluggatjalda og stórar eða herbergisvíðar áhættuskipanir spyrja fyrst einu sinni. Slökkt: þær keyra strax.",
        "Kveikt: Klar geymir síðustu 200 umferðir í 24 klukkustundir. Þarf fyrir niðurhalin hér að neðan.",
        "Kveikt: niðurhal inniheldur sagða setninguna. Slökkt: aðeins ritstýrt.",
        "Slökkt sjálfgefið. Kveikt: eftir miss getur staðbundin merkingarsamsvörun enn fundið ásetninginn. Ekki LLM.",
        "Nauðsynlegt til að vista af þessum skjá. Sama gildi og App-teiknið.",
        "Staða",
        "Svör eins og herbergis- eða tækjastaða. Kveikt: LLM endurskrifar fullbúnu setninguna.",
        "Skipanir",
        "Staðfesting eftir að Klar hefur þegar keyrt skipunina. Kveikt: «ljósið er kveikt» fær þessa rödd.",
        "Eftirfylgnispurningar",
        "Hvaða-herbergi og hvaða-tæki spurningar. Kveikt: spurning Klars er endurskrifuð.",
        "Höfnun",
        "Svör eins og ég-skildi-ekki. Kveikt: þær setningar fá þessa rödd.",
        "Spjall- og dagatals-LLM svör haldast eins og þau eru — engin önnur fínpússun.",
        "Vistað.",
        "Gat ekki vistað.",
        "Ekki vistað. Sláðu inn skrifteiknið undir Engine.",
    ),
    "et": row(
        "Lahenda seadmed: Klar valib olemi. Ainult toad: see peatub alal.",
        "Sees: lukud, katete sulgemine ja suured või toaülesed riskantsed käsud küsivad enne korra. Väljas: need käivituvad kohe.",
        "Sees: Klar hoiab viimast 200 käiku 24 tundi. Vaja allalaadimiste jaoks allpool.",
        "Sees: allalaadimised sisaldavad öeldud lauset. Väljas: ainult redigeeritud.",
        "Vaikimisi väljas. Sees: pärast möödalaskmist võib kohalik tähendusvaste intentiooni ikka leida. Pole LLM.",
        "Vajalik sellelt ekraanilt salvestamiseks. Sama väärtus kui rakenduse tunnus.",
        "Olek",
        "Vastused nagu toa või seadme olek. Sees: LLM kirjutab valmis lause ümber.",
        "Käsud",
        "Kinnitus pärast seda, kui Klar on käsu juba käivitanud. Sees: «valgus on sees» saab selle hääle.",
        "Järelküsimused",
        "Milline-tuba ja milline-seade küsimused. Sees: Klari küsimus kirjutatakse ümber.",
        "Keeldumine",
        "Vastused nagu ma-ei-saanud-aru. Sees: need laused saavad selle hääle.",
        "Vestluse ja kalendri LLM-vastused jäävad endiseks — teist lihvimist pole.",
        "Salvestatud.",
        "Salvestamine ebaõnnestus.",
        "Ei salvestatud. Sisesta kirjutustunnus jaotises Engine.",
    ),
    "lt": row(
        "Išspręsti įrenginius: Klar pasirenka objektą. Tik kambariai: sustoja prie zonos.",
        "Įjungta: spynos, užuolaidų uždarymas ir didelės ar viso kambario rizikingos komandos pirma klausia. Išjungta: jos vykdomos iškart.",
        "Įjungta: Klar saugo paskutinius 200 ėjimų 24 valandas. Reikia atsisiuntimams žemiau.",
        "Įjungta: atsisiuntimai turi ištartą sakinį. Išjungta: tik redaguota.",
        "Pagal numatymą išjungta. Įjungta: po klaidos vietinis prasmės atitikmuo vis dar gali rasti ketinimą. Ne LLM.",
        "Reikia įrašyti iš šio ekrano. Ta pati reikšmė kaip programos prieigos raktas.",
        "Būsena",
        "Atsakymai kaip kambario ar įrenginio būsena. Įjungta: LLM perrašo baigtą sakinį.",
        "Komandos",
        "Patvirtinimas po to, kai Klar jau įvykdė komandą. Įjungta: «šviesa įjungta» gauna šį balsą.",
        "Tęstiniai klausimai",
        "Kurio kambario ir kurio įrenginio klausimai. Įjungta: Klar klausimas perrašomas.",
        "Atmetimas",
        "Atsakymai kaip nesupratau. Įjungta: tie sakiniai gauna šį balsą.",
        "Pokalbio ir kalendoriaus LLM atsakymai lieka kaip yra — be antro šlifavimo.",
        "Įrašyta.",
        "Nepavyko įrašyti.",
        "Neįrašyta. Įveskite rašymo raktą ties Engine.",
    ),
    "lv": row(
        "Atrisināt ierīces: Klar izvēlas entītiju. Tikai telpas: tas apstājas pie zonas.",
        "Ieslēgts: slēdzenes, žalūziju aizvēršana un lielas vai visā telpā riskantas komandas vispirms vaicā. Izslēgts: tās izpildās uzreiz.",
        "Ieslēgts: Klar glabā pēdējos 200 gājienus 24 stundas. Vajag lejupielādēm zemāk.",
        "Ieslēgts: lejupielādes ietver teikto teikumu. Izslēgts: tikai rediģēts.",
        "Pēc noklusējuma izslēgts. Ieslēgts: pēc kļūdas vietēja nozīmes sakritība joprojām var atrast nodomu. Nav LLM.",
        "Nepieciešams, lai saglabātu no šī ekrāna. Tā pati vērtība kā lietotnes pilnvara.",
        "Statuss",
        "Atbildes kā telpas vai ierīces statuss. Ieslēgts: LLM pārraksta pabeigto teikumu.",
        "Komandas",
        "Apstiprinājums pēc tam, kad Klar jau izpildīja komandu. Ieslēgts: «gaisma ir ieslēgta» iegūst šo balsi.",
        "Turpmākie jautājumi",
        "Kuras telpas un kuras ierīces jautājumi. Ieslēgts: Klara jautājums tiek pārrakstīts.",
        "Noraidījums",
        "Atbildes kā nesapratu. Ieslēgts: tie teikumi iegūst šo balsi.",
        "Tērzēšanas un kalendāra LLM atbildes paliek, kādas ir — bez otra slīpējuma.",
        "Saglabāts.",
        "Neizdevās saglabāt.",
        "Nav saglabāts. Ievadi rakstīšanas pilnvaru sadaļā Engine.",
    ),
    "cs": row(
        "Vyřešit zařízení: Klar vybere entitu. Jen místnosti: zastaví se u oblasti.",
        "Zapnuto: zámky, zavírání žaluzií a velké nebo celomístnostní rizikové příkazy se nejdřív zeptají. Vypnuto: spustí se hned.",
        "Zapnuto: Klar uchová posledních 200 tahů 24 hodin. Potřeba pro stažení níže.",
        "Zapnuto: stažení obsahují pronesenou větu. Vypnuto: jen začerněné.",
        "Ve výchozím stavu vypnuto. Zapnuto: po minutí může místní významová shoda záměr ještě najít. Není to LLM.",
        "Nutné k uložení z této obrazovky. Stejná hodnota jako token aplikace.",
        "Stav",
        "Odpovědi jako stav místnosti nebo zařízení. Zapnuto: LLM přepíše hotovou větu.",
        "Příkazy",
        "Potvrzení poté, co Klar příkaz už provedl. Zapnuto: «světlo je zapnuté» dostane tento hlas.",
        "Navazující otázky",
        "Otázky která-místnost a které-zařízení. Zapnuto: Klarova otázka se přepíše.",
        "Odmítnutí",
        "Odpovědi jako nerozuměl-jsem. Zapnuto: ty věty dostanou tento hlas.",
        "Odpovědi LLM z chatu a kalendáře zůstanou, jaké jsou — bez druhého přepisu.",
        "Uloženo.",
        "Uložení selhalo.",
        "Neuloženo. Zadej zapisovací token v Engine.",
    ),
    "sk": row(
        "Vyriešiť zariadenia: Klar vyberie entitu. Len miestnosti: zastaví sa pri oblasti.",
        "Zapnuté: zámky, zatváranie žalúzií a veľké alebo celomiestnostné rizikové príkazy sa najprv spýtajú. Vypnuté: spustia sa hneď.",
        "Zapnuté: Klar uchová posledných 200 ťahov 24 hodín. Potrebné na stiahnutia nižšie.",
        "Zapnuté: stiahnutia obsahujú povedanú vetu. Vypnuté: len začiernené.",
        "Predvolene vypnuté. Zapnuté: po minutí môže miestna významová zhoda zámer ešte nájsť. Nie je to LLM.",
        "Potrebné na uloženie z tejto obrazovky. Rovnaká hodnota ako token aplikácie.",
        "Stav",
        "Odpovede ako stav miestnosti alebo zariadenia. Zapnuté: LLM prepíše hotovú vetu.",
        "Príkazy",
        "Potvrdenie potom, čo Klar príkaz už vykonal. Zapnuté: «svetlo je zapnuté» dostane tento hlas.",
        "Nadväzujúce otázky",
        "Otázky ktorá-miestnosť a ktoré-zariadenie. Zapnuté: Klarova otázka sa prepíše.",
        "Odmietnutie",
        "Odpovede ako nerozumel-som. Zapnuté: tie vety dostanú tento hlas.",
        "Odpovede LLM z chatu a kalendára ostanú, aké sú — bez druhého prepisu.",
        "Uložené.",
        "Uloženie zlyhalo.",
        "Neuložené. Zadaj zapisovací token v Engine.",
    ),
    "pl": row(
        "Rozwiąż urządzenia: Klar wybiera encję. Tylko pomieszczenia: zatrzymuje się na obszarze.",
        "Wł.: zamki, zamykanie rolet i duże albo całopokojowe ryzykowne polecenia pytają najpierw. Wył.: wykonują się od razu.",
        "Wł.: Klar trzyma ostatnie 200 tur przez 24 godziny. Potrzebne do pobrań poniżej.",
        "Wł.: pobrania zawierają wypowiedziane zdanie. Wył.: tylko zredagowane.",
        "Domyślnie wył. Wł.: po pudle lokalne dopasowanie znaczenia może jeszcze odzyskać zamiar. To nie LLM.",
        "Wymagane, by zapisać z tego ekranu. Ta sama wartość co token aplikacji.",
        "Stan",
        "Odpowiedzi jak stan pokoju lub urządzenia. Wł.: LLM przepisuje skończone zdanie.",
        "Polecenia",
        "Potwierdzenie po tym, jak Klar już wykonał polecenie. Wł.: «światło jest włączone» dostaje ten głos.",
        "Pytania doprecyzowujące",
        "Pytania który-pokój i które-urządzenie. Wł.: pytanie Klara jest przepisywane.",
        "Odrzucenie",
        "Odpowiedzi jak nie-zrozumiałem. Wł.: te zdania dostają ten głos.",
        "Odpowiedzi LLM czatu i kalendarza zostają, jakie są — bez drugiego szlifu.",
        "Zapisano.",
        "Nie udało się zapisać.",
        "Nie zapisano. Wpisz token zapisu w Engine.",
    ),
    "hu": row(
        "Eszközök feloldása: a Klar választja az entitást. Csak szobák: a területen megáll.",
        "Be: zárak, redőnyzárás és nagy vagy szobaszintű kockázatos parancsok először rákérdeznek. Ki: azonnal lefutnak.",
        "Be: a Klar 24 óráig őrzi az utolsó 200 kört. Kell a lenti letöltésekhez.",
        "Be: a letöltések tartalmazzák a kimondott mondatot. Ki: csak kitakarva.",
        "Alapból ki. Be: tévesztés után egy helyi jelentésegyezés még megtalálhatja a szándékot. Nem LLM.",
        "Szükséges a mentéshez erről a képernyőről. Ugyanaz az érték, mint az App tokenje.",
        "Állapot",
        "Válaszok, mint egy szoba vagy eszköz állapota. Be: az LLM átírja a kész mondatot.",
        "Parancsok",
        "Visszaigazolás, miután a Klar már futtatta a parancsot. Be: «a lámpa be van kapcsolva» ezt a hangot kapja.",
        "Rákérdezések",
        "Melyik-szoba és melyik-eszköz kérdések. Be: a Klar kérdése átíródik.",
        "Elutasítás",
        "Nem-értettem típusú válaszok. Be: azok a mondatok ezt a hangot kapják.",
        "A csevegés és naptár LLM-válaszai maradnak, ahogy vannak — nincs második csiszolás.",
        "Mentve.",
        "A mentés nem sikerült.",
        "Nincs mentve. Írd be az írási tokent az Engine alatt.",
    ),
    "hr": row(
        "Razriješi uređaje: Klar bira entitet. Samo sobe: staje na području.",
        "Uključeno: brave, zatvaranje roleta i velike ili cjelosobne rizične naredbe prvo pitaju. Isključeno: izvršavaju se odmah.",
        "Uključeno: Klar čuva zadnjih 200 poteza 24 sata. Treba za preuzimanja ispod.",
        "Uključeno: preuzimanja uključuju izgovorenu rečenicu. Isključeno: samo redigirano.",
        "Po zadanome isključeno. Uključeno: nakon promašaja lokalno značenjsko podudaranje još može pronaći nakanu. Nije LLM.",
        "Potrebno za spremanje s ovog zaslona. Ista vrijednost kao token aplikacije.",
        "Stanje",
        "Odgovori kao stanje sobe ili uređaja. Uključeno: LLM prepisuje gotovu rečenicu.",
        "Naredbe",
        "Potvrda nakon što je Klar već izvršio naredbu. Uključeno: «svjetlo je upaljeno» dobiva ovaj glas.",
        "Naknadna pitanja",
        "Pitanja koja-soba i koji-uređaj. Uključeno: Klarovo pitanje se prepisuje.",
        "Odbijanje",
        "Odgovori kao nisam-razumio. Uključeno: te rečenice dobivaju ovaj glas.",
        "LLM odgovori chata i kalendara ostaju kakvi jesu — bez drugog dorađivanja.",
        "Spremljeno.",
        "Spremanje nije uspjelo.",
        "Nije spremljeno. Unesi token za pisanje pod Engine.",
    ),
    "sl": row(
        "Razreši naprave: Klar izbere entiteto. Samo prostori: se ustavi pri območju.",
        "Vklopljeno: ključavnice, zapiranje senčil in veliki ali celoprostorski tvegani ukazi najprej vprašajo. Izklopljeno: se izvedejo takoj.",
        "Vklopljeno: Klar hrani zadnjih 200 potez 24 ur. Potrebno za prenose spodaj.",
        "Vklopljeno: prenosi vključujejo izrečeni stavek. Izklopljeno: samo prekrito.",
        "Privzeto izklopljeno. Vklopljeno: po zgrešitvi lahko lokalno ujemanje pomena še najde namen. Ni LLM.",
        "Potrebno za shranjevanje s tega zaslona. Ista vrednost kot žeton aplikacije.",
        "Stanje",
        "Odgovori kot stanje prostora ali naprave. Vklopljeno: LLM prepiše končani stavek.",
        "Ukazi",
        "Potrditev, potem ko je Klar ukaz že izvedel. Vklopljeno: «luč je prižgana» dobi ta glas.",
        "Nadaljnja vprašanja",
        "Vprašanja kateri-prostor in katera-naprava. Vklopljeno: Klarovo vprašanje se prepiše.",
        "Zavrnitev",
        "Odgovori kot nisem-razumel. Vklopljeno: tisti stavki dobijo ta glas.",
        "LLM odgovori klepeta in koledarja ostanejo, kakršni so — brez drugega izboljšanja.",
        "Shranjeno.",
        "Shranjevanje ni uspelo.",
        "Ni shranjeno. Vnesi žeton za pisanje pod Engine.",
    ),
    "bg": row(
        "Разреши устройства: Klar избира обекта. Само стаи: спира на зоната.",
        "Вкл.: ключалки, затваряне на щори и големи или за цялата стая рискови команди питат първо. Изкл.: изпълняват се веднага.",
        "Вкл.: Klar пази последните 200 хода 24 часа. Нужно за изтеглянията отдолу.",
        "Вкл.: изтеглянията включват изреченото изречение. Изкл.: само редактирано.",
        "По подразбиране изкл. Вкл.: след пропуск местно смислово съвпадение все още може да намери намерението. Не е LLM.",
        "Нужно, за да запишеш от този екран. Същата стойност като токена на приложението.",
        "Състояние",
        "Отговори като състояние на стая или устройство. Вкл.: LLM пренаписва готовото изречение.",
        "Команди",
        "Потвърждение, след като Klar вече е изпълнил командата. Вкл.: «светлината е включена» получава този глас.",
        "Уточняващи въпроси",
        "Въпроси коя-стая и кое-устройство. Вкл.: въпросът на Klar се пренаписва.",
        "Отказ",
        "Отговори като не-разбрах. Вкл.: тези изречения получават този глас.",
        "LLM отговорите от чата и календара остават както са — без второ изпипване.",
        "Записано.",
        "Записването не успя.",
        "Не е записано. Въведи токена за писане в Engine.",
    ),
    "sr": row(
        "Разреши уређаје: Klar бира ентитет. Само собе: стаје на подручју.",
        "Укљ.: браве, затварање ролетни и велике или целособне ризичне наредбе прво питају. Искљ.: извршавају се одмах.",
        "Укљ.: Klar чува последњих 200 потеза 24 сата. Треба за преузимања испод.",
        "Укљ.: преузимања укључују изговорену реченицу. Искљ.: само редакција.",
        "Подразумевано искљ. Укљ.: после промашаја локално значењско подударање још може наћи намеру. Није LLM.",
        "Потребно да сачуваш са овог екрана. Иста вредност као жетон апликације.",
        "Стање",
        "Одговори као стање собе или уређаја. Укљ.: LLM преписује готову реченицу.",
        "Наредбе",
        "Потврда пошто је Klar већ извршио наредбу. Укљ.: «светло је упаљено» добија овај глас.",
        "Накнадна питања",
        "Питања која-соба и који-уређај. Укљ.: Кларово питање се преписује.",
        "Одбијање",
        "Одговори као нисам-разумео. Укљ.: те реченице добијају овај глас.",
        "LLM одговори ћаскања и календара остају какви јесу — без друге дораде.",
        "Сачувано.",
        "Чување није успело.",
        "Није сачувано. Унеси жетон за писање под Engine.",
    ),
    "sr-Latn": row(
        "Razreši uređaje: Klar bira entitet. Samo sobe: staje na području.",
        "Uklj.: brave, zatvaranje roletni i velike ili celosobne rizične naredbe prvo pitaju. Isklj.: izvršavaju se odmah.",
        "Uklj.: Klar čuva poslednjih 200 poteza 24 sata. Treba za preuzimanja ispod.",
        "Uklj.: preuzimanja uključuju izgovorenu rečenicu. Isklj.: samo redakcija.",
        "Podrazumevano isklj. Uklj.: posle promašaja lokalno značenjsko podudaranje još može naći nameru. Nije LLM.",
        "Potrebno da sačuvaš sa ovog ekrana. Ista vrednost kao žeton aplikacije.",
        "Stanje",
        "Odgovori kao stanje sobe ili uređaja. Uklj.: LLM prepisuje gotovu rečenicu.",
        "Naredbe",
        "Potvrda pošto je Klar već izvršio naredbu. Uklj.: «svetlo je upaljeno» dobija ovaj glas.",
        "Naknadna pitanja",
        "Pitanja koja-soba i koji-uređaj. Uklj.: Klarovo pitanje se prepisuje.",
        "Odbijanje",
        "Odgovori kao nisam-razumeo. Uklj.: te rečenice dobijaju ovaj glas.",
        "LLM odgovori ćaskanja i kalendara ostaju kakvi jesu — bez druge dorade.",
        "Sačuvano.",
        "Čuvanje nije uspelo.",
        "Nije sačuvano. Unesi žeton za pisanje pod Engine.",
    ),
    "uk": row(
        "Розв’язати пристрої: Klar обирає сутність. Лише кімнати: зупиняється на зоні.",
        "Увімк.: замки, закриття ролет і великі чи на всю кімнату ризиковані команди спершу питають. Вимк.: виконуються одразу.",
        "Увімк.: Klar зберігає останні 200 ходів 24 години. Потрібно для завантажень нижче.",
        "Увімк.: завантаження містять сказане речення. Вимк.: лише відредаговано.",
        "Типово вимк. Увімк.: після промаху локальний збіг значення ще може знайти намір. Це не LLM.",
        "Потрібно, щоб зберегти з цього екрана. Те саме значення, що й токен застосунку.",
        "Стан",
        "Відповіді на кшталт стану кімнати чи пристрою. Увімк.: LLM переписує готове речення.",
        "Команди",
        "Підтвердження після того, як Klar уже виконав команду. Увімк.: «світло ввімкнено» отримує цей голос.",
        "Уточнювальні питання",
        "Питання яка-кімната і який-пристрій. Увімк.: питання Klar переписується.",
        "Відмова",
        "Відповіді на кшталт не-зрозумів. Увімк.: ті речення отримують цей голос.",
        "Відповіді LLM чату й календаря лишаються як є — без другого шліфування.",
        "Збережено.",
        "Не вдалося зберегти.",
        "Не збережено. Введи токен запису в Engine.",
    ),
}
