"""Settings / LLM / trainer chrome for East European and Asian Assist locales."""

from __future__ import annotations

PACKS: dict[str, dict[str, str]] = {
    "cs": {
        "engineHint": "Hlas, jazyky a LLM jsou tady. Home Assistant jen připojuje engine.",
        "languageHint": "Prázdný seznam nechá každou zkompilovanou Assist locale aktivní. Připnout jeden pack je běžná domácnost.",
        "personalityHa": "Hlas, jazyky a LLM jsou na této stránce Settings.",
        "assistLanguages": "Jazyky Assist",
        "assistLanguagesHint": "Které packy smí Klar parsovat. Satelit stejně posílá jeden jazyk na požadavek. Prázdné = všechny zkompilované locale.",
        "allAssistLanguages": "Každá zkompilovaná locale",
        "pinLanguage": "Připnout jeden pack",
        "voice": "Hlas",
        "voiceHint": "Osobnost a mluvené odpovědi. Assist to čte z enginu, ne z voleb Home Assistant.",
        "extraPrompt": "Extra prompt",
        "extraPromptHint": "Volitelný řádek nad osobností packu. Nechte prázdné, pokud dům nepotřebuje vlastní pravidlo.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM vylepšení",
        "refineSpeechHint": "Klar dál ovládá zařízení. LLM enginu pak přepíše hotové NLU odpovědi tímto hlasem.",
        "quietAck": "Krátké potvrzení",
        "quietAckHint": "U jednoduchého světla nebo vypínače zapnout/vypnout přeskoč TTS a přehraj zvonek na satelitu.",
        "calendarLlm": "Kalendář přes LLM",
        "calendarLlmHint": "Klar kalendář dál čte. Zapnuto: LLM říká události. Vypnuto: Klar říká seznam.",
        "allowLlmTools": "Povolit nástroje Assist v chatu",
        "allowLlmToolsHint": "Ve výchozím stavu vypnuto. Zapnuto: chatovací model smí ovládat Home Assistant. Vypnuto: Klar agenta s nástroji přeskočí.",
        "missTitle": "Když Klar mine",
        "missHint": "Volitelné vrstvy po deterministickém odmítnutí. Žádná z nich nedává model na parse.",
        "operatorChrome": "Tato obrazovka",
        "operatorChromeHint": "Motiv a jazyk rozhraní pro operátory. Ne Assist.",
        "haGlueHint": "Home Assistant Configure potřebuje jen URL enginu, token, kanál a volitelného zbylého conversation agenta. Hlas a LLM zůstávají tady.",
        "settingsGuide": "Nastav tyhle tři, pak namapuj dům.",
        "settingsGuideVoice": "Hlas",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Jazyk Assist",
        "appearanceDark": "Tmavý",
        "appearanceLight": "Světlý",
        "setupReplay": "Znovu setup",
        "personalityDefault": "Normální",
        "personalityButler": "Butler",
        "personalityLocker": "Uvolněný",
        "personalityFuersorglich": "Pečující",
        "personalityParty": "Párty",
        "personalityGrantig": "Mrzutý",
        "personalitySarkastisch": "Sarkastický",
        "personalityPirat": "Pirát",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Jazyk operátora",
        "operatorLanguageHint": "Jen tato aplikace. Uloženo tady, nebo KLAR_UI_LOCALE před prvním uložením. Ne Assist, ne profil Home Assistant.",
        "nluRag": "Kontext domu při miss",
        "modeFull": "Rozlišit zařízení",
        "modeContext": "Jen místnosti",
        "inLab": "V laboratoři",
        "undoLastCommand": "Vrátit poslední příkaz",
        "applyDone": "Použito {count} návrhů místností",
        "applyUndone": "Návrhy místností vráceny",
        "applyUndoFailed": "Návrhy místností se nepodařilo vrátit",
        "llm": "LLM",
        "llmHint": "Klar mluví s OpenAI-kompatibilním endpointem. Chat Assist a trenér používají stejnou config. Integrace OpenAI nebo Ollama v Home Assistant není potřeba.",
        "llmBaseUrl": "Základní URL",
        "llmModel": "Model",
        "llmApiKey": "API klíč",
        "llmApiKeyHint": "Nechte prázdné, abyste ponechali uložený klíč. U Ollama může zůstat prázdné.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Nastaveno",
        "llmNotConfigured": "Nenastaveno",
        "llmClear": "Vymazat",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Trenér",
        "trainerForLane": "Trenér pro tuto stopu",
        "trainerHint": "Klar volá OpenAI-kompatibilní model v Rustu. Chatuj, ověř, pak použij po stopách. Integrace LLM v Home Assistant není potřeba. Pokročilé JSON je pro debug.",
        "trainerContext": "Kontext",
        "trainerValidate": "Ověřit",
        "trainerApply": "Použít",
        "trainerProposal": "Návrh JSON",
        "trainerOk": "Platné",
        "trainerFail": "Neplatné",
        "trainerSend": "Odeslat",
        "trainerNeedLlm": "Nejdřív nastav LLM v Settings. Klar nepotřebuje další conversation integraci Home Assistant.",
        "trainerOpenSettings": "Otevřít Settings",
        "trainerApplyHouse": "Použít House",
        "trainerApplyMatch": "Použít Match",
        "trainerApplyLanguage": "Použít Language",
        "trainerAdvanced": "Pokročilé JSON",
        "trainerStreaming": "Streamování…",
    },
    "sk": {
        "engineHint": "Hlas, jazyky a LLM sú tu. Home Assistant len pripája engine.",
        "languageHint": "Prázdny zoznam nechá každú skompilovanú Assist locale aktívnu. Pripnúť jeden pack je bežná domácnosť.",
        "personalityHa": "Hlas, jazyky a LLM sú na tejto stránke Settings.",
        "assistLanguages": "Jazyky Assist",
        "assistLanguagesHint": "Ktoré packy smie Klar parsovať. Satelit aj tak posiela jeden jazyk na požiadavku. Prázdne = všetky skompilované locale.",
        "allAssistLanguages": "Každá skompilovaná locale",
        "pinLanguage": "Pripnúť jeden pack",
        "voice": "Hlas",
        "voiceHint": "Osobnosť a hovorené odpovede. Assist to číta z enginu, nie z volieb Home Assistant.",
        "extraPrompt": "Extra prompt",
        "extraPromptHint": "Voliteľný riadok nad osobnosťou packu. Nechajte prázdne, ak dom nepotrebuje vlastné pravidlo.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM vylepšenie",
        "refineSpeechHint": "Klar ďalej ovláda zariadenia. LLM enginu potom prepíše hotové NLU odpovede týmto hlasom.",
        "quietAck": "Krátke potvrdenie",
        "quietAckHint": "Pri jednoduchom svetle alebo vypínači zapnúť/vypnúť preskoč TTS a prehraj zvonček na satelite.",
        "calendarLlm": "Kalendár cez LLM",
        "calendarLlmHint": "Klar kalendár ďalej číta. Zapnuté: LLM hovorí udalosti. Vypnuté: Klar hovorí zoznam.",
        "allowLlmTools": "Povoliť nástroje Assist v chate",
        "allowLlmToolsHint": "Predvolene vypnuté. Zapnuté: chatovací model smie ovládať Home Assistant. Vypnuté: Klar agenta s nástrojmi preskočí.",
        "missTitle": "Keď Klar mine",
        "missHint": "Voliteľné vrstvy po deterministickom odmietnutí. Žiadna z nich nedáva model na parse.",
        "operatorChrome": "Táto obrazovka",
        "operatorChromeHint": "Motív a jazyk rozhrania pre operátorov. Nie Assist.",
        "haGlueHint": "Home Assistant Configure potrebuje len URL enginu, token, kanál a voliteľného zvyšného conversation agenta. Hlas a LLM ostávajú tu.",
        "settingsGuide": "Nastav tieto tri, potom namapuj dom.",
        "settingsGuideVoice": "Hlas",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Jazyk Assist",
        "appearanceDark": "Tmavý",
        "appearanceLight": "Svetlý",
        "setupReplay": "Znova setup",
        "personalityDefault": "Normálny",
        "personalityButler": "Butler",
        "personalityLocker": "Uvoľnený",
        "personalityFuersorglich": "Starostlivý",
        "personalityParty": "Párty",
        "personalityGrantig": "Mrzutý",
        "personalitySarkastisch": "Sarkastický",
        "personalityPirat": "Pirát",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Jazyk operátora",
        "operatorLanguageHint": "Len táto aplikácia. Uložené tu, alebo KLAR_UI_LOCALE pred prvým uložením. Nie Assist, nie profil Home Assistant.",
        "nluRag": "Kontext domu pri miss",
        "modeFull": "Rozlíšiť zariadenia",
        "modeContext": "Len miestnosti",
        "inLab": "V laboratóriu",
        "undoLastCommand": "Vrátiť posledný príkaz",
        "applyDone": "Použité {count} návrhov miestností",
        "applyUndone": "Návrhy miestností vrátené",
        "applyUndoFailed": "Návrhy miestností sa nepodarilo vrátiť",
        "llm": "LLM",
        "llmHint": "Klar hovorí s OpenAI-kompatibilným endpointom. Chat Assist a tréner používajú rovnakú config. Integrácia OpenAI alebo Ollama v Home Assistant nie je potrebná.",
        "llmBaseUrl": "Základná URL",
        "llmModel": "Model",
        "llmApiKey": "API kľúč",
        "llmApiKeyHint": "Nechajte prázdne, aby ste ponechali uložený kľúč. Pri Ollama môže ostať prázdne.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Nastavené",
        "llmNotConfigured": "Nenastavené",
        "llmClear": "Vymazať",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Tréner",
        "trainerForLane": "Tréner pre túto stopu",
        "trainerHint": "Klar volá OpenAI-kompatibilný model v Ruste. Chatuj, over, potom použi po stopách. Integrácia LLM v Home Assistant nie je potrebná. Pokročilé JSON je pre debug.",
        "trainerContext": "Kontext",
        "trainerValidate": "Overiť",
        "trainerApply": "Použiť",
        "trainerProposal": "Návrh JSON",
        "trainerOk": "Platné",
        "trainerFail": "Neplatné",
        "trainerSend": "Odoslať",
        "trainerNeedLlm": "Najprv nastav LLM v Settings. Klar nepotrebuje ďalšiu conversation integráciu Home Assistant.",
        "trainerOpenSettings": "Otvoriť Settings",
        "trainerApplyHouse": "Použiť House",
        "trainerApplyMatch": "Použiť Match",
        "trainerApplyLanguage": "Použiť Language",
        "trainerAdvanced": "Pokročilé JSON",
        "trainerStreaming": "Streamovanie…",
    },
    "pl": {
        "engineHint": "Głos, języki i LLM są tutaj. Home Assistant tylko podłącza silnik.",
        "languageHint": "Pusta lista zostawia każdą skompilowaną locale Assist. Przypięcie jednego packa to zwykły dom.",
        "personalityHa": "Głos, języki i LLM są na tej stronie Settings.",
        "assistLanguages": "Języki Assist",
        "assistLanguagesHint": "Które packi Klar może parsować. Satelita i tak wysyła jeden język na żądanie. Puste = wszystkie skompilowane locale.",
        "allAssistLanguages": "Każda skompilowana locale",
        "pinLanguage": "Przypnij jeden pack",
        "voice": "Głos",
        "voiceHint": "Osobowość i mówione odpowiedzi. Assist czyta to z silnika, nie z opcji Home Assistant.",
        "extraPrompt": "Dodatkowy prompt",
        "extraPromptHint": "Opcjonalna linia nad osobowością packa. Zostaw puste, chyba że dom potrzebuje własnej reguły.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "Dopracowanie LLM",
        "refineSpeechHint": "Klar nadal steruje urządzeniami. LLM silnika przepisuje potem gotowe odpowiedzi NLU tym głosem.",
        "quietAck": "Krótkie potwierdzenie",
        "quietAckHint": "Przy prostym świetle lub włączniku on/off pomiń TTS i odegraj dzwonek na satelicie.",
        "calendarLlm": "Kalendarz przez LLM",
        "calendarLlmHint": "Klar nadal czyta kalendarz. Wł.: LLM mówi wydarzenia. Wył.: Klar mówi listę.",
        "allowLlmTools": "Zezwól na narzędzia Assist na czacie",
        "allowLlmToolsHint": "Domyślnie wył. Wł.: model czatu może sterować Home Assistant. Wył.: Klar pomija tego agenta, gdy ma narzędzia.",
        "missTitle": "Gdy Klar chybi",
        "missHint": "Opcjonalne warstwy po deterministycznym odrzuceniu. Żadna nie stawia modelu na parse.",
        "operatorChrome": "Ten ekran",
        "operatorChromeHint": "Motyw i język interfejsu dla operatorów. Nie Assist.",
        "haGlueHint": "Home Assistant Configure potrzebuje tylko URL silnika, tokenu, kanału i opcjonalnego pozostałego agenta rozmowy. Głos i LLM zostają tutaj.",
        "settingsGuide": "Ustaw te trzy, potem zmapuj dom.",
        "settingsGuideVoice": "Głos",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Język Assist",
        "appearanceDark": "Ciemny",
        "appearanceLight": "Jasny",
        "setupReplay": "Powtórz setup",
        "personalityDefault": "Zwykły",
        "personalityButler": "Butler",
        "personalityLocker": "Luźny",
        "personalityFuersorglich": "Troskliwy",
        "personalityParty": "Impreza",
        "personalityGrantig": "Zrzędliwy",
        "personalitySarkastisch": "Sarkastyczny",
        "personalityPirat": "Pirat",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Język operatora",
        "operatorLanguageHint": "Tylko ta aplikacja. Zapisane tutaj albo KLAR_UI_LOCALE przed pierwszym zapisem. Nie Assist, nie profil Home Assistant.",
        "nluRag": "Kontekst domu przy miss",
        "modeFull": "Rozwiąż urządzenia",
        "modeContext": "Tylko pomieszczenia",
        "inLab": "W laboratorium",
        "undoLastCommand": "Cofnij ostatnie polecenie",
        "applyDone": "Zastosowano {count} propozycji pomieszczeń",
        "applyUndone": "Propozycje pomieszczeń cofnięte",
        "applyUndoFailed": "Nie udało się cofnąć propozycji pomieszczeń",
        "llm": "LLM",
        "llmHint": "Klar rozmawia z endpointem zgodnym z OpenAI. Czat Assist i trener używają tej samej config. Integracja OpenAI lub Ollama w Home Assistant nie jest potrzebna.",
        "llmBaseUrl": "Bazowy URL",
        "llmModel": "Model",
        "llmApiKey": "Klucz API",
        "llmApiKeyHint": "Zostaw puste, aby zachować zapisany klucz. Ollama może zostać puste.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Skonfigurowane",
        "llmNotConfigured": "Nieskonfigurowane",
        "llmClear": "Wyczyść",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Trener",
        "trainerForLane": "Trener dla tego toru",
        "trainerHint": "Klar wywołuje model zgodny z OpenAI w Ruście. Czatuj, sprawdź, potem zastosuj na tor. Integracja LLM w Home Assistant nie jest potrzebna. Zaawansowany JSON jest do debugowania.",
        "trainerContext": "Kontekst",
        "trainerValidate": "Sprawdź",
        "trainerApply": "Zastosuj",
        "trainerProposal": "JSON propozycji",
        "trainerOk": "Poprawne",
        "trainerFail": "Niepoprawne",
        "trainerSend": "Wyślij",
        "trainerNeedLlm": "Najpierw skonfiguruj LLM w Settings. Klar nie potrzebuje innej integracji rozmowy Home Assistant.",
        "trainerOpenSettings": "Otwórz Settings",
        "trainerApplyHouse": "Zastosuj House",
        "trainerApplyMatch": "Zastosuj Match",
        "trainerApplyLanguage": "Zastosuj Language",
        "trainerAdvanced": "Zaawansowany JSON",
        "trainerStreaming": "Strumieniowanie…",
    },
    "hu": {
        "engineHint": "A hang, a nyelvek és az LLM itt van. A Home Assistant csak a motort köti be.",
        "languageHint": "Az üres lista minden lefordított Assist locale-t aktívan tart. Egy pack rögzítése a szokásos háztartás.",
        "personalityHa": "A hang, a nyelvek és az LLM ezen a Settings oldalon van.",
        "assistLanguages": "Assist nyelvek",
        "assistLanguagesHint": "Mely packokat elemezheti a Klar. A műhold attól még egy nyelvet küld kérésenként. Üres = minden lefordított locale.",
        "allAssistLanguages": "Minden lefordított locale",
        "pinLanguage": "Egy pack rögzítése",
        "voice": "Hang",
        "voiceHint": "Személyiség és beszélt válaszok. Az Assist a motorból olvassa, nem a Home Assistant beállításaiból.",
        "extraPrompt": "Extra prompt",
        "extraPromptHint": "Opcionális sor a pack személyisége fölött. Hagyd üresen, hacsak a háznak nincs saját szabálya.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM csiszolás",
        "refineSpeechHint": "A Klar továbbra is vezérli az eszközöket. A motor LLM-je ezután átírja a kész NLU válaszokat ezen a hangon.",
        "quietAck": "Rövid megerősítés",
        "quietAckHint": "Egyszerű lámpánál vagy kapcsolónál be/ki: hagyd ki a TTS-t, és játssz csengetést a műholdon.",
        "calendarLlm": "Naptár az LLM-en át",
        "calendarLlmHint": "A Klar továbbra is olvassa a naptárt. Be: az LLM mondja az eseményeket. Ki: a Klar mondja a listát.",
        "allowLlmTools": "Assist eszközök a csevegésen",
        "allowLlmToolsHint": "Alapból ki. Be: a csevegőmodell vezérelheti a Home Assistantot. Ki: a Klar kihagyja azt az ügynököt, ha eszközei vannak.",
        "missTitle": "Ha a Klar mellélő",
        "missHint": "Opcionális rétegek determinisztikus elutasítás után. Egyik sem tesz modellt a parse-ra.",
        "operatorChrome": "Ez a képernyő",
        "operatorChromeHint": "Téma és felület nyelve az operátoroknak. Nem Assist.",
        "haGlueHint": "A Home Assistant Configure-nak csak motor-URL, token, csatorna és opcionális maradék beszélgetési ügynök kell. Hang és LLM itt marad.",
        "settingsGuide": "Állítsd be ezt a hármat, aztán térképezd a házat.",
        "settingsGuideVoice": "Hang",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist nyelv",
        "appearanceDark": "Sötét",
        "appearanceLight": "Világos",
        "setupReplay": "Setup újra",
        "personalityDefault": "Normál",
        "personalityButler": "Butler",
        "personalityLocker": "Laza",
        "personalityFuersorglich": "Gondoskodó",
        "personalityParty": "Parti",
        "personalityGrantig": "Mogorva",
        "personalitySarkastisch": "Szarkasztikus",
        "personalityPirat": "Kalóz",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Operátor nyelve",
        "operatorLanguageHint": "Csak ez az app. Itt mentve, vagy KLAR_UI_LOCALE az első mentés előtt. Nem Assist, nem a Home Assistant profil.",
        "nluRag": "Háztartási kontextus missnél",
        "modeFull": "Eszközök feloldása",
        "modeContext": "Csak szobák",
        "inLab": "A laborban",
        "undoLastCommand": "Utolsó parancs visszavonása",
        "applyDone": "{count} szoba javaslat alkalmazva",
        "applyUndone": "Szoba javaslatok visszavonva",
        "applyUndoFailed": "A szoba javaslatokat nem lehetett visszavonni",
        "llm": "LLM",
        "llmHint": "A Klar egy OpenAI-kompatibilis végponttal beszél. Az Assist csevegés és a tréner ugyanazt a configot használja. Nincs szükség OpenAI- vagy Ollama-integrációra a Home Assistantban.",
        "llmBaseUrl": "Alap URL",
        "llmModel": "Modell",
        "llmApiKey": "API kulcs",
        "llmApiKeyHint": "Hagyd üresen a tárolt kulcs megtartásához. Az Ollama üresen maradhat.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Beállítva",
        "llmNotConfigured": "Nincs beállítva",
        "llmClear": "Törlés",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Tréner",
        "trainerForLane": "Tréner ehhez a sávhoz",
        "trainerHint": "A Klar OpenAI-kompatibilis modellt hív Rustban. Csevegj, ellenőrizd, majd alkalmazd sávonként. Nincs szükség Home Assistant LLM-integrációra. A haladó JSON hibakeresésre való.",
        "trainerContext": "Kontextus",
        "trainerValidate": "Ellenőrzés",
        "trainerApply": "Alkalmaz",
        "trainerProposal": "Javaslat JSON",
        "trainerOk": "Érvényes",
        "trainerFail": "Érvénytelen",
        "trainerSend": "Küldés",
        "trainerNeedLlm": "Először állíts be egy LLM-et a Settingsben. A Klarnak nincs szüksége másik Home Assistant beszélgetési integrációra.",
        "trainerOpenSettings": "Settings megnyitása",
        "trainerApplyHouse": "House alkalmazása",
        "trainerApplyMatch": "Match alkalmazása",
        "trainerApplyLanguage": "Language alkalmazása",
        "trainerAdvanced": "Haladó JSON",
        "trainerStreaming": "Streamelés…",
    },
    "hr": {
        "engineHint": "Glas, jezici i LLM su ovdje. Home Assistant samo spaja engine.",
        "languageHint": "Prazan popis ostavlja svaku kompajliranu Assist locale aktivnom. Prikvačiti jedan pack je uobičajeno kućanstvo.",
        "personalityHa": "Glas, jezici i LLM su na ovoj stranici Settings.",
        "assistLanguages": "Assist jezici",
        "assistLanguagesHint": "Koje packove Klar smije parsirati. Satelit i dalje šalje jedan jezik po zahtjevu. Prazno = sve kompajlirane locale.",
        "allAssistLanguages": "Svaka kompajlirana locale",
        "pinLanguage": "Prikvači jedan pack",
        "voice": "Glas",
        "voiceHint": "Osobnost i izgovoreni odgovori. Assist to čita iz enginea, ne iz opcija Home Assistant.",
        "extraPrompt": "Dodatni prompt",
        "extraPromptHint": "Neobavezni redak iznad osobnosti packa. Ostavi prazno osim ako kuća treba vlastilo pravilo.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM dorada",
        "refineSpeechHint": "Klar i dalje upravlja uređajima. LLM enginea zatim prepisuje gotove NLU odgovore ovim glasom.",
        "quietAck": "Kratka potvrda",
        "quietAckHint": "Kod jednostavnog svjetla ili prekidača uklj/isklj preskoči TTS i pusti zvono na satelitu.",
        "calendarLlm": "Kalendar kroz LLM",
        "calendarLlmHint": "Klar i dalje čita kalendar. Uklj.: LLM govori događaje. Isklj.: Klar govori popis.",
        "allowLlmTools": "Dopusti alate Assist u chatu",
        "allowLlmToolsHint": "Zadano isključeno. Uklj.: chat model smije upravljati Home Assistantom. Isklj.: Klar preskače tog agenta ako ima alate.",
        "missTitle": "Kad Klar promaši",
        "missHint": "Neobavezni slojevi nakon determinističkog odbijanja. Nijedan ne stavlja model na parse.",
        "operatorChrome": "Ovaj zaslon",
        "operatorChromeHint": "Tema i jezik sučelja za operatore. Ne Assist.",
        "haGlueHint": "Home Assistant Configure treba samo URL enginea, token, kanal i neobaveznog preostalog conversation agenta. Glas i LLM ostaju ovdje.",
        "settingsGuide": "Postavi ova tri, zatim mapiraj kuću.",
        "settingsGuideVoice": "Glas",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist jezik",
        "appearanceDark": "Tamno",
        "appearanceLight": "Svijetlo",
        "setupReplay": "Ponovi setup",
        "personalityDefault": "Normalno",
        "personalityButler": "Butler",
        "personalityLocker": "Opusteno",
        "personalityFuersorglich": "Briga",
        "personalityParty": "Zabava",
        "personalityGrantig": "Mrzovoljan",
        "personalitySarkastisch": "Sarkastičan",
        "personalityPirat": "Pirat",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Jezik operatora",
        "operatorLanguageHint": "Samo ova aplikacija. Spremljeno ovdje ili KLAR_UI_LOCALE prije prvog spremanja. Ne Assist, ne profil Home Assistant.",
        "nluRag": "Kontekst kuće pri missu",
        "modeFull": "Razriješi uređaje",
        "modeContext": "Samo prostorije",
        "inLab": "U labosu",
        "undoLastCommand": "Poništi zadnju naredbu",
        "applyDone": "Primijenjeno {count} prijedloga prostorija",
        "applyUndone": "Prijedlozi prostorija poništeni",
        "applyUndoFailed": "Prijedloge prostorija nije bilo moguće poništiti",
        "llm": "LLM",
        "llmHint": "Klar razgovara s OpenAI-kompatibilnom krajnjom točkom. Assist chat i trener koriste istu config. Integracija OpenAI ili Ollama u Home Assistant nije potrebna.",
        "llmBaseUrl": "Osnovni URL",
        "llmModel": "Model",
        "llmApiKey": "API ključ",
        "llmApiKeyHint": "Ostavi prazno da zadržiš spremljeni ključ. Ollama može ostati prazan.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Konfigurirano",
        "llmNotConfigured": "Nije konfigurirano",
        "llmClear": "Očisti",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Trener",
        "trainerForLane": "Trener za ovu traku",
        "trainerHint": "Klar zove OpenAI-kompatibilan model u Rustu. Chat, provjeri, zatim primijeni po traci. Integracija LLM u Home Assistant nije potrebna. Napredni JSON je za debug.",
        "trainerContext": "Kontekst",
        "trainerValidate": "Provjeri",
        "trainerApply": "Primijeni",
        "trainerProposal": "JSON prijedloga",
        "trainerOk": "Valjano",
        "trainerFail": "Nevaljano",
        "trainerSend": "Pošalji",
        "trainerNeedLlm": "Prvo konfiguriraj LLM u Settings. Klar ne treba drugu Home Assistant integraciju razgovora.",
        "trainerOpenSettings": "Otvori Settings",
        "trainerApplyHouse": "Primijeni House",
        "trainerApplyMatch": "Primijeni Match",
        "trainerApplyLanguage": "Primijeni Language",
        "trainerAdvanced": "Napredni JSON",
        "trainerStreaming": "Strujanje…",
    },
    "sl": {
        "engineHint": "Glas, jeziki in LLM so tukaj. Home Assistant samo poveže pogon.",
        "languageHint": "Prazen seznam pusti vsako prevedeno Assist locale aktivno. Pripni en pack je običajno gospodinjstvo.",
        "personalityHa": "Glas, jeziki in LLM so na tej strani Settings.",
        "assistLanguages": "Jeziki Assist",
        "assistLanguagesHint": "Katere packe sme Klar razčleniti. Satelit vseeno pošlje en jezik na zahtevo. Prazno = vse prevedene locale.",
        "allAssistLanguages": "Vsaka prevedena locale",
        "pinLanguage": "Pripni en pack",
        "voice": "Glas",
        "voiceHint": "Osebnost in govorjeni odgovori. Assist to bere iz pogona, ne iz možnosti Home Assistant.",
        "extraPrompt": "Dodatni prompt",
        "extraPromptHint": "Izbirna vrstica nad osebnostjo packa. Pustite prazno, razen če hiša potrebuje lastno pravilo.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM izpilitev",
        "refineSpeechHint": "Klar še vedno krmili naprave. LLM pogona nato prepiše končane NLU odgovore s tem glasom.",
        "quietAck": "Kratka potrditev",
        "quietAckHint": "Pri preprosti luči ali stikalu vklop/izklop preskoči TTS in predvajaj zvonec na satelitu.",
        "calendarLlm": "Koledar prek LLM",
        "calendarLlmHint": "Klar koledar še bere. Vkl.: LLM pove dogodke. Izkl.: Klar pove seznam.",
        "allowLlmTools": "Dovoli orodja Assist v klepetu",
        "allowLlmToolsHint": "Privzeto izklopljeno. Vkl.: klepetalni model sme krmiliti Home Assistant. Izkl.: Klar agenta z orodji preskoči.",
        "missTitle": "Ko Klar zgreši",
        "missHint": "Izbirne plasti po deterministični zavrnitvi. Nobena ne postavi modela na parse.",
        "operatorChrome": "Ta zaslon",
        "operatorChromeHint": "Tema in jezik vmesnika za operatorje. Ne Assist.",
        "haGlueHint": "Home Assistant Configure potrebuje samo URL pogona, žeton, kanal in izbirnega preostalega agenta za pogovor. Glas in LLM ostaneta tukaj.",
        "settingsGuide": "Nastavi te tri, nato preslikaj hišo.",
        "settingsGuideVoice": "Glas",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Jezik Assist",
        "appearanceDark": "Temno",
        "appearanceLight": "Svetlo",
        "setupReplay": "Ponovi setup",
        "personalityDefault": "Običajno",
        "personalityButler": "Butler",
        "personalityLocker": "Sproščeno",
        "personalityFuersorglich": "Skrbno",
        "personalityParty": "Zabava",
        "personalityGrantig": "Godrnjavo",
        "personalitySarkastisch": "Sarkastično",
        "personalityPirat": "Pirat",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Jezik operatorja",
        "operatorLanguageHint": "Samo ta aplikacija. Shranjeno tukaj ali KLAR_UI_LOCALE pred prvim shranjevanjem. Ne Assist, ne profil Home Assistant.",
        "nluRag": "Kontekst hiše ob miss",
        "modeFull": "Razreši naprave",
        "modeContext": "Samo prostori",
        "inLab": "V laboratoriju",
        "undoLastCommand": "Razveljavi zadnji ukaz",
        "applyDone": "Uporabljenih {count} predlogov prostorov",
        "applyUndone": "Predlogi prostorov razveljavljeni",
        "applyUndoFailed": "Predlogov prostorov ni bilo mogoče razveljaviti",
        "llm": "LLM",
        "llmHint": "Klar govori z OpenAI-združljivo končno točko. Klepet Assist in trener uporabljata isto config. Integracija OpenAI ali Ollama v Home Assistant ni potrebna.",
        "llmBaseUrl": "Osnovni URL",
        "llmModel": "Model",
        "llmApiKey": "API ključ",
        "llmApiKeyHint": "Pustite prazno, da obdržite shranjeni ključ. Ollama lahko ostane prazen.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Nastavljeno",
        "llmNotConfigured": "Ni nastavljeno",
        "llmClear": "Počisti",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Trener",
        "trainerForLane": "Trener za to stezo",
        "trainerHint": "Klar kliče OpenAI-združljiv model v Rustu. Klepetaj, preveri, nato uporabi po stezah. Integracija LLM v Home Assistant ni potrebna. Napredni JSON je za razhroščevanje.",
        "trainerContext": "Kontekst",
        "trainerValidate": "Preveri",
        "trainerApply": "Uporabi",
        "trainerProposal": "JSON predloga",
        "trainerOk": "Veljavno",
        "trainerFail": "Neveljavno",
        "trainerSend": "Pošlji",
        "trainerNeedLlm": "Najprej nastavi LLM v Settings. Klar ne potrebuje druge integracije pogovora Home Assistant.",
        "trainerOpenSettings": "Odpri Settings",
        "trainerApplyHouse": "Uporabi House",
        "trainerApplyMatch": "Uporabi Match",
        "trainerApplyLanguage": "Uporabi Language",
        "trainerAdvanced": "Napredni JSON",
        "trainerStreaming": "Pretakanje…",
    },
    "bg": {
        "engineHint": "Гласът, езиците и LLM са тук. Home Assistant само свързва двигателя.",
        "languageHint": "Празен списък оставя всяка компилирана Assist locale активна. Закачането на един pack е обичайният дом.",
        "personalityHa": "Гласът, езиците и LLM са на тази страница Settings.",
        "assistLanguages": "Езици на Assist",
        "assistLanguagesHint": "Кои pack-ове Klar може да разборва. Сателитът пак изпраща един език на заявка. Празно = всички компилирани locale.",
        "allAssistLanguages": "Всяка компилирана locale",
        "pinLanguage": "Закачи един pack",
        "voice": "Глас",
        "voiceHint": "Личност и изговорени отговори. Assist ги чете от двигателя, не от опциите на Home Assistant.",
        "extraPrompt": "Допълнителен prompt",
        "extraPromptHint": "Незадължителен ред върху личността на pack-а. Оставете празно, освен ако домът няма собствено правило.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM изглаждане",
        "refineSpeechHint": "Klar продължава да управлява устройствата. LLM на двигателя после пренаписва готовите NLU отговори с този глас.",
        "quietAck": "Кратко потвърждение",
        "quietAckHint": "При проста лампа или ключ вкл/изкл пропусни TTS и пусни звън на сателита.",
        "calendarLlm": "Календар през LLM",
        "calendarLlmHint": "Klar продължава да чете календара. Вкл.: LLM казва събитията. Изкл.: Klar казва списъка.",
        "allowLlmTools": "Позволи инструменти Assist в чата",
        "allowLlmToolsHint": "По подразбиране изкл. Вкл.: чат моделът може да управлява Home Assistant. Изкл.: Klar пропуска този агент, ако има инструменти.",
        "missTitle": "Когато Klar пропуска",
        "missHint": "Незадължителни слоеве след детерминистичен отказ. Никой не слага модел върху parse.",
        "operatorChrome": "Този екран",
        "operatorChromeHint": "Тема и език на интерфейса за оператори. Не Assist.",
        "haGlueHint": "Home Assistant Configure трябва само URL на двигателя, токен, канал и незадължителен останал агент за разговор. Гласът и LLM остават тук.",
        "settingsGuide": "Задай тези три, после картирай къщата.",
        "settingsGuideVoice": "Глас",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Език Assist",
        "appearanceDark": "Тъмна",
        "appearanceLight": "Светла",
        "setupReplay": "Повтори setup",
        "personalityDefault": "Нормален",
        "personalityButler": "Butler",
        "personalityLocker": "Непринуден",
        "personalityFuersorglich": "Грижовен",
        "personalityParty": "Купон",
        "personalityGrantig": "Ръмжащ",
        "personalitySarkastisch": "Саркастичен",
        "personalityPirat": "Пират",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Език на оператора",
        "operatorLanguageHint": "Само това приложение. Записано тук или KLAR_UI_LOCALE преди първото записване. Не Assist, не профилът на Home Assistant.",
        "nluRag": "Контекст на къщата при miss",
        "modeFull": "Разреши устройства",
        "modeContext": "Само стаи",
        "inLab": "В лабораторията",
        "undoLastCommand": "Отмени последната команда",
        "applyDone": "Приложени {count} предложения за стаи",
        "applyUndone": "Предложенията за стаи са отменени",
        "applyUndoFailed": "Предложенията за стаи не можаха да се отменят",
        "llm": "LLM",
        "llmHint": "Klar говори с крайна точка, съвместима с OpenAI. Чатът Assist и треньорът ползват същата config. Не е нужна интеграция OpenAI или Ollama в Home Assistant.",
        "llmBaseUrl": "Базов URL",
        "llmModel": "Модел",
        "llmApiKey": "API ключ",
        "llmApiKeyHint": "Остави празно, за да запазиш съхранения ключ. При Ollama може да остане празно.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Настроено",
        "llmNotConfigured": "Не е настроено",
        "llmClear": "Изчисти",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Треньор",
        "trainerForLane": "Треньор за тази лента",
        "trainerHint": "Klar вика модел, съвместим с OpenAI, в Rust. Чат, проверка, после прилагане по лента. Не е нужна LLM интеграция в Home Assistant. Разширеният JSON е за debug.",
        "trainerContext": "Контекст",
        "trainerValidate": "Провери",
        "trainerApply": "Приложи",
        "trainerProposal": "JSON на предложение",
        "trainerOk": "Валидно",
        "trainerFail": "Невалидно",
        "trainerSend": "Изпрати",
        "trainerNeedLlm": "Първо настрой LLM в Settings. Klar няма нужда от друга интеграция за разговор в Home Assistant.",
        "trainerOpenSettings": "Отвори Settings",
        "trainerApplyHouse": "Приложи House",
        "trainerApplyMatch": "Приложи Match",
        "trainerApplyLanguage": "Приложи Language",
        "trainerAdvanced": "Разширен JSON",
        "trainerStreaming": "Поток…",
    },
    "sr": {
        "engineHint": "Глас, језици и LLM су овде. Home Assistant само повезује погон.",
        "languageHint": "Празан списак оставља сваку компајлирану Assist locale активном. Закачити један pack је уобичајено домаћинство.",
        "personalityHa": "Глас, језици и LLM су на овој страници Settings.",
        "assistLanguages": "Језици Assist",
        "assistLanguagesHint": "Које pack-ове Klar сме да рашчлани. Сателит и даље шаље један језик по захтеву. Празно = све компајлиране locale.",
        "allAssistLanguages": "Свака компајлирана locale",
        "pinLanguage": "Закачи један pack",
        "voice": "Глас",
        "voiceHint": "Личност и изговорени одговори. Assist то чита из погона, не из опција Home Assistant.",
        "extraPrompt": "Додатни prompt",
        "extraPromptHint": "Опционалан ред изнад личности pack-а. Остави празно осим ако кућа треба сопствено правило.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM дорада",
        "refineSpeechHint": "Klar и даље управља уређајима. LLM погона затим преписује готове NLU одговоре овим гласом.",
        "quietAck": "Кратка потврда",
        "quietAckHint": "Код простог светла или прекидача укљ/искљ прескочи TTS и пусти звоно на сателиту.",
        "calendarLlm": "Календар кроз LLM",
        "calendarLlmHint": "Klar и даље чита календар. Укљ.: LLM говори догађаје. Искљ.: Klar говори списак.",
        "allowLlmTools": "Дозволи алате Assist у ћаскању",
        "allowLlmToolsHint": "Подразумевано искључено. Укљ.: модел ћаскања сме да управља Home Assistant. Искљ.: Klar прескаче тог агента ако има алате.",
        "missTitle": "Кад Klar промаши",
        "missHint": "Опционални слојеви после детерминистичког одбијања. Ниједан не ставља модел на parse.",
        "operatorChrome": "Овај екран",
        "operatorChromeHint": "Тема и језик сучеља за операторе. Не Assist.",
        "haGlueHint": "Home Assistant Configure треба само URL погона, токен, канал и опционалног преосталог агента за разговор. Глас и LLM остају овде.",
        "settingsGuide": "Подеси ова три, затим мапирај кућу.",
        "settingsGuideVoice": "Глас",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Језик Assist",
        "appearanceDark": "Тамно",
        "appearanceLight": "Светло",
        "setupReplay": "Понови setup",
        "personalityDefault": "Обичан",
        "personalityButler": "Butler",
        "personalityLocker": "Опуштен",
        "personalityFuersorglich": "Брижан",
        "personalityParty": "Журка",
        "personalityGrantig": "Мрзовољан",
        "personalitySarkastisch": "Саркастичан",
        "personalityPirat": "Пират",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Језик оператора",
        "operatorLanguageHint": "Само ова апликација. Сачувано овде или KLAR_UI_LOCALE пре првог чувања. Не Assist, не профил Home Assistant.",
        "nluRag": "Контекст куће при miss",
        "modeFull": "Разреши уређаје",
        "modeContext": "Само просторије",
        "inLab": "У лабораторији",
        "undoLastCommand": "Опозови последњу наредбу",
        "applyDone": "Примењено {count} предлога просторија",
        "applyUndone": "Предлози просторија опозвани",
        "applyUndoFailed": "Предлоге просторија није било могуће опозвати",
        "llm": "LLM",
        "llmHint": "Klar разговара са крајњом тачком компатибилном са OpenAI. Ћаскање Assist и тренер користе исту config. Интеграција OpenAI или Ollama у Home Assistant није потребна.",
        "llmBaseUrl": "Основни URL",
        "llmModel": "Модел",
        "llmApiKey": "API кључ",
        "llmApiKeyHint": "Остави празно да задржиш сачувани кључ. Ollama може остати празан.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Подешено",
        "llmNotConfigured": "Није подешено",
        "llmClear": "Обриши",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Тренер",
        "trainerForLane": "Тренер за ову траку",
        "trainerHint": "Klar зове модел компатибилан са OpenAI у Rust-у. Ћаскај, провери, затим примени по траци. Интеграција LLM у Home Assistant није потребна. Напредни JSON је за debug.",
        "trainerContext": "Контекст",
        "trainerValidate": "Провери",
        "trainerApply": "Примени",
        "trainerProposal": "JSON предлога",
        "trainerOk": "Исправно",
        "trainerFail": "Неисправно",
        "trainerSend": "Пошаљи",
        "trainerNeedLlm": "Прво подеси LLM у Settings. Klar не треба другу интеграцију разговора Home Assistant.",
        "trainerOpenSettings": "Отвори Settings",
        "trainerApplyHouse": "Примени House",
        "trainerApplyMatch": "Примени Match",
        "trainerApplyLanguage": "Примени Language",
        "trainerAdvanced": "Напредни JSON",
        "trainerStreaming": "Стримовање…",
    },
    "sr-Latn": {
        "engineHint": "Glas, jezici i LLM su ovde. Home Assistant samo povezuje pogon.",
        "languageHint": "Prazan spisak ostavlja svaku kompajliranu Assist locale aktivnom. Zakačiti jedan pack je uobičajeno domaćinstvo.",
        "personalityHa": "Glas, jezici i LLM su na ovoj stranici Settings.",
        "assistLanguages": "Jezici Assist",
        "assistLanguagesHint": "Koje pack-ove Klar sme da raščlani. Satelit i dalje šalje jedan jezik po zahtevu. Prazno = sve kompajlirane locale.",
        "allAssistLanguages": "Svaka kompajlirana locale",
        "pinLanguage": "Zakači jedan pack",
        "voice": "Glas",
        "voiceHint": "Ličnost i izgovoreni odgovori. Assist to čita iz pogona, ne iz opcija Home Assistant.",
        "extraPrompt": "Dodatni prompt",
        "extraPromptHint": "Opcionalan red iznad ličnosti pack-a. Ostavi prazno osim ako kuća treba sopstveno pravilo.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM dorada",
        "refineSpeechHint": "Klar i dalje upravlja uređajima. LLM pogona zatim prepisuje gotove NLU odgovore ovim glasom.",
        "quietAck": "Kratka potvrda",
        "quietAckHint": "Kod prostog svetla ili prekidača uklj/isklj preskoči TTS i pusti zvono na satelitu.",
        "calendarLlm": "Kalendar kroz LLM",
        "calendarLlmHint": "Klar i dalje čita kalendar. Uklj.: LLM govori događaje. Isklj.: Klar govori spisak.",
        "allowLlmTools": "Dozvoli alate Assist u ćaskanju",
        "allowLlmToolsHint": "Podrazumevano isključeno. Uklj.: model ćaskanja sme da upravlja Home Assistant. Isklj.: Klar preskače tog agenta ako ima alate.",
        "missTitle": "Kad Klar promaši",
        "missHint": "Opcionalni slojevi posle determinističkog odbijanja. Nijedan ne stavlja model na parse.",
        "operatorChrome": "Ovaj ekran",
        "operatorChromeHint": "Tema i jezik sučelja za operatore. Ne Assist.",
        "haGlueHint": "Home Assistant Configure treba samo URL pogona, token, kanal i opcionalnog preostalog agenta za razgovor. Glas i LLM ostaju ovde.",
        "settingsGuide": "Podesi ova tri, zatim mapiraj kuću.",
        "settingsGuideVoice": "Glas",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Jezik Assist",
        "appearanceDark": "Tamno",
        "appearanceLight": "Svetlo",
        "setupReplay": "Ponovi setup",
        "personalityDefault": "Običan",
        "personalityButler": "Butler",
        "personalityLocker": "Opušten",
        "personalityFuersorglich": "Brižan",
        "personalityParty": "Žurka",
        "personalityGrantig": "Mrzovoljan",
        "personalitySarkastisch": "Sarkastičan",
        "personalityPirat": "Pirat",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Jezik operatora",
        "operatorLanguageHint": "Samo ova aplikacija. Sačuvano ovde ili KLAR_UI_LOCALE pre prvog čuvanja. Ne Assist, ne profil Home Assistant.",
        "nluRag": "Kontekst kuće pri miss",
        "modeFull": "Razreši uređaje",
        "modeContext": "Samo prostorije",
        "inLab": "U laboratoriji",
        "undoLastCommand": "Opozovi poslednju naredbu",
        "applyDone": "Primenjeno {count} predloga prostorija",
        "applyUndone": "Predlozi prostorija opozvani",
        "applyUndoFailed": "Predloge prostorija nije bilo moguće opozvati",
        "llm": "LLM",
        "llmHint": "Klar razgovara sa krajnjom tačkom kompatibilnom sa OpenAI. Ćaskanje Assist i trener koriste istu config. Integracija OpenAI ili Ollama u Home Assistant nije potrebna.",
        "llmBaseUrl": "Osnovni URL",
        "llmModel": "Model",
        "llmApiKey": "API ključ",
        "llmApiKeyHint": "Ostavi prazno da zadržiš sačuvani ključ. Ollama može ostati prazan.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Podešeno",
        "llmNotConfigured": "Nije podešeno",
        "llmClear": "Obriši",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Trener",
        "trainerForLane": "Trener za ovu traku",
        "trainerHint": "Klar zove model kompatibilan sa OpenAI u Rust-u. Ćaskaj, proveri, zatim primeni po traci. Integracija LLM u Home Assistant nije potrebna. Napredni JSON je za debug.",
        "trainerContext": "Kontekst",
        "trainerValidate": "Proveri",
        "trainerApply": "Primeni",
        "trainerProposal": "JSON predloga",
        "trainerOk": "Ispravno",
        "trainerFail": "Neispravno",
        "trainerSend": "Pošalji",
        "trainerNeedLlm": "Prvo podesi LLM u Settings. Klar ne treba drugu integraciju razgovora Home Assistant.",
        "trainerOpenSettings": "Otvori Settings",
        "trainerApplyHouse": "Primeni House",
        "trainerApplyMatch": "Primeni Match",
        "trainerApplyLanguage": "Primeni Language",
        "trainerAdvanced": "Napredni JSON",
        "trainerStreaming": "Strimovanje…",
    },
    "uk": {
        "engineHint": "Голос, мови й LLM тут. Home Assistant лише підключає рушій.",
        "languageHint": "Порожній список лишає кожну скомпільовану Assist locale активною. Закріпити один pack — звичайне господарство.",
        "personalityHa": "Голос, мови й LLM на цій сторінці Settings.",
        "assistLanguages": "Мови Assist",
        "assistLanguagesHint": "Які pack Klar може розбирати. Супутник усе одно надсилає одну мову на запит. Порожньо = усі скомпільовані locale.",
        "allAssistLanguages": "Кожна скомпільована locale",
        "pinLanguage": "Закріпити один pack",
        "voice": "Голос",
        "voiceHint": "Особистість і сказані відповіді. Assist читає це з рушія, не з опцій Home Assistant.",
        "extraPrompt": "Додатковий prompt",
        "extraPromptHint": "Необов’язковий рядок поверх особистості pack. Залиш порожнім, якщо дім не потребує власного правила.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM шліфування",
        "refineSpeechHint": "Klar і далі керує пристроями. LLM рушія потім переписує готові NLU-відповіді цим голосом.",
        "quietAck": "Коротке підтвердження",
        "quietAckHint": "На простому світлі чи вимикачі вкл/викл пропусти TTS і зіграй дзвіночок на супутнику.",
        "calendarLlm": "Календар через LLM",
        "calendarLlmHint": "Klar і далі читає календар. Увімк.: LLM озвучує події. Вимк.: Klar озвучує список.",
        "allowLlmTools": "Дозволити інструменти Assist у чаті",
        "allowLlmToolsHint": "Типово вимкнено. Увімк.: модель чату може керувати Home Assistant. Вимк.: Klar пропускає того агента, якщо в нього є інструменти.",
        "missTitle": "Коли Klar хибить",
        "missHint": "Необов’язкові шари після детерміністичної відмови. Жоден не ставить модель на parse.",
        "operatorChrome": "Цей екран",
        "operatorChromeHint": "Тема й мова інтерфейсу для операторів. Не Assist.",
        "haGlueHint": "Home Assistant Configure потребує лише URL рушія, токен, канал і необов’язкового залишкового агента розмови. Голос і LLM лишаються тут.",
        "settingsGuide": "Задай ці три, потім нанеси дім.",
        "settingsGuideVoice": "Голос",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Мова Assist",
        "appearanceDark": "Темна",
        "appearanceLight": "Світла",
        "setupReplay": "Повторити setup",
        "personalityDefault": "Звичайний",
        "personalityButler": "Butler",
        "personalityLocker": "Невимушений",
        "personalityFuersorglich": "Турботливий",
        "personalityParty": "Вечірка",
        "personalityGrantig": "Буркітливий",
        "personalitySarkastisch": "Саркастичний",
        "personalityPirat": "Пірат",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Мова оператора",
        "operatorLanguageHint": "Лише цей застосунок. Збережено тут або KLAR_UI_LOCALE перед першим збереженням. Не Assist, не профіль Home Assistant.",
        "nluRag": "Контекст дому при miss",
        "modeFull": "Розв’язати пристрої",
        "modeContext": "Лише кімнати",
        "inLab": "У лабораторії",
        "undoLastCommand": "Скасувати останню команду",
        "applyDone": "Застосовано {count} пропозицій кімнат",
        "applyUndone": "Пропозиції кімнат скасовано",
        "applyUndoFailed": "Не вдалося скасувати пропозиції кімнат",
        "llm": "LLM",
        "llmHint": "Klar розмовляє з кінцевою точкою, сумісною з OpenAI. Чат Assist і тренер використовують ту саму config. Інтеграція OpenAI чи Ollama у Home Assistant не потрібна.",
        "llmBaseUrl": "Базовий URL",
        "llmModel": "Модель",
        "llmApiKey": "Ключ API",
        "llmApiKeyHint": "Залиш порожнім, щоб зберегти збережений ключ. Ollama може лишитися порожнім.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Налаштовано",
        "llmNotConfigured": "Не налаштовано",
        "llmClear": "Очистити",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Тренер",
        "trainerForLane": "Тренер для цієї смуги",
        "trainerHint": "Klar викликає модель, сумісну з OpenAI, у Rust. Чат, перевірка, потім застосувати по смугах. Інтеграція LLM у Home Assistant не потрібна. Розширений JSON — для налагодження.",
        "trainerContext": "Контекст",
        "trainerValidate": "Перевірити",
        "trainerApply": "Застосувати",
        "trainerProposal": "JSON пропозиції",
        "trainerOk": "Чинне",
        "trainerFail": "Нечинне",
        "trainerSend": "Надіслати",
        "trainerNeedLlm": "Спочатку налаштуй LLM у Settings. Klar не потребує іншої інтеграції розмови Home Assistant.",
        "trainerOpenSettings": "Відкрити Settings",
        "trainerApplyHouse": "Застосувати House",
        "trainerApplyMatch": "Застосувати Match",
        "trainerApplyLanguage": "Застосувати Language",
        "trainerAdvanced": "Розширений JSON",
        "trainerStreaming": "Потік…",
    },
    "zh-CN": {
        "engineHint": "语音、语言和 LLM 都在这里。Home Assistant 只负责连接引擎。",
        "languageHint": "空列表会保留每个已编译的 Assist 语言区域。钉住一个语言包是常见家庭用法。",
        "personalityHa": "语音、语言和 LLM 都在这个 Settings 页。",
        "assistLanguages": "Assist 语言",
        "assistLanguagesHint": "Klar 可以解析哪些语言包。卫星仍按每次请求发送一种语言。空 = 全部已编译语言区域。",
        "allAssistLanguages": "全部已编译语言区域",
        "pinLanguage": "钉住一个语言包",
        "voice": "语音",
        "voiceHint": "人格和口播回复。Assist 从引擎读取，不从 Home Assistant 选项读取。",
        "extraPrompt": "额外提示",
        "extraPromptHint": "叠在语言包人格之上的可选一行。没有宅规就留空。",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM 润色",
        "refineSpeechHint": "Klar 仍控制设备。引擎 LLM 再用这个声音改写已完成的 NLU 回复。",
        "quietAck": "简短确认",
        "quietAckHint": "简单灯或开关开/关时，跳过 TTS，在卫星上播放一声提示音。",
        "calendarLlm": "日历走 LLM",
        "calendarLlmHint": "Klar 仍读取日历。开：由 LLM 口述事件。关：由 Klar 念列表。",
        "allowLlmTools": "聊天时允许 Assist 工具",
        "allowLlmToolsHint": "默认关闭。开：聊天模型可以控制 Home Assistant。关：该代理带工具时 Klar 会跳过它。",
        "missTitle": "当 Klar 没听懂",
        "missHint": "确定性拒绝之后的可选层。这些都不会把模型放到解析上。",
        "operatorChrome": "这个界面",
        "operatorChromeHint": "操作员的主题和界面语言。不是 Assist。",
        "haGlueHint": "Home Assistant Configure 只需要引擎 URL、令牌、通道，以及可选的残留对话代理。语音和 LLM 留在这里。",
        "settingsGuide": "先设这三项，再对照住宅。",
        "settingsGuideVoice": "语音",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist 语言",
        "appearanceDark": "深色",
        "appearanceLight": "浅色",
        "setupReplay": "重放设置向导",
        "personalityDefault": "普通",
        "personalityButler": "Butler",
        "personalityLocker": "随意",
        "personalityFuersorglich": "体贴",
        "personalityParty": "派对",
        "personalityGrantig": "牢骚",
        "personalitySarkastisch": "讽刺",
        "personalityPirat": "海盗",
        "personalityHippie": "嬉皮",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "操作员语言",
        "operatorLanguageHint": "仅此应用。保存在这里，或首次保存前用 KLAR_UI_LOCALE。不是 Assist，也不是 Home Assistant 个人资料。",
        "nluRag": "未命中时使用住宅上下文",
        "modeFull": "解析设备",
        "modeContext": "仅房间",
        "inLab": "在实验室",
        "undoLastCommand": "撤销上一条命令",
        "applyDone": "已应用 {count} 条房间建议",
        "applyUndone": "已撤销房间建议",
        "applyUndoFailed": "无法撤销房间建议",
        "llm": "LLM",
        "llmHint": "Klar 连接兼容 OpenAI 的端点。Assist 聊天和训练器共用这份配置。不需要 Home Assistant 的 OpenAI 或 Ollama 集成。",
        "llmBaseUrl": "基础 URL",
        "llmModel": "模型",
        "llmApiKey": "API 密钥",
        "llmApiKeyHint": "留空以保留已存储的密钥。Ollama 可以一直为空。",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "已配置",
        "llmNotConfigured": "未配置",
        "llmClear": "清除",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "训练器",
        "trainerForLane": "此通道的训练器",
        "trainerHint": "Klar 在 Rust 中调用兼容 OpenAI 的模型。先聊天、校验，再按通道应用。不需要 Home Assistant 的 LLM 集成。高级 JSON 仅供调试。",
        "trainerContext": "上下文",
        "trainerValidate": "校验",
        "trainerApply": "应用",
        "trainerProposal": "提案 JSON",
        "trainerOk": "有效",
        "trainerFail": "无效",
        "trainerSend": "发送",
        "trainerNeedLlm": "请先在 Settings 中配置 LLM。Klar 不需要另一个 Home Assistant 对话集成。",
        "trainerOpenSettings": "打开 Settings",
        "trainerApplyHouse": "应用 House",
        "trainerApplyMatch": "应用 Match",
        "trainerApplyLanguage": "应用 Language",
        "trainerAdvanced": "高级 JSON",
        "trainerStreaming": "正在流式传输…",
    },
    "zh-TW": {
        "engineHint": "語音、語言和 LLM 都在這裡。Home Assistant 只負責連接引擎。",
        "languageHint": "空白清單會保留每個已編譯的 Assist 語系。釘住一個語言包是常見家庭用法。",
        "personalityHa": "語音、語言和 LLM 都在這個 Settings 頁。",
        "assistLanguages": "Assist 語言",
        "assistLanguagesHint": "Klar 可以解析哪些語言包。衛星仍依每次請求傳送一種語言。空白 = 全部已編譯語系。",
        "allAssistLanguages": "全部已編譯語系",
        "pinLanguage": "釘住一個語言包",
        "voice": "語音",
        "voiceHint": "人格與口播回覆。Assist 從引擎讀取，不是從 Home Assistant 選項。",
        "extraPrompt": "額外提示",
        "extraPromptHint": "疊在語言包人格之上的可選一行。沒有宅規就留空。",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM 潤飾",
        "refineSpeechHint": "Klar 仍控制裝置。引擎 LLM 再用這個聲音改寫已完成的 NLU 回覆。",
        "quietAck": "簡短確認",
        "quietAckHint": "簡單燈或開關開／關時，略過 TTS，在衛星上播放一聲提示音。",
        "calendarLlm": "日曆走 LLM",
        "calendarLlmHint": "Klar 仍讀取日曆。開：由 LLM 唸事件。關：由 Klar 唸清單。",
        "allowLlmTools": "聊天時允許 Assist 工具",
        "allowLlmToolsHint": "預設關閉。開：聊天模型可以控制 Home Assistant。關：該代理帶工具時 Klar 會跳過它。",
        "missTitle": "當 Klar 沒聽懂",
        "missHint": "確定性拒絕之後的可選層。這些都不會把模型放到解析上。",
        "operatorChrome": "這個畫面",
        "operatorChromeHint": "操作員的主題與介面語言。不是 Assist。",
        "haGlueHint": "Home Assistant Configure 只需要引擎 URL、權杖、頻道，以及可選的殘留對話代理。語音和 LLM 留在這裡。",
        "settingsGuide": "先設這三項，再對照住家。",
        "settingsGuideVoice": "語音",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist 語言",
        "appearanceDark": "深色",
        "appearanceLight": "淺色",
        "setupReplay": "重播設定精靈",
        "personalityDefault": "普通",
        "personalityButler": "Butler",
        "personalityLocker": "隨興",
        "personalityFuersorglich": "體貼",
        "personalityParty": "派對",
        "personalityGrantig": "牢騷",
        "personalitySarkastisch": "諷刺",
        "personalityPirat": "海盜",
        "personalityHippie": "嬉皮",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "操作員語言",
        "operatorLanguageHint": "僅此應用程式。儲存在這裡，或首次儲存前用 KLAR_UI_LOCALE。不是 Assist，也不是 Home Assistant 個人檔案。",
        "nluRag": "未命中時使用住家脈絡",
        "modeFull": "解析裝置",
        "modeContext": "僅房間",
        "inLab": "在實驗室",
        "undoLastCommand": "復原上一道指令",
        "applyDone": "已套用 {count} 則房間建議",
        "applyUndone": "已復原房間建議",
        "applyUndoFailed": "無法復原房間建議",
        "llm": "LLM",
        "llmHint": "Klar 連線相容 OpenAI 的端點。Assist 聊天與訓練器共用這份設定。不需要 Home Assistant 的 OpenAI 或 Ollama 整合。",
        "llmBaseUrl": "基礎 URL",
        "llmModel": "模型",
        "llmApiKey": "API 金鑰",
        "llmApiKeyHint": "留空以保留已儲存的金鑰。Ollama 可以一直空白。",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "已設定",
        "llmNotConfigured": "未設定",
        "llmClear": "清除",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "訓練器",
        "trainerForLane": "此通道的訓練器",
        "trainerHint": "Klar 在 Rust 中呼叫相容 OpenAI 的模型。先聊天、驗證，再依通道套用。不需要 Home Assistant 的 LLM 整合。進階 JSON 僅供除錯。",
        "trainerContext": "脈絡",
        "trainerValidate": "驗證",
        "trainerApply": "套用",
        "trainerProposal": "提案 JSON",
        "trainerOk": "有效",
        "trainerFail": "無效",
        "trainerSend": "傳送",
        "trainerNeedLlm": "請先在 Settings 設定 LLM。Klar 不需要另一個 Home Assistant 對話整合。",
        "trainerOpenSettings": "開啟 Settings",
        "trainerApplyHouse": "套用 House",
        "trainerApplyMatch": "套用 Match",
        "trainerApplyLanguage": "套用 Language",
        "trainerAdvanced": "進階 JSON",
        "trainerStreaming": "串流中…",
    },
    "zh-HK": {
        "engineHint": "聲、語言同 LLM 都喺度。Home Assistant 淨係連接引擎。",
        "languageHint": "空白清單會保留每個已編譯嘅 Assist 語系。釘住一個語言包係常見家庭用法。",
        "personalityHa": "聲、語言同 LLM 都喺呢個 Settings 頁。",
        "assistLanguages": "Assist 語言",
        "assistLanguagesHint": "Klar 可以解析邊啲語言包。衞星仍然每次請求傳送一種語言。空白 = 全部已編譯語系。",
        "allAssistLanguages": "全部已編譯語系",
        "pinLanguage": "釘住一個語言包",
        "voice": "聲",
        "voiceHint": "人格同口播回覆。Assist 由引擎讀，唔係由 Home Assistant 選項。",
        "extraPrompt": "額外提示",
        "extraPromptHint": "疊喺語言包人格上面嘅可選一行。冇屋企規則就留空。",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM 潤飾",
        "refineSpeechHint": "Klar 仍然控制裝置。引擎 LLM 再用呢個聲改寫已完成嘅 NLU 回覆。",
        "quietAck": "簡短確認",
        "quietAckHint": "簡單燈或者開關開／關時，跳過 TTS，喺衞星播一聲提示音。",
        "calendarLlm": "日曆經 LLM",
        "calendarLlmHint": "Klar 仍然讀日曆。開：由 LLM 講事件。關：由 Klar 講清單。",
        "allowLlmTools": "傾偈時允許 Assist 工具",
        "allowLlmToolsHint": "預設關閉。開：傾偈模型可以控制 Home Assistant。關：個代理有工具時 Klar 會跳過佢。",
        "missTitle": "當 Klar 聽唔明",
        "missHint": "確定性拒絕之後嘅可選層。呢啲都唔會將模型放到解析上。",
        "operatorChrome": "呢個畫面",
        "operatorChromeHint": "操作員嘅主題同介面語言。唔係 Assist。",
        "haGlueHint": "Home Assistant Configure 淨係要引擎 URL、權杖、頻道，同埋可選嘅剩餘對話代理。聲同 LLM 留喺度。",
        "settingsGuide": "先設呢三樣，再對照屋企。",
        "settingsGuideVoice": "聲",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist 語言",
        "appearanceDark": "深色",
        "appearanceLight": "淺色",
        "setupReplay": "重播設定精靈",
        "personalityDefault": "普通",
        "personalityButler": "Butler",
        "personalityLocker": "隨性",
        "personalityFuersorglich": "貼心",
        "personalityParty": "派對",
        "personalityGrantig": "嘮叨",
        "personalitySarkastisch": "諷刺",
        "personalityPirat": "海盜",
        "personalityHippie": "嬉皮",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "操作員語言",
        "operatorLanguageHint": "淨係呢個應用程式。儲存喺度，或者首次儲存前用 KLAR_UI_LOCALE。唔係 Assist，亦唔係 Home Assistant 個人檔案。",
        "nluRag": "未命中時用屋企脈絡",
        "modeFull": "解析裝置",
        "modeContext": "淨係房間",
        "inLab": "喺實驗室",
        "undoLastCommand": "復原上一道指令",
        "applyDone": "已套用 {count} 則房間建議",
        "applyUndone": "已復原房間建議",
        "applyUndoFailed": "無法復原房間建議",
        "llm": "LLM",
        "llmHint": "Klar 連線相容 OpenAI 嘅端點。Assist 傾偈同訓練器共用呢份設定。唔需要 Home Assistant 嘅 OpenAI 或者 Ollama 整合。",
        "llmBaseUrl": "基礎 URL",
        "llmModel": "模型",
        "llmApiKey": "API 密鑰",
        "llmApiKeyHint": "留空以保留已儲存嘅密鑰。Ollama 可以一直空白。",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "已設定",
        "llmNotConfigured": "未設定",
        "llmClear": "清除",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "訓練器",
        "trainerForLane": "呢條通道嘅訓練器",
        "trainerHint": "Klar 喺 Rust 入面呼叫相容 OpenAI 嘅模型。先傾偈、驗證，再按通道套用。唔需要 Home Assistant 嘅 LLM 整合。進階 JSON 淨係用嚟除錯。",
        "trainerContext": "脈絡",
        "trainerValidate": "驗證",
        "trainerApply": "套用",
        "trainerProposal": "提案 JSON",
        "trainerOk": "有效",
        "trainerFail": "無效",
        "trainerSend": "傳送",
        "trainerNeedLlm": "請先喺 Settings 設定 LLM。Klar 唔需要另一個 Home Assistant 對話整合。",
        "trainerOpenSettings": "開啟 Settings",
        "trainerApplyHouse": "套用 House",
        "trainerApplyMatch": "套用 Match",
        "trainerApplyLanguage": "套用 Language",
        "trainerAdvanced": "進階 JSON",
        "trainerStreaming": "串流緊…",
    },
    "ja": {
        "engineHint": "音声、言語、LLM はここにあります。Home Assistant はエンジンをつなぐだけです。",
        "languageHint": "空の一覧は、コンパイル済みの Assist ロケールをすべて有効のままにします。パックをひとつ固定するのが普通の家庭です。",
        "personalityHa": "音声、言語、LLM はこの Settings ページにあります。",
        "assistLanguages": "Assist の言語",
        "assistLanguagesHint": "Klar が解析してよいパック。衛星はリクエストごとに言語をひとつ送ります。空 = すべてのコンパイル済みロケール。",
        "allAssistLanguages": "すべてのコンパイル済みロケール",
        "pinLanguage": "パックをひとつ固定",
        "voice": "音声",
        "voiceHint": "人格と話し言葉の返答。Assist はエンジンから読み、Home Assistant のオプションからは読みません。",
        "extraPrompt": "追加プロンプト",
        "extraPromptHint": "パックの人格の上に載せる任意の一行。家独自の規則がなければ空のまま。",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM 仕上げ",
        "refineSpeechHint": "Klar は引き続き機器を制御します。エンジンの LLM が、できた NLU 返答をこの声で書き直します。",
        "quietAck": "短い確認",
        "quietAckHint": "単純な照明やスイッチのオン／オフでは TTS を飛ばし、衛星でチャイムを鳴らします。",
        "calendarLlm": "カレンダーを LLM 経由",
        "calendarLlmHint": "Klar はカレンダーを読み続けます。オン：LLM が予定を話します。オフ：Klar が一覧を話します。",
        "allowLlmTools": "チャットで Assist ツールを許可",
        "allowLlmToolsHint": "既定はオフ。オン：チャットモデルが Home Assistant を操作できます。オフ：ツール付きのそのエージェントを Klar は飛ばします。",
        "missTitle": "Klar が外したとき",
        "missHint": "決定的な拒否のあとの任意レイヤー。どれも解析にモデルを載せません。",
        "operatorChrome": "この画面",
        "operatorChromeHint": "運用者向けのテーマと画面言語。Assist ではありません。",
        "haGlueHint": "Home Assistant の Configure に必要なのはエンジン URL、トークン、チャネル、任意の残り会話エージェントだけ。音声と LLM はここに残します。",
        "settingsGuide": "この三つを設定してから、家を対応づけます。",
        "settingsGuideVoice": "音声",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist の言語",
        "appearanceDark": "ダーク",
        "appearanceLight": "ライト",
        "setupReplay": "セットアップを再生",
        "personalityDefault": "ふつう",
        "personalityButler": "Butler",
        "personalityLocker": "くだけた",
        "personalityFuersorglich": "やさしい",
        "personalityParty": "パーティー",
        "personalityGrantig": "不機嫌",
        "personalitySarkastisch": "皮肉",
        "personalityPirat": "海賊",
        "personalityHippie": "ヒッピー",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "運用者の言語",
        "operatorLanguageHint": "このアプリだけ。ここに保存、または初回保存前の KLAR_UI_LOCALE。Assist でも Home Assistant のプロフィールでもありません。",
        "nluRag": "外れ時の家の文脈",
        "modeFull": "機器を解決",
        "modeContext": "部屋だけ",
        "inLab": "ラボ内",
        "undoLastCommand": "直前のコマンドを取り消す",
        "applyDone": "{count} 件の部屋提案を適用しました",
        "applyUndone": "部屋提案を取り消しました",
        "applyUndoFailed": "部屋提案を取り消せませんでした",
        "llm": "LLM",
        "llmHint": "Klar は OpenAI 互換のエンドポイントと話します。Assist チャットとトレーナーは同じ設定を使います。Home Assistant の OpenAI や Ollama 連携は不要です。",
        "llmBaseUrl": "ベース URL",
        "llmModel": "モデル",
        "llmApiKey": "API キー",
        "llmApiKeyHint": "保存済みのキーを残すなら空のまま。Ollama は空で構いません。",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "設定済み",
        "llmNotConfigured": "未設定",
        "llmClear": "消去",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "トレーナー",
        "trainerForLane": "このレーンのトレーナー",
        "trainerHint": "Klar は Rust で OpenAI 互換モデルを呼び出します。チャット、検証、レーンごとに適用。Home Assistant の LLM 連携は不要です。高度な JSON はデバッグ用です。",
        "trainerContext": "文脈",
        "trainerValidate": "検証",
        "trainerApply": "適用",
        "trainerProposal": "提案 JSON",
        "trainerOk": "有効",
        "trainerFail": "無効",
        "trainerSend": "送信",
        "trainerNeedLlm": "先に Settings で LLM を設定してください。Klar に別の Home Assistant 会話連携は不要です。",
        "trainerOpenSettings": "Settings を開く",
        "trainerApplyHouse": "House を適用",
        "trainerApplyMatch": "Match を適用",
        "trainerApplyLanguage": "Language を適用",
        "trainerAdvanced": "高度な JSON",
        "trainerStreaming": "ストリーミング…",
    },
    "ko": {
        "engineHint": "음성, 언어, LLM은 여기에 있습니다. Home Assistant는 엔진만 연결합니다.",
        "languageHint": "빈 목록은 컴파일된 Assist 로캘을 모두 켜 둡니다. 팩 하나를 고정하는 것이 흔한 가정입니다.",
        "personalityHa": "음성, 언어, LLM은 이 Settings 페이지에 있습니다.",
        "assistLanguages": "Assist 언어",
        "assistLanguagesHint": "Klar가 파싱해도 되는 팩. 위성은 요청마다 언어 하나를 보냅니다. 비움 = 컴파일된 모든 로캘.",
        "allAssistLanguages": "컴파일된 모든 로캘",
        "pinLanguage": "팩 하나 고정",
        "voice": "음성",
        "voiceHint": "성격과 말 대답. Assist는 엔진에서 읽고 Home Assistant 옵션에서는 읽지 않습니다.",
        "extraPrompt": "추가 프롬프트",
        "extraPromptHint": "팩 성격 위에 얹는 선택 한 줄. 집만의 규칙이 없으면 비워 두세요.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM 다듬기",
        "refineSpeechHint": "Klar는 계속 기기를 제어합니다. 엔진 LLM이 끝난 NLU 대답을 이 목소리로 다시 씁니다.",
        "quietAck": "짧은 확인",
        "quietAckHint": "단순한 조명이나 스위치 켜기/끄기에서는 TTS를 건너뛰고 위성에서 차임을 재생합니다.",
        "calendarLlm": "캘린더를 LLM으로",
        "calendarLlmHint": "Klar는 캘린더를 계속 읽습니다. 켜짐: LLM이 일정을 말합니다. 꺼짐: Klar가 목록을 말합니다.",
        "allowLlmTools": "채팅에서 Assist 도구 허용",
        "allowLlmToolsHint": "기본은 꺼짐. 켜짐: 채팅 모델이 Home Assistant를 제어할 수 있습니다. 꺼짐: 도구가 있으면 Klar가 그 에이전트를 건너뜁니다.",
        "missTitle": "Klar가 놓쳤을 때",
        "missHint": "결정적 거절 뒤의 선택 계층. 어느 것도 파스에 모델을 올리지 않습니다.",
        "operatorChrome": "이 화면",
        "operatorChromeHint": "운영자용 테마와 화면 언어. Assist가 아닙니다.",
        "haGlueHint": "Home Assistant Configure에는 엔진 URL, 토큰, 채널, 선택적 남은 대화 에이전트만 필요합니다. 음성과 LLM은 여기에 둡니다.",
        "settingsGuide": "이 셋을 설정한 뒤 집을 대응하세요.",
        "settingsGuideVoice": "음성",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist 언어",
        "appearanceDark": "어둡게",
        "appearanceLight": "밝게",
        "setupReplay": "설정 다시 재생",
        "personalityDefault": "보통",
        "personalityButler": "Butler",
        "personalityLocker": "편한",
        "personalityFuersorglich": "다정한",
        "personalityParty": "파티",
        "personalityGrantig": "투덜",
        "personalitySarkastisch": "비꼬는",
        "personalityPirat": "해적",
        "personalityHippie": "히피",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "운영자 언어",
        "operatorLanguageHint": "이 앱만. 여기에 저장하거나, 첫 저장 전에 KLAR_UI_LOCALE. Assist도 Home Assistant 프로필도 아닙니다.",
        "nluRag": "놓쳤을 때 집 맥락",
        "modeFull": "기기 해석",
        "modeContext": "방만",
        "inLab": "랩에서",
        "undoLastCommand": "마지막 명령 실행 취소",
        "applyDone": "방 제안 {count}건을 적용함",
        "applyUndone": "방 제안을 되돌림",
        "applyUndoFailed": "방 제안을 되돌릴 수 없음",
        "llm": "LLM",
        "llmHint": "Klar는 OpenAI 호환 엔드포인트와 대화합니다. Assist 채팅과 트레이너가 같은 설정을 씁니다. Home Assistant OpenAI 또는 Ollama 연동은 필요 없습니다.",
        "llmBaseUrl": "기본 URL",
        "llmModel": "모델",
        "llmApiKey": "API 키",
        "llmApiKeyHint": "저장된 키를 유지하려면 비워 두세요. Ollama는 비워도 됩니다.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "구성됨",
        "llmNotConfigured": "구성되지 않음",
        "llmClear": "지우기",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "트레이너",
        "trainerForLane": "이 레인의 트레이너",
        "trainerHint": "Klar는 Rust에서 OpenAI 호환 모델을 호출합니다. 채팅, 검증, 레인별로 적용. Home Assistant LLM 연동은 필요 없습니다. 고급 JSON은 디버그용입니다.",
        "trainerContext": "맥락",
        "trainerValidate": "검증",
        "trainerApply": "적용",
        "trainerProposal": "제안 JSON",
        "trainerOk": "유효",
        "trainerFail": "무효",
        "trainerSend": "보내기",
        "trainerNeedLlm": "먼저 Settings에서 LLM을 구성하세요. Klar는 다른 Home Assistant 대화 연동이 필요 없습니다.",
        "trainerOpenSettings": "Settings 열기",
        "trainerApplyHouse": "House 적용",
        "trainerApplyMatch": "Match 적용",
        "trainerApplyLanguage": "Language 적용",
        "trainerAdvanced": "고급 JSON",
        "trainerStreaming": "스트리밍…",
    },
    "th": {
        "engineHint": "เสียง ภาษา และ LLM อยู่ที่นี่ Home Assistant แค่เชื่อมเครื่องยนต์",
        "languageHint": "รายการว่างคงทุก locale ของ Assist ที่คอมไพล์แล้ว การปักหมุดแพ็กเดียวเป็นบ้านทั่วไป",
        "personalityHa": "เสียง ภาษา และ LLM อยู่ที่หน้า Settings นี้",
        "assistLanguages": "ภาษา Assist",
        "assistLanguagesHint": "แพ็กที่ Klar อนุญาตให้แยกความ ดาวเทียมยังส่งภาษาเดียวต่อคำขอ ว่าง = ทุก locale ที่คอมไพล์แล้ว",
        "allAssistLanguages": "ทุก locale ที่คอมไพล์แล้ว",
        "pinLanguage": "ปักหมุดแพ็กเดียว",
        "voice": "เสียง",
        "voiceHint": "บุคลิกและคำตอบที่พูด Assist อ่านจากเครื่องยนต์ ไม่ใช่จากตัวเลือก Home Assistant",
        "extraPrompt": "พรอมต์เพิ่ม",
        "extraPromptHint": "บรรทัดเสริมทับบุคลิกของแพ็ก ปล่อยว่างถ้าบ้านไม่ต้องการกฎเฉพาะ",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "ขัดเกลาด้วย LLM",
        "refineSpeechHint": "Klar ยังควบคุมอุปกรณ์ LLM ของเครื่องยนต์จะเขียนคำตอบ NLU ที่เสร็จแล้วด้วยเสียงนี้",
        "quietAck": "ยืนยันสั้น",
        "quietAckHint": "ไฟหรือสวิตช์เปิด/ปิดธรรมดา ให้ข้าม TTS แล้วเล่นเสียงระฆังที่ดาวเทียม",
        "calendarLlm": "ปฏิทินผ่าน LLM",
        "calendarLlmHint": "Klar ยังอ่านปฏิทิน เปิด: LLM พูดเหตุการณ์ ปิด: Klar พูดรายการ",
        "allowLlmTools": "อนุญาตเครื่องมือ Assist บนแชต",
        "allowLlmToolsHint": "ปิดเป็นค่าเริ่มต้น เปิด: โมเดลแชตอาจควบคุม Home Assistant ปิด: Klar ข้ามเอเจนต์นั้นเมื่อมีเครื่องมือ",
        "missTitle": "เมื่อ Klar พลาด",
        "missHint": "ชั้นเสริมหลังปฏิเสธแบบกำหนดแน่นอน ไม่มีชั้นใดใส่โมเดลบนการแยกความ",
        "operatorChrome": "หน้าจอนี้",
        "operatorChromeHint": "ธีมและภาษาส่วนติดต่อสำหรับผู้ปฏิบัติการ ไม่ใช่ Assist",
        "haGlueHint": "Home Assistant Configure ต้องการแค่ URL เครื่องยนต์ โทเค็น ช่อง และเอเจนต์สนทนาเก่าที่เลือกได้ เสียงกับ LLM อยู่ที่นี่",
        "settingsGuide": "ตั้งสามอย่างนี้ แล้วค่อยจับคู่บ้าน",
        "settingsGuideVoice": "เสียง",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "ภาษา Assist",
        "appearanceDark": "มืด",
        "appearanceLight": "สว่าง",
        "setupReplay": "เล่น setup ซ้ำ",
        "personalityDefault": "ปกติ",
        "personalityButler": "Butler",
        "personalityLocker": "สบาย ๆ",
        "personalityFuersorglich": "ห่วงใย",
        "personalityParty": "ปาร์ตี้",
        "personalityGrantig": "หงุดหงิด",
        "personalitySarkastisch": "ประชด",
        "personalityPirat": "โจรสลัด",
        "personalityHippie": "ฮิปปี้",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "ภาษาผู้ปฏิบัติการ",
        "operatorLanguageHint": "เฉพาะแอปนี้ บันทึกที่นี่ หรือ KLAR_UI_LOCALE ก่อนบันทึกครั้งแรก ไม่ใช่ Assist ไม่ใช่โปรไฟล์ Home Assistant",
        "nluRag": "บริบทบ้านเมื่อพลาด",
        "modeFull": "ระบุอุปกรณ์",
        "modeContext": "เฉพาะห้อง",
        "inLab": "ในแล็บ",
        "undoLastCommand": "เลิกทำคำสั่งล่าสุด",
        "applyDone": "ใช้คำแนะนำห้อง {count} รายการแล้ว",
        "applyUndone": "เลิกทำคำแนะนำห้องแล้ว",
        "applyUndoFailed": "เลิกทำคำแนะนำห้องไม่ได้",
        "llm": "LLM",
        "llmHint": "Klar พูดกับจุดปลายที่เข้ากันกับ OpenAI แชต Assist และผู้ฝึกใช้ config เดียวกัน ไม่ต้องมีอินทิเกรชัน OpenAI หรือ Ollama ใน Home Assistant",
        "llmBaseUrl": "URL ฐาน",
        "llmModel": "โมเดล",
        "llmApiKey": "คีย์ API",
        "llmApiKeyHint": "ปล่อยว่างเพื่อเก็บคีย์ที่บันทึกไว้ Ollama ว่างได้",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "ตั้งค่าแล้ว",
        "llmNotConfigured": "ยังไม่ตั้งค่า",
        "llmClear": "ล้าง",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "ผู้ฝึก",
        "trainerForLane": "ผู้ฝึกสำหรับเลนนี้",
        "trainerHint": "Klar เรียกโมเดลที่เข้ากันกับ OpenAI ใน Rust แชต ตรวจ แล้วใช้ทีละเลน ไม่ต้องมีอินทิเกรชัน LLM ของ Home Assistant JSON ขั้นสูงสำหรับดีบัก",
        "trainerContext": "บริบท",
        "trainerValidate": "ตรวจ",
        "trainerApply": "ใช้",
        "trainerProposal": "JSON ข้อเสนอ",
        "trainerOk": "ถูกต้อง",
        "trainerFail": "ไม่ถูกต้อง",
        "trainerSend": "ส่ง",
        "trainerNeedLlm": "ตั้งค่า LLM ใน Settings ก่อน Klar ไม่ต้องใช้อินทิเกรชันสนทนา Home Assistant อีกชุด",
        "trainerOpenSettings": "เปิด Settings",
        "trainerApplyHouse": "ใช้ House",
        "trainerApplyMatch": "ใช้ Match",
        "trainerApplyLanguage": "ใช้ Language",
        "trainerAdvanced": "JSON ขั้นสูง",
        "trainerStreaming": "กำลังสตรีม…",
    },
    "vi": {
        "engineHint": "Giọng, ngôn ngữ và LLM ở đây. Home Assistant chỉ nối động cơ.",
        "languageHint": "Danh sách trống giữ mọi locale Assist đã biên dịch. Ghim một gói là hộ gia đình thông thường.",
        "personalityHa": "Giọng, ngôn ngữ và LLM nằm trên trang Settings này.",
        "assistLanguages": "Ngôn ngữ Assist",
        "assistLanguagesHint": "Klar được phép phân tích gói nào. Vệ tinh vẫn gửi một ngôn ngữ mỗi yêu cầu. Trống = mọi locale đã biên dịch.",
        "allAssistLanguages": "Mọi locale đã biên dịch",
        "pinLanguage": "Ghim một gói",
        "voice": "Giọng",
        "voiceHint": "Tính cách và câu trả lời nói. Assist đọc từ động cơ, không từ tùy chọn Home Assistant.",
        "extraPrompt": "Prompt thêm",
        "extraPromptHint": "Dòng tùy chọn trên tính cách của gói. Để trống trừ khi nhà cần quy tắc riêng.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "Chỉnh LLM",
        "refineSpeechHint": "Klar vẫn điều khiển thiết bị. LLM động cơ rồi viết lại câu trả lời NLU xong bằng giọng này.",
        "quietAck": "Xác nhận ngắn",
        "quietAckHint": "Với đèn hoặc công tắc bật/tắt đơn giản, bỏ TTS và phát chuông trên vệ tinh.",
        "calendarLlm": "Lịch qua LLM",
        "calendarLlmHint": "Klar vẫn đọc lịch. Bật: LLM nói sự kiện. Tắt: Klar nói danh sách.",
        "allowLlmTools": "Cho phép công cụ Assist trên chat",
        "allowLlmToolsHint": "Tắt mặc định. Bật: mô hình chat có thể điều khiển Home Assistant. Tắt: Klar bỏ qua tác nhân đó khi có công cụ.",
        "missTitle": "Khi Klar trượt",
        "missHint": "Lớp tùy chọn sau từ chối tất định. Không lớp nào đặt mô hình lên parse.",
        "operatorChrome": "Màn hình này",
        "operatorChromeHint": "Chủ đề và ngôn ngữ giao diện cho người vận hành. Không phải Assist.",
        "haGlueHint": "Home Assistant Configure chỉ cần URL động cơ, token, kênh và tác nhân hội thoại còn lại tùy chọn. Giọng và LLM ở lại đây.",
        "settingsGuide": "Đặt ba mục này, rồi ánh xạ nhà.",
        "settingsGuideVoice": "Giọng",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Ngôn ngữ Assist",
        "appearanceDark": "Tối",
        "appearanceLight": "Sáng",
        "setupReplay": "Phát lại setup",
        "personalityDefault": "Bình thường",
        "personalityButler": "Butler",
        "personalityLocker": "Thoải mái",
        "personalityFuersorglich": "Ân cần",
        "personalityParty": "Tiệc",
        "personalityGrantig": "Cáu kỉnh",
        "personalitySarkastisch": "Châm biếm",
        "personalityPirat": "Cướp biển",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Ngôn ngữ người vận hành",
        "operatorLanguageHint": "Chỉ ứng dụng này. Lưu ở đây, hoặc KLAR_UI_LOCALE trước lần lưu đầu. Không Assist, không hồ sơ Home Assistant.",
        "nluRag": "Ngữ cảnh nhà khi trượt",
        "modeFull": "Giải thiết bị",
        "modeContext": "Chỉ phòng",
        "inLab": "Trong lab",
        "undoLastCommand": "Hoàn tác lệnh cuối",
        "applyDone": "Đã áp {count} gợi ý phòng",
        "applyUndone": "Đã hoàn tác gợi ý phòng",
        "applyUndoFailed": "Không hoàn tác được gợi ý phòng",
        "llm": "LLM",
        "llmHint": "Klar nói với điểm cuối tương thích OpenAI. Chat Assist và huấn luyện viên dùng cùng config. Không cần tích hợp OpenAI hay Ollama trong Home Assistant.",
        "llmBaseUrl": "URL gốc",
        "llmModel": "Mô hình",
        "llmApiKey": "Khóa API",
        "llmApiKeyHint": "Để trống để giữ khóa đã lưu. Ollama có thể để trống.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Đã cấu hình",
        "llmNotConfigured": "Chưa cấu hình",
        "llmClear": "Xóa",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Huấn luyện viên",
        "trainerForLane": "Huấn luyện viên cho làn này",
        "trainerHint": "Klar gọi mô hình tương thích OpenAI trong Rust. Chat, kiểm tra, rồi áp theo làn. Không cần tích hợp LLM Home Assistant. JSON nâng cao dành cho gỡ lỗi.",
        "trainerContext": "Ngữ cảnh",
        "trainerValidate": "Kiểm tra",
        "trainerApply": "Áp",
        "trainerProposal": "JSON đề xuất",
        "trainerOk": "Hợp lệ",
        "trainerFail": "Không hợp lệ",
        "trainerSend": "Gửi",
        "trainerNeedLlm": "Hãy cấu hình LLM trong Settings trước. Klar không cần tích hợp hội thoại Home Assistant khác.",
        "trainerOpenSettings": "Mở Settings",
        "trainerApplyHouse": "Áp House",
        "trainerApplyMatch": "Áp Match",
        "trainerApplyLanguage": "Áp Language",
        "trainerAdvanced": "JSON nâng cao",
        "trainerStreaming": "Đang phát…",
    },
    "id": {
        "engineHint": "Suara, bahasa, dan LLM ada di sini. Home Assistant hanya menyambungkan mesin.",
        "languageHint": "Daftar kosong menjaga setiap locale Assist yang terkompilasi. Menjepit satu paket adalah rumah tangga biasa.",
        "personalityHa": "Suara, bahasa, dan LLM ada di halaman Settings ini.",
        "assistLanguages": "Bahasa Assist",
        "assistLanguagesHint": "Paket mana yang boleh diurai Klar. Satelit tetap mengirim satu bahasa per permintaan. Kosong = semua locale terkompilasi.",
        "allAssistLanguages": "Setiap locale terkompilasi",
        "pinLanguage": "Jepit satu paket",
        "voice": "Suara",
        "voiceHint": "Kepribadian dan jawaban lisan. Assist membacanya dari mesin, bukan dari opsi Home Assistant.",
        "extraPrompt": "Prompt tambahan",
        "extraPromptHint": "Baris opsional di atas kepribadian paket. Biarkan kosong kecuali rumah butuh aturan sendiri.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "Penghalusan LLM",
        "refineSpeechHint": "Klar tetap mengendalikan perangkat. LLM mesin lalu menulis ulang jawaban NLU jadi dengan suara ini.",
        "quietAck": "Konfirmasi singkat",
        "quietAckHint": "Pada lampu atau sakelar on/off sederhana, lewati TTS dan bunyikan lonceng di satelit.",
        "calendarLlm": "Kalender lewat LLM",
        "calendarLlmHint": "Klar tetap membaca kalender. On: LLM mengucapkan acara. Off: Klar mengucapkan daftar.",
        "allowLlmTools": "Izinkan alat Assist di obrolan",
        "allowLlmToolsHint": "Off secara bawaan. On: model obrolan boleh mengendalikan Home Assistant. Off: Klar melewati agen itu jika punya alat.",
        "missTitle": "Saat Klar meleset",
        "missHint": "Lapisan opsional setelah penolakan deterministik. Tidak ada yang menaruh model pada parse.",
        "operatorChrome": "Layar ini",
        "operatorChromeHint": "Tema dan bahasa antarmuka untuk operator. Bukan Assist.",
        "haGlueHint": "Home Assistant Configure hanya butuh URL mesin, token, saluran, dan agen percakapan sisa opsional. Suara dan LLM tetap di sini.",
        "settingsGuide": "Atur ketiga ini, lalu petakan rumah.",
        "settingsGuideVoice": "Suara",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Bahasa Assist",
        "appearanceDark": "Gelap",
        "appearanceLight": "Terang",
        "setupReplay": "Ulang setup",
        "personalityDefault": "Biasa",
        "personalityButler": "Butler",
        "personalityLocker": "Santai",
        "personalityFuersorglich": "Penyayang",
        "personalityParty": "Pesta",
        "personalityGrantig": "Pemurung",
        "personalitySarkastisch": "Sarkastis",
        "personalityPirat": "Bajak laut",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Bahasa operator",
        "operatorLanguageHint": "Hanya aplikasi ini. Disimpan di sini, atau KLAR_UI_LOCALE sebelum simpan pertama. Bukan Assist, bukan profil Home Assistant.",
        "nluRag": "Konteks rumah saat miss",
        "modeFull": "Selesaikan perangkat",
        "modeContext": "Hanya ruangan",
        "inLab": "Di lab",
        "undoLastCommand": "Batalkan perintah terakhir",
        "applyDone": "Menerapkan {count} saran ruangan",
        "applyUndone": "Saran ruangan dibatalkan",
        "applyUndoFailed": "Tidak bisa membatalkan saran ruangan",
        "llm": "LLM",
        "llmHint": "Klar berbicara ke endpoint yang kompatibel dengan OpenAI. Obrolan Assist dan pelatih memakai config yang sama. Integrasi OpenAI atau Ollama di Home Assistant tidak diperlukan.",
        "llmBaseUrl": "URL dasar",
        "llmModel": "Model",
        "llmApiKey": "Kunci API",
        "llmApiKeyHint": "Biarkan kosong untuk mempertahankan kunci tersimpan. Ollama boleh kosong.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Dikonfigurasi",
        "llmNotConfigured": "Belum dikonfigurasi",
        "llmClear": "Hapus",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Pelatih",
        "trainerForLane": "Pelatih untuk jalur ini",
        "trainerHint": "Klar memanggil model yang kompatibel dengan OpenAI di Rust. Obrol, validasi, lalu terapkan per jalur. Integrasi LLM Home Assistant tidak diperlukan. JSON lanjutan untuk debug.",
        "trainerContext": "Konteks",
        "trainerValidate": "Validasi",
        "trainerApply": "Terapkan",
        "trainerProposal": "JSON usulan",
        "trainerOk": "Valid",
        "trainerFail": "Tidak valid",
        "trainerSend": "Kirim",
        "trainerNeedLlm": "Konfigurasikan LLM di Settings dulu. Klar tidak butuh integrasi percakapan Home Assistant lain.",
        "trainerOpenSettings": "Buka Settings",
        "trainerApplyHouse": "Terapkan House",
        "trainerApplyMatch": "Terapkan Match",
        "trainerApplyLanguage": "Terapkan Language",
        "trainerAdvanced": "JSON lanjutan",
        "trainerStreaming": "Streaming…",
    },
    "ms": {
        "engineHint": "Suara, bahasa dan LLM tinggal di sini. Home Assistant hanya menyambungkan enjin.",
        "languageHint": "Senarai kosong mengekalkan setiap locale Assist yang terkompil. Menyemat satu pek ialah rumah tangga biasa.",
        "personalityHa": "Suara, bahasa dan LLM tinggal pada halaman Settings ini.",
        "assistLanguages": "Bahasa Assist",
        "assistLanguagesHint": "Pek mana yang Klar boleh hurai. Satelit masih menghantar satu bahasa setiap permintaan. Kosong = semua locale terkompil.",
        "allAssistLanguages": "Setiap locale terkompil",
        "pinLanguage": "Semat satu pek",
        "voice": "Suara",
        "voiceHint": "Personaliti dan jawapan dituturkan. Assist membaca ini daripada enjin, bukan pilihan Home Assistant.",
        "extraPrompt": "Prompt tambahan",
        "extraPromptHint": "Baris pilihan di atas personaliti pek. Biarkan kosong melainkan rumah perlukan peraturan sendiri.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "Penghalusan LLM",
        "refineSpeechHint": "Klar masih mengawal peranti. LLM enjin kemudian menulis semula jawapan NLU siap dalam suara ini.",
        "quietAck": "Pengesahan singkat",
        "quietAckHint": "Pada lampu atau suis on/off mudah, langkau TTS dan mainkan loceng pada satelit.",
        "calendarLlm": "Kalendar melalui LLM",
        "calendarLlmHint": "Klar masih membaca kalendar. On: LLM menyebut acara. Off: Klar menyebut senarai.",
        "allowLlmTools": "Benarkan alat Assist pada sembang",
        "allowLlmToolsHint": "Off secara lalai. On: model sembang boleh mengawal Home Assistant. Off: Klar langkau ejen itu jika ada alat.",
        "missTitle": "Apabila Klar terlepas",
        "missHint": "Lapisan pilihan selepas tolakan deterministik. Tiada yang meletakkan model pada parse.",
        "operatorChrome": "Skrin ini",
        "operatorChromeHint": "Tema dan bahasa antara muka untuk pengendali. Bukan Assist.",
        "haGlueHint": "Home Assistant Configure hanya perlukan URL enjin, token, saluran dan ejen perbualan sisa pilihan. Suara dan LLM kekal di sini.",
        "settingsGuide": "Tetapkan tiga ini, kemudian peta rumah.",
        "settingsGuideVoice": "Suara",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Bahasa Assist",
        "appearanceDark": "Gelap",
        "appearanceLight": "Cerah",
        "setupReplay": "Main semula setup",
        "personalityDefault": "Biasa",
        "personalityButler": "Butler",
        "personalityLocker": "Santai",
        "personalityFuersorglich": "Penyayang",
        "personalityParty": "Pesta",
        "personalityGrantig": "Meragam",
        "personalitySarkastisch": "Sarkastik",
        "personalityPirat": "Lanun",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Bahasa pengendali",
        "operatorLanguageHint": "Aplikasi ini sahaja. Disimpan di sini, atau KLAR_UI_LOCALE sebelum simpanan pertama. Bukan Assist, bukan profil Home Assistant.",
        "nluRag": "Konteks rumah semasa miss",
        "modeFull": "Selesaikan peranti",
        "modeContext": "Bilik sahaja",
        "inLab": "Dalam makmal",
        "undoLastCommand": "Buat asal arahan terakhir",
        "applyDone": "Menggunakan {count} cadangan bilik",
        "applyUndone": "Cadangan bilik dibuat asal",
        "applyUndoFailed": "Tidak dapat membuat asal cadangan bilik",
        "llm": "LLM",
        "llmHint": "Klar bercakap dengan titik hujung serasi OpenAI. Sembang Assist dan jurulatih menggunakan config yang sama. Integrasi OpenAI atau Ollama dalam Home Assistant tidak diperlukan.",
        "llmBaseUrl": "URL asas",
        "llmModel": "Model",
        "llmApiKey": "Kunci API",
        "llmApiKeyHint": "Biarkan kosong untuk mengekalkan kunci tersimpan. Ollama boleh kekal kosong.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Dikonfigurasi",
        "llmNotConfigured": "Tidak dikonfigurasi",
        "llmClear": "Kosongkan",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Jurulatih",
        "trainerForLane": "Jurulatih untuk lorong ini",
        "trainerHint": "Klar memanggil model serasi OpenAI dalam Rust. Sembang, sahkan, kemudian guna mengikut lorong. Integrasi LLM Home Assistant tidak diperlukan. JSON lanjutan untuk nyahpepijat.",
        "trainerContext": "Konteks",
        "trainerValidate": "Sahkan",
        "trainerApply": "Guna",
        "trainerProposal": "JSON cadangan",
        "trainerOk": "Sah",
        "trainerFail": "Tidak sah",
        "trainerSend": "Hantar",
        "trainerNeedLlm": "Konfigurasikan LLM dalam Settings dahulu. Klar tidak memerlukan integrasi perbualan Home Assistant lain.",
        "trainerOpenSettings": "Buka Settings",
        "trainerApplyHouse": "Guna House",
        "trainerApplyMatch": "Guna Match",
        "trainerApplyLanguage": "Guna Language",
        "trainerAdvanced": "JSON lanjutan",
        "trainerStreaming": "Penstriman…",
    },
    "mn": {
        "engineHint": "Дуу хоолой, хэл, LLM энд байна. Home Assistant зөвхөн хөдөлгүүрийг холбоно.",
        "languageHint": "Хоосон жагсаалт эмхэтгэсэн Assist locale бүрийг идэвхтэй үлдээнэ. Нэг багц хатгах нь энгийн өрх.",
        "personalityHa": "Дуу хоолой, хэл, LLM энэ Settings хуудсанд байна.",
        "assistLanguages": "Assist хэлнүүд",
        "assistLanguagesHint": "Klar аль багцыг задлахыг зөвшөөрнө. Хиймэл дагуул хүсэлт бүрт нэг хэл илгээнэ. Хоосон = бүх эмхэтгэсэн locale.",
        "allAssistLanguages": "Эмхэтгэсэн locale бүр",
        "pinLanguage": "Нэг багц хатгах",
        "voice": "Дуу хоолой",
        "voiceHint": "Зан чанар болон ярьсан хариулт. Assist үүнийг хөдөлгүүрээс уншина, Home Assistant сонголтоос биш.",
        "extraPrompt": "Нэмэлт prompt",
        "extraPromptHint": "Багцын зан чанарын дээрх нэмэлт мөр. Гэрийн өөрийн дүрэм хэрэггүй бол хоосон орхи.",
        "personalityPrompt": "Personality prompt",
        "personalityPromptHint": "What the engine LLM gets for this voice. Extra prompt below is optional and house-specific.",
        "refineSpeech": "LLM өнгөлөлт",
        "refineSpeechHint": "Klar төхөөрөмжийг хянасаар байна. Хөдөлгүүрийн LLM дууссан NLU хариултыг энэ дуугаар дахин бичнэ.",
        "quietAck": "Богино баталгаа",
        "quietAckHint": "Энгийн гэрэл эсвэл унтраалга асаах/унтраахад TTS-ийг алгасаад хиймэл дагуул дээр хонх тоглуул.",
        "calendarLlm": "Календарийг LLM-ээр",
        "calendarLlmHint": "Klar календарийг уншсаар байна. Асаалттай: LLM үйл явдлыг хэлнэ. Унтраалттай: Klar жагсаалтыг хэлнэ.",
        "allowLlmTools": "Чат дээр Assist хэрэгслийг зөвшөөрөх",
        "allowLlmToolsHint": "Анхдагчаар унтраалттай. Асаалттай: чат загвар Home Assistant-ыг удирдаж болно. Унтраалттай: хэрэгсэлтэй бол Klar тэр агентыг алгасна.",
        "missTitle": "Klar буруу ойлгоход",
        "missHint": "Тогтмол татгалзсаны дараах нэмэлт давхарга. Аль нь ч parse дээр загвар тавихгүй.",
        "operatorChrome": "Энэ дэлгэц",
        "operatorChromeHint": "Операторт зориулсан сэдэв ба интерфэйсийн хэл. Assist биш.",
        "haGlueHint": "Home Assistant Configure-д зөвхөн хөдөлгүүрийн URL, токен, суваг, сонголтот үлдсэн ярианы агент хэрэгтэй. Дуу хоолой ба LLM энд үлдэнэ.",
        "settingsGuide": "Эдгээр гурвыг тохируулаад гэрийг зурагла.",
        "settingsGuideVoice": "Дуу хоолой",
        "settingsGuideLlm": "LLM",
        "settingsGuideLang": "Assist хэл",
        "appearanceDark": "Харанхуй",
        "appearanceLight": "Гэрэл",
        "setupReplay": "Setup дахин тоглуулах",
        "personalityDefault": "Энгийн",
        "personalityButler": "Butler",
        "personalityLocker": "Чөлөөтэй",
        "personalityFuersorglich": "Халамжтай",
        "personalityParty": "Үдэшлэг",
        "personalityGrantig": "Ууртай",
        "personalitySarkastisch": "Ёжтой",
        "personalityPirat": "Далайн дээрэмчин",
        "personalityHippie": "Hippie",
        "personalityGollum": "Gollum",
        "personalityJarvis": "Jarvis",
        "operatorLanguage": "Операторын хэл",
        "operatorLanguageHint": "Зөвхөн энэ апп. Энд хадгалсан, эсвэл эхний хадгалалтын өмнө KLAR_UI_LOCALE. Assist биш, Home Assistant профайл биш.",
        "nluRag": "Алдагдахад гэрийн контекст",
        "modeFull": "Төхөөрөмжийг шийд",
        "modeContext": "Зөвхөн өрөө",
        "inLab": "Лабораторид",
        "undoLastCommand": "Сүүлийн тушаалыг буцаа",
        "applyDone": "{count} өрөөний саналыг хэрэглэсэн",
        "applyUndone": "Өрөөний саналыг буцаасан",
        "applyUndoFailed": "Өрөөний саналыг буцааж чадсангүй",
        "llm": "LLM",
        "llmHint": "Klar OpenAI-тэй нийцэх төгсгөлтэй ярина. Assist чат ба дасгалжуулагч ижил config ашиглана. Home Assistant дахь OpenAI эсвэл Ollama нэгтгэл шаардлагагүй.",
        "llmBaseUrl": "Суурь URL",
        "llmModel": "Загвар",
        "llmApiKey": "API түлхүүр",
        "llmApiKeyHint": "Хадгалсан түлхүүрийг үлдээхийн тулд хоосон орхи. Ollama хоосон байж болно.",
        "llmPresetOpenAi": "OpenAI",
        "llmPresetOllama": "Ollama",
        "llmConfigured": "Тохируулсан",
        "llmNotConfigured": "Тохируулаагүй",
        "llmClear": "Цэвэрлэх",
        "llmThinking": "Thinking",
        "llmThinkingHint": "Off sends enable_thinking=false (default). Leave off for Gemma 4 so replies stay in the content channel.",
        "trainer": "Дасгалжуулагч",
        "trainerForLane": "Энэ замын дасгалжуулагч",
        "trainerHint": "Klar Rust дотор OpenAI-тэй нийцэх загвар дуудна. Чатлаад шалгаад замын дагуу хэрэглэ. Home Assistant LLM нэгтгэл шаардлагагүй. Нарийвчилсан JSON нь debug-д.",
        "trainerContext": "Контекст",
        "trainerValidate": "Шалгах",
        "trainerApply": "Хэрэглэх",
        "trainerProposal": "Саналын JSON",
        "trainerOk": "Хүчинтэй",
        "trainerFail": "Хүчингүй",
        "trainerSend": "Илгээх",
        "trainerNeedLlm": "Эхлээд Settings-д LLM тохируул. Klar өөр Home Assistant ярианы нэгтгэл хэрэггүй.",
        "trainerOpenSettings": "Settings нээх",
        "trainerApplyHouse": "House хэрэглэх",
        "trainerApplyMatch": "Match хэрэглэх",
        "trainerApplyLanguage": "Language хэрэглэх",
        "trainerAdvanced": "Нарийвчилсан JSON",
        "trainerStreaming": "Урсгал…",
    },
}


