"""Speech slots: Celtic, Baltic, SE Asia, Caucasus."""

from lang_packs.speech_slots import P, S

REST = {
    "cy": S(
        "Mae'r amserydd yn rhedeg.", "Mae'r amserydd wedi'i ganslo.", "Mae'r amserydd ar seibiant.",
        "Beth ddylwn i chwarae?", "Symudwyd y gerddoriaeth.", "Ychwanegwyd at ffefrynnau.",
        "{target} yn sugno.", "{target} yn mynd i'r orsaf.", "Y sugnwr",
        "gwres", "aerdymheru", "gartref", "Gwyntyll ar {n} y cant.",
        jarvis=("Wrth gwrs, syr. ", "Ar unwaith. ", ""),
    ),
    "et": S(
        "Taimer töötab.", "Taimer on tühistatud.", "Taimer on pausil.",
        "Mida mängida?", "Muusika on teisaldatud.", "Lisatud lemmikutesse.",
        "{target} tolmuimeb.", "{target} sõidab dokki.", "Tolmuimeja",
        "küte", "jahutus", "kodus", "Ventilaator {n} protsenti.",
        jarvis=("Muidugi, härra. ", "Kohe. ", ""),
    ),
    "eu": S(
        "Tenporizadorea martxan.", "Tenporizadorea bertan behera.", "Tenporizadorea pausatuta.",
        "Zer jo dezat?", "Musika mugitu da.", "Gogokoetara gehituta.",
        "{target} xurgatzen ari da.", "{target} oinarrira doa.", "Xurgagailua",
        "berogailua", "aire girotua", "etxean", "Haizagailua {n} ehunekoan.",
        jarvis=("Noski, jauna. ", "Oraintxe. ", ""),
    ),
    "ga": S(
        "Tá an t-amadóir ar siúl.", "Tá an t-amadóir curtha ar ceal.", "Tá an t-amadóir ar sos.",
        "Cad ba chóir dom a sheinm?", "Bogadh an ceol.", "Curtha le ceanáin.",
        "{target} ag súchán.", "{target} ag dul go dtí an duga.", "An súchán",
        "téamh", "aerchóiriú", "sa bhaile", "Gaothrán ag {n} faoin gcéad.",
        jarvis=("Ar ndóigh, a dhuine uasail. ", "Láithreach. ", ""),
    ),
    "gl": S(
        "O temporizador está en marcha.", "Temporizador cancelado.", "Temporizador en pausa.",
        "Que reproduzo?", "Música movida.", "Engadido aos favoritos.",
        "{target} está aspirando.", "{target} volve á base.", "O aspirador",
        "calefacción", "aire acondicionado", "na casa", "Ventilador ao {n} por cento.",
        jarvis=("Claro, señor. ", "Agora mesmo. ", ""),
    ),
    "is": S(
        "Tíminn er í gangi.", "Tíminn er stöðvaður.", "Tíminn er í bið.",
        "Hvað á ég að spila?", "Tónlist flutt.", "Bætt við eftirlæti.",
        "{target} er að ryksuga.", "{target} fer á stöðina.", "Ryksugan",
        "hitun", "kæling", "heima", "Viftan á {n} prósent.",
        jarvis=("Að sjálfsögðu, herra. ", "Strax. ", ""),
    ),
    "lb": S(
        "Timer leeft.", "Timer ass aus.", "Timer ass pauséiert.",
        "Wat soll ech ofspillen?", "Musek ass geréckelt.", "Bei d Favoritten derbäi.",
        "{target} saugt elo.", "{target} fiert op d Statioun.", "De Staubsauger",
        "Heizung", "Klimaanlag", "doheem", "Ventilator op {n} Prozent.",
        jarvis=("Natierlech, Här. ", "Direkt. ", ""),
    ),
    "kw": S(
        "Yn termyn yw ow kerdhes.", "Y termyn yw hedhyes.", "Y termyn yw pausys.",
        "Pandra wovyn vy seni?", "An ilewydh yw gwayys.", "Keworrys dhe'n gwella.",
        "{target} yw ow sugna.", "{target} yw ow mos dhe'n savla.", "An sugner",
        "tommder", "ayr oer", "dhe dre", "Gwynsellen dhe {n} kansran.",
        jarvis=("Yn sur, syrra. ", "A-dhesempis. ", ""),
    ),
    "lt": S(
        "Laikmatis veikia.", "Laikmatis atšauktas.", "Laikmatis pristabdytas.",
        "Ką groti?", "Muzika perkelta.", "Pridėta prie mėgstamų.",
        "{target} siurbia.", "{target} važiuoja į stotelę.", "Siurblys",
        "šildymas", "vėsinimas", "namie", "Ventiliatorius {n} procentų.",
        jarvis=("Žinoma, pone. ", "Iškart. ", ""),
    ),
    "lv": S(
        "Taimeris darbojas.", "Taimeris atcelts.", "Taimeris pauzēts.",
        "Ko atskaņot?", "Mūzika pārvietota.", "Pievienots izlasei.",
        "{target} putekļsūc.", "{target} brauc uz staciju.", "Putekļsūcējs",
        "apkure", "dzesēšana", "mājās", "Ventilators {n} procenti.",
        jarvis=("Protams, kungs. ", "Tūlīt. ", ""),
    ),
    "id": S(
        "Timer berjalan.", "Timer dibatalkan.", "Timer dijeda.",
        "Apa yang saya putar?", "Musik dipindahkan.", "Ditambah ke favorit.",
        "{target} sedang menyedot.", "{target} kembali ke pangkalan.", "Penyedot debu",
        "pemanas", "AC", "di rumah", "Kipas {n} persen.",
        jarvis=("Tentu, tuan. ", "Sekarang. ", ""),
    ),
    "ms": S(
        "Pemasa berjalan.", "Pemasa dibatalkan.", "Pemasa dijeda.",
        "Apa yang saya mainkan?", "Muzik dipindahkan.", "Ditambah ke kegemaran.",
        "{target} sedang menghisap.", "{target} kembali ke pangkalan.", "Penyedut habuk",
        "pemanasan", "penyaman udara", "di rumah", "Kipas {n} peratus.",
        jarvis=("Sudah tentu, tuan. ", "Sekarang. ", ""),
    ),
    "sw": S(
        "Kipima muda kinafanya kazi.", "Kipima muda kimeghairiwa.", "Kipima muda kimesimamishwa.",
        "Nicheze nini?", "Muziki umehamishwa.", "Imeongezwa kwenye vipendwa.",
        "{target} inasafisha.", "{target} inarudi kwenye kituo.", "Kifyonzamchanga",
        "joto", "kipozaji", "nyumbani", "Feni asilimia {n}.",
        jarvis=("Bila shaka, bwana. ", "Sasa hivi. ", ""),
    ),
    "vi": S(
        "Hẹn giờ đang chạy.", "Đã hủy hẹn giờ.", "Hẹn giờ tạm dừng.",
        "Phát gì?", "Đã chuyển nhạc.", "Đã thêm vào yêu thích.",
        "{target} đang hút bụi.", "{target} về đế sạc.", "Máy hút bụi",
        "sưởi", "điều hòa", "ở nhà", "Quạt {n} phần trăm.",
        jarvis=("Dạ, thưa ông. ", "Ngay. ", ""),
    ),
    "hy": S(
        "Ժամաչափը աշխատում է։",
        "Ժամաչափը չեղարկվեց։",
        "Ժամաչափը դադարեց։",
        "Ի՞նչ նվագեմ։",
        "Երաժշտությունը տեղափոխվեց։",
        "Ավելացվեց նախընտրելիներին։",
        "{target} փոշեկուլ է անում։",
        "{target} վերադառնում է կայան։",
        "Փոշեկուլը",
        "ջեռուցում",
        "սառեցում",
        "տանը",
        "Օդափոխիչը {n} տոկոս։",
        light_suffix=" լույս",
        area_light="լույս {loc}",
        or_home="սարքը",
        list_add="Ցուցակում է։",
        calendar_empty="Հանդիպում չկա։",
        calendar_none="Օրացույց չկա։",
        calendar_need_title="Ի՞նչ անուն։",
        calendar_need_when="Ե՞րբ։",
        calendar_readonly="Միայն կարդալու։",
        calendar_deleted="Ջնջվեց։",
        calendar_which="Ո՞ր հանդիպումը։",
        calendar_no_uid="Նոյնացուցիչ չկա։",
        no_music_player="Նվագարկիչ չկա։",
        correction="Լավ, վերջին նախադասությունը թողնում եմ։",
        turn_on="{target} միացված է։",
        turn_off="{target} անջատված է։",
        toggle="{target} փոխվում է։",
        get_temp="Ջերմաստիճանը {loc}։",
        get_state="Նայում եմ {target}։",
        personality=P(
            "Լավ։ ", "Հաճույքով։ ",
            "Հասկացա։ ", "Արված է։ ",
            "Հիմա կանեմ։ ", "Ամեն ինչ լավ է։ ",
            "Գնանք։ ", "Գեղեցիկ։ ",
            "Լավ։ ", "Եթե պետք է։ ",
            "Իհարկե։ ", "Ի՛նչ անակնկալ։ ",
            "Aye. ", "Նավապետ։ ",
            "Հանգիստ։ ", "Դանդաղ։ ",
            "Այո։ ", "Այո, իմ գանձ։ ",
            "Իհարկե, պարոն։ ", "Անմիջապես։ ",
        ),
    ),
    "ka": S(
        "ტაიმერი მუშაობს.",
        "ტაიმერი გაუქმდა.",
        "ტაიმერი შეჩერდა.",
        "რა დავუკრა?",
        "მუსიკა გადავიდა.",
        "დაემატა რჩეულებს.",
        "{target} ასუფთავებს.",
        "{target} ბრუნდება სადგურზე.",
        "მტვერსასრუტი",
        "გათბობა",
        "გაგრილება",
        "სახლში",
        "ვენტილატორი {n} პროცენტზე.",
        light_suffix=" ნათურა",
        area_light="ნათურა {loc}",
        or_home="მოწყობილობა",
        list_add="სიაშია.",
        calendar_empty="შეხვედრა არ არის.",
        calendar_none="კალენდარი არ არის.",
        calendar_need_title="რა სახელი?",
        calendar_need_when="როდის?",
        calendar_readonly="მხოლოდ კითხვა.",
        calendar_deleted="წაიშალა.",
        calendar_which="რომელი შეხვედრა?",
        calendar_no_uid="იდენტიფიკატორი არაა.",
        no_music_player="დამკვრელი არაა.",
        correction="კარგი, ბოლო წინადადებას ვტოვებ.",
        turn_on="{target} ჩართულია.",
        turn_off="{target} გამორთულია.",
        toggle="{target} იცვლება.",
        get_temp="ტემპერატურა {loc}.",
        get_state="ვუყურებ {target}.",
        personality=P(
            "კარგი. ", "სიამოვნებით. ",
            "გავიგე. ", "გაკეთდა. ",
            "ახლა გავაკეთებ. ", "ყველაფერი კარგადაა. ",
            "წავიდეთ. ", "ლამაზი. ",
            "კარგი. ", "თუ უნდა. ",
            "რა თქმა უნდა. ", "რა სიურპრიზი. ",
            "Aye. ", "კაპიტანო. ",
            "მშვიდად. ", "ნელა. ",
            "დიახ. ", "დიახ, ჩემო განძო. ",
            "რა თქმა უნდა, ბატონო. ", "მაშინვე. ",
        ),
    ),
    "mn": S(
        "Таймер ажиллаж байна.", "Таймер цуцлагдлаа.", "Таймер түр зогслоо.",
        "Юу тоглуулах вэ?", "Хөгжим шилжлээ.", "Дуртайд нэмэгдлээ.",
        "{target} тоос соруулж байна.", "{target} суурь руу явна.", "Тоос сорогч",
        "халаалт", "хөргөлт", "гэртээ", "Сэнс {n} хувь.",
        light_suffix=" гэрэл", area_light="гэрэл {loc}", or_home="төхөөрөмж",
        list_add="Жагсаалтад нэмэв.",
        calendar_empty="Уулзалт алга.", calendar_none="Календарь алга.",
        calendar_need_title="Ямар нэр?", calendar_need_when="Хэзээ?",
        calendar_readonly="Зөвхөн унших.", calendar_deleted="Устгалаа.",
        calendar_which="Аль уулзалт?", calendar_no_uid="Таних тэмдэг алга.",
        no_music_player="Тоглуулагч алга.",
        correction="За, сүүлийн өгүүлбэрийг орхиё.",
        turn_on="{target} аслаа.", turn_off="{target} унтарлаа.",
        toggle="{target} солигдож байна.", get_temp="Температур {loc}.",
        get_state="Би {target}-г харж байна.",
        personality=P(
            "За. ", "Баяртайгаар. ",
            "Ойлголоо. ", "Боллоо. ",
            "Одоо хийнэ. ", "Бүгд сайн. ",
            "Явцгаая. ", "Сайн. ",
            "За. ", "Хэрэв хэрэгтэй. ",
            "Мэдээж. ", "Ямар гайхалтай. ",
            "Aye. ", "Ахмад. ",
            "Тайван. ", "Аажуу. ",
            "Тийм. ", "Тийм, миний эрдэнэ. ",
            "Мэдээж, ноён. ", "Даруй. ",
        ),
    ),
}
