"""Speech slots: CJK, RTL, Thai, Korean, Japanese, Turkish."""

from lang_packs.speech_slots import P, S

SCRIPT = {
    "zh-CN": S(
        "定时器已开始。", "定时器已取消。", "定时器已暂停。",
        "播放什么？", "音乐已转移。", "已加入收藏。",
        "{target}开始清扫。", "{target}正在回充。", "扫地机",
        "暖气", "空调", "家里", "风扇{n}%。",
        light_suffix="灯", area_light="{loc}的灯", or_home="设备",
        list_add="已加入清单。",
        calendar_empty="没有日程。", calendar_none="没有日历。",
        calendar_need_title="叫什么名字？", calendar_need_when="什么时候？",
        calendar_readonly="日历只读。", calendar_deleted="已删除。",
        calendar_which="哪个日程？", calendar_no_uid="没有标识。",
        no_music_player="没有播放器。",
        jarvis=("当然，先生。 ", "马上。 ", ""),
    ),
    "zh-TW": S(
        "計時器已開始。", "計時器已取消。", "計時器已暫停。",
        "要播放什麼？", "音樂已轉移。", "已加入收藏。",
        "{target}開始清掃。", "{target}正在回充。", "掃地機",
        "暖氣", "空調", "家裡", "風扇{n}%。",
        light_suffix="燈", area_light="{loc}的燈", or_home="裝置",
        list_add="已加入清單。",
        calendar_empty="沒有行程。", calendar_none="沒有日曆。",
        calendar_need_title="叫什麼名字？", calendar_need_when="什麼時候？",
        calendar_readonly="日曆唯讀。", calendar_deleted="已刪除。",
        calendar_which="哪個行程？", calendar_no_uid="沒有識別碼。",
        no_music_player="沒有播放器。",
        jarvis=("當然，先生。 ", "馬上。 ", ""),
    ),
    "zh-HK": S(
        "計時器開始咗。", "計時器取消咗。", "計時器暫停咗。",
        "播咩？", "音樂搬咗。", "加咗入收藏。",
        "{target}開始掃地。", "{target}返去充電。", "吸塵機",
        "暖氣", "冷氣", "屋企", "風扇{n}%。",
        light_suffix="燈", area_light="{loc}嘅燈", or_home="裝置",
        list_add="加咗入清單。",
        calendar_empty="冇行程。", calendar_none="冇日曆。",
        calendar_need_title="叫咩名？", calendar_need_when="幾時？",
        calendar_readonly="日曆唯讀。", calendar_deleted="刪咗。",
        calendar_which="邊個行程？", calendar_no_uid="冇識別。",
        no_music_player="冇播放器。",
        jarvis=("當然，先生。 ", "而家。 ", ""),
    ),
    "ar": S(
        "بدأ المؤقت.", "أُلغي المؤقت.", "توقف المؤقت.",
        "ماذا أشغّل؟", "نُقل الصوت.", "أُضيف إلى المفضلة.",
        "{target} يكنس الآن.", "{target} يعود إلى القاعدة.", "المكنسة",
        "تدفئة", "تكييف", "في المنزل", "المروحة على {n} بالمئة.",
        light_suffix=" ضوء", area_light="ضوء {loc}", or_home="الجهاز",
        list_add="أضيف إلى القائمة.",
        jarvis=("طبعا يا سيدي. ", "حالا. ", ""),
    ),
    "he": S(
        "הטיימר רץ.", "הטיימר בוטל.", "הטיימר מושהה.",
        "מה לנגן?", "המוזיקה הועברה.", "נוסף למועדפים.",
        "{target} שואב עכשיו.", "{target} חוזר לעמדת הטעינה.", "השואב",
        "חימום", "מיזוג", "בבית", "מאוורר ב־{n} אחוז.",
        light_suffix=" אור", area_light="אור {loc}", or_home="המכשיר",
        jarvis=("כמובן, אדוני. ", "מיד. ", ""),
    ),
    "fa": S(
        "تایمر شروع شد.", "تایمر لغو شد.", "تایمر مکث شد.",
        "چه چیزی پخش کنم؟", "موسیقی جابه‌جا شد.", "به علاقه‌مندی‌ها اضافه شد.",
        "{target} در حال جارو است.", "{target} به پایگاه برمی‌گردد.", "جاروبرقی",
        "گرمایش", "سرمایش", "در خانه", "پنکه روی {n} درصد.",
        light_suffix=" چراغ", area_light="چراغ {loc}", or_home="دستگاه",
        jarvis=("البته، قربان. ", "فورا. ", ""),
    ),
    "ur": S(
        "ٹائمر چل پڑا۔", "ٹائمر بند ہو گیا۔", "ٹائمر رک گیا۔",
        "کیا چلاؤں؟", "موسیقی منتقل ہو گئی۔", "پسندیدہ میں شامل۔",
        "{target} صاف کر رہا ہے۔", "{target} بیس پر جا رہا ہے۔", "خلاء صاف کن",
        "حرارت", "ایسی", "گھر میں", "پنکھا {n} فیصد پر۔",
        light_suffix=" بتی", area_light="بتی {loc}", or_home="آلہ",
        jarvis=("جی ہاں، سر۔ ", "ابھی۔ ", ""),
    ),
    "tr": S(
        "Zamanlayıcı çalışıyor.", "Zamanlayıcı iptal edildi.", "Zamanlayıcı duraklatıldı.",
        "Ne çalayım?", "Müzik taşındı.", "Favorilere eklendi.",
        "{target} süpürüyor.", "{target} istasyona gidiyor.", "Süpürge",
        "ısıtma", "klima", "evde", "Fan yüzde {n}.",
        light_suffix=" ışık", area_light="{loc} ışığı", or_home="cihaz",
        jarvis=("Tabii, efendim. ", "Hemen. ", ""),
    ),
    "th": S(
        "ตั้งเวลาแล้ว", "ยกเลิกตั้งเวลาแล้ว", "หยุดตั้งเวลาชั่วคราว",
        "จะเล่นอะไร", "ย้ายเพลงแล้ว", "เพิ่มรายการโปรดแล้ว",
        "{target} กำลังดูดฝุ่น", "{target} กลับแท่นชาร์จ", "เครื่องดูดฝุ่น",
        "ความร้อน", "แอร์", "ที่บ้าน", "พัดลม {n} เปอร์เซ็นต์",
        light_suffix=" ไฟ", area_light="ไฟ {loc}", or_home="อุปกรณ์",
        jarvis=("ครับท่าน ", "ทันที ", ""),
    ),
    "ko": S(
        "타이머가 시작됐어요.", "타이머를 취소했어요.", "타이머를 멈췄어요.",
        "뭘 재생할까요?", "음악을 옮겼어요.", "즐겨찾기에 넣었어요.",
        "{target}가 청소 중이에요.", "{target}가 충전대로 가요.", "청소기",
        "난방", "에어컨", "집 안", "선풍기 {n}퍼센트.",
        light_suffix=" 조명", area_light="{loc} 조명", or_home="기기",
        light_set="{target} {n}%",
        jarvis=("물론이죠, 선생님. ", "바로요. ", ""),
    ),
    "ja": S(
        "タイマーを開始しました。", "タイマーを止めました。", "タイマーを一時停止しました。",
        "何を再生しますか？", "音楽を移しました。", "お気に入りに追加しました。",
        "{target}が掃除しています。", "{target}が充電台に戻ります。", "掃除機",
        "暖房", "エアコン", "家の中", "扇風機は{n}パーセントです。",
        light_suffix="の電気", area_light="{loc}のライト", or_home="機器",
        list_add="リストに追加しました。",
        jarvis=("承知しました。 ", "すぐに。 ", ""),
        personality=P(
            "わかりました。 ", "喜んで。 ",
            "了解。 ", "できた。 ",
            "今やります。 ", "大丈夫です。 ",
            "いこう。 ", "いいね。 ",
            "わかった。 ", "仕方ない。 ",
            "もちろん。 ", "驚いたな。 ",
            "Aye. ", "船長。 ",
            "のんびり。 ", "ゆっくり。 ",
            "はい。 ", "はい、宝物。 ",
            "承知しました。 ", "すぐに。 ",
        ),
    ),
}
