"""Speech and chat helpers for pack generation."""


def speech(
    unknown,
    need_on,
    need_off,
    need_which,
    correction,
    clarify,
    clarify_or,
    and_join,
    group_on,
    group_off,
    turn_on,
    turn_on_scene,
    turn_off,
    toggle,
    light_set,
    light_color,
    climate_set,
    heat_noun,
    cool_noun,
    get_temp,
    get_state,
    media_pause,
    media_play,
    media_next,
    media_previous,
    media_mute,
    media_unmute,
    media_volume,
    media_search,
    media_transfer,
    media_favorite,
    fan_set,
    vacuum_start,
    vacuum_dock,
    vacuum_default,
    timer_start,
    timer_cancel,
    timer_pause,
    list_add,
    done,
    light_suffix,
    area_light,
    loc_in,
    loc_in_der,
    loc_home,
    or_home,
    confirm,
) -> dict:
    return {
        "unknown": unknown,
        "need_on": need_on,
        "need_off": need_off,
        "need_which": need_which,
        "correction": correction,
        "clarify": clarify,
        "clarify_or": clarify_or,
        "and_join": and_join,
        "group_on": group_on,
        "group_off": group_off,
        "turn_on": turn_on,
        "turn_on_scene": turn_on_scene,
        "turn_off": turn_off,
        "toggle": toggle,
        "light_set": light_set,
        "light_color": light_color,
        "climate_set": climate_set,
        "heat_noun": heat_noun,
        "cool_noun": cool_noun,
        "get_temp": get_temp,
        "get_state": get_state,
        "media_pause": media_pause,
        "media_play": media_play,
        "media_next": media_next,
        "media_previous": media_previous,
        "media_mute": media_mute,
        "media_unmute": media_unmute,
        "media_volume": media_volume,
        "media_search": media_search,
        "media_transfer": media_transfer,
        "media_favorite": media_favorite,
        "fan_set": fan_set,
        "vacuum_start": vacuum_start,
        "vacuum_dock": vacuum_dock,
        "vacuum_default": vacuum_default,
        "timer_start": timer_start,
        "timer_cancel": timer_cancel,
        "timer_pause": timer_pause,
        "list_add": list_add,
        "done": done,
        "light_suffix": light_suffix,
        "area_light": area_light,
        "loc_in": loc_in,
        "loc_in_der": loc_in_der,
        "loc_home": loc_home,
        "or_home": or_home,
        "confirm": confirm,
    }


def chat(greet, thanks, feeling, identity, tell, yarn, world, advice, open_, news, dismiss, intro, nudge, done) -> dict:
    return {
        "greet": greet,
        "thanks": thanks,
        "feeling": feeling,
        "identity": identity,
        "tell": tell,
        "yarn": yarn,
        "world": world,
        "advice": advice,
        "open": open_,
        "news": news,
        "news_dismiss": dismiss,
        "news_intro": intro,
        "news_nudge": nudge,
        "news_done": done,
    }
