"""Speech slots: Romance, Nordic, de-CH/AT, en-GB, pt-BR, Afrikaans."""

from lang_packs.speech_slots import S

WEST = {
    "fr": S(
        "Minuteur lancé.", "Minuteur arrêté.", "Minuteur en pause.",
        "Que dois-je jouer ?", "Musique déplacée.", "Titre ajouté aux favoris.",
        "{target} aspire.", "{target} rentre à la base.", "L'aspirateur",
        "Chauffage", "Climatisation", "dans la maison", "Ventilateur à {n} pour cent.",
    ),
    "nl": S(
        "Timer loopt.", "Timer uit.", "Timer gepauzeerd.",
        "Wat moet ik afspelen?", "Muziek verplaatst.", "Favoriet toegevoegd.",
        "{target} stofzuigt.", "{target} gaat naar het station.", "De stofzuiger",
        "Verwarming", "Airco", "in huis", "Ventilator op {n} procent.",
    ),
    "es": S(
        "Temporizador en marcha.", "Temporizador cancelado.", "Temporizador en pausa.",
        "Qué reproduzco?", "Música movida.", "Añadido a favoritos.",
        "{target} está aspirando.", "{target} vuelve a la base.", "La aspiradora",
        "calefacción", "aire acondicionado", "en casa", "Ventilador al {n} por ciento.",
        light_suffix=" luz", area_light="luz {loc}", or_home="el aparato",
        jarvis=("Claro, señor. ", "Enseguida. ", ""),
    ),
    "it": S(
        "Timer avviato.", "Timer annullato.", "Timer in pausa.",
        "Cosa riproduco?", "Musica spostata.", "Aggiunto ai preferiti.",
        "{target} sta aspirando.", "{target} torna alla base.", "L'aspirapolvere",
        "riscaldamento", "aria condizionata", "in casa", "Ventola al {n} per cento.",
        light_suffix=" luce", area_light="luce {loc}", or_home="il dispositivo",
        jarvis=("Certo, signore. ", "Subito. ", ""),
    ),
    "pt": S(
        "Temporizador a correr.", "Temporizador cancelado.", "Temporizador em pausa.",
        "O que toco?", "Música movida.", "Adicionado aos favoritos.",
        "{target} está a aspirar.", "{target} volta à base.", "O aspirador",
        "aquecimento", "ar condicionado", "em casa", "Ventoinha a {n} por cento.",
        light_suffix=" luz", area_light="luz {loc}", or_home="o aparelho",
        jarvis=("Claro, senhor. ", "Já faço. ", ""),
    ),
    "ca": S(
        "Temporitzador en marxa.", "Temporitzador cancel·lat.", "Temporitzador en pausa.",
        "Què reprodueixo?", "Música moguda.", "Afegit als preferits.",
        "{target} està aspirant.", "{target} torna a la base.", "L'aspiradora",
        "calefacció", "aire condicionat", "a casa", "Ventilador al {n} per cent.",
        light_suffix=" llum", area_light="llum {loc}", or_home="l'aparell",
        jarvis=("És clar, senyor. ", "Ara mateix. ", ""),
    ),
    "ro": S(
        "Cronometrul rulează.", "Cronometru anulat.", "Cronometru în pauză.",
        "Ce redau?", "Muzica a fost mutată.", "Adăugat la favorite.",
        "{target} aspiră acum.", "{target} se întoarce la bază.", "Aspiratorul",
        "încălzire", "aer condiționat", "acasă", "Ventilator la {n} la sută.",
        light_suffix=" lumină", area_light="lumina {loc}", or_home="aparatul",
        jarvis=("Sigur, domnule. ", "Imediat. ", ""),
    ),
    "da": S(
        "Timeren kører.", "Timeren er slukket.", "Timeren er sat på pause.",
        "Hvad skal jeg spille?", "Musikken er flyttet.", "Føjet til favoritter.",
        "{target} støvsuger.", "{target} kører til stationen.", "Støvsugeren",
        "varme", "aircondition", "hjemme", "Ventilator på {n} procent.",
        jarvis=("Selvfølgelig, sir. ", "Med det samme. ", ""),
    ),
    "nb": S(
        "Timeren kjører.", "Timeren er av.", "Timeren er satt på pause.",
        "Hva skal jeg spille?", "Musikken er flyttet.", "Lagt til i favoritter.",
        "{target} støvsuger.", "{target} kjører til stasjonen.", "Støvsugeren",
        "varme", "klimaanlegg", "hjemme", "Vifte på {n} prosent.",
        jarvis=("Selvsagt, sir. ", "Med en gang. ", ""),
    ),
    "sv": S(
        "Timern är igång.", "Timern är av.", "Timern är pausad.",
        "Vad ska jag spela?", "Musiken är flyttad.", "Tillagd i favoriter.",
        "{target} dammsuger.", "{target} åker till stationen.", "Dammsugaren",
        "värme", "luftkonditionering", "hemma", "Fläkt på {n} procent.",
        jarvis=("Javisst, sir. ", "Genast. ", ""),
    ),
    "fi": S(
        "Ajastin käynnissä.", "Ajastin pois.", "Ajastin tauolla.",
        "Mitä soitetaan?", "Musiikki siirretty.", "Lisätty suosikkeihin.",
        "{target} imuroi.", "{target} palaa telakalle.", "Imuri",
        "lämmitys", "ilmastointi", "kotona", "Tuuletin {n} prosentissa.",
        jarvis=("Totta kai, sir. ", "Heti. ", ""),
    ),
    "de-CH": S(
        "Timer lauft.", "Timer isch uus.", "Timer isch pausiert.",
        "Was söll i abspile?", "Musig isch verschobe.", "Zu de Favoritä derzue.",
        "{target} saugt jetz.", "{target} gaat zrugg a d Station.", "De Staubsauger",
        "Heizig", "Klimaanlage", "i de Wohnig", "Ventilator uf {n} Prozent.",
        light_suffix=" liecht", area_light="Liecht {loc}", or_home="s Grät",
        jarvis=("Natürlich, Sir. ", "Sofort. ", ""),
    ),
    "de-AT": S(
        "Timer läuft.", "Timer is aus.", "Timer is pausiert.",
        "Was soll i abspielen?", "Musik is verschoben.", "Zu den Favoriten dazua.",
        "{target} saugt jetzt.", "{target} fahrt zur Station.", "Der Staubsauger",
        "Heizung", "Klimaanlage", "in der Wohnung", "Ventilator auf {n} Prozent.",
        light_suffix=" licht", area_light="Licht {loc}", or_home="das Gerät",
        jarvis=("Natürlich, Sir. ", "Gleich. ", ""),
    ),
    "en-GB": S(
        "Timer is running.", "Timer is off.", "Timer is paused.",
        "What should I play?", "Music moved.", "Added to favourites.",
        "{target} is hoovering.", "{target} is heading to the dock.", "The hoover",
        "heating", "air con", "at home", "Fan is at {n} percent.",
        light_suffix=" light", area_light="light {loc}", or_home="the device",
        jarvis=("Certainly, sir. ", "Right away. ", ""),
    ),
    "pt-BR": S(
        "Temporizador rodando.", "Temporizador cancelado.", "Temporizador em pausa.",
        "O que eu toco?", "Música movida.", "Adicionado aos favoritos.",
        "{target} está aspirando.", "{target} volta pra base.", "O aspirador",
        "aquecimento", "ar-condicionado", "em casa", "Ventilador em {n} por cento.",
        jarvis=("Claro, senhor. ", "Já faço. ", ""),
    ),
    "af": S(
        "Afteller loop.", "Afteller is af.", "Afteller is onderbreek.",
        "Wat moet ek speel?", "Musiek is verskuif.", "By gunstelinge gevoeg.",
        "{target} stofsuig nou.", "{target} gaan na die stasie.", "Die stofsuier",
        "verhitting", "lugversorging", "by die huis", "Waaier op {n} persent.",
        jarvis=("Natuurlik, meneer. ", "Dadelik. ", ""),
    ),
}
