"""Timer decrease verbs, how-long prompts, and media fillers for generated packs.

de/en stay handwritten. Decrease words must not collide with Dim (fr moins).
"""

from __future__ import annotations

DECREASE = {
    "fr": ["reduire"],
    "nl": ["verlaag"],
    "es": ["reduce"],
    "it": ["riduci"],
    "pt": ["diminui"],
    "ca": ["redueix"],
    "ro": ["scade"],
    "da": ["saenk"],
    "nb": ["reduser"],
    "sv": ["minska"],
    "fi": ["vahenna"],
    "de-CH": ["verringere"],
    "de-AT": ["verringere"],
    "en-GB": ["decrease"],
    "pt-BR": ["diminui"],
    "af": ["verminder"],
    "cs": ["sniz"],
    "sk": ["zniz"],
    "pl": ["zmniejsz"],
    "hu": ["csokkent"],
    "hr": ["smanji"],
    "sl": ["zmanjsaj"],
    "bg": ["намали"],
    "el": ["μειωσε"],
    "sr": ["смањи"],
    "sr-Latn": ["smanji"],
    "uk": ["зменш"],
    "zh-CN": ["减少"],
    "zh-TW": ["減少"],
    "zh-HK": ["減少"],
    "ar": ["أنقص"],
    "he": ["הפחת"],
    "fa": ["کاهش"],
    "ur": ["کم"],
    "tr": ["azalt"],
    "th": ["ลด"],
    "ko": ["줄여"],
    "ja": ["減らす"],
    "cy": ["lleihau"],
    "et": ["vahenda"],
    "eu": ["gutxitu"],
    "ga": ["laghdaigh"],
    "gl": ["reduce"],
    "is": ["minnka"],
    "lb": ["verringer"],
    "kw": ["lehe"],
    "lt": ["sumazink"],
    "lv": ["samazini"],
    "id": ["kurangi"],
    "ms": ["kurang"],
    "sw": ["punguza"],
    "vi": ["giam"],
    "hi": ["ghatao"],
    "bn": ["komau"],
    "gu": ["kami"],
    "kn": ["tagisu"],
    "ml": ["kuraykku"],
    "mr": ["kami"],
    "ta": ["kurai"],
    "te": ["tagginchu"],
    "pa": ["ghatao"],
    "ne": ["ghatau"],
    "hy": ["nvazecnel"],
    "ka": ["sheamcire"],
    "mn": ["buuruul"],
}

HOW_LONG = {
    "fr": "Combien de temps ?",
    "nl": "Hoe lang?",
    "es": "¿Cuánto tiempo?",
    "it": "Quanto tempo?",
    "pt": "Quanto tempo?",
    "ca": "Quant de temps?",
    "ro": "Cât timp?",
    "da": "Hvor længe?",
    "nb": "Hvor lenge?",
    "sv": "Hur länge?",
    "fi": "Kuinka kauan?",
    "de-CH": "Wie lang?",
    "de-AT": "Wie lange?",
    "en-GB": "How long?",
    "pt-BR": "Quanto tempo?",
    "af": "Hoe lank?",
    "cs": "Jak dlouho?",
    "sk": "Ako dlho?",
    "pl": "Jak długo?",
    "hu": "Mennyi ideig?",
    "hr": "Koliko dugo?",
    "sl": "Kako dolgo?",
    "bg": "Колко дълго?",
    "el": "Πόσο ώρα;",
    "sr": "Колико дуго?",
    "sr-Latn": "Koliko dugo?",
    "uk": "Як довго?",
    "zh-CN": "多长时间？",
    "zh-TW": "多長時間？",
    "zh-HK": "幾耐？",
    "ar": "كم المدة؟",
    "he": "לכמה זמן?",
    "fa": "چقدر؟",
    "ur": "کتنا دیر؟",
    "tr": "Ne kadar?",
    "th": "นานเท่าไหร่",
    "ko": "얼마나요?",
    "ja": "どのくらい？",
    "cy": "Am faint?",
    "et": "Kui kaua?",
    "eu": "Zenbat denbora?",
    "ga": "Cá fhad?",
    "gl": "Canto tempo?",
    "is": "Hversu lengi?",
    "lb": "Wéi laang?",
    "kw": "Pys termyn?",
    "lt": "Kaip ilgai?",
    "lv": "Cik ilgi?",
    "id": "Berapa lama?",
    "ms": "Berapa lama?",
    "sw": "Muda gani?",
    "vi": "Bao lâu?",
    "hi": "कितनी देर?",
    "bn": "কতক্ষণ?",
    "gu": "કેટલી વાર?",
    "kn": "ಎಷ್ಟು ಹೊತ್ತು?",
    "ml": "എത്ര നേരം?",
    "mr": "किती वेळ?",
    "ta": "எவ்வளவு நேரம்?",
    "te": "ఎంతసేపు?",
    "pa": "ਕਿੰਨਾ ਚਿਰ?",
    "ne": "कति बेर?",
    "hy": "Որքա՞ն?",
    "ka": "რამდენ ხანს?",
    "mn": "Хэр удаан?",
}

UNITS = {
    "fr": (["heure"], ["minute"], ["seconde"]),
    "nl": (["uur"], ["minuut"], ["seconde"]),
    "es": (["hora"], ["minuto"], ["segundo"]),
    "it": (["ora"], ["minuto"], ["secondo"]),
    "pt": (["hora"], ["minuto"], ["segundo"]),
    "ca": (["hora"], ["minut"], ["segon"]),
    "ro": (["ora"], ["minut"], ["secunda"]),
    "da": (["time"], ["minut"], ["sekund"]),
    "nb": (["time"], ["minutt"], ["sekund"]),
    "sv": (["timme"], ["minut"], ["sekund"]),
    "fi": (["tunti"], ["minuutti"], ["sekunti"]),
    "de-CH": (["stund"], ["minute"], ["sekunde"]),
    "de-AT": (["stunde"], ["minute"], ["sekunde"]),
    "en-GB": (["hour", "hours"], ["minute", "minutes"], ["second", "seconds"]),
    "pt-BR": (["hora"], ["minuto"], ["segundo"]),
    "af": (["uur"], ["minuut"], ["sekonde"]),
    "cs": (["hodina"], ["minuta"], ["sekunda"]),
    "sk": (["hodina"], ["minuta"], ["sekunda"]),
    "pl": (["godzina"], ["minuta"], ["sekunda"]),
    "hu": (["ora"], ["perc"], ["masodperc"]),
    "hr": (["sat"], ["minuta"], ["sekunda"]),
    "sl": (["ura"], ["minuta"], ["sekunda"]),
    "bg": (["час"], ["минута"], ["секунда"]),
    "el": (["ωρα"], ["λεπτο"], ["δευτερολεπτο"]),
    "sr": (["сат"], ["минут"], ["секунда"]),
    "sr-Latn": (["sat"], ["minut"], ["sekunda"]),
    "uk": (["година"], ["хвилина"], ["секунда"]),
    "zh-CN": (["小时"], ["分钟"], ["秒"]),
    "zh-TW": (["小時"], ["分鐘"], ["秒"]),
    "zh-HK": (["小時"], ["分鐘"], ["秒"]),
    "ar": (["ساعة"], ["دقيقة"], ["ثانية"]),
    "he": (["שעה"], ["דקה"], ["שניה"]),
    "fa": (["ساعت"], ["دقیقه"], ["ثانیه"]),
    "ur": (["گھنٹہ"], ["منٹ"], ["سیکنڈ"]),
    "tr": (["saat"], ["dakika"], ["saniye"]),
    "th": (["ชั่วโมง"], ["นาที"], ["วินาที"]),
    "ko": (["시간"], ["분"], ["초"]),
    "ja": (["時間"], ["分"], ["秒"]),
    "cy": (["awr"], ["munud"], ["eiliad"]),
    "et": (["tund"], ["minut"], ["sekund"]),
    "eu": (["ordu"], ["minutu"], ["segundo"]),
    "ga": (["uair"], ["noimead"], ["soicind"]),
    "gl": (["hora"], ["minuto"], ["segundo"]),
    "is": (["klukkustund"], ["minuta"], ["sekunda"]),
    "lb": (["stonn"], ["minutt"], ["sekonn"]),
    "kw": (["our"], ["mynysen"], ["sekond"]),
    "lt": (["valanda"], ["minute"], ["sekunde"]),
    "lv": (["stunda"], ["minute"], ["sekunde"]),
    "id": (["jam"], ["menit"], ["detik"]),
    "ms": (["jam"], ["minit"], ["saat"]),
    "sw": (["saa"], ["dakika"], ["sekunde"]),
    "vi": (["gio"], ["phut"], ["giay"]),
    "hi": (["ghanta"], ["minute"], ["second"]),
    "bn": (["ghonta"], ["minute"], ["second"]),
    "gu": (["kalak"], ["minute"], ["second"]),
    "kn": (["gante"], ["minute"], ["second"]),
    "ml": (["manikkoor"], ["minute"], ["second"]),
    "mr": (["tas"], ["minute"], ["second"]),
    "ta": (["mani"], ["minute"], ["second"]),
    "te": (["ganta"], ["minute"], ["second"]),
    "pa": (["ghanta"], ["minute"], ["second"]),
    "ne": (["ghanta"], ["minute"], ["second"]),
    "hy": (["zham"], ["rope"], ["vayrkyan"]),
    "ka": (["saati"], ["wuti"], ["wami"]),
    "mn": (["tsag"], ["minut"], ["sekund"]),
}

EN_UNITS = (["hour", "hours", "hrs"], ["minute", "minutes", "min", "mins"], ["second", "seconds", "sec", "secs"])

MUSIC = {
    "cy": ["cerddoriaeth"],
    "kw": ["ilow"],
    "ga": ["ceol"],
    "is": ["tonlist"],
    "eu": ["musika"],
    "et": ["muusika"],
    "lb": ["musek"],
    "lt": ["muzika"],
    "lv": ["muzika"],
    "ur": ["موسیقی"],
}


def apply_to_words(code: str, words: dict) -> None:
    words.setdefault("decrease", list(DECREASE.get(code) or ["minus"]))
    hours, minutes, seconds = UNITS.get(code, EN_UNITS)
    if not words.get("hours"):
        words["hours"] = list(hours)
    if not words.get("minutes"):
        words["minutes"] = list(minutes)
    if not words.get("seconds"):
        words["seconds"] = list(seconds)
    if music := MUSIC.get(code):
        words.setdefault("music", list(music))


def how_long(code: str) -> str:
    if code in HOW_LONG:
        return HOW_LONG[code]
    base = code.split("-", 1)[0]
    return HOW_LONG.get(base, "How long?")
