"""Page-guide chrome for MENA, Hellenic, and Caucasian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_guides import guides

PACKS: dict[str, dict[str, str]] = {
    "ar": guides(
        empty="لا نماذج من نقطة النهاية هذه. اكتب معرّفاً.",
        fail="تعذّر سرد النماذج. اكتب معرّفاً.",
        loading="جارٍ تحميل النماذج…",
        thinking="الإيقاف يستخدم علم no-thinking لدى المزوّد (Lemonade/llama.cpp: chat_template_kwargs، سلسلة o من OpenAI: reasoning_effort none، Anthropic: احذف thinking، Google: thinking_budget 0).",
        convos="قل شيئاً عبر Assist. يظهر هنا.",
        evaluator="اكتب كما في البيت. الخطوة المؤطّرة هي التي أُطلقت.",
        routines="اسم منطوق يبدأ سكربت Home Assistant.",
        sentences="جملة واحدة نحو نية معروفة. ثم جرّبها.",
        policies="ثلاثة مسارات. قاعدتك المنزلية تفوز أولاً. جرّب جملة بالأسفل.",
        lab="اكتب جملة، ثم حلّل أو Enter.",
    ),
    "he": guides(
        empty="אין מודלים מנקודת הקצה הזו. הקלידו id.",
        fail="לא ניתן היה למנות מודלים. הקלידו id.",
        loading="טוען מודלים…",
        thinking="כבוי משתמש בדגל no-thinking של הספק (Lemonade/llama.cpp: chat_template_kwargs, סדרת o של OpenAI: reasoning_effort none, Anthropic: השמיטו thinking, Google: thinking_budget 0).",
        convos="אמרו משהו דרך Assist. זה יופיע כאן.",
        evaluator="הקלידו כמו בבית. השלב הממוסגר הוא זה שנורה.",
        routines="שם מדובר מפעיל סקריפט של Home Assistant.",
        sentences="משפט אחד לכוונה ידועה. אחר כך נסו.",
        policies="שלושה נתיבים. כלל הבית שלכם מנצח קודם. נסו משפט למטה.",
        lab="הקלידו משפט, אחר כך נתח או Enter.",
    ),
    "fa": guides(
        empty="مدلی از این نقطه پایانی نیست. یک id بنویسید.",
        fail="فهرست مدل‌ها گرفته نشد. یک id بنویسید.",
        loading="در حال بارگذاری مدل‌ها…",
        thinking="خاموش پرچم no-thinking ارائه‌دهنده را به کار می‌برد (Lemonade/llama.cpp: chat_template_kwargs، سری o OpenAI: reasoning_effort none، Anthropic: thinking را حذف کن، Google: thinking_budget 0).",
        convos="چیزی از راه Assist بگویید. اینجا ظاهر می‌شود.",
        evaluator="همان‌طور که در خانه می‌گویید بنویسید. گام قاب‌دار همان است که شلیک شد.",
        routines="نام گفته‌شده یک اسکریپت Home Assistant را شروع می‌کند.",
        sentences="یک جمله روی نیت شناخته‌شده. بعد امتحان کنید.",
        policies="سه مسیر. قاعده خانه شما اول می‌برد. جمله‌ای پایین را بیازمایید.",
        lab="جمله‌ای بنویسید، سپس تحلیل یا Enter.",
    ),
    "ur": guides(
        empty="اس اینڈ پوائنٹ سے کوئی ماڈل نہیں۔ ایک id لکھیں۔",
        fail="ماڈل فہرست نہ ہو سکے۔ ایک id لکھیں۔",
        loading="ماڈل لوڈ ہو رہے ہیں…",
        thinking="بند ہر فراہم کنندہ کا no-thinking جھنڈا استعمال کرتا ہے (Lemonade/llama.cpp: chat_template_kwargs، OpenAI o سیریز: reasoning_effort none، Anthropic: thinking چھوڑیں، Google: thinking_budget 0)۔",
        convos="Assist کے ذریعے کچھ کہیں۔ وہ یہاں دکھے گا۔",
        evaluator="ویسا ہی لکھیں جیسے گھر پر۔ فریم والا مرحلہ وہی ہے جو چلا۔",
        routines="بولا گیا نام Home Assistant اسکرپٹ شروع کرتا ہے۔",
        sentences="ایک جملہ معلوم ارادے پر۔ پھر آزمائیں۔",
        policies="تین لین۔ آپ کا گھر کا قاعدہ پہلے جیتتا ہے۔ نیچے جملہ آزمائیں۔",
        lab="ایک جملہ لکھیں، پھر تجزیہ یا Enter۔",
    ),
    "tr": guides(
        empty="Bu uçtan model yok. Bir id yazın.",
        fail="Modeller listelenemedi. Bir id yazın.",
        loading="Modeller yükleniyor…",
        thinking="Kapalı, sağlayıcının no-thinking bayrağını kullanır (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o serisi: reasoning_effort none, Anthropic: thinking’i atla, Google: thinking_budget 0).",
        convos="Assist üzerinden bir şey söyleyin. Burada görünür.",
        evaluator="Evde söylediğiniz gibi yazın. Çerçeveli adım tetiklenen adımdır.",
        routines="Söylenen ad bir Home Assistant betiğini başlatır.",
        sentences="Bilinen bir niyete bir cümle. Sonra dene.",
        policies="Üç şerit. Ev kuralınız önce kazanır. Aşağıda bir cümle dene.",
        lab="Bir cümle yazın, sonra Çözümle veya Enter.",
    ),
    "el": guides(
        empty="Δεν υπάρχουν μοντέλα από αυτό το endpoint. Πληκτρολογήστε id.",
        fail="Αδυναμία λίστας μοντέλων. Πληκτρολογήστε id.",
        loading="Φόρτωση μοντέλων…",
        thinking="Ανενεργό χρησιμοποιεί τη σημαία no-thinking του παρόχου (Lemonade/llama.cpp: chat_template_kwargs, σειρά o OpenAI: reasoning_effort none, Anthropic: παράλειψη thinking, Google: thinking_budget 0).",
        convos="Πες κάτι μέσω Assist. Εμφανίζεται εδώ.",
        evaluator="Γράψε το όπως στο σπίτι. Το βήμα στο πλαίσιο είναι αυτό που πυροδοτήθηκε.",
        routines="Ένα προφορικό όνομα ξεκινά ένα σενάριο Home Assistant.",
        sentences="Μία πρόταση σε γνωστή πρόθεση. Μετά δοκίμασέ την.",
        policies="Τρεις λωρίδες. Ο οικιακός κανόνας σου κερδίζει πρώτος. Δοκίμασε πρόταση παρακάτω.",
        lab="Πληκτρολόγησε πρόταση, μετά Ανάλυση ή Enter.",
    ),
    "hy": guides(
        empty="Այս endpoint-ից մոդել չկա։ Մուտքագրեք id։",
        fail="Մոդելները չհաջողվեց ցուցակել։ Մուտքագրեք id։",
        loading="Մոդելները բեռնվում են…",
        thinking="Անջատվածը օգտագործում է մատակարարի no-thinking դրոշը (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o շարք՝ reasoning_effort none, Anthropic՝ բաց թողնել thinking, Google՝ thinking_budget 0)։",
        convos="Ասա ինչ-որ բան Assist-ով։ Այստեղ կերևա։",
        evaluator="Գրիր ինչպես տանը։ Շրջանակված քայլը այն է, որ գործարկվեց։",
        routines="Ասված անունը սկսում է Home Assistant սկրիպտ։",
        sentences="Մեկ նախադասություն հայտնի մտադրության վրա։ Հետո փորձիր։",
        policies="Երեք ուղի։ Քո տան կանոնը հաղթում է առաջինը։ Փորձիր նախադասություն ներքևում։",
        lab="Մուտքագրիր նախադասություն, հետո Վերլուծել կամ Enter։",
    ),
    "ka": guides(
        empty="ამ endpoint-იდან მოდელები არაა. აკრიფე id.",
        fail="მოდელების სია ვერ ჩაიტვირთა. აკრიფე id.",
        loading="მოდელები იტვირთება…",
        thinking="გამორთული იყენებს მომწოდებლის no-thinking დროშას (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o სერია: reasoning_effort none, Anthropic: thinking-ის გამოტოვება, Google: thinking_budget 0).",
        convos="თქვი რამე Assist-ით. აქ გამოჩნდება.",
        evaluator="დაწერე როგორც სახლში. ჩარჩოში მოქცეული ნაბიჯი ისაა, რომელიც ამუშავდა.",
        routines="ნათქვამი სახელი იწყებს Home Assistant სკრიპტს.",
        sentences="ერთი წინადადება ცნობილ განზრახვაზე. შემდეგ სცადე.",
        policies="სამი ბილიკი. შენი სახლის წესი იგებს პირველი. სცადე წინადადება ქვემოთ.",
        lab="აკრიფე წინადადება, შემდეგ ანალიზი ან Enter.",
    ),
}
