"""Page-guide chrome for Nordic and Baltic Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_guides import guides

PACKS: dict[str, dict[str, str]] = {
    "da": guides(
        empty="Ingen modeller fra dette endpoint. Skriv et id.",
        fail="Kunne ikke liste modeller. Skriv et id.",
        loading="Indlæser modeller…",
        thinking="Fra bruger udbyderens no-thinking-flag (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serie: reasoning_effort none, Anthropic: udlad thinking, Google: thinking_budget 0).",
        convos="Sig noget via Assist. Det vises her.",
        evaluator="Skriv det som hjemme. Det indrammede trin er det, der affyrede.",
        routines="Et talt navn starter et Home Assistant-script.",
        sentences="Én sætning på en kendt intent. Prøv den bagefter.",
        policies="Tre spor. Din husregel vinder først. Prøv en sætning nedenfor.",
        lab="Skriv en sætning, derefter Analysér eller Enter.",
    ),
    "nb": guides(
        empty="Ingen modeller fra dette endepunktet. Skriv en id.",
        fail="Kunne ikke liste modeller. Skriv en id.",
        loading="Laster modeller…",
        thinking="Av bruker leverandørens no-thinking-flagg (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serie: reasoning_effort none, Anthropic: utelat thinking, Google: thinking_budget 0).",
        convos="Si noe via Assist. Det vises her.",
        evaluator="Skriv det som hjemme. Det innrammede steget er det som utløste.",
        routines="Et talt navn starter et Home Assistant-skript.",
        sentences="Én setning på en kjent intensjon. Prøv den etterpå.",
        policies="Tre spor. Husregelen din vinner først. Prøv en setning nedenfor.",
        lab="Skriv en setning, deretter Analyser eller Enter.",
    ),
    "sv": guides(
        empty="Inga modeller från den här endpointen. Skriv ett id.",
        fail="Kunde inte lista modeller. Skriv ett id.",
        loading="Hämtar modeller…",
        thinking="Av använder leverantörens no-thinking-flagga (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serie: reasoning_effort none, Anthropic: utelämna thinking, Google: thinking_budget 0).",
        convos="Säg något via Assist. Det visas här.",
        evaluator="Skriv som hemma. Det inramade steget är det som utlöstes.",
        routines="Ett talat namn startar ett Home Assistant-skript.",
        sentences="En mening mot en känd avsikt. Prova den sedan.",
        policies="Tre spår. Din husregel vinner först. Prova en mening nedan.",
        lab="Skriv en mening, sedan Analysera eller Enter.",
    ),
    "fi": guides(
        empty="Ei malleja tästä endpointista. Kirjoita id.",
        fail="Malleja ei voitu listata. Kirjoita id.",
        loading="Ladataan malleja…",
        thinking="Pois käyttää toimittajan no-thinking-lippua (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-sarja: reasoning_effort none, Anthropic: jätä thinking pois, Google: thinking_budget 0).",
        convos="Sano jotain Assistin kautta. Se näkyy tässä.",
        evaluator="Kirjoita kuten kotona. Kehystetty askel on se joka laukesi.",
        routines="Puhuttu nimi käynnistää Home Assistant -skriptin.",
        sentences="Yksi lause tunnettuun intentioon. Kokeile sen jälkeen.",
        policies="Kolme kaistaa. Talosääntösi voittaa ensin. Kokeile lausetta alla.",
        lab="Kirjoita lause, sitten Analysoi tai Enter.",
    ),
    "is": guides(
        empty="Engin módel frá þessum endapunkti. Sláðu inn id.",
        fail="Gat ekki listað módel. Sláðu inn id.",
        loading="Hleð módelum…",
        thinking="Slökkt notar no-thinking-fána veitanda (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-röð: reasoning_effort none, Anthropic: sleppa thinking, Google: thinking_budget 0).",
        convos="Segðu eitthvað í gegnum Assist. Það birtist hér.",
        evaluator="Sláðu inn eins og heima. Ramminn sýnir skrefið sem fór af stað.",
        routines="Talað nafn ræsir Home Assistant skriftu.",
        sentences="Ein setning á þekktan ásetning. Prófaðu svo.",
        policies="Þrjár brautir. Húsreglan þín vinnur fyrst. Prófaðu setningu hér fyrir neðan.",
        lab="Sláðu inn setningu, svo Greina eða Enter.",
    ),
    "et": guides(
        empty="Sellelt endpointilt pole mudeleid. Sisesta id.",
        fail="Mudeleid ei õnnestunud loetleda. Sisesta id.",
        loading="Laadin mudeleid…",
        thinking="Väljas kasutab teenusepakkuja no-thinking lippu (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-seeria: reasoning_effort none, Anthropic: jäta thinking ära, Google: thinking_budget 0).",
        convos="Ütle midagi Assisti kaudu. See ilmub siia.",
        evaluator="Kirjuta nagu kodus. Raamitud samm on see, mis rakendus.",
        routines="Öeldud nimi käivitab Home Assistanti skripti.",
        sentences="Üks lause tuntud kavatsusele. Seejärel proovi.",
        policies="Kolm rada. Sinu kodureegel võidab esimesena. Proovi allpool lauset.",
        lab="Kirjuta lause, siis Analüüsi või Enter.",
    ),
    "lt": guides(
        empty="Iš šio endpoint nėra modelių. Įveskite id.",
        fail="Nepavyko išvardyti modelių. Įveskite id.",
        loading="Įkeliami modeliai…",
        thinking="Išjungta naudoja teikėjo no-thinking vėliavą (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o serija: reasoning_effort none, Anthropic: praleisti thinking, Google: thinking_budget 0).",
        convos="Pasakykite ką nors per Assist. Tai atsiranda čia.",
        evaluator="Rašykite kaip namie. Įrėmintas žingsnis yra tas, kuris suveikė.",
        routines="Ištartas vardas paleidžia Home Assistant scenarijų.",
        sentences="Vienas sakinys žinomam ketinimui. Tada išbandykite.",
        policies="Trys juostos. Jūsų namų taisyklė laimi pirma. Išbandykite sakinį žemiau.",
        lab="Įveskite sakinį, tada Analizuoti arba Enter.",
    ),
    "lv": guides(
        empty="No šī endpoint nav modeļu. Ierakstiet id.",
        fail="Neizdevās uzskaitīt modeļus. Ierakstiet id.",
        loading="Ielādē modeļus…",
        thinking="Izslēgts izmanto piegādātāja no-thinking karogu (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o sērija: reasoning_effort none, Anthropic: izlaist thinking, Google: thinking_budget 0).",
        convos="Sakiet kaut ko caur Assist. Tas parādās šeit.",
        evaluator="Rakstiet kā mājās. Ierāmētais solis ir tas, kas nostrādāja.",
        routines="Izrunāts vārds palaiž Home Assistant skriptu.",
        sentences="Viens teikums uz zināmu nodomu. Pēc tam izmēģiniet.",
        policies="Trīs joslas. Jūsu mājas likums uzvar pirmais. Izmēģiniet teikumu zemāk.",
        lab="Ierakstiet teikumu, tad Analizēt vai Enter.",
    ),
}
