"""Dashboard LLM chrome for MENA, Hellenic, and Caucasian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_llm import llm_row

PACKS = {
    "ar": llm_row(
        llmCalls="استدعاءات LLM",
        llmCallsCaption="المصدر: LLM المحرك، آخر 24 ساعة",
        llmKindRefine="تنقيح",
        llmKindAssist="Assist",
        llmKindChat="دردشة",
        llmErrors="أخطاء",
        llmAcceptRate="معدل القبول",
        llmLatency="زمن استجابة LLM",
        llmLatencyCaption="المصدر: LLM المحرك، نافذة منزلقة",
        llmTokens="رموز",
        llmTokensCaption="المصدر: استخدام المنبع، عندما يرسله النموذج",
        llmNoCalls="لا توجد استدعاءات LLM بعد.",
        labThisTurn="هذا الدور",
    ),
    "he": llm_row(
        llmCalls="קריאות LLM",
        llmCallsCaption="מקור: LLM של המנוע, 24 השעות האחרונות",
        llmKindRefine="עידון",
        llmKindAssist="Assist",
        llmKindChat="שיחה",
        llmErrors="שגיאות",
        llmAcceptRate="שיעור קבלה",
        llmLatency="השהיית LLM",
        llmLatencyCaption="מקור: LLM של המנוע, חלון מתגלגל",
        llmTokens="אסימונים",
        llmTokensCaption="מקור: שימוש במעלה הזרם, כשהמודל שולח אותו",
        llmNoCalls="אין עדיין קריאות LLM.",
        labThisTurn="התור הזה",
    ),
    "fa": llm_row(
        llmCalls="فراخوانی‌های LLM",
        llmCallsCaption="منبع: LLM موتور، ۲۴ ساعت گذشته",
        llmKindRefine="پالایش",
        llmKindAssist="Assist",
        llmKindChat="گفتگو",
        llmErrors="خطاها",
        llmAcceptRate="نرخ پذیرش",
        llmLatency="تأخیر LLM",
        llmLatencyCaption="منبع: LLM موتور، پنجره غلتان",
        llmTokens="توکن",
        llmTokensCaption="منبع: مصرف بالادست، وقتی مدل بفرستد",
        llmNoCalls="هنوز فراخوانی LLM نیست.",
        labThisTurn="این نوبت",
    ),
    "ur": llm_row(
        llmCalls="LLM کالز",
        llmCallsCaption="ماخذ: انجن LLM، پچھلے 24 گھنٹے",
        llmKindRefine="نکھار",
        llmKindAssist="Assist",
        llmKindChat="چیٹ",
        llmErrors="غلطیاں",
        llmAcceptRate="قبول کی شرح",
        llmLatency="LLM تاخیر",
        llmLatencyCaption="ماخذ: انجن LLM، رولنگ ونڈو",
        llmTokens="ٹوکن",
        llmTokensCaption="ماخذ: اپ اسٹریم استعمال، جب ماڈل بھیجے",
        llmNoCalls="ابھی کوئی LLM کال نہیں۔",
        labThisTurn="یہ باری",
    ),
    "tr": llm_row(
        llmCalls="LLM çağrıları",
        llmCallsCaption="Kaynak: motor LLM, son 24 saat",
        llmKindRefine="inceltme",
        llmKindAssist="Assist",
        llmKindChat="sohbet",
        llmErrors="hatalar",
        llmAcceptRate="kabul oranı",
        llmLatency="LLM gecikmesi",
        llmLatencyCaption="Kaynak: motor LLM, kayan pencere",
        llmTokens="jetonlar",
        llmTokensCaption="Kaynak: yukarı akış kullanımı, model gönderirse",
        llmNoCalls="Henüz LLM çağrısı yok.",
        labThisTurn="Bu tur",
    ),
    "el": llm_row(
        llmCalls="Κλήσεις LLM",
        llmCallsCaption="Πηγή: LLM της μηχανής, τελευταίες 24 ώρες",
        llmKindRefine="εξευγενισμός",
        llmKindAssist="Assist",
        llmKindChat="κουβέντα",
        llmErrors="σφάλματα",
        llmAcceptRate="ποσοστό αποδοχής",
        llmLatency="Καθυστέρηση LLM",
        llmLatencyCaption="Πηγή: LLM της μηχανής, κυλιόμενο παράθυρο",
        llmTokens="μάρκες",
        llmTokensCaption="Πηγή: χρήση ανάντη, όταν το μοντέλο τη στέλνει",
        llmNoCalls="Δεν υπάρχουν ακόμη κλήσεις LLM.",
        labThisTurn="Αυτή η σειρά",
    ),
    "hy": llm_row(
        llmCalls="LLM կանչեր",
        llmCallsCaption="Աղբյուր՝ շարժիչի LLM, վերջին 24 ժամ",
        llmKindRefine="հղկում",
        llmKindAssist="Assist",
        llmKindChat="զրույց",
        llmErrors="սխալներ",
        llmAcceptRate="ընդունման մասնաբաժին",
        llmLatency="LLM ուշացում",
        llmLatencyCaption="Աղբյուր՝ շարժիչի LLM, սահող պատուհան",
        llmTokens="թոքեններ",
        llmTokensCaption="Աղբյուր՝ վերին հոսքի օգտագործում, երբ մոդելն ուղարկում է",
        llmNoCalls="Դեռ LLM կանչեր չկան։",
        labThisTurn="Այս քայլը",
    ),
    "ka": llm_row(
        llmCalls="LLM გამოძახებები",
        llmCallsCaption="წყარო: ძრავის LLM, ბოლო 24 საათი",
        llmKindRefine="გაპრიალება",
        llmKindAssist="Assist",
        llmKindChat="საუბარი",
        llmErrors="შეცდომები",
        llmAcceptRate="მიღების წილი",
        llmLatency="LLM დაყოვნება",
        llmLatencyCaption="წყარო: ძრავის LLM, მოცურავე ფანჯარა",
        llmTokens="ტოკენები",
        llmTokensCaption="წყარო: ზედა ნაკადის მოხმარება, როცა მოდელი აგზავნის",
        llmNoCalls="LLM გამოძახება ჯერ არ არის.",
        labThisTurn="ეს სვლა",
    ),
}
