"""Rules/house guides and leftover Settings chrome for Indic Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_pages import pages
from lang_packs.web_ui_pages_indic_rest import PACKS as REST
from lang_packs.web_ui_pages_indic_tail import PACKS as TAIL

PACKS: dict[str, dict[str, str]] = {
    "hi": pages(
        guideRoutinesSay="तुम क्या कहते हो?",
        guideRoutinesSayHint="शुभ रात्रि, मैं जाता हूँ, फिल्म की शाम।",
        guideRoutinesScript="कौन सी स्क्रिप्ट?",
        guideRoutinesScriptHint="script.xxx चुनें। entity id न लिखें।",
        guideSentencesPhrase="कौन सा वाक्य?",
        guideSentencesPhraseHint="जैसा सच में कहते हो।",
        guideSentencesIntent="Klar क्या करे?",
        guideSentencesIntentHint="आशय चुनें, उपकरण केवल ज़रूरत पर।",
        guideSentencesTest="आज़माएँ",
        guideSentencesTestHint="वाक्य रखने से पहले झलक।",
        guidePoliciesMatch="कौन से आदेश",
        guidePoliciesMatchHint="Engine-matcher। चालू रखें, जब तक वजह न पता हो।",
        guidePoliciesLang="भाषा और Safety",
        guidePoliciesLangHint="Pack-seeds और शब्दकोश। केवल जब कोई शब्द गलत हो।",
        guidePoliciesHouse="तुम्हारा नियम",
        guidePoliciesHouseHint="जब → तब। उपकरण या कमरा चुनें, id न लिखें।",
        guidePoliciesTest="आज़माएँ",
        guidePoliciesTestHint="वाक्य लिखें और विश्लेषण। फ्रेम वाला पथ चला।",
        houseGuideGraph="जाँच के लिए उपकरण छुएँ। खींचना केवल कार्ड हिलाता है।",
        houseGuideDevices="खोजें, फिर एक उपकरण छुएँ।",
        houseGuideMap="सुझाव मानें या कमरा चुनें।",
        menu="मेनू",
        ragModeShort="घर का संदर्भ",
        llmThinking="Thinking",
        unitSystem="इकाइयाँ",
        unitSystemHint="बोले और समझे गए तापमान। बत्तियाँ, टाइमर और चमक वैसी रहती हैं।",
        unitMetric="मेट्रिक",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="भाषाएँ",
        settingsNavVoice="आवाज़",
        llmProvider="प्रदाता",
        llmPresetCustom="OpenAI-संगत",
        personalityPrompt="व्यक्तित्व Prompt",
    ),
    "bn": pages(
        guideRoutinesSay="তুমি কী বলো?",
        guideRoutinesSayHint="শুভ রাত্রি, আমি যাচ্ছি, সিনেমার সন্ধ্যা।",
        guideRoutinesScript="কোন script?",
        guideRoutinesScriptHint="script.xxx বেছে নিন। entity id লিখবেন না।",
        guideSentencesPhrase="কোন বাক্য?",
        guideSentencesPhraseHint="যেমন সত্যিই বলেন।",
        guideSentencesIntent="Klar কী করবে?",
        guideSentencesIntentHint="অভিপ্রায় বেছে নিন, যন্ত্র শুধু দরকারে।",
        guideSentencesTest="চেষ্টা",
        guideSentencesTestHint="বাক্য রাখার আগে ঝলক।",
        guidePoliciesMatch="কোন আদেশ",
        guidePoliciesMatchHint="Engine-matcher। চালু রাখুন, কারণ না জানা পর্যন্ত।",
        guidePoliciesLang="ভাষা ও Safety",
        guidePoliciesLangHint="Pack-seeds ও অভিধান। শুধু কোনো শব্দ ভুল হলে।",
        guidePoliciesHouse="তোমার নিয়ম",
        guidePoliciesHouseHint="যখন → তখন। যন্ত্র বা ঘর বেছে নিন, id লিখবেন না।",
        guidePoliciesTest="চেষ্টা",
        guidePoliciesTestHint="বাক্য লিখুন আর বিশ্লেষণ। ফ্রেমের পথটা চালু হয়েছে।",
        houseGuideGraph="পরীক্ষায় যন্ত্র ছুঁয়ে দেখুন। টানা শুধু কার্ড সরায়।",
        houseGuideDevices="খুঁজুন, তারপর একটি যন্ত্র ছুঁয়ে দেখুন।",
        houseGuideMap="পরামর্শ মানুন বা ঘর বেছে নিন।",
        menu="মেনু",
        ragModeShort="ঘরের প্রসঙ্গ",
        llmThinking="Thinking",
        unitSystem="একক",
        unitSystemHint="বলা ও বোঝা তাপমাত্রা। আলো, টাইমার ও উজ্জ্বলতা থাকে যেমন আছে।",
        unitMetric="মেট্রিক",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="ভাষা",
        settingsNavVoice="কণ্ঠ",
        llmProvider="প্রদানকারী",
        llmPresetCustom="OpenAI-সঙ্গত",
        personalityPrompt="ব্যক্তিত্ব Prompt",
    ),
}
PACKS.update(REST)
PACKS.update(TAIL)
