"""Custom-voice and interview chrome for West European Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice

PACKS: dict[str, dict[str, str]] = {
    "fr": voice(
        personalityCustom="Voix perso",
        customVoice="Voix perso",
        customVoiceHint="Le seed fixe le personnage. Les curseurs ne font que raffiner la façon de parler. Le verrouillage de langue et les règles de sécurité restent.",
        customVoiceMake="Écrire la voix à partir du seed et des curseurs",
        customVoiceFail="Impossible d'écrire une voix. Vérifie le LLM.",
        customVoiceName="Nom de la voix",
        customVoiceNameHint="Ainsi apparaît cette personnalité dans la liste.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Qui Klar doit être, indépendamment des curseurs. Par exemple : Tu es Spock de Star Trek.",
        interviewTraitsHint="0 = off, 10 = fort. Uniquement le débit, pas le personnage.",
        interviewWarmth="Chaleur",
        interviewSarcasm="Sarcasme",
        interviewFormality="Formalité",
        interviewVerbosity="Verbosité",
        interviewEnergy="Énergie",
        interviewAddress="Comment Klar doit-il t'adresser ?",
        interviewAddressDu="Tu",
        interviewAddressSie="Vous",
        interviewAddressName="Prénom",
        interviewName="Nom",
        interviewTone="Ton",
        interviewToneShort="Court",
        interviewToneWarm="Chaleureux",
        interviewToneDry="Sec",
        interviewHumor="Humour",
        interviewHumorNone="Aucun",
        interviewHumorLight="Léger",
        interviewHumorSharp="Piquant",
        interviewLength="Longueur",
        interviewLengthOne="Une phrase",
        interviewLengthMore="Un peu plus",
        interviewTaboo="Ne pas dire",
    ),
    "nl": voice(
        personalityCustom="Eigen stem",
        customVoice="Eigen stem",
        customVoiceHint="De seed bepaalt het personage. Schuifregelaars verfijnen alleen hoe het spreekt. Taalslot en veiligheidsregels blijven.",
        customVoiceMake="Stem schrijven uit seed en schuifregelaars",
        customVoiceFail="Kon geen stem schrijven. Controleer de LLM.",
        customVoiceName="Stemnaam",
        customVoiceNameHint="Zo verschijnt deze persoonlijkheid in de lijst.",
        customVoiceSeed="Seed-prompt",
        customVoiceSeedHint="Wie Klar moet zijn, los van de schuifregelaars. Bijvoorbeeld: Jij bent Spock uit Star Trek.",
        interviewTraitsHint="0 = uit, 10 = sterk. Alleen de voordracht, niet het personage.",
        interviewWarmth="Warmte",
        interviewSarcasm="Sarcasme",
        interviewFormality="Formaliteit",
        interviewVerbosity="Uitgebreidheid",
        interviewEnergy="Energie",
        interviewAddress="Hoe moet Klar je aanspreken?",
        interviewAddressDu="Je",
        interviewAddressSie="U",
        interviewAddressName="Voornaam",
        interviewName="Naam",
        interviewTone="Toon",
        interviewToneShort="Kort",
        interviewToneWarm="Warm",
        interviewToneDry="Droog",
        interviewHumor="Humor",
        interviewHumorNone="Geen",
        interviewHumorLight="Licht",
        interviewHumorSharp="Scherp",
        interviewLength="Lengte",
        interviewLengthOne="Eén zin",
        interviewLengthMore="Iets meer",
        interviewTaboo="Niet zeggen",
    ),
    "es": voice(
        personalityCustom="Voz propia",
        customVoice="Voz propia",
        customVoiceHint="La semilla fija el personaje. Los deslizadores solo afinan cómo habla. El bloqueo de idioma y las reglas de seguridad se quedan.",
        customVoiceMake="Escribir la voz a partir de la semilla y los deslizadores",
        customVoiceFail="No se pudo escribir una voz. Revisa el LLM.",
        customVoiceName="Nombre de la voz",
        customVoiceNameHint="Así aparece esta personalidad en la lista.",
        customVoiceSeed="Indicación semilla",
        customVoiceSeedHint="Quién debe ser Klar, independiente de los deslizadores. Por ejemplo: Eres Spock de Star Trek.",
        interviewTraitsHint="0 = off, 10 = fuerte. Solo el habla, no el personaje.",
        interviewWarmth="Calidez",
        interviewSarcasm="Sarcasmo",
        interviewFormality="Formalidad",
        interviewVerbosity="Verbosidad",
        interviewEnergy="Energía",
        interviewAddress="¿Cómo debe dirigirse Klar a ti?",
        interviewAddressDu="Tú",
        interviewAddressSie="Usted",
        interviewAddressName="Nombre de pila",
        interviewName="Nombre",
        interviewTone="Tono",
        interviewToneShort="Corto",
        interviewToneWarm="Cálido",
        interviewToneDry="Seco",
        interviewHumor="Humor",
        interviewHumorNone="Ninguno",
        interviewHumorLight="Ligero",
        interviewHumorSharp="Cortante",
        interviewLength="Longitud",
        interviewLengthOne="Una frase",
        interviewLengthMore="Un poco más",
        interviewTaboo="No decir",
    ),
    "it": voice(
        personalityCustom="Voce personalizzata",
        customVoice="Voce personalizzata",
        customVoiceHint="Il seed fissa il personaggio. I cursori raffinano solo il modo di parlare. Blocco lingua e regole di sicurezza restano.",
        customVoiceMake="Scrivi la voce da seed e cursori",
        customVoiceFail="Impossibile scrivere una voce. Controlla l'LLM.",
        customVoiceName="Nome della voce",
        customVoiceNameHint="Così compare questa personalità nell'elenco.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Chi deve essere Klar, indipendentemente dai cursori. Ad esempio: Sei Spock di Star Trek.",
        interviewTraitsHint="0 = off, 10 = forte. Solo il modo di parlare, non il personaggio.",
        interviewWarmth="Calore",
        interviewSarcasm="Sarcasmo",
        interviewFormality="Formalità",
        interviewVerbosity="Verbosità",
        interviewEnergy="Energia",
        interviewAddress="Come deve rivolgersi Klar?",
        interviewAddressDu="Tu",
        interviewAddressSie="Lei",
        interviewAddressName="Nome",
        interviewName="Nome",
        interviewTone="Tono",
        interviewToneShort="Corto",
        interviewToneWarm="Caldo",
        interviewToneDry="Secco",
        interviewHumor="Umorismo",
        interviewHumorNone="Nessuno",
        interviewHumorLight="Leggero",
        interviewHumorSharp="Tagliente",
        interviewLength="Lunghezza",
        interviewLengthOne="Una frase",
        interviewLengthMore="Un po' di più",
        interviewTaboo="Non dire",
    ),
    "pt": voice(
        personalityCustom="Voz própria",
        customVoice="Voz própria",
        customVoiceHint="A semente define a personagem. Os cursores só afinam a forma de falar. O bloqueio de língua e as regras de segurança mantêm-se.",
        customVoiceMake="Escrever a voz a partir da semente e dos cursores",
        customVoiceFail="Não foi possível escrever uma voz. Verifica o LLM.",
        customVoiceName="Nome da voz",
        customVoiceNameHint="Assim aparece esta personalidade na lista.",
        customVoiceSeed="Prompt semente",
        customVoiceSeedHint="Quem o Klar deve ser, independente dos cursores. Por exemplo: És o Spock de Star Trek.",
        interviewTraitsHint="0 = off, 10 = forte. Só a dicção, não a personagem.",
        interviewWarmth="Calor",
        interviewSarcasm="Sarcasmo",
        interviewFormality="Formalidade",
        interviewVerbosity="Verbosidade",
        interviewEnergy="Energia",
        interviewAddress="Como deve o Klar tratar-te?",
        interviewAddressDu="Tu",
        interviewAddressSie="Você",
        interviewAddressName="Nome próprio",
        interviewName="Nome",
        interviewTone="Tom",
        interviewToneShort="Curto",
        interviewToneWarm="Quente",
        interviewToneDry="Seco",
        interviewHumor="Humor",
        interviewHumorNone="Nenhum",
        interviewHumorLight="Leve",
        interviewHumorSharp="Afiado",
        interviewLength="Comprimento",
        interviewLengthOne="Uma frase",
        interviewLengthMore="Um pouco mais",
        interviewTaboo="Não dizer",
    ),
    "ca": voice(
        personalityCustom="Veu pròpia",
        customVoice="Veu pròpia",
        customVoiceHint="La llavor fixa el personatge. Els lliscadors només afinen com parla. El bloqueig de llengua i les regles de seguretat es queden.",
        customVoiceMake="Escriu la veu a partir de la llavor i els lliscadors",
        customVoiceFail="No s'ha pogut escriure una veu. Comprova l'LLM.",
        customVoiceName="Nom de la veu",
        customVoiceNameHint="Així apareix aquesta personalitat a la llista.",
        customVoiceSeed="Indicació llavor",
        customVoiceSeedHint="Qui ha de ser Klar, independent dels lliscadors. Per exemple: Ets en Spock de Star Trek.",
        interviewTraitsHint="0 = off, 10 = fort. Només l'elocució, no el personatge.",
        interviewWarmth="Calidesa",
        interviewSarcasm="Sarcasme",
        interviewFormality="Formalitat",
        interviewVerbosity="Verbositat",
        interviewEnergy="Energia",
        interviewAddress="Com t'ha d'adreçar Klar?",
        interviewAddressDu="Tu",
        interviewAddressSie="Vós",
        interviewAddressName="Nom",
        interviewName="Nom",
        interviewTone="To",
        interviewToneShort="Curt",
        interviewToneWarm="Càlid",
        interviewToneDry="Sec",
        interviewHumor="Humor",
        interviewHumorNone="Cap",
        interviewHumorLight="Lleuger",
        interviewHumorSharp="Tallant",
        interviewLength="Llargada",
        interviewLengthOne="Una frase",
        interviewLengthMore="Una mica més",
        interviewTaboo="No dir",
    ),
    "ro": voice(
        personalityCustom="Voce proprie",
        customVoice="Voce proprie",
        customVoiceHint="Seed-ul fixează personajul. Cursoarele doar rafinează vorbirea. Blocarea limbii și regulile de siguranță rămân.",
        customVoiceMake="Scrie vocea din seed și cursoare",
        customVoiceFail="Nu s-a putut scrie o voce. Verifică LLM-ul.",
        customVoiceName="Numele vocii",
        customVoiceNameHint="Așa apare această personalitate în listă.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Cine trebuie să fie Klar, independent de cursoare. De exemplu: Ești Spock din Star Trek.",
        interviewTraitsHint="0 = off, 10 = puternic. Doar livrarea, nu personajul.",
        interviewWarmth="Căldură",
        interviewSarcasm="Sarcasm",
        interviewFormality="Formalitate",
        interviewVerbosity="Verbalitate",
        interviewEnergy="Energie",
        interviewAddress="Cum să ți se adreseze Klar?",
        interviewAddressDu="Tu",
        interviewAddressSie="Dumneavoastră",
        interviewAddressName="Prenume",
        interviewName="Nume",
        interviewTone="Ton",
        interviewToneShort="Scurt",
        interviewToneWarm="Cald",
        interviewToneDry="Sec",
        interviewHumor="Umor",
        interviewHumorNone="Fără",
        interviewHumorLight="Ușor",
        interviewHumorSharp="Ascuțit",
        interviewLength="Lungime",
        interviewLengthOne="O frază",
        interviewLengthMore="Un pic mai mult",
        interviewTaboo="Nu spune",
    ),
    "pt-BR": voice(
        personalityCustom="Voz própria",
        customVoice="Voz própria",
        customVoiceHint="A semente define o personagem. Os controles só afinam o jeito de falar. O bloqueio de idioma e as regras de segurança ficam.",
        customVoiceMake="Escrever a voz a partir da semente e dos controles",
        customVoiceFail="Não foi possível escrever uma voz. Verifique o LLM.",
        customVoiceName="Nome da voz",
        customVoiceNameHint="Assim essa personalidade aparece na lista.",
        customVoiceSeed="Prompt semente",
        customVoiceSeedHint="Quem o Klar deve ser, independente dos controles. Por exemplo: Você é o Spock de Star Trek.",
        interviewTraitsHint="0 = off, 10 = forte. Só a fala, não o personagem.",
        interviewWarmth="Calor",
        interviewSarcasm="Sarcasmo",
        interviewFormality="Formalidade",
        interviewVerbosity="Verbosidade",
        interviewEnergy="Energia",
        interviewAddress="Como o Klar deve te tratar?",
        interviewAddressDu="Você",
        interviewAddressSie="O senhor",
        interviewAddressName="Nome",
        interviewName="Nome",
        interviewTone="Tom",
        interviewToneShort="Curto",
        interviewToneWarm="Quente",
        interviewToneDry="Seco",
        interviewHumor="Humor",
        interviewHumorNone="Nenhum",
        interviewHumorLight="Leve",
        interviewHumorSharp="Ácido",
        interviewLength="Comprimento",
        interviewLengthOne="Uma frase",
        interviewLengthMore="Um pouco mais",
        interviewTaboo="Não dizer",
    ),
    "gl": voice(
        personalityCustom="Voz propia",
        customVoice="Voz propia",
        customVoiceHint="A semente fixa a personaxe. Os deslizadores só afínan como fala. O bloqueo de lingua e as regras de seguridade quedan.",
        customVoiceMake="Escribir a voz a partir da semente e dos deslizadores",
        customVoiceFail="Non se puido escribir unha voz. Comproba o LLM.",
        customVoiceName="Nome da voz",
        customVoiceNameHint="Así aparece esta personalidade na lista.",
        customVoiceSeed="Indicación semente",
        customVoiceSeedHint="Quen debe ser Klar, independente dos deslizadores. Por exemplo: Es Spock de Star Trek.",
        interviewTraitsHint="0 = off, 10 = forte. Só a dicción, non a personaxe.",
        interviewWarmth="Calidez",
        interviewSarcasm="Sarcasmo",
        interviewFormality="Formalidade",
        interviewVerbosity="Verbosidade",
        interviewEnergy="Enerxía",
        interviewAddress="Como debe dirixirse Klar a ti?",
        interviewAddressDu="Ti",
        interviewAddressSie="Vostede",
        interviewAddressName="Nome",
        interviewName="Nome",
        interviewTone="Ton",
        interviewToneShort="Curto",
        interviewToneWarm="Cálido",
        interviewToneDry="Seco",
        interviewHumor="Humor",
        interviewHumorNone="Ningún",
        interviewHumorLight="Lixeiro",
        interviewHumorSharp="Afilado",
        interviewLength="Lonxitude",
        interviewLengthOne="Unha frase",
        interviewLengthMore="Un pouco máis",
        interviewTaboo="Non dicir",
    ),
}
