"""Lab / mapping / backup chrome for Germanic and Celtic Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_table import parse_rows

CODES = ["de-CH", "de-AT", "en-GB", "af", "lb", "cy", "eu", "ga", "kw"]

TABLE = """
parseHint	S Labor isch de Assist-Pfad für d gwählt Sproch. Entscheid und Intents da führt Klar us. Satztrigger nur, wenn Klar nöd erreichbar isch.	Das Labor ist der Assist-Pfad für die gewählte Sprache. Entscheidung und Intents hier führt Klar aus. Satztrigger nur, wenn Klar nicht erreichbar ist.	Lab is the Assist path for the selected language. Decision and intents here are what Klar runs. Sentence triggers run only if Klar is unreachable.	Die lab is die Assist-pad vir die gekose taal. Besluit en intents hier voer Klar uit. Sinsnellers loop net as Klar onbereikbaar is.	De Labo ass de Assist-Pad fir déi gewielte Sprooch. Decisioun an Intents hei féiert Klar aus. Saztrigger nëmmen, wann Klar net erreechbar ass.	Y lab yw llwybr Assist ar gyfer yr iaith a ddewiswyd. Penderfyniad a bwriadau yma yw'r hyn mae Klar yn ei redeg. Dim ond os yw Klar yn anghyraeddadwy y rhed sbardunau brawddeg.	Laborategia da hautatutako hizkuntzaren Assist bidea. Hemen dagoen erabakia eta asmoak Klarrek exekutatzen ditu. Esaldi-abiarazleak Klar iristezin denean soilik.	Is é an tsaotharlann cosán Assist na teanga roghnaithe. Is iad an cinneadh agus na hintinní anseo a rithfidh Klar. Ní rithfidh spreagthóirí abairte ach má tá Klar dorochtana.	An labordy yw hyns Assist an yeth dewys. An ervirans ha intents omma yw an pyth a wra Klar. Ny wre triggerow lavar marnas mar nyns yw Klar kavadow.
triggerFirst	Klar-Parse, denn de Pfad. Assist startet kein andere Intent, kein Satztrigger und kein Wetter-Fallback.	Klar-Parse, dann dieser Pfad. Assist startet keinen anderen Intent, keinen Satztrigger und keinen Wetter-Fallback.	Klar parse, then that path. Assist does not run a different intent, a sentence trigger, or a weather fallback.	Klar-ontleding, dan daardie pad. Assist laat nie 'n ander intent, 'n sinsneller of 'n weer-terugval loop nie.	Klar-Parse, dann deen Pad. Assist start kee aneren Intent, kee Saztrigger an kee Wieder-Fallback.	Parse Klar, yna'r llwybr hwnnw. Nid yw Assist yn rhedeg bwriad gwahanol, sbardun brawddeg, na chwymp tywydd.	Klar parse, gero bide hori. Assist-ek ez du asmo desberdinik, esaldi-abiarazlerik edo eguraldi-erreserbarik exekutatzen.	Parsáil Klar, ansin an cosán sin. Ní ritheann Assist intent eile, spreagthóir abairte, ná cúltaca aimsire.	Parse Klar, ena an hyns na. Ny wre Assist intent aral, trigger lavar, na fallback kewer.
labPipeline	Pipeline	Pipeline	Pipeline	Pyplyn	Pipeline	Piblinell	Hodi	Píblíne	Piblinen
labChipContextOnly	nur Kontext	nur Kontext	context only	slegs konteks	nëmme Kontext	cyd-destun yn unig	testuingurua soilik	comhthéacs amháin	kendonyn ken
labChipNluRag	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG
labChipSemantic	semantisch	semantisch	semantic	semanties	semantesch	semanteg	semantikoa	sémanteach	semantek
labChipNoConfirm	ohni Bestätigig	ohne Bestätigung	no confirm	sonder bevestiging	ouni Bestätegung	dim cadarnhad	baieztapenik gabe	gan deimhniú	heb afydhya
labChipLlmRefine	LLM-Verfiinerig	LLM-Verfeinerung	LLM refine	LLM-verfyning	LLM-Verfeinerung	mân-osod LLM	LLM finketa	snasú LLM	finheans LLM
labChipCalendarLlm	Kaländer-LLM	Kalender-LLM	calendar LLM	kalender-LLM	Kalenner-LLM	calendr LLM	egutegi LLM	féilire LLM	devisi LLM
labChipQuietAck	churzi Bestätigig	kurze Bestätigung	quiet ack	stil bevestiging	kuerz Bestätegung	cadarnhad byr	baieztapen laburra	deimhniú ciúin	afydhyans berr
labChipLlmTools	LLM-Wärchzüüg	LLM-Werkzeuge	LLM tools	LLM-gereedskap	LLM-Geschier	offerynnau LLM	LLM tresnak	uirlisí LLM	toulyow LLM
labChipLlmChat	LLM-Chat	LLM-Chat	LLM chat	LLM-klets	LLM-Chat	sgwrs LLM	LLM txata	comhrá LLM	keskows LLM
labChipConfirmRisky	riskant bestätige	riskant bestätigen	confirm risky	bevestig risiko	riskant bestätegen	cadarnhau risg	arriskua baieztatu	deimhnigh riosca	afydhya risk
labDecisionExecute	Klar usfüehre	Klar ausführen	Klar execute	Klar uitvoer	Klar ausféieren	Klar yn gweithredu	Klar exekutatu	Klar a rith	Klar oberi
labDecisionBriefing	Briefing	Briefing	briefing	inligting	Briefing	briff	briefinga	briefing	briefing
labParse	Klar-Parse	Klar-Parse	Klar parse	Klar-ontleding	Klar-Parse	Parse Klar	Klar parse	Parsáil Klar	Parse Klar
reasonMissingArea	kei Ruum	kein Raum	missing room	geen kamer	kee Zëmmer	dim ystafell	gelarik ez	gan seomra	heb stevell
reasonWeakName	schwache Name	schwacher Name	weak name	swak naam	schwaachen Numm	enw gwan	izen ahula	ainm lag	hanow gwann
reasonReady	bereit	bereit	ready	gereed	bereet	barod	prest	réidh	parys
reasonMatch	Treffer	Treffer	match	tref	Treffer	cydweddiad	bat	meaitseáil	par
sentencesEmpty	En Satz uf en bekannte Intent. Nöd für jedes Liecht.	Ein Satz auf einen bekannten Intent. Nicht für jedes Licht.	One sentence onto a known intent. Not one phrase per light.	Een sin op 'n bekende intent. Nie een frase per lig nie.	Ee Saz op e bekannten Intent. Net fir all Luucht.	Un frawddeg at fwriad hysbys. Nid un ymadrodd fesul golau.	Esaldi bat asmo ezagun batera. Ez esaldi bat argi bakoitzeko.	Abairt amháin ar intent aitheanta. Ní frása amháin in aghaidh an tsolais.	Un lavar war intent aswonnys. Nyns yw lavar pub golow.
policiesEmpty	Erschti passendi Regle gwünnt. Grät/Ruum/Stock wähle, nöd tippe.	Erste zutreffende Regel gewinnt. Gerät/Raum/Etage wählen, nicht tippen.	First matching rule wins. Pick a device, room, or floor — do not type ids.	Eerste passing reël wen. Kies 'n toestel, kamer of vloer — moenie id's tik nie.	Éischt passend Reegel gewënnt. Apparat/Zëmmer/Zock wielen, net tippen.	Y rheol gyfatebol gyntaf sy'n ennill. Dewiswch ddyfais, ystafell neu lawr — peidiwch â theipio id.	Lehen arau bat datorrenak irabazten du. Gailu, gela edo solairua aukeratu — ez idatzi id-rik.	Buaileann an chéad riail mheaitseála. Roghnaigh gléas, seomra nó urlár — ná clóscríobh id.	An kynsa rewl par a wayn. Dewis devis, stevell po leur — na skrif id.
setupAgainWhere	Setup nomol isch under Iistellige.	Setup erneut liegt unter Einstellungen.	Replay setup is in Settings.	Herhaal opstelling is in Instellings.	Setup nach eemol ass ënner Astellungen.	Mae ailchwarae'r gosodiad yn Gosodiadau.	Setup berriro Ezarpenetan dago.	Tá athimirt an t socraithe i Socruithe.	Replay setup yw yn Settyansow.
whyThisBand	Worüm die Band?	Warum diese Band?	Why this band?	Hoekom hierdie band?	Firwat dës Band?	Pam y band hwn?	Zergatik banda hau?	Cén fáth an banda seo?	Prag an band ma?
rememberAsPhrase	Als Phrase merke	Als Phrase merken	Remember as phrase	Onthou as frase	Als Phrase verhalen	Cofiwch fel ymadrodd	Esamolde gisa gogoratu	Cuimhnigh mar fhrása	Perthi avel lavar
evidence	Evidänz	Evidenz	Evidence	Bewys	Beweis	Tystiolaeth	Frogak	Fianaise	Dustuni
names	Nämme	Namen	Names	Name	Nimm	Enwau	Izenak	Ainmneacha	Henwyn
settingsBackup	Iistellige sichere	Einstellungen sichern	Settings backup	Instellingsrugsteun	Astellungen sécheren	Copi wrth gefn gosodiadau	Ezarpenen babeskopia	Cúltaca socruithe	Kopi settyansow
settingsBackupHint	Overlay, Zuornige, Regle und de LLM-Endpunkt. Gspröch und de Huus-Graph blibed uf dere Engine.	Overlay, Zuweisungen, Regeln und der LLM-Endpunkt. Gespräche und der Haus-Graph bleiben auf dieser Engine.	Overlay, assignments, rules, and the LLM endpoint. Conversations and the house graph stay on this engine.	Oorleg, toewysings, reëls en die LLM-eindpunt. Gesprekke en die huisgrafiek bly op hierdie enjin.	Overlay, Zouuerdnungen, Reegelen an den LLM-Endpunkt. Gespréicher an de Haus-Graph bleiwen op dëser Engine.	Haen, aseinadau, rheolau, a phwynt terfyn yr LLM. Mae sgyrsiau a graff y tŷ yn aros ar yr injan hon.	Overlay, esleipenak, arauak eta LLM amaiera-puntua. Elkarrizketak eta etxeko grafoa motor honetan geratzen dira.	Forleagan, sannadh, rialacha, agus críochphointe an LLM. Fanann comhráite agus graf an tí ar an inneall seo.	Overlay, ranna, reylow, ha penn LLM. Keskowsow ha graf an chi a wort war an jynn ma.
settingsBackupDownload	Iistellige abelade	Einstellungen herunterladen	Download settings	Laai instellings af	Astellungen eroflueden	Lawrlwytho gosodiadau	Ezarpenak deskargatu	Íoslódáil socruithe	Isarga settyansow
settingsBackupIncludeKey	API-Key iineh	API-Key einschließen	Include API key	Sluit API-sleutel in	API-Schlëssel abeghuelen	Cynnwys allwedd API	API gakoa sartu	Cuir eochair API san áireamh	Synsa alhwedh API
settingsBackupIncludeKeyHint	Standard us. Aa: s Archiv het de gspicheret LLM-Key.	Standard aus. An: das Archiv enthält den gespeicherten LLM-Key.	Off by default. On: the archive contains the stored LLM key.	Af by verstek. Aan: die argief bevat die gestoorde LLM-sleutel.	Standard aus. Un: d'Archiv huet de gespäicherte LLM-Schlëssel.	I ffwrdd yn ddiofyn. Ymlaen: mae'r archif yn cynnwys allwedd LLM a storir.	Desaktibatuta lehenetsita. Piztuta: artxiboak gordetako LLM gakoa du.	As feadh réamhshocraithe. Ar: tá eochair LLM stóráilte sa chartlann.	Pes default. War: an kuntel a'n jeves an alhwedh LLM gwithys.
settingsBackupIncludeKeyConfirm	S Archiv het de LLM-API-Key. Trotzdem abelade?	Das Archiv enthält den LLM-API-Key. Trotzdem herunterladen?	The archive will contain the LLM API key. Download anyway?	Die argief sal die LLM-API-sleutel bevat. Tog download?	D'Archiv huet de LLM-API-Schlëssel. Trotzdeem eroflueden?	Bydd yr allwedd API LLM yn yr archif. Lawrlwytho serch hynny?	Artxiboak LLM API gakoa izango du. Deskargatu hala ere?	Beidh eochair API an LLM sa chartlann. Íoslódáil mar sin féin?	An kuntel a'n jeves alhwedh API LLM. Isarga ynwedh?
settingsBackupRestore	Iistellige zruggsetze	Einstellungen wiederherstellen	Restore settings	Herstel instellings	Astellungen restauréieren	Adfer gosodiadau	Ezarpenak leheneratu	Athchóirigh socruithe	Dascor settyansow
settingsBackupRestoreConfirm	Das überschriibt alli Klar-Iistellige uf dere Engine.	Das überschreibt alle Klar-Einstellungen auf dieser Engine.	This overwrites all Klar settings on this engine.	Dit oorskryf alle Klar-instellings op hierdie enjin.	Dat iwwerschreift all Klar-Astellungen op dëser Engine.	Mae hyn yn trosysgrifo holl osodiadau Klar ar yr injan hon.	Honek Klar-en ezarpen guztiak gainidazten ditu motor honetan.	Forscríobhann sé seo gach socrú Klar ar an inneall seo.	Hemm a skrif arnowydh pub settyans Klar war an jynn ma.
settingsBackupRestoreOk	Iistellige zruggsetzt.	Einstellungen wiederhergestellt.	Settings restored.	Instellings herstel.	Astellungen restauréiert.	Gosodiadau wedi'u hadfer.	Ezarpenak leheneratu dira.	Socruithe athchóirithe.	Settyansow daskorrys.
settingsBackupRestoreFail	Zruggsetze fählgschlage.	Wiederherstellen fehlgeschlagen.	Could not restore settings.	Kon nie instellings herstel nie.	Restauréieren ass feelgeschloen.	Methwyd adfer gosodiadau.	Ezin izan dira ezarpenak leheneratu.	Níorbh fhéidir socruithe a athchóiriú.	Ny ylli dascor settyansow.
settingsBackupPickFile	Archiv wähle	Archiv wählen	Choose archive	Kies argief	Archiv wielen	Dewiswch archif	Artxiboa aukeratu	Roghnaigh cartlann	Dewis kuntel
speechRefined	LLM-Verfiinerig	LLM-Verfeinerung	LLM refine	LLM-verfyning	LLM-Verfeinerung	mân-osod LLM	LLM finketa	snasú LLM	finheans LLM
speechChat	LLM-Chat	LLM-Chat	LLM chat	LLM-klets	LLM-Chat	sgwrs LLM	LLM txata	comhrá LLM	keskows LLM
refineRejected	D Verfiinerig het d NLU-Antwort bhalte.	Die Verfeinerung hat die NLU-Antwort behalten.	Refine kept the NLU reply.	Verfyning het die NLU-antwoord gehou.	D'Verfeinerung huet d'NLU-Äntwert behalen.	Cadwodd y mân-osod yr ateb NLU.	Finketak NLU erantzuna gorde du.	Choinnigh an snasú an freagra NLU.	Refine a withas gorthyp NLU.
"""

PACKS = parse_rows(CODES, TABLE)
