"""Custom-voice and interview chrome for Slavic and Hungarian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice

PACKS: dict[str, dict[str, str]] = {
    "cs": voice(
        personalityCustom="Vlastní hlas",
        customVoice="Vlastní hlas",
        customVoiceHint="Seed určí postavu. Posuvníky jen doladí způsob řeči. Zámek jazyka a bezpečnostní pravidla zůstanou.",
        customVoiceMake="Napsat hlas ze seedu a posuvníků",
        customVoiceFail="Hlas se nepodařilo napsat. Zkontrolujte LLM.",
        customVoiceName="Název hlasu",
        customVoiceNameHint="Tak se tato osobnost ukáže v seznamu.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Kým má Klar být, nezávisle na posuvnících. Například: Jsi Spock ze Star Treku.",
        interviewTraitsHint="0 = vypnuto, 10 = silné. Jen přednes, ne postava.",
        interviewWarmth="Teplo",
        interviewSarcasm="Sarkasmus",
        interviewFormality="Formálnost",
        interviewVerbosity="Rozvláčnost",
        interviewEnergy="Energie",
        interviewAddress="Jak tě má Klar oslovovat?",
        interviewAddressDu="Ty",
        interviewAddressSie="Vy",
        interviewAddressName="Jméno",
        interviewName="Jméno",
        interviewTone="Tón",
        interviewToneShort="Krátký",
        interviewToneWarm="Teplý",
        interviewToneDry="Suchý",
        interviewHumor="Humor",
        interviewHumorNone="Žádný",
        interviewHumorLight="Lehký",
        interviewHumorSharp="Ostrý",
        interviewLength="Délka",
        interviewLengthOne="Jedna věta",
        interviewLengthMore="Trochu víc",
        interviewTaboo="Neříkat",
    ),
    "sk": voice(
        personalityCustom="Vlastný hlas",
        customVoice="Vlastný hlas",
        customVoiceHint="Seed určí postavu. Posuvníky len dolaďujú spôsob reči. Zámok jazyka a bezpečnostné pravidlá ostanú.",
        customVoiceMake="Napísať hlas zo seedu a posuvníkov",
        customVoiceFail="Hlas sa nepodarilo napísať. Skontrolujte LLM.",
        customVoiceName="Názov hlasu",
        customVoiceNameHint="Tak sa táto osobnosť ukáže v zozname.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Kým má Klar byť, nezávisle od posuvníkov. Napríklad: Si Spock zo Star Treku.",
        interviewTraitsHint="0 = vypnuté, 10 = silné. Len prednes, nie postava.",
        interviewWarmth="Teplo",
        interviewSarcasm="Sarkazmus",
        interviewFormality="Formálnosť",
        interviewVerbosity="Rozvláčnosť",
        interviewEnergy="Energia",
        interviewAddress="Ako ťa má Klar oslovovať?",
        interviewAddressDu="Ty",
        interviewAddressSie="Vy",
        interviewAddressName="Meno",
        interviewName="Meno",
        interviewTone="Tón",
        interviewToneShort="Krátky",
        interviewToneWarm="Teplý",
        interviewToneDry="Suchý",
        interviewHumor="Humor",
        interviewHumorNone="Žiadny",
        interviewHumorLight="Ľahký",
        interviewHumorSharp="Ostrý",
        interviewLength="Dĺžka",
        interviewLengthOne="Jedna veta",
        interviewLengthMore="Trochu viac",
        interviewTaboo="Nepovedať",
    ),
    "pl": voice(
        personalityCustom="Własny głos",
        customVoice="Własny głos",
        customVoiceHint="Seed ustala postać. Suwaki tylko dopracowują sposób mówienia. Blokada języka i reguły bezpieczeństwa zostają.",
        customVoiceMake="Napisz głos z seeda i suwaków",
        customVoiceFail="Nie udało się napisać głosu. Sprawdź LLM.",
        customVoiceName="Nazwa głosu",
        customVoiceNameHint="Tak ta osobowość pojawia się na liście.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Kim Klar ma być, niezależnie od suwaków. Na przykład: Jesteś Spockiem ze Star Treka.",
        interviewTraitsHint="0 = wył., 10 = mocno. Tylko sposób mówienia, nie postać.",
        interviewWarmth="Ciepło",
        interviewSarcasm="Sarkazm",
        interviewFormality="Formalność",
        interviewVerbosity="Gadatliwość",
        interviewEnergy="Energia",
        interviewAddress="Jak Klar ma się do ciebie zwracać?",
        interviewAddressDu="Ty",
        interviewAddressSie="Pan / Pani",
        interviewAddressName="Imię",
        interviewName="Nazwa",
        interviewTone="Ton",
        interviewToneShort="Krótki",
        interviewToneWarm="Ciepły",
        interviewToneDry="Suchy",
        interviewHumor="Humor",
        interviewHumorNone="Brak",
        interviewHumorLight="Lekki",
        interviewHumorSharp="Ostry",
        interviewLength="Długość",
        interviewLengthOne="Jedno zdanie",
        interviewLengthMore="Trochę więcej",
        interviewTaboo="Nie mów",
    ),
    "hu": voice(
        personalityCustom="Saját hang",
        customVoice="Saját hang",
        customVoiceHint="A seed rögzíti a karaktert. A csúszkák csak a beszédmódot finomítják. A nyelvi zár és a biztonsági szabályok megmaradnak.",
        customVoiceMake="Hang írása seedből és csúszkákból",
        customVoiceFail="Nem sikerült hangot írni. Ellenőrizd az LLM-et.",
        customVoiceName="Hang neve",
        customVoiceNameHint="Így jelenik meg ez a személyiség a listában.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Kinek kell Klarnek lennie, a csúszkáktól függetlenül. Például: Te vagy Spock a Star Trekből.",
        interviewTraitsHint="0 = ki, 10 = erős. Csak az előadás, nem a karakter.",
        interviewWarmth="Melegség",
        interviewSarcasm="Szarkazmus",
        interviewFormality="Formálisság",
        interviewVerbosity="Bőbeszédűség",
        interviewEnergy="Energia",
        interviewAddress="Hogyan szólítson Klar?",
        interviewAddressDu="Te",
        interviewAddressSie="Ön",
        interviewAddressName="Keresztnév",
        interviewName="Név",
        interviewTone="Hangnem",
        interviewToneShort="Rövid",
        interviewToneWarm="Meleg",
        interviewToneDry="Száraz",
        interviewHumor="Humor",
        interviewHumorNone="Nincs",
        interviewHumorLight="Enyhe",
        interviewHumorSharp="Éles",
        interviewLength="Hossz",
        interviewLengthOne="Egy mondat",
        interviewLengthMore="Kicsit több",
        interviewTaboo="Ne mondd",
    ),
    "hr": voice(
        personalityCustom="Vlastiti glas",
        customVoice="Vlastiti glas",
        customVoiceHint="Seed određuje lik. Klizači samo dotjeruju način govora. Jezična brava i sigurnosna pravila ostaju.",
        customVoiceMake="Napiši glas iz seeda i klizača",
        customVoiceFail="Glas nije napisan. Provjeri LLM.",
        customVoiceName="Ime glasa",
        customVoiceNameHint="Tako se ova osobnost pojavljuje na popisu.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Tko Klar treba biti, neovisno o klizačima. Na primjer: Ti si Spock iz Star Treka.",
        interviewTraitsHint="0 = isključeno, 10 = jako. Samo izvedba, ne lik.",
        interviewWarmth="Toplina",
        interviewSarcasm="Sarkazam",
        interviewFormality="Formalnost",
        interviewVerbosity="Opširnost",
        interviewEnergy="Energija",
        interviewAddress="Kako te Klar treba oslovljavati?",
        interviewAddressDu="Ti",
        interviewAddressSie="Vi",
        interviewAddressName="Ime",
        interviewName="Ime",
        interviewTone="Ton",
        interviewToneShort="Kratko",
        interviewToneWarm="Toplo",
        interviewToneDry="Suho",
        interviewHumor="Humor",
        interviewHumorNone="Nema",
        interviewHumorLight="Lagano",
        interviewHumorSharp="Oštro",
        interviewLength="Duljina",
        interviewLengthOne="Jedna rečenica",
        interviewLengthMore="Malo više",
        interviewTaboo="Ne reci",
    ),
    "sl": voice(
        personalityCustom="Lastni glas",
        customVoice="Lastni glas",
        customVoiceHint="Seed določi lik. Drsniki samo izpilijo način govora. Jezikovna ključavnica in varnostna pravila ostanejo.",
        customVoiceMake="Napiši glas iz seeda in drsnikov",
        customVoiceFail="Glasu ni bilo mogoče napisati. Preveri LLM.",
        customVoiceName="Ime glasu",
        customVoiceNameHint="Tako se ta osebnost pokaže na seznamu.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Kdo naj bo Klar, neodvisno od drsnikov. Na primer: Ti si Spock iz Star Treka.",
        interviewTraitsHint="0 = izklopljeno, 10 = močno. Samo podaja, ne lik.",
        interviewWarmth="Toplina",
        interviewSarcasm="Sarkazem",
        interviewFormality="Formalnost",
        interviewVerbosity="Zgovornost",
        interviewEnergy="Energija",
        interviewAddress="Kako naj te Klar nagovarja?",
        interviewAddressDu="Ti",
        interviewAddressSie="Vi",
        interviewAddressName="Ime",
        interviewName="Ime",
        interviewTone="Ton",
        interviewToneShort="Kratko",
        interviewToneWarm="Toplo",
        interviewToneDry="Suho",
        interviewHumor="Humor",
        interviewHumorNone="Brez",
        interviewHumorLight="Lahko",
        interviewHumorSharp="Ostro",
        interviewLength="Dolžina",
        interviewLengthOne="En stavek",
        interviewLengthMore="Malo več",
        interviewTaboo="Ne reci",
    ),
    "bg": voice(
        personalityCustom="Собствен глас",
        customVoice="Собствен глас",
        customVoiceHint="Seed определя героя. Плъзгачите само доизпипват говора. Езиковата ключалка и правилата за безопасност остават.",
        customVoiceMake="Напиши глас от seed и плъзгачи",
        customVoiceFail="Гласът не беше написан. Провери LLM.",
        customVoiceName="Име на гласа",
        customVoiceNameHint="Така тази личност се показва в списъка.",
        customVoiceSeed="Seed подкана",
        customVoiceSeedHint="Кой трябва да бъде Klar, независимо от плъзгачите. Например: Ти си Спок от Стар Трек.",
        interviewTraitsHint="0 = изкл., 10 = силно. Само подаването, не героят.",
        interviewWarmth="Топлина",
        interviewSarcasm="Сарказъм",
        interviewFormality="Формалност",
        interviewVerbosity="Многословност",
        interviewEnergy="Енергия",
        interviewAddress="Как да те обръща Klar?",
        interviewAddressDu="Ти",
        interviewAddressSie="Вие",
        interviewAddressName="Име",
        interviewName="Име",
        interviewTone="Тон",
        interviewToneShort="Кратко",
        interviewToneWarm="Топло",
        interviewToneDry="Сухо",
        interviewHumor="Хумор",
        interviewHumorNone="Няма",
        interviewHumorLight="Леко",
        interviewHumorSharp="Остро",
        interviewLength="Дължина",
        interviewLengthOne="Едно изречение",
        interviewLengthMore="Малко повече",
        interviewTaboo="Не казвай",
    ),
    "sr": voice(
        personalityCustom="Сопствени глас",
        customVoice="Сопствени глас",
        customVoiceHint="Seed одређује лик. Клизачи само дотерују говор. Језичка брава и безбедносна правила остају.",
        customVoiceMake="Напиши глас из seed-а и клизача",
        customVoiceFail="Глас није написан. Провери LLM.",
        customVoiceName="Име гласа",
        customVoiceNameHint="Тако се ова личност појављује на списку.",
        customVoiceSeed="Seed промпт",
        customVoiceSeedHint="Ко Klar треба да буде, независно од клизача. На пример: Ти си Спок из Звезданих стаза.",
        interviewTraitsHint="0 = искључено, 10 = јако. Само извођење, не лик.",
        interviewWarmth="Топлина",
        interviewSarcasm="Сарказам",
        interviewFormality="Формалност",
        interviewVerbosity="Опширност",
        interviewEnergy="Енергија",
        interviewAddress="Како да те Klar ословљава?",
        interviewAddressDu="Ти",
        interviewAddressSie="Ви",
        interviewAddressName="Име",
        interviewName="Име",
        interviewTone="Тон",
        interviewToneShort="Кратко",
        interviewToneWarm="Топло",
        interviewToneDry="Суво",
        interviewHumor="Хумор",
        interviewHumorNone="Нема",
        interviewHumorLight="Лако",
        interviewHumorSharp="Оштро",
        interviewLength="Дужина",
        interviewLengthOne="Једна реченица",
        interviewLengthMore="Мало више",
        interviewTaboo="Не реци",
    ),
    "sr-Latn": voice(
        personalityCustom="Sopstveni glas",
        customVoice="Sopstveni glas",
        customVoiceHint="Seed određuje lik. Klizači samo doteruju govor. Jezička brava i bezbednosna pravila ostaju.",
        customVoiceMake="Napiši glas iz seed-a i klizača",
        customVoiceFail="Glas nije napisan. Proveri LLM.",
        customVoiceName="Ime glasa",
        customVoiceNameHint="Tako se ova ličnost pojavljuje na spisku.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Ko Klar treba da bude, nezavisno od klizača. Na primer: Ti si Spok iz Zvezdanih staza.",
        interviewTraitsHint="0 = isključeno, 10 = jako. Samo izvođenje, ne lik.",
        interviewWarmth="Toplina",
        interviewSarcasm="Sarkazam",
        interviewFormality="Formalnost",
        interviewVerbosity="Opširnost",
        interviewEnergy="Energija",
        interviewAddress="Kako da te Klar oslovljava?",
        interviewAddressDu="Ti",
        interviewAddressSie="Vi",
        interviewAddressName="Ime",
        interviewName="Ime",
        interviewTone="Ton",
        interviewToneShort="Kratko",
        interviewToneWarm="Toplo",
        interviewToneDry="Suvo",
        interviewHumor="Humor",
        interviewHumorNone="Nema",
        interviewHumorLight="Lako",
        interviewHumorSharp="Oštro",
        interviewLength="Dužina",
        interviewLengthOne="Jedna rečenica",
        interviewLengthMore="Malo više",
        interviewTaboo="Ne reci",
    ),
    "uk": voice(
        personalityCustom="Власний голос",
        customVoice="Власний голос",
        customVoiceHint="Seed задає персонажа. Повзунки лише шліфують манеру мови. Мовний замок і правила безпеки лишаються.",
        customVoiceMake="Написати голос із seed і повзунків",
        customVoiceFail="Голос не записано. Перевірте LLM.",
        customVoiceName="Назва голосу",
        customVoiceNameHint="Так ця особистість з’являється в списку.",
        customVoiceSeed="Seed-запит",
        customVoiceSeedHint="Ким має бути Klar, незалежно від повзунків. Наприклад: Ти Спок із Зоряного шляху.",
        interviewTraitsHint="0 = вимк., 10 = сильно. Лише подача, не персонаж.",
        interviewWarmth="Тепло",
        interviewSarcasm="Сарказм",
        interviewFormality="Формальність",
        interviewVerbosity="Багатослівність",
        interviewEnergy="Енергія",
        interviewAddress="Як Klar має до тебе звертатися?",
        interviewAddressDu="Ти",
        interviewAddressSie="Ви",
        interviewAddressName="Ім’я",
        interviewName="Ім’я",
        interviewTone="Тон",
        interviewToneShort="Короткий",
        interviewToneWarm="Теплий",
        interviewToneDry="Сухий",
        interviewHumor="Гумор",
        interviewHumorNone="Немає",
        interviewHumorLight="Легкий",
        interviewHumorSharp="Гострий",
        interviewLength="Довжина",
        interviewLengthOne="Одне речення",
        interviewLengthMore="Трохи більше",
        interviewTaboo="Не казати",
    ),
}
