"""Page-guide chrome for Slavic and Hungarian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_guides import guides

PACKS: dict[str, dict[str, str]] = {
    "cs": guides(
        empty="Žádné modely z tohoto endpointu. Zadejte id.",
        fail="Modely se nepodařilo vypsat. Zadejte id.",
        loading="Načítání modelů…",
        thinking="Vypnuto použije příznak no-thinking poskytovatele (Lemonade/llama.cpp: chat_template_kwargs, řada o OpenAI: reasoning_effort none, Anthropic: vynechat thinking, Google: thinking_budget 0).",
        convos="Řekněte něco přes Assist. Objeví se tady.",
        evaluator="Napište to jako doma. Orámovaný krok je ten, který se spustil.",
        routines="Vyřčené jméno spustí skript Home Assistant.",
        sentences="Jedna věta na známý záměr. Pak to zkuste.",
        policies="Tři dráhy. Vaše domácí pravidlo vyhraje první. Zkuste větu níže.",
        lab="Napište větu, pak Analyzovat nebo Enter.",
    ),
    "sk": guides(
        empty="Žiadne modely z tohto endpointu. Zadajte id.",
        fail="Modely sa nepodarilo vypísať. Zadajte id.",
        loading="Načítavajú sa modely…",
        thinking="Vypnuté použije príznak no-thinking poskytovateľa (Lemonade/llama.cpp: chat_template_kwargs, rad o OpenAI: reasoning_effort none, Anthropic: vynechať thinking, Google: thinking_budget 0).",
        convos="Povedzte niečo cez Assist. Objaví sa tu.",
        evaluator="Napíšte to ako doma. Orámovaný krok je ten, ktorý sa spustil.",
        routines="Vyslovené meno spustí skript Home Assistant.",
        sentences="Jedna veta na známy zámer. Potom to skúste.",
        policies="Tri dráhy. Vaše domáce pravidlo vyhrá prvé. Skúste vetu nižšie.",
        lab="Napíšte vetu, potom Analyzovať alebo Enter.",
    ),
    "pl": guides(
        empty="Brak modeli z tego endpointu. Wpisz id.",
        fail="Nie udało się pobrać listy modeli. Wpisz id.",
        loading="Wczytywanie modeli…",
        thinking="Wyłączone używa flagi no-thinking dostawcy (Lemonade/llama.cpp: chat_template_kwargs, seria o OpenAI: reasoning_effort none, Anthropic: pomiń thinking, Google: thinking_budget 0).",
        convos="Powiedz coś przez Assist. Pojawi się tutaj.",
        evaluator="Wpisz jak w domu. Obramowany krok to ten, który zadziałał.",
        routines="Wypowiedziana nazwa uruchamia skrypt Home Assistant.",
        sentences="Jedno zdanie na znany zamiar. Potem wypróbuj.",
        policies="Trzy tory. Twoja reguła domu wygrywa pierwsza. Wypróbuj zdanie poniżej.",
        lab="Wpisz zdanie, potem Analizuj lub Enter.",
    ),
    "hu": guides(
        empty="Nincs modell erről az endpointról. Írj be egy id-t.",
        fail="A modelleket nem sikerült listázni. Írj be egy id-t.",
        loading="Modellek betöltése…",
        thinking="Ki a szolgáltató no-thinking jelzőjét használja (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-sorozat: reasoning_effort none, Anthropic: thinking kihagyása, Google: thinking_budget 0).",
        convos="Mondj valamit Assisten keresztül. Itt megjelenik.",
        evaluator="Írd be, ahogy otthon. A keretezett lépés az, amelyik elsült.",
        routines="Egy kimondott név Home Assistant scriptet indít.",
        sentences="Egy mondat egy ismert szándékra. Aztán próbáld ki.",
        policies="Három sáv. A házi szabályod nyer először. Próbálj egy mondatot lent.",
        lab="Írj be egy mondatot, majd Elemzés vagy Enter.",
    ),
    "hr": guides(
        empty="Nema modela s ovog endpointa. Upiši id.",
        fail="Nije uspjelo dohvatiti modele. Upiši id.",
        loading="Učitavanje modela…",
        thinking="Isključeno koristi no-thinking zastavicu pružatelja (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serija: reasoning_effort none, Anthropic: izostavi thinking, Google: thinking_budget 0).",
        convos="Reci nešto preko Assist. Pojavi se ovdje.",
        evaluator="Upiši kao kod kuće. Uokvireni korak je onaj koji se okidao.",
        routines="Izgovoreno ime pokreće Home Assistant skriptu.",
        sentences="Jedna rečenica na poznatu namjeru. Zatim isprobaj.",
        policies="Tri trake. Tvoje kućno pravilo pobjeđuje prvo. Isprobaj rečenicu ispod.",
        lab="Upiši rečenicu, zatim Analiziraj ili Enter.",
    ),
    "sl": guides(
        empty="Ni modelov s tega endpointa. Vnesi id.",
        fail="Modelov ni bilo mogoče našteti. Vnesi id.",
        loading="Nalaganje modelov…",
        thinking="Izklopljeno uporabi zastavico no-thinking ponudnika (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serija: reasoning_effort none, Anthropic: izpusti thinking, Google: thinking_budget 0).",
        convos="Reci kaj prek Assist. Pokaže se tukaj.",
        evaluator="Vpiši kot doma. Uokvirjeni korak je tisti, ki se je sprožil.",
        routines="Izgovorjeno ime zažene skript Home Assistant.",
        sentences="En stavek na znan namen. Nato poskusi.",
        policies="Tri proge. Tvoje hišno pravilo zmaga prvo. Poskusi stavek spodaj.",
        lab="Vpiši stavek, nato Analiziraj ali Enter.",
    ),
    "bg": guides(
        empty="Няма модели от този endpoint. Въведи id.",
        fail="Моделите не можаха да се изброят. Въведи id.",
        loading="Зареждане на модели…",
        thinking="Изкл. ползва флага no-thinking на доставчика (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-серия: reasoning_effort none, Anthropic: пропусни thinking, Google: thinking_budget 0).",
        convos="Кажи нещо през Assist. Появява се тук.",
        evaluator="Пиши както вкъщи. Рамкираната стъпка е тази, която се задейства.",
        routines="Изречено име стартира скрипт на Home Assistant.",
        sentences="Едно изречение към познато намерение. После го пробвай.",
        policies="Три ленти. Твоето домашно правило печели първо. Пробвай изречение отдолу.",
        lab="Въведи изречение, после Анализирай или Enter.",
    ),
    "sr": guides(
        empty="Нема модела са овог endpoint-а. Унеси id.",
        fail="Модели нису могли да се излистају. Унеси id.",
        loading="Учитавање модела…",
        thinking="Искључено користи no-thinking заставицу добављача (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-серија: reasoning_effort none, Anthropic: изостави thinking, Google: thinking_budget 0).",
        convos="Реци нешто преко Assist. Појави се овде.",
        evaluator="Упиши као код куће. Уоквирени корак је онај који се окинуо.",
        routines="Изговорено име покреће Home Assistant скрипту.",
        sentences="Једна реченица на познату намеру. Затим пробај.",
        policies="Три траке. Твоје кућно правило побеђује прво. Пробај реченицу испод.",
        lab="Упиши реченицу, затим Анализирај или Enter.",
    ),
    "sr-Latn": guides(
        empty="Nema modela sa ovog endpoint-a. Unesi id.",
        fail="Modeli nisu mogli da se izlistaju. Unesi id.",
        loading="Učitavanje modela…",
        thinking="Isključeno koristi no-thinking zastavicu dobavljača (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serija: reasoning_effort none, Anthropic: izostavi thinking, Google: thinking_budget 0).",
        convos="Reci nešto preko Assist. Pojavi se ovde.",
        evaluator="Upiši kao kod kuće. Uokvireni korak je onaj koji se okinuo.",
        routines="Izgovoreno ime pokreće Home Assistant skriptu.",
        sentences="Jedna rečenica na poznatu nameru. Zatim probaj.",
        policies="Tri trake. Tvoje kućno pravilo pobeđuje prvo. Probaj rečenicu ispod.",
        lab="Upiši rečenicu, zatim Analiziraj ili Enter.",
    ),
    "uk": guides(
        empty="Немає моделей з цього endpoint. Введи id.",
        fail="Не вдалося отримати список моделей. Введи id.",
        loading="Завантаження моделей…",
        thinking="Вимкнено використовує прапорець no-thinking постачальника (Lemonade/llama.cpp: chat_template_kwargs, серія o OpenAI: reasoning_effort none, Anthropic: пропустити thinking, Google: thinking_budget 0).",
        convos="Скажи щось через Assist. Воно з’явиться тут.",
        evaluator="Пиши як удома. Обрамлений крок — той, що спрацював.",
        routines="Промовлене ім’я запускає скрипт Home Assistant.",
        sentences="Одне речення на відомий намір. Потім спробуй.",
        policies="Три смуги. Твоє домашнє правило виграє першим. Спробуй речення нижче.",
        lab="Введи речення, потім Аналізувати або Enter.",
    ),
}
