"""Lab / mapping / backup chrome for Slavic and Hungarian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_table import parse_rows

CODES = ["cs", "sk", "pl", "hu", "hr", "sl", "bg", "sr", "sr-Latn", "uk"]

TABLE = """
parseHint	Labor je cesta Assist pro zvolený jazyk. Rozhodnutí a intentty tady provádí Klar. Spouštěče vět běží jen když je Klar nedostupný.	Labor je cesta Assist pre zvolený jazyk. Rozhodnutie a intentty tu vykonáva Klar. Spúšťače viet bežia len keď je Klar nedostupný.	Lab to ścieżka Assist dla wybranego języka. Decyzję i intenty tutaj wykonuje Klar. Wyzwalacze zdań działają tylko, gdy Klar jest nieosiągalny.	A labor a kiválasztott nyelv Assist-útja. A döntést és az intenteket itt a Klar futtatja. A mondatindítók csak akkor futnak, ha a Klar nem elérhető.	Lab je Assist-put za odabrani jezik. Odluku i intentte ovdje izvodi Klar. Okidači rečenica rade samo ako Klar nije dostupan.	Lab je Assist-pot za izbrani jezik. Odločitev in intente tukaj izvede Klar. Sprožilci stavkov tečejo le, če Klar ni dosegljiv.	Лабът е пътят на Assist за избрания език. Решението и намеренията тук изпълнява Klar. Тригерите за изречения работят само ако Klar е недостъпен.	Лаб је пут Assist за изабрани језик. Одлуку и намере овде извршава Klar. Окидачи реченица раде само ако Klar није доступан.	Lab je put Assist za izabrani jezik. Odluku i namere ovde izvršava Klar. Okidači rečenica rade samo ako Klar nije dostupan.	Лаб — шлях Assist для вибраної мови. Рішення і наміри тут виконує Klar. Тригери речень працюють лише коли Klar недоступний.
triggerFirst	Klar-parse, pak tato cesta. Assist nespustí jiný intent, spouštěč vět ani zálohu počasí.	Klar-parse, potom táto cesta. Assist nespustí iný intent, spúšťač viet ani zálohu počasia.	Parsowanie Klar, potem ta ścieżka. Assist nie uruchamia innego intentu, wyzwalacza zdań ani zapasu pogody.	Klar-elemzés, aztán ez az út. Az Assist nem futtat más intentet, mondatindítót vagy időjárás-tartalékot.	Klar-parse, zatim taj put. Assist ne pokreće drugi intent, okidač rečenice ni rezervu vremena.	Klar-parse, nato ta pot. Assist ne zažene drugega intenta, sprožilca stavkov ali vremenskega rezervnega koraka.	Разбор Klar, после този път. Assist не пуска друг intent, тригер за изречение или резерва за времето.	Рашчлањивање Klar, затим тај пут. Assist не покреће други intent, окидач реченице или резерву за време.	Raščlanjivanje Klar, zatim taj put. Assist ne pokreće drugi intent, okidač rečenice ili rezervu za vreme.	Розбір Klar, потім цей шлях. Assist не запускає інший намір, тригер речення чи запас погоди.
labPipeline	Pipeline	Pipeline	Potok	Csővezeték	Cjevovod	Cevovod	Конвейер	Цевовод	Cevovod	Конвеєр
labChipContextOnly	jen kontext	len kontext	tylko kontekst	csak kontextus	samo kontekst	samo kontekst	само контекст	само контекст	samo kontekst	лише контекст
labChipNluRag	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG
labChipSemantic	sémantický	sémantický	semantyczny	szemantikus	semantički	semantičen	семантичен	семантички	semantički	семантичний
labChipNoConfirm	bez potvrzení	bez potvrdenia	bez potwierdzenia	megerősítés nélkül	bez potvrde	brez potrditve	без потвърждение	без потврде	bez potvrde	без підтвердження
labChipLlmRefine	LLM-zjemnění	LLM-spresnenie	doprecyzowanie LLM	LLM-finomítás	LLM-dorada	LLM-izboljšava	LLM уточнение	LLM дорада	LLM dorada	уточнення LLM
labChipCalendarLlm	kalendář-LLM	kalendár-LLM	kalendarz LLM	naptár-LLM	kalendar LLM	koledar LLM	календар-LLM	календар LLM	kalendar LLM	календар LLM
labChipQuietAck	tiché potvrzení	tiché potvrdenie	ciche potwierdzenie	rövid nyugtázás	tiha potvrda	tiha potrditev	тихо потвърждение	тиха потврда	tiha potvrda	тихе підтвердження
labChipLlmTools	nástroje LLM	nástroje LLM	narzędzia LLM	LLM-eszközök	LLM alati	orodja LLM	инструменти LLM	алати LLM	alati LLM	інструменти LLM
labChipLlmChat	chat LLM	chat LLM	czat LLM	LLM-csevegés	chat LLM	klepet LLM	чат LLM	ћеркање LLM	ćaskanje LLM	чат LLM
labChipConfirmRisky	potvrdit riziko	potvrdiť riziko	potwierdź ryzyko	kockázat megerősítése	potvrdi rizik	potrdi tveganje	потвърди риск	потврди ризик	potvrdi rizik	підтвердити ризик
labDecisionExecute	Klar vykoná	Klar vykoná	Klar wykonuje	Klar végrehajt	Klar izvršava	Klar izvede	Klar изпълнява	Klar извршава	Klar izvršava	Klar виконує
labDecisionBriefing	briefing	briefing	briefing	tájékoztató	briefing	briefing	брифинг	брифинг	brifing	брифінг
labParse	Klar-parse	Klar-parse	Parsowanie Klar	Klar-elemzés	Klar-parse	Klar-parse	Разбор Klar	Рашчлањивање Klar	Raščlanjivanje Klar	Розбір Klar
reasonMissingArea	chybí místnost	chýba miestnosť	brak pokoju	hiányzó szoba	nema sobe	manjka prostor	липсва стая	нема собе	nema sobe	немає кімнати
reasonWeakName	slabý název	slabý názov	słaba nazwa	gyenge név	slabo ime	šibko ime	слабо име	слабо име	slabo ime	слабка назва
reasonReady	připraveno	pripravené	gotowe	kész	spremno	pripravljeno	готово	спремно	spremno	готово
reasonMatch	shoda	zhoda	trafienie	találat	pogodak	zadetek	съвпадение	погодак	pogodak	збіг
sentencesEmpty	Jedna věta na známý intent. Ne jedna fráze na každé světlo.	Jedna veta na známy intent. Nie jedna fráza na každé svetlo.	Jedno zdanie na znany intent. Nie jedna fraza na każdą lampę.	Egy mondat egy ismert intentre. Nem egy kifejezés lámpánként.	Jedna rečenica na poznati intent. Ne jedna fraza po svjetlu.	En stavek na znan intent. Ne ena fraza na vsako luč.	Едно изречение към известен intent. Не по фраза за всяка лампа.	Једна реченица на познати intent. Не једна фраза по светлу.	Jedna rečenica na poznati intent. Ne jedna fraza po svetlu.	Одне речення на відомий намір. Не одна фраза на кожне світло.
policiesEmpty	První odpovídající pravidlo vyhraje. Vyberte zařízení, místnost nebo patro — nepište id.	Prvé zodpovedajúce pravidlo vyhrá. Vyberte zariadenie, miestnosť alebo poschodie — nepíšte id.	Pierwsza pasująca reguła wygrywa. Wybierz urządzenie, pokój lub piętro — nie wpisuj id.	Az első illeszkedő szabály nyer. Válassz eszközt, szobát vagy emeletet — ne írj azonosítót.	Prvo odgovarajuće pravilo pobjeđuje. Odaberite uređaj, sobu ili kat — ne tipkajte id.	Prvo ujemajoče pravilo zmaga. Izberite napravo, prostor ali nadstropje — ne tipkajte id.	Първото съвпадащо правило печели. Изберете устройство, стая или етаж — не пишете id.	Прво одговарајуће правило побеђује. Изаберите уређај, собу или спрат — не куцајте id.	Prvo odgovarajuće pravilo pobeđuje. Izaberite uređaj, sobu ili sprat — ne kucajte id.	Перше відповідне правило перемагає. Оберіть пристрій, кімнату або поверх — не вводьте id.
setupAgainWhere	Opakovat setup je v Nastavení.	Zopakovať setup je v Nastaveniach.	Ponowienie setupu jest w Ustawieniach.	A setup újra a Beállításokban van.	Ponovi setup je u Postavkama.	Ponovi setup je v Nastavitvah.	Повторният setup е в Настройки.	Понови setup је у Подешавањима.	Ponovi setup je u Podešavanjima.	Повтор setup у Налаштуваннях.
whyThisBand	Proč tento pás?	Prečo tento pás?	Dlaczego ten pas?	Miért ez a sáv?	Zašto ovaj pojas?	Zakaj ta pas?	Защо тази лента?	Зашто ова трака?	Zašto ova traka?	Чому ця смуга?
rememberAsPhrase	Zapamatovat jako frázi	Zapamätať ako frázu	Zapamiętaj jako frazę	Jegyezd meg kifejezésként	Zapamti kao frazu	Zapomni kot frazo	Запомни като фраза	Запамти као фразу	Zapamti kao frazu	Запам'ятати як фразу
evidence	Důkaz	Dôkaz	Dowód	Bizonyíték	Dokaz	Dokaz	Доказателство	Доказ	Dokaz	Доказ
names	Názvy	Názvy	Nazwy	Nevek	Imena	Imena	Имена	Имена	Imena	Імена
settingsBackup	Záloha nastavení	Záloha nastavení	Kopia ustawień	Beállítások mentése	Sigurnosna kopija postavki	Varnostna kopija nastavitev	Резервно копие на настройки	Резервна копија подешавања	Rezervna kopija podešavanja	Резервна копія налаштувань
settingsBackupHint	Overlay, přiřazení, pravidla a endpoint LLM. Konverzace a graf domu zůstanou na tomto enginu.	Overlay, priradenia, pravidlá a endpoint LLM. Konverzácie a graf domu ostanú na tomto engine.	Nakładka, przypisania, reguły i endpoint LLM. Rozmowy i graf domu zostają na tym silniku.	Overlay, hozzárendelések, szabályok és az LLM végpont. A beszélgetések és a házgráf ezen a motoron maradnak.	Overlay, dodjele, pravila i LLM krajnja točka. Razgovori i graf kuće ostaju na ovom motoru.	Prekrivni sloj, dodelitve, pravila in končna točka LLM. Pogovori in graf hiše ostanejo na tem pogonu.	Наслойка, присвоявания, правила и крайна точка на LLM. Разговорите и графът на къщата остават на този двигател.	Преклоп, доделе, правила и крајња тачка LLM. Разговори и граф куће остају на овом мотору.	Preklop, dodele, pravila i krajnja tačka LLM. Razgovori i graf kuće ostaju na ovom motoru.	Накладка, призначення, правила та кінцева точка LLM. Розмови і граф будинку лишаються на цьому рушії.
settingsBackupDownload	Stáhnout nastavení	Stiahnuť nastavenia	Pobierz ustawienia	Beállítások letöltése	Preuzmi postavke	Prenesi nastavitve	Изтегли настройки	Преузми подешавања	Preuzmi podešavanja	Завантажити налаштування
settingsBackupIncludeKey	Zahrnout API klíč	Zahrnúť API kľúč	Dołącz klucz API	API-kulcs csatolása	Uključi API ključ	Vključi API ključ	Включи API ключ	Укључи API кључ	Uključi API ključ	Включити ключ API
settingsBackupIncludeKeyHint	Ve výchozím stavu vypnuto. Zapnuto: archiv obsahuje uložený LLM klíč.	V predvolenom stave vypnuté. Zapnuté: archív obsahuje uložený LLM kľúč.	Domyślnie wyłączone. Włączone: archiwum zawiera zapisany klucz LLM.	Alapból ki. Be: az archívum tartalmazza a tárolt LLM-kulcsot.	Zadano isključeno. Uključeno: arhiva sadrži pohranjeni LLM ključ.	Privzeto izklopljeno. Vklopljeno: arhiv vsebuje shranjeni ključ LLM.	По подразбиране изключено. Включено: архивът съдържа съхранения ключ LLM.	Подразумевано искључено. Укључено: архива садржи сачувани LLM кључ.	Podrazumevano isključeno. Uključeno: arhiva sadrži sačuvani LLM ključ.	Типово вимкнено. Увімкнено: архів містить збережений ключ LLM.
settingsBackupIncludeKeyConfirm	Archiv bude obsahovat API klíč LLM. Stáhnout přesto?	Archív bude obsahovať API kľúč LLM. Stiahnuť aj tak?	Archiwum będzie zawierać klucz API LLM. Pobrać mimo to?	Az archívum tartalmazni fogja az LLM API-kulcsát. Letöltöd mégis?	Arhiva će sadržavati API ključ LLM. Svejedno preuzeti?	Arhiv bo vseboval API ključ LLM. Vseeno prenesi?	Архивът ще съдържа API ключа на LLM. Изтегляне въпреки това?	Архива ће садржати API кључ LLM. Ипак преузети?	Arhiva će sadržati API ključ LLM. Ipak preuzeti?	Архів міститиме ключ API LLM. Завантажити все одно?
settingsBackupRestore	Obnovit nastavení	Obnoviť nastavenia	Przywróć ustawienia	Beállítások visszaállítása	Vrati postavke	Obnovi nastavitve	Възстанови настройки	Врати подешавања	Vrati podešavanja	Відновити налаштування
settingsBackupRestoreConfirm	Tím se přepíší všechna nastavení Klar na tomto enginu.	Tým sa prepíšu všetky nastavenia Klar na tomto engine.	To nadpisuje wszystkie ustawienia Klar na tym silniku.	Ez felülírja a Klar összes beállítását ezen a motoron.	Ovo prepisuje sve Klar postavke na ovom motoru.	To prepiše vse nastavitve Klar na tem pogonu.	Това презаписва всички настройки на Klar на този двигател.	Ово преписује сва Klar подешавања на овом мотору.	Ovo prepisuje sva Klar podešavanja na ovom motoru.	Це перезаписує всі налаштування Klar на цьому рушії.
settingsBackupRestoreOk	Nastavení obnovena.	Nastavenia obnovené.	Ustawienia przywrócone.	Beállítások visszaállítva.	Postavke vraćene.	Nastavitve obnovljene.	Настройките са възстановени.	Подешавања враћена.	Podešavanja vraćena.	Налаштування відновлено.
settingsBackupRestoreFail	Nastavení se nepodařilo obnovit.	Nastavenia sa nepodarilo obnoviť.	Nie udało się przywrócić ustawień.	A beállításokat nem sikerült visszaállítani.	Vraćanje postavki nije uspjelo.	Nastavitev ni bilo mogoče obnoviti.	Настройките не бяха възстановени.	Враћање подешавања није успело.	Vraćanje podešavanja nije uspelo.	Не вдалося відновити налаштування.
settingsBackupPickFile	Vybrat archiv	Vybrať archív	Wybierz archiwum	Archívum kiválasztása	Odaberi arhivu	Izberi arhiv	Избери архив	Изабери архиву	Izaberi arhivu	Обрати архів
speechRefined	LLM-zjemnění	LLM-spresnenie	doprecyzowanie LLM	LLM-finomítás	LLM-dorada	LLM-izboljšava	LLM уточнение	LLM дорада	LLM dorada	уточнення LLM
speechChat	chat LLM	chat LLM	czat LLM	LLM-csevegés	chat LLM	klepet LLM	чат LLM	ћеркање LLM	ćaskanje LLM	чат LLM
refineRejected	Zjemnění ponechalo odpověď NLU.	Spresnenie ponechalo odpoveď NLU.	Doprecyzowanie zachowało odpowiedź NLU.	A finomítás megtartotta az NLU választ.	Dorada je zadržala NLU odgovor.	Izboljšava je obdržala odgovor NLU.	Уточнението запази отговора на NLU.	Дорада је задржала NLU одговор.	Dorada je zadržala NLU odgovor.	Уточнення зберегло відповідь NLU.
"""

PACKS = parse_rows(CODES, TABLE)
