"""Lab / mapping / backup chrome for West European Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_table import parse_rows

CODES = ["fr", "nl", "es", "it", "pt", "ca", "ro", "pt-BR", "gl"]

TABLE = """
parseHint	Le labo est le chemin Assist pour la langue choisie. La décision et les intentions ici sont ce que Klar exécute. Les déclencheurs de phrases ne s'exécutent que si Klar est injoignable.	Het lab is het Assist-pad voor de gekozen taal. Beslissing en intenties hier voert Klar uit. Zintriggers lopen alleen als Klar onbereikbaar is.	El laboratorio es la ruta de Assist para el idioma elegido. La decisión y las intenciones de aquí son las que ejecuta Klar. Los disparadores de frases solo se ejecutan si Klar no está disponible.	Il laboratorio è il percorso Assist per la lingua selezionata. Decisione e intenti qui sono ciò che Klar esegue. Gli attivatori di frase partono solo se Klar non è raggiungibile.	O laboratório é o caminho Assist para o idioma selecionado. A decisão e as intenções daqui são o que o Klar executa. Os acionadores de frases só correm se o Klar estiver inacessível.	El laboratori és el camí d'Assist per a la llengua triada. La decisió i les intencions d'aquí són el que executa Klar. Els activadors de frases només s'executen si Klar no és accessible.	Laboratorul este calea Assist pentru limba selectată. Decizia și intențiile de aici sunt ce execută Klar. Declanșatoarele de fraze rulează doar dacă Klar este inaccesibil.	O laboratório é o caminho do Assist para o idioma selecionado. A decisão e as intenções daqui são o que o Klar executa. Os acionadores de frases só rodam se o Klar estiver inacessível.	O laboratorio é a ruta de Assist para a lingua escollida. A decisión e as intencións de aquí son o que executa Klar. Os disparadores de frases só se executan se Klar non está accesible.
triggerFirst	Analyse Klar, puis ce chemin. Assist n'exécute pas une autre intention, un déclencheur de phrase ni un repli météo.	Klar-parse, daarna dit pad. Assist start geen andere intentie, geen zintrigger en geen weer-fallback.	Análisis de Klar, luego esa ruta. Assist no ejecuta otra intención, un disparador de frases ni un respaldo meteorológico.	Parse Klar, poi quel percorso. Assist non esegue un intento diverso, un attivatore di frase o un fallback meteo.	Análise Klar, depois esse caminho. O Assist não executa outra intenção, um acionador de frases nem um recurso de meteorologia.	Anàlisi Klar, després aquest camí. Assist no executa una altra intenció, un activador de frases ni un recanvi del temps.	Parsare Klar, apoi acea cale. Assist nu execută o altă intenție, un declanșator de frază sau un fallback meteo.	Análise Klar, depois esse caminho. O Assist não executa outra intenção, um acionador de frases nem um fallback de clima.	Análise Klar, logo esa ruta. Assist non executa outra intención, un disparador de frases nin un recurso meteorolóxico.
labPipeline	Pipeline	Pijplijn	Canal	Pipeline	Canal	Canal	Conduct	Pipeline	Canle
labChipContextOnly	contexte seul	alleen context	solo contexto	solo contesto	só contexto	només context	doar context	só contexto	só contexto
labChipNluRag	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG	NLU-RAG
labChipSemantic	sémantique	semantisch	semántico	semantico	semântico	semàntic	semantic	semântico	semántico
labChipNoConfirm	sans confirmation	zonder bevestiging	sin confirmar	senza conferma	sem confirmação	sense confirmació	fără confirmare	sem confirmação	sen confirmación
labChipLlmRefine	raffinage LLM	LLM-verfijning	refino LLM	raffinamento LLM	refino LLM	refinament LLM	rafinare LLM	refino LLM	refino LLM
labChipCalendarLlm	agenda LLM	agenda-LLM	calendario LLM	calendario LLM	calendário LLM	calendari LLM	calendar LLM	calendário LLM	calendario LLM
labChipQuietAck	accusé court	stille bevestiging	acuse breve	conferma breve	confirmação breve	confirmació breu	confirmare scurtă	confirmação breve	confirmación breve
labChipLlmTools	outils LLM	LLM-hulpmiddelen	herramientas LLM	strumenti LLM	ferramentas LLM	eines LLM	unelte LLM	ferramentas LLM	ferramentas LLM
labChipLlmChat	chat LLM	LLM-chat	chat LLM	chat LLM	chat LLM	xat LLM	chat LLM	chat LLM	chat LLM
labChipConfirmRisky	confirmer le risque	risico bevestigen	confirmar riesgo	conferma rischio	confirmar risco	confirmar risc	confirmă riscul	confirmar risco	confirmar risco
labDecisionExecute	Klar exécute	Klar uitvoeren	Klar ejecuta	Klar esegue	Klar executa	Klar executa	Klar execută	Klar executa	Klar executa
labDecisionBriefing	briefing	briefing	informe	briefing	briefing	briefing	briefing	briefing	informe
labParse	Analyse Klar	Klar-parse	Análisis Klar	Parse Klar	Análise Klar	Anàlisi Klar	Parsare Klar	Análise Klar	Análise Klar
reasonMissingArea	sans pièce	geen ruimte	sin estancia	senza stanza	sem divisão	sense estança	fără cameră	sem cômodo	sen estancia
reasonWeakName	nom faible	zwakke naam	nombre débil	nome debole	nome fraco	nom feble	nume slab	nome fraco	nome feble
reasonReady	prêt	gereed	listo	pronto	pronto	llest	gata	pronto	listo
reasonMatch	correspondance	treffer	coincidencia	corrispondenza	correspondência	coincidència	potrivire	correspondência	coincidencia
sentencesEmpty	Une phrase vers une intention connue. Pas une phrase par lumière.	Eén zin op een bekende intentie. Niet één zin per lamp.	Una frase hacia una intención conocida. No una frase por luz.	Una frase su un intento noto. Non una frase per luce.	Uma frase para uma intenção conhecida. Não uma frase por luz.	Una frase cap a una intenció coneguda. No una frase per llum.	O frază către o intenție cunoscută. Nu o frază per bec.	Uma frase para uma intenção conhecida. Não uma frase por lâmpada.	Unha frase cara a unha intención coñecida. Non unha frase por luz.
policiesEmpty	La première règle correspondante l'emporte. Choisissez un appareil, une pièce ou un étage — n'écrivez pas d'identifiants.	Eerste passende regel wint. Kies een apparaat, ruimte of verdieping — typ geen id's.	Gana la primera regla coincidente. Elige un dispositivo, estancia o planta — no escribas identificadores.	Vince la prima regola corrispondente. Scegli un dispositivo, una stanza o un piano — non digitare id.	Vence a primeira regra correspondente. Escolha um dispositivo, divisão ou piso — não escreva identificadores.	Guanya la primera regla coincident. Trieu un dispositiu, una estança o un pis — no escriviu identificadors.	Prima regulă potrivită câștigă. Alegeți un dispozitiv, o cameră sau un etaj — nu tastați id-uri.	Vence a primeira regra correspondente. Escolha um dispositivo, cômodo ou andar — não digite ids.	Gaña a primeira regra coincidente. Escolle un dispositivo, estancia ou andar — non escribas identificadores.
setupAgainWhere	Rejouer le setup est dans Paramètres.	Setup opnieuw staat onder Instellingen.	Rehacer el setup está en Ajustes.	Rifare il setup è in Impostazioni.	Repetir o setup está em Definições.	Tornar a fer el setup és a Configuració.	Reluarea setup-ului e la Setări.	Refazer o setup está em Configurações.	Repetir o setup está en Configuración.
whyThisBand	Pourquoi cette bande ?	Waarom deze band?	¿Por qué esta banda?	Perché questa banda?	Porque esta banda?	Per què aquesta banda?	De ce această bandă?	Por que esta banda?	Por que esta banda?
rememberAsPhrase	Retenir comme phrase	Onthouden als zin	Recordar como frase	Ricorda come frase	Lembrar como frase	Recorda com a frase	Reține ca frază	Lembrar como frase	Lembrar como frase
evidence	Preuve	Bewijs	Evidencia	Evidenza	Evidência	Evidència	Dovezi	Evidência	Evidencia
names	Noms	Namen	Nombres	Nomi	Nomes	Noms	Nume	Nomes	Nomes
settingsBackup	Sauvegarde des paramètres	Instellingen-back-up	Copia de ajustes	Backup impostazioni	Cópia das definições	Còpia de la configuració	Copie de rezervă setări	Backup das configurações	Copia da configuración
settingsBackupHint	Overlay, affectations, règles et le point de terminaison LLM. Les conversations et le graphe de la maison restent sur ce moteur.	Overlay, toewijzingen, regels en het LLM-eindpunt. Gesprekken en de huisgrafiek blijven op deze engine.	Overlay, asignaciones, reglas y el endpoint del LLM. Las conversaciones y el grafo de la casa se quedan en este motor.	Overlay, assegnazioni, regole e l'endpoint LLM. Conversazioni e grafo della casa restano su questo motore.	Overlay, atribuições, regras e o endpoint do LLM. Conversas e o grafo da casa ficam neste motor.	Overlay, assignacions, regles i l'extrem LLM. Les converses i el graf de la casa es queden en aquest motor.	Overlay, atribuiri, reguli și endpoint-ul LLM. Conversațiile și graful casei rămân pe acest motor.	Overlay, atribuições, regras e o endpoint do LLM. Conversas e o grafo da casa ficam neste mecanismo.	Overlay, asignacións, regras e o endpoint do LLM. As conversas e o grafo da casa quedan neste motor.
settingsBackupDownload	Télécharger les paramètres	Instellingen downloaden	Descargar ajustes	Scarica impostazioni	Transferir definições	Baixa la configuració	Descarcă setările	Baixar configurações	Descargar a configuración
settingsBackupIncludeKey	Inclure la clé API	API-sleutel opnemen	Incluir clave API	Includi chiave API	Incluir chave API	Incloure la clau API	Include cheia API	Incluir chave de API	Incluír a chave API
settingsBackupIncludeKeyHint	Désactivé par défaut. Activé : l'archive contient la clé LLM stockée.	Standaard uit. Aan: het archief bevat de opgeslagen LLM-sleutel.	Desactivado por defecto. Activado: el archivo contiene la clave LLM guardada.	Disattivato di default. Attivo: l'archivio contiene la chiave LLM salvata.	Desligado por predefinição. Ligado: o arquivo contém a chave LLM guardada.	Desactivat per defecte. Actiu: l'arxiu conté la clau LLM desada.	Dezactivat implicit. Pornit: arhiva conține cheia LLM stocată.	Desligado por padrão. Ligado: o arquivo contém a chave LLM armazenada.	Desactivado por defecto. Activado: o arquivo contén a chave LLM gardada.
settingsBackupIncludeKeyConfirm	L'archive contiendra la clé API du LLM. Télécharger quand même ?	Het archief bevat de LLM-API-sleutel. Toch downloaden?	El archivo contendrá la clave API del LLM. ¿Descargar de todos modos?	L'archivio conterrà la chiave API dell'LLM. Scaricare comunque?	O arquivo conterá a chave API do LLM. Transferir mesmo assim?	L'arxiu contindrà la clau API de l'LLM. Voleu baixar-lo igualment?	Arhiva va conține cheia API a LLM. Descărcați oricum?	O arquivo conterá a chave de API do LLM. Baixar mesmo assim?	O arquivo conterá a chave API do LLM. Descargar de todos os xeitos?
settingsBackupRestore	Restaurer les paramètres	Instellingen herstellen	Restaurar ajustes	Ripristina impostazioni	Restaurar definições	Restaura la configuració	Restaurează setările	Restaurar configurações	Restaurar a configuración
settingsBackupRestoreConfirm	Cela écrase tous les réglages Klar sur ce moteur.	Dit overschrijft alle Klar-instellingen op deze engine.	Esto sobrescribe todos los ajustes de Klar en este motor.	Questo sovrascrive tutte le impostazioni Klar su questo motore.	Isto substitui todas as definições Klar neste motor.	Això sobreescriu tots els paràmetres de Klar en aquest motor.	Aceasta suprascrie toate setările Klar de pe acest motor.	Isso substitui todas as configurações do Klar neste mecanismo.	Isto sobrescribe todos os axustes de Klar neste motor.
settingsBackupRestoreOk	Paramètres restaurés.	Instellingen hersteld.	Ajustes restaurados.	Impostazioni ripristinate.	Definições restauradas.	Configuració restaurada.	Setări restaurate.	Configurações restauradas.	Configuración restaurada.
settingsBackupRestoreFail	Impossible de restaurer les paramètres.	Instellingen herstellen mislukt.	No se pudieron restaurar los ajustes.	Impossibile ripristinare le impostazioni.	Não foi possível restaurar as definições.	No s'ha pogut restaurar la configuració.	Nu s-au putut restaura setările.	Não foi possível restaurar as configurações.	Non se puido restaurar a configuración.
settingsBackupPickFile	Choisir une archive	Archief kiezen	Elegir archivo	Scegli archivio	Escolher arquivo	Tria un arxiu	Alege arhiva	Escolher arquivo	Escoller arquivo
speechRefined	raffinage LLM	LLM-verfijning	refino LLM	raffinamento LLM	refino LLM	refinament LLM	rafinare LLM	refino LLM	refino LLM
speechChat	chat LLM	LLM-chat	chat LLM	chat LLM	chat LLM	xat LLM	chat LLM	chat LLM	chat LLM
refineRejected	Le raffinage a gardé la réponse NLU.	De verfijning hield het NLU-antwoord.	El refino conservó la respuesta NLU.	Il raffinamento ha tenuto la risposta NLU.	O refino manteve a resposta NLU.	El refinament ha conservat la resposta NLU.	Rafinarea a păstrat răspunsul NLU.	O refino manteve a resposta NLU.	O refino conservou a resposta NLU.
"""

PACKS = parse_rows(CODES, TABLE)
