"""Rules/house guides and leftover Settings chrome for MENA Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_pages import pages
from lang_packs.web_ui_pages_mena_east import PACKS as EAST

PACKS: dict[str, dict[str, str]] = {
    "ar": pages(
        guideRoutinesSay="ماذا تقول؟",
        guideRoutinesSayHint="تصبح على خير، سأخرج، سهرة فيلم.",
        guideRoutinesScript="أي سكربت؟",
        guideRoutinesScriptHint="اختر script.xxx. لا تكتب entity id.",
        guideSentencesPhrase="أي جملة؟",
        guideSentencesPhraseHint="كما تقولونها فعلاً.",
        guideSentencesIntent="ماذا يجب أن يفعل Klar؟",
        guideSentencesIntentHint="اختر نية، جهازاً فقط إن لزم.",
        guideSentencesTest="جرّب",
        guideSentencesTestHint="معاينة قبل أن تبقى الجملة.",
        guidePoliciesMatch="أي أوامر",
        guidePoliciesMatchHint="مطابقات المحرك. اتركها شغّالة إلا إن عرفت السبب.",
        guidePoliciesLang="أمان اللغة",
        guidePoliciesLangHint="بذور الحزمة والمعجم. فقط إن كانت كلمة خاطئة.",
        guidePoliciesHouse="قاعدتك",
        guidePoliciesHouseHint="عندما ← ثم. اختر جهازاً أو غرفة، لا تكتب المعرّفات.",
        guidePoliciesTest="جرّب",
        guidePoliciesTestHint="اكتب جملة ثم حلّل. المسار المؤطّر هو الذي اشتغل.",
        houseGuideGraph="المس جهازاً للفحص. السحب يحرّك البطاقة فقط.",
        houseGuideDevices="ابحث، ثم المس جهازاً.",
        houseGuideMap="اقبل الاقتراح أو اختر غرفة.",
        menu="القائمة",
        ragModeShort="سياق المنزل",
        llmThinking="Thinking",
        unitSystem="الوحدات",
        unitSystemHint="درجات حرارة تُقال وتُفهم. الأضواء والمؤقتات والسطوع تبقى كما هي.",
        unitMetric="متري",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="اللغات",
        settingsNavVoice="الصوت",
        llmProvider="المزوّد",
        llmPresetCustom="متوافق مع OpenAI",
        personalityPrompt="موجّه الشخصية",
    ),
    "he": pages(
        guideRoutinesSay="מה אומרים?",
        guideRoutinesSayHint="לילה טוב, אני יוצא, ערב סרט.",
        guideRoutinesScript="איזה script?",
        guideRoutinesScriptHint="בחרו script.xxx. אל תקלידו entity id.",
        guideSentencesPhrase="איזה משפט?",
        guideSentencesPhraseHint="כפי שאומרים אותו באמת.",
        guideSentencesIntent="מה Klar צריך לעשות?",
        guideSentencesIntentHint="בחרו כוונה, מכשיר רק אם צריך.",
        guideSentencesTest="נסו",
        guideSentencesTestHint="תצוגה לפני שהמשפט נשאר.",
        guidePoliciesMatch="אילו פקודות",
        guidePoliciesMatchHint="מתאמי המנוע. השאירו דולק אלא אם אתם יודעים למה.",
        guidePoliciesLang="בטיחות שפה",
        guidePoliciesLangHint="זרעי החבילה והלקסיקון. רק אם מילה שגויה.",
        guidePoliciesHouse="הכלל שלכם",
        guidePoliciesHouseHint="כש → אז. בחרו מכשיר או חדר, אל תקלידו מזהים.",
        guidePoliciesTest="נסו",
        guidePoliciesTestHint="הקלידו משפט ואז נתח. הנתיב הממוסגר הוא שקפץ.",
        houseGuideGraph="געו במכשיר לבדיקה. גרירה רק מזיזה את הכרטיס.",
        houseGuideDevices="חפשו, אחר כך געו במכשיר.",
        houseGuideMap="קבלו את ההצעה או בחרו חדר.",
        menu="תפריט",
        ragModeShort="הקשר הבית",
        llmThinking="Thinking",
        unitSystem="יחידות",
        unitSystemHint="טמפרטורות מדוברות ומובנות. אורות, טיימרים ובהירות נשארים.",
        unitMetric="מטרי",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="שפות",
        settingsNavVoice="קול",
        llmProvider="ספק",
        llmPresetCustom="תואם OpenAI",
        personalityPrompt="הנחיית אישיות",
    ),
    "fa": pages(
        guideRoutinesSay="چه می‌گویی؟",
        guideRoutinesSayHint="شب بخیر، می‌روم، شب فیلم.",
        guideRoutinesScript="کدام script؟",
        guideRoutinesScriptHint="script.xxx را برگزین. entity id ننویس.",
        guideSentencesPhrase="کدام جمله؟",
        guideSentencesPhraseHint="همان‌طور که واقعاً می‌گویید.",
        guideSentencesIntent="Klar چه باید بکند؟",
        guideSentencesIntentHint="نیتی برگزین، دستگاه فقط اگر لازم است.",
        guideSentencesTest="بیازمای",
        guideSentencesTestHint="پیش‌نمایش پیش از ماندن جمله.",
        guidePoliciesMatch="کدام فرمان‌ها",
        guidePoliciesMatchHint="تطبيق‌گرهای موتور. روشن بگذار مگر بدانی چرا.",
        guidePoliciesLang="ایمنی زبان",
        guidePoliciesLangHint="بذر بسته و واژگان. فقط اگر واژه‌ای غلط است.",
        guidePoliciesHouse="قاعده تو",
        guidePoliciesHouseHint="وقتی ← آنگاه. دستگاه یا اتاق برگزین، شناسه ننویس.",
        guidePoliciesTest="بیازمای",
        guidePoliciesTestHint="جمله‌ای بنویس و تحلیل کن. مسیر قاب‌دار همان است که زد.",
        houseGuideGraph="برای بازرسی دستگاه را لمس کن. کشیدن فقط کارت را جابه‌جا می‌کند.",
        houseGuideDevices="بجو، سپس دستگاهی را لمس کن.",
        houseGuideMap="پیشنهاد را بپذیر یا اتاقی برگزین.",
        menu="منو",
        ragModeShort="بافت خانه",
        llmThinking="Thinking",
        unitSystem="یکاها",
        unitSystemHint="دماهای گفته و فهمیده‌شده. چراغ‌ها، زمان‌سنج‌ها و روشنایی همان می‌مانند.",
        unitMetric="متریک",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="زبان‌ها",
        settingsNavVoice="صدا",
        llmProvider="ارائه‌دهنده",
        llmPresetCustom="سازگار با OpenAI",
        personalityPrompt="پرامپت شخصیت",
    ),
    "ur": pages(
        guideRoutinesSay="تم کیا کہتے ہو؟",
        guideRoutinesSayHint="شب بخیر، میں جا رہا ہوں، فلم کی شام.",
        guideRoutinesScript="کون سا script؟",
        guideRoutinesScriptHint="script.xxx چنو۔ entity id نہ لکھو.",
        guideSentencesPhrase="کون سا جملہ؟",
        guideSentencesPhraseHint="جیسا واقعی کہتے ہو.",
        guideSentencesIntent="Klar کو کیا کرنا چاہیے؟",
        guideSentencesIntentHint="ارادہ چنو، آلہ صرف ضرورت پر.",
        guideSentencesTest="آزماؤ",
        guideSentencesTestHint="جملہ رکھنے سے پہلے جھلک.",
        guidePoliciesMatch="کون سے حکم",
        guidePoliciesMatchHint="Engine کے matcher۔ آن رہنے دو جب تک وجہ معلوم نہ ہو.",
        guidePoliciesLang="زبان کی حفاظت",
        guidePoliciesLangHint="پیک کے seed اور لغت۔ صرف اگر کوئی لفظ غلط ہو.",
        guidePoliciesHouse="تمہارا قاعدہ",
        guidePoliciesHouseHint="جب ← تب۔ آلہ یا کمرہ چنو، id نہ لکھو.",
        guidePoliciesTest="آزماؤ",
        guidePoliciesTestHint="جملہ لکھو اور تجزیہ کرو۔ فریم والا راستہ چلا.",
        houseGuideGraph="جانچ کے لیے آلہ چھؤ۔ گھسیٹنا صرف کارڈ ہلاتا ہے۔",
        houseGuideDevices="تلاش کرو، پھر ایک آلہ چھؤ.",
        houseGuideMap="تجویز مانو یا کمرہ چنو.",
        menu="مینو",
        ragModeShort="گھر کا سیاق",
        llmThinking="Thinking",
        unitSystem="اکائیاں",
        unitSystemHint="بولی اور سمجھی گئی حرارت۔ روشنیاں، ٹائمر اور چمک ویسی رہتی ہیں۔",
        unitMetric="میٹرک",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="زبانیں",
        settingsNavVoice="آواز",
        llmProvider="فراہم کنندہ",
        llmPresetCustom="OpenAI سے ہم آہنگ",
        personalityPrompt="شخصیت کا پرامپٹ",
    ),
    "tr": pages(
        guideRoutinesSay="Ne dersin?",
        guideRoutinesSayHint="İyi geceler, gidiyorum, film gecesi.",
        guideRoutinesScript="Hangi script?",
        guideRoutinesScriptHint="script.xxx seç. entity id yazma.",
        guideSentencesPhrase="Hangi cümle?",
        guideSentencesPhraseHint="Gerçekten söylediğiniz gibi.",
        guideSentencesIntent="Klar ne yapsın?",
        guideSentencesIntentHint="Bir niyet seç, cihaz yalnızca gerekirse.",
        guideSentencesTest="Dene",
        guideSentencesTestHint="Cümle kalmadan önce önizleme.",
        guidePoliciesMatch="Hangi komutlar",
        guidePoliciesMatchHint="Engine eşleştiricileri. Nedenini bilmiyorsan açık bırak.",
        guidePoliciesLang="Dil güvenliği",
        guidePoliciesLangHint="Paket seed'leri ve sözlük. Yalnızca bir sözcük yanlışsa.",
        guidePoliciesHouse="Senin kuralın",
        guidePoliciesHouseHint="Ne zaman → o zaman. Cihaz veya oda seç, id yazma.",
        guidePoliciesTest="Dene",
        guidePoliciesTestHint="Cümle yaz ve Çözümle. Çerçeveli şerit yakaladı.",
        houseGuideGraph="Denetlemek için cihaza dokun. Sürüklemek yalnızca kartı taşır.",
        houseGuideDevices="Ara, sonra bir cihaza dokun.",
        houseGuideMap="Öneriyi kabul et veya oda seç.",
        menu="Menü",
        ragModeShort="Ev bağlamı",
        llmThinking="Thinking",
        unitSystem="Birimler",
        unitSystemHint="Konuşulan ve anlaşılan sıcaklıklar. Işıklar, zamanlayıcılar ve parlaklık aynı kalır.",
        unitMetric="Metrik",
        unitImperial="Imperial",
        settingsNavBackup="Backup",
        settingsNavEngine="Engine",
        settingsNavLanguages="Diller",
        settingsNavVoice="Ses",
        llmProvider="Sağlayıcı",
        llmPresetCustom="OpenAI uyumlu",
        personalityPrompt="Kişilik promptu",
    ),
}
PACKS.update(EAST)
