"""Custom-voice and interview chrome for Nordic and Baltic Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice

PACKS: dict[str, dict[str, str]] = {
    "da": voice(
        personalityCustom="Egen stemme",
        customVoice="Egen stemme",
        customVoiceHint="Seed fastlægger figuren. Skydere finpudser kun måden, den taler på. Sproglås og sikkerhedsregler bliver.",
        customVoiceMake="Skriv stemme fra seed og skydere",
        customVoiceFail="Kunne ikke skrive en stemme. Tjek LLM'en.",
        customVoiceName="Stemmenavn",
        customVoiceNameHint="Sådan vises denne personlighed på listen.",
        customVoiceSeed="Seed-prompt",
        customVoiceSeedHint="Hvem Klar skal være, uafhængigt af skyderne. For eksempel: Du er Spock fra Star Trek.",
        interviewTraitsHint="0 = fra, 10 = stærk. Kun leveringen, ikke figuren.",
        interviewWarmth="Varme",
        interviewSarcasm="Sarkasme",
        interviewFormality="Formalitet",
        interviewVerbosity="Udførlighed",
        interviewEnergy="Energi",
        interviewAddress="Hvordan skal Klar tiltale dig?",
        interviewAddressDu="Du",
        interviewAddressSie="De",
        interviewAddressName="Fornavn",
        interviewName="Navn",
        interviewTone="Tone",
        interviewToneShort="Kort",
        interviewToneWarm="Varm",
        interviewToneDry="Tør",
        interviewHumor="Humor",
        interviewHumorNone="Ingen",
        interviewHumorLight="Let",
        interviewHumorSharp="Skarp",
        interviewLength="Længde",
        interviewLengthOne="Én sætning",
        interviewLengthMore="Lidt mere",
        interviewTaboo="Sig ikke",
    ),
    "nb": voice(
        personalityCustom="Egen stemme",
        customVoice="Egen stemme",
        customVoiceHint="Seed fastsetter figuren. Glidere finpusser bare hvordan den snakker. Språklås og sikkerhetsregler blir.",
        customVoiceMake="Skriv stemme fra seed og glidere",
        customVoiceFail="Klarte ikke å skrive en stemme. Sjekk LLM-en.",
        customVoiceName="Stemmenavn",
        customVoiceNameHint="Slik vises denne personligheten i listen.",
        customVoiceSeed="Seed-prompt",
        customVoiceSeedHint="Hvem Klar skal være, uavhengig av gliderne. For eksempel: Du er Spock fra Star Trek.",
        interviewTraitsHint="0 = av, 10 = sterk. Bare leveringen, ikke figuren.",
        interviewWarmth="Varme",
        interviewSarcasm="Sarkasme",
        interviewFormality="Formalitet",
        interviewVerbosity="Utførlighet",
        interviewEnergy="Energi",
        interviewAddress="Hvordan skal Klar tiltale deg?",
        interviewAddressDu="Du",
        interviewAddressSie="De",
        interviewAddressName="Fornavn",
        interviewName="Navn",
        interviewTone="Tone",
        interviewToneShort="Kort",
        interviewToneWarm="Varm",
        interviewToneDry="Tørr",
        interviewHumor="Humor",
        interviewHumorNone="Ingen",
        interviewHumorLight="Lett",
        interviewHumorSharp="Skarp",
        interviewLength="Lengde",
        interviewLengthOne="Én setning",
        interviewLengthMore="Litt mer",
        interviewTaboo="Ikke si",
    ),
    "sv": voice(
        personalityCustom="Egen röst",
        customVoice="Egen röst",
        customVoiceHint="Seed sätter figuren. Reglagen finslipar bara hur den talar. Språklås och säkerhetsregler är kvar.",
        customVoiceMake="Skriv röst från seed och reglage",
        customVoiceFail="Kunde inte skriva en röst. Kontrollera LLM:n.",
        customVoiceName="Röstnamn",
        customVoiceNameHint="Så syns den här personligheten i listan.",
        customVoiceSeed="Seed-prompt",
        customVoiceSeedHint="Vem Klar ska vara, oberoende av reglagen. Till exempel: Du är Spock från Star Trek.",
        interviewTraitsHint="0 = av, 10 = stark. Bara framförandet, inte figuren.",
        interviewWarmth="Värme",
        interviewSarcasm="Sarkasm",
        interviewFormality="Formalitet",
        interviewVerbosity="Utförlighet",
        interviewEnergy="Energi",
        interviewAddress="Hur ska Klar tilltala dig?",
        interviewAddressDu="Du",
        interviewAddressSie="Ni",
        interviewAddressName="Förnamn",
        interviewName="Namn",
        interviewTone="Ton",
        interviewToneShort="Kort",
        interviewToneWarm="Varm",
        interviewToneDry="Torr",
        interviewHumor="Humor",
        interviewHumorNone="Ingen",
        interviewHumorLight="Lätt",
        interviewHumorSharp="Vass",
        interviewLength="Längd",
        interviewLengthOne="En mening",
        interviewLengthMore="Lite mer",
        interviewTaboo="Säg inte",
    ),
    "fi": voice(
        personalityCustom="Oma ääni",
        customVoice="Oma ääni",
        customVoiceHint="Seed määrää hahmon. Liukusäätimet hiovat vain puhetapaa. Kielilukko ja turvasäännöt jäävät.",
        customVoiceMake="Kirjoita ääni seedistä ja liukusäätimistä",
        customVoiceFail="Ääntä ei voitu kirjoittaa. Tarkista LLM.",
        customVoiceName="Äänen nimi",
        customVoiceNameHint="Näin tämä persoonallisuus näkyy listassa.",
        customVoiceSeed="Seed-kehote",
        customVoiceSeedHint="Kuka Klarin tulee olla, liukusäätimistä riippumatta. Esimerkiksi: Olet Spock Star Trekistä.",
        interviewTraitsHint="0 = pois, 10 = vahva. Vain esitystapa, ei hahmo.",
        interviewWarmth="Lämpö",
        interviewSarcasm="Sarkasmi",
        interviewFormality="Muodollisuus",
        interviewVerbosity="Sanallisuus",
        interviewEnergy="Energia",
        interviewAddress="Miten Klarin tulee puhutella sinua?",
        interviewAddressDu="Sinä",
        interviewAddressSie="Te",
        interviewAddressName="Etunimi",
        interviewName="Nimi",
        interviewTone="Sävy",
        interviewToneShort="Lyhyt",
        interviewToneWarm="Lämmin",
        interviewToneDry="Kuiva",
        interviewHumor="Huumori",
        interviewHumorNone="Ei mitään",
        interviewHumorLight="Kevyt",
        interviewHumorSharp="Terävä",
        interviewLength="Pituus",
        interviewLengthOne="Yksi lause",
        interviewLengthMore="Hieman lisää",
        interviewTaboo="Älä sano",
    ),
    "is": voice(
        personalityCustom="Eigin rödd",
        customVoice="Eigin rödd",
        customVoiceHint="Seed setur persónuna. Renndur fínpússa aðeins hvernig hún talar. Tungumálalás og öryggisreglur haldast.",
        customVoiceMake="Skrifa rödd úr seed og renndum",
        customVoiceFail="Gat ekki skrifað rödd. Athugaðu LLM.",
        customVoiceName="Nafn raddar",
        customVoiceNameHint="Svona birtist þessi persónuleiki á listanum.",
        customVoiceSeed="Seed-kvaðning",
        customVoiceSeedHint="Hver Klar á að vera, óháð renndunum. Til dæmis: Þú ert Spock úr Star Trek.",
        interviewTraitsHint="0 = slökkt, 10 = sterkt. Aðeins framsetningin, ekki persónan.",
        interviewWarmth="Hlýja",
        interviewSarcasm="Sarkasmi",
        interviewFormality="Formlegheit",
        interviewVerbosity="Orðamunur",
        interviewEnergy="Orka",
        interviewAddress="Hvernig á Klar að ávarpa þig?",
        interviewAddressDu="Þú",
        interviewAddressSie="Þér",
        interviewAddressName="Fornafn",
        interviewName="Nafn",
        interviewTone="Tónn",
        interviewToneShort="Stutt",
        interviewToneWarm="Hlýtt",
        interviewToneDry="Þurrt",
        interviewHumor="Húmor",
        interviewHumorNone="Enginn",
        interviewHumorLight="Létt",
        interviewHumorSharp="Beitt",
        interviewLength="Lengd",
        interviewLengthOne="Ein setning",
        interviewLengthMore="Aðeins meira",
        interviewTaboo="Ekki segja",
    ),
    "et": voice(
        personalityCustom="Oma hääl",
        customVoice="Oma hääl",
        customVoiceHint="Seed määrab tegelase. Liugurid lihvivad ainult kõneviisi. Keelelukk ja turvareeglid jäävad.",
        customVoiceMake="Kirjuta hääl seedist ja liuguritest",
        customVoiceFail="Häält ei saanud kirjutada. Kontrolli LLM-i.",
        customVoiceName="Hääle nimi",
        customVoiceNameHint="Nii ilmub see isiksus loendis.",
        customVoiceSeed="Seed-viip",
        customVoiceSeedHint="Kes Klar peab olema, liuguritest sõltumata. Näiteks: Sa oled Spock Star Trekist.",
        interviewTraitsHint="0 = väljas, 10 = tugev. Ainult esitus, mitte tegelane.",
        interviewWarmth="Soojus",
        interviewSarcasm="Sarkasm",
        interviewFormality="Formaalsus",
        interviewVerbosity="Sõnaohtrus",
        interviewEnergy="Energia",
        interviewAddress="Kuidas Klar peaks sind kõnetama?",
        interviewAddressDu="Sina",
        interviewAddressSie="Teie",
        interviewAddressName="Eesnimi",
        interviewName="Nimi",
        interviewTone="Toon",
        interviewToneShort="Lühike",
        interviewToneWarm="Soe",
        interviewToneDry="Kuiv",
        interviewHumor="Huumor",
        interviewHumorNone="Puudub",
        interviewHumorLight="Kerge",
        interviewHumorSharp="Terav",
        interviewLength="Pikkus",
        interviewLengthOne="Üks lause",
        interviewLengthMore="Natuke rohkem",
        interviewTaboo="Ära ütle",
    ),
    "lt": voice(
        personalityCustom="Savo balsas",
        customVoice="Savo balsas",
        customVoiceHint="Seed nustato veikėją. Šliaužikliai tik šlifuoja kalbėjimo būdą. Kalbos spyna ir saugos taisyklės lieka.",
        customVoiceMake="Rašyti balsą iš seed ir šliaužiklių",
        customVoiceFail="Nepavyko parašyti balso. Patikrinkite LLM.",
        customVoiceName="Balso vardas",
        customVoiceNameHint="Taip ši asmenybė rodoma sąraše.",
        customVoiceSeed="Seed užklausa",
        customVoiceSeedHint="Kas Klar turi būti, nepriklausomai nuo šliaužiklių. Pavyzdžiui: Tu esi Spockas iš Star Trek.",
        interviewTraitsHint="0 = išjungta, 10 = stipru. Tik pateikimas, ne veikėjas.",
        interviewWarmth="Šiluma",
        interviewSarcasm="Sarkazmas",
        interviewFormality="Formalumas",
        interviewVerbosity="Žodingumas",
        interviewEnergy="Energija",
        interviewAddress="Kaip Klar turėtų tave kreiptis?",
        interviewAddressDu="Tu",
        interviewAddressSie="Jūs",
        interviewAddressName="Vardas",
        interviewName="Vardas",
        interviewTone="Tonas",
        interviewToneShort="Trumpas",
        interviewToneWarm="Šiltas",
        interviewToneDry="Sausas",
        interviewHumor="Humoras",
        interviewHumorNone="Nėra",
        interviewHumorLight="Lengvas",
        interviewHumorSharp="Aštrus",
        interviewLength="Ilgis",
        interviewLengthOne="Vienas sakinys",
        interviewLengthMore="Truputį daugiau",
        interviewTaboo="Nesakyti",
    ),
    "lv": voice(
        personalityCustom="Paša balss",
        customVoice="Paša balss",
        customVoiceHint="Seed nosaka tēlu. Slīdņi tikai noslīpē runas veidu. Valodas slēdzene un drošības noteikumi paliek.",
        customVoiceMake="Rakstīt balsi no seed un slīdņiem",
        customVoiceFail="Neizdevās uzrakstīt balsi. Pārbaudi LLM.",
        customVoiceName="Balss nosaukums",
        customVoiceNameHint="Tā šī personība parādās sarakstā.",
        customVoiceSeed="Seed uzvedne",
        customVoiceSeedHint="Kam Klar jābūt, neatkarīgi no slīdņiem. Piemēram: Tu esi Spoks no Zvaigžņu ceļa.",
        interviewTraitsHint="0 = izslēgts, 10 = spēcīgi. Tikai izpildījums, ne tēls.",
        interviewWarmth="Siltums",
        interviewSarcasm="Sarkasms",
        interviewFormality="Formālums",
        interviewVerbosity="Vārdu daudzums",
        interviewEnergy="Enerģija",
        interviewAddress="Kā Klar vajadzētu tevi uzrunāt?",
        interviewAddressDu="Tu",
        interviewAddressSie="Jūs",
        interviewAddressName="Vārds",
        interviewName="Vārds",
        interviewTone="Tonis",
        interviewToneShort="Īss",
        interviewToneWarm="Silts",
        interviewToneDry="Sauss",
        interviewHumor="Humors",
        interviewHumorNone="Nav",
        interviewHumorLight="Viegls",
        interviewHumorSharp="Ass",
        interviewLength="Garums",
        interviewLengthOne="Viens teikums",
        interviewLengthMore="Nedaudz vairāk",
        interviewTaboo="Nesaki",
    ),
}
