"""Operator UI field map. Catalogs store unique chrome; expand() fills aliases."""

from __future__ import annotations

ALIASES = {
    "dashboard": "home",
    "parse": "lab",
    "houseGraph": "graph",
    "houseDevices": "entities",
    "houseMap": "calibrate",
    "matchedRule": "addRule",
    "ragMode": "nluRag",
    "sentences": "custom",
}

CONSTANTS = {
    "unitsPercent": "%",
    "entityId": "entity_id",
    "advancedJson": "JSON",
    "unitsUs": "µs",
    "unitsMs": "ms",
    "coverageGraph": "Graph",
    "coverageAssist": "Assist",
    "coverageReady": "ready",
    "coverageOpen": "open",
    "floors": "Floors",
}

CATALOG_KEYS = (
    "home",
    "conversations",
    "rules",
    "house",
    "lab",
    "graph",
    "calibrate",
    "entities",
    "custom",
    "settings",
    "open",
    "bundleOn",
    "bundleOff",
    "engineReady",
    "understandsHome",
    "assistVisible",
    "certain",
    "needsWork",
    "recordings",
    "processed",
    "coverage",
    "confidence",
    "domains",
    "rooms",
    "recent",
    "replay",
    "applyAll",
    "undo",
    "accept",
    "otherRoom",
    "dismiss",
    "noGaps",
    "unmapped",
    "parseHint",
    "command",
    "analyze",
    "raw",
    "speech",
    "speechNlu",
    "speechRefined",
    "speechChat",
    "refineRejected",
    "intent",
    "slots",
    "searchDevice",
    "alias",
    "room",
    "preferred",
    "save",
    "saveOk",
    "saveFail",
    "saveUnauthorized",
    "personality",
    "mode",
    "modeFull",
    "modeContext",
    "modeHint",
    "supportBundle",
    "recordProtocol",
    "recordProtocolHint",
    "includeRawText",
    "includeRawTextHint",
    "semanticAdapters",
    "semanticAdaptersHint",
    "downloadDataset",
    "downloadProtocol",
    "settingsBackup",
    "settingsBackupHint",
    "settingsBackupDownload",
    "settingsBackupIncludeKey",
    "settingsBackupIncludeKeyHint",
    "settingsBackupIncludeKeyConfirm",
    "settingsBackupRestore",
    "settingsBackupRestoreConfirm",
    "settingsBackupRestoreOk",
    "settingsBackupRestoreFail",
    "settingsBackupPickFile",
    "deleteSelected",
    "clearAll",
    "token",
    "tokenHint",
    "customJson",
    "customHint",
    "addPhrase",
    "previewRule",
    "explainRule",
    "rollback",
    "noRules",
    "engineOffline",
    "emptyBundle",
    "confirmApply",
    "cancel",
    "apply",
    "close",
    "low",
    "medium",
    "high",
    "source",
    "language",
    "time",
    "text",
    "answer",
    "graphHint",
    "resetLayout",
    "score",
    "noIntent",
    "loading",
    "nluRag",
    "nluRagHint",
    "confirmRisky",
    "confirmRiskyHint",
    "languages",
    "languageSearch",
    "allLanguages",
    "noLanguageMatch",
    "languageHint",
    "operatorLanguage",
    "operatorLanguageHint",
    "engineHint",
    "assistLanguages",
    "assistLanguagesHint",
    "allAssistLanguages",
    "pinLanguage",
    "voice",
    "voiceHint",
    "extraPrompt",
    "extraPromptHint",
    "personalityPrompt",
    "personalityPromptHint",
    "refineSpeech",
    "refineSpeechHint",
    "refineBandStatus",
    "refineBandStatusHint",
    "refineBandCommand",
    "refineBandCommandHint",
    "refineBandPrompt",
    "refineBandPromptHint",
    "refineBandReject",
    "refineBandRejectHint",
    "refineBandsHint",
    "quietAck",
    "quietAckHint",
    "unitSystem",
    "unitSystemHint",
    "unitMetric",
    "unitImperial",
    "calendarLlm",
    "calendarLlmHint",
    "allowLlmTools",
    "allowLlmToolsHint",
    "missTitle",
    "missHint",
    "operatorChrome",
    "operatorChromeHint",
    "haGlueHint",
    "settingsGuide",
    "settingsGuideVoice",
    "settingsGuideLlm",
    "settingsGuideLang",
    "settingsNavLlm",
    "settingsNavVoice",
    "settingsNavLanguages",
    "settingsNavEngine",
    "settingsNavBackup",
    "appearanceDark",
    "appearanceLight",
    "setupReplay",
    "mappingHint",
    "parseSample",
    "tryOn",
    "tryLock",
    "tryTime",
    "tryNight",
    "tryUndo",
    "tryRoom",
    "nluIgnore",
    "nluIgnoreHint",
    "savePhrase",
    "ignoreTarget",
    "teachSaved",
    "journal",
    "journalHint",
    "decisionMix",
    "mixCaption",
    "coverageCaption",
    "latency",
    "latencyCaption",
    "unitsTurns",
    "llmCalls",
    "llmCallsCaption",
    "llmKindRefine",
    "llmKindAssist",
    "llmKindChat",
    "llmErrors",
    "llmAcceptRate",
    "llmLatency",
    "llmLatencyCaption",
    "llmTokens",
    "llmTokensCaption",
    "llmNoCalls",
    "timeline",
    "noConversations",
    "when",
    "then",
    "priority",
    "evaluator",
    "bakeSpeech",
    "addRule",
    "noPolicies",
    "compiledRisk",
    "finalBand",
    "processPath",
    "triggerFirst",
    "discarded",
    "stageTokens",
    "stageBind",
    "stageRank",
    "stagePolicy",
    "stageBand",
    "effectConfirm",
    "effectBlock",
    "effectAllow",
    "effectPreferEntity",
    "effectPreferArea",
    "effectReply",
    "effectScript",
    "effectTemplate",
    "effectLlm",
    "payloadReply",
    "payloadScript",
    "payloadTemplate",
    "payloadLlm",
    "whenPhrase",
    "chatMode",
    "variantPreview",
    "policies",
    "routines",
    "routineHint",
    "routinePhraseHint",
    "addRoutine",
    "noRoutines",
    "routineInvalid",
    "lastTurn",
    "heardIn",
    "tryThese",
    "tryTheseHint",
    "anyRoom",
    "inLab",
    "undoLastCommand",
    "applyDone",
    "applyUndone",
    "applyUndoFailed",
    "personalityHa",
    "personalityDefault",
    "personalityButler",
    "personalityLocker",
    "personalityFuersorglich",
    "personalityParty",
    "personalityGrantig",
    "personalitySarkastisch",
    "personalityPirat",
    "personalityHippie",
    "personalityGollum",
    "personalityJarvis",
    "personalityCustom",
    "customVoice",
    "customVoiceHint",
    "customVoiceMake",
    "customVoiceFail",
    "customVoiceName",
    "customVoiceNameHint",
    "customVoiceSeed",
    "customVoiceSeedHint",
    "interviewTraitsHint",
    "interviewWarmth",
    "interviewSarcasm",
    "interviewFormality",
    "interviewVerbosity",
    "interviewEnergy",
    "interviewAddress",
    "interviewAddressDu",
    "interviewAddressSie",
    "interviewAddressName",
    "interviewName",
    "interviewTone",
    "interviewToneShort",
    "interviewToneWarm",
    "interviewToneDry",
    "interviewHumor",
    "interviewHumorNone",
    "interviewHumorLight",
    "interviewHumorSharp",
    "interviewLength",
    "interviewLengthOne",
    "interviewLengthMore",
    "interviewTaboo",
    "pathUnchecked",
    "pathMatch",
    "pathSeed",
    "pathHouse",
    "pathBand",
    "laneMatch",
    "laneMatchEngine",
    "laneLanguage",
    "laneHouse",
    "laneTabs",
    "lexiconOverlay",
    "lexiconOverlayPlus",
    "lexiconEmpty",
    "governSeed",
    "governEmpty",
    "matchCatalog",
    "matchReadOnly",
    "matchEnabled",
    "matchDisabled",
    "matchPrecedence",
    "matchDisableWarning",
    "lexiconPath",
    "lexiconToken",
    "lexiconAdd",
    "lexiconRemove",
    "originEngine",
    "originOperator",
    "originSeed",
    "originTrainer",
    "compiledFloor",
    "trainer",
    "trainerForLane",
    "trainerHint",
    "trainerContext",
    "trainerValidate",
    "trainerApply",
    "trainerProposal",
    "trainerOk",
    "trainerFail",
    "trainerSend",
    "trainerNeedLlm",
    "trainerOpenSettings",
    "trainerApplyHouse",
    "trainerApplyMatch",
    "trainerApplyLanguage",
    "trainerAdvanced",
    "trainerStreaming",
    "trainerAllow",
    "trainerAllowOnce",
    "trainerYolo",
    "trainerDeny",
    "trainerAskAgain",
    "llm",
    "llmHint",
    "llmBaseUrl",
    "llmModel",
    "llmModelsEmpty",
    "llmModelsFail",
    "llmModelsLoading",
    "llmApiKey",
    "llmApiKeyHint",
    "llmProvider",
    "llmPresetOpenAi",
    "llmPresetOllama",
    "llmPresetAnthropic",
    "llmPresetGoogle",
    "llmPresetLemonade",
    "llmPresetLlamaCpp",
    "llmPresetCustom",
    "llmConfigured",
    "llmNotConfigured",
    "llmClear",
    "llmThinking",
    "llmThinkingHint",
    "menu",
    "seedOn",
    "seedOff",
    "conversationsEmptyHint",
    "evaluatorHint",
    "rulesRoutinesHint",
    "rulesSentencesHint",
    "rulesPoliciesHint",
    "guideRoutinesSay",
    "guideRoutinesSayHint",
    "guideRoutinesScript",
    "guideRoutinesScriptHint",
    "guideSentencesPhrase",
    "guideSentencesPhraseHint",
    "guideSentencesIntent",
    "guideSentencesIntentHint",
    "guideSentencesTest",
    "guideSentencesTestHint",
    "guidePoliciesMatch",
    "guidePoliciesMatchHint",
    "guidePoliciesLang",
    "guidePoliciesLangHint",
    "guidePoliciesHouse",
    "guidePoliciesHouseHint",
    "guidePoliciesTest",
    "guidePoliciesTestHint",
    "houseGuideGraph",
    "houseGuideDevices",
    "houseGuideMap",
    "labGuide",
    "ragModeShort",
    "trainerEmpty",
    "trainerEmptyHint",
    "trainerYou",
    "trainerPermit",
    "trainerPromptGaps",
    "trainerPromptNight",
    "trainerPromptMatchers",
    "trainerPromptPrecedence",
    "trainerPromptLexicon",
    "trainerPromptSlang",
    "trainerTool",
    "trainerClear",
    "trainerComposer",
    "trainerYes",
    "trainerNo",
    "trainerNotNow",
    "labPipeline",
    "labThisTurn",
    "labChipContextOnly",
    "labChipNluRag",
    "labChipSemantic",
    "labChipNoConfirm",
    "labChipLlmRefine",
    "labChipCalendarLlm",
    "labChipQuietAck",
    "labChipLlmTools",
    "labChipLlmChat",
    "labChipConfirmRisky",
    "labDecisionExecute",
    "labDecisionBriefing",
    "labParse",
    "reasonMissingArea",
    "reasonWeakName",
    "reasonReady",
    "reasonMatch",
    "sentencesEmpty",
    "policiesEmpty",
    "setupAgainWhere",
    "whyThisBand",
    "rememberAsPhrase",
    "evidence",
    "names",
)


# English fallbacks for operator-chrome keys not yet hand-translated in pack tables.
FALLBACKS = {
    "engineOffline": "Engine unreachable. This list is empty until a live load succeeds.",
    "settingsBackup": "Settings backup",
    "settingsBackupHint": "Overlay, assignments, rules, and the LLM endpoint. Conversations and the house graph stay on this engine.",
    "settingsBackupDownload": "Download settings",
    "settingsBackupIncludeKey": "Include API key",
    "settingsBackupIncludeKeyHint": "Off by default. On: the archive contains the stored LLM key.",
    "settingsBackupIncludeKeyConfirm": "The archive will contain the LLM API key. Download anyway?",
    "settingsBackupRestore": "Restore settings",
    "settingsBackupRestoreConfirm": "This overwrites all Klar settings on this engine.",
    "settingsBackupRestoreOk": "Settings restored.",
    "settingsBackupRestoreFail": "Could not restore settings.",
    "saveOk": "Saved.",
    "saveFail": "Could not save.",
    "saveUnauthorized": "Not saved. Enter the write token under Engine.",
    "settingsBackupPickFile": "Choose archive",
    "processPath": "Path",
    "pathUnchecked": "—",
    "pathMatch": "Match",
    "pathSeed": "Seed",
    "pathHouse": "House",
    "pathBand": "Band",
    "laneMatch": "Match",
    "laneMatchEngine": "Match (Engine)",
    "laneLanguage": "Language",
    "laneHouse": "House",
    "laneTabs": "Lanes",
    "lexiconOverlay": "Lexicon overlay",
    "lexiconOverlayPlus": "Lexicon overlay +{count}",
    "lexiconEmpty": "No lexicon overlay deltas.",
    "governSeed": "Govern seed",
    "governEmpty": "Safety seeds ship with every pack. Off writes a house override; the compiled floor stays on.",
    "matchCatalog": "Compiled matchers",
    "matchReadOnly": "Missing row uses the engine default. Empty overlay is today’s candidate list.",
    "matchEnabled": "On",
    "matchDisabled": "Off",
    "matchPrecedence": "Precedence",
    "matchDisableWarning": "Disabling area_command or all_lights changes room-wide and whole-home commands.",
    "lexiconPath": "Set path",
    "lexiconToken": "Token",
    "lexiconAdd": "Add",
    "lexiconRemove": "Remove",
    "originEngine": "engine",
    "originOperator": "operator",
    "originSeed": "seed",
    "originTrainer": "trainer",
    "compiledFloor": "compiled floor",
    "trainer": "Guide",
    "trainerForLane": "Guide for this lane",
    "trainerHint": "Ask about Klar anytime. Writes wait for Allow in this chat.",
    "trainerContext": "Context",
    "trainerValidate": "Validate",
    "trainerApply": "Apply",
    "trainerProposal": "Proposal JSON",
    "trainerOk": "Valid",
    "trainerFail": "Invalid",
    "trainerSend": "Send",
    "trainerNeedLlm": "Configure an LLM in Settings first. Klar does not need another Home Assistant conversation integration.",
    "trainerOpenSettings": "Open Settings",
    "trainerApplyHouse": "Apply House",
    "trainerApplyMatch": "Apply Match",
    "trainerApplyLanguage": "Apply Language",
    "trainerAdvanced": "Advanced JSON",
    "trainerStreaming": "Streaming…",
    "trainerAllow": "Allow",
    "trainerAllowOnce": "Allow once",
    "trainerYolo": "YOLO",
    "trainerDeny": "Deny",
    "trainerAskAgain": "Ask again",
    "llm": "LLM",
    "llmHint": "Klar talks to an OpenAI-compatible endpoint. Assist chat and Lotse use this same config. No Home Assistant OpenAI or Ollama integration is required.",
    "llmBaseUrl": "Base URL",
    "llmModel": "Model",
    "llmModelsEmpty": "No models from this endpoint. Type an id.",
    "llmModelsFail": "Could not list models. Type an id.",
    "llmModelsLoading": "Loading models…",
    "llmApiKey": "API key",
    "llmApiKeyHint": "Leave empty to keep the stored key. Ollama can stay empty.",
    "llmProvider": "Provider",
    "llmPresetOpenAi": "OpenAI",
    "llmPresetOllama": "Ollama",
    "llmPresetAnthropic": "Anthropic",
    "llmPresetGoogle": "Google",
    "llmPresetLemonade": "Lemonade AI",
    "llmPresetLlamaCpp": "llama.cpp",
    "llmPresetCustom": "OpenAI-compatible",
    "llmConfigured": "Configured",
    "llmNotConfigured": "Not configured",
    "llmClear": "Clear",
    "llmThinking": "Thinking",
    "llmThinkingHint": "Off uses each provider’s no-thinking flag (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-series: reasoning_effort none, Anthropic: omit thinking, Google: thinking_budget 0).",
    "speechNlu": "NLU",
    "speechRefined": "LLM refine",
    "speechChat": "LLM chat",
    "refineRejected": "Refine kept the NLU reply.",
    "menu": "Menu",
    "seedOn": "On",
    "seedOff": "Off",
    "nluRag": "House context on miss",
    "operatorLanguage": "Operator language",
    "operatorLanguageHint": "This app only. Saved here, or KLAR_UI_LOCALE before the first save. Not Assist, not the Home Assistant profile.",
    "modeFull": "Resolve devices",
    "modeContext": "Rooms only",
    "modeHint": "Resolve devices: Klar picks the entity. Rooms only: it stops at the area.",
    "inLab": "In Lab",
    "undoLastCommand": "Undo last command",
    "applyDone": "Applied {count} room suggestions",
    "applyUndone": "Room suggestions undone",
    "applyUndoFailed": "Could not undo room suggestions",
    "languageHint": "Empty list keeps every compiled Assist locale. Pinning one pack is the usual household.",
    "personalityHa": "Voice, languages, and the LLM live on this Settings page.",
    "engineHint": "Voice, languages, and the LLM live here. Home Assistant only connects the engine.",
    "assistLanguages": "Assist languages",
    "assistLanguagesHint": "Which packs Klar may parse. The satellite still sends one language per request. Empty = all compiled locales.",
    "allAssistLanguages": "Every compiled locale",
    "pinLanguage": "Pin one pack",
    "voice": "Voice",
    "voiceHint": "Personality and spoken replies. Assist reads this from the engine, not from Home Assistant options.",
    "extraPrompt": "Extra prompt",
    "extraPromptHint": "House rule sent as a user message. Does not replace the packed voice. Leave empty unless the house needs its own rule.",
    "personalityPrompt": "Personality prompt",
    "personalityPromptHint": "System prompt for this voice: language lock, safety rules, and stock few-shots. Extra prompt is a separate user message.",
    "refineSpeech": "LLM refine",
    "refineSpeechHint": "Klar still controls devices without the LLM. Choose which finished spoken replies get this voice.",
    "refineBandStatus": "Status",
    "refineBandStatusHint": "Answers like room or device status. On: the LLM rewrites the finished sentence.",
    "refineBandCommand": "Commands",
    "refineBandCommandHint": "Spoken ack after Klar already ran the command. On: “light is on” gets this voice.",
    "refineBandPrompt": "Follow-up questions",
    "refineBandPromptHint": "Which-room and which-device questions. On: Klar’s question is rewritten.",
    "refineBandReject": "Rejection",
    "refineBandRejectHint": "I-didn’t-understand replies. On: those sentences get this voice.",
    "refineBandsHint": "Chat and calendar LLM replies stay as they are — no second refine.",
    "quietAck": "Short confirmation",
    "quietAckHint": "On a simple light or switch on/off, skip TTS and play a chime on the satellite.",
    "unitSystem": "Units",
    "unitSystemHint": "Spoken and parsed temperatures. Lights, timers, and brightness stay as they are.",
    "unitMetric": "Metric",
    "unitImperial": "Imperial",
    "calendarLlm": "Calendar through the LLM",
    "calendarLlmHint": "Klar still reads the calendar. On: the LLM speaks the events. Off: Klar speaks the list.",
    "allowLlmTools": "Allow Assist tools on chat",
    "allowLlmToolsHint": "Off by default. On: after Klar parses, the engine chat model may call Home Assistant Assist tools (names from Core). Off: conversation only.",
    "missTitle": "When Klar misses",
    "missHint": "Optional layers after a deterministic reject. None of these put a model on parse.",
    "confirmRiskyHint": "On: locks, closing covers, and large or room-wide risky commands ask once first. Off: they run immediately.",
    "recordProtocolHint": "On: Klar keeps the last 200 turns for 24 hours. Needed for the downloads below.",
    "includeRawTextHint": "On: downloads include the spoken sentence. Off: redacted only.",
    "semanticAdaptersHint": "Off by default. On: after a miss, a local meaning match may still recover the intent. Not an LLM.",
    "tokenHint": "Required to save from this screen. Same value as the App token.",
    "operatorChrome": "This screen",
    "operatorChromeHint": "Theme and chrome language for operators. Not Assist.",
    "haGlueHint": "Home Assistant Configure only needs engine URL, token, channel, and an optional leftover conversation agent. Voice and LLM stay here.",
    "settingsGuide": "Set these three, then map the house.",
    "settingsGuideVoice": "Voice",
    "settingsGuideLlm": "LLM",
    "settingsGuideLang": "Assist language",
    "settingsNavLlm": "LLM",
    "settingsNavVoice": "Voice",
    "settingsNavLanguages": "Languages",
    "settingsNavEngine": "Engine",
    "settingsNavBackup": "Backup",
    "appearanceDark": "Dark",
    "appearanceLight": "Light",
    "setupReplay": "Replay setup",
    "personalityDefault": "Normal",
    "personalityButler": "Butler",
    "personalityLocker": "Casual",
    "personalityFuersorglich": "Caring",
    "personalityParty": "Party",
    "personalityGrantig": "Grumpy",
    "personalitySarkastisch": "Sarcastic",
    "personalityPirat": "Pirate",
    "personalityHippie": "Hippie",
    "personalityGollum": "Gollum",
    "personalityJarvis": "Jarvis",
    "personalityCustom": "Custom voice",
    "customVoice": "Custom voice",
    "customVoiceHint": "The seed sets the character. Sliders only refine how it speaks. Language lock and safety rules stay.",
    "customVoiceMake": "Write voice from seed and sliders",
    "customVoiceFail": "Could not write a voice. Check the LLM.",
    "customVoiceName": "Voice name",
    "customVoiceNameHint": "How this personality appears in the list.",
    "customVoiceSeed": "Seed prompt",
    "customVoiceSeedHint": "Who Klar should be, independent of the sliders. For example: You are Spock from Star Trek.",
    "interviewTraitsHint": "0 = off, 10 = strong. Delivery only, not the character.",
    "interviewWarmth": "Warmth",
    "interviewSarcasm": "Sarcasm",
    "interviewFormality": "Formality",
    "interviewVerbosity": "Verbosity",
    "interviewEnergy": "Energy",
    "interviewAddress": "How should Klar address you?",
    "interviewAddressDu": "Informal you",
    "interviewAddressSie": "Formal you",
    "interviewAddressName": "First name",
    "interviewName": "Name",
    "interviewTone": "Tone",
    "interviewToneShort": "Short",
    "interviewToneWarm": "Warm",
    "interviewToneDry": "Dry",
    "interviewHumor": "Humor",
    "interviewHumorNone": "None",
    "interviewHumorLight": "Light",
    "interviewHumorSharp": "Sharp",
    "interviewLength": "Length",
    "interviewLengthOne": "One sentence",
    "interviewLengthMore": "A bit more",
    "interviewTaboo": "Do not say",
    'conversationsEmptyHint': 'Say something through Assist. It shows up here.',
    'evaluatorHint': 'Type it as you would at home. The framed step is the one that fired.',
    'rulesRoutinesHint': 'A spoken name starts a Home Assistant script.',
    'rulesSentencesHint': 'One sentence onto a known intent. Then try it.',
    'rulesPoliciesHint': 'Three lanes. Your house rule wins first. Then try a sentence below.',
    'guideRoutinesSay': 'What do you say?',
    'guideRoutinesSayHint': 'Good night, I’m leaving, movie time.',
    'guideRoutinesScript': 'Which script?',
    'guideRoutinesScriptHint': 'Pick script.xxx. Do not type an entity id.',
    'guideSentencesPhrase': 'Which sentence?',
    'guideSentencesPhraseHint': 'How you actually say it.',
    'guideSentencesIntent': 'What should Klar do?',
    'guideSentencesIntentHint': 'Pick an intent, optionally a device.',
    'guideSentencesTest': 'Try it',
    'guideSentencesTestHint': 'Preview before you keep the phrase.',
    'guidePoliciesMatch': 'Which commands',
    'guidePoliciesMatchHint': 'Engine matchers. Leave on unless you know why.',
    'guidePoliciesLang': 'Language safety',
    'guidePoliciesLangHint': 'Pack seeds and lexicon. Only if a word is wrong.',
    'guidePoliciesHouse': 'Your rule',
    'guidePoliciesHouseHint': 'When → then. Pick a device or room, don’t type ids.',
    'guidePoliciesTest': 'Try it',
    'guidePoliciesTestHint': 'Type a sentence and analyze. The framed lane fired.',
    'houseGuideGraph': 'Tap a device to inspect. Drag only moves the card.',
    'houseGuideDevices': 'Search, then tap a device.',
    'houseGuideMap': 'Accept the suggestion or pick a room.',
    'labGuide': 'Type a sentence, then Analyze or Enter.',
    'ragModeShort': 'House context',
    'trainerEmpty': 'Ask how Klar works — or about a gap.',
    'trainerEmptyHint': 'Lotse writes nothing until you tap Allow.',
    'trainerYou': 'You',
    'trainerPermit': 'Write access',
    'trainerPromptGaps': 'Which devices have no room?',
    'trainerPromptNight': 'Suggest a house rule for good night.',
    'trainerPromptMatchers': 'Which matchers are on, and in what order?',
    'trainerPromptPrecedence': 'Explain matcher precedence. Do not change it.',
    'trainerPromptLexicon': 'Which lexicon paths exist for German?',
    'trainerPromptSlang': 'Suggest slang to add to a lexicon path. Do not write yet.',
    'trainerTool': 'Tool',
    'trainerClear': 'Clear chat',
    'trainerComposer': 'Message Lotse',
    'trainerYes': 'Yes',
    'trainerNo': 'No',
    'trainerNotNow': 'Not now',
    "llmCalls": "LLM calls",
    "llmCallsCaption": "Source: engine LLM, last 24 hours",
    "llmKindRefine": "refine",
    "llmKindAssist": "assist",
    "llmKindChat": "chat",
    "llmErrors": "errors",
    "llmAcceptRate": "accept rate",
    "llmLatency": "LLM latency",
    "llmLatencyCaption": "Source: engine LLM, rolling window",
    "llmTokens": "tokens",
    "llmTokensCaption": "Source: upstream usage, when the model reports it",
    "llmNoCalls": "No LLM calls yet.",
    "labPipeline": "Pipeline",
    "labThisTurn": "This turn",
    "labChipContextOnly": "context only",
    "labChipNluRag": "NLU-RAG",
    "labChipSemantic": "semantic",
    "labChipNoConfirm": "no confirm",
    "labChipLlmRefine": "LLM refine",
    "labChipCalendarLlm": "calendar LLM",
    "labChipQuietAck": "quiet ack",
    "labChipLlmTools": "LLM tools",
    "labChipLlmChat": "LLM chat",
    "labChipConfirmRisky": "confirm risky",
    "labDecisionExecute": "Klar execute",
    "labDecisionBriefing": "briefing",
    "labParse": "Klar parse",
    "reasonMissingArea": "missing room",
    "reasonWeakName": "weak name",
    "reasonReady": "ready",
    "reasonMatch": "match",
    "sentencesEmpty": "One sentence onto a known intent. Not one phrase per light.",
    "policiesEmpty": "First matching rule wins. Pick a device, room, or floor — do not type ids.",
    "setupAgainWhere": "Replay setup is in Settings.",
    "whyThisBand": "Why this band?",
    "rememberAsPhrase": "Remember as phrase",
    "evidence": "Evidence",
    "names": "Names",
}


def expand(fields: dict[str, str]) -> dict[str, str]:
    out = {**CONSTANTS}
    for key in CATALOG_KEYS:
        out[key] = fields[key]
    for dest, src in ALIASES.items():
        out[dest] = out[src]
    return out
