"""Page-guide chrome for West European Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_guides import guides

PACKS: dict[str, dict[str, str]] = {
    "fr": guides(
        empty="Aucun modèle depuis cet endpoint. Saisis un id.",
        fail="Impossible de lister les modèles. Saisis un id.",
        loading="Chargement des modèles…",
        thinking="Désactivé utilise le drapeau no-thinking du fournisseur (Lemonade/llama.cpp : chat_template_kwargs, série o OpenAI : reasoning_effort none, Anthropic : omettre thinking, Google : thinking_budget 0).",
        convos="Dis quelque chose via Assist. Ça apparaît ici.",
        evaluator="Tape comme à la maison. L’étape encadrée est celle qui a déclenché.",
        routines="Un nom parlé lance un script Home Assistant.",
        sentences="Une phrase vers une intention connue. Puis essaie.",
        policies="Trois pistes. Ta règle maison gagne d’abord. Essaie une phrase plus bas.",
        lab="Saisis une phrase, puis Analyser ou Entrée.",
    ),
    "nl": guides(
        empty="Geen modellen van dit endpoint. Typ een id.",
        fail="Modellen niet opgehaald. Typ een id.",
        loading="Modellen laden…",
        thinking="Uit gebruikt de no-thinking-vlag van de aanbieder (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-serie: reasoning_effort none, Anthropic: thinking weglaten, Google: thinking_budget 0).",
        convos="Zeg iets via Assist. Het verschijnt hier.",
        evaluator="Typ het zoals thuis. De omlijnde stap is degene die greep.",
        routines="Een gesproken naam start een Home Assistant-script.",
        sentences="Eén zin op een bekende intentie. Probeer het daarna.",
        policies="Drie sporen. Jouw huisregel wint eerst. Probeer hieronder een zin.",
        lab="Typ een zin, daarna Analyseren of Enter.",
    ),
    "es": guides(
        empty="No hay modelos de este endpoint. Escribe un id.",
        fail="No se pudieron listar los modelos. Escribe un id.",
        loading="Cargando modelos…",
        thinking="Desactivado usa la bandera no-thinking del proveedor (Lemonade/llama.cpp: chat_template_kwargs, serie o de OpenAI: reasoning_effort none, Anthropic: omitir thinking, Google: thinking_budget 0).",
        convos="Di algo a través de Assist. Aparece aquí.",
        evaluator="Escríbelo como en casa. El paso enmarcado es el que disparó.",
        routines="Un nombre hablado inicia un script de Home Assistant.",
        sentences="Una frase hacia una intención conocida. Luego pruébala.",
        policies="Tres carriles. Tu regla de casa gana primero. Prueba una frase abajo.",
        lab="Escribe una frase, luego Analizar o Enter.",
    ),
    "it": guides(
        empty="Nessun modello da questo endpoint. Digita un id.",
        fail="Impossibile elencare i modelli. Digita un id.",
        loading="Caricamento modelli…",
        thinking="Disattivato usa il flag no-thinking del fornitore (Lemonade/llama.cpp: chat_template_kwargs, serie o OpenAI: reasoning_effort none, Anthropic: omettere thinking, Google: thinking_budget 0).",
        convos="Di qualcosa tramite Assist. Compare qui.",
        evaluator="Scrivilo come a casa. Il passo incorniciato è quello scattato.",
        routines="Un nome parlato avvia uno script Home Assistant.",
        sentences="Una frase su un intento noto. Poi provala.",
        policies="Tre corsie. La tua regola di casa vince per prima. Prova una frase sotto.",
        lab="Scrivi una frase, poi Analizza o Invio.",
    ),
    "pt": guides(
        empty="Sem modelos deste endpoint. Escreve um id.",
        fail="Não foi possível listar os modelos. Escreve um id.",
        loading="A carregar modelos…",
        thinking="Desligado usa a flag no-thinking do fornecedor (Lemonade/llama.cpp: chat_template_kwargs, série o da OpenAI: reasoning_effort none, Anthropic: omitir thinking, Google: thinking_budget 0).",
        convos="Diz algo através do Assist. Aparece aqui.",
        evaluator="Escreve como em casa. O passo emoldurado é o que disparou.",
        routines="Um nome falado inicia um script do Home Assistant.",
        sentences="Uma frase para uma intenção conhecida. Depois experimenta.",
        policies="Três pistas. A tua regra de casa ganha primeiro. Experimenta uma frase abaixo.",
        lab="Escreve uma frase, depois Analisar ou Enter.",
    ),
    "ca": guides(
        empty="Cap model d'aquest endpoint. Escriu un id.",
        fail="No s'han pogut llistar els models. Escriu un id.",
        loading="S'estan carregant els models…",
        thinking="Desactivat usa el senyal no-thinking del proveïdor (Lemonade/llama.cpp: chat_template_kwargs, sèrie o d'OpenAI: reasoning_effort none, Anthropic: ometre thinking, Google: thinking_budget 0).",
        convos="Digues alguna cosa via Assist. Apareix aquí.",
        evaluator="Escriu-ho com a casa. El pas emmarcat és el que ha disparat.",
        routines="Un nom parlat inicia un script de Home Assistant.",
        sentences="Una frase cap a una intenció coneguda. Després prova-ho.",
        policies="Tres pistes. La teva regla de casa guanya primer. Prova una frase a sota.",
        lab="Escriu una frase, després Analitza o Intro.",
    ),
    "ro": guides(
        empty="Niciun model de la acest endpoint. Tastează un id.",
        fail="Nu s-au putut lista modelele. Tastează un id.",
        loading="Se încarcă modelele…",
        thinking="Oprit folosește steagul no-thinking al furnizorului (Lemonade/llama.cpp: chat_template_kwargs, seria o OpenAI: reasoning_effort none, Anthropic: omite thinking, Google: thinking_budget 0).",
        convos="Spune ceva prin Assist. Apare aici.",
        evaluator="Tastează ca acasă. Pasul încadrat e cel care s-a declanșat.",
        routines="Un nume rostit pornește un script Home Assistant.",
        sentences="O frază către o intenție cunoscută. Apoi încearcă.",
        policies="Trei piste. Regula ta de casă câștigă prima. Încearcă o frază mai jos.",
        lab="Tastează o frază, apoi Analizează sau Enter.",
    ),
    "pt-BR": guides(
        empty="Nenhum modelo deste endpoint. Digite um id.",
        fail="Não foi possível listar os modelos. Digite um id.",
        loading="Carregando modelos…",
        thinking="Desligado usa o sinalizador no-thinking do provedor (Lemonade/llama.cpp: chat_template_kwargs, série o da OpenAI: reasoning_effort none, Anthropic: omitir thinking, Google: thinking_budget 0).",
        convos="Diga algo pelo Assist. Aparece aqui.",
        evaluator="Digite como em casa. O passo emoldurado é o que disparou.",
        routines="Um nome falado inicia um script do Home Assistant.",
        sentences="Uma frase para uma intenção conhecida. Depois experimente.",
        policies="Três pistas. Sua regra da casa ganha primeiro. Experimente uma frase abaixo.",
        lab="Digite uma frase, depois Analisar ou Enter.",
    ),
    "gl": guides(
        empty="Sen modelos deste endpoint. Escribe un id.",
        fail="Non se puideron listar os modelos. Escribe un id.",
        loading="Cargando modelos…",
        thinking="Desactivado usa a bandeira no-thinking do provedor (Lemonade/llama.cpp: chat_template_kwargs, serie o de OpenAI: reasoning_effort none, Anthropic: omitir thinking, Google: thinking_budget 0).",
        convos="Di algo a través de Assist. Aparece aquí.",
        evaluator="Escríbeo como na casa. O paso enmarcado é o que disparou.",
        routines="Un nome falado inicia un script de Home Assistant.",
        sentences="Unha frase cara a unha intención coñecida. Logo próbao.",
        policies="Tres raias. A túa regra da casa gaña primeiro. Proba unha frase abaixo.",
        lab="Escribe unha frase, logo Analizar ou Enter.",
    ),
}
