"""Page-guide chrome for East and Southeast Asian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_guides import guides

PACKS: dict[str, dict[str, str]] = {
    "zh-CN": guides(
        empty="此端点没有模型。请输入 id。",
        fail="无法列出模型。请输入 id。",
        loading="正在加载模型…",
        thinking="关闭时使用各提供方的 no-thinking 标志（Lemonade/llama.cpp：chat_template_kwargs，OpenAI o 系列：reasoning_effort none，Anthropic：省略 thinking，Google：thinking_budget 0）。",
        convos="通过 Assist 说一句。它会显示在这里。",
        evaluator="像在家里那样输入。带框的步骤就是触发的那一步。",
        routines="说出的名称会启动 Home Assistant 脚本。",
        sentences="一句话对应已知意图。然后试一下。",
        policies="三条通道。你家规优先。再在下方试一句。",
        lab="输入一句话，然后点分析或按 Enter。",
    ),
    "zh-TW": guides(
        empty="此端點沒有模型。請輸入 id。",
        fail="無法列出模型。請輸入 id。",
        loading="正在載入模型…",
        thinking="關閉時使用各提供方的 no-thinking 旗標（Lemonade/llama.cpp：chat_template_kwargs，OpenAI o 系列：reasoning_effort none，Anthropic：省略 thinking，Google：thinking_budget 0）。",
        convos="透過 Assist 說一句。它會顯示在這裡。",
        evaluator="像在家裡那樣輸入。加框的步驟就是觸發的那一步。",
        routines="說出的名稱會啟動 Home Assistant 指令碼。",
        sentences="一句話對應已知意圖。然後試一下。",
        policies="三條通道。你家規優先。再在下方試一句。",
        lab="輸入一句話，然後點分析或按 Enter。",
    ),
    "zh-HK": guides(
        empty="呢個端點冇模型。輸入 id。",
        fail="列唔到模型。輸入 id。",
        loading="載入緊模型…",
        thinking="關閉會用各供應商嘅 no-thinking 旗標（Lemonade/llama.cpp：chat_template_kwargs，OpenAI o 系列：reasoning_effort none，Anthropic：省略 thinking，Google：thinking_budget 0）。",
        convos="透過 Assist 講一句。佢會喺呢度顯示。",
        evaluator="好似喺屋企咁輸入。加框嘅步驟就係觸發嗰步。",
        routines="講出嚟嘅名稱會啟動 Home Assistant 指令碼。",
        sentences="一句對應已知意圖。然後試吓。",
        policies="三條通道。你嘅屋企規則優先。再喺下面試一句。",
        lab="輸入一句，然後撳分析或 Enter。",
    ),
    "ja": guides(
        empty="このエンドポイントからモデルがありません。id を入力してください。",
        fail="モデルを一覧できませんでした。id を入力してください。",
        loading="モデルを読み込み中…",
        thinking="オフは各プロバイダーの no-thinking フラグを使います（Lemonade/llama.cpp: chat_template_kwargs、OpenAI o シリーズ: reasoning_effort none、Anthropic: thinking を省略、Google: thinking_budget 0）。",
        convos="Assist で何か話してください。ここに表示されます。",
        evaluator="家で言うように入力。枠付きの段階が発火した段階です。",
        routines="話した名前で Home Assistant のスクリプトが始まります。",
        sentences="既知の意図に一文。それから試す。",
        policies="三つの経路。家のルールが先に勝つ。下で文を試す。",
        lab="文を入力し、解析または Enter。",
    ),
    "ko": guides(
        empty="이 엔드포인트에서 모델이 없습니다. id를 입력하세요.",
        fail="모델을 나열하지 못했습니다. id를 입력하세요.",
        loading="모델 불러오는 중…",
        thinking="끄면 각 제공자의 no-thinking 플래그를 씁니다(Lemonade/llama.cpp: chat_template_kwargs, OpenAI o 시리즈: reasoning_effort none, Anthropic: thinking 생략, Google: thinking_budget 0).",
        convos="Assist로 말해 보세요. 여기에 나타납니다.",
        evaluator="집에서처럼 입력하세요. 테두리 친 단계가 발화한 단계입니다.",
        routines="말한 이름이 Home Assistant 스크립트를 시작합니다.",
        sentences="알려진 의도에 문장 하나. 그다음 시험하세요.",
        policies="세 경로. 집 규칙이 먼저 이깁니다. 아래에서 문장을 시험하세요.",
        lab="문장을 입력한 뒤 분석 또는 Enter.",
    ),
    "th": guides(
        empty="ไม่มีโมเดลจาก endpoint นี้ พิมพ์ id",
        fail="แสดงรายการโมเดลไม่ได้ พิมพ์ id",
        loading="กำลังโหลดโมเดล…",
        thinking="ปิดจะใช้ธง no-thinking ของผู้ให้บริการ (Lemonade/llama.cpp: chat_template_kwargs, ซีรีส์ o ของ OpenAI: reasoning_effort none, Anthropic: ละ thinking, Google: thinking_budget 0)",
        convos="พูดอะไรสักอย่างผ่าน Assist แล้วจะโผล่ที่นี่",
        evaluator="พิมพ์อย่างที่พูดที่บ้าน ขั้นที่กรอบไว้คือขั้นที่ทำงาน",
        routines="ชื่อที่พูดจะเริ่มสคริปต์ Home Assistant",
        sentences="ประโยคเดียวสู่เจตนาที่รู้จัก แล้วลอง",
        policies="สามช่อง กฎบ้านคุณชนะก่อน แล้วลองประโยคด้านล่าง",
        lab="พิมพ์ประโยค แล้ววิเคราะห์ หรือ Enter",
    ),
    "vi": guides(
        empty="Không có mô hình từ endpoint này. Gõ một id.",
        fail="Không liệt kê được mô hình. Gõ một id.",
        loading="Đang tải mô hình…",
        thinking="Tắt dùng cờ no-thinking của nhà cung cấp (Lemonade/llama.cpp: chat_template_kwargs, dòng o OpenAI: reasoning_effort none, Anthropic: bỏ thinking, Google: thinking_budget 0).",
        convos="Nói gì đó qua Assist. Nó hiện ở đây.",
        evaluator="Gõ như ở nhà. Bước có khung là bước đã kích hoạt.",
        routines="Tên nói ra khởi chạy tập lệnh Home Assistant.",
        sentences="Một câu vào ý định đã biết. Rồi thử.",
        policies="Ba làn. Luật nhà bạn thắng trước. Thử một câu bên dưới.",
        lab="Gõ một câu, rồi Phân tích hoặc Enter.",
    ),
    "id": guides(
        empty="Tidak ada model dari endpoint ini. Ketik sebuah id.",
        fail="Tidak bisa menampilkan model. Ketik sebuah id.",
        loading="Memuat model…",
        thinking="Mati memakai bendera no-thinking penyedia (Lemonade/llama.cpp: chat_template_kwargs, seri o OpenAI: reasoning_effort none, Anthropic: hilangkan thinking, Google: thinking_budget 0).",
        convos="Ucapkan sesuatu lewat Assist. Muncul di sini.",
        evaluator="Ketik seperti di rumah. Langkah berbingkai adalah yang terpicu.",
        routines="Nama yang diucapkan memulai skrip Home Assistant.",
        sentences="Satu kalimat ke niat yang dikenal. Lalu coba.",
        policies="Tiga jalur. Aturan rumahmu menang dulu. Coba kalimat di bawah.",
        lab="Ketik kalimat, lalu Analisis atau Enter.",
    ),
    "ms": guides(
        empty="Tiada model dari titik hujung ini. Taip id.",
        fail="Tidak dapat menyenaraikan model. Taip id.",
        loading="Memuatkan model…",
        thinking="Mati menggunakan bendera no-thinking penyedia (Lemonade/llama.cpp: chat_template_kwargs, siri o OpenAI: reasoning_effort none, Anthropic: tinggal thinking, Google: thinking_budget 0).",
        convos="Cakap sesuatu melalui Assist. Ia muncul di sini.",
        evaluator="Taip seperti di rumah. Langkah berbingkai ialah yang terpicu.",
        routines="Nama disebut memulakan skrip Home Assistant.",
        sentences="Satu ayat ke niat yang diketahui. Kemudian cuba.",
        policies="Tiga lorong. Peraturan rumah anda menang dahulu. Cuba ayat di bawah.",
        lab="Taip ayat, kemudian Analisis atau Enter.",
    ),
    "mn": guides(
        empty="Энэ төгсгөлөөс модель алга. id бичнэ үү.",
        fail="Модель жагсааж чадсангүй. id бичнэ үү.",
        loading="Модель ачааллаж байна…",
        thinking="Унтраалт нь нийлүүлэгчийн no-thinking туг ашиглана (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o цуврал: reasoning_effort none, Anthropic: thinking алгасах, Google: thinking_budget 0).",
        convos="Assist-ээр ямар нэгэн зүйл хэл. Энд гарна.",
        evaluator="Гэртээ байгаа шиг бич. Хүрээтэй алхам нь ажилласан нь.",
        routines="Хэлсэн нэр Home Assistant скриптийг эхлүүлнэ.",
        sentences="Мэдэгдэх зорилгод нэг өгүүлбэр. Дараа нь турш.",
        policies="Гурван зам. Таны гэрийн дүрэм түрүүнд хожно. Доор өгүүлбэр турш.",
        lab="Өгүүлбэр бичээд Шинжлэх эсвэл Enter.",
    ),
}
