"""Custom-voice and interview chrome for East and Southeast Asian Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice

PACKS: dict[str, dict[str, str]] = {
    "zh-CN": voice(
        personalityCustom="自定义语音",
        customVoice="自定义语音",
        customVoiceHint="种子决定角色。滑块只微调说话方式。语言锁定和安全规则保留。",
        customVoiceMake="用种子和滑块写语音",
        customVoiceFail="未能写入语音。请检查 LLM。",
        customVoiceName="语音名称",
        customVoiceNameHint="此人格在列表中的显示名称。",
        customVoiceSeed="种子提示",
        customVoiceSeedHint="Klar 应成为谁，与滑块无关。例如：你是《星际迷航》里的斯波克。",
        interviewTraitsHint="0 = 关，10 = 强。只影响说话方式，不影响角色。",
        interviewWarmth="温度",
        interviewSarcasm="讽刺",
        interviewFormality="正式",
        interviewVerbosity="详细",
        interviewEnergy="活力",
        interviewAddress="Klar 该怎么称呼你？",
        interviewAddressDu="你",
        interviewAddressSie="您",
        interviewAddressName="名字",
        interviewName="名称",
        interviewTone="语气",
        interviewToneShort="短",
        interviewToneWarm="温暖",
        interviewToneDry="干",
        interviewHumor="幽默",
        interviewHumorNone="无",
        interviewHumorLight="轻",
        interviewHumorSharp="锐",
        interviewLength="长度",
        interviewLengthOne="一句话",
        interviewLengthMore="再多一点",
        interviewTaboo="不要说",
    ),
    "zh-TW": voice(
        personalityCustom="自訂語音",
        customVoice="自訂語音",
        customVoiceHint="種子決定角色。滑桿只微調說話方式。語言鎖定與安全規則保留。",
        customVoiceMake="用種子和滑桿寫語音",
        customVoiceFail="無法寫入語音。請檢查 LLM。",
        customVoiceName="語音名稱",
        customVoiceNameHint="此人設在清單中的顯示名稱。",
        customVoiceSeed="種子提示",
        customVoiceSeedHint="Klar 應成為誰，與滑桿無關。例如：你是《星際迷航》裡的史波克。",
        interviewTraitsHint="0 = 關，10 = 強。只影響說話方式，不影響角色。",
        interviewWarmth="溫度",
        interviewSarcasm="諷刺",
        interviewFormality="正式",
        interviewVerbosity="詳細",
        interviewEnergy="活力",
        interviewAddress="Klar 該怎麼稱呼你？",
        interviewAddressDu="你",
        interviewAddressSie="您",
        interviewAddressName="名字",
        interviewName="名稱",
        interviewTone="語氣",
        interviewToneShort="短",
        interviewToneWarm="溫暖",
        interviewToneDry="乾",
        interviewHumor="幽默",
        interviewHumorNone="無",
        interviewHumorLight="輕",
        interviewHumorSharp="銳",
        interviewLength="長度",
        interviewLengthOne="一句話",
        interviewLengthMore="再多一點",
        interviewTaboo="不要說",
    ),
    "zh-HK": voice(
        personalityCustom="自訂聲線",
        customVoice="自訂聲線",
        customVoiceHint="種子決定角色。滑桿淨係微調講嘢方式。語言鎖定同安全規則留住。",
        customVoiceMake="用種子同滑桿寫聲線",
        customVoiceFail="寫唔到聲線。檢查 LLM。",
        customVoiceName="聲線名稱",
        customVoiceNameHint="呢個人設喺清單點樣顯示。",
        customVoiceSeed="種子提示",
        customVoiceSeedHint="Klar 應該係邊個，同滑桿無關。例如：你係《星際迷航》嘅史波克。",
        interviewTraitsHint="0 = 關，10 = 強。淨係影響講嘢，唔影響角色。",
        interviewWarmth="溫度",
        interviewSarcasm="諷刺",
        interviewFormality="正式",
        interviewVerbosity="詳細",
        interviewEnergy="活力",
        interviewAddress="Klar 應該點稱呼你？",
        interviewAddressDu="你",
        interviewAddressSie="您",
        interviewAddressName="名",
        interviewName="名稱",
        interviewTone="語氣",
        interviewToneShort="短",
        interviewToneWarm="溫暖",
        interviewToneDry="乾",
        interviewHumor="幽默",
        interviewHumorNone="無",
        interviewHumorLight="輕",
        interviewHumorSharp="銳",
        interviewLength="長度",
        interviewLengthOne="一句",
        interviewLengthMore="再多啲",
        interviewTaboo="唔好講",
    ),
    "ja": voice(
        personalityCustom="独自の声",
        customVoice="独自の声",
        customVoiceHint="Seed がキャラを決める。スライダーは話し方だけ整える。言語ロックと安全ルールはそのまま。",
        customVoiceMake="Seed とスライダーから声を書く",
        customVoiceFail="声を書けませんでした。LLM を確認。",
        customVoiceName="声の名前",
        customVoiceNameHint="この人格が一覧にどう出るか。",
        customVoiceSeed="Seed プロンプト",
        customVoiceSeedHint="スライダーとは別に、Klar が誰であるか。例：あなたはスタートレックのスポックです。",
        interviewTraitsHint="0 = オフ、10 = 強い。話し方だけ。キャラは変えない。",
        interviewWarmth="温かさ",
        interviewSarcasm="皮肉",
        interviewFormality="改まり",
        interviewVerbosity="詳しさ",
        interviewEnergy="勢い",
        interviewAddress="Klar はどう呼びかけますか？",
        interviewAddressDu="ため口",
        interviewAddressSie="敬語",
        interviewAddressName="名前",
        interviewName="名称",
        interviewTone="口調",
        interviewToneShort="短い",
        interviewToneWarm="温かい",
        interviewToneDry="淡々",
        interviewHumor="ユーモア",
        interviewHumorNone="なし",
        interviewHumorLight="軽め",
        interviewHumorSharp="鋭い",
        interviewLength="長さ",
        interviewLengthOne="一文",
        interviewLengthMore="もう少し",
        interviewTaboo="言わないこと",
    ),
    "ko": voice(
        personalityCustom="직접 만든 음성",
        customVoice="직접 만든 음성",
        customVoiceHint="시드가 캐릭터를 정합니다. 슬라이더는 말투만 다듬습니다. 언어 잠금과 안전 규칙은 유지됩니다.",
        customVoiceMake="시드와 슬라이더로 음성 작성",
        customVoiceFail="음성을 쓰지 못했습니다. LLM을 확인하세요.",
        customVoiceName="음성 이름",
        customVoiceNameHint="이 성격이 목록에 어떻게 보이는지.",
        customVoiceSeed="시드 프롬프트",
        customVoiceSeedHint="슬라이더와 별개로 Klar가 누구여야 하는지. 예: 당신은 스타트렉의 스폭입니다.",
        interviewTraitsHint="0 = 끔, 10 = 강함. 말투만, 캐릭터는 아님.",
        interviewWarmth="따뜻함",
        interviewSarcasm="풍자",
        interviewFormality="격식",
        interviewVerbosity="장황함",
        interviewEnergy="에너지",
        interviewAddress="Klar가 어떻게 부를까요?",
        interviewAddressDu="반말",
        interviewAddressSie="존댓말",
        interviewAddressName="이름",
        interviewName="이름",
        interviewTone="어조",
        interviewToneShort="짧게",
        interviewToneWarm="따뜻하게",
        interviewToneDry="건조하게",
        interviewHumor="유머",
        interviewHumorNone="없음",
        interviewHumorLight="가볍게",
        interviewHumorSharp="날카롭게",
        interviewLength="길이",
        interviewLengthOne="한 문장",
        interviewLengthMore="조금 더",
        interviewTaboo="말하지 말 것",
    ),
    "th": voice(
        personalityCustom="เสียงกำหนดเอง",
        customVoice="เสียงกำหนดเอง",
        customVoiceHint="ซีดกำหนดตัวละคร แถบเลื่อนปรับเฉพาะวิธีพูด ล็อกภาษาและกฎความปลอดภัยยังอยู่",
        customVoiceMake="เขียนเสียงจากซีดและแถบเลื่อน",
        customVoiceFail="เขียนเสียงไม่ได้ ตรวจ LLM",
        customVoiceName="ชื่อเสียง",
        customVoiceNameHint="บุคลิกนี้แสดงในรายการอย่างไร",
        customVoiceSeed="พรอมต์ซีด",
        customVoiceSeedHint="Klar ควรเป็นใคร โดยไม่ขึ้นกับแถบเลื่อน เช่น คุณคือสป็อคจากสตาร์เทรค",
        interviewTraitsHint="0 = ปิด, 10 = แรง เฉพาะการพูด ไม่ใช่ตัวละคร",
        interviewWarmth="ความอบอุ่น",
        interviewSarcasm="เสียดสี",
        interviewFormality="ความเป็นทางการ",
        interviewVerbosity="ความยาวพูด",
        interviewEnergy="พลัง",
        interviewAddress="Klar ควรเรียกคุณอย่างไร?",
        interviewAddressDu="คุณ (กันเอง)",
        interviewAddressSie="คุณ (สุภาพ)",
        interviewAddressName="ชื่อ",
        interviewName="ชื่อ",
        interviewTone="น้ำเสียง",
        interviewToneShort="สั้น",
        interviewToneWarm="อบอุ่น",
        interviewToneDry="แห้ง",
        interviewHumor="อารมณ์ขัน",
        interviewHumorNone="ไม่มี",
        interviewHumorLight="เบา",
        interviewHumorSharp="คม",
        interviewLength="ความยาว",
        interviewLengthOne="หนึ่งประโยค",
        interviewLengthMore="อีกนิด",
        interviewTaboo="ห้ามพูด",
    ),
    "vi": voice(
        personalityCustom="Giọng riêng",
        customVoice="Giọng riêng",
        customVoiceHint="Seed đặt nhân vật. Thanh trượt chỉ tinh chỉnh cách nói. Khóa ngôn ngữ và quy tắc an toàn giữ nguyên.",
        customVoiceMake="Viết giọng từ seed và thanh trượt",
        customVoiceFail="Không viết được giọng. Kiểm tra LLM.",
        customVoiceName="Tên giọng",
        customVoiceNameHint="Cách tính cách này hiện trên danh sách.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Klar phải là ai, không phụ thuộc thanh trượt. Ví dụ: Bạn là Spock trong Star Trek.",
        interviewTraitsHint="0 = tắt, 10 = mạnh. Chỉ cách nói, không phải nhân vật.",
        interviewWarmth="Ấm",
        interviewSarcasm="Mỉa mai",
        interviewFormality="Trang trọng",
        interviewVerbosity="Dài lời",
        interviewEnergy="Năng lượng",
        interviewAddress="Klar nên xưng hô với bạn thế nào?",
        interviewAddressDu="Bạn",
        interviewAddressSie="Quý vị",
        interviewAddressName="Tên",
        interviewName="Tên",
        interviewTone="Giọng điệu",
        interviewToneShort="Ngắn",
        interviewToneWarm="Ấm",
        interviewToneDry="Khô",
        interviewHumor="Hài",
        interviewHumorNone="Không",
        interviewHumorLight="Nhẹ",
        interviewHumorSharp="Sắc",
        interviewLength="Độ dài",
        interviewLengthOne="Một câu",
        interviewLengthMore="Thêm một chút",
        interviewTaboo="Đừng nói",
    ),
    "id": voice(
        personalityCustom="Suara kustom",
        customVoice="Suara kustom",
        customVoiceHint="Seed menetapkan karakter. Penggeser hanya merapikan cara bicara. Kunci bahasa dan aturan keamanan tetap.",
        customVoiceMake="Tulis suara dari seed dan penggeser",
        customVoiceFail="Tidak bisa menulis suara. Periksa LLM.",
        customVoiceName="Nama suara",
        customVoiceNameHint="Bagaimana kepribadian ini tampil di daftar.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Siapa Klar seharusnya, terlepas dari penggeser. Contoh: Kau adalah Spock dari Star Trek.",
        interviewTraitsHint="0 = mati, 10 = kuat. Hanya penyampaian, bukan karakter.",
        interviewWarmth="Kehangatan",
        interviewSarcasm="Sarkasme",
        interviewFormality="Formalitas",
        interviewVerbosity="Kelengkapan kata",
        interviewEnergy="Energi",
        interviewAddress="Bagaimana Klar harus menyapamu?",
        interviewAddressDu="Kamu",
        interviewAddressSie="Anda",
        interviewAddressName="Nama depan",
        interviewName="Nama",
        interviewTone="Nada",
        interviewToneShort="Pendek",
        interviewToneWarm="Hangat",
        interviewToneDry="Kering",
        interviewHumor="Humor",
        interviewHumorNone="Tidak ada",
        interviewHumorLight="Ringan",
        interviewHumorSharp="Tajam",
        interviewLength="Panjang",
        interviewLengthOne="Satu kalimat",
        interviewLengthMore="Sedikit lagi",
        interviewTaboo="Jangan ucapkan",
    ),
    "ms": voice(
        personalityCustom="Suara tersuai",
        customVoice="Suara tersuai",
        customVoiceHint="Seed menetapkan watak. Peluncur hanya memperhalusi cara bercakap. Kunci bahasa dan peraturan keselamatan kekal.",
        customVoiceMake="Tulis suara daripada seed dan peluncur",
        customVoiceFail="Tidak dapat menulis suara. Semak LLM.",
        customVoiceName="Nama suara",
        customVoiceNameHint="Bagaimana personaliti ini muncul dalam senarai.",
        customVoiceSeed="Prom seed",
        customVoiceSeedHint="Siapa Klar sepatutnya, tanpa peluncur. Contoh: Awak ialah Spock dari Star Trek.",
        interviewTraitsHint="0 = mati, 10 = kuat. Hanya penyampaian, bukan watak.",
        interviewWarmth="Kehangatan",
        interviewSarcasm="Sarkasme",
        interviewFormality="Keformalan",
        interviewVerbosity="Panjang kata",
        interviewEnergy="Tenaga",
        interviewAddress="Bagaimana Klar patut menyapa anda?",
        interviewAddressDu="Awak",
        interviewAddressSie="Anda",
        interviewAddressName="Nama pertama",
        interviewName="Nama",
        interviewTone="Nada",
        interviewToneShort="Pendek",
        interviewToneWarm="Hangat",
        interviewToneDry="Kering",
        interviewHumor="Humor",
        interviewHumorNone="Tiada",
        interviewHumorLight="Ringan",
        interviewHumorSharp="Tajam",
        interviewLength="Panjang",
        interviewLengthOne="Satu ayat",
        interviewLengthMore="Sikit lagi",
        interviewTaboo="Jangan sebut",
    ),
    "mn": voice(
        personalityCustom="Өөрийн дуу",
        customVoice="Өөрийн дуу",
        customVoiceHint="Seed дүрийг тогтооно. Гулсуур зөвхөн ярианы хэлбэрийг нарийсгана. Хэлний цоож, аюулгүй байдлын дүрэм үлдэнэ.",
        customVoiceMake="Seed болон гулсуураас дуу бичих",
        customVoiceFail="Дуу бичигдсэнгүй. LLM-г шалга.",
        customVoiceName="Дууны нэр",
        customVoiceNameHint="Энэ зан чанар жагсаалтад ингэж харагдана.",
        customVoiceSeed="Seed сануулга",
        customVoiceSeedHint="Klar хэн байх ёстой, гулсуураас хамаарахгүй. Жишээ: Чи Star Trek-ийн Спок.",
        interviewTraitsHint="0 = унтраалттай, 10 = хүчтэй. Зөвхөн яриа, дүр биш.",
        interviewWarmth="Дулаан",
        interviewSarcasm="Егөө",
        interviewFormality="Албан ёсны",
        interviewVerbosity="Дэлгэрэнгүй",
        interviewEnergy="Эрчим",
        interviewAddress="Klar чамайг яаж дуудах вэ?",
        interviewAddressDu="Чи",
        interviewAddressSie="Та",
        interviewAddressName="Нэр",
        interviewName="Нэр",
        interviewTone="Ая",
        interviewToneShort="Богино",
        interviewToneWarm="Дулаахан",
        interviewToneDry="Хуурай",
        interviewHumor="Хошигнол",
        interviewHumorNone="Байхгүй",
        interviewHumorLight="Хөнгөн",
        interviewHumorSharp="Хурц",
        interviewLength="Урт",
        interviewLengthOne="Нэг өгүүлбэр",
        interviewLengthMore="Жаахан илүү",
        interviewTaboo="Бүү хэл",
    ),
}
