"""Page-guide chrome for Central / Insular European Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_guides import guides

PACKS: dict[str, dict[str, str]] = {
    "de-CH": guides(
        empty="Kei Modell vo dem Endpoint. Id tippe.",
        fail="Modell nöd glade. Id tippe.",
        loading="Modell werde glade…",
        thinking="Us brucht s no-thinking vom Aabieter (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-Serie: reasoning_effort none, Anthropic: thinking weglah, Google: thinking_budget 0).",
        convos="Sag öppis über Assist. Denn erschynts da.",
        evaluator="Tipps wie deheim. De Raame zeigt, weli Spur griffe het.",
        routines="En gredte Name startet es Home Assistant Skript.",
        sentences="En Satz uf en bekannte Intent. Denn Probe.",
        policies="Drü Spure. Dini Huusregle gwünnt zerscht. Une en Satz prüefe.",
        lab="Satz tippe, denn Zerlege oder Enter.",
    ),
    "de-AT": guides(
        empty="Keine Modelle von diesem Endpoint. Id eintippen.",
        fail="Modelle nicht geladen. Id eintippen.",
        loading="Modelle werden geladen…",
        thinking="Aus nutzt das no-thinking des Anbieters (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-Serie: reasoning_effort none, Anthropic: thinking weglassen, Google: thinking_budget 0).",
        convos="Sprich einen Satz über Assist. Dann erscheint er hier.",
        evaluator="So wie zu Hause. Der Rahmen zeigt, welche Spur gegriffen hat.",
        routines="Ein gesprochener Name startet ein Home-Assistant-Skript.",
        sentences="Ein Satz auf einen bekannten Intent. Dann Probe.",
        policies="Drei Spuren. Deine Hausregel gewinnt zuerst. Unten einen Satz prüfen.",
        lab="Satz eintippen, dann Zerlegen oder Enter.",
    ),
    "en-GB": guides(
        empty="No models from this endpoint. Type an id.",
        fail="Could not list models. Type an id.",
        loading="Loading models…",
        thinking="Off uses each provider’s no-thinking flag (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-series: reasoning_effort none, Anthropic: omit thinking, Google: thinking_budget 0).",
        convos="Say something through Assist. It shows up here.",
        evaluator="Type it as you would at home. The framed step is the one that fired.",
        routines="A spoken name starts a Home Assistant script.",
        sentences="One sentence onto a known intent. Then try it.",
        policies="Three lanes. Your house rule wins first. Then try a sentence below.",
        lab="Type a sentence, then Analyse or Enter.",
    ),
    "af": guides(
        empty="Geen modelle van hierdie endpoint nie. Tik 'n id.",
        fail="Kon nie modelle lys nie. Tik 'n id.",
        loading="Laai modelle…",
        thinking="Af gebruik die verskaffer se no-thinking-vlag (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-reeks: reasoning_effort none, Anthropic: thinking weglaat, Google: thinking_budget 0).",
        convos="Sê iets deur Assist. Dit verskyn hier.",
        evaluator="Tik dit soos by die huis. Die omraamde stap is dié wat gevuur het.",
        routines="'n Gesproke naam begin 'n Home Assistant-skrip.",
        sentences="Een sin op 'n bekende intent. Probeer dit daarna.",
        policies="Drie bane. Jou huisreël wen eerste. Probeer 'n sin hieronder.",
        lab="Tik 'n sin, dan Ontleed of Enter.",
    ),
    "lb": guides(
        empty="Keng Modeller vun dësem Endpoint. Tippt eng Id.",
        fail="Modeller konnten net geluede ginn. Tippt eng Id.",
        loading="Modeller ginn gelueden…",
        thinking="Aus benotzt de no-thinking-Fändel vum Fournisseur (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-Serie: reasoning_effort none, Anthropic: thinking ewechloossen, Google: thinking_budget 0).",
        convos="Sot eppes iwwer Assist. Dann erschéngt et hei.",
        evaluator="Tippt et wéi doheem. De Rahmen weist, wéi eng Spur gegräift huet.",
        routines="En ausgeschwatenen Numm start e Home Assistant Skript.",
        sentences="Ee Saz op en bekannten Intent. Dann ausprobéieren.",
        policies="Dräi Spuren. Deng Hausregel gewënnt als éischt. Probéier ënnen e Saz.",
        lab="Saz antippen, dann Zerleeën oder Enter.",
    ),
    "cy": guides(
        empty="Dim modelau o'r endpoint hwn. Teipiwch id.",
        fail="Methu rhestru modelau. Teipiwch id.",
        loading="Wrthi'n llwytho modelau…",
        thinking="I ffwrdd mae'n defnyddio baner no-thinking y darparwr (Lemonade/llama.cpp: chat_template_kwargs, cyfres o OpenAI: reasoning_effort none, Anthropic: hepgor thinking, Google: thinking_budget 0).",
        convos="Dywedwch rywbeth trwy Assist. Mae'n ymddangos yma.",
        evaluator="Teipiwch fel gartref. Y cam fframiog yw'r un a daniodd.",
        routines="Mae enw llafar yn cychwyn sgript Home Assistant.",
        sentences="Un frawddeg at fwriad hysbys. Yna rhowch gynnig arni.",
        policies="Tair lôn. Eich rheol tŷ sy'n ennill gyntaf. Rhowch gynnig ar frawddeg isod.",
        lab="Teipiwch frawddeg, yna Dadansoddi neu Enter.",
    ),
    "eu": guides(
        empty="Ez dago modelorik endpoint honetatik. Idatzi id bat.",
        fail="Ezin izan dira modeloak zerrendatu. Idatzi id bat.",
        loading="Modeloak kargatzen…",
        thinking="Itzalita hornitzailearen no-thinking bandera erabiltzen du (Lemonade/llama.cpp: chat_template_kwargs, OpenAI o-seriea: reasoning_effort none, Anthropic: thinking kendu, Google: thinking_budget 0).",
        convos="Esan zerbait Assist bidez. Hemen agertzen da.",
        evaluator="Idatzi etxean bezala. Markoan dagoen urratsa da su egin duena.",
        routines="Izen mintzatu batek Home Assistant script bat abiatzen du.",
        sentences="Esaldi bat asmo ezagun batera. Gero saiatu.",
        policies="Hiru erreil. Zure etxeko arauak irabazten du lehenik. Saiatu esaldi bat behean.",
        lab="Idatzi esaldi bat, gero Aztertu edo Enter.",
    ),
    "ga": guides(
        empty="Níl aon mhúnla ón endpoint seo. Clóscríobh id.",
        fail="Níorbh fhéidir múnlaí a liostáil. Clóscríobh id.",
        loading="Múnlaí á lódáil…",
        thinking="Úsáideann Off bratach no-thinking an tsoláthraí (Lemonade/llama.cpp: chat_template_kwargs, sraith o OpenAI: reasoning_effort none, Anthropic: fág thinking ar lár, Google: thinking_budget 0).",
        convos="Abair rud éigin trí Assist. Taispeánann sé anseo.",
        evaluator="Clóscríobh é mar a dhéanfá sa bhaile. Is é an chéim fhrámaithe an ceann a scaoil.",
        routines="Tosaíonn ainm labhartha script Home Assistant.",
        sentences="Abairt amháin ar rún aitheanta. Ansin bain triail as.",
        policies="Trí lána. Buaileann do riail tí ar dtús. Bain triail as abairt thíos.",
        lab="Clóscríobh abairt, ansin Déan anailís nó Enter.",
    ),
    "kw": guides(
        empty="Nyns eus modelow dhyworth an penn-hyns ma. Jynnskrif id.",
        fail="Ny yllir rolya modelow. Jynnskrif id.",
        loading="Ow karga modelow…",
        thinking="Degeys a us baner no-thinking an pourveyas (Lemonade/llama.cpp: chat_template_kwargs, kevres o OpenAI: reasoning_effort none, Anthropic: gas thinking, Google: thinking_budget 0).",
        convos="Leverewgh neppyth dre Assist. Diskwedh ev omma.",
        evaluator="Jynnskrifewgh ev kepar hag y'n chi. An kamm framys yw an huni a dennas.",
        routines="Hanow kewsys a dhalleth skript Home Assistant.",
        sentences="Onan lavar war intent aswonnys. Ena previ.",
        policies="Teyr hyns. Dha rewl chi a wayn kynsa. Previ lavar a-woles.",
        lab="Jynnskrifewgh lavar, ena Analysya po Enter.",
    ),
}
