"""Custom-voice and interview chrome for MENA and neighbouring Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice
from lang_packs.web_ui_voice_mena_east import PACKS as EAST


PACKS: dict[str, dict[str, str]] = {
    'ar': voice(
        personalityCustom='صوت مخصص',
        customVoice='صوت مخصص',
        customVoiceHint='البذرة تحدد الشخصية. المنزلقات تصقل طريقة الكلام فقط. قفل اللغة وقواعد السلامة تبقى.',
        customVoiceMake='اكتب الصوت من البذرة والمنزلقات',
        customVoiceFail='تعذر كتابة صوت. تحقق من LLM.',
        customVoiceName='اسم الصوت',
        customVoiceNameHint='كيف تظهر هذه الشخصية في القائمة.',
        customVoiceSeed='موجه البذرة',
        customVoiceSeedHint='من يجب أن يكون Klar، بمعزل عن المنزلقات. مثال: أنت سبوك من ستار تريك.',
        interviewTraitsHint='0 = إيقاف، 10 = قوي. طريقة الإلقاء فقط، لا الشخصية.',
        interviewWarmth='دفء',
        interviewSarcasm='سخرية',
        interviewFormality='رسمية',
        interviewVerbosity='إطالة',
        interviewEnergy='طاقة',
        interviewAddress='كيف يخاطبك Klar؟',
        interviewAddressDu='أنت (غير رسمي)',
        interviewAddressSie='أنت (رسمي)',
        interviewAddressName='الاسم الأول',
        interviewName='الاسم',
        interviewTone='نبرة',
        interviewToneShort='قصير',
        interviewToneWarm='دافئ',
        interviewToneDry='جاف',
        interviewHumor='فكاهة',
        interviewHumorNone='بلا',
        interviewHumorLight='خفيف',
        interviewHumorSharp='حاد',
        interviewLength='طول',
        interviewLengthOne='جملة واحدة',
        interviewLengthMore='قليل زيادة',
        interviewTaboo='لا تقل',
    ),
    'he': voice(
        personalityCustom='קול מותאם',
        customVoice='קול מותאם',
        customVoiceHint='הזרע קובע את הדמות. המחוונים רק מלטשים את אופן הדיבור. נעילת שפה וכללי בטיחות נשארים.',
        customVoiceMake='כתוב קול מהזרע והמחוונים',
        customVoiceFail='לא ניתן לכתוב קול. בדוק את ה-LLM.',
        customVoiceName='שם הקול',
        customVoiceNameHint='איך האישיות הזו מופיעה ברשימה.',
        customVoiceSeed='הנחיית זרע',
        customVoiceSeedHint='מי Klar צריך להיות, בלי תלות במחוונים. לדוגמה: אתה ספוק מסטאר טרק.',
        interviewTraitsHint='0 = כבוי, 10 = חזק. רק המסירה, לא הדמות.',
        interviewWarmth='חום',
        interviewSarcasm='סרקזם',
        interviewFormality='רשמיות',
        interviewVerbosity='פירוט',
        interviewEnergy='אנרגיה',
        interviewAddress='איך Klar צריך לפנות אליך?',
        interviewAddressDu='אתה',
        interviewAddressSie='כבוד',
        interviewAddressName='שם פרטי',
        interviewName='שם',
        interviewTone='טון',
        interviewToneShort='קצר',
        interviewToneWarm='חם',
        interviewToneDry='יבש',
        interviewHumor='הומור',
        interviewHumorNone='בלי',
        interviewHumorLight='קל',
        interviewHumorSharp='חד',
        interviewLength='אורך',
        interviewLengthOne='משפט אחד',
        interviewLengthMore='קצת יותר',
        interviewTaboo='אל תגיד',
    ),
    'fa': voice(
        personalityCustom='صدای سفارشی',
        customVoice='صدای سفارشی',
        customVoiceHint='بذر شخصیت را تعیین می کند. لغزنده ها فقط شیوه سخن را می پردازند. قفل زبان و قواعد ایمنی می مانند.',
        customVoiceMake='صدا را از بذر و لغزنده ها بنویس',
        customVoiceFail='نتوانست صدا بنویسد. LLM را بررسی کن.',
        customVoiceName='نام صدا',
        customVoiceNameHint='این شخصیت در فهرست چگونه دیده می شود.',
        customVoiceSeed='اعلان بذر',
        customVoiceSeedHint='Klar باید که باشد، جدا از لغزنده ها. مثلا: تو اسپاک از پیشتازان فضا هستی.',
        interviewTraitsHint='0 = خاموش، 10 = قوی. فقط بیان، نه شخصیت.',
        interviewWarmth='گرمی',
        interviewSarcasm='طعنه',
        interviewFormality='رسمیت',
        interviewVerbosity='پرحرفی',
        interviewEnergy='انرژی',
        interviewAddress='Klar چطور باید خطاب کند؟',
        interviewAddressDu='تو',
        interviewAddressSie='شما',
        interviewAddressName='نام',
        interviewName='نام',
        interviewTone='لحن',
        interviewToneShort='کوتاه',
        interviewToneWarm='گرم',
        interviewToneDry='خشک',
        interviewHumor='شوخ طبعی',
        interviewHumorNone='هیچ',
        interviewHumorLight='ملایم',
        interviewHumorSharp='تیز',
        interviewLength='طول',
        interviewLengthOne='یک جمله',
        interviewLengthMore='کمی بیشتر',
        interviewTaboo='نگو',
    ),
    'ur': voice(
        personalityCustom='حسب ضرورت آواز',
        customVoice='حسب ضرورت آواز',
        customVoiceHint='بیج کردار متعین کرتا ہے۔ سلائیڈر صرف بول چال سنوارتے ہیں۔ زبان کا تالا اور حفاظتی قواعد رہتے ہیں۔',
        customVoiceMake='بیج اور سلائیڈر سے آواز لکھو',
        customVoiceFail='آواز نہیں لکھی جا سکی۔ LLM چیک کریں۔',
        customVoiceName='آواز کا نام',
        customVoiceNameHint='یہ شخصیت فہرست میں کیسے دکھتی ہے۔',
        customVoiceSeed='بیج پرامپٹ',
        customVoiceSeedHint='Klar کون ہو، سلائیڈر سے الگ۔ مثال: آپ اسٹار ٹریک کے سپاک ہیں۔',
        interviewTraitsHint='0 = بند، 10 = مضبوط۔ صرف ادا، کردار نہیں۔',
        interviewWarmth='گرمی',
        interviewSarcasm='طعن',
        interviewFormality='رسمیت',
        interviewVerbosity='طول کلام',
        interviewEnergy='توانائی',
        interviewAddress='Klar آپ کو کیسے پکارے؟',
        interviewAddressDu='تم',
        interviewAddressSie='آپ',
        interviewAddressName='نام',
        interviewName='نام',
        interviewTone='لہجہ',
        interviewToneShort='مختصر',
        interviewToneWarm='گرم',
        interviewToneDry='خشک',
        interviewHumor='مزاح',
        interviewHumorNone='کوئی نہیں',
        interviewHumorLight='ہلکا',
        interviewHumorSharp='تیز',
        interviewLength='طول',
        interviewLengthOne='ایک جملہ',
        interviewLengthMore='ذرا زیادہ',
        interviewTaboo='مت کہو',
    ),
}
PACKS.update(EAST)
