"""Custom-voice and interview chrome for Central / Insular European Assist locales."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice

PACKS: dict[str, dict[str, str]] = {
    "de-CH": voice(
        personalityCustom="Eigeni Stimm",
        customVoice="Eigeni Stimm",
        customVoiceHint="Seed legt d Figur fescht. Slider verfiinered nume d Art z rede. Language-Lock und Safety-Rules bliibed.",
        customVoiceMake="Stimm us Seed und Slider schriibe",
        customVoiceFail="Stimm nöd gschribe. LLM prüefe.",
        customVoiceName="Name vo de Stimm",
        customVoiceNameHint="So heisst die Persönlichkeit i de Liste.",
        customVoiceSeed="Seed-Prompt",
        customVoiceSeedHint="Wer Klar si söll, unabhängig vo de Slider. Zum Biispil: Du bisch Spock us Star Trek.",
        interviewTraitsHint="0 = uus, 10 = starch. Wirkt nume uf d Sprochart, nöd uf d Figur.",
        interviewWarmth="Wermi",
        interviewSarcasm="Sarkasmus",
        interviewFormality="Förmlichkeit",
        interviewVerbosity="Uusführlichkeit",
        interviewEnergy="Energie",
        interviewAddress="Wie söll Klar di aarede?",
        interviewAddressDu="Du",
        interviewAddressSie="Sie",
        interviewAddressName="Vorname",
        interviewName="Name",
        interviewTone="Ton",
        interviewToneShort="Churz",
        interviewToneWarm="Warm",
        interviewToneDry="Trocke",
        interviewHumor="Humor",
        interviewHumorNone="Keine",
        interviewHumorLight="Liecht",
        interviewHumorSharp="Spitz",
        interviewLength="Lengi",
        interviewLengthOne="En Satz",
        interviewLengthMore="Öppis meh",
        interviewTaboo="Nöd säge",
    ),
    "de-AT": voice(
        personalityCustom="Eigene Stimme",
        customVoice="Eigene Stimme",
        customVoiceHint="Seed legt die Figur fest. Slider verfeinern nur die Art zu sprechen. Language-Lock und Safety-Rules bleiben.",
        customVoiceMake="Stimme aus Seed und Slider schreiben",
        customVoiceFail="Stimme nicht geschrieben. LLM prüfen.",
        customVoiceName="Name der Stimme",
        customVoiceNameHint="So heißt diese Persönlichkeit in der Liste.",
        customVoiceSeed="Seed-Prompt",
        customVoiceSeedHint="Wer Klar sein soll, unabhängig von den Slidern. Zum Beispiel: Du bist Spock aus Star Trek.",
        interviewTraitsHint="0 = aus, 10 = stark. Wirkt nur auf die Sprechweise, nicht auf die Figur.",
        interviewWarmth="Wärme",
        interviewSarcasm="Sarkasmus",
        interviewFormality="Förmlichkeit",
        interviewVerbosity="Ausführlichkeit",
        interviewEnergy="Energie",
        interviewAddress="Wie soll Klar dich anreden?",
        interviewAddressDu="Du",
        interviewAddressSie="Sie",
        interviewAddressName="Vorname",
        interviewName="Name",
        interviewTone="Ton",
        interviewToneShort="Kurz",
        interviewToneWarm="Warm",
        interviewToneDry="Trocken",
        interviewHumor="Humor",
        interviewHumorNone="Keiner",
        interviewHumorLight="Leicht",
        interviewHumorSharp="Spitz",
        interviewLength="Länge",
        interviewLengthOne="Ein Satz",
        interviewLengthMore="Etwas mehr",
        interviewTaboo="Nicht sagen",
    ),
    "en-GB": voice(
        personalityCustom="Custom voice",
        customVoice="Custom voice",
        customVoiceHint="The seed sets the character. Sliders only refine how it speaks. Language lock and safety rules stay.",
        customVoiceMake="Write voice from seed and sliders",
        customVoiceFail="Could not write a voice. Check the LLM.",
        customVoiceName="Voice name",
        customVoiceNameHint="How this personality appears in the list.",
        customVoiceSeed="Seed prompt",
        customVoiceSeedHint="Who Klar should be, independent of the sliders. For example: You are Spock from Star Trek.",
        interviewTraitsHint="0 = off, 10 = strong. Delivery only, not the character.",
        interviewWarmth="Warmth",
        interviewSarcasm="Sarcasm",
        interviewFormality="Formality",
        interviewVerbosity="Verbosity",
        interviewEnergy="Energy",
        interviewAddress="How should Klar address you?",
        interviewAddressDu="Informal you",
        interviewAddressSie="Formal you",
        interviewAddressName="First name",
        interviewName="Name",
        interviewTone="Tone",
        interviewToneShort="Short",
        interviewToneWarm="Warm",
        interviewToneDry="Dry",
        interviewHumor="Humour",
        interviewHumorNone="None",
        interviewHumorLight="Light",
        interviewHumorSharp="Sharp",
        interviewLength="Length",
        interviewLengthOne="One sentence",
        interviewLengthMore="A bit more",
        interviewTaboo="Do not say",
    ),
    "af": voice(
        personalityCustom="Eie stem",
        customVoice="Eie stem",
        customVoiceHint="Die seed stel die karakter. Skuifknoppe verfyn net hoe dit praat. Taalslot en veiligheidsreëls bly.",
        customVoiceMake="Skryf stem uit seed en skuifknoppe",
        customVoiceFail="Kon nie 'n stem skryf nie. Kontroleer die LLM.",
        customVoiceName="Stemnaam",
        customVoiceNameHint="So verskyn hierdie persoonlikheid in die lys.",
        customVoiceSeed="Seed-prompt",
        customVoiceSeedHint="Wie Klar moet wees, onafhanklik van die skuifknoppe. Byvoorbeeld: Jy is Spock van Star Trek.",
        interviewTraitsHint="0 = af, 10 = sterk. Net die voordrag, nie die karakter nie.",
        interviewWarmth="Warmte",
        interviewSarcasm="Sarkasme",
        interviewFormality="Formaliteit",
        interviewVerbosity="Uitvoerigheid",
        interviewEnergy="Energie",
        interviewAddress="Hoe moet Klar jou aanspreek?",
        interviewAddressDu="Jy",
        interviewAddressSie="U",
        interviewAddressName="Voornaam",
        interviewName="Naam",
        interviewTone="Toon",
        interviewToneShort="Kort",
        interviewToneWarm="Warm",
        interviewToneDry="Droog",
        interviewHumor="Humor",
        interviewHumorNone="Geen",
        interviewHumorLight="Lig",
        interviewHumorSharp="Skerp",
        interviewLength="Lengte",
        interviewLengthOne="Een sin",
        interviewLengthMore="'n Bietjie meer",
        interviewTaboo="Moenie sê",
    ),
    "lb": voice(
        personalityCustom="Eegen Stëmm",
        customVoice="Eegen Stëmm",
        customVoiceHint="De Seed leet d'Figur fest. Slider verfeineren nëmmen d'Aart ze schwätzen. Language-Lock a Safety-Rules bleiwen.",
        customVoiceMake="Stëmm aus Seed a Slider schreiwen",
        customVoiceFail="Stëmm net geschriwwen. LLM préiwen.",
        customVoiceName="Numm vun der Stëmm",
        customVoiceNameHint="Sou heescht dës Perséinlechkeet an der Lëscht.",
        customVoiceSeed="Seed-Prompt",
        customVoiceSeedHint="Wien Klar si soll, onofhängeg vun de Slider. Zum Beispill: Du bass Spock aus Star Trek.",
        interviewTraitsHint="0 = aus, 10 = staark. Wirkt nëmmen op d'Sproochweis, net op d'Figur.",
        interviewWarmth="Wäermt",
        interviewSarcasm="Sarkasmus",
        interviewFormality="Förmlechkeet",
        interviewVerbosity="Ausféierlechkeet",
        interviewEnergy="Energie",
        interviewAddress="Wéi soll Klar dech uschwetzen?",
        interviewAddressDu="Du",
        interviewAddressSie="Dir",
        interviewAddressName="Virnumm",
        interviewName="Numm",
        interviewTone="Toun",
        interviewToneShort="Kuerz",
        interviewToneWarm="Warm",
        interviewToneDry="Dréchen",
        interviewHumor="Humor",
        interviewHumorNone="Keen",
        interviewHumorLight="Liicht",
        interviewHumorSharp="Spëtz",
        interviewLength="Längt",
        interviewLengthOne="Ee Saz",
        interviewLengthMore="E bëssen méi",
        interviewTaboo="Net soen",
    ),
    "cy": voice(
        personalityCustom="Llais personol",
        customVoice="Llais personol",
        customVoiceHint="Mae'r seed yn gosod y cymeriad. Dim ond mireinio sut mae'n siarad mae'r llithryddion. Mae clo iaith a rheolau diogelwch yn aros.",
        customVoiceMake="Ysgrifennu llais o seed a llithryddion",
        customVoiceFail="Methu ysgrifennu llais. Gwiriwch yr LLM.",
        customVoiceName="Enw'r llais",
        customVoiceNameHint="Sut mae'r bersonoliaeth hon yn ymddangos yn y rhestr.",
        customVoiceSeed="Anogwr seed",
        customVoiceSeedHint="Pwy ddylai Klar fod, annibynnol ar y llithryddion. Er enghraifft: Ti yw Spock o Star Trek.",
        interviewTraitsHint="0 = i ffwrdd, 10 = cryf. Cyflwyniad yn unig, nid y cymeriad.",
        interviewWarmth="Cynhesrwydd",
        interviewSarcasm="Dychan",
        interviewFormality="Ffurfioldeb",
        interviewVerbosity="Hirwyntogrwydd",
        interviewEnergy="Ynni",
        interviewAddress="Sut dylai Klar eich annerch?",
        interviewAddressDu="Ti",
        interviewAddressSie="Chi",
        interviewAddressName="Enw cyntaf",
        interviewName="Enw",
        interviewTone="Tôn",
        interviewToneShort="Byr",
        interviewToneWarm="Cynnes",
        interviewToneDry="Sych",
        interviewHumor="Hwyl",
        interviewHumorNone="Dim",
        interviewHumorLight="Ysgafn",
        interviewHumorSharp="Llym",
        interviewLength="Hyd",
        interviewLengthOne="Un frawddeg",
        interviewLengthMore="Ychydig yn fwy",
        interviewTaboo="Paid dweud",
    ),
    "eu": voice(
        personalityCustom="Ahots propioa",
        customVoice="Ahots propioa",
        customVoiceHint="Seed-ak pertsonaia finkatzen du. Graduatzaileek nola hitz egiten duen soilik fintzen dute. Hizkuntza-blokeoa eta segurtasun-arauak geratzen dira.",
        customVoiceMake="Ahotsa idatzi seed eta graduatzaileetatik",
        customVoiceFail="Ezin izan da ahotsa idatzi. Egiaztatu LLM.",
        customVoiceName="Ahotsaren izena",
        customVoiceNameHint="Horrela agertzen da nortasun hau zerrendan.",
        customVoiceSeed="Seed prompta",
        customVoiceSeedHint="Nor izan behar duen Klar, graduatzaileetatik independente. Adibidez: Spock zara Star Trek-ekoa.",
        interviewTraitsHint="0 = itzalita, 10 = indartsua. Entrega bakarrik, ez pertsonaia.",
        interviewWarmth="Beroa",
        interviewSarcasm="Sarkasmoa",
        interviewFormality="Formalitatea",
        interviewVerbosity="Hitz-jarioa",
        interviewEnergy="Energia",
        interviewAddress="Nola helarazi behar dizu Klar-ek?",
        interviewAddressDu="Hi / zu",
        interviewAddressSie="Zu (formal)",
        interviewAddressName="Izena",
        interviewName="Izena",
        interviewTone="Tonua",
        interviewToneShort="Labur",
        interviewToneWarm="Bero",
        interviewToneDry="Lehor",
        interviewHumor="Umorea",
        interviewHumorNone="Bat ere ez",
        interviewHumorLight="Arina",
        interviewHumorSharp="Zorrotza",
        interviewLength="Luzera",
        interviewLengthOne="Esaldi bat",
        interviewLengthMore="Pixka bat gehiago",
        interviewTaboo="Ez esan",
    ),
    "ga": voice(
        personalityCustom="Guth saincheaptha",
        customVoice="Guth saincheaptha",
        customVoiceHint="Socraíonn an seed an carachtar. Ní dhéanann na sleamhnáin ach an chaoi a labhraíonn sé a bheachtú. Fanann glas teanga agus rialacha sábháilteachta.",
        customVoiceMake="Scríobh guth ón seed agus na sleamhnáin",
        customVoiceFail="Níorbh fhéidir guth a scríobh. Seiceáil an LLM.",
        customVoiceName="Ainm an ghutha",
        customVoiceNameHint="Mar a léiríonn an phearsantacht seo sa liosta.",
        customVoiceSeed="Leid seed",
        customVoiceSeedHint="Cé ba cheart do Klar a bheith, neamhspleách ar na sleamhnáin. Mar shampla: Is tú Spock as Star Trek.",
        interviewTraitsHint="0 = as, 10 = láidir. An tseachadadh amháin, ní an carachtar.",
        interviewWarmth="Teas",
        interviewSarcasm="Searbhas",
        interviewFormality="Foirmeáltacht",
        interviewVerbosity="Fadfhoclacht",
        interviewEnergy="Fuinneamh",
        interviewAddress="Conas ba cheart do Klar labhairt leat?",
        interviewAddressDu="Tú",
        interviewAddressSie="Sibh",
        interviewAddressName="Céadainm",
        interviewName="Ainm",
        interviewTone="Tonn",
        interviewToneShort="Gearr",
        interviewToneWarm="Te",
        interviewToneDry="Tirim",
        interviewHumor="Greann",
        interviewHumorNone="Dada",
        interviewHumorLight="Éadrom",
        interviewHumorSharp="Géar",
        interviewLength="Fad",
        interviewLengthOne="Abairt amháin",
        interviewLengthMore="Beagán níos mó",
        interviewTaboo="Ná habair",
    ),
    "kw": voice(
        personalityCustom="Lev personel",
        customVoice="Lev personel",
        customVoiceHint="An seed a sett an gymeriad. Slyderow a fin yn unnik fatel gews ev. Alhwedh yeth ha rewlys sawder a wort.",
        customVoiceMake="Skrifa lev dhyworth seed ha slyderow",
        customVoiceFail="Ny yllir skrifa lev. Checkya an LLM.",
        customVoiceName="Hanow an lev",
        customVoiceNameHint="Yndella yth omdhiskwa an personoleth ma y'n rol.",
        customVoiceSeed="Prompt seed",
        customVoiceSeedHint="Piw y tal Klar bos, heb an slyderow. Rag ensampel: Ty yw Spock a Star Trek.",
        interviewTraitsHint="0 = degeys, 10 = krev. An dhelivrans yn unnik, a-der an gymeriad.",
        interviewWarmth="Tommder",
        interviewSarcasm="Sarkasm",
        interviewFormality="Furveleter",
        interviewVerbosity="Hirwheth",
        interviewEnergy="Nerth",
        interviewAddress="Fatel dal Klar dha leverel?",
        interviewAddressDu="Ty",
        interviewAddressSie="Hwi",
        interviewAddressName="Kynsa hanow",
        interviewName="Hanow",
        interviewTone="Ton",
        interviewToneShort="Berr",
        interviewToneWarm="Tomm",
        interviewToneDry="Sygh",
        interviewHumor="Hwarth",
        interviewHumorNone="Nagonan",
        interviewHumorLight="Skav",
        interviewHumorSharp="Lymm",
        interviewLength="Hirder",
        interviewLengthOne="Onan lavar",
        interviewLengthMore="Neppyth moy",
        interviewTaboo="Na lever",
    ),
}
