"""Custom-voice and interview chrome for Indic Assist locales and Swahili."""

from __future__ import annotations

from lang_packs.web_ui_voice import voice
from lang_packs.web_ui_voice_indic_rest import PACKS as REST

PACKS: dict[str, dict[str, str]] = {
    "hi": voice(
        personalityCustom="अपनी आवाज़",
        customVoice="अपनी आवाज़",
        customVoiceHint="Seed किरदार तय करता है। Slider केवल बोलने का ढंग सुधारते हैं। Language-Lock और Safety-Rules रहते हैं।",
        customVoiceMake="Seed और Slider से आवाज़ लिखें",
        customVoiceFail="आवाज़ नहीं लिखी गई। LLM जाँचें।",
        customVoiceName="आवाज़ का नाम",
        customVoiceNameHint="सूची में यह व्यक्तित्व ऐसा दिखता है।",
        customVoiceSeed="Seed-Prompt",
        customVoiceSeedHint="Klar कौन हो, Slider से अलग। उदाहरण: तुम Star Trek के स्पॉक हो।",
        interviewTraitsHint="0 = बंद, 10 = मजबूत। केवल बोलने का ढंग, किरदार नहीं।",
        interviewWarmth="गर्माहट",
        interviewSarcasm="व्यंग्य",
        interviewFormality="औपचारिकता",
        interviewVerbosity="विस्तार",
        interviewEnergy="ऊर्जा",
        interviewAddress="Klar तुम्हें कैसे पुकारे?",
        interviewAddressDu="तुम",
        interviewAddressSie="आप",
        interviewAddressName="नाम",
        interviewName="नाम",
        interviewTone="स्वर",
        interviewToneShort="छोटा",
        interviewToneWarm="गर्म",
        interviewToneDry="सूखा",
        interviewHumor="हास्य",
        interviewHumorNone="नहीं",
        interviewHumorLight="हल्का",
        interviewHumorSharp="तीखा",
        interviewLength="लंबाई",
        interviewLengthOne="एक वाक्य",
        interviewLengthMore="थोड़ा और",
        interviewTaboo="मत कहो",
    ),
    "bn": voice(
        personalityCustom="নিজের কণ্ঠ",
        customVoice="নিজের কণ্ঠ",
        customVoiceHint="Seed চরিত্র ঠিক করে। Slider শুধু বলার ধরন ঘষে। Language-Lock ও Safety-Rules থাকে।",
        customVoiceMake="Seed ও Slider থেকে কণ্ঠ লিখুন",
        customVoiceFail="কণ্ঠ লেখা যায়নি। LLM দেখুন।",
        customVoiceName="কণ্ঠের নাম",
        customVoiceNameHint="তালিকায় এই ব্যক্তিত্ব এমন দেখায়।",
        customVoiceSeed="Seed-Prompt",
        customVoiceSeedHint="Klar কে হবে, Slider ছাড়া। যেমন: তুমি Star Trek-এর স্পক।",
        interviewTraitsHint="0 = বন্ধ, 10 = জোরালো। শুধু বলার ধরন, চরিত্র নয়।",
        interviewWarmth="উষ্ণতা",
        interviewSarcasm="ব্যঙ্গ",
        interviewFormality="আনুষ্ঠানিকতা",
        interviewVerbosity="বিস্তার",
        interviewEnergy="শক্তি",
        interviewAddress="Klar তোমাকে কীভাবে ডাকবে?",
        interviewAddressDu="তুমি",
        interviewAddressSie="আপনি",
        interviewAddressName="নাম",
        interviewName="নাম",
        interviewTone="সুর",
        interviewToneShort="ছোট",
        interviewToneWarm="উষ্ণ",
        interviewToneDry="শুকনো",
        interviewHumor="রসিকতা",
        interviewHumorNone="নেই",
        interviewHumorLight="হালকা",
        interviewHumorSharp="তীক্ষ্ণ",
        interviewLength="দৈর্ঘ্য",
        interviewLengthOne="এক বাক্য",
        interviewLengthMore="আর একটু",
        interviewTaboo="বলো না",
    ),
}
PACKS.update(REST)
