"""First-run wizard chrome for RTL, Indic, and other script Assist locales."""

from __future__ import annotations

from lang_packs.wizard import pack

PACKS: dict[str, dict[str, str]] = {
    "ar": pack(
        title="الإعداد", skip="تخطي", back="رجوع", next="التالي", done="تم",
        whatTitle="ما هو Klar",
        whatLead="NLU Assist محلي. Home Assistant يبقى قاعدة الأجهزة. هذه ليست لوحة منزل ولا محرك محادثة LLM.",
        whatLocal="Klar يحلّل الجملة. Home Assistant يملك الغرف والأجهزة.",
        whatConsole="Lovelace «Klar» هو آخر دور Assist. هذه الواجهة (Klar NLU) هي وحدة المشغّل: Settings والبيت والمختبر والقواعد.",
        whatNoLlm="لا تضع LLM كمحرك محادثة للمسار. الصوت وLLM في Settings.",
        modeLead="الشخصية والوضع والصقل تُحفظ على المحرك. Home Assistant Configure لا يحتاجها.",
        missLead="دردشة Assist والصقل والمدرب يشاركون نقطة النهاية المتوافقة مع OpenAI. لا تكامل LLM في Home Assistant.",
        missLlmBody="دردشة Assist والصقل والمدرب في Settings، لا في تكامل محادثة Home Assistant.",
        missWarn="لا تضع LLM أبدًا في خانة Conversation engine بالمسار.",
        llmOptional="اتركه فارغًا واضبطه لاحقًا في Settings. الإعداد ينتهي بلا LLM.",
        toolsLead="بعد الإعداد تبقى في هذه الوحدة. الصوت واللغات وLLM تحت Settings.",
    ),
    "he": pack(
        title="התקנה", skip="דלג", back="חזרה", next="הבא", done="סיום",
        whatTitle="מהו Klar",
        whatLead="NLU Assist מקומי. Home Assistant נשאר מסד המכשירים. זה לא לוח בית ולא מנוע שיחה LLM.",
        whatLocal="Klar מפרק את המשפט. Home Assistant מחזיק חדרים ומכשירים.",
        whatConsole="Lovelace „Klar“ הוא התור Assist האחרון. המשטח הזה (Klar NLU) הוא קונסולת המפעיל: Settings, בית, מעבדה וכללים.",
        whatNoLlm="אל תגדיר LLM כמנוע השיחה בצינור. קול ו-LLM ב-Settings.",
        modeLead="אישיות, מצב וליטוש נשמרים במנוע. Home Assistant Configure לא צריך אותם.",
        missLead="צ'אט Assist, ליטוש והמאמן חולקים נקודת קצה תואמת OpenAI. אין שילוב LLM של Home Assistant.",
        missLlmBody="צ'אט Assist, ליטוש והמאמן חיים ב-Settings, לא באינטגרציית שיחה של Home Assistant.",
        missWarn="לעולם אל תשים את ה-LLM בחריץ Conversation engine של הצינור.",
        llmOptional="השאר ריק והגדר אחר כך ב-Settings. ההתקנה מסתיימת בלי LLM.",
        toolsLead="אחרי ההתקנה נשארים בקונסולה הזו. קול, שפות ו-LLM תחת Settings.",
    ),
    "fa": pack(
        title="راه‌اندازی", skip="رد کردن", back="بازگشت", next="بعدی", done="تمام",
        whatTitle="Klar چیست",
        whatLead="NLU Assist محلی. Home Assistant پایگاه دستگاه می‌ماند. این داشبورد خانه و موتور گفتگوی LLM نیست.",
        whatLocal="Klar جمله را تجزیه می‌کند. Home Assistant اتاق‌ها و دستگاه‌ها را دارد.",
        whatConsole="Lovelace «Klar» آخرین نوبت Assist است. این سطح (Klar NLU) کنسول اپراتور است: Settings، خانه، آزمایشگاه و قوانین.",
        whatNoLlm="LLM را موتور گفتگوی خط لوله نگذارید. صدا و LLM در Settings است.",
        modeLead="شخصیت، حالت و پرداخت روی موتور ذخیره می‌شود. Home Assistant Configure لازم نیست.",
        missLead="گفتگوی Assist، پرداخت و مربی این نقطه پایانی سازگار با OpenAI را شریک‌اند. یکپارچگی LLM هوم اسیستنت نیست.",
        missLlmBody="گفتگوی Assist، پرداخت و مربی در Settings زندگی می‌کنند، نه در یکپارچگی گفتگوی Home Assistant.",
        missWarn="هرگز LLM را در شکاف Conversation engine خط لوله نگذارید.",
        llmOptional="خالی بگذارید و بعداً در Settings تنظیم کنید. راه‌اندازی بدون LLM تمام می‌شود.",
        toolsLead="بعد از راه‌اندازی در این کنسول می‌مانید. صدا، زبان‌ها و LLM زیر Settings است.",
    ),
    "ur": pack(
        title="سیٹ اپ", skip="چھوڑیں", back="واپس", next="اگلا", done="مکمل",
        whatTitle="Klar کیا ہے",
        whatLead="مقامی Assist NLU۔ Home Assistant آلات کا ڈیٹا بیس رہتا ہے۔ یہ گھر کا ڈیش بورڈ نہیں اور LLM گفتگو انجن نہیں۔",
        whatLocal="Klar جملہ پارس کرتا ہے۔ Home Assistant کمروں اور آلات کا مالک ہے۔",
        whatConsole="Lovelace “Klar” آخری Assist باری ہے۔ یہ سطح (Klar NLU) آپریٹر کنسول ہے: Settings، گھر، لیب اور قواعد۔",
        whatNoLlm="LLM کو پائپ لائن کا گفتگو انجن نہ بنائیں۔ آواز اور LLM Settings میں ہیں۔",
        modeLead="شخصیت، موڈ اور اصلاح انجن پر محفوظ ہیں۔ Home Assistant Configure کی ضرورت نہیں۔",
        missLead="Assist چیٹ، اصلاح اور ٹرینر یہ OpenAI موافق اینڈ پوائنٹ بانٹتے ہیں۔ کوئی Home Assistant LLM انضمام نہیں۔",
        missLlmBody="Assist چیٹ، اصلاح اور ٹرینر Settings میں رہتے ہیں، Home Assistant گفتگو انضمام میں نہیں۔",
        missWarn="LLM کو کبھی پائپ لائن کے Conversation engine خانے میں نہ رکھیں۔",
        llmOptional="خالی چھوڑیں اور بعد میں Settings میں سیٹ کریں۔ سیٹ اپ LLM کے بغیر ختم ہوتا ہے۔",
        toolsLead="سیٹ اپ کے بعد آپ اس کنسول میں رہتے ہیں۔ آواز، زبانیں اور LLM Settings کے نیچے ہیں۔",
    ),
    "tr": pack(
        title="Kurulum", skip="Atla", back="Geri", next="İleri", done="Bitti",
        whatTitle="Klar nedir",
        whatLead="Yerel Assist NLU. Home Assistant cihaz veritabanı olarak kalır. Bu bir ev paneli ve LLM sohbet motoru değil.",
        whatLocal="Klar cümleyi ayırır. Odalar ve cihazlar Home Assistant’a aittir.",
        whatConsole="Lovelace “Klar” son Assist turudur. Bu yüzey (Klar NLU) operatör konsoludur: Settings, Ev, Lab ve Kurallar.",
        whatNoLlm="LLM’yi boru hattının sohbet motoru yapma. Ses ve LLM Settings’te.",
        modeLead="Kişilik, kip ve cilalama motorda saklanır. Home Assistant Configure gerekmez.",
        missLead="Assist sohbeti, cilalama ve eğitmen bu OpenAI uyumlu uç noktayı paylaşır. Home Assistant LLM entegrasyonu yok.",
        missLlmBody="Assist sohbeti, cilalama ve eğitmen Settings’te yaşar, bir Home Assistant sohbet entegrasyonunda değil.",
        missWarn="LLM’yi asla boru hattının Conversation engine yuvasına koyma.",
        llmOptional="Boş bırak, sonra Settings’te ayarla. Kurulum LLM olmadan biter.",
        toolsLead="Kurulumdan sonra bu konsolda kalırsın. Ses, diller ve LLM Settings altında.",
    ),
    "el": pack(
        title="Ρύθμιση", skip="Παράλειψη", back="Πίσω", next="Επόμενο", done="Τέλος",
        whatTitle="Τι είναι το Klar",
        whatLead="Τοπικό Assist NLU. Το Home Assistant μένει η βάση συσκευών. Αυτό δεν είναι πίνακας σπιτιού ούτε μηχανή συνομιλίας LLM.",
        whatLocal="Το Klar αναλύει την πρόταση. Το Home Assistant κατέχει δωμάτια και συσκευές.",
        whatConsole="Το Lovelace «Klar» είναι η τελευταία σειρά Assist. Αυτή η επιφάνεια (Klar NLU) είναι η κονσόλα χειριστή: Settings, Σπίτι, Lab και Κανόνες.",
        whatNoLlm="Μην βάζεις LLM ως μηχανή συνομιλίας του pipeline. Φωνή και LLM είναι στα Settings.",
        modeLead="Προσωπικότητα, λειτουργία και φινίρισμα αποθηκεύονται στη μηχανή. Το Home Assistant Configure δεν τα χρειάζεται.",
        missLead="Η συνομιλία Assist, το φινίρισμα και ο εκπαιδευτής μοιράζονται αυτό το συμβατό με OpenAI endpoint. Χωρίς ενσωμάτωση LLM Home Assistant.",
        missLlmBody="Η συνομιλία Assist, το φινίρισμα και ο εκπαιδευτής ζουν στα Settings, όχι σε ενσωμάτωση συνομιλίας Home Assistant.",
        missWarn="Ποτέ μην βάζεις το LLM στη σχισμή Conversation engine του pipeline.",
        llmOptional="Άφησέ το κενό και όρισέ το αργότερα στα Settings. Η ρύθμιση τελειώνει χωρίς LLM.",
        toolsLead="Μετά τη ρύθμιση μένεις σε αυτή την κονσόλα. Φωνή, γλώσσες και LLM είναι κάτω από Settings.",
    ),
    "hy": pack(
        title="Կարգավորում", skip="Բաց թողնել", back="Հետ", next="Հաջորդ", done="Պատրաստ",
        whatTitle="Ինչ է Klar-ը",
        whatLead="Տեղական Assist NLU։ Home Assistant-ը մնում է սարքերի շտեմարան։ Սա տան վահանակ չէ և LLM խոսակցական շարժիչ չէ։",
        whatLocal="Klar-ը վերլուծում է նախադասությունը։ Home Assistant-ն ունի սենյակներն ու սարքերը։",
        whatConsole="Lovelace «Klar»-ը Assist-ի վերջին քայլն է։ Այս մակերեսը (Klar NLU) օպերատորի վահանակն է՝ Settings, Տուն, Lab և Կանոններ։",
        whatNoLlm="LLM-ը մի դրեք որպես pipeline-ի խոսակցական շարժիչ։ Ձայնն ու LLM-ը Settings-ում են։",
        modeLead="Անհատականությունը, ռեժիմը և մշակումը պահվում են շարժիչում։ Home Assistant Configure-ը պետք չէ։",
        missLead="Assist զրույցը, մշակումը և մարզիչը կիսում են այս OpenAI համատեղելի վերջնակետը։ Home Assistant LLM ինտեգրում չկա։",
        missLlmBody="Assist զրույցը, մշակումը և մարզիչը ապրում են Settings-ում, ոչ Home Assistant խոսակցական ինտեգրման մեջ։",
        missWarn="Երբեք մի դրեք LLM-ը pipeline-ի Conversation engine բնիկում։",
        llmOptional="Թողեք դատարկ և սահմանեք հետո Settings-ում։ Կարգավորումն ավարտվում է առանց LLM։",
        toolsLead="Կարգավորումից հետո մնում եք այս վահանակում։ Ձայնը, լեզուները և LLM-ը Settings-ում են։",
    ),
    "ka": pack(
        title="დაყენება", skip="გამოტოვება", back="უკან", next="შემდეგი", done="მზადაა",
        whatTitle="რა არის Klar",
        whatLead="ადგილობრივი Assist NLU. Home Assistant რჩება მოწყობილობების ბაზად. ეს არ არის სახლის დაფა და არც LLM საუბრის ძრავა.",
        whatLocal="Klar წინადადებას ანაწილებს. Home Assistant ფლობს ოთახებს და მოწყობილობებს.",
        whatConsole="Lovelace „Klar“ Assist-ის ბოლო ნაბიჯია. ეს ზედაპირი (Klar NLU) ოპერატორის კონსოლია: Settings, სახლი, Lab და წესები.",
        whatNoLlm="არ დააყენო LLM pipeline-ის საუბრის ძრავად. ხმა და LLM Settings-შია.",
        modeLead="პიროვნება, რეჟიმი და გაპრიალება ძრავზე ინახება. Home Assistant Configure არ სჭირდება.",
        missLead="Assist ჩატი, გაპრიალება და მწვრთნელი იზიარებენ ამ OpenAI თავსებად წერტილს. Home Assistant LLM ინტეგრაცია არ არის.",
        missLlmBody="Assist ჩატი, გაპრიალება და მწვრთნელი Settings-ში ცხოვრობენ, არა Home Assistant საუბრის ინტეგრაციაში.",
        missWarn="არასდროს ჩასვა LLM pipeline-ის Conversation engine სლოტში.",
        llmOptional="დატოვე ცარიელი და დააყენე მოგვიანებით Settings-ში. დაყენება LLM-ის გარეშე სრულდება.",
        toolsLead="დაყენების შემდეგ ამ კონსოლში რჩები. ხმა, ენები და LLM Settings-შია.",
    ),
    "hi": pack(
        title="सेटअप", skip="छोड़ें", back="पीछे", next="आगे", done="पूर्ण",
        whatTitle="Klar क्या है",
        whatLead="स्थानीय Assist NLU। Home Assistant उपकरण डेटाबेस रहता है। यह घर का डैशबोर्ड नहीं और LLM बातचीत इंजन नहीं।",
        whatLocal="Klar वाक्य पार्स करता है। कमरे और उपकरण Home Assistant के हैं।",
        whatConsole="Lovelace “Klar” आखिरी Assist पारी है। यह सतह (Klar NLU) संचालक कंसोल है: Settings, घर, लैब और नियम।",
        whatNoLlm="LLM को पाइपलाइन का बातचीत इंजन न बनाएँ। आवाज़ और LLM Settings में हैं।",
        modeLead="व्यक्तित्व, मोड और परिष्करण इंजन पर सहेजे जाते हैं। Home Assistant Configure की ज़रूरत नहीं।",
        missLead="Assist चैट, परिष्करण और प्रशिक्षक यह OpenAI-संगत एंडपॉइंट साझा करते हैं। कोई Home Assistant LLM एकीकरण नहीं।",
        missLlmBody="Assist चैट, परिष्करण और प्रशिक्षक Settings में रहते हैं, Home Assistant बातचीत एकीकरण में नहीं।",
        missWarn="LLM को पाइपलाइन के Conversation engine स्लॉट में कभी न डालें।",
        llmOptional="खाली छोड़ें और बाद में Settings में सेट करें। सेटअप बिना LLM पूरा होता है।",
        toolsLead="सेटअप के बाद आप इसी कंसोल में रहते हैं। आवाज़, भाषाएँ और LLM Settings में हैं।",
    ),
    "bn": pack(
        title="সেটআপ", skip="এড়িয়ে যান", back="পিছনে", next="পরবর্তী", done="শেষ",
        whatTitle="Klar কী",
        whatLead="স্থানীয় Assist NLU। Home Assistant ডিভাইস ডেটাবেস থাকে। এটি ঘরের ড্যাশবোর্ড নয় এবং LLM কথোপকথন ইঞ্জিন নয়।",
        whatLocal="Klar বাক্য পার্স করে। ঘর ও ডিভাইস Home Assistant-এর।",
        whatConsole="Lovelace “Klar” শেষ Assist পালা। এই পৃষ্ঠ (Klar NLU) অপারেটর কনসোল: Settings, বাড়ি, ল্যাব ও নিয়ম।",
        whatNoLlm="LLM-কে পাইপলাইনের কথোপকথন ইঞ্জিন করবেন না। কণ্ঠ ও LLM Settings-এ।",
        modeLead="ব্যক্তিত্ব, মোড ও পরিমার্জন ইঞ্জিনে থাকে। Home Assistant Configure লাগে না।",
        missLead="Assist চ্যাট, পরিমার্জন ও প্রশিক্ষক এই OpenAI-সামঞ্জস্যপূর্ণ এন্ডপয়েন্ট ভাগ করে। Home Assistant LLM ইন্টিগ্রেশন নেই।",
        missLlmBody="Assist চ্যাট, পরিমার্জন ও প্রশিক্ষক Settings-এ থাকে, Home Assistant কথোপকথন ইন্টিগ্রেশনে নয়।",
        missWarn="LLM কখনও পাইপলাইনের Conversation engine স্লটে দিবেন না।",
        llmOptional="খালি রাখুন, পরে Settings-এ সেট করুন। সেটআপ LLM ছাড়াই শেষ হয়।",
        toolsLead="সেটআপের পর এই কনসোলে থাকবেন। কণ্ঠ, ভাষা ও LLM Settings-এ।",
    ),
    "gu": pack(
        title="સેટઅપ", skip="છોડો", back="પાછળ", next="આગળ", done="પૂર્ણ",
        whatTitle="Klar શું છે",
        whatLead="સ્થાનિક Assist NLU. Home Assistant ઉપકરણ ડેટાબેઝ રહે છે. આ ઘરનું ડેશબોર્ડ નથી અને LLM વાતચીત એન્જિન નથી.",
        whatLocal="Klar વાક્ય પાર્સ કરે છે. રૂમ અને ઉપકરણો Home Assistant ના છે.",
        whatConsole="Lovelace “Klar” છેલ્લી Assist પાળી છે. આ સપાટી (Klar NLU) ઓપરેટર કન્સોલ છે: Settings, ઘર, લેબ અને નિયમો.",
        whatNoLlm="LLM ને પાઇપલાઇનનું વાતચીત એન્જિન ન બનાવો. અવાજ અને LLM Settings માં છે.",
        modeLead="વ્યક્તિત્વ, મોડ અને પરિષ્કરણ એન્જિન પર સંગ્રહાય છે. Home Assistant Configure જોઈએ નહીં.",
        missLead="Assist ચેટ, પરિષ્કરણ અને તાલીમકાર આ OpenAI-સુસંગત એન્ડપોઇન્ટ વહેંચે છે. Home Assistant LLM એકીકરણ નથી.",
        missLlmBody="Assist ચેટ, પરિષ્કરણ અને તાલીમકાર Settings માં રહે છે, Home Assistant વાતચીત એકીકરણમાં નહીં.",
        missWarn="LLM ને પાઇપલાઇનના Conversation engine સ્લોટમાં ક્યારેય ન મૂકો.",
        llmOptional="ખાલી રાખો અને પછી Settings માં સેટ કરો. સેટઅપ LLM વગર પૂરું થાય છે.",
        toolsLead="સેટઅપ પછી તમે આ કન્સોલમાં રહો છો. અવાજ, ભાષાઓ અને LLM Settings હેઠળ છે.",
    ),
    "kn": pack(
        title="ಸೆಟಪ್", skip="ಬಿಟ್ಟುಬಿಡಿ", back="ಹಿಂದೆ", next="ಮುಂದೆ", done="ಮುಗಿದಿದೆ",
        whatTitle="Klar ಎಂದರೇನು",
        whatLead="ಸ್ಥಳೀಯ Assist NLU. Home Assistant ಸಾಧನ ಡೇಟಾಬೇಸ್ ಆಗಿ ಉಳಿಯುತ್ತದೆ. ಇದು ಮನೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅಲ್ಲ ಮತ್ತು LLM ಸಂಭಾಷಣೆ ಎಂಜಿನ್ ಅಲ್ಲ.",
        whatLocal="Klar ವಾಕ್ಯವನ್ನು ಪಾರ್ಸ್ ಮಾಡುತ್ತದೆ. ಕೋಣೆಗಳು ಮತ್ತು ಸಾಧನಗಳು Home Assistant ಗೆ ಸೇರಿವೆ.",
        whatConsole="Lovelace “Klar” ಕೊನೆಯ Assist ಸರದಿ. ಈ ಮೇಲ್ಮೈ (Klar NLU) ಆಪರೇಟರ್ ಕನ್ಸೋಲ್: Settings, ಮನೆ, ಲ್ಯಾಬ್ ಮತ್ತು ನಿಯಮಗಳು.",
        whatNoLlm="LLM ಅನ್ನು ಪೈಪ್‌ಲೈನ್ ಸಂಭಾಷಣೆ ಎಂಜಿನ್ ಆಗಿ ಹಾಕಬೇಡಿ. ಧ್ವನಿ ಮತ್ತು LLM Settings ನಲ್ಲಿವೆ.",
        modeLead="ವ್ಯಕ್ತಿತ್ವ, ಮೋಡ್ ಮತ್ತು ಪರಿಷ್ಕರಣೆ ಎಂಜಿನ್‌ನಲ್ಲಿ ಉಳಿಯುತ್ತವೆ. Home Assistant Configure ಬೇಕಿಲ್ಲ.",
        missLead="Assist ಚಾಟ್, ಪರಿಷ್ಕರಣೆ ಮತ್ತು ತರಬೇತುದಾರ ಈ OpenAI-ಹೊಂದಾಣಿಕೆಯ ಎಂಡ್‌ಪಾಯಿಂಟ್ ಹಂಚಿಕೊಳ್ಳುತ್ತಾರೆ. Home Assistant LLM ಏಕೀಕರಣ ಇಲ್ಲ.",
        missLlmBody="Assist ಚಾಟ್, ಪರಿಷ್ಕರಣೆ ಮತ್ತು ತರಬೇತುದಾರ Settings ನಲ್ಲಿ ಇರುತ್ತಾರೆ, Home Assistant ಸಂಭಾಷಣೆ ಏಕೀಕರಣದಲ್ಲಿ ಅಲ್ಲ.",
        missWarn="LLM ಅನ್ನು ಪೈಪ್‌ಲೈನ್ Conversation engine ಸ್ಲಾಟ್‌ನಲ್ಲಿ ಎಂದಿಗೂ ಹಾಕಬೇಡಿ.",
        llmOptional="ಖಾಲಿ ಬಿಟ್ಟು ನಂತರ Settings ನಲ್ಲಿ ಹೊಂದಿಸಿ. LLM ಇಲ್ಲದೆಯೂ ಸೆಟಪ್ ಮುಗಿಯುತ್ತದೆ.",
        toolsLead="ಸೆಟಪ್ ನಂತರ ಈ ಕನ್ಸೋಲ್‌ನಲ್ಲಿಯೇ ಇರುತ್ತೀರಿ. ಧ್ವನಿ, ಭಾಷೆಗಳು ಮತ್ತು LLM Settings ಅಡಿಯಲ್ಲಿವೆ.",
    ),
    "ml": pack(
        title="സെറ്റപ്പ്", skip="ഒഴിവാക്കുക", back="പിന്നോട്ട്", next="അടുത്തത്", done="പൂർത്തി",
        whatTitle="Klar എന്താണ്",
        whatLead="പ്രാദേശിക Assist NLU. Home Assistant ഉപകരണ ഡാറ്റാബേസായി തുടരുന്നു. ഇത് വീട്ടു ഡാഷ്ബോർഡല്ല, LLM സംഭാഷണ എഞ്ചിനുമല്ല.",
        whatLocal="Klar വാക്യം പാർസ് ചെയ്യുന്നു. മുറികളും ഉപകരണങ്ങളും Home Assistant-ന്റേതാണ്.",
        whatConsole="Lovelace “Klar” അവസാന Assist ഊഴമാണ്. ഈ ഉപരിതലം (Klar NLU) ഓപ്പറേറ്റർ കൺസോളാണ്: Settings, വീട്, ലാബ്, നിയമങ്ങൾ.",
        whatNoLlm="LLM-നെ പൈപ്പ്‌ലൈൻ സംഭാഷണ എഞ്ചിനാക്കരുത്. ശബ്ദവും LLM-ഉം Settings-ൽ.",
        modeLead="വ്യക്തിത്വം, മോഡ്, മിനുക്കൽ എഞ്ചിനിൽ സൂക്ഷിക്കുന്നു. Home Assistant Configure വേണ്ട.",
        missLead="Assist ചാറ്റ്, മിനുക്കൽ, പരിശീലകൻ ഈ OpenAI-അനുയോജ്യ എൻഡ്‌പോയിന്റ് പങ്കിടുന്നു. Home Assistant LLM സംയോജനമില്ല.",
        missLlmBody="Assist ചാറ്റ്, മിനുക്കൽ, പരിശീലകൻ Settings-ൽ ജീവിക്കുന്നു, Home Assistant സംഭാഷണ സംയോജനത്തിലല്ല.",
        missWarn="LLM-നെ പൈപ്പ്‌ലൈൻ Conversation engine സ്ലോട്ടിൽ ഒരിക്കലും ഇടരുത്.",
        llmOptional="ശൂന്യമായിട്ട് പിന്നീട് Settings-ൽ സജ്ജമാക്കുക. LLM ഇല്ലാതെയും സെറ്റപ്പ് തീരും.",
        toolsLead="സെറ്റപ്പിന് ശേഷം ഈ കൺസോളിൽ തുടരും. ശബ്ദം, ഭാഷകൾ, LLM Settings-ൽ.",
    ),
    "mr": pack(
        title="सेटअप", skip="वगळा", back="मागे", next="पुढे", done="पूर्ण",
        whatTitle="Klar काय आहे",
        whatLead="स्थानिक Assist NLU. Home Assistant उपकरण डेटाबेस राहतो. हे घरचे डॅशबोर्ड नाही आणि LLM संभाषण इंजिन नाही.",
        whatLocal="Klar वाक्य पार्स करतो. खोल्या आणि उपकरणे Home Assistant कडे आहेत.",
        whatConsole="Lovelace “Klar” शेवटची Assist पाळी आहे. ही पृष्ठभाग (Klar NLU) ऑपरेटर कन्सोल आहे: Settings, घर, लॅब आणि नियम.",
        whatNoLlm="LLM ला पाइपलाइनचे संभाषण इंजिन करू नका. आवाज आणि LLM Settings मध्ये आहेत.",
        modeLead="व्यक्तिमत्व, मोड आणि परिष्करण इंजिनवर साठवले जातात. Home Assistant Configure नको.",
        missLead="Assist चॅट, परिष्करण आणि प्रशिक्षक हा OpenAI-सुसंगत एंडपॉइंट वाटतात. Home Assistant LLM एकत्रीकरण नाही.",
        missLlmBody="Assist चॅट, परिष्करण आणि प्रशिक्षक Settings मध्ये राहतात, Home Assistant संभाषण एकत्रीकरणात नाही.",
        missWarn="LLM कधीही पाइपलाइनच्या Conversation engine स्लॉटमध्ये ठेवू नका.",
        llmOptional="रिकामे ठेवा आणि नंतर Settings मध्ये सेट करा. सेटअप LLM शिवाय पूर्ण होतो.",
        toolsLead="सेटअपनंतर तुम्ही या कन्सोलमध्ये राहता. आवाज, भाषा आणि LLM Settings खाली आहेत.",
    ),
    "ta": pack(
        title="அமைப்பு", skip="தவிர்", back="பின்", next="அடுத்தது", done="முடிந்தது",
        whatTitle="Klar என்றால் என்ன",
        whatLead="உள்ளூர் Assist NLU. Home Assistant சாதன தரவுத்தளமாகவே இருக்கும். இது வீட்டு டாஷ்போர்டு அல்ல, LLM உரையாடல் இயந்திரம் அல்ல.",
        whatLocal="Klar வாக்கியத்தை பிரிக்கிறது. அறைகளும் சாதனங்களும் Home Assistant உடைமை.",
        whatConsole="Lovelace “Klar” கடைசி Assist முறை. இந்த மேற்பரப்பு (Klar NLU) இயக்குபவர் கன்சோல்: Settings, வீடு, ஆய்வகம், விதிகள்.",
        whatNoLlm="LLM-ஐ குழாய் உரையாடல் இயந்திரமாக வைக்க வேண்டாம். குரல் மற்றும் LLM Settings-இல்.",
        modeLead="ஆளுமை, முறை, செம்மைப்படுத்துதல் இயந்திரத்தில் சேமிக்கப்படும். Home Assistant Configure தேவையில்லை.",
        missLead="Assist அரட்டை, செம்மைப்படுத்துதல், பயிற்றுனர் இந்த OpenAI-இணக்க முனையத்தை பகிர்கின்றனர். Home Assistant LLM ஒருங்கிணைப்பு இல்லை.",
        missLlmBody="Assist அரட்டை, செம்மைப்படுத்துதல், பயிற்றுனர் Settings-இல் வாழ்கின்றனர், Home Assistant உரையாடல் ஒருங்கிணைப்பில் அல்ல.",
        missWarn="LLM-ஐ குழாயின் Conversation engine இடத்தில் ஒருபோதும் வைக்க வேண்டாம்.",
        llmOptional="காலியாக விட்டுப் பிறகு Settings-இல் அமைக்கவும். LLM இல்லாமலே அமைப்பு முடியும்.",
        toolsLead="அமைப்புக்குப் பிறகு இந்தக் கன்சோலிலேயே இருப்பீர்கள். குரல், மொழிகள், LLM Settings கீழ்.",
    ),
    "te": pack(
        title="సెటప్", skip="దాటవేయి", back="వెనుకకు", next="తర్వాత", done="పూర్తి",
        whatTitle="Klar అంటే ఏమిటి",
        whatLead="స్థానిక Assist NLU. Home Assistant పరికర డేటాబేస్‌గా ఉంటుంది. ఇది ఇంటి డాష్‌బోర్డ్ కాదు, LLM సంభాషణ ఇంజిన్ కాదు.",
        whatLocal="Klar వాక్యాన్ని పార్స్ చేస్తుంది. గదులు, పరికరాలు Home Assistantవి.",
        whatConsole="Lovelace “Klar” చివరి Assist వంతు. ఈ ఉపరితలం (Klar NLU) ఆపరేటర్ కన్సోల్: Settings, ఇల్లు, ల్యాబ్, నియమాలు.",
        whatNoLlm="LLMని పైప్‌లైన్ సంభాషణ ఇంజిన్‌గా పెట్టవద్దు. వాయిస్, LLM Settingsలో ఉన్నాయి.",
        modeLead="వ్యక్తిత్వం, మోడ్, మెరుగుదల ఇంజిన్‌పై నిలుస్తాయి. Home Assistant Configure అవసరం లేదు.",
        missLead="Assist చాట్, మెరుగుదల, శిక్షకుడు ఈ OpenAI-అనుకూల ఎండ్‌పాయింట్ పంచుకుంటారు. Home Assistant LLM ఏకీకరణ లేదు.",
        missLlmBody="Assist చాట్, మెరుగుదల, శిక్షకుడు Settingsలో ఉంటారు, Home Assistant సంభాషణ ఏకీకరణలో కాదు.",
        missWarn="LLMని పైప్‌లైన్ Conversation engine స్లాట్‌లో ఎప్పుడూ పెట్టవద్దు.",
        llmOptional="ఖాళీగా ఉంచి తర్వాత Settingsలో సెట్ చేయండి. LLM లేకుండానే సెటప్ అవుతుంది.",
        toolsLead="సెటప్ తర్వాత ఈ కన్సోల్‌లోనే ఉంటారు. వాయిస్, భాషలు, LLM Settings కింద.",
    ),
    "pa": pack(
        title="ਸੈੱਟਅੱਪ", skip="ਛੱਡੋ", back="ਪਿੱਛੇ", next="ਅੱਗੇ", done="ਮੁਕੰਮਲ",
        whatTitle="Klar ਕੀ ਹੈ",
        whatLead="ਸਥਾਨਕ Assist NLU. Home Assistant ਡਿਵਾਈਸ ਡਾਟਾਬੇਸ ਰਹਿੰਦਾ ਹੈ. ਇਹ ਘਰ ਦਾ ਡੈਸ਼ਬੋਰਡ ਨਹੀਂ ਅਤੇ LLM ਗੱਲਬਾਤ ਇੰਜਣ ਨਹੀਂ.",
        whatLocal="Klar ਵਾਕ ਪਾਰਸ ਕਰਦਾ ਹੈ. ਕਮਰੇ ਤੇ ਡਿਵਾਈਸ Home Assistant ਦੇ ਹਨ.",
        whatConsole="Lovelace “Klar” ਆਖਰੀ Assist ਵਾਰੀ ਹੈ. ਇਹ ਸਤਹ (Klar NLU) ਆਪਰੇਟਰ ਕੰਸੋਲ ਹੈ: Settings, ਘਰ, ਲੈਬ ਤੇ ਨਿਯਮ.",
        whatNoLlm="LLM ਨੂੰ ਪਾਈਪਲਾਈਨ ਦਾ ਗੱਲਬਾਤ ਇੰਜਣ ਨਾ ਬਣਾਓ. ਆਵਾਜ਼ ਤੇ LLM Settings ਵਿੱਚ ਹਨ.",
        modeLead="ਸ਼ਖਸੀਅਤ, ਮੋਡ ਤੇ ਸੁਧਾਰ ਇੰਜਣ ਤੇ ਸੰਭਾਲੇ ਜਾਂਦੇ ਹਨ. Home Assistant Configure ਲੋੜੀਂਦਾ ਨਹੀਂ.",
        missLead="Assist ਚੈਟ, ਸੁਧਾਰ ਤੇ ਟਰੇਨਰ ਇਹ OpenAI-ਅਨੁਕੂਲ ਐਂਡਪੌਇੰਟ ਵੰਡਦੇ ਹਨ. Home Assistant LLM ਏਕੀਕਰਨ ਨਹੀਂ.",
        missLlmBody="Assist ਚੈਟ, ਸੁਧਾਰ ਤੇ ਟਰੇਨਰ Settings ਵਿੱਚ ਰਹਿੰਦੇ ਹਨ, Home Assistant ਗੱਲਬਾਤ ਏਕੀਕਰਨ ਵਿੱਚ ਨਹੀਂ.",
        missWarn="LLM ਨੂੰ ਪਾਈਪਲਾਈਨ ਦੇ Conversation engine ਸਲਾਟ ਵਿੱਚ ਕਦੇ ਨਾ ਪਾਓ.",
        llmOptional="ਖਾਲੀ ਛੱਡੋ ਤੇ ਬਾਅਦ ਵਿੱਚ Settings ਵਿੱਚ ਸੈੱਟ ਕਰੋ. ਸੈੱਟਅੱਪ LLM ਤੋਂ ਬਿਨਾਂ ਪੂਰਾ ਹੁੰਦਾ ਹੈ.",
        toolsLead="ਸੈੱਟਅੱਪ ਤੋਂ ਬਾਅਦ ਤੁਸੀਂ ਇਸ ਕੰਸੋਲ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ. ਆਵਾਜ਼, ਭਾਸ਼ਾਵਾਂ ਤੇ LLM Settings ਹੇਠ ਹਨ.",
    ),
    "ne": pack(
        title="सेटअप", skip="छोड्नुहोस्", back="पछाडि", next="अर्को", done="सकियो",
        whatTitle="Klar के हो",
        whatLead="स्थानीय Assist NLU। Home Assistant उपकरण डाटाबेस रहन्छ। यो घरको ड्यासबोर्ड होइन र LLM कुराकानी इन्जिन होइन।",
        whatLocal="Klar वाक्य पार्स गर्छ। कोठा र उपकरण Home Assistant का हुन्।",
        whatConsole="Lovelace “Klar” अन्तिम Assist पालो हो। यो सतह (Klar NLU) अपरेटर कन्सोल हो: Settings, घर, ल्याब र नियम।",
        whatNoLlm="LLM लाई पाइपलाइनको कुराकानी इन्जिन नबनाउनुहोस्। आवाज र LLM Settings मा छन्।",
        modeLead="व्यक्तित्व, मोड र परिष्करण इन्जिनमा बचत हुन्छन्। Home Assistant Configure चाहिँदैन।",
        missLead="Assist च्याट, परिष्करण र प्रशिक्षक यो OpenAI-संगत एन्डपोइन्ट बाँड्छन्। Home Assistant LLM एकीकरण छैन।",
        missLlmBody="Assist च्याट, परिष्करण र प्रशिक्षक Settings मा बस्छन्, Home Assistant कुराकानी एकीकरणमा होइन।",
        missWarn="LLM लाई पाइपलाइनको Conversation engine स्लटमा कहिल्यै नराख्नुहोस्।",
        llmOptional="खाली छोड्नुहोस् र पछि Settings मा सेट गर्नुहोस्। सेटअप LLM बिना सकिन्छ।",
        toolsLead="सेटअपपछि तपाईं यस कन्सोलमा रहनुहुन्छ। आवाज, भाषा र LLM Settings मुनि छन्।",
    ),
    "sw": pack(
        title="Usanidi", skip="Ruka", back="Rudi", next="Ifuatayo", done="Imekamilika",
        whatTitle="Klar ni nini",
        whatLead="Assist NLU ya ndani. Home Assistant inabaki hifadhidata ya vifaa. Hii si dashibodi ya nyumba wala injini ya mazungumzo ya LLM.",
        whatLocal="Klar inachanganua sentensi. Home Assistant inamiliki vyumba na vifaa.",
        whatConsole="Lovelace “Klar” ni zamu ya mwisho ya Assist. Uso huu (Klar NLU) ni konsoli ya opereta: Settings, Nyumba, Lab na Kanuni.",
        whatNoLlm="Usiweke LLM kama injini ya mazungumzo ya bomba. Sauti na LLM ziko Settings.",
        modeLead="Tabia, hali na uboreshaji huhifadhiwa kwenye injini. Home Assistant Configure haihitaji.",
        missLead="Gumzo la Assist, uboreshaji na mkufunzi hushiriki sehemu hii inayolingana na OpenAI. Hakuna muunganisho wa LLM wa Home Assistant.",
        missLlmBody="Gumzo la Assist, uboreshaji na mkufunzi wanaishi Settings, si katika muunganisho wa mazungumzo wa Home Assistant.",
        missWarn="Usiweke LLM kwenye nafasi ya Conversation engine ya bomba.",
        llmOptional="Acha tupu na uweke baadaye Settings. Usanidi unakamilika bila LLM.",
        toolsLead="Baada ya usanidi unabaki kwenye konsoli hii. Sauti, lugha na LLM ziko chini ya Settings.",
    ),
}
