"""First-run wizard chrome for East European and Asian Assist locales."""

from __future__ import annotations

from lang_packs.wizard import pack

PACKS: dict[str, dict[str, str]] = {
    "cs": pack(
        title="Nastavení", skip="Přeskočit", back="Zpět", next="Další", done="Hotovo",
        whatTitle="Co je Klar",
        whatLead="Lokální Assist NLU. Home Assistant zůstává databází zařízení. Tohle není domácí nástěnka ani LLM konverzační engine.",
        whatLocal="Klar rozebere větu. Home Assistant vlastní místnosti a zařízení.",
        whatConsole="Lovelace „Klar“ je poslední Assist tah. Tato plocha (Klar NLU) je operátorská konzole: Settings, Dům, Lab a Pravidla.",
        whatNoLlm="Nedávejte LLM jako konverzační engine pipeline. Hlas a LLM jsou v Settings.",
        modeLead="Osobnost, režim a vylepšení se ukládají na engine. Home Assistant Configure je nepotřebuje.",
        missLead="Assist chat, vylepšení a trenér sdílejí tento OpenAI-kompatibilní endpoint. Žádná Home Assistant LLM integrace.",
        missLlmBody="Assist chat, vylepšení a trenér žijí v Settings, ne v Home Assistant konverzační integraci.",
        missWarn="Nikdy nedávejte LLM do slotu Conversation engine pipeline.",
        llmOptional="Nechte prázdné a nastavte později v Settings. Setup skončí bez LLM.",
        toolsLead="Po setupu zůstanete v této konzoli. Hlas, jazyky a LLM jsou pod Settings.",
    ),
    "sk": pack(
        title="Nastavenie", skip="Preskočiť", back="Späť", next="Ďalej", done="Hotovo",
        whatTitle="Čo je Klar",
        whatLead="Lokálne Assist NLU. Home Assistant zostáva databázou zariadení. Toto nie je domácí panel ani LLM konverzačný engine.",
        whatLocal="Klar rozoberie vetu. Home Assistant vlastní miestnosti a zariadenia.",
        whatConsole="Lovelace „Klar“ je posledný Assist ťah. Táto plocha (Klar NLU) je operátorská konzola: Settings, Dom, Lab a Pravidlá.",
        whatNoLlm="Nedávajte LLM ako konverzačný engine pipeline. Hlas a LLM sú v Settings.",
        modeLead="Osobnosť, režim a vylepšenie sa ukladajú na engine. Home Assistant Configure ich nepotrebuje.",
        missLead="Assist chat, vylepšenie a tréner zdieľajú tento OpenAI-kompatibilný endpoint. Žiadna Home Assistant LLM integrácia.",
        missLlmBody="Assist chat, vylepšenie a tréner žijú v Settings, nie v Home Assistant konverzačnej integrácii.",
        missWarn="Nikdy nedávajte LLM do slotu Conversation engine pipeline.",
        llmOptional="Nechajte prázdne a nastavte neskôr v Settings. Setup skončí bez LLM.",
        toolsLead="Po setupe ostávate v tejto konzole. Hlas, jazyky a LLM sú pod Settings.",
    ),
    "pl": pack(
        title="Konfiguracja", skip="Pomiń", back="Wstecz", next="Dalej", done="Gotowe",
        whatTitle="Czym jest Klar",
        whatLead="Lokalne Assist NLU. Home Assistant zostaje bazą urządzeń. To nie jest pulpit domu ani silnik rozmowy LLM.",
        whatLocal="Klar analizuje zdanie. Home Assistant posiada pokoje i urządzenia.",
        whatConsole="Lovelace „Klar” to ostatnia tura Assist. Ta powierzchnia (Klar NLU) to konsola operatora: Settings, Dom, Lab i Reguły.",
        whatNoLlm="Nie ustawiaj LLM jako silnika rozmowy w pipeline. Głos i LLM są w Settings.",
        modeLead="Osobowość, tryb i dopracowanie zapisują się na silniku. Home Assistant Configure ich nie potrzebuje.",
        missLead="Czat Assist, dopracowanie i trener dzielą ten endpoint zgodny z OpenAI. Bez integracji LLM Home Assistant.",
        missLlmBody="Czat Assist, dopracowanie i trener żyją w Settings, nie w integracji rozmowy Home Assistant.",
        missWarn="Nigdy nie wkładaj LLM w szczelinę Conversation engine pipeline.",
        llmOptional="Zostaw puste i ustaw później w Settings. Setup kończy się bez LLM.",
        toolsLead="Po setupie zostajesz w tej konsoli. Głos, języki i LLM są pod Settings.",
    ),
    "hu": pack(
        title="Beállítás", skip="Kihagy", back="Vissza", next="Tovább", done="Kész",
        whatTitle="Mi a Klar",
        whatLead="Helyi Assist NLU. A Home Assistant marad az eszközadatbázis. Ez nem háztartási panel és nem LLM beszélgetőmotor.",
        whatLocal="A Klar feldolgozza a mondatot. A Home Assistant birtokolja a szobákat és eszközöket.",
        whatConsole="A Lovelace „Klar” az utolsó Assist kör. Ez a felület (Klar NLU) az operátori konzol: Settings, Ház, Lab és Szabályok.",
        whatNoLlm="Ne tedd az LLM-et a pipeline beszélgetőmotorjának. Hang és LLM a Settingsben van.",
        modeLead="Személyiség, mód és csiszolás a motoron tárolódik. A Home Assistant Configure nem kell hozzá.",
        missLead="Az Assist csevegés, a csiszolás és a tréner osztozik ezen az OpenAI-kompatibilis végponton. Nincs Home Assistant LLM integráció.",
        missLlmBody="Az Assist csevegés, a csiszolás és a tréner a Settingsben él, nem egy Home Assistant beszélgetési integrációban.",
        missWarn="Soha ne tedd az LLM-et a pipeline Conversation engine rekeszébe.",
        llmOptional="Hagyd üresen, és állítsd később a Settingsben. A setup LLM nélkül is kész.",
        toolsLead="A setup után ebben a konzolban maradsz. Hang, nyelvek és LLM a Settings alatt van.",
    ),
    "hr": pack(
        title="Postavljanje", skip="Preskoči", back="Natrag", next="Dalje", done="Gotovo",
        whatTitle="Što je Klar",
        whatLead="Lokalni Assist NLU. Home Assistant ostaje baza uređaja. Ovo nije kućna ploča niti LLM motor razgovora.",
        whatLocal="Klar rastavlja rečenicu. Home Assistant posjeduje sobe i uređaje.",
        whatConsole="Lovelace „Klar” je zadnji Assist potez. Ova površina (Klar NLU) je operatorska konzola: Settings, Kuća, Lab i Pravila.",
        whatNoLlm="Ne stavljaj LLM kao motor razgovora u pipeline. Glas i LLM su u Settings.",
        modeLead="Osobnost, način i dorada spremaju se na engine. Home Assistant Configure ih ne treba.",
        missLead="Assist chat, dorada i trener dijele ovaj OpenAI-kompatibilan endpoint. Nema Home Assistant LLM integracije.",
        missLlmBody="Assist chat, dorada i trener žive u Settings, ne u Home Assistant integraciji razgovora.",
        missWarn="Nikad ne stavljaj LLM u slot Conversation engine pipelinea.",
        llmOptional="Ostavi prazno i postavi kasnije u Settings. Setup završava bez LLM-a.",
        toolsLead="Nakon setupa ostaješ u ovoj konzoli. Glas, jezici i LLM su pod Settings.",
    ),
    "sl": pack(
        title="Namestitev", skip="Preskoči", back="Nazaj", next="Naprej", done="Končano",
        whatTitle="Kaj je Klar",
        whatLead="Lokalni Assist NLU. Home Assistant ostane zbirka naprav. To ni hišna plošča in ne LLM pogovorni pogon.",
        whatLocal="Klar razčleni stavek. Home Assistant ima sobe in naprave.",
        whatConsole="Lovelace „Klar” je zadnji Assist korak. Ta površina (Klar NLU) je operatorska konzola: Settings, Hiša, Lab in Pravila.",
        whatNoLlm="Ne nastavi LLM kot pogovorni pogon cevovoda. Glas in LLM sta v Settings.",
        modeLead="Osebnost, način in izboljšava se shranita na pogon. Home Assistant Configure ju ne potrebuje.",
        missLead="Assist klepet, izboljšava in trener delijo to OpenAI-združljivo končno točko. Ni Home Assistant LLM integracije.",
        missLlmBody="Assist klepet, izboljšava in trener živijo v Settings, ne v Home Assistant pogovorni integraciji.",
        missWarn="Nikoli ne daj LLM v režo Conversation engine cevovoda.",
        llmOptional="Pusti prazno in nastavi pozneje v Settings. Namestitev se konča brez LLM.",
        toolsLead="Po namestitvi ostaneš v tej konzoli. Glas, jeziki in LLM so pod Settings.",
    ),
    "bg": pack(
        title="Настройка", skip="Пропусни", back="Назад", next="Напред", done="Готово",
        whatTitle="Какво е Klar",
        whatLead="Локално Assist NLU. Home Assistant остава базата с устройства. Това не е домашно табло и не е LLM разговорен двигател.",
        whatLocal="Klar разглобява изречението. Home Assistant притежава стаите и устройствата.",
        whatConsole="Lovelace „Klar“ е последният Assist ход. Тази повърхност (Klar NLU) е операторската конзола: Settings, Дом, Lab и Правила.",
        whatNoLlm="Не слагай LLM като разговорен двигател на pipeline. Гласът и LLM са в Settings.",
        modeLead="Личност, режим и доизглаждане се пазят на двигателя. Home Assistant Configure не ги трябва.",
        missLead="Assist чат, доизглаждане и треньорът споделят тази OpenAI-съвместима крайна точка. Няма Home Assistant LLM интеграция.",
        missLlmBody="Assist чат, доизглаждане и треньорът живеят в Settings, не в Home Assistant разговорна интеграция.",
        missWarn="Никога не слагай LLM в слота Conversation engine на pipeline.",
        llmOptional="Остави празно и задай по-късно в Settings. Настройката свършва без LLM.",
        toolsLead="След настройката оставаш в тази конзола. Глас, езици и LLM са под Settings.",
    ),
    "sr": pack(
        title="Подешавање", skip="Прескочи", back="Назад", next="Даље", done="Готово",
        whatTitle="Шта је Klar",
        whatLead="Локални Assist NLU. Home Assistant остаје база уређаја. Ово није кућна табла ни LLM мотор разговора.",
        whatLocal="Klar раставља реченицу. Home Assistant поседује собе и уређаје.",
        whatConsole="Lovelace „Klar” је последњи Assist потез. Ова површина (Klar NLU) је операторска конзола: Settings, Кућа, Lab и Правила.",
        whatNoLlm="Не стављај LLM као мотор разговора у pipeline. Глас и LLM су у Settings.",
        modeLead="Личност, режим и дотеравање се чувају на енџину. Home Assistant Configure их не треба.",
        missLead="Assist ћаскање, дотеравање и тренер деле овај OpenAI-компатибилан endpoint. Нема Home Assistant LLM интеграције.",
        missLlmBody="Assist ћаскање, дотеравање и тренер живе у Settings, не у Home Assistant интеграцији разговора.",
        missWarn="Никад не стављај LLM у слот Conversation engine pipeline-а.",
        llmOptional="Остави празно и постави касније у Settings. Подешавање завршава без LLM-а.",
        toolsLead="После подешавања остајеш у овој конзоли. Глас, језици и LLM су под Settings.",
    ),
    "sr-Latn": pack(
        title="Podešavanje", skip="Preskoči", back="Nazad", next="Dalje", done="Gotovo",
        whatTitle="Šta je Klar",
        whatLead="Lokalni Assist NLU. Home Assistant ostaje baza uređaja. Ovo nije kućna tabla ni LLM motor razgovora.",
        whatLocal="Klar rastavlja rečenicu. Home Assistant poseduje sobe i uređaje.",
        whatConsole="Lovelace „Klar” je poslednji Assist potez. Ova površina (Klar NLU) je operatorska konzola: Settings, Kuća, Lab i Pravila.",
        whatNoLlm="Ne stavljaj LLM kao motor razgovora u pipeline. Glas i LLM su u Settings.",
        modeLead="Ličnost, režim i doteravanje se čuvaju na engine. Home Assistant Configure ih ne treba.",
        missLead="Assist ćaskanje, doteravanje i trener dele ovaj OpenAI-kompatibilan endpoint. Nema Home Assistant LLM integracije.",
        missLlmBody="Assist ćaskanje, doteravanje i trener žive u Settings, ne u Home Assistant integraciji razgovora.",
        missWarn="Nikad ne stavljaj LLM u slot Conversation engine pipeline-a.",
        llmOptional="Ostavi prazno i postavi kasnije u Settings. Podešavanje završava bez LLM-a.",
        toolsLead="Posle podešavanja ostaješ u ovoj konzoli. Glas, jezici i LLM su pod Settings.",
    ),
    "uk": pack(
        title="Налаштування", skip="Пропустити", back="Назад", next="Далі", done="Готово",
        whatTitle="Що таке Klar",
        whatLead="Локальний Assist NLU. Home Assistant лишається базою пристроїв. Це не домашня панель і не LLM рушій розмови.",
        whatLocal="Klar розбирає речення. Home Assistant володіє кімнатами й пристроями.",
        whatConsole="Lovelace «Klar» — останній хід Assist. Ця поверхня (Klar NLU) — консоль оператора: Settings, Дім, Lab і Правила.",
        whatNoLlm="Не став LLM як рушій розмови в pipeline. Голос і LLM у Settings.",
        modeLead="Особистість, режим і доопрацювання зберігаються на рушії. Home Assistant Configure їх не потребує.",
        missLead="Assist-чат, доопрацювання й тренер ділять цей OpenAI-сумісний endpoint. Немає інтеграції LLM Home Assistant.",
        missLlmBody="Assist-чат, доопрацювання й тренер живуть у Settings, не в інтеграції розмови Home Assistant.",
        missWarn="Ніколи не клади LLM у слот Conversation engine pipeline.",
        llmOptional="Залиш порожнім і задай пізніше в Settings. Налаштування завершується без LLM.",
        toolsLead="Після налаштування лишаєшся в цій консолі. Голос, мови й LLM — під Settings.",
    ),
    "zh-CN": pack(
        title="设置", skip="跳过", back="上一步", next="下一步", done="完成",
        whatTitle="Klar 是什么",
        whatLead="本地 Assist NLU。Home Assistant 仍是设备库。这不是家庭仪表盘，也不是 LLM 对话引擎。",
        whatLocal="Klar 解析句子。Home Assistant 拥有房间和设备。",
        whatConsole="Lovelace「Klar」是最后一轮 Assist。这个界面（Klar NLU）是操作控制台：Settings、房屋、实验室和规则。",
        whatNoLlm="不要把 LLM 设为管道对话引擎。语音和 LLM 在 Settings。",
        modeLead="个性、模式和润色存在引擎上。Home Assistant 配置不需要它们。",
        missLead="Assist 聊天、润色和训练器共用这个 OpenAI 兼容端点。不需要 Home Assistant LLM 集成。",
        missLlmBody="Assist 聊天、润色和训练器在 Settings，不在 Home Assistant 对话集成里。",
        missWarn="绝不要把 LLM 放进管道的 Conversation engine 槽。",
        llmOptional="先留空，稍后在 Settings 设置。没有 LLM 也能完成安装。",
        toolsLead="安装后留在这个控制台。语音、语言和 LLM 在 Settings。",
    ),
    "zh-TW": pack(
        title="設定", skip="跳過", back="上一步", next="下一步", done="完成",
        whatTitle="Klar 是什麼",
        whatLead="本機 Assist NLU。Home Assistant 仍是裝置庫。這不是家庭儀表板，也不是 LLM 對話引擎。",
        whatLocal="Klar 解析句子。Home Assistant 擁有房間和裝置。",
        whatConsole="Lovelace「Klar」是最後一輪 Assist。這個介面（Klar NLU）是操作控制台：Settings、房屋、實驗室和規則。",
        whatNoLlm="不要把 LLM 設為管線對話引擎。語音和 LLM 在 Settings。",
        modeLead="個性、模式和潤色存在引擎上。Home Assistant 設定不需要它們。",
        missLead="Assist 聊天、潤色和訓練器共用這個 OpenAI 相容端點。不需要 Home Assistant LLM 整合。",
        missLlmBody="Assist 聊天、潤色和訓練器在 Settings，不在 Home Assistant 對話整合裡。",
        missWarn="絕不要把 LLM 放進管線的 Conversation engine 槽。",
        llmOptional="先留空，稍後在 Settings 設定。沒有 LLM 也能完成安裝。",
        toolsLead="安裝後留在這個控制台。語音、語言和 LLM 在 Settings。",
    ),
    "zh-HK": pack(
        title="設定", skip="跳過", back="上一步", next="下一步", done="完成",
        whatTitle="Klar 係咩",
        whatLead="本機 Assist NLU。Home Assistant 仍然係裝置庫。呢個唔係家庭儀表板，亦唔係 LLM 對話引擎。",
        whatLocal="Klar 解析句子。Home Assistant 擁有房間同裝置。",
        whatConsole="Lovelace「Klar」係最後一輪 Assist。呢個介面（Klar NLU）係操作控制台：Settings、房屋、實驗室同規則。",
        whatNoLlm="唔好將 LLM 設做管線對話引擎。語音同 LLM 喺 Settings。",
        modeLead="個性、模式同潤色存在引擎度。Home Assistant 設定唔使佢哋。",
        missLead="Assist 傾偈、潤色同訓練器共用呢個 OpenAI 相容端點。唔使 Home Assistant LLM 整合。",
        missLlmBody="Assist 傾偈、潤色同訓練器喺 Settings，唔喺 Home Assistant 對話整合。",
        missWarn="千萬唔好將 LLM 放入管線 Conversation engine 槽。",
        llmOptional="留空，之後喺 Settings 設定。冇 LLM 都可以完成安裝。",
        toolsLead="安裝之後留喺呢個控制台。語音、語言同 LLM 喺 Settings。",
    ),
    "ja": pack(
        title="セットアップ", skip="スキップ", back="戻る", next="次へ", done="完了",
        whatTitle="Klar とは",
        whatLead="ローカル Assist NLU。Home Assistant が機器データベースのままです。家庭ダッシュボードでも LLM 会話エンジンでもありません。",
        whatLocal="Klar が文を解析します。部屋と機器は Home Assistant のものです。",
        whatConsole="Lovelace「Klar」は最後の Assist ターンです。この画面（Klar NLU）が操作コンソール：Settings、家、ラボ、ルール。",
        whatNoLlm="パイプラインの会話エンジンに LLM を置かないでください。声と LLM は Settings にあります。",
        modeLead="個性・モード・リファインはエンジンに保存します。Home Assistant の設定は不要です。",
        missLead="Assist チャット、リファイン、トレーナーはこの OpenAI 互換エンドポイントを共有します。Home Assistant の LLM 統合は不要です。",
        missLlmBody="Assist チャット、リファイン、トレーナーは Settings にあり、Home Assistant の会話統合にはありません。",
        missWarn="パイプラインの Conversation engine 枠に LLM を入れないでください。",
        llmOptional="空のままで、あとで Settings で設定できます。LLM なしでもセットアップは終わります。",
        toolsLead="セットアップ後もこのコンソールにいます。声・言語・LLM は Settings にあります。",
    ),
    "ko": pack(
        title="설정", skip="건너뛰기", back="뒤로", next="다음", done="완료",
        whatTitle="Klar란",
        whatLead="로컬 Assist NLU. Home Assistant가 기기 데이터베이스로 남습니다. 가정 대시보드도 LLM 대화 엔진도 아닙니다.",
        whatLocal="Klar가 문장을 분석합니다. 방과 기기는 Home Assistant 소유입니다.",
        whatConsole="Lovelace “Klar”는 마지막 Assist 턴입니다. 이 화면(Klar NLU)이 운영 콘솔입니다: Settings, 집, 랩, 규칙.",
        whatNoLlm="파이프라인 대화 엔진으로 LLM을 두지 마세요. 음성과 LLM은 Settings에 있습니다.",
        modeLead="성격, 모드, 다듬기는 엔진에 저장됩니다. Home Assistant 구성은 필요 없습니다.",
        missLead="Assist 채팅, 다듬기, 트레이너가 이 OpenAI 호환 엔드포인트를 공유합니다. Home Assistant LLM 통합은 없습니다.",
        missLlmBody="Assist 채팅, 다듬기, 트레이너는 Settings에 있으며 Home Assistant 대화 통합에 있지 않습니다.",
        missWarn="파이프라인 Conversation engine 칸에 LLM을 넣지 마세요.",
        llmOptional="비워 두고 나중에 Settings에서 설정하세요. LLM 없이도 설정이 끝납니다.",
        toolsLead="설정 후에도 이 콘솔에 머뭅니다. 음성, 언어, LLM은 Settings에 있습니다.",
    ),
    "th": pack(
        title="ตั้งค่า", skip="ข้าม", back="ย้อนกลับ", next="ถัดไป", done="เสร็จ",
        whatTitle="Klar คืออะไร",
        whatLead="Assist NLU ในเครื่อง Home Assistant ยังเป็นฐานข้อมูลอุปกรณ์ นี่ไม่ใช่แดชบอร์ดบ้านและไม่ใช่เอนจินสนทนา LLM",
        whatLocal="Klar แยกประโยค Home Assistant เป็นเจ้าของห้องและอุปกรณ์",
        whatConsole="Lovelace “Klar” คือตา Assist สุดท้าย พื้นผิวนี้ (Klar NLU) คือคอนโซลผู้ปฏิบัติ: Settings บ้าน แล็บ และกฎ",
        whatNoLlm="อย่าตั้ง LLM เป็นเอนจินสนทนาของไปป์ไลน์ เสียงและ LLM อยู่ใน Settings",
        modeLead="บุคลิก โหมด และการขัดเกลาเก็บบนเอนจิน Home Assistant Configure ไม่ต้องใช้",
        missLead="แชท Assist การขัดเกลา และเทรนเนอร์ใช้เอนด์พอยต์ที่เข้ากันกับ OpenAI นี้ ไม่มีการรวม LLM ของ Home Assistant",
        missLlmBody="แชท Assist การขัดเกลา และเทรนเนอร์อยู่ใน Settings ไม่ได้อยู่ในการรวมสนทนาของ Home Assistant",
        missWarn="อย่าใส่ LLM ในช่อง Conversation engine ของไปป์ไลน์",
        llmOptional="เว้นว่างแล้วตั้งทีหลังใน Settings การติดตั้งจบได้โดยไม่มี LLM",
        toolsLead="หลังติดตั้งคุณอยู่ในคอนโซลนี้ เสียง ภาษา และ LLM อยู่ใต้ Settings",
    ),
    "vi": pack(
        title="Cài đặt", skip="Bỏ qua", back="Quay lại", next="Tiếp", done="Xong",
        whatTitle="Klar là gì",
        whatLead="NLU Assist tại chỗ. Home Assistant vẫn là cơ sở thiết bị. Đây không phải bảng nhà và không phải động cơ hội thoại LLM.",
        whatLocal="Klar phân tích câu. Home Assistant sở hữu phòng và thiết bị.",
        whatConsole="Lovelace “Klar” là lượt Assist cuối. Bề mặt này (Klar NLU) là bảng điều khiển vận hành: Settings, Nhà, Lab và Quy tắc.",
        whatNoLlm="Đừng đặt LLM làm động cơ hội thoại của pipeline. Giọng và LLM nằm trong Settings.",
        modeLead="Tính cách, chế độ và tinh chỉnh lưu trên engine. Home Assistant Configure không cần chúng.",
        missLead="Chat Assist, tinh chỉnh và trainer dùng chung endpoint tương thích OpenAI này. Không có tích hợp LLM Home Assistant.",
        missLlmBody="Chat Assist, tinh chỉnh và trainer sống trong Settings, không trong tích hợp hội thoại Home Assistant.",
        missWarn="Đừng bao giờ đặt LLM vào ô Conversation engine của pipeline.",
        llmOptional="Để trống và đặt sau trong Settings. Cài đặt xong mà không cần LLM.",
        toolsLead="Sau cài đặt bạn ở lại bảng này. Giọng, ngôn ngữ và LLM nằm dưới Settings.",
    ),
    "id": pack(
        title="Penyiapan", skip="Lewati", back="Kembali", next="Berikutnya", done="Selesai",
        whatTitle="Apa itu Klar",
        whatLead="NLU Assist lokal. Home Assistant tetap basis data perangkat. Ini bukan dasbor rumah dan bukan mesin percakapan LLM.",
        whatLocal="Klar mengurai kalimat. Home Assistant memiliki ruangan dan perangkat.",
        whatConsole="Lovelace “Klar” adalah giliran Assist terakhir. Permukaan ini (Klar NLU) adalah konsol operator: Settings, Rumah, Lab, dan Aturan.",
        whatNoLlm="Jangan setel LLM sebagai mesin percakapan pipeline. Suara dan LLM ada di Settings.",
        modeLead="Kepribadian, mode, dan penghalusan disimpan di mesin. Home Assistant Configure tidak membutuhkannya.",
        missLead="Obrolan Assist, penghalusan, dan pelatih berbagi endpoint kompatibel OpenAI ini. Tidak ada integrasi LLM Home Assistant.",
        missLlmBody="Obrolan Assist, penghalusan, dan pelatih hidup di Settings, bukan di integrasi percakapan Home Assistant.",
        missWarn="Jangan pernah taruh LLM di slot Conversation engine pipeline.",
        llmOptional="Biarkan kosong dan atur nanti di Settings. Penyiapan selesai tanpa LLM.",
        toolsLead="Setelah penyiapan Anda tetap di konsol ini. Suara, bahasa, dan LLM ada di Settings.",
    ),
    "ms": pack(
        title="Persediaan", skip="Langkau", back="Kembali", next="Seterusnya", done="Selesai",
        whatTitle="Apa itu Klar",
        whatLead="NLU Assist setempat. Home Assistant kekal pangkalan peranti. Ini bukan papan pemuka rumah dan bukan enjin perbualan LLM.",
        whatLocal="Klar menghurai ayat. Home Assistant memiliki bilik dan peranti.",
        whatConsole="Lovelace “Klar” ialah pusingan Assist terakhir. Permukaan ini (Klar NLU) ialah konsol pengendali: Settings, Rumah, Lab dan Peraturan.",
        whatNoLlm="Jangan tetapkan LLM sebagai enjin perbualan saluran paip. Suara dan LLM ada dalam Settings.",
        modeLead="Personaliti, mod dan penambahbaikan disimpan pada enjin. Home Assistant Configure tidak memerlukannya.",
        missLead="Sembang Assist, penambahbaikan dan jurulatih berkongsi titik hujung serasi OpenAI ini. Tiada integrasi LLM Home Assistant.",
        missLlmBody="Sembang Assist, penambahbaikan dan jurulatih tinggal dalam Settings, bukan dalam integrasi perbualan Home Assistant.",
        missWarn="Jangan letak LLM dalam slot Conversation engine saluran paip.",
        llmOptional="Biarkan kosong dan tetapkan kemudian dalam Settings. Persediaan tamat tanpa LLM.",
        toolsLead="Selepas persediaan anda kekal dalam konsol ini. Suara, bahasa dan LLM di bawah Settings.",
    ),
    "mn": pack(
        title="Тохиргоо", skip="Алгасах", back="Буцах", next="Дараах", done="Дууссан",
        whatTitle="Klar гэж юу вэ",
        whatLead="Орон нутгийн Assist NLU. Home Assistant төхөөрөмжийн өгөгдлийн сан хэвээр. Энэ нь гэрийн самбар биш, LLM ярианы хөдөлгүүр биш.",
        whatLocal="Klar өгүүлбэрийг задлана. Home Assistant өрөө, төхөөрөмжийг эзэмшинэ.",
        whatConsole="Lovelace „Klar“ бол Assist-ийн сүүлийн ээлж. Энэ гадаргуу (Klar NLU) нь операторын консол: Settings, Гэр, Lab, Дүрэм.",
        whatNoLlm="LLM-ийг pipeline-ийн ярианы хөдөлгүүр болгож бүү тавь. Дуу болон LLM Settings-д байна.",
        modeLead="Зан чанар, горим, засвар хөдөлгүүрт хадгалагдана. Home Assistant Configure хэрэггүй.",
        missLead="Assist чат, засвар, дасгалжуулагч энэ OpenAI нийцтэй төгсгөлийг хуваалцана. Home Assistant LLM интеграци байхгүй.",
        missLlmBody="Assist чат, засвар, дасгалжуулагч Settings-д амьдарна, Home Assistant ярианы интеграцид биш.",
        missWarn="LLM-ийг pipeline-ийн Conversation engine нүдэнд хэзээ ч бүү хий.",
        llmOptional="Хоосон орхиод дараа Settings-д тохируул. Тохиргоо LLMгүйгээр дуусна.",
        toolsLead="Тохиргооны дараа энэ консолд үлдэнэ. Дуу, хэл, LLM Settings-д байна.",
    ),
}
