"""First-run wizard chrome for West European Assist locales."""

from __future__ import annotations

from lang_packs.wizard import pack

PACKS: dict[str, dict[str, str]] = {
    "fr": pack(
        title="Installation", skip="Passer", back="Retour", next="Suivant", done="Terminé",
        stepOf="Étape {n} sur {total}", close="Fermer", detected="Détecté", recommended="Recommandé",
        whatTitle="Ce qu’est Klar",
        whatLead="NLU Assist locale. Home Assistant reste la base des appareils. Ce n’est pas un tableau de bord du foyer ni un moteur de conversation LLM.",
        whatLocal="Klar analyse la phrase. Home Assistant possède les pièces et les appareils.",
        whatConsole="Lovelace « Klar » est le dernier tour Assist. Cette surface (Klar NLU) est la console opérateur : Settings, Maison, Labo et Règles.",
        whatNoLlm="Ne mettez pas un LLM comme moteur de conversation du pipeline. Voix et LLM sont dans Settings.",
        pathTitle="Chemin d’installation", pathLead="Un hôte moteur. Intégration pour Assist. App ou Docker pour cette UI.",
        pathShared="N’exécutez pas l’App et le moteur inclus ensemble. Les deux n’améliorent pas l’analyse.",
        modeTitle="Voix",
        modeLead="Personnalité, mode et raffinage sont stockés sur le moteur. Home Assistant Configure n’en a pas besoin.",
        missTitle="LLM du moteur",
        missLead="Le chat Assist, le raffinage et le trainer partagent cet endpoint compatible OpenAI. Pas d’intégration LLM Home Assistant.",
        missLlmBody="Le chat Assist, le raffinage et le trainer sont dans Settings, pas dans une intégration conversation Home Assistant.",
        missWarn="Ne jamais mettre le LLM dans le créneau Conversation-Engine du pipeline.",
        llmOptional="Laissez vide et réglez plus tard dans Settings. L’installation se termine sans LLM.",
        toolsLead="Après l’installation vous restez dans cette console. Voix, langues et LLM sont sous Settings.",
        phrasesMapping="{count} appareils sans pièce sûre — ensuite Maison → Attribution.",
        phrasesReopen="Rouvrir cette installation depuis Settings. Ce n’est pas un septième onglet.",
        phraseSay="Dire", phraseExpect="Attendu",
    ),
    "nl": pack(
        title="Installatie", skip="Overslaan", back="Terug", next="Volgende", done="Klaar",
        stepOf="Stap {n} van {total}", close="Sluiten", detected="Herkend", recommended="Aanbevolen",
        whatTitle="Wat Klar is",
        whatLead="Lokale Assist-NLU. Home Assistant blijft de apparaatdatabase. Dit is geen huishouddashboard en geen LLM-conversatiemotor.",
        whatLocal="Klar ontleedt de zin. Home Assistant bezit kamers en apparaten.",
        whatConsole="Lovelace „Klar” is de laatste Assist-beurt. Dit oppervlak (Klar NLU) is de operatorconsole: Settings, Huis, Lab en Regels.",
        whatNoLlm="Zet geen LLM als conversation-engine in de pipeline. Stem en LLM staan onder Settings.",
        pathTitle="Installatiepad",
        modeTitle="Stem",
        modeLead="Persoonlijkheid, modus en verfijning staan op de engine. Home Assistant Configure heeft ze niet nodig.",
        missTitle="Engine-LLM",
        missLead="Assist-chat, verfijning en de trainer delen dit OpenAI-compatibele endpoint. Geen Home Assistant-LLM-integratie.",
        missLlmBody="Assist-chat, verfijning en de trainer staan in Settings, niet in een Home Assistant-conversatie-integratie.",
        missWarn="Zet de LLM nooit in het Conversation-engine-vak van de pipeline.",
        llmOptional="Leeg laten en later in Settings zetten. Setup gaat door zonder LLM.",
        toolsLead="Na setup blijf je in deze console. Stem, talen en LLM staan onder Settings.",
        phraseSay="Zeg", phraseExpect="Verwacht",
    ),
    "es": pack(
        title="Instalación", skip="Saltar", back="Atrás", next="Siguiente", done="Listo",
        stepOf="Paso {n} de {total}", close="Cerrar", detected="Detectado", recommended="Recomendado",
        whatTitle="Qué es Klar",
        whatLead="NLU Assist local. Home Assistant sigue siendo la base de dispositivos. Esto no es un panel del hogar ni un motor de conversación LLM.",
        whatLocal="Klar analiza la frase. Home Assistant posee habitaciones y dispositivos.",
        whatConsole="Lovelace «Klar» es el último turno Assist. Esta superficie (Klar NLU) es la consola de operador: Settings, Casa, Lab y Reglas.",
        whatNoLlm="No pongas un LLM como motor de conversación del pipeline. Voz y LLM están en Settings.",
        modeTitle="Voz",
        modeLead="Personalidad, modo y refine se guardan en el motor. Home Assistant Configure no los necesita.",
        missTitle="LLM del motor",
        missLead="El chat Assist, refine y el trainer comparten este endpoint compatible con OpenAI. Sin integración LLM de Home Assistant.",
        missLlmBody="El chat Assist, refine y el trainer viven en Settings, no en una integración de conversación de Home Assistant.",
        missWarn="Nunca pongas el LLM en la ranura Conversation engine del pipeline.",
        llmOptional="Déjalo vacío y configúralo luego en Settings. El setup termina sin LLM.",
        toolsLead="Tras el setup te quedas en esta consola. Voz, idiomas y LLM están en Settings.",
        phraseSay="Decir", phraseExpect="Esperado",
    ),
    "it": pack(
        title="Installazione", skip="Salta", back="Indietro", next="Avanti", done="Fatto",
        stepOf="Passo {n} di {total}", close="Chiudi", detected="Rilevato", recommended="Consigliato",
        whatTitle="Cos’è Klar",
        whatLead="NLU Assist locale. Home Assistant resta il database dei dispositivi. Questa non è una dashboard della casa né un motore di conversazione LLM.",
        whatLocal="Klar analizza la frase. Home Assistant possiede stanze e dispositivi.",
        whatConsole="Lovelace «Klar» è l’ultimo turno Assist. Questa superficie (Klar NLU) è la console operatore: Settings, Casa, Lab e Regole.",
        whatNoLlm="Non impostare un LLM come motore di conversazione della pipeline. Voce e LLM stanno in Settings.",
        modeTitle="Voce",
        modeLead="Personalità, modalità e refine sono sul motore. Home Assistant Configure non ne ha bisogno.",
        missTitle="LLM del motore",
        missLead="Chat Assist, refine e trainer condividono questo endpoint compatibile OpenAI. Nessuna integrazione LLM Home Assistant.",
        missLlmBody="Chat Assist, refine e trainer stanno in Settings, non in un’integrazione conversazione Home Assistant.",
        missWarn="Non mettere mai l'LLM nello slot Conversation engine della pipeline.",
        llmOptional="Lascia vuoto e impostalo dopo in Settings. Il setup finisce senza LLM.",
        toolsLead="Dopo il setup resti in questa console. Voce, lingue e LLM sono sotto Settings.",
        phraseSay="Dire", phraseExpect="Atteso",
    ),
    "pt": pack(
        title="Instalação", skip="Saltar", back="Voltar", next="Seguinte", done="Concluído",
        stepOf="Passo {n} de {total}", close="Fechar", detected="Detetado", recommended="Recomendado",
        whatTitle="O que é o Klar",
        whatLead="NLU Assist local. O Home Assistant continua a base de dispositivos. Isto não é um painel da casa nem um motor de conversa LLM.",
        whatLocal="O Klar analisa a frase. O Home Assistant possui divisões e dispositivos.",
        whatConsole="O Lovelace «Klar» é o último turno Assist. Esta superfície (Klar NLU) é a consola do operador: Settings, Casa, Lab e Regras.",
        whatNoLlm="Não ponhas um LLM como motor de conversa do pipeline. Voz e LLM estão em Settings.",
        modeTitle="Voz",
        modeLead="Personalidade, modo e refine ficam no motor. O Home Assistant Configure não precisa deles.",
        missTitle="LLM do motor",
        missLead="Chat Assist, refine e trainer partilham este endpoint compatível OpenAI. Sem integração LLM do Home Assistant.",
        missLlmBody="Chat Assist, refine e trainer ficam em Settings, não numa integração de conversa do Home Assistant.",
        missWarn="Nunca ponhas o LLM na ranhura Conversation engine do pipeline.",
        llmOptional="Deixa vazio e define depois em Settings. A instalação acaba sem LLM.",
        toolsLead="Depois da instalação ficas nesta consola. Voz, línguas e LLM estão em Settings.",
        phraseSay="Dizer", phraseExpect="Esperado",
    ),
    "ca": pack(
        title="Instal·lació", skip="Omet", back="Enrere", next="Següent", done="Fet",
        stepOf="Pas {n} de {total}", close="Tanca", detected="Detectat", recommended="Recomanat",
        whatTitle="Què és Klar",
        whatLead="NLU Assist local. Home Assistant continua sent la base de dispositius. Això no és un tauler de la llar ni un motor de conversa LLM.",
        whatLocal="Klar analitza la frase. Home Assistant té les habitacions i els dispositius.",
        whatConsole="Lovelace «Klar» és l’últim torn Assist. Aquesta superfície (Klar NLU) és la consola d’operador: Settings, Casa, Lab i Regles.",
        whatNoLlm="No posis un LLM com a motor de conversa del pipeline. Veu i LLM són a Settings.",
        modeLead="Personalitat, mode i refine es desen al motor. Home Assistant Configure no els necessita.",
        missLead="El xat Assist, refine i el trainer comparteixen aquest endpoint compatible OpenAI. Sense integració LLM de Home Assistant.",
        missLlmBody="El xat Assist, refine i el trainer viuen a Settings, no en una integració de conversa de Home Assistant.",
        missWarn="No posis mai l'LLM a la ranura Conversation engine del pipeline.",
        llmOptional="Deixa-ho buit i configura-ho després a Settings. El setup acaba sense LLM.",
        toolsLead="Després del setup et quedes en aquesta consola. Veu, llengües i LLM són a Settings.",
    ),
    "ro": pack(
        title="Instalare", skip="Sari", back="Înapoi", next="Următorul", done="Gata",
        stepOf="Pasul {n} din {total}", close="Închide", detected="Detectat", recommended="Recomandat",
        whatTitle="Ce este Klar",
        whatLead="NLU Assist local. Home Assistant rămâne baza de dispozitive. Aceasta nu e o consolă a casei și nu e un motor de conversație LLM.",
        whatLocal="Klar analizează propoziția. Home Assistant deține camerele și dispozitivele.",
        whatConsole="Lovelace „Klar” este ultimul tur Assist. Această suprafață (Klar NLU) este consola operator: Settings, Casă, Lab și Reguli.",
        whatNoLlm="Nu pune un LLM ca motor de conversație în pipeline. Vocea și LLM-ul stau în Settings.",
        modeLead="Personalitatea, modul și refine sunt pe motor. Home Assistant Configure nu are nevoie de ele.",
        missLead="Chat Assist, refine și trainer împart acest endpoint compatibil OpenAI. Fără integrare LLM Home Assistant.",
        missLlmBody="Chat Assist, refine și trainer stau în Settings, nu într-o integrare de conversație Home Assistant.",
        missWarn="Nu pune niciodată LLM-ul în slotul Conversation engine al pipeline-ului.",
        llmOptional="Lasă gol și setează mai târziu în Settings. Setup-ul se termină fără LLM.",
        toolsLead="După setup rămâi în această consolă. Voce, limbi și LLM sunt sub Settings.",
    ),
    "pt-BR": pack(
        title="Instalação", skip="Pular", back="Voltar", next="Avançar", done="Concluído",
        stepOf="Passo {n} de {total}", close="Fechar", detected="Detectado", recommended="Recomendado",
        whatTitle="O que é o Klar",
        whatLead="NLU Assist local. O Home Assistant continua o banco de dispositivos. Isto não é um painel da casa nem um motor de conversa LLM.",
        whatLocal="O Klar analisa a frase. O Home Assistant possui cômodos e dispositivos.",
        whatConsole="O Lovelace “Klar” é o último turno Assist. Esta superfície (Klar NLU) é o console do operador: Settings, Casa, Lab e Regras.",
        whatNoLlm="Não coloque um LLM como motor de conversa do pipeline. Voz e LLM ficam em Settings.",
        modeLead="Personalidade, modo e refine ficam no motor. O Home Assistant Configure não precisa deles.",
        missLead="Chat Assist, refine e trainer compartilham este endpoint compatível OpenAI. Sem integração LLM do Home Assistant.",
        missLlmBody="Chat Assist, refine e trainer ficam em Settings, não numa integração de conversa do Home Assistant.",
        missWarn="Nunca coloque o LLM na fenda Conversation engine do pipeline.",
        llmOptional="Deixe vazio e configure depois em Settings. A instalação termina sem LLM.",
        toolsLead="Depois da instalação você fica neste console. Voz, idiomas e LLM estão em Settings.",
    ),
    "gl": pack(
        title="Instalación", skip="Saltar", back="Atrás", next="Seguinte", done="Feito",
        stepOf="Paso {n} de {total}", close="Pechar", detected="Detectado", recommended="Recomendado",
        whatTitle="Que é Klar",
        whatLead="NLU Assist local. Home Assistant segue sendo a base de dispositivos. Isto non é un panel da casa nin un motor de conversa LLM.",
        whatLocal="Klar analiza a frase. Home Assistant ten as habitacións e os dispositivos.",
        whatConsole="Lovelace «Klar» é o último turno Assist. Esta superficie (Klar NLU) é a consola de operador: Settings, Casa, Lab e Regras.",
        whatNoLlm="Non poñas un LLM como motor de conversa do pipeline. Voz e LLM están en Settings.",
        modeLead="Personalidade, modo e refine gárdanse no motor. Home Assistant Configure non os precisa.",
        missLead="O chat Assist, refine e o trainer compartillen este endpoint compatible OpenAI. Sen integración LLM de Home Assistant.",
        missLlmBody="O chat Assist, refine e o trainer viven en Settings, non nunha integración de conversa de Home Assistant.",
        missWarn="Nunca poñas o LLM na rañura Conversation engine do pipeline.",
        llmOptional="Déixao baleiro e configúrao despois en Settings. O setup remata sen LLM.",
        toolsLead="Despois do setup quedas nesta consola. Voz, linguas e LLM están en Settings.",
    ),
    "de-CH": pack(
        title="Setup", skip="Überspringe", back="Zrugg", next="Wyter", done="Fertig",
        stepOf="Schritt {n} vo {total}", close="Schliisse", detected="Erkännt", recommended="Empfohle",
        whatTitle="Was Klar isch",
        whatLead="Lokali Assist-NLU. Home Assistant bliibt d Gerätedatebank. Das isch kei Huushaltszentrale und kei LLM-Conversation-Engine.",
        whatLocal="Klar zerleit de Satz. Home Assistant het Rüüm und Grät.",
        whatConsole="Lovelace „Klar“ isch de letscht Assist-Zug. Die Oberflächi (Klar NLU) isch d Operator-Konsole: Settings, Huus, Labor und Regle.",
        whatNoLlm="De LLM-Agent nöd als Conversation-Engine i d Pipeline setze. Stimm und LLM ligged under Settings.",
        pathTitle="Installationswäg",
        modeTitle="Stimm",
        modeLead="Persönlichkeit, Modus und Refine werded uf de Engine gspeicheret. Home Assistant Configure brucht das nöd.",
        missTitle="LLM vo de Engine",
        missLead="Assist-Chat, Refine und Trainer nüzet de gliich OpenAI-kompatibel Endpunkt. Kei HA-LLM-Integration.",
        missLlmBody="Assist-Chat, Refine und Trainer ligged i Settings, nöd i ere Home-Assistant-Conversation-Integration.",
        missWarn="LLM nie i de Slot „Conversation-Engine“ vo de Pipeline.",
        llmOptional="Leer loh und spöter i Settings setze. Setup chunnt ohni LLM dür.",
        toolsLead="Nach em Setup bliibed ihr i dere Konsole. Stimm, Sproche und LLM ligged under Settings.",
        phraseSay="Säge", phraseExpect="Erwartig",
    ),
    "de-AT": pack(
        title="Setup", skip="Überspringen", back="Zurück", next="Weiter", done="Fertig",
        stepOf="Schritt {n} von {total}", close="Schließen", detected="Erkannt", recommended="Empfohlen",
        whatTitle="Was Klar ist",
        whatLead="Lokale Assist-NLU. Home Assistant bleibt die Gerätedatenbank. Das hier ist keine Haushaltszentrale und keine LLM-Conversation-Engine.",
        whatLocal="Klar zerlegt den Satz. Home Assistant besitzt Räume und Geräte.",
        whatConsole="Lovelace „Klar“ ist der letzte Assist-Zug. Diese Oberfläche (Klar NLU) ist die Operator-Konsole: Settings, Haus, Labor und Regeln.",
        whatNoLlm="Den LLM-Agenten nicht als Conversation-Engine in der Pipeline setzen. Stimme und LLM liegen unter Settings.",
        modeTitle="Stimme",
        modeLead="Persönlichkeit, Modus und Refine werden auf der Engine gespeichert. Home Assistant Configure braucht das nicht.",
        missTitle="LLM der Engine",
        missLead="Assist-Chat, Refine und Trainer nutzen denselben OpenAI-kompatiblen Endpunkt. Keine HA-LLM-Integration.",
        missLlmBody="Assist-Chat, Refine und Trainer liegen in Settings, nicht in einer Home-Assistant-Conversation-Integration.",
        missWarn="LLM niemals in den Slot „Conversation-Engine“ der Pipeline.",
        llmOptional="Leer lassen und später in Settings setzen. Setup kommt ohne LLM durch.",
        toolsLead="Nach dem Setup bleibt ihr in dieser Konsole. Stimme, Sprachen und LLM liegen unter Settings.",
        phraseSay="Sagen", phraseExpect="Erwartung",
    ),
    "en-GB": pack(
        whatConsole="Lovelace “Klar” is the last Assist turn. This surface (Klar NLU) is the operator console: Settings, House, Lab, and Rules.",
        missLlmBody="Assist chat, refine, and the trainer live in Settings, not in a Home Assistant conversation integration.",
        phrasesOther="German works in the same pipeline.",
    ),
    "af": pack(
        title="Opstelling", skip="Slaan oor", back="Terug", next="Volgende", done="Klaar",
        whatTitle="Wat Klar is",
        whatLead="Plaaslike Assist-NLU. Home Assistant bly die toesteldatabasis. Dit is nie ’n huishoudelike dashboard of ’n LLM-gespreksenjin nie.",
        whatLocal="Klar ontleed die sin. Home Assistant besit kamers en toestelle.",
        whatConsole="Lovelace „Klar” is die laaste Assist-beurt. Hierdie oppervlak (Klar NLU) is die operateurkonsole: Settings, Huis, Lab en Reëls.",
        whatNoLlm="Moenie ’n LLM as die pyplyn se gespreksenjin sit nie. Stem en LLM is onder Settings.",
        modeLead="Persoonlikheid, modus en verfyning word op die enjin gestoor. Home Assistant Configure het dit nie nodig nie.",
        missLead="Assist-klets, verfyning en die afrigter deel hierdie OpenAI-versoenbare eindpunt. Geen Home Assistant-LLM-integrasie nie.",
        missLlmBody="Assist-klets, verfyning en die afrigter leef in Settings, nie in ’n Home Assistant-gespreksintegrasie nie.",
        missWarn="Moet nooit die LLM in die Conversation engine-gleuf van die pyplyn sit nie.",
        llmOptional="Laat leeg en stel later in Settings. Opstelling eindig sonder ’n LLM.",
        toolsLead="Ná opstelling bly jy in hierdie konsole. Stem, tale en die LLM is onder Settings.",
    ),
    "lb": pack(
        title="Setup", skip="Iwwersprangen", back="Zréck", next="Weider", done="Fäerdeg",
        whatTitle="Wat Klar ass",
        whatLead="Lokal Assist-NLU. Home Assistant bleift d’Gerätedatebank. Dat hei ass keng Haushaltszentral an keng LLM-Conversation-Engine.",
        whatLocal="Klar zerleet de Saz. Home Assistant huet Raim an Geräter.",
        whatConsole="Lovelace „Klar“ ass de leschte Assist-Zuch. Dës Uewerfläch (Klar NLU) ass d’Operator-Konsole: Settings, Haus, Labor an Reegelen.",
        whatNoLlm="Den LLM-Agent net als Conversation-Engine an d’Pipeline setzen. Stëmm an LLM leien ënner Settings.",
        modeLead="Perséinlechkeet, Modus a Refine ginn op der Engine gespäichert. Home Assistant Configure brauch dat net.",
        missLead="Assist-Chat, Refine an Trainer notzen dee selwechten OpenAI-kompatibelen Endpunkt. Keng HA-LLM-Integratioun.",
        missLlmBody="Assist-Chat, Refine an Trainer leien a Settings, net an enger Home-Assistant-Conversation-Integratioun.",
        missWarn="LLM ni an de Slot „Conversation-Engine“ vun der Pipeline.",
        llmOptional="Eidel loossen a spéider a Settings setzen. Setup kënnt ouni LLM duerch.",
        toolsLead="Nom Setup bleift dir an dëser Konsole. Stëmm, Sproochen an LLM leien ënner Settings.",
    ),
    "cy": pack(
        title="Gosod", skip="Hepgor", back="Nôl", next="Nesaf", done="Wedi gorffen",
        whatTitle="Beth yw Klar",
        whatLead="NLU Assist leol. Mae Home Assistant yn aros yn gronfa ddata’r dyfeisiau. Nid dangosfwrdd cartref na pheiriant sgwrs LLM yw hwn.",
        whatLocal="Mae Klar yn dosrannu’r frawddeg. Mae Home Assistant yn berchen ar ystafelloedd a dyfeisiau.",
        whatConsole="Lovelace “Klar” yw’r tro Assist olaf. Y wyneb hwn (Klar NLU) yw consola’r gweithredydd: Settings, Tŷ, Lab a Rheolau.",
        whatNoLlm="Peidiwch â gosod LLM fel peiriant sgwrs y biblinell. Mae llais a’r LLM yn Settings.",
        modeLead="Mae personoliaeth, modd a mireinio yn cael eu cadw ar y peiriant. Nid oes angen Home Assistant Configure arnynt.",
        missLead="Mae sgwrs Assist, mireinio a’r hyfforddwr yn rhannu’r pwynt terfyn cydnaws OpenAI hwn. Dim integreiddiad LLM Home Assistant.",
        missLlmBody="Mae sgwrs Assist, mireinio a’r hyfforddwr yn byw yn Settings, nid mewn integreiddiad sgwrs Home Assistant.",
        missWarn="Peidiwch byth â rhoi’r LLM yn slot Conversation engine y biblinell.",
        llmOptional="Gadewch yn wag a’i osod yn nes ymlaen yn Settings. Mae’r gosodiad yn gorffen heb LLM.",
        toolsLead="Ar ôl gosod rydych yn aros yn y consola hwn. Mae llais, ieithoedd a’r LLM o dan Settings.",
    ),
    "eu": pack(
        title="Konfigurazioa", skip="Saltatu", back="Atzera", next="Hurrengoa", done="Eginda",
        whatTitle="Zer da Klar",
        whatLead="Assist NLU lokala. Home Assistant gailuen datu-basea izaten jarraitzen du. Hau ez da etxeko panela ez LLM elkarrizketa-motorra.",
        whatLocal="Klar-ek esaldia aztertzen du. Home Assistant-ek gelak eta gailuak ditu.",
        whatConsole="Lovelace «Klar» da Assist txanda azkena. Azalera hau (Klar NLU) da operadorearen kontsola: Settings, Etxea, Lab eta Arauak.",
        whatNoLlm="Ez jarri LLM-rik pipeline-aren elkarrizketa-motor gisa. Ahotsa eta LLM Settings-en daude.",
        modeLead="Nortasuna, modua eta refine motorrean gordetzen dira. Home Assistant Configure-k ez ditu behar.",
        missLead="Assist txata, refine eta trainerrek OpenAI-bateragarri den endpoint hau partekatzen dute. Ez dago Home Assistant LLM integraziorik.",
        missLlmBody="Assist txata, refine eta trainera Settings-en bizi dira, ez Home Assistant elkarrizketa-integrazio batean.",
        missWarn="Inoiz ez jarri LLM-a pipeline-aren Conversation engine zirrikituan.",
        llmOptional="Utzi hutsik eta ezarri gero Settings-en. Setup-ak LLM gabe amaitzen du.",
        toolsLead="Setup ondoren kontsola honetan geratzen zara. Ahotsa, hizkuntzak eta LLM Settings-en daude.",
    ),
    "ga": pack(
        title="Socrú", skip="Scipeáil", back="Siar", next="Ar aghaidh", done="Déanta",
        whatTitle="Cad é Klar",
        whatLead="NLU Assist áitiúil. Fanann Home Assistant mar bhunachar na ngléasanna. Ní painéal teaghlaigh ná inneall comhrá LLM é seo.",
        whatLocal="Déanann Klar anabhrú ar an abairt. Is le Home Assistant na seomraí agus na gléasanna.",
        whatConsole="Is é Lovelace “Klar” an casadh Assist deireanach. Is é an dromchla seo (Klar NLU) consól an oibreora: Settings, Teach, Lab agus Rialacha.",
        whatNoLlm="Ná cuir LLM mar inneall comhrá an phíblíne. Tá guth agus an LLM i Settings.",
        modeLead="Stóráiltear pearsantacht, mód agus mionchoigeartú ar an inneall. Níl gá le Home Assistant Configure.",
        missLead="Comhroinneann comhrá Assist, mionchoigeartú agus an traenálaí an críochphointe comhoiriúnach OpenAI seo. Gan comhtháthú LLM Home Assistant.",
        missLlmBody="Maireann comhrá Assist, mionchoigeartú agus an traenálaí i Settings, ní i gcomhtháthú comhrá Home Assistant.",
        missWarn="Ná cuir an LLM riamh i sliotán Conversation engine na píblíne.",
        llmOptional="Fág folamh agus socraigh níos déanaí i Settings. Críochnaíonn an socrú gan LLM.",
        toolsLead="Tar éis an tsocraithe fanann tú sa chonsól seo. Tá guth, teangacha agus an LLM faoi Settings.",
    ),
    "kw": pack(
        title="Settyans", skip="Lamma", back="War-dhelergh", next="Nessa", done="Gwrys",
        whatTitle="Pyth yw Klar",
        whatLead="NLU Assist leel. Home Assistant a wort an database a dhyvisyow. Nyns yw hemma dashboard chi na jynn keskows LLM.",
        whatLocal="Klar a dhibarth an lavar. Home Assistant a berth stevellow ha dyvisyow.",
        whatConsole="Lovelace “Klar” yw an tro Assist diwettha. An enep ma (Klar NLU) yw konsol an oberer: Settings, Chi, Lab ha Rewlys.",
        whatNoLlm="Na worr LLM avel jynn keskows an biblinenn. Lev ha’n LLM yw yn Settings.",
        modeLead="Personoleth, modh ha fynna yw gwithys war an jynn. Nyns yw Home Assistant Configure res.",
        missLead="Chat Assist, fynna ha’n trenyer a gevrenn an penn-hyns kesoberus OpenAI ma. Ny gemmyn kevren LLM Home Assistant.",
        missLlmBody="Chat Assist, fynna ha’n trenyer a vew yn Settings, ny yn kevren keskows Home Assistant.",
        missWarn="Na worr byth an LLM yn lagas Conversation engine an biblinenn.",
        llmOptional="Ges gwag ha sett a-wosa yn Settings. An settyans a worfen heb LLM.",
        toolsLead="Wosa settyans yth esowgh y’n konsol ma. Lev, yethow ha’n LLM yw yn-dann Settings.",
    ),
    "da": pack(
        title="Opsætning", skip="Spring over", back="Tilbage", next="Næste", done="Færdig",
        whatTitle="Hvad Klar er",
        whatLead="Lokal Assist-NLU. Home Assistant forbliver enhedsdatabasen. Dette er ikke et hustavle og ikke en LLM-samtalemotor.",
        whatLocal="Klar parser sætningen. Home Assistant ejer rum og enheder.",
        whatConsole="Lovelace „Klar“ er den sidste Assist-tur. Denne flade (Klar NLU) er operatørkonsollen: Settings, Hus, Lab og Regler.",
        whatNoLlm="Sæt ikke en LLM som pipeline-samtalemotor. Stemme og LLM ligger under Settings.",
        modeLead="Personlighed, tilstand og forfinelse gemmes på motoren. Home Assistant Configure behøver dem ikke.",
        missLead="Assist-chat, forfinelse og træneren deler dette OpenAI-kompatible endepunkt. Ingen Home Assistant-LLM-integration.",
        missLlmBody="Assist-chat, forfinelse og træneren bor i Settings, ikke i en Home Assistant-samtaleintegration.",
        missWarn="Læg aldrig LLM’en i pipeline-feltet Conversation engine.",
        llmOptional="Lad stå tomt og sæt det senere i Settings. Opsætningen slutter uden LLM.",
        toolsLead="Efter opsætning bliver du i denne konsol. Stemme, sprog og LLM er under Settings.",
    ),
    "nb": pack(
        title="Oppsett", skip="Hopp over", back="Tilbake", next="Neste", done="Ferdig",
        whatTitle="Hva Klar er",
        whatLead="Lokal Assist-NLU. Home Assistant forblir enhetsdatabasen. Dette er ikke et hustavle og ikke en LLM-samtalemotor.",
        whatLocal="Klar parser setningen. Home Assistant eier rom og enheter.",
        whatConsole="Lovelace «Klar» er den siste Assist-turen. Denne flaten (Klar NLU) er operatørkonsollen: Settings, Hus, Lab og Regler.",
        whatNoLlm="Ikke sett en LLM som samtale-motor i pipelinen. Stemme og LLM ligger under Settings.",
        modeLead="Personlighet, modus og forfining lagres på motoren. Home Assistant Configure trenger dem ikke.",
        missLead="Assist-chat, forfining og treneren deler dette OpenAI-kompatible endepunktet. Ingen Home Assistant-LLM-integrasjon.",
        missLlmBody="Assist-chat, forfining og treneren bor i Settings, ikke i en Home Assistant-samtaleintegrasjon.",
        missWarn="Aldri legg LLM-en i pipeline-feltet Conversation engine.",
        llmOptional="La stå tomt og sett det senere i Settings. Oppsettet blir ferdig uten LLM.",
        toolsLead="Etter oppsett blir du i denne konsollen. Stemme, språk og LLM er under Settings.",
    ),
    "sv": pack(
        title="Installation", skip="Hoppa över", back="Tillbaka", next="Nästa", done="Klar",
        whatTitle="Vad Klar är",
        whatLead="Lokal Assist-NLU. Home Assistant förblir enhetsdatabasen. Detta är inte en hushållspanel och inte en LLM-samtalsmotor.",
        whatLocal="Klar parsar meningen. Home Assistant äger rum och enheter.",
        whatConsole="Lovelace ”Klar” är sista Assist-turen. Den här ytan (Klar NLU) är operatörskonsolen: Settings, Hus, Lab och Regler.",
        whatNoLlm="Sätt inte en LLM som pipeline-samtalsmotor. Röst och LLM ligger under Settings.",
        modeLead="Personlighet, läge och förfining sparas på motorn. Home Assistant Configure behöver dem inte.",
        missLead="Assist-chatt, förfining och tränaren delar denna OpenAI-kompatibla endpoint. Ingen Home Assistant-LLM-integration.",
        missLlmBody="Assist-chatt, förfining och tränaren bor i Settings, inte i en Home Assistant-samtalsintegration.",
        missWarn="Lägg aldrig LLM:en i pipeline-fältet Conversation engine.",
        llmOptional="Lämna tomt och ställ in senare i Settings. Installationen blir klar utan LLM.",
        toolsLead="Efter installationen stannar du i den här konsolen. Röst, språk och LLM finns under Settings.",
    ),
    "fi": pack(
        title="Asennus", skip="Ohita", back="Takaisin", next="Seuraava", done="Valmis",
        whatTitle="Mikä Klar on",
        whatLead="Paikallinen Assist-NLU. Home Assistant pysyy laitetietokantana. Tämä ei ole kodin kojelma eikä LLM-keskustelumoottori.",
        whatLocal="Klar jäsentää lauseen. Home Assistant omistaa huoneet ja laitteet.",
        whatConsole="Lovelace „Klar” on viimeinen Assist-vuoro. Tämä pinta (Klar NLU) on operaattorikonsoli: Settings, Talo, Lab ja Säännöt.",
        whatNoLlm="Älä aseta LLM:ää putken keskustelumoottoriksi. Ääni ja LLM ovat Settingsissä.",
        modeLead="Persoonallisuus, tila ja hienosäätö tallennetaan moottoriin. Home Assistant Configure ei niitä tarvitse.",
        missLead="Assist-chat, hienosäätö ja kouluttaja jakavat tämän OpenAI-yhteensopivan päätepisteen. Ei Home Assistant -LLM-integraatiota.",
        missLlmBody="Assist-chat, hienosäätö ja kouluttaja asuvat Settingsissä, ei Home Assistant -keskusteluintograatiossa.",
        missWarn="Älä koskaan laita LLM:ää putken Conversation engine -paikkaan.",
        llmOptional="Jätä tyhjäksi ja aseta myöhemmin Settingsissä. Asennus valmistuu ilman LLM:ää.",
        toolsLead="Asennuksen jälkeen jäät tähän konsoliin. Ääni, kielet ja LLM ovat Settingsissä.",
    ),
    "is": pack(
        title="Uppsetning", skip="Sleppa", back="Til baka", next="Næsta", done="Lokið",
        whatTitle="Hvað Klar er",
        whatLead="Staðbundin Assist-NLU. Home Assistant er áfram tækjagrunnurinn. Þetta er ekki heimilisspjald né LLM-samtalsvél.",
        whatLocal="Klar þátta setninguna. Home Assistant á herbergi og tæki.",
        whatConsole="Lovelace „Klar“ er síðasta Assist-umferðin. Þetta yfirborð (Klar NLU) er stjórnandastöðin: Settings, Hús, Lab og Reglur.",
        whatNoLlm="Ekki setja LLM sem samtalsvél pípunnar. Rödd og LLM eru undir Settings.",
        modeLead="Persónuleiki, hamur og fínstilling eru geymd á vélinni. Home Assistant Configure þarf þau ekki.",
        missLead="Assist-spjall, fínstilling og þjálfarinn deila þessum OpenAI-samhæfða endapunkti. Engin Home Assistant-LLM-samþætting.",
        missLlmBody="Assist-spjall, fínstilling og þjálfarinn búa í Settings, ekki í Home Assistant-samtalssamþættingu.",
        missWarn="Settu LLM aldrei í Conversation engine-reit pípunnar.",
        llmOptional="Skildu eftir autt og stilltu síðar í Settings. Uppsetning lýkur án LLM.",
        toolsLead="Eftir uppsetningu ertu áfram í þessari stöð. Rödd, tungumál og LLM eru undir Settings.",
    ),
    "et": pack(
        title="Seadistus", skip="Jäta vahele", back="Tagasi", next="Edasi", done="Valmis",
        whatTitle="Mis Klar on",
        whatLead="Kohalik Assist-NLU. Home Assistant jääb seadmete andmebaasiks. See ei ole kodu juhtpaneel ega LLM-vestlusmootor.",
        whatLocal="Klar parsib lause. Home Assistant omab ruume ja seadmeid.",
        whatConsole="Lovelace „Klar” on viimane Assist-käik. See pind (Klar NLU) on operaatorikonsool: Settings, Maja, Lab ja Reeglid.",
        whatNoLlm="Ära sea LLM-i toru vestlusmootoriks. Hääl ja LLM on Settingsis.",
        modeLead="Isiksus, režiim ja lihvimine salvestatakse mootorisse. Home Assistant Configure neid ei vaja.",
        missLead="Assist-vestlus, lihvimine ja treener jagavad seda OpenAI-ühilduvat otspunkti. Pole Home Assistant LLM-integratsiooni.",
        missLlmBody="Assist-vestlus, lihvimine ja treener elavad Settingsis, mitte Home Assistant vestlusintegratsioonis.",
        missWarn="Ära pane LLM-i kunagi toru Conversation engine pesasse.",
        llmOptional="Jäta tühjaks ja sea hiljem Settingsis. Seadistus lõpeb ilma LLM-ita.",
        toolsLead="Pärast seadistust jääd sellesse konsooli. Hääl, keeled ja LLM on Settingsis.",
    ),
    "lt": pack(
        title="Sąranka", skip="Praleisti", back="Atgal", next="Toliau", done="Baigta",
        whatTitle="Kas yra Klar",
        whatLead="Vietinė Assist NLU. Home Assistant lieka įrenginių duomenų bazė. Tai ne namų skydelis ir ne LLM pokalbių variklis.",
        whatLocal="Klar išnagrinėja sakinį. Home Assistant valdo kambarius ir įrenginius.",
        whatConsole="Lovelace „Klar“ yra paskutinis Assist ėjimas. Šis paviršius (Klar NLU) yra operatoriaus pultas: Settings, Namai, Lab ir Taisyklės.",
        whatNoLlm="Nestatykite LLM kaip vamzdyno pokalbių variklio. Balsas ir LLM yra Settings.",
        modeLead="Asmenybė, režimas ir tobulinimas saugomi variklyje. Home Assistant Configure jų nereikia.",
        missLead="Assist pokalbis, tobulinimas ir treneris dalijasi šiuo OpenAI suderinamu galutiniu tašku. Nėra Home Assistant LLM integracijos.",
        missLlmBody="Assist pokalbis, tobulinimas ir treneris gyvena Settings, ne Home Assistant pokalbių integracijoje.",
        missWarn="Niekada nedėkite LLM į vamzdyno Conversation engine lizdą.",
        llmOptional="Palikite tuščią ir nustatykite vėliau Settings. Sąranka baigiasi be LLM.",
        toolsLead="Po sąrankos liekate šiame pulte. Balsas, kalbos ir LLM yra po Settings.",
    ),
    "lv": pack(
        title="Iestatīšana", skip="Izlaist", back="Atpakaļ", next="Tālāk", done="Gatavs",
        whatTitle="Kas ir Klar",
        whatLead="Vietējā Assist NLU. Home Assistant paliek ierīču datubāze. Šis nav mājas panelis un nav LLM sarunu dzinējs.",
        whatLocal="Klar parsē teikumu. Home Assistant pieder istabas un ierīces.",
        whatConsole="Lovelace „Klar” ir pēdējais Assist gājiens. Šī virsma (Klar NLU) ir operatora konsole: Settings, Māja, Lab un Noteikumi.",
        whatNoLlm="Nesāciet LLM kā cauruļvada sarunu dzinēju. Balss un LLM ir Settings.",
        modeLead="Personība, režīms un pilnveide tiek glabāti dzinējā. Home Assistant Configure tas nav vajadzīgs.",
        missLead="Assist tērzēšana, pilnveide un treneris dalās šajā OpenAI saderīgajā galapunktā. Nav Home Assistant LLM integrācijas.",
        missLlmBody="Assist tērzēšana, pilnveide un treneris dzīvo Settings, nevis Home Assistant sarunu integrācijā.",
        missWarn="Nekad nelieciet LLM cauruļvada Conversation engine slotā.",
        llmOptional="Atstājiet tukšu un iestatiet vēlāk Settings. Iestatīšana beidzas bez LLM.",
        toolsLead="Pēc iestatīšanas paliekat šajā konsolē. Balss, valodas un LLM ir zem Settings.",
    ),
}
